openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: accessanalyzer
  x-aws-serviceName: accessanalyzer
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2019-11-01'
  title: Access Analyzer
  description: |-
    Identity and Access Management Access Analyzer helps you to set, verify, and refine your IAM policies by providing a suite of capabilities. Its features include findings for external and unused access, basic and custom policy checks for validating policies, and policy generation to generate fine-grained policies. To start using IAM Access Analyzer to identify external or unused access, you first need to create an analyzer.

    **External access analyzers** help identify potential risks of accessing resources by enabling you to identify any resource policies that grant access to an external principal. It does this by using logic-based reasoning to analyze resource-based policies in your Amazon Web Services environment. An external principal can be another Amazon Web Services account, a root user, an IAM user or role, a federated user, an Amazon Web Services service, or an anonymous user. You can also use IAM Access Analyzer to preview public and cross-account access to your resources before deploying permissions changes.

    **Unused access analyzers** help identify potential identity access risks by enabling you to identify unused IAM roles, unused access keys, unused console passwords, and IAM principals with unused service and action-level permissions.

    Beyond findings, IAM Access Analyzer provides basic and custom policy checks to validate IAM policies before deploying permissions changes. You can use policy generation to refine permissions by attaching a policy generated using access activity logged in CloudTrail logs.

    This guide describes the IAM Access Analyzer operations that you can call programmatically. For general information about IAM Access Analyzer, see [Identity and Access Management Access Analyzer](https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html) in the **IAM User Guide**.
servers:
- description: The Access Analyzer regional endpoint
  url: https://access-analyzer.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccessCheckPolicyDocument:
      type: string
    AccessCheckPolicyType:
      type: string
      enum:
      - IDENTITY_POLICY
      - RESOURCE_POLICY
    AccessCheckResourceType:
      type: string
      enum:
      - AWS::DynamoDB::Table
      - AWS::DynamoDB::Stream
      - AWS::EFS::FileSystem
      - AWS::OpenSearchService::Domain
      - AWS::Kinesis::Stream
      - AWS::Kinesis::StreamConsumer
      - AWS::KMS::Key
      - AWS::Lambda::Function
      - AWS::S3::Bucket
      - AWS::S3::AccessPoint
      - AWS::S3Express::DirectoryBucket
      - AWS::S3::Glacier
      - AWS::S3Outposts::Bucket
      - AWS::S3Outposts::AccessPoint
      - AWS::SecretsManager::Secret
      - AWS::SNS::Topic
      - AWS::SQS::Queue
      - AWS::IAM::AssumeRolePolicyDocument
      - AWS::S3Tables::TableBucket
      - AWS::ApiGateway::RestApi
      - AWS::CodeArtifact::Domain
      - AWS::Backup::BackupVault
      - AWS::CloudTrail::Dashboard
      - AWS::CloudTrail::EventDataStore
      - AWS::S3Tables::Table
      - AWS::S3Express::AccessPoint
    AccessPointArn:
      type: string
      pattern: ^arn:[^:]*:s3:[^:]*:[^:]*:accesspoint/.*$
    AccessPointPolicy:
      type: string
    AccessPreviewFindingId:
      type: string
    AccessPreviewId:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
    AccessPreviewStatus:
      type: string
      enum:
      - COMPLETED
      - CREATING
      - FAILED
    AccessPreviewStatusReasonCode:
      type: string
      enum:
      - INTERNAL_ERROR
      - INVALID_CONFIGURATION
    AclCanonicalId:
      type: string
    AclPermission:
      type: string
      enum:
      - READ
      - WRITE
      - READ_ACP
      - WRITE_ACP
      - FULL_CONTROL
    AclUri:
      type: string
    Action:
      type: string
    AnalyzerArn:
      type: string
      pattern: ^[^:]*:[^:]*:[^:]*:[^:]*:[^:]*:analyzer/.{1,255}$
    AnalyzerStatus:
      type: string
      enum:
      - ACTIVE
      - CREATING
      - DISABLED
      - FAILED
    CheckAccessNotGrantedResult:
      type: string
      enum:
      - PASS
      - FAIL
    CheckNoNewAccessResult:
      type: string
      enum:
      - PASS
      - FAIL
    CheckNoPublicAccessResult:
      type: string
      enum:
      - PASS
      - FAIL
    CloudTrailArn:
      type: string
      pattern: ^arn:[^:]*:cloudtrail:[^:]*:[^:]*:trail/.{1,576}$
    ConfigurationsMapKey:
      type: string
    DynamodbStreamPolicy:
      type: string
    DynamodbTablePolicy:
      type: string
    EbsGroup:
      type: string
    EbsSnapshotDataEncryptionKeyId:
      type: string
    EbsUserId:
      type: string
    EcrRepositoryPolicy:
      type: string
    EfsFileSystemPolicy:
      type: string
    FindingChangeType:
      type: string
      enum:
      - CHANGED
      - NEW
      - UNCHANGED
    FindingId:
      type: string
    FindingSourceType:
      type: string
      enum:
      - POLICY
      - BUCKET_ACL
      - S3_ACCESS_POINT
      - S3_ACCESS_POINT_ACCOUNT
    FindingStatus:
      type: string
      enum:
      - ACTIVE
      - ARCHIVED
      - RESOLVED
    FindingStatusUpdate:
      type: string
      enum:
      - ACTIVE
      - ARCHIVED
    FindingType:
      type: string
      enum:
      - ExternalAccess
      - UnusedIAMRole
      - UnusedIAMUserAccessKey
      - UnusedIAMUserPassword
      - UnusedPermission
    GranteePrincipal:
      type: string
    IamTrustPolicy:
      type: string
    IssueCode:
      type: string
    IssuingAccount:
      type: string
    JobErrorCode:
      type: string
      enum:
      - AUTHORIZATION_ERROR
      - RESOURCE_NOT_FOUND_ERROR
      - SERVICE_QUOTA_EXCEEDED_ERROR
      - SERVICE_ERROR
    JobId:
      type: string
    JobStatus:
      type: string
      enum:
      - IN_PROGRESS
      - SUCCEEDED
      - FAILED
      - CANCELED
    KmsConstraintsKey:
      type: string
    KmsConstraintsValue:
      type: string
    KmsGrantOperation:
      type: string
      enum:
      - CreateGrant
      - Decrypt
      - DescribeKey
      - Encrypt
      - GenerateDataKey
      - GenerateDataKeyPair
      - GenerateDataKeyPairWithoutPlaintext
      - GenerateDataKeyWithoutPlaintext
      - GetPublicKey
      - ReEncryptFrom
      - ReEncryptTo
      - RetireGrant
      - Sign
      - Verify
    KmsKeyPolicy:
      type: string
    LearnMoreLink:
      type: string
    Locale:
      type: string
      enum:
      - DE
      - EN
      - ES
      - FR
      - IT
      - JA
      - KO
      - PT_BR
      - ZH_CN
      - ZH_TW
    Name:
      type: string
      pattern: ^[A-Za-z][A-Za-z0-9_.-]*$
      minLength: 1
      maxLength: 255
    OrderBy:
      type: string
      enum:
      - ASC
      - DESC
    PolicyDocument:
      type: string
    PolicyName:
      type: string
    PolicyType:
      type: string
      enum:
      - IDENTITY_POLICY
      - RESOURCE_POLICY
      - SERVICE_CONTROL_POLICY
      - RESOURCE_CONTROL_POLICY
    PrincipalArn:
      type: string
      pattern: ^arn:[^:]*:iam::[^:]*:(role|user)/.{1,576}$
    RdsDbClusterSnapshotAccountId:
      type: string
    RdsDbClusterSnapshotAttributeName:
      type: string
    RdsDbClusterSnapshotKmsKeyId:
      type: string
    RdsDbSnapshotAccountId:
      type: string
    RdsDbSnapshotAttributeName:
      type: string
    RdsDbSnapshotKmsKeyId:
      type: string
    ReasonCode:
      type: string
      enum:
      - AWS_SERVICE_ACCESS_DISABLED
      - DELEGATED_ADMINISTRATOR_DEREGISTERED
      - ORGANIZATION_DELETED
      - SERVICE_LINKED_ROLE_CREATION_FAILED
    RecommendationType:
      type: string
      enum:
      - UnusedPermissionRecommendation
    RecommendedRemediationAction:
      type: string
      enum:
      - CREATE_POLICY
      - DETACH_POLICY
    Resource:
      type: string
      maxLength: 2048
    ResourceArn:
      type: string
      pattern: ^arn:[^:]*:[^:]*:[^:]*:[^:]*:.*$
    ResourceControlPolicyRestriction:
      type: string
      enum:
      - APPLICABLE
      - FAILED_TO_EVALUATE_RCP
      - NOT_APPLICABLE
    ResourceType:
      type: string
      enum:
      - AWS::S3::Bucket
      - AWS::IAM::Role
      - AWS::SQS::Queue
      - AWS::Lambda::Function
      - AWS::Lambda::LayerVersion
      - AWS::KMS::Key
      - AWS::SecretsManager::Secret
      - AWS::EFS::FileSystem
      - AWS::EC2::Snapshot
      - AWS::ECR::Repository
      - AWS::RDS::DBSnapshot
      - AWS::RDS::DBClusterSnapshot
      - AWS::SNS::Topic
      - AWS::S3Express::DirectoryBucket
      - AWS::DynamoDB::Table
      - AWS::DynamoDB::Stream
      - AWS::IAM::User
    RetiringPrincipal:
      type: string
    RoleArn:
      type: string
      pattern: ^arn:[^:]*:iam::[^:]*:role/.{1,576}$
    S3BucketPolicy:
      type: string
    S3ExpressDirectoryAccessPointArn:
      type: string
      pattern: ^arn:[^:]*:s3express:[^:]*:[^:]*:accesspoint/.*$
    S3ExpressDirectoryBucketPolicy:
      type: string
    SecretsManagerSecretKmsId:
      type: string
    SecretsManagerSecretPolicy:
      type: string
    SnsTopicPolicy:
      type: string
      maxLength: 30720
    SqsQueuePolicy:
      type: string
    Status:
      type: string
      enum:
      - SUCCEEDED
      - FAILED
      - IN_PROGRESS
    Token:
      type: string
    Type:
      type: string
      enum:
      - ACCOUNT
      - ORGANIZATION
      - ACCOUNT_UNUSED_ACCESS
      - ORGANIZATION_UNUSED_ACCESS
    ValidatePolicyFindingType:
      type: string
      enum:
      - ERROR
      - SECURITY_WARNING
      - SUGGESTION
      - WARNING
    ValidatePolicyResourceType:
      type: string
      enum:
      - AWS::S3::Bucket
      - AWS::S3::AccessPoint
      - AWS::S3::MultiRegionAccessPoint
      - AWS::S3ObjectLambda::AccessPoint
      - AWS::IAM::AssumeRolePolicyDocument
      - AWS::DynamoDB::Table
    ValidationExceptionReason:
      type: string
      enum:
      - unknownOperation
      - cannotParse
      - fieldValidationFailed
      - other
      - notSupported
    VpcId:
      type: string
      pattern: ^vpc-([0-9a-f]){8}(([0-9a-f]){9})?$
