openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: account
  x-aws-serviceName: account
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2021-02-01'
  title: AWS Account
  description: |-
    Operations for Amazon Web Services Account Management
servers:
- description: The AWS Account regional endpoint
  url: https://account.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccountId:
      type: string
      pattern: ^\d{12}$
    AccountName:
      type: string
      pattern: ^[ -;=?-~]+$
      minLength: 1
      maxLength: 50
    AddressLine:
      type: string
      minLength: 1
      maxLength: 60
    AlternateContactType:
      type: string
      enum:
      - BILLING
      - OPERATIONS
      - SECURITY
    City:
      type: string
      minLength: 1
      maxLength: 50
    CompanyName:
      type: string
      minLength: 1
      maxLength: 50
    ContactInformationPhoneNumber:
      type: string
      pattern: ^[+][\s0-9()-]+$
      minLength: 1
      maxLength: 20
    CountryCode:
      type: string
      minLength: 2
      maxLength: 2
    DistrictOrCounty:
      type: string
      minLength: 1
      maxLength: 50
    EmailAddress:
      type: string
      pattern: ^[\s]*[\w+=.#|!&-]+@[\w.-]+\.[\w]+[\s]*$
      minLength: 1
      maxLength: 254
    FullName:
      type: string
      minLength: 1
      maxLength: 50
    Name:
      type: string
      minLength: 1
      maxLength: 64
    Otp:
      type: string
      pattern: ^[a-zA-Z0-9]{6}$
    PhoneNumber:
      type: string
      pattern: ^[\s0-9()+-]+$
      minLength: 1
      maxLength: 25
    PostalCode:
      type: string
      minLength: 1
      maxLength: 20
    PrimaryEmailAddress:
      type: string
      minLength: 5
      maxLength: 64
    PrimaryEmailUpdateStatus:
      type: string
      enum:
      - PENDING
      - ACCEPTED
    RegionName:
      type: string
      minLength: 1
      maxLength: 50
    RegionOptStatus:
      type: string
      enum:
      - ENABLED
      - ENABLING
      - DISABLING
      - DISABLED
      - ENABLED_BY_DEFAULT
    SensitiveString:
      type: string
    StateOrRegion:
      type: string
      minLength: 1
      maxLength: 50
    Title:
      type: string
      minLength: 1
      maxLength: 50
    ValidationExceptionReason:
      type: string
      enum:
      - invalidRegionOptTarget
      - fieldValidationFailed
    WebsiteUrl:
      type: string
      minLength: 1
      maxLength: 256
