openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: amp
  x-aws-serviceName: amp
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-08-01'
  title: Amazon Prometheus Service
  description: |-
    Amazon Managed Service for Prometheus is a serverless, Prometheus-compatible monitoring service for container metrics that makes it easier to securely monitor container environments at scale. With Amazon Managed Service for Prometheus, you can use the same open-source Prometheus data model and query language that you use today to monitor the performance of your containerized workloads, and also enjoy improved scalability, availability, and security without having to manage the underlying infrastructure.

    For more information about Amazon Managed Service for Prometheus, see the [Amazon Managed Service for Prometheus](https://docs.aws.amazon.com/prometheus/latest/userguide/what-is-Amazon-Managed-Service-Prometheus.html) User Guide.

    Amazon Managed Service for Prometheus includes two APIs.

      * Use the Amazon Web Services API described in this guide to manage Amazon Managed Service for Prometheus resources, such as workspaces, rule groups, and alert managers.

      * Use the [Prometheus-compatible API](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-APIReference.html#AMP-APIReference-Prometheus-Compatible-Apis) to work within your Prometheus workspace.
servers:
- description: The Amazon Prometheus Service regional endpoint
  url: https://aps.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AlertManagerDefinitionStatusCode:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - UPDATING
      - DELETING
      - CREATION_FAILED
      - UPDATE_FAILED
    ClusterArn:
      type: string
      pattern: ^arn:aws[-a-z]*:eks:[-a-z0-9]+:[0-9]{12}:cluster/.+$
    FilterKey:
      type: string
      minLength: 1
      maxLength: 256
    FilterValue:
      type: string
      minLength: 1
      maxLength: 256
    IamRoleArn:
      type: string
      pattern: ^arn:aws[-a-z]*:iam::[0-9]{12}:role/.+$
    IdempotencyToken:
      type: string
      pattern: ^[!-~]+$
      minLength: 1
      maxLength: 64
    KmsKeyArn:
      type: string
      pattern: ^arn:aws[-a-z]*:kms:[-a-z0-9]+:[0-9]{12}:key/[-a-f0-9]+$
      minLength: 20
      maxLength: 2048
    LabelName:
      type: string
      pattern: ^[a-zA-Z_][a-zA-Z0-9_]*$
      minLength: 1
    LabelValue:
      type: string
      minLength: 1
    LogGroupArn:
      type: string
      pattern: ^arn:aws[-a-z]*:logs:[-a-z0-9]+:[0-9]{12}:log-group:[A-Za-z0-9\.\-\_\#/]{1,512}\:\*$
    LoggingConfigurationStatusCode:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - UPDATING
      - DELETING
      - CREATION_FAILED
      - UPDATE_FAILED
    PaginationToken:
      type: string
      maxLength: 1000
    RuleGroupsNamespaceArn:
      type: string
    RuleGroupsNamespaceName:
      type: string
      pattern: '[0-9A-Za-z][-.0-9A-Z_a-z]*'
      minLength: 1
      maxLength: 64
    RuleGroupsNamespaceStatusCode:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - UPDATING
      - DELETING
      - CREATION_FAILED
      - UPDATE_FAILED
    ScraperAlias:
      type: string
      pattern: ^[0-9A-Za-z][-.0-9A-Z_a-z]*$
      minLength: 1
      maxLength: 100
    ScraperArn:
      type: string
    ScraperId:
      type: string
      pattern: ^[0-9A-Za-z][-.0-9A-Z_a-z]*$
      minLength: 1
      maxLength: 64
    ScraperStatusCode:
      type: string
      enum:
      - CREATING
      - UPDATING
      - ACTIVE
      - DELETING
      - CREATION_FAILED
      - UPDATE_FAILED
      - DELETION_FAILED
    SecurityGroupId:
      type: string
      pattern: ^sg-[0-9a-z]+$
      minLength: 0
      maxLength: 255
    StatusReason:
      type: string
      minLength: 1
      maxLength: 256
    SubnetId:
      type: string
      pattern: ^subnet-[0-9a-z]+$
      minLength: 0
      maxLength: 255
    TagKey:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
      minLength: 0
      maxLength: 256
    Uri:
      type: string
      minLength: 1
      maxLength: 1024
    ValidationExceptionReason:
      type: string
      enum:
      - UNKNOWN_OPERATION
      - CANNOT_PARSE
      - FIELD_VALIDATION_FAILED
      - OTHER
    WorkspaceAlias:
      type: string
      minLength: 1
      maxLength: 100
    WorkspaceArn:
      type: string
      pattern: ^arn:aws[-a-z]*:aps:[-a-z0-9]+:[0-9]{12}:workspace/.+$
    WorkspaceConfigurationStatusCode:
      type: string
      enum:
      - ACTIVE
      - UPDATING
      - UPDATE_FAILED
    WorkspaceId:
      type: string
      pattern: '[0-9A-Za-z][-.0-9A-Z_a-z]*'
      minLength: 1
      maxLength: 64
    WorkspaceStatusCode:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - UPDATING
      - DELETING
      - CREATION_FAILED
