openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: amplifybackend
  x-aws-serviceName: amplifybackend
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-08-11'
  title: AmplifyBackend
  description: |-
    AWS Amplify Admin API
servers:
- description: The AmplifyBackend regional endpoint
  url: https://amplifybackend.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AdditionalConstraintsElement:
      type: string
      enum:
      - REQUIRE_DIGIT
      - REQUIRE_LOWERCASE
      - REQUIRE_SYMBOL
      - REQUIRE_UPPERCASE
    AuthResources:
      type: string
      enum:
      - USER_POOL_ONLY
      - IDENTITY_POOL_AND_USER_POOL
    AuthenticatedElement:
      type: string
      enum:
      - READ
      - CREATE_AND_UPDATE
      - DELETE
    DeliveryMethod:
      type: string
      enum:
      - EMAIL
      - SMS
      description: <p>The type of verification message to send.</p>
    ListOfAdditionalConstraintsElement:
      type: array
      items:
        $ref: '#/components/schemas/AdditionalConstraintsElement'
    ListOfAuthenticatedElement:
      type: array
      items:
        $ref: '#/components/schemas/AuthenticatedElement'
    ListOfBackendAPIAuthType:
      type: array
      items:
        $ref: '#/components/schemas/BackendAPIAuthType'
    ListOfBackendJobRespObj:
      type: array
      items:
        $ref: '#/components/schemas/BackendJobRespObj'
    ListOfMfaTypesElement:
      type: array
      items:
        $ref: '#/components/schemas/MfaTypesElement'
    ListOfOAuthScopesElement:
      type: array
      items:
        $ref: '#/components/schemas/OAuthScopesElement'
    ListOfRequiredSignUpAttributesElement:
      type: array
      items:
        $ref: '#/components/schemas/RequiredSignUpAttributesElement'
    ListOfS3BucketInfo:
      type: array
      items:
        $ref: '#/components/schemas/S3BucketInfo'
    ListOfUnAuthenticatedElement:
      type: array
      items:
        $ref: '#/components/schemas/UnAuthenticatedElement'
    ListOf__string:
      type: array
      items:
        $ref: '#/components/schemas/__string'
    MFAMode:
      type: string
      enum:
      - 'ON'
      - 'OFF'
      - OPTIONAL
    MfaTypesElement:
      type: string
      enum:
      - SMS
      - TOTP
    Mode:
      type: string
      enum:
      - API_KEY
      - AWS_IAM
      - AMAZON_COGNITO_USER_POOLS
      - OPENID_CONNECT
    OAuthGrantType:
      type: string
      enum:
      - CODE
      - IMPLICIT
    OAuthScopesElement:
      type: string
      enum:
      - PHONE
      - EMAIL
      - OPENID
      - PROFILE
      - AWS_COGNITO_SIGNIN_USER_ADMIN
    RequiredSignUpAttributesElement:
      type: string
      enum:
      - ADDRESS
      - BIRTHDATE
      - EMAIL
      - FAMILY_NAME
      - GENDER
      - GIVEN_NAME
      - LOCALE
      - MIDDLE_NAME
      - NAME
      - NICKNAME
      - PHONE_NUMBER
      - PICTURE
      - PREFERRED_USERNAME
      - PROFILE
      - UPDATED_AT
      - WEBSITE
      - ZONE_INFO
    ResolutionStrategy:
      type: string
      enum:
      - OPTIMISTIC_CONCURRENCY
      - LAMBDA
      - AUTOMERGE
      - NONE
    Service:
      type: string
      enum:
      - COGNITO
    ServiceName:
      type: string
      enum:
      - S3
    SignInMethod:
      type: string
      enum:
      - EMAIL
      - EMAIL_AND_PHONE_NUMBER
      - PHONE_NUMBER
      - USERNAME
    Status:
      type: string
      enum:
      - LATEST
      - STALE
    UnAuthenticatedElement:
      type: string
      enum:
      - READ
      - CREATE_AND_UPDATE
      - DELETE
    __boolean:
      type: boolean
    __double:
      type: number
      format: double
    __integerMin1Max25:
      type: integer
      minimum: 1
      maximum: 25
    __string:
      type: string
