openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: amplify
  x-aws-serviceName: amplify
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-07-25'
  title: AWS Amplify
  description: |-
    Amplify enables developers to develop and deploy cloud-powered mobile and web apps. Amplify Hosting provides a continuous delivery and hosting service for web applications. For more information, see the [Amplify Hosting User Guide](https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html). The Amplify Framework is a comprehensive set of SDKs, libraries, tools, and documentation for client app development. For more information, see the [Amplify Framework.](https://docs.amplify.aws/)
servers:
- description: The AWS Amplify regional endpoint
  url: https://amplify.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccessToken:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 255
    ActiveJobId:
      type: string
      minLength: 0
      maxLength: 1000
    AppArn:
      type: string
      minLength: 0
      maxLength: 1000
    AppId:
      type: string
      pattern: ^d[a-z0-9]+$
      minLength: 1
      maxLength: 20
    ArtifactFileName:
      type: string
      minLength: 0
      maxLength: 1000
    ArtifactId:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 255
    ArtifactUrl:
      type: string
      minLength: 0
      maxLength: 1000
    ArtifactsUrl:
      type: string
      minLength: 0
      maxLength: 1000
    AssociatedResource:
      type: string
      minLength: 1
      maxLength: 2048
    AutoBranchCreationPattern:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 2048
    AutoSubDomainCreationPattern:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 2048
    AutoSubDomainIAMRole:
      type: string
      pattern: ^$|^arn:aws:iam::\d{12}:role.+$
      minLength: 0
      maxLength: 1000
    BackendEnvironmentArn:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 1000
    BasicAuthCredentials:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 2000
    BranchArn:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 1000
    BranchName:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 255
    BuildSpec:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 25000
    CertificateArn:
      type: string
      pattern: ^arn:aws:acm:[a-z0-9-]+:\d{12}:certificate\/.+$
      minLength: 0
      maxLength: 1000
    CertificateVerificationDNSRecord:
      type: string
      minLength: 0
      maxLength: 1000
    Code:
      type: string
    CommitId:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 255
    CommitMessage:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 10000
    ComputeRoleArn:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 1000
    Condition:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 2048
    Context:
      type: string
    CustomDomain:
      type: string
      minLength: 0
      maxLength: 255
    CustomHeaders:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 25000
    DNSRecord:
      type: string
      minLength: 0
      maxLength: 1000
    DefaultDomain:
      type: string
      minLength: 1
      maxLength: 1000
    DeploymentArtifacts:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 1000
    Description:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 1000
    DisplayName:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 255
    DomainAssociationArn:
      type: string
      minLength: 0
      maxLength: 1000
    DomainName:
      type: string
      pattern: ^(((?!-)[A-Za-z0-9-]{0,62}[A-Za-z0-9])\.)+((?!-)[A-Za-z0-9-]{1,62}[A-Za-z0-9])(\.)?$
      minLength: 0
      maxLength: 64
    DomainPrefix:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 255
    EnableAutoBranchCreation:
      type: boolean
    EnableAutoBuild:
      type: boolean
    EnableAutoSubDomain:
      type: boolean
    EnableBasicAuth:
      type: boolean
    EnableBranchAutoBuild:
      type: boolean
    EnableBranchAutoDeletion:
      type: boolean
    EnableNotification:
      type: boolean
    EnablePerformanceMode:
      type: boolean
    EnablePullRequestPreview:
      type: boolean
    EnableSkewProtection:
      type: boolean
    EnvKey:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 255
    EnvValue:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 5500
    EnvironmentName:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 255
    ErrorMessage:
      type: string
      minLength: 0
      maxLength: 255
    FileName:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 255
    Framework:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 255
    JobArn:
      type: string
      minLength: 0
      maxLength: 1000
    JobId:
      type: string
      pattern: ^[0-9]+$
      minLength: 0
      maxLength: 255
    JobReason:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 255
    LogUrl:
      type: string
      minLength: 0
      maxLength: 1000
    MD5Hash:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 32
    MaxResults:
      type: integer
      default: 0
      minimum: 0
      maximum: 50
    MaxResultsForListApps:
      type: integer
      default: 0
      minimum: 0
      maximum: 100
    Name:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 255
    NextToken:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 2000
    OauthToken:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 1000
    PullRequestEnvironmentName:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 20
    Repository:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 1000
    ResourceArn:
      type: string
      pattern: '^arn:aws:amplify:'
      minLength: 0
      maxLength: 2048
    ServiceRoleArn:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 1000
    Source:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 2048
    SourceUrl:
      type: string
      pattern: ^(s3|https|http)://
      minLength: 0
      maxLength: 3000
    StackArn:
      type: string
      pattern: ^arn:aws:cloudformation:[a-z0-9-]+:\d{12}:stack/.+/.+$
      minLength: 20
      maxLength: 2048
    StackName:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 255
    Status:
      type: string
      pattern: ^.{3,7}$
      minLength: 3
      maxLength: 7
    StatusReason:
      type: string
      minLength: 0
      maxLength: 1000
    StepName:
      type: string
      minLength: 0
      maxLength: 255
    TTL:
      type: string
      pattern: ^\d*$
      minLength: 0
      maxLength: 32
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
      minLength: 0
      maxLength: 256
    Target:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 2048
    TestArtifactsUrl:
      type: string
      minLength: 0
      maxLength: 1000
    TestConfigUrl:
      type: string
      minLength: 0
      maxLength: 1000
    ThumbnailName:
      type: string
      minLength: 0
      maxLength: 256
    ThumbnailUrl:
      type: string
      minLength: 1
      maxLength: 2000
    TotalNumberOfJobs:
      type: string
      minLength: 0
      maxLength: 1000
    UploadUrl:
      type: string
      minLength: 0
      maxLength: 1000
    Verified:
      type: boolean
    WebAclArn:
      type: string
      pattern: '^arn:aws:wafv2:'
      minLength: 0
      maxLength: 512
    WebhookArn:
      type: string
      minLength: 0
      maxLength: 1000
    WebhookId:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 255
    WebhookUrl:
      type: string
      minLength: 0
      maxLength: 1000
