openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: amplifyuibuilder
  x-aws-serviceName: amplifyuibuilder
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2021-08-11'
  title: AWS Amplify UI Builder
  description: |-
    The Amplify UI Builder API provides a programmatic interface for creating and configuring user interface (UI) component libraries and themes for use in your Amplify applications. You can then connect these UI components to an application's backend Amazon Web Services resources.

    You can also use the Amplify Studio visual designer to create UI components and model data for an app. For more information, see [Introduction](https://docs.amplify.aws/console/adminui/intro) in the _Amplify Docs_.

    The Amplify Framework is a comprehensive set of SDKs, libraries, tools, and documentation for client app development. For more information, see the [Amplify Framework](https://docs.amplify.aws/). For more information about deploying an Amplify application to Amazon Web Services, see the [Amplify User Guide](https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html).
servers:
- description: The AWS Amplify UI Builder regional endpoint
  url: https://amplifyuibuilder.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AppId:
      type: string
      pattern: ^d[a-z0-9]+$
      minLength: 1
      maxLength: 20
    ComponentName:
      type: string
      minLength: 1
      maxLength: 255
    ComponentType:
      type: string
      minLength: 1
      maxLength: 255
    FormDataSourceType:
      type: string
      enum:
      - DataStore
      - Custom
    FormName:
      type: string
      minLength: 1
      maxLength: 255
    LabelDecorator:
      type: string
      enum:
      - required
      - optional
      - none
    ListCodegenJobsLimit:
      type: integer
      minimum: 1
      maximum: 100
    ListEntityLimit:
      type: integer
      minimum: 1
      maximum: 100
    OperandType:
      type: string
      pattern: ^boolean|string|number$
    SensitiveString:
      type: string
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 1
      maxLength: 256
    ThemeName:
      type: string
      minLength: 1
      maxLength: 255
    TokenProviders:
      type: string
      enum:
      - figma
    Uuid:
      type: string
