openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: amplify
  x-aws-serviceName: amplify
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-07-25'
  title: AWS Amplify
  description: |-
    Amplify enables developers to develop and deploy cloud-powered mobile and web apps. Amplify Hosting provides a continuous delivery and hosting service for web applications. For more information, see the [Amplify Hosting User Guide](https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html). The Amplify Framework is a comprehensive set of SDKs, libraries, tools, and documentation for client app development. For more information, see the [Amplify Framework.](https://docs.amplify.aws/)
servers:
- description: The AWS Amplify regional endpoint
  url: https://amplify.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccessToken:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 255
    ActiveJobId:
      type: string
      minLength: 0
      maxLength: 1000
    AppArn:
      type: string
      minLength: 0
      maxLength: 1000
    AppId:
      type: string
      pattern: ^d[a-z0-9]+$
      minLength: 1
      maxLength: 20
    Apps:
      type: array
      items:
        $ref: '#/components/schemas/App'
    ArtifactFileName:
      type: string
      minLength: 0
      maxLength: 1000
    ArtifactId:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 255
    ArtifactUrl:
      type: string
      minLength: 0
      maxLength: 1000
    Artifacts:
      type: array
      items:
        $ref: '#/components/schemas/Artifact'
    ArtifactsUrl:
      type: string
      minLength: 0
      maxLength: 1000
    AssociatedResource:
      type: string
      minLength: 1
      maxLength: 2048
    AssociatedResources:
      type: array
      items:
        $ref: '#/components/schemas/AssociatedResource'
    AutoBranchCreationPattern:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 2048
    AutoBranchCreationPatterns:
      type: array
      items:
        $ref: '#/components/schemas/AutoBranchCreationPattern'
    AutoSubDomainCreationPattern:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 2048
    AutoSubDomainCreationPatterns:
      type: array
      items:
        $ref: '#/components/schemas/AutoSubDomainCreationPattern'
    AutoSubDomainIAMRole:
      type: string
      pattern: ^$|^arn:aws:iam::\d{12}:role.+$
      minLength: 0
      maxLength: 1000
    BackendEnvironmentArn:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 1000
    BackendEnvironments:
      type: array
      items:
        $ref: '#/components/schemas/BackendEnvironment'
    BasicAuthCredentials:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 2000
    BranchArn:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 1000
    BranchName:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 255
    Branches:
      type: array
      items:
        $ref: '#/components/schemas/Branch'
    BuildSpec:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 25000
    CacheConfigType:
      type: string
      enum:
      - AMPLIFY_MANAGED
      - AMPLIFY_MANAGED_NO_COOKIES
    CertificateArn:
      type: string
      pattern: ^arn:aws:acm:[a-z0-9-]+:\d{12}:certificate\/.+$
      minLength: 0
      maxLength: 1000
    CertificateType:
      type: string
      enum:
      - AMPLIFY_MANAGED
      - CUSTOM
    CertificateVerificationDNSRecord:
      type: string
      minLength: 0
      maxLength: 1000
    Code:
      type: string
    CommitId:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 255
    CommitMessage:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 10000
    CommitTime:
      type: string
      format: date-time
    ComputeRoleArn:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 1000
    Condition:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 2048
    Context:
      type: string
    CreateTime:
      type: string
      format: date-time
    CustomDomain:
      type: string
      minLength: 0
      maxLength: 255
    CustomDomains:
      type: array
      items:
        $ref: '#/components/schemas/CustomDomain'
    CustomHeaders:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 25000
    CustomRules:
      type: array
      items:
        $ref: '#/components/schemas/CustomRule'
    DNSRecord:
      type: string
      minLength: 0
      maxLength: 1000
    DefaultDomain:
      type: string
      minLength: 1
      maxLength: 1000
    DeploymentArtifacts:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 1000
    Description:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 1000
    DisplayName:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 255
    DomainAssociationArn:
      type: string
      minLength: 0
      maxLength: 1000
    DomainAssociations:
      type: array
      items:
        $ref: '#/components/schemas/DomainAssociation'
    DomainName:
      type: string
      pattern: ^(((?!-)[A-Za-z0-9-]{0,62}[A-Za-z0-9])\.)+((?!-)[A-Za-z0-9-]{1,62}[A-Za-z0-9])(\.)?$
      minLength: 0
      maxLength: 64
    DomainPrefix:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 255
    DomainStatus:
      type: string
      enum:
      - PENDING_VERIFICATION
      - IN_PROGRESS
      - AVAILABLE
      - IMPORTING_CUSTOM_CERTIFICATE
      - PENDING_DEPLOYMENT
      - AWAITING_APP_CNAME
      - FAILED
      - CREATING
      - REQUESTING_CERTIFICATE
      - UPDATING
    EnableAutoBranchCreation:
      type: boolean
    EnableAutoBuild:
      type: boolean
    EnableAutoSubDomain:
      type: boolean
    EnableBasicAuth:
      type: boolean
    EnableBranchAutoBuild:
      type: boolean
    EnableBranchAutoDeletion:
      type: boolean
    EnableNotification:
      type: boolean
    EnablePerformanceMode:
      type: boolean
    EnablePullRequestPreview:
      type: boolean
    EnableSkewProtection:
      type: boolean
    EndTime:
      type: string
      format: date-time
    EnvKey:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 255
    EnvValue:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 5500
    EnvironmentName:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 255
    EnvironmentVariables:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/EnvValue'
    ErrorMessage:
      type: string
      minLength: 0
      maxLength: 255
    FileMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/MD5Hash'
    FileName:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 255
    FileUploadUrls:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/UploadUrl'
    Framework:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 255
    JobArn:
      type: string
      minLength: 0
      maxLength: 1000
    JobId:
      type: string
      pattern: ^[0-9]+$
      minLength: 0
      maxLength: 255
    JobReason:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 255
    JobStatus:
      type: string
      enum:
      - CREATED
      - PENDING
      - PROVISIONING
      - RUNNING
      - FAILED
      - SUCCEED
      - CANCELLING
      - CANCELLED
    JobSummaries:
      type: array
      items:
        $ref: '#/components/schemas/JobSummary'
    JobType:
      type: string
      enum:
      - RELEASE
      - RETRY
      - MANUAL
      - WEB_HOOK
    LastDeployTime:
      type: string
      format: date-time
    LogUrl:
      type: string
      minLength: 0
      maxLength: 1000
    MD5Hash:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 32
    MaxResults:
      type: integer
      default: 0
      minimum: 0
      maximum: 50
    MaxResultsForListApps:
      type: integer
      default: 0
      minimum: 0
      maximum: 100
    Name:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 255
    NextToken:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 2000
    OauthToken:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 1000
    Platform:
      type: string
      enum:
      - WEB
      - WEB_DYNAMIC
      - WEB_COMPUTE
    PullRequestEnvironmentName:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 20
    Repository:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 1000
    RepositoryCloneMethod:
      type: string
      enum:
      - SSH
      - TOKEN
      - SIGV4
    ResourceArn:
      type: string
      pattern: '^arn:aws:amplify:'
      minLength: 0
      maxLength: 2048
    Screenshots:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ThumbnailUrl'
    ServiceRoleArn:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 1000
    Source:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 2048
    SourceUrl:
      type: string
      pattern: ^(s3|https|http)://
      minLength: 0
      maxLength: 3000
    SourceUrlType:
      type: string
      enum:
      - ZIP
      - BUCKET_PREFIX
    StackArn:
      type: string
      pattern: ^arn:aws:cloudformation:[a-z0-9-]+:\d{12}:stack/.+/.+$
      minLength: 20
      maxLength: 2048
    StackName:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 255
    Stage:
      type: string
      enum:
      - PRODUCTION
      - BETA
      - DEVELOPMENT
      - EXPERIMENTAL
      - PULL_REQUEST
    StartTime:
      type: string
      format: date-time
    Status:
      type: string
      pattern: ^.{3,7}$
      minLength: 3
      maxLength: 7
    StatusReason:
      type: string
      minLength: 0
      maxLength: 1000
    StepName:
      type: string
      minLength: 0
      maxLength: 255
    Steps:
      type: array
      items:
        $ref: '#/components/schemas/Step'
    SubDomainSettings:
      type: array
      items:
        $ref: '#/components/schemas/SubDomainSetting'
    SubDomains:
      type: array
      items:
        $ref: '#/components/schemas/SubDomain'
    TTL:
      type: string
      pattern: ^\d*$
      minLength: 0
      maxLength: 32
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
      minLength: 0
      maxLength: 256
    Target:
      type: string
      pattern: ^(?s).+$
      minLength: 1
      maxLength: 2048
    TestArtifactsUrl:
      type: string
      minLength: 0
      maxLength: 1000
    TestConfigUrl:
      type: string
      minLength: 0
      maxLength: 1000
    ThumbnailName:
      type: string
      minLength: 0
      maxLength: 256
    ThumbnailUrl:
      type: string
      minLength: 1
      maxLength: 2000
    TotalNumberOfJobs:
      type: string
      minLength: 0
      maxLength: 1000
    UpdateStatus:
      type: string
      enum:
      - REQUESTING_CERTIFICATE
      - PENDING_VERIFICATION
      - IMPORTING_CUSTOM_CERTIFICATE
      - PENDING_DEPLOYMENT
      - AWAITING_APP_CNAME
      - UPDATE_COMPLETE
      - UPDATE_FAILED
    UpdateTime:
      type: string
      format: date-time
    UploadUrl:
      type: string
      minLength: 0
      maxLength: 1000
    Verified:
      type: boolean
    WafStatus:
      type: string
      enum:
      - ASSOCIATING
      - ASSOCIATION_FAILED
      - ASSOCIATION_SUCCESS
      - DISASSOCIATING
      - DISASSOCIATION_FAILED
    WebAclArn:
      type: string
      pattern: '^arn:aws:wafv2:'
      minLength: 0
      maxLength: 512
    WebhookArn:
      type: string
      minLength: 0
      maxLength: 1000
    WebhookId:
      type: string
      pattern: ^(?s)
      minLength: 0
      maxLength: 255
    WebhookUrl:
      type: string
      minLength: 0
      maxLength: 1000
    Webhooks:
      type: array
      items:
        $ref: '#/components/schemas/Webhook'
    webhookCreateTime:
      type: string
      format: date-time
