openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: apigatewayv2
  x-aws-serviceName: apigatewayv2
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-11-29'
  title: AmazonApiGatewayV2
  description: |-
    Amazon API Gateway V2
servers:
- description: The AmazonApiGatewayV2 regional endpoint
  url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Arn:
      type: string
    Id:
      type: string
    IntegerWithLengthBetween0And3600:
      type: integer
      minimum: 0
      maximum: 3600
      description: <p>An integer with a value between [0-3600].</p>
    IntegerWithLengthBetween50And30000:
      type: integer
      minimum: 50
      maximum: 30000
      description: <p>An integer with a value between [50-30000].</p>
    IntegerWithLengthBetweenMinus1And86400:
      type: integer
      minimum: -1
      maximum: 86400
      description: <p>An integer with a value between -1 and 86400. Supported only
        for HTTP APIs.</p>
    NextToken:
      type: string
    SelectionExpression:
      type: string
    SelectionKey:
      type: string
    StringWithLengthBetween0And1024:
      type: string
    StringWithLengthBetween0And2048:
      type: string
    StringWithLengthBetween0And32K:
      type: string
    StringWithLengthBetween1And1024:
      type: string
    StringWithLengthBetween1And128:
      type: string
    StringWithLengthBetween1And1600:
      type: string
    StringWithLengthBetween1And256:
      type: string
    StringWithLengthBetween1And512:
      type: string
    StringWithLengthBetween1And64:
      type: string
    UriWithLengthBetween1And2048:
      type: string
    __boolean:
      type: boolean
    __integer:
      type: integer
    __string:
      type: string
