openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: api_gateway
  x-aws-serviceName: apigateway
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2015-07-09'
  title: Amazon API Gateway
  description: |-
    Amazon API Gateway

    Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.
servers:
- description: The Amazon API Gateway regional endpoint
  url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccessAssociationSourceType:
      type: string
      enum:
      - VPCE
    ApiKeySourceType:
      type: string
      enum:
      - HEADER
      - AUTHORIZER
    ApiKeysFormat:
      type: string
      enum:
      - csv
    AuthorizerType:
      type: string
      enum:
      - TOKEN
      - REQUEST
      - COGNITO_USER_POOLS
      description: <p>The authorizer type. Valid values are <code>TOKEN</code> for
        a Lambda function using a single authorization token submitted in a custom
        header, <code>REQUEST</code> for a Lambda function using incoming request
        parameters, and <code>COGNITO_USER_POOLS</code> for using an Amazon Cognito
        user pool.</p>
    Blob:
      type: string
      format: byte
    Boolean:
      type: boolean
      default: false
    CacheClusterSize:
      type: string
      enum:
      - '0.5'
      - '1.6'
      - '6.1'
      - '13.5'
      - '28.4'
      - '58.2'
      - '118'
      - '237'
      description: <p>Returns the size of the CacheCluster.</p>
    CacheClusterStatus:
      type: string
      enum:
      - CREATE_IN_PROGRESS
      - AVAILABLE
      - DELETE_IN_PROGRESS
      - NOT_AVAILABLE
      - FLUSH_IN_PROGRESS
      description: <p>Returns the status of the CacheCluster.</p>
    ConnectionType:
      type: string
      enum:
      - INTERNET
      - VPC_LINK
    ContentHandlingStrategy:
      type: string
      enum:
      - CONVERT_TO_BINARY
      - CONVERT_TO_TEXT
    DocumentationPartLocationStatusCode:
      type: string
      pattern: ^([1-5]\d\d|\*|\s*)$
    DocumentationPartType:
      type: string
      enum:
      - API
      - AUTHORIZER
      - MODEL
      - RESOURCE
      - METHOD
      - PATH_PARAMETER
      - QUERY_PARAMETER
      - REQUEST_HEADER
      - REQUEST_BODY
      - RESPONSE
      - RESPONSE_HEADER
      - RESPONSE_BODY
    DomainNameStatus:
      type: string
      enum:
      - AVAILABLE
      - UPDATING
      - PENDING
      - PENDING_CERTIFICATE_REIMPORT
      - PENDING_OWNERSHIP_VERIFICATION
    Double:
      type: number
      format: double
      default: 0
    EndpointType:
      type: string
      enum:
      - REGIONAL
      - EDGE
      - PRIVATE
      description: <p>The endpoint type. The valid values are <code>EDGE</code> for
        edge-optimized API setup, most suitable for mobile applications; <code>REGIONAL</code>
        for regional API endpoint setup, most suitable for calling from AWS Region;
        and <code>PRIVATE</code> for private APIs.</p>
    GatewayResponseType:
      type: string
      enum:
      - DEFAULT_4XX
      - DEFAULT_5XX
      - RESOURCE_NOT_FOUND
      - UNAUTHORIZED
      - INVALID_API_KEY
      - ACCESS_DENIED
      - AUTHORIZER_FAILURE
      - AUTHORIZER_CONFIGURATION_ERROR
      - INVALID_SIGNATURE
      - EXPIRED_TOKEN
      - MISSING_AUTHENTICATION_TOKEN
      - INTEGRATION_FAILURE
      - INTEGRATION_TIMEOUT
      - API_CONFIGURATION_ERROR
      - UNSUPPORTED_MEDIA_TYPE
      - BAD_REQUEST_PARAMETERS
      - BAD_REQUEST_BODY
      - REQUEST_TOO_LARGE
      - THROTTLED
      - QUOTA_EXCEEDED
      - WAF_FILTERED
    Integer:
      type: integer
      default: 0
    IntegrationType:
      type: string
      enum:
      - HTTP
      - AWS
      - MOCK
      - HTTP_PROXY
      - AWS_PROXY
      description: <p>The integration type. The valid value is <code>HTTP</code> for
        integrating an API method with an HTTP backend; <code>AWS</code> with any
        Amazon Web Services service endpoints; <code>MOCK</code> for testing without
        actually invoking the backend; <code>HTTP_PROXY</code> for integrating with
        the HTTP proxy integration; <code>AWS_PROXY</code> for integrating with the
        Lambda proxy integration. </p>
    IpAddressType:
      type: string
      enum:
      - ipv4
      - dualstack
    ListOfARNs:
      type: array
      items:
        $ref: '#/components/schemas/ProviderARN'
    ListOfApiKey:
      type: array
      items:
        $ref: '#/components/schemas/ApiKey'
    ListOfApiStage:
      type: array
      items:
        $ref: '#/components/schemas/ApiStage'
    ListOfAuthorizer:
      type: array
      items:
        $ref: '#/components/schemas/Authorizer'
    ListOfBasePathMapping:
      type: array
      items:
        $ref: '#/components/schemas/BasePathMapping'
    ListOfClientCertificate:
      type: array
      items:
        $ref: '#/components/schemas/ClientCertificate'
    ListOfDeployment:
      type: array
      items:
        $ref: '#/components/schemas/Deployment'
    ListOfDocumentationPart:
      type: array
      items:
        $ref: '#/components/schemas/DocumentationPart'
    ListOfDocumentationVersion:
      type: array
      items:
        $ref: '#/components/schemas/DocumentationVersion'
    ListOfDomainName:
      type: array
      items:
        $ref: '#/components/schemas/DomainName'
    ListOfDomainNameAccessAssociation:
      type: array
      items:
        $ref: '#/components/schemas/DomainNameAccessAssociation'
    ListOfEndpointType:
      type: array
      items:
        $ref: '#/components/schemas/EndpointType'
    ListOfGatewayResponse:
      type: array
      items:
        $ref: '#/components/schemas/GatewayResponse'
    ListOfLong:
      type: array
      items:
        $ref: '#/components/schemas/Long'
    ListOfModel:
      type: array
      items:
        $ref: '#/components/schemas/Model'
    ListOfPatchOperation:
      type: array
      items:
        $ref: '#/components/schemas/PatchOperation'
      description: "<p>A list of operations describing the updates to apply to the\
        \ specified resource. The patches are applied\n      in the order specified\
        \ in the list.</p>"
    ListOfRequestValidator:
      type: array
      items:
        $ref: '#/components/schemas/RequestValidator'
    ListOfResource:
      type: array
      items:
        $ref: '#/components/schemas/Resource'
    ListOfRestApi:
      type: array
      items:
        $ref: '#/components/schemas/RestApi'
    ListOfSdkConfigurationProperty:
      type: array
      items:
        $ref: '#/components/schemas/SdkConfigurationProperty'
    ListOfSdkType:
      type: array
      items:
        $ref: '#/components/schemas/SdkType'
    ListOfStage:
      type: array
      items:
        $ref: '#/components/schemas/Stage'
    ListOfStageKeys:
      type: array
      items:
        $ref: '#/components/schemas/StageKey'
    ListOfString:
      type: array
      items:
        $ref: '#/components/schemas/String'
    ListOfUsage:
      type: array
      items:
        $ref: '#/components/schemas/ListOfLong'
    ListOfUsagePlan:
      type: array
      items:
        $ref: '#/components/schemas/UsagePlan'
    ListOfUsagePlanKey:
      type: array
      items:
        $ref: '#/components/schemas/UsagePlanKey'
    ListOfVpcLink:
      type: array
      items:
        $ref: '#/components/schemas/VpcLink'
    LocationStatusType:
      type: string
      enum:
      - DOCUMENTED
      - UNDOCUMENTED
    Long:
      type: integer
      format: int64
      default: 0
    MapOfApiStageThrottleSettings:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ThrottleSettings'
    MapOfIntegrationResponse:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/IntegrationResponse'
    MapOfKeyUsages:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ListOfUsage'
    MapOfMethod:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Method'
    MapOfMethodResponse:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/MethodResponse'
    MapOfMethodSettings:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/MethodSetting'
    MapOfMethodSnapshot:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/MethodSnapshot'
    MapOfStringToBoolean:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/NullableBoolean'
    MapOfStringToList:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ListOfString'
    MapOfStringToString:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    NullableBoolean:
      type: boolean
    NullableInteger:
      type: integer
    Op:
      type: string
      enum:
      - add
      - remove
      - replace
      - move
      - copy
      - test
    PathToMapOfMethodSnapshot:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/MapOfMethodSnapshot'
    ProviderARN:
      type: string
    PutMode:
      type: string
      enum:
      - merge
      - overwrite
    QuotaPeriodType:
      type: string
      enum:
      - DAY
      - WEEK
      - MONTH
    ResourceOwner:
      type: string
      enum:
      - SELF
      - OTHER_ACCOUNTS
    SecurityPolicy:
      type: string
      enum:
      - TLS_1_0
      - TLS_1_2
    StatusCode:
      type: string
      pattern: ^[1-5]\d\d$
    String:
      type: string
    Timestamp:
      type: string
      format: date-time
    UnauthorizedCacheControlHeaderStrategy:
      type: string
      enum:
      - FAIL_WITH_403
      - SUCCEED_WITH_RESPONSE_HEADER
      - SUCCEED_WITHOUT_RESPONSE_HEADER
    VpcLinkStatus:
      type: string
      enum:
      - AVAILABLE
      - PENDING
      - DELETING
      - FAILED
