openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: appflow
  x-aws-serviceName: appflow
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-08-23'
  title: Amazon Appflow
  description: |-
    Welcome to the Amazon AppFlow API reference. This guide is for developers who need detailed information about the Amazon AppFlow API operations, data types, and errors.

    Amazon AppFlow is a fully managed integration service that enables you to securely transfer data between software as a service (SaaS) applications like Salesforce, Marketo, Slack, and ServiceNow, and Amazon Web Services like Amazon S3 and Amazon Redshift.

    Use the following links to get started on the Amazon AppFlow API:

      * [Actions](https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Operations.html): An alphabetical list of all Amazon AppFlow API operations.

      * [Data types](https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Types.html): An alphabetical list of all Amazon AppFlow data types.

      * [Common parameters](https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonParameters.html): Parameters that all Query operations can use.

      * [Common errors](https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonErrors.html): Client and server errors that all operations can return.

    If you're new to Amazon AppFlow, we recommend that you review the [Amazon AppFlow User Guide](https://docs.aws.amazon.com/appflow/latest/userguide/what-is-appflow.html).

    Amazon AppFlow API users can use vendor-specific mechanisms for OAuth, and include applicable OAuth attributes (such as `auth-code` and `redirecturi`) with the connector-specific `ConnectorProfileProperties` when creating a new connector profile using Amazon AppFlow API operations. For example, Salesforce users can refer to the [ _Authorize Apps with OAuth_ ](https://help.salesforce.com/articleView?id=remoteaccess_authenticate.htm) documentation.
servers:
- description: The Amazon Appflow regional endpoint
  url: https://appflow.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ARN:
      type: string
      pattern: '^arn:aws:.*:.*:[0-9]+:'
      minLength: 0
      maxLength: 512
    AccessKeyId:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 256
    AccessToken:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 4096
    AccountName:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 512
    ApiKey:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 256
    ApiSecretKey:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 256
    ApiToken:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 256
    ApiVersion:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 256
    ApplicationHostUrl:
      type: string
      pattern: ^(https?)://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]$
      minLength: 0
      maxLength: 256
    ApplicationKey:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 512
    ApplicationServicePath:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 512
    ApplicationType:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 512
    AuthCode:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 4096
    AuthCodeUrl:
      type: string
      pattern: ^(https?)://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]$
      minLength: 0
      maxLength: 256
    Boolean:
      type: boolean
      default: false
    BucketName:
      type: string
      pattern: ^\S+$
      minLength: 3
      maxLength: 63
    BucketPrefix:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 512
    BusinessUnitId:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 18
    ClientCredentialsArn:
      type: string
      pattern: '^arn:aws:secretsmanager:.*:[0-9]+:'
      minLength: 20
      maxLength: 2048
    ClientId:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 512
    ClientNumber:
      type: string
      pattern: ^\d{3}$
      minLength: 3
      maxLength: 3
    ClientSecret:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 512
    ClientToken:
      type: string
      pattern: ^[ -~]+$
      minLength: 1
      maxLength: 256
    ClusterIdentifier:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 512
    ConnectorDescription:
      type: string
      pattern: ^[\w!@#\-.?,\s]*$
      minLength: 0
      maxLength: 2048
    ConnectorLabel:
      type: string
      pattern: ^[a-zA-Z0-9][\w!@#.-]+$
      minLength: 0
      maxLength: 256
    ConnectorMode:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 256
    ConnectorName:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 256
    ConnectorOwner:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 256
    ConnectorProfileArn:
      type: string
      pattern: '^arn:aws:appflow:.*:[0-9]+:'
      minLength: 0
      maxLength: 512
    ConnectorProfileName:
      type: string
      pattern: ^[\w/!@#+=.-]+$
      minLength: 0
      maxLength: 256
    ConnectorRuntimeSettingDataType:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 256
    ConnectorRuntimeSettingScope:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 256
    ConnectorSuppliedValue:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 256
    ConnectorVersion:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 256
    CreatedBy:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 256
    CredentialsMapKey:
      type: string
      pattern: ^[\w]+$
      minLength: 1
      maxLength: 128
    CredentialsMapValue:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 2048
    CustomAuthenticationType:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 256
    CustomPropertyKey:
      type: string
      pattern: ^[\w]+$
      minLength: 1
      maxLength: 128
    CustomPropertyValue:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 2048
    DataApiRoleArn:
      type: string
      pattern: '^arn:aws:iam:.*:[0-9]+:'
      minLength: 0
      maxLength: 512
    DataTransferApiTypeName:
      type: string
      pattern: ^[\w/-]+$
      minLength: 0
      maxLength: 64
    DatabaseName:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 512
    DatabaseUrl:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 512
    DatetimeTypeFieldName:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 256
    Description:
      type: string
      pattern: ^[\s\w/!@#+=.-]*$
      minLength: 0
      maxLength: 1024
    DestinationField:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 256
    DocumentType:
      type: string
      pattern: ^[\s\w_-]+$
      minLength: 0
      maxLength: 512
    DomainName:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 64
    EntitiesPath:
      type: string
      pattern: ^[\s\w/!@#+=,.-]*$
      minLength: 0
      maxLength: 256
    EntityName:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 1024
    ErrorMessage:
      type: string
      pattern: ^[\s\w/!@#+=.-]*$
      minLength: 0
      maxLength: 2048
    ExecutionId:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 256
    ExecutionMessage:
      type: string
      pattern: ^[\s\w/!@#+=.-]*$
      minLength: 0
      maxLength: 2048
    FieldType:
      type: string
    FlowArn:
      type: string
      pattern: '^arn:aws:appflow:.*:[0-9]+:'
      minLength: 0
      maxLength: 512
    FlowDescription:
      type: string
      pattern: ^[\w!@#\-.?,\s]*$
      minLength: 0
      maxLength: 2048
    FlowErrorDeactivationThreshold:
      type: integer
      minimum: 1
      maximum: 100
    FlowName:
      type: string
      pattern: ^[a-zA-Z0-9][\w!@#.-]+$
      minLength: 0
      maxLength: 256
    FlowStatusMessage:
      type: string
      pattern: ^[\s\w/!@#+=.-]*$
      minLength: 0
      maxLength: 2048
    GlueDataCatalogDatabaseName:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 0
      maxLength: 255
    GlueDataCatalogIAMRole:
      type: string
      pattern: '^arn:aws:iam:.*:[0-9]+:'
      minLength: 0
      maxLength: 512
    GlueDataCatalogTablePrefix:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 0
      maxLength: 128
    Group:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 128
    Identifier:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 128
    InstanceUrl:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 256
    JavaBoolean:
      type: boolean
    JwtToken:
      type: string
      pattern: ^([a-zA-Z0-9_=]+)\.([a-zA-Z0-9_=]+)\.([a-zA-Z0-9_\-\+\/=]*)$
      minLength: 0
      maxLength: 8000
    KMSArn:
      type: string
      pattern: '^arn:aws:kms:.*:[0-9]+:'
      minLength: 20
      maxLength: 2048
    Key:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 512
    Label:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 128
    ListEntitiesMaxResults:
      type: integer
      minimum: 1
      maximum: 10000
    LogoURL:
      type: string
      pattern: ^(https?|ftp|file)://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]$
      minLength: 0
      maxLength: 256
    LogonLanguage:
      type: string
      pattern: ^[a-zA-Z0-9_]*$
      minLength: 0
      maxLength: 2
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    MostRecentExecutionMessage:
      type: string
      pattern: ^[\w!@#\-.?,\s]*$
      minLength: 0
      maxLength: 2048
    Name:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 128
    NextToken:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 2048
    OAuthScope:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 128
    Object:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 512
    ObjectTypeName:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 255
    Password:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 512
    PortNumber:
      type: integer
      minimum: 1
      maximum: 65535
    PrivateConnectionProvisioningFailureMessage:
      type: string
      pattern: ^[\s\w/!@#+=.-]*$
      minLength: 0
      maxLength: 2048
    PrivateLinkServiceName:
      type: string
      pattern: ^$|com.amazonaws.vpce.[\w/!:@#.\-]+$
      minLength: 0
      maxLength: 512
    ProfilePropertyKey:
      type: string
      pattern: ^[\w]+$
      minLength: 1
      maxLength: 128
    ProfilePropertyValue:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 2048
    Property:
      type: string
      pattern: ^.+$
      minLength: 0
      maxLength: 2048
    RedirectUri:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 512
    RefreshToken:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 4096
    Region:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 64
    RegisteredBy:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 512
    RoleArn:
      type: string
      pattern: '^arn:aws:iam:.*:[0-9]+:'
      minLength: 0
      maxLength: 512
    SAPODataMaxPageSize:
      type: integer
      minimum: 1
      maximum: 10000
    SAPODataMaxParallelism:
      type: integer
      minimum: 1
      maximum: 10
    ScheduleExpression:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 256
    SecretKey:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 256
    Stage:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 512
    String:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 2048
    SupportedApiVersion:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 256
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^[\s\w+-=\.:/@]*$
      minLength: 0
      maxLength: 256
    Timezone:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 256
    TokenUrl:
      type: string
      pattern: ^(https?)://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]$
      minLength: 0
      maxLength: 256
    UpdatedBy:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 256
    UpsolverBucketName:
      type: string
      pattern: ^(upsolver-appflow)\S*$
      minLength: 16
      maxLength: 63
    Username:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 512
    Value:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 128
    Warehouse:
      type: string
      pattern: ^[\s\w/!@#+=.-]*$
      minLength: 0
      maxLength: 512
    WorkgroupName:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 512
