openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: appintegrations
  x-aws-serviceName: appintegrations
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-07-29'
  title: Amazon AppIntegrations Service
  description: |-
    * [Amazon AppIntegrations actions](https://docs.aws.amazon.com/connect/latest/APIReference/API_Operations_Amazon_AppIntegrations_Service.html)

      * [Amazon AppIntegrations data types](https://docs.aws.amazon.com/connect/latest/APIReference/API_Types_Amazon_AppIntegrations_Service.html)

    The Amazon AppIntegrations service enables you to configure and reuse connections to external applications.

    For information about how you can use external applications with Amazon Connect, see the following topics in the _Amazon Connect Administrator Guide_ :

      * [Third-party applications (3p apps) in the agent workspace](https://docs.aws.amazon.com/connect/latest/adminguide/3p-apps.html)

      * [Use Amazon Q in Connect for generative AI–powered agent assistance in real-time](https://docs.aws.amazon.com/connect/latest/adminguide/amazon-q-connect.html)
servers:
- description: The Amazon AppIntegrations Service regional endpoint
  url: https://app-integrations.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ApplicationApprovedOrigins:
      type: array
      items:
        $ref: '#/components/schemas/ApplicationTrustedSource'
    ApplicationAssociationsList:
      type: array
      items:
        $ref: '#/components/schemas/ApplicationAssociationSummary'
    ApplicationName:
      type: string
      pattern: ^[a-zA-Z0-9\/\._ \-]+$
      minLength: 1
      maxLength: 255
    ApplicationNamespace:
      type: string
      pattern: ^[a-zA-Z0-9\/\._\-]+$
      minLength: 1
      maxLength: 32
    ApplicationTrustedSource:
      type: string
      pattern: ^\w+\:\/\/.*$
      minLength: 1
      maxLength: 128
    ApplicationsList:
      type: array
      items:
        $ref: '#/components/schemas/ApplicationSummary'
    Arn:
      type: string
      pattern: ^arn:aws:[A-Za-z0-9][A-Za-z0-9_/.-]{0,62}:[A-Za-z0-9_/.-]{0,63}:[A-Za-z0-9_/.-]{0,63}:[A-Za-z0-9][A-Za-z0-9:_/+=,@.-]{0,1023}$
      minLength: 1
      maxLength: 2048
    ArnOrUUID:
      type: string
      pattern: ^(arn:aws:[A-Za-z0-9][A-Za-z0-9_/.-]{0,62}:[A-Za-z0-9_/.-]{0,63}:[A-Za-z0-9_/.-]{0,63}:[A-Za-z0-9][A-Za-z0-9:_/+=,@.-]{0,1023}|[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})(:[\w\$]+)?$
      minLength: 1
      maxLength: 2048
    ClientAssociationMetadata:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/NonBlankString'
    ClientId:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 255
    DataIntegrationAssociationsList:
      type: array
      items:
        $ref: '#/components/schemas/DataIntegrationAssociationSummary'
    DataIntegrationsList:
      type: array
      items:
        $ref: '#/components/schemas/DataIntegrationSummary'
    Description:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 1000
    DestinationURI:
      type: string
      pattern: ^(\w+\:\/\/[\w.-]+[\w/!@#+=.-]+$)|(\w+\:\/\/[\w.-]+[\w/!@#+=.-]+[\w/!@#+=.-]+[\w/!@#+=.,-]+$)$
      minLength: 1
      maxLength: 1000
    EventBridgeBus:
      type: string
      pattern: ^[a-zA-Z0-9\/\._\-]+$
      minLength: 1
      maxLength: 255
    EventBridgeRuleName:
      type: string
      pattern: ^[a-zA-Z0-9\/\._\-]+$
      minLength: 1
      maxLength: 2048
    EventDefinitionSchema:
      type: string
      pattern: ^.*$
      minLength: 1
      maxLength: 10240
    EventIntegrationAssociationsList:
      type: array
      items:
        $ref: '#/components/schemas/EventIntegrationAssociation'
    EventIntegrationsList:
      type: array
      items:
        $ref: '#/components/schemas/EventIntegration'
    EventName:
      type: string
      pattern: ^[a-zA-Z0-9\/\._\-]+::[a-zA-Z0-9\/\._\-]+(?:\*)?$
      minLength: 1
      maxLength: 255
    ExecutionMode:
      type: string
      enum:
      - ON_DEMAND
      - SCHEDULED
    ExecutionStatus:
      type: string
      enum:
      - COMPLETED
      - IN_PROGRESS
      - FAILED
    Fields:
      type: string
      pattern: ^[a-zA-Z0-9\/\._\-]+$
      minLength: 1
      maxLength: 255
    FieldsList:
      type: array
      items:
        $ref: '#/components/schemas/Fields'
    FieldsMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/FieldsList'
    FolderList:
      type: array
      items:
        $ref: '#/components/schemas/NonBlankLongString'
    IdempotencyToken:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 2048
    Identifier:
      type: string
      pattern: \S
      minLength: 1
      maxLength: 255
    MaxResults:
      type: integer
      minimum: 1
      maximum: 50
    Message:
      type: string
    Name:
      type: string
      pattern: ^[a-zA-Z0-9\/\._\-]+$
      minLength: 1
      maxLength: 255
    NextToken:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 1000
    NonBlankLongString:
      type: string
      pattern: \S
      minLength: 1
      maxLength: 200
    NonBlankString:
      type: string
      pattern: \S
      minLength: 1
      maxLength: 255
    Object:
      type: string
      pattern: ^[a-zA-Z0-9\/\._\-]+$
      minLength: 1
      maxLength: 255
    ObjectConfiguration:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/FieldsMap'
      description: <p>The configuration for what data should be pulled from the source.</p>
    Permission:
      type: string
      pattern: ^[a-zA-Z0-9\/\._\-\*]+$
      minLength: 1
      maxLength: 255
    PermissionList:
      type: array
      items:
        $ref: '#/components/schemas/Permission'
    PublicationList:
      type: array
      items:
        $ref: '#/components/schemas/Publication'
    Source:
      type: string
      pattern: ^aws\.partner\/.*$
      minLength: 1
      maxLength: 256
    SourceURI:
      type: string
      pattern: ^(\w+\:\/\/[\w.-]+[\w/!@#+=.-]+$)|(\w+\:\/\/[\w.-]+[\w/!@#+=.-]+[\w/!@#+=.-]+[\w/!@#+=.,-]+$)$
      minLength: 1
      maxLength: 1000
    SubscriptionList:
      type: array
      items:
        $ref: '#/components/schemas/Subscription'
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    Timestamp:
      type: string
      format: date-time
    URL:
      type: string
      pattern: ^\w+\:\/\/.*$
      minLength: 1
      maxLength: 1000
    UUID:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
