openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: application_signals
  x-aws-serviceName: applicationsignals
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2024-04-15'
  title: Amazon CloudWatch Application Signals
  description: "Use CloudWatch Application Signals for comprehensive observability\
    \ of your cloud-based applications. It enables real-time service health dashboards\
    \ and helps you track long-term performance trends against your business goals.\
    \ The application-centric view provides you with unified visibility across your\
    \ applications, services, and dependencies, so you can proactively monitor and\
    \ efficiently triage any issues that may arise, ensuring optimal customer experience.\n\
    \nApplication Signals provides the following benefits:\n\n  * Automatically collect\
    \ metrics and traces from your applications, and display key metrics such as call\
    \ volume, availability, latency, faults, and errors. \n\n  * Create and monitor\
    \ service level objectives (SLOs). \n\n  * See a map of your application topology\
    \ that Application Signals automatically discovers, that gives you a visual representation\
    \ of your applications, dependencies, and their connectivity.\n\nApplication Signals\
    \ works with CloudWatch RUM, CloudWatch Synthetics canaries, and Amazon Web Services\
    \ Service Catalog AppRegistry, to display your client pages, Synthetics canaries,\
    \ and application names within dashboards and maps."
servers:
- description: The Amazon CloudWatch Application Signals regional endpoint
  url: https://application-signals.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccountId:
      type: string
      minLength: 1
      maxLength: 255
    AmazonResourceName:
      type: string
      minLength: 1
      maxLength: 1024
    Attainment:
      type: number
      format: double
    AttainmentGoal:
      type: number
      format: double
    AttributeMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    AttributeMaps:
      type: array
      items:
        $ref: '#/components/schemas/AttributeMap'
    Attributes:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/KeyAttributeValue'
    AwsAccountId:
      type: string
      pattern: ^[0-9]{12}$
    BatchUpdateExclusionWindowsErrors:
      type: array
      items:
        $ref: '#/components/schemas/BatchUpdateExclusionWindowsError'
    BudgetRequestsRemaining:
      type: integer
    BudgetSecondsRemaining:
      type: integer
    BurnRateConfigurations:
      type: array
      items:
        $ref: '#/components/schemas/BurnRateConfiguration'
    BurnRateLookBackWindowMinutes:
      type: integer
      minimum: 1
      maximum: 10080
    CalendarIntervalDuration:
      type: integer
      minimum: 1
    DimensionName:
      type: string
      minLength: 1
      maxLength: 255
    DimensionValue:
      type: string
      minLength: 1
      maxLength: 1024
    Dimensions:
      type: array
      items:
        $ref: '#/components/schemas/Dimension'
    DurationUnit:
      type: string
      enum:
      - MINUTE
      - HOUR
      - DAY
      - MONTH
    EvaluationType:
      type: string
      enum:
      - PeriodBased
      - RequestBased
    ExclusionDuration:
      type: integer
      minimum: 1
    ExclusionReason:
      type: string
      minLength: 1
      maxLength: 1024
    ExclusionWindowErrorCode:
      type: string
    ExclusionWindowErrorMessage:
      type: string
    ExclusionWindows:
      type: array
      items:
        $ref: '#/components/schemas/ExclusionWindow'
    Expression:
      type: string
      minLength: 1
      maxLength: 1024
    FaultDescription:
      type: string
    Interval:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/RollingInterval'
        description: |-
          If the interval is a rolling interval, this structure contains the interval specifications.
      - allOf:
        - $ref: '#/components/schemas/CalendarInterval'
        description: |-
          If the interval is a calendar interval, this structure contains the interval specifications.
      description: |-
        The time period used to evaluate the SLO. It can be either a calendar interval or rolling interval.
    KeyAttributeName:
      type: string
      pattern: ^[a-zA-Z]{1,50}$
    KeyAttributeValue:
      type: string
      pattern: ^[ -~]*[!-~]+[ -~]*$
      minLength: 1
      maxLength: 1024
    ListServiceDependenciesMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListServiceDependentsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListServiceLevelObjectiveExclusionWindowsMaxResults:
      type: integer
      minimum: 1
      maximum: 10
    ListServiceLevelObjectivesMaxResults:
      type: integer
      minimum: 1
      maximum: 50
    ListServiceOperationMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListServicesMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    LogGroupReferences:
      type: array
      items:
        $ref: '#/components/schemas/Attributes'
    MetricDataQueries:
      type: array
      items:
        $ref: '#/components/schemas/MetricDataQuery'
    MetricExpression:
      type: string
      minLength: 1
      maxLength: 2048
    MetricId:
      type: string
      minLength: 1
      maxLength: 255
    MetricLabel:
      type: string
    MetricName:
      type: string
      minLength: 1
      maxLength: 255
    MetricReferences:
      type: array
      items:
        $ref: '#/components/schemas/MetricReference'
    MetricSourceType:
      type: string
      enum:
      - ServiceOperation
      - CloudWatchMetric
      - ServiceDependency
    MetricSourceTypes:
      type: array
      items:
        $ref: '#/components/schemas/MetricSourceType'
    MetricType:
      type: string
      pattern: ^[A-Za-z0-9 -]+$
    MonitoredRequestCountMetricDataQueries:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/MetricDataQueries'
        description: |-
          If you want to count "good requests" to determine the percentage of successful requests for this request-based SLO, specify the metric to use as "good requests" in this structure.
      - allOf:
        - $ref: '#/components/schemas/MetricDataQueries'
        description: |-
          If you want to count "bad requests" to determine the percentage of successful requests for this request-based SLO, specify the metric to use as "bad requests" in this structure.
      description: |-
        This structure defines the metric that is used as the "good request" or "bad request" value for a request-based SLO. This value observed for the metric defined in `TotalRequestCountMetric` is divided by the number found for `MonitoredRequestCountMetric` to determine the percentage of successful requests that this SLO tracks.
    Namespace:
      type: string
      pattern: '[^:].*'
      minLength: 1
      maxLength: 255
    NextToken:
      type: string
    OperationName:
      type: string
      minLength: 1
      maxLength: 255
    Period:
      type: integer
      minimum: 1
    ResourceId:
      type: string
    ResourceType:
      type: string
    ReturnData:
      type: boolean
    RollingIntervalDuration:
      type: integer
      minimum: 1
    SLIPeriodSeconds:
      type: integer
      minimum: 60
      maximum: 900
    ServiceDependencies:
      type: array
      items:
        $ref: '#/components/schemas/ServiceDependency'
    ServiceDependents:
      type: array
      items:
        $ref: '#/components/schemas/ServiceDependent'
    ServiceErrorMessage:
      type: string
    ServiceLevelIndicatorComparisonOperator:
      type: string
      enum:
      - GreaterThanOrEqualTo
      - GreaterThan
      - LessThan
      - LessThanOrEqualTo
    ServiceLevelIndicatorMetricThreshold:
      type: number
      format: double
    ServiceLevelIndicatorMetricType:
      type: string
      enum:
      - LATENCY
      - AVAILABILITY
    ServiceLevelIndicatorStatistic:
      type: string
      pattern: ^[a-zA-Z0-9.]+$
      minLength: 1
      maxLength: 20
    ServiceLevelObjectiveArn:
      type: string
      pattern: ^arn:aws:application-signals:[^:]*:[^:]*:slo/[0-9A-Za-z][-._0-9A-Za-z
        ]{0,126}[0-9A-Za-z]$
      minLength: 1
      maxLength: 2048
    ServiceLevelObjectiveBudgetReportErrorCode:
      type: string
    ServiceLevelObjectiveBudgetReportErrorMessage:
      type: string
    ServiceLevelObjectiveBudgetReportErrors:
      type: array
      items:
        $ref: '#/components/schemas/ServiceLevelObjectiveBudgetReportError'
    ServiceLevelObjectiveBudgetReports:
      type: array
      items:
        $ref: '#/components/schemas/ServiceLevelObjectiveBudgetReport'
    ServiceLevelObjectiveBudgetStatus:
      type: string
      enum:
      - OK
      - WARNING
      - BREACHED
      - INSUFFICIENT_DATA
    ServiceLevelObjectiveDescription:
      type: string
      minLength: 1
      maxLength: 1024
    ServiceLevelObjectiveId:
      type: string
      pattern: ^[0-9A-Za-z][-._0-9A-Za-z ]{0,126}[0-9A-Za-z]$|^arn:aws:application-signals:[^:]*:[^:]*:slo/[0-9A-Za-z][-._0-9A-Za-z
        ]{0,126}[0-9A-Za-z]$
    ServiceLevelObjectiveIds:
      type: array
      items:
        type: string
    ServiceLevelObjectiveName:
      type: string
      pattern: ^[0-9A-Za-z][-._0-9A-Za-z ]{0,126}[0-9A-Za-z]$
    ServiceLevelObjectiveSummaries:
      type: array
      items:
        $ref: '#/components/schemas/ServiceLevelObjectiveSummary'
    ServiceOperations:
      type: array
      items:
        $ref: '#/components/schemas/ServiceOperation'
    ServiceSummaries:
      type: array
      items:
        $ref: '#/components/schemas/ServiceSummary'
    StandardUnit:
      type: string
      enum:
      - Microseconds
      - Milliseconds
      - Seconds
      - Bytes
      - Kilobytes
      - Megabytes
      - Gigabytes
      - Terabytes
      - Bits
      - Kilobits
      - Megabits
      - Gigabits
      - Terabits
      - Percent
      - Count
      - Bytes/Second
      - Kilobytes/Second
      - Megabytes/Second
      - Gigabytes/Second
      - Terabytes/Second
      - Bits/Second
      - Kilobits/Second
      - Megabits/Second
      - Gigabits/Second
      - Terabits/Second
      - Count/Second
      - None
    Stat:
      type: string
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagList:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TotalBudgetRequests:
      type: integer
    TotalBudgetSeconds:
      type: integer
    ValidationExceptionMessage:
      type: string
    WarningThreshold:
      type: number
      format: double
