openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: application_signals
  x-aws-serviceName: applicationsignals
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2024-04-15'
  title: Amazon CloudWatch Application Signals
  description: "Use CloudWatch Application Signals for comprehensive observability\
    \ of your cloud-based applications. It enables real-time service health dashboards\
    \ and helps you track long-term performance trends against your business goals.\
    \ The application-centric view provides you with unified visibility across your\
    \ applications, services, and dependencies, so you can proactively monitor and\
    \ efficiently triage any issues that may arise, ensuring optimal customer experience.\n\
    \nApplication Signals provides the following benefits:\n\n  * Automatically collect\
    \ metrics and traces from your applications, and display key metrics such as call\
    \ volume, availability, latency, faults, and errors. \n\n  * Create and monitor\
    \ service level objectives (SLOs). \n\n  * See a map of your application topology\
    \ that Application Signals automatically discovers, that gives you a visual representation\
    \ of your applications, dependencies, and their connectivity.\n\nApplication Signals\
    \ works with CloudWatch RUM, CloudWatch Synthetics canaries, and Amazon Web Services\
    \ Service Catalog AppRegistry, to display your client pages, Synthetics canaries,\
    \ and application names within dashboards and maps."
servers:
- description: The Amazon CloudWatch Application Signals regional endpoint
  url: https://application-signals.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas: {}
