openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: app_mesh
  x-aws-serviceName: appmesh
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2019-01-25'
  title: AWS App Mesh
  description: |-
    App Mesh is a service mesh based on the Envoy proxy that makes it easy to monitor and control microservices. App Mesh standardizes how your microservices communicate, giving you end-to-end visibility and helping to ensure high availability for your applications.

    App Mesh gives you consistent visibility and network traffic controls for every microservice in an application. You can use App Mesh with Amazon Web Services Fargate, Amazon ECS, Amazon EKS, Kubernetes on Amazon Web Services, and Amazon EC2.

    App Mesh supports microservice applications that use service discovery naming for their components. For more information about service discovery on Amazon ECS, see [Service Discovery](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-discovery.html) in the _Amazon Elastic Container Service Developer Guide_. Kubernetes `kube-dns` and `coredns` are supported. For more information, see [DNS for Services and Pods](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/) in the Kubernetes documentation.
servers:
- description: The AWS App Mesh regional endpoint
  url: https://appmesh.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccountId:
      type: string
      minLength: 12
      maxLength: 12
    Arn:
      type: string
    AwsCloudMapInstanceAttributeKey:
      type: string
      pattern: ^[a-zA-Z0-9!-~]+$
      minLength: 1
      maxLength: 255
    AwsCloudMapInstanceAttributeValue:
      type: string
      pattern: "^([a-zA-Z0-9!-~][ \ta-zA-Z0-9!-~]*){0,1}[a-zA-Z0-9!-~]{0,1}$"
      minLength: 1
      maxLength: 1024
    AwsCloudMapName:
      type: string
      minLength: 1
      maxLength: 1024
    DefaultGatewayRouteRewrite:
      type: string
      enum:
      - ENABLED
      - DISABLED
    DnsResponseType:
      type: string
      enum:
      - LOADBALANCER
      - ENDPOINTS
    DurationUnit:
      type: string
      enum:
      - s
      - ms
    EgressFilterType:
      type: string
      enum:
      - ALLOW_ALL
      - DROP_ALL
    ExactHostName:
      type: string
      minLength: 1
      maxLength: 253
    FilePath:
      type: string
      minLength: 1
      maxLength: 255
    GatewayRoutePriority:
      type: integer
      minimum: 0
      maximum: 1000
    GatewayRouteStatusCode:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
      - DELETED
    GrpcRetryPolicyEvent:
      type: string
      enum:
      - cancelled
      - deadline-exceeded
      - internal
      - resource-exhausted
      - unavailable
    HeaderMatch:
      type: string
      minLength: 1
      maxLength: 255
    HeaderName:
      type: string
      minLength: 1
      maxLength: 50
    HealthCheckThreshold:
      type: integer
      minimum: 2
      maximum: 10
    Hostname:
      type: string
    HttpGatewayRoutePrefix:
      type: string
      minLength: 1
      maxLength: 255
    HttpMethod:
      type: string
      enum:
      - GET
      - HEAD
      - POST
      - PUT
      - DELETE
      - CONNECT
      - OPTIONS
      - TRACE
      - PATCH
    HttpPathExact:
      type: string
      minLength: 1
      maxLength: 255
    HttpPathRegex:
      type: string
      minLength: 1
      maxLength: 255
    HttpRetryPolicyEvent:
      type: string
      minLength: 1
      maxLength: 25
    HttpScheme:
      type: string
      enum:
      - http
      - https
    IpPreference:
      type: string
      enum:
      - IPv6_PREFERRED
      - IPv4_PREFERRED
      - IPv4_ONLY
      - IPv6_ONLY
    JsonKey:
      type: string
      minLength: 1
      maxLength: 100
    JsonValue:
      type: string
      minLength: 1
      maxLength: 100
    ListGatewayRoutesLimit:
      type: integer
      minimum: 1
      maximum: 100
    ListMeshesLimit:
      type: integer
      minimum: 1
      maximum: 100
    ListRoutesLimit:
      type: integer
      minimum: 1
      maximum: 100
    ListVirtualGatewaysLimit:
      type: integer
      minimum: 1
      maximum: 100
    ListVirtualNodesLimit:
      type: integer
      minimum: 1
      maximum: 100
    ListVirtualRoutersLimit:
      type: integer
      minimum: 1
      maximum: 100
    ListVirtualServicesLimit:
      type: integer
      minimum: 1
      maximum: 100
    ListenerPort:
      type: integer
      minimum: 1
      maximum: 65535
    ListenerTlsMode:
      type: string
      enum:
      - STRICT
      - PERMISSIVE
      - DISABLED
    MaxConnections:
      type: integer
      minimum: 1
    MaxPendingRequests:
      type: integer
      minimum: 1
    MaxRequests:
      type: integer
      minimum: 1
    MeshStatusCode:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
      - DELETED
    MethodName:
      type: string
      minLength: 1
      maxLength: 50
    OutlierDetectionMaxEjectionPercent:
      type: integer
      minimum: 0
      maximum: 100
    PercentInt:
      type: integer
      default: 0
      minimum: 0
      maximum: 100
    PortNumber:
      type: integer
      minimum: 1
      maximum: 65535
    PortProtocol:
      type: string
      enum:
      - http
      - tcp
      - http2
      - grpc
    QueryParameterName:
      type: string
    ResourceName:
      type: string
      minLength: 1
      maxLength: 255
    RoutePriority:
      type: integer
      minimum: 0
      maximum: 1000
    RouteStatusCode:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
      - DELETED
    SdsSecretName:
      type: string
    ServiceName:
      type: string
    SubjectAlternativeName:
      type: string
      minLength: 1
      maxLength: 254
    SuffixHostname:
      type: string
      minLength: 1
      maxLength: 253
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TagsLimit:
      type: integer
      minimum: 1
      maximum: 50
    TcpRetryPolicyEvent:
      type: string
      enum:
      - connection-error
    TextFormat:
      type: string
      minLength: 1
      maxLength: 1000
    VirtualGatewayHealthCheckThreshold:
      type: integer
      minimum: 2
      maximum: 10
    VirtualGatewayListenerTlsMode:
      type: string
      enum:
      - STRICT
      - PERMISSIVE
      - DISABLED
    VirtualGatewayPortProtocol:
      type: string
      enum:
      - http
      - http2
      - grpc
    VirtualGatewaySdsSecretName:
      type: string
    VirtualGatewayStatusCode:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
      - DELETED
    VirtualNodeStatusCode:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
      - DELETED
    VirtualRouterStatusCode:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
      - DELETED
    VirtualServiceStatusCode:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
      - DELETED
