openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: appsync
  x-aws-serviceName: appsync
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-07-25'
  title: AWS AppSync
  description: |-
    AppSync provides API actions for creating and interacting with data sources using GraphQL from your application.
servers:
- description: The AWS AppSync regional endpoint
  url: https://appsync.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AdditionalAuthenticationProviders:
      type: array
      items:
        $ref: '#/components/schemas/AdditionalAuthenticationProvider'
    ApiCacheStatus:
      type: string
      enum:
      - AVAILABLE
      - CREATING
      - DELETING
      - MODIFYING
      - FAILED
    ApiCacheType:
      type: string
      enum:
      - T2_SMALL
      - T2_MEDIUM
      - R4_LARGE
      - R4_XLARGE
      - R4_2XLARGE
      - R4_4XLARGE
      - R4_8XLARGE
      - SMALL
      - MEDIUM
      - LARGE
      - XLARGE
      - LARGE_2X
      - LARGE_4X
      - LARGE_8X
      - LARGE_12X
    ApiCachingBehavior:
      type: string
      enum:
      - FULL_REQUEST_CACHING
      - PER_RESOLVER_CACHING
      - OPERATION_LEVEL_CACHING
    ApiKeys:
      type: array
      items:
        $ref: '#/components/schemas/ApiKey'
    ApiName:
      type: string
      pattern: ^[A-Za-z0-9_\-\ ]+$
      minLength: 1
      maxLength: 50
    Apis:
      type: array
      items:
        $ref: '#/components/schemas/Api'
    AssociationStatus:
      type: string
      enum:
      - PROCESSING
      - FAILED
      - SUCCESS
    AuthModes:
      type: array
      items:
        $ref: '#/components/schemas/AuthMode'
    AuthProviders:
      type: array
      items:
        $ref: '#/components/schemas/AuthProvider'
    AuthenticationType:
      type: string
      enum:
      - API_KEY
      - AWS_IAM
      - AMAZON_COGNITO_USER_POOLS
      - OPENID_CONNECT
      - AWS_LAMBDA
    AuthorizationType:
      type: string
      enum:
      - AWS_IAM
    BadRequestReason:
      type: string
      enum:
      - CODE_ERROR
      description: "<p>Provides context for the cause of the bad request. The only\
        \ supported value is\n            <code>CODE_ERROR</code>.</p>"
    Blob:
      type: string
      format: byte
    Boolean:
      type: boolean
      default: false
    BooleanValue:
      type: boolean
    CacheHealthMetricsConfig:
      type: string
      enum:
      - ENABLED
      - DISABLED
    CachingKeys:
      type: array
      items:
        $ref: '#/components/schemas/String'
    CertificateArn:
      type: string
      pattern: ^arn:[a-z-]*:(acm|iam):[a-z0-9-]*:\d{12}:(certificate|server-certificate)/[0-9A-Za-z_/-]*$
      minLength: 20
      maxLength: 2048
    ChannelNamespaces:
      type: array
      items:
        $ref: '#/components/schemas/ChannelNamespace'
    Code:
      type: string
      minLength: 1
      maxLength: 32768
    CodeErrorColumn:
      type: integer
      default: 0
    CodeErrorLine:
      type: integer
      default: 0
    CodeErrorSpan:
      type: integer
      default: 0
    CodeErrors:
      type: array
      items:
        $ref: '#/components/schemas/CodeError'
    ConflictDetectionType:
      type: string
      enum:
      - VERSION
      - NONE
    ConflictHandlerType:
      type: string
      enum:
      - OPTIMISTIC_CONCURRENCY
      - LAMBDA
      - AUTOMERGE
      - NONE
    Context:
      type: string
      pattern: ^[\s\S]*$
      minLength: 2
      maxLength: 28000
    DataSourceIntrospectionModelFieldTypeValues:
      type: array
      items:
        $ref: '#/components/schemas/String'
    DataSourceIntrospectionModelFields:
      type: array
      items:
        $ref: '#/components/schemas/DataSourceIntrospectionModelField'
    DataSourceIntrospectionModelIndexFields:
      type: array
      items:
        $ref: '#/components/schemas/String'
    DataSourceIntrospectionModelIndexes:
      type: array
      items:
        $ref: '#/components/schemas/DataSourceIntrospectionModelIndex'
    DataSourceIntrospectionModels:
      type: array
      items:
        $ref: '#/components/schemas/DataSourceIntrospectionModel'
    DataSourceIntrospectionStatus:
      type: string
      enum:
      - PROCESSING
      - FAILED
      - SUCCESS
    DataSourceLevelMetricsBehavior:
      type: string
      enum:
      - FULL_REQUEST_DATA_SOURCE_METRICS
      - PER_DATA_SOURCE_METRICS
    DataSourceLevelMetricsConfig:
      type: string
      enum:
      - ENABLED
      - DISABLED
    DataSourceType:
      type: string
      enum:
      - AWS_LAMBDA
      - AMAZON_DYNAMODB
      - AMAZON_ELASTICSEARCH
      - NONE
      - HTTP
      - RELATIONAL_DATABASE
      - AMAZON_OPENSEARCH_SERVICE
      - AMAZON_EVENTBRIDGE
      - AMAZON_BEDROCK_RUNTIME
    DataSources:
      type: array
      items:
        $ref: '#/components/schemas/DataSource'
    Date:
      type: string
      format: date-time
    DefaultAction:
      type: string
      enum:
      - ALLOW
      - DENY
    Description:
      type: string
      pattern: ^.*$
      minLength: 0
      maxLength: 255
    DomainName:
      type: string
      pattern: ^(\*[\w\d-]*\.)?([\w\d-]+\.)+[\w\d-]+$
      minLength: 1
      maxLength: 253
    DomainNameConfigs:
      type: array
      items:
        $ref: '#/components/schemas/DomainNameConfig'
    EnvironmentVariableKey:
      type: string
      pattern: ^[A-Za-z]+\w*$
      minLength: 2
      maxLength: 64
    EnvironmentVariableMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/EnvironmentVariableValue'
    EnvironmentVariableValue:
      type: string
      minLength: 0
      maxLength: 512
    ErrorMessage:
      type: string
    EvaluationResult:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 65536
    EventLogLevel:
      type: string
      enum:
      - NONE
      - ERROR
      - ALL
      - INFO
      - DEBUG
    FieldLogLevel:
      type: string
      enum:
      - NONE
      - ERROR
      - ALL
      - INFO
      - DEBUG
    Functions:
      type: array
      items:
        $ref: '#/components/schemas/FunctionConfiguration'
    FunctionsIds:
      type: array
      items:
        $ref: '#/components/schemas/String'
    GraphQLApiIntrospectionConfig:
      type: string
      enum:
      - ENABLED
      - DISABLED
    GraphQLApiType:
      type: string
      enum:
      - GRAPHQL
      - MERGED
    GraphQLApiVisibility:
      type: string
      enum:
      - GLOBAL
      - PRIVATE
    GraphqlApis:
      type: array
      items:
        $ref: '#/components/schemas/GraphqlApi'
    HandlerBehavior:
      type: string
      enum:
      - CODE
      - DIRECT
    InvokeType:
      type: string
      enum:
      - REQUEST_RESPONSE
      - EVENT
    Logs:
      type: array
      items:
        $ref: '#/components/schemas/String'
    Long:
      type: integer
      format: int64
      default: 0
    MapOfStringToString:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    MappingTemplate:
      type: string
      pattern: ^.*$
      minLength: 1
      maxLength: 65536
    MaxBatchSize:
      type: integer
      default: 0
      minimum: 0
      maximum: 2000
    MaxResults:
      type: integer
      default: 0
      minimum: 0
      maximum: 25
    MergeType:
      type: string
      enum:
      - MANUAL_MERGE
      - AUTO_MERGE
    Namespace:
      type: string
      pattern: ^([A-Za-z0-9](?:[A-Za-z0-9\-]{0,48}[A-Za-z0-9])?)$
      minLength: 1
      maxLength: 50
    OperationLevelMetricsConfig:
      type: string
      enum:
      - ENABLED
      - DISABLED
    OutErrors:
      type: string
      pattern: ^[\s\S]*$
    OutputType:
      type: string
      enum:
      - SDL
      - JSON
    OwnerContact:
      type: string
      pattern: ^[A-Za-z0-9_\-\ \.]+$
      minLength: 0
      maxLength: 250
    Ownership:
      type: string
      enum:
      - CURRENT_ACCOUNT
      - OTHER_ACCOUNTS
    PaginationToken:
      type: string
      pattern: ^[\S]+$
      minLength: 1
      maxLength: 65536
    QueryDepthLimit:
      type: integer
      default: 0
      minimum: 0
      maximum: 75
    RdsDataApiConfigDatabaseName:
      type: string
      minLength: 1
      maxLength: 128
    RdsDataApiConfigResourceArn:
      type: string
      pattern: ^arn:[a-z-]*:rds:[a-z0-9-]*:\d{12}:cluster:[0-9A-Za-z_/-]*$
      minLength: 20
      maxLength: 2048
    RdsDataApiConfigSecretArn:
      type: string
      pattern: ^arn:[a-z-]*:secretsmanager:[a-z0-9-]*:\d{12}:secret:[0-9A-Za-z_/+=.@!-]*$
      minLength: 20
      maxLength: 2048
    RelationalDatabaseSourceType:
      type: string
      enum:
      - RDS_HTTP_ENDPOINT
    ResolverCountLimit:
      type: integer
      default: 0
      minimum: 0
      maximum: 10000
    ResolverKind:
      type: string
      enum:
      - UNIT
      - PIPELINE
    ResolverLevelMetricsBehavior:
      type: string
      enum:
      - FULL_REQUEST_RESOLVER_METRICS
      - PER_RESOLVER_METRICS
    ResolverLevelMetricsConfig:
      type: string
      enum:
      - ENABLED
      - DISABLED
    Resolvers:
      type: array
      items:
        $ref: '#/components/schemas/Resolver'
    ResourceArn:
      type: string
      pattern: ^arn:aws:appsync:[A-Za-z0-9_/.-]{0,63}:\d{12}:apis/[0-9A-Za-z_-]{26}$
      minLength: 70
      maxLength: 75
    ResourceName:
      type: string
      pattern: ^[_A-Za-z][_0-9A-Za-z]*$
      minLength: 1
      maxLength: 65536
    RuntimeName:
      type: string
      enum:
      - APPSYNC_JS
    SchemaStatus:
      type: string
      enum:
      - PROCESSING
      - ACTIVE
      - DELETING
      - FAILED
      - SUCCESS
      - NOT_APPLICABLE
    SourceApiAssociationStatus:
      type: string
      enum:
      - MERGE_SCHEDULED
      - MERGE_FAILED
      - MERGE_SUCCESS
      - MERGE_IN_PROGRESS
      - AUTO_MERGE_SCHEDULE_FAILED
      - DELETION_SCHEDULED
      - DELETION_IN_PROGRESS
      - DELETION_FAILED
    SourceApiAssociationSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/SourceApiAssociationSummary'
    Stash:
      type: string
      pattern: ^[\s\S]*$
    String:
      type: string
    TTL:
      type: integer
      default: 0
      minimum: 0
      maximum: 3600
    TagKey:
      type: string
      pattern: ^(?!aws:)[ a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
      description: "<p>A map with keys of <code>TagKey</code> objects and values of\
        \ <code>TagValue</code>\n         objects.</p>"
    TagValue:
      type: string
      pattern: ^[\s\w+-=\.:/@]*$
      minLength: 0
      maxLength: 256
    Template:
      type: string
      pattern: ^[\s\S]*$
      minLength: 2
      maxLength: 65536
    Timestamp:
      type: string
      format: date-time
    TypeDefinitionFormat:
      type: string
      enum:
      - SDL
      - JSON
    TypeList:
      type: array
      items:
        $ref: '#/components/schemas/Type'
