openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: appsync
  x-aws-serviceName: appsync
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-07-25'
  title: AWS AppSync
  description: |-
    AppSync provides API actions for creating and interacting with data sources using GraphQL from your application.
servers:
- description: The AWS AppSync regional endpoint
  url: https://appsync.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ApiName:
      type: string
      pattern: ^[A-Za-z0-9_\-\ ]+$
      minLength: 1
      maxLength: 50
    Boolean:
      type: boolean
      default: false
    BooleanValue:
      type: boolean
    CertificateArn:
      type: string
      pattern: ^arn:[a-z-]*:(acm|iam):[a-z0-9-]*:\d{12}:(certificate|server-certificate)/[0-9A-Za-z_/-]*$
      minLength: 20
      maxLength: 2048
    Code:
      type: string
      minLength: 1
      maxLength: 32768
    CodeErrorColumn:
      type: integer
      default: 0
    CodeErrorLine:
      type: integer
      default: 0
    CodeErrorSpan:
      type: integer
      default: 0
    Context:
      type: string
      pattern: ^[\s\S]*$
      minLength: 2
      maxLength: 28000
    Description:
      type: string
      pattern: ^.*$
      minLength: 0
      maxLength: 255
    DomainName:
      type: string
      pattern: ^(\*[\w\d-]*\.)?([\w\d-]+\.)+[\w\d-]+$
      minLength: 1
      maxLength: 253
    EnvironmentVariableKey:
      type: string
      pattern: ^[A-Za-z]+\w*$
      minLength: 2
      maxLength: 64
    EnvironmentVariableValue:
      type: string
      minLength: 0
      maxLength: 512
    ErrorMessage:
      type: string
    EvaluationResult:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 65536
    MappingTemplate:
      type: string
      pattern: ^.*$
      minLength: 1
      maxLength: 65536
    MaxBatchSize:
      type: integer
      default: 0
      minimum: 0
      maximum: 2000
    MaxResults:
      type: integer
      default: 0
      minimum: 0
      maximum: 25
    Namespace:
      type: string
      pattern: ^([A-Za-z0-9](?:[A-Za-z0-9\-]{0,48}[A-Za-z0-9])?)$
      minLength: 1
      maxLength: 50
    OutErrors:
      type: string
      pattern: ^[\s\S]*$
    OwnerContact:
      type: string
      pattern: ^[A-Za-z0-9_\-\ \.]+$
      minLength: 0
      maxLength: 250
    PaginationToken:
      type: string
      pattern: ^[\S]+$
      minLength: 1
      maxLength: 65536
    QueryDepthLimit:
      type: integer
      default: 0
      minimum: 0
      maximum: 75
    RdsDataApiConfigDatabaseName:
      type: string
      minLength: 1
      maxLength: 128
    RdsDataApiConfigResourceArn:
      type: string
      pattern: ^arn:[a-z-]*:rds:[a-z0-9-]*:\d{12}:cluster:[0-9A-Za-z_/-]*$
      minLength: 20
      maxLength: 2048
    RdsDataApiConfigSecretArn:
      type: string
      pattern: ^arn:[a-z-]*:secretsmanager:[a-z0-9-]*:\d{12}:secret:[0-9A-Za-z_/+=.@!-]*$
      minLength: 20
      maxLength: 2048
    ResolverCountLimit:
      type: integer
      default: 0
      minimum: 0
      maximum: 10000
    ResourceArn:
      type: string
      pattern: ^arn:aws:appsync:[A-Za-z0-9_/.-]{0,63}:\d{12}:apis/[0-9A-Za-z_-]{26}$
      minLength: 70
      maxLength: 75
    ResourceName:
      type: string
      pattern: ^[_A-Za-z][_0-9A-Za-z]*$
      minLength: 1
      maxLength: 65536
    Stash:
      type: string
      pattern: ^[\s\S]*$
    String:
      type: string
    TTL:
      type: integer
      default: 0
      minimum: 0
      maximum: 3600
    TagKey:
      type: string
      pattern: ^(?!aws:)[ a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^[\s\w+-=\.:/@]*$
      minLength: 0
      maxLength: 256
    Template:
      type: string
      pattern: ^[\s\S]*$
      minLength: 2
      maxLength: 65536
