openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: apptest
  x-aws-serviceName: apptest
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2022-12-06'
  title: AWS Mainframe Modernization Application Testing
  description: |-
    AWS Mainframe Modernization Application Testing provides tools and resources for automated functional equivalence testing for your migration projects.
servers:
- description: The AWS Mainframe Modernization Application Testing regional endpoint
  url: https://apptest.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Arn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-iso|aws-iso-[a-z]{1}|aws-us-gov):[A-Za-z0-9][A-Za-z0-9_/.-]{0,62}:([a-z]{2}-((iso[a-z]{0,1}-)|(gov-)){0,1}[a-z]+-[0-9]):[0-9]{12}:[A-Za-z0-9/][A-Za-z0-9:_/+=,@.-]{0,1023}$
    BatchJobParameters:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    CaptureTool:
      type: string
      enum:
      - Precisely
      - AWS DMS
    CloudFormationActionType:
      type: string
      enum:
      - Create
      - Delete
    CloudFormationStepSummary:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/CreateCloudFormationSummary'
        description: |-
          Creates the CloudFormation summary of the step.
      - allOf:
        - $ref: '#/components/schemas/DeleteCloudFormationSummary'
        description: |-
          Deletes the CloudFormation summary of the CloudFormation step summary.
      description: |-
        Specifies the CloudFormation step summary.
    CompareFileType:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/CompareDataSetsSummary'
        description: |-
          The data sets in the compare file type.
      - allOf:
        - $ref: '#/components/schemas/CompareDatabaseCDCSummary'
        description: |-
          The database CDC of the compare file type.
      description: |-
        Compares the file type.
    ComparisonStatusEnum:
      type: string
      enum:
      - Different
      - Equivalent
      - Equal
    DataSetList:
      type: array
      items:
        $ref: '#/components/schemas/DataSet'
    DataSetType:
      type: string
      enum:
      - PS
    ExportDataSetNames:
      type: array
      items:
        $ref: '#/components/schemas/String100'
    File:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/CompareFileType'
        description: |-
          The file type of the file.
      description: |-
        Defines a file.
    FileMetadata:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/DataSetList'
        description: |-
          The data sets of the file metadata.
      - allOf:
        - $ref: '#/components/schemas/DatabaseCDC'
        description: |-
          The database CDC of the file metadata.
      description: |-
        Specifies a file metadata.
    Format:
      type: string
      enum:
      - FIXED
      - VARIABLE
      - LINE_SEQUENTIAL
    IdempotencyTokenString:
      type: string
      pattern: ^[A-Za-z0-9\-]{1,64}$
    Identifier:
      type: string
      pattern: ^[A-Za-z0-9:/\-]{1,100}$
    Input:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/InputFile'
        description: |-
          The file in the input.
      description: |-
        Specifies the input.
    M2ManagedActionType:
      type: string
      enum:
      - Configure
      - Deconfigure
    M2ManagedRuntime:
      type: string
      enum:
      - MicroFocus
    M2NonManagedActionType:
      type: string
      enum:
      - Configure
      - Deconfigure
    M2NonManagedRuntime:
      type: string
      enum:
      - BluAge
    MainframeActionSummary:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/BatchSummary'
        description: |-
          The batch of the mainframe action summary.
      - allOf:
        - $ref: '#/components/schemas/TN3270Summary'
        description: |-
          The tn3270 port of the mainframe action summary.
      description: |-
        Specifies the mainframe action summary.
    MainframeActionType:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/Batch'
        description: |-
          The batch of the mainframe action type.
      - allOf:
        - $ref: '#/components/schemas/TN3270'
        description: |-
          The tn3270 port of the mainframe action type.
      description: |-
        Specifies the mainframe action type.
    MainframeResourceSummary:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/M2ManagedApplicationSummary'
        description: |-
          The AWS Mainframe Modernization managed application in the mainframe resource summary.
      - allOf:
        - $ref: '#/components/schemas/M2NonManagedApplicationSummary'
        description: |-
          The AWS Mainframe Modernization non-managed application in the mainframe resource summary.
      description: |-
        Specifies the mainframe resource summary.
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    NextToken:
      type: string
      pattern: ^\S{1,2000}$
    Output:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/OutputFile'
        description: |-
          The file of the output.
      description: |-
        Specifies an output.
    Properties:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    ResourceAction:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/M2ManagedApplicationAction'
        description: |-
          The AWS Mainframe Modernization managed application action of the resource action.
      - allOf:
        - $ref: '#/components/schemas/M2NonManagedApplicationAction'
        description: |-
          The AWS Mainframe Modernization non-managed application action of the resource action.
      - allOf:
        - $ref: '#/components/schemas/CloudFormationAction'
        description: |-
          The CloudFormation action of the resource action.
      description: |-
        Specifies a resource action.
    ResourceActionSummary:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/CloudFormationStepSummary'
        description: |-
          The CloudFormation template of the resource action summary.
      - allOf:
        - $ref: '#/components/schemas/M2ManagedApplicationStepSummary'
        description: |-
          The AWS Mainframe Modernization managed application of the resource action summary.
      - allOf:
        - $ref: '#/components/schemas/M2NonManagedApplicationStepSummary'
        description: |-
          The AWS Mainframe Modernization non-managed application of the resource action summary.
      description: |-
        Specifies the resource action summary.
    ResourceDescription:
      type: string
      minLength: 0
      maxLength: 1000
    ResourceList:
      type: array
      items:
        $ref: '#/components/schemas/Resource'
    ResourceName:
      type: string
      pattern: ^[A-Za-z][A-Za-z0-9_\-]{1,59}$
    ResourceType:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/CloudFormation'
        description: |-
          The CloudFormation template of the resource type.
      - allOf:
        - $ref: '#/components/schemas/M2ManagedApplication'
        description: |-
          The AWS Mainframe Modernization managed application of the resource type.
      - allOf:
        - $ref: '#/components/schemas/M2NonManagedApplication'
        description: |-
          The AWS Mainframe Modernization non-managed application of the resource type.
      description: |-
        Specifies the resource type.
    S3Uri:
      type: string
      minLength: 0
      maxLength: 1024
    ScriptType:
      type: string
      enum:
      - Selenium
    SourceDatabase:
      type: string
      enum:
      - z/OS-DB2
    StepAction:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/ResourceAction'
        description: |-
          The resource action of the step action.
      - allOf:
        - $ref: '#/components/schemas/MainframeAction'
        description: |-
          The mainframe action of the step action.
      - allOf:
        - $ref: '#/components/schemas/CompareAction'
        description: |-
          The compare action of the step action.
      description: |-
        Specifies a step action.
    StepList:
      type: array
      items:
        $ref: '#/components/schemas/Step'
    StepRunStatus:
      type: string
      enum:
      - Success
      - Failed
      - Running
    StepRunSummary:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/MainframeActionSummary'
        description: |-
          The mainframe action of the step run summary.
      - allOf:
        - $ref: '#/components/schemas/CompareActionSummary'
        description: |-
          The compare action of the step run summary.
      - allOf:
        - $ref: '#/components/schemas/ResourceActionSummary'
        description: |-
          The resource action of the step run summary.
      description: |-
        Defines the step run summary.
    String100:
      type: string
      pattern: ^\S{1,100}$
    String50:
      type: string
      pattern: ^\S{1,50}$
    TagKey:
      type: string
      pattern: ^(?!aws:).+$
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TargetDatabase:
      type: string
      enum:
      - PostgreSQL
    TestCaseIdList:
      type: array
      items:
        $ref: '#/components/schemas/Identifier'
    TestCaseLifecycle:
      type: string
      enum:
      - Active
      - Deleting
    TestCaseList:
      type: array
      items:
        $ref: '#/components/schemas/Identifier'
    TestCaseRunStatus:
      type: string
      enum:
      - Success
      - Running
      - Failed
    TestCaseRunSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/TestCaseRunSummary'
    TestCaseSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/TestCaseSummary'
    TestCases:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/TestCaseList'
        description: |-
          The sequential of the test case.
      description: |-
        Specifies test cases.
    TestConfigurationIdList:
      type: array
      items:
        $ref: '#/components/schemas/Identifier'
    TestConfigurationLifecycle:
      type: string
      enum:
      - Active
      - Deleting
    TestConfigurationList:
      type: array
      items:
        $ref: '#/components/schemas/TestConfigurationSummary'
    TestRunIdList:
      type: array
      items:
        $ref: '#/components/schemas/Identifier'
    TestRunStatus:
      type: string
      enum:
      - Success
      - Running
      - Failed
      - Deleting
    TestRunStepSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/TestRunStepSummary'
    TestRunSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/TestRunSummary'
    TestSuiteIdList:
      type: array
      items:
        $ref: '#/components/schemas/Identifier'
    TestSuiteLifecycle:
      type: string
      enum:
      - Creating
      - Updating
      - Active
      - Failed
      - Deleting
    TestSuiteList:
      type: array
      items:
        $ref: '#/components/schemas/TestSuiteSummary'
    ValidationExceptionFieldList:
      type: array
      items:
        $ref: '#/components/schemas/ValidationExceptionField'
    ValidationExceptionReason:
      type: string
      enum:
      - unknownOperation
      - cannotParse
      - fieldValidationFailed
      - other
    Variable:
      type: string
      pattern: ^\S{1,1000}$
    Version:
      type: integer
