openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: apptest
  x-aws-serviceName: apptest
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2022-12-06'
  title: AWS Mainframe Modernization Application Testing
  description: |-
    AWS Mainframe Modernization Application Testing provides tools and resources for automated functional equivalence testing for your migration projects.
servers:
- description: The AWS Mainframe Modernization Application Testing regional endpoint
  url: https://apptest.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Arn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-iso|aws-iso-[a-z]{1}|aws-us-gov):[A-Za-z0-9][A-Za-z0-9_/.-]{0,62}:([a-z]{2}-((iso[a-z]{0,1}-)|(gov-)){0,1}[a-z]+-[0-9]):[0-9]{12}:[A-Za-z0-9/][A-Za-z0-9:_/+=,@.-]{0,1023}$
    IdempotencyTokenString:
      type: string
      pattern: ^[A-Za-z0-9\-]{1,64}$
    Identifier:
      type: string
      pattern: ^[A-Za-z0-9:/\-]{1,100}$
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    NextToken:
      type: string
      pattern: ^\S{1,2000}$
    ResourceDescription:
      type: string
      minLength: 0
      maxLength: 1000
    ResourceName:
      type: string
      pattern: ^[A-Za-z][A-Za-z0-9_\-]{1,59}$
    S3Uri:
      type: string
      minLength: 0
      maxLength: 1024
    String100:
      type: string
      pattern: ^\S{1,100}$
    String50:
      type: string
      pattern: ^\S{1,50}$
    TagKey:
      type: string
      pattern: ^(?!aws:).+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    Variable:
      type: string
      pattern: ^\S{1,1000}$
    Version:
      type: integer
