openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: artifact
  x-aws-serviceName: artifact
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: AWS Artifact
  description: |-
    This reference provides descriptions of the low-level AWS Artifact Service API.
servers:
- description: The AWS Artifact regional endpoint
  url: https://artifact.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AcceptanceType:
      type: string
      enum:
      - PASSTHROUGH
      - EXPLICIT
    AgreementTerms:
      type: array
      items:
        $ref: '#/components/schemas/LongStringAttribute'
    AgreementType:
      type: string
      enum:
      - CUSTOM
      - DEFAULT
      - MODIFIED
    CustomerAgreementIdAttribute:
      type: string
      pattern: ^customer-agreement-[a-zA-Z0-9]{16}$
    CustomerAgreementList:
      type: array
      items:
        $ref: '#/components/schemas/CustomerAgreementSummary'
    CustomerAgreementState:
      type: string
      enum:
      - ACTIVE
      - CUSTOMER_TERMINATED
      - AWS_TERMINATED
    LongStringAttribute:
      type: string
      pattern: ^[^<>]*$
      minLength: 1
      maxLength: 1024
    MaxResultsAttribute:
      type: integer
      minimum: 1
      maximum: 300
    NextTokenAttribute:
      type: string
      minLength: 1
      maxLength: 2048
    NotificationSubscriptionStatus:
      type: string
      enum:
      - SUBSCRIBED
      - NOT_SUBSCRIBED
    PublishedState:
      type: string
      enum:
      - PUBLISHED
      - UNPUBLISHED
    ReportId:
      type: string
      pattern: ^report-[a-zA-Z0-9]{16}$
    ReportsList:
      type: array
      items:
        $ref: '#/components/schemas/ReportSummary'
    SequenceNumberAttribute:
      type: integer
      format: int64
      minimum: 1
    ShortStringAttribute:
      type: string
      pattern: ^[a-zA-Z0-9_\-\s]*$
      minLength: 1
      maxLength: 256
    StatusMessage:
      type: string
    TermId:
      type: string
      pattern: ^term-[a-zA-Z0-9]{16}$
    TimestampAttribute:
      type: string
      format: date-time
    UploadState:
      type: string
      enum:
      - PROCESSING
      - COMPLETE
      - FAILED
      - FAULT
    ValidationExceptionFieldList:
      type: array
      items:
        $ref: '#/components/schemas/ValidationExceptionField'
    ValidationExceptionReason:
      type: string
      enum:
      - unknownOperation
      - cannotParse
      - fieldValidationFailed
      - invalidToken
      - other
    VersionAttribute:
      type: integer
      format: int64
      minimum: 1
