openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: auditmanager
  x-aws-serviceName: auditmanager
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-07-25'
  title: AWS Audit Manager
  description: |-
    Welcome to the Audit Manager API reference. This guide is for developers who need detailed information about the Audit Manager API operations, data types, and errors.

    Audit Manager is a service that provides automated evidence collection so that you can continually audit your Amazon Web Services usage. You can use it to assess the effectiveness of your controls, manage risk, and simplify compliance.

    Audit Manager provides prebuilt frameworks that structure and automate assessments for a given compliance standard. Frameworks include a prebuilt collection of controls with descriptions and testing procedures. These controls are grouped according to the requirements of the specified compliance standard or regulation. You can also customize frameworks and controls to support internal audits with specific requirements.

    Use the following links to get started with the Audit Manager API:

      * [Actions](https://docs.aws.amazon.com/audit-manager/latest/APIReference/API_Operations.html): An alphabetical list of all Audit Manager API operations.

      * [Data types](https://docs.aws.amazon.com/audit-manager/latest/APIReference/API_Types.html): An alphabetical list of all Audit Manager data types.

      * [Common parameters](https://docs.aws.amazon.com/audit-manager/latest/APIReference/CommonParameters.html): Parameters that all operations can use.

      * [Common errors](https://docs.aws.amazon.com/audit-manager/latest/APIReference/CommonErrors.html): Client and server errors that all operations can return.

    If you're new to Audit Manager, we recommend that you review the [ Audit Manager User Guide](https://docs.aws.amazon.com/audit-manager/latest/userguide/what-is.html).
servers:
- description: The AWS Audit Manager regional endpoint
  url: https://auditmanager.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AWSAccounts:
      type: array
      items:
        $ref: '#/components/schemas/AWSAccount'
      x-sensitive: true
    AWSServiceName:
      type: string
      pattern: ^[a-zA-Z0-9-\s().]+$
      minLength: 1
      maxLength: 40
    AWSServices:
      type: array
      items:
        $ref: '#/components/schemas/AWSService'
    AccountId:
      type: string
      pattern: ^[0-9]{12}$
      minLength: 12
      maxLength: 12
    AccountName:
      type: string
      pattern: ^[\u0020-\u007E]+$
      minLength: 1
      maxLength: 50
    AccountStatus:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
      - PENDING_ACTIVATION
    ActionEnum:
      type: string
      enum:
      - CREATE
      - UPDATE_METADATA
      - ACTIVE
      - INACTIVE
      - DELETE
      - UNDER_REVIEW
      - REVIEWED
      - IMPORT_EVIDENCE
    ActionPlanInstructions:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 1000
    ActionPlanTitle:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 300
    AssessmentControlSets:
      type: array
      items:
        $ref: '#/components/schemas/AssessmentControlSet'
    AssessmentControls:
      type: array
      items:
        $ref: '#/components/schemas/AssessmentControl'
    AssessmentDescription:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 1000
    AssessmentEvidenceFolderName:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 1
      maxLength: 300
    AssessmentEvidenceFolders:
      type: array
      items:
        $ref: '#/components/schemas/AssessmentEvidenceFolder'
    AssessmentFrameworkDescription:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 1
      maxLength: 200
    AssessmentFrameworkShareRequestList:
      type: array
      items:
        $ref: '#/components/schemas/AssessmentFrameworkShareRequest'
    AssessmentName:
      type: string
      pattern: ^[^\\]*$
      minLength: 1
      maxLength: 300
    AssessmentReportDescription:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 1000
    AssessmentReportDestinationType:
      type: string
      enum:
      - S3
    AssessmentReportEvidenceErrors:
      type: array
      items:
        $ref: '#/components/schemas/AssessmentReportEvidenceError'
    AssessmentReportName:
      type: string
      pattern: ^[a-zA-Z0-9-_\.]+$
      minLength: 1
      maxLength: 300
    AssessmentReportStatus:
      type: string
      enum:
      - COMPLETE
      - IN_PROGRESS
      - FAILED
    AssessmentReportsMetadata:
      type: array
      items:
        $ref: '#/components/schemas/AssessmentReportMetadata'
    AssessmentStatus:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
    AuditManagerArn:
      type: string
      pattern: '^arn:.*:auditmanager:'
      minLength: 20
      maxLength: 2048
    BatchCreateDelegationByAssessmentErrors:
      type: array
      items:
        $ref: '#/components/schemas/BatchCreateDelegationByAssessmentError'
      x-sensitive: true
    BatchDeleteDelegationByAssessmentErrors:
      type: array
      items:
        $ref: '#/components/schemas/BatchDeleteDelegationByAssessmentError'
      x-sensitive: true
    BatchImportEvidenceToAssessmentControlErrors:
      type: array
      items:
        $ref: '#/components/schemas/BatchImportEvidenceToAssessmentControlError'
    Boolean:
      type: boolean
    ChangeLogs:
      type: array
      items:
        $ref: '#/components/schemas/ChangeLog'
    CloudTrailArn:
      type: string
      pattern: '^arn:.*:cloudtrail:'
      minLength: 20
      maxLength: 2048
    ComplianceType:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 100
    ControlCatalogId:
      type: string
      pattern: ^arn:.*:controlcatalog:.*|UNCATEGORIZED$
      minLength: 13
      maxLength: 2048
    ControlCommentBody:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 500
    ControlComments:
      type: array
      items:
        $ref: '#/components/schemas/ControlComment'
    ControlDescription:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 1000
    ControlDomainId:
      type: string
      pattern: ^arn:.*:controlcatalog:.*:.*:domain/.*|UNCATEGORIZED|^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 13
      maxLength: 2048
    ControlDomainInsightsList:
      type: array
      items:
        $ref: '#/components/schemas/ControlDomainInsights'
    ControlInsightsMetadata:
      type: array
      items:
        $ref: '#/components/schemas/ControlInsightsMetadataItem'
    ControlInsightsMetadataByAssessment:
      type: array
      items:
        $ref: '#/components/schemas/ControlInsightsMetadataByAssessmentItem'
    ControlMappingSources:
      type: array
      items:
        $ref: '#/components/schemas/ControlMappingSource'
    ControlMetadataList:
      type: array
      items:
        $ref: '#/components/schemas/ControlMetadata'
    ControlName:
      type: string
      pattern: ^[^\\]*$
      minLength: 1
      maxLength: 300
    ControlResponse:
      type: string
      enum:
      - MANUAL
      - AUTOMATE
      - DEFER
      - IGNORE
    ControlSetId:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 1
      maxLength: 300
    ControlSetName:
      type: string
      pattern: ^[^\\\_]*$
      minLength: 1
      maxLength: 300
    ControlSetStatus:
      type: string
      enum:
      - ACTIVE
      - UNDER_REVIEW
      - REVIEWED
    ControlSets:
      type: array
      items:
        $ref: '#/components/schemas/ControlSet'
      x-sensitive: true
    ControlSetsCount:
      type: integer
      default: 0
    ControlSources:
      type: string
      pattern: ^[a-zA-Z_0-9-\s.,]+$
      minLength: 1
      maxLength: 100
    ControlState:
      type: string
      enum:
      - ACTIVE
      - END_OF_SUPPORT
    ControlStatus:
      type: string
      enum:
      - UNDER_REVIEW
      - REVIEWED
      - INACTIVE
    ControlType:
      type: string
      enum:
      - Standard
      - Custom
      - Core
    Controls:
      type: array
      items:
        $ref: '#/components/schemas/Control'
    ControlsCount:
      type: integer
      default: 0
    CreateAssessmentFrameworkControlSets:
      type: array
      items:
        $ref: '#/components/schemas/CreateAssessmentFrameworkControlSet'
    CreateAssessmentFrameworkControls:
      type: array
      items:
        $ref: '#/components/schemas/CreateAssessmentFrameworkControl'
    CreateControlMappingSources:
      type: array
      items:
        $ref: '#/components/schemas/CreateControlMappingSource'
    CreateDelegationRequests:
      type: array
      items:
        $ref: '#/components/schemas/CreateDelegationRequest'
      x-sensitive: true
    CreatedBy:
      type: string
      pattern: ^[a-zA-Z0-9\s-_()\[\]]+$
      minLength: 1
      maxLength: 100
    DataSourceType:
      type: string
      enum:
      - AWS_Cloudtrail
      - AWS_Config
      - AWS_Security_Hub
      - AWS_API_Call
      - MANUAL
    DelegationComment:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 350
    DelegationIds:
      type: array
      items:
        $ref: '#/components/schemas/UUID'
    DelegationMetadataList:
      type: array
      items:
        $ref: '#/components/schemas/DelegationMetadata'
    DelegationStatus:
      type: string
      enum:
      - IN_PROGRESS
      - UNDER_REVIEW
      - COMPLETE
    Delegations:
      type: array
      items:
        $ref: '#/components/schemas/Delegation'
    DeleteResources:
      type: string
      enum:
      - ALL
      - DEFAULT
    EmailAddress:
      type: string
      pattern: ^.*@.*$
      minLength: 1
      maxLength: 320
    ErrorCode:
      type: string
      pattern: ^[0-9]{3}$
      minLength: 3
      maxLength: 3
    ErrorMessage:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 300
    EventName:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 100
    EvidenceAttributeKey:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 100
    EvidenceAttributeValue:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 200
    EvidenceAttributes:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/EvidenceAttributeValue'
    EvidenceFinderBackfillStatus:
      type: string
      enum:
      - NOT_STARTED
      - IN_PROGRESS
      - COMPLETED
    EvidenceFinderEnablementStatus:
      type: string
      enum:
      - ENABLED
      - DISABLED
      - ENABLE_IN_PROGRESS
      - DISABLE_IN_PROGRESS
    EvidenceIds:
      type: array
      items:
        $ref: '#/components/schemas/UUID'
    EvidenceList:
      type: array
      items:
        $ref: '#/components/schemas/Evidence'
    EvidenceSources:
      type: array
      items:
        $ref: '#/components/schemas/NonEmptyString'
    ExportDestinationType:
      type: string
      enum:
      - S3
    Filename:
      type: string
      pattern: ^[\w,\s-]+\.[A-Za-z]+$
      minLength: 1
      maxLength: 255
    FrameworkDescription:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 1
      maxLength: 1000
    FrameworkMetadataList:
      type: array
      items:
        $ref: '#/components/schemas/AssessmentFrameworkMetadata'
    FrameworkName:
      type: string
      pattern: ^[^\\]*$
      minLength: 1
      maxLength: 300
    FrameworkType:
      type: string
      enum:
      - Standard
      - Custom
    GenericArn:
      type: string
      pattern: '^arn:'
      minLength: 20
      maxLength: 2048
    HyperlinkName:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 1
      maxLength: 200
    IamArn:
      type: string
      pattern: '^arn:.*:iam:'
      minLength: 20
      maxLength: 2048
    Integer:
      type: integer
      default: 0
    KeywordInputType:
      type: string
      enum:
      - SELECT_FROM_LIST
      - UPLOAD_FILE
      - INPUT_TEXT
    KeywordValue:
      type: string
      pattern: ^[a-zA-Z_0-9-\s().:\/]+$
      minLength: 1
      maxLength: 100
    Keywords:
      type: array
      items:
        $ref: '#/components/schemas/KeywordValue'
    KmsKey:
      type: string
      pattern: ^arn:.*:kms:.*|DEFAULT$
      minLength: 7
      maxLength: 2048
    LastUpdatedBy:
      type: string
      pattern: ^[a-zA-Z0-9\s-_()\[\]]+$
      minLength: 1
      maxLength: 100
    ListAssessmentMetadata:
      type: array
      items:
        $ref: '#/components/schemas/AssessmentMetadataItem'
    ManualEvidenceList:
      type: array
      items:
        $ref: '#/components/schemas/ManualEvidence'
    ManualEvidenceLocalFileName:
      type: string
      pattern: ^[^\/]*$
      minLength: 1
      maxLength: 300
    ManualEvidenceTextResponse:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 1
      maxLength: 1000
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
      description: Max results in the page.
    NonEmptyString:
      type: string
      pattern: \S
      minLength: 1
      maxLength: 2048
    Notifications:
      type: array
      items:
        $ref: '#/components/schemas/Notification'
    NullableInteger:
      type: integer
    ObjectTypeEnum:
      type: string
      enum:
      - ASSESSMENT
      - CONTROL_SET
      - CONTROL
      - DELEGATION
      - ASSESSMENT_REPORT
    QueryStatement:
      type: string
      pattern: ^(?s)
      minLength: 1
      maxLength: 10000
    Region:
      type: string
      pattern: ^[a-z]{2}-[a-z]+-[0-9]{1}$
    Resources:
      type: array
      items:
        $ref: '#/components/schemas/Resource'
    RoleType:
      type: string
      enum:
      - PROCESS_OWNER
      - RESOURCE_OWNER
    Roles:
      type: array
      items:
        $ref: '#/components/schemas/Role'
      x-sensitive: true
    S3Url:
      type: string
      pattern: ^(S|s)3:\/\/[a-zA-Z0-9\-\.\(\)\'\*\_\!\/]+$
      minLength: 1
      maxLength: 1024
    SNSTopic:
      type: string
      pattern: ^[a-zA-Z0-9-_\(\)\[\]]+$
      minLength: 1
      maxLength: 255
    ServiceMetadataList:
      type: array
      items:
        $ref: '#/components/schemas/ServiceMetadata'
    SettingAttribute:
      type: string
      enum:
      - ALL
      - IS_AWS_ORG_ENABLED
      - SNS_TOPIC
      - DEFAULT_ASSESSMENT_REPORTS_DESTINATION
      - DEFAULT_PROCESS_OWNERS
      - EVIDENCE_FINDER_ENABLEMENT
      - DEREGISTRATION_POLICY
      - DEFAULT_EXPORT_DESTINATION
    ShareRequestAction:
      type: string
      enum:
      - ACCEPT
      - DECLINE
      - REVOKE
    ShareRequestComment:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 500
    ShareRequestStatus:
      type: string
      enum:
      - ACTIVE
      - REPLICATING
      - SHARED
      - EXPIRING
      - FAILED
      - EXPIRED
      - DECLINED
      - REVOKED
    ShareRequestType:
      type: string
      enum:
      - SENT
      - RECEIVED
    SnsArn:
      type: string
      pattern: ^arn:.*:sns:.*|NONE$
      minLength: 4
      maxLength: 2048
    SourceDescription:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 1000
    SourceFrequency:
      type: string
      enum:
      - DAILY
      - WEEKLY
      - MONTHLY
    SourceName:
      type: string
      minLength: 1
      maxLength: 300
    SourceSetUpOption:
      type: string
      enum:
      - System_Controls_Mapping
      - Procedural_Controls_Mapping
    SourceType:
      type: string
      enum:
      - AWS_Cloudtrail
      - AWS_Config
      - AWS_Security_Hub
      - AWS_API_Call
      - MANUAL
      - Common_Control
      - Core_Control
    String:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 2048
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      pattern: ^.{0,255}$
      minLength: 0
      maxLength: 256
    TestingInformation:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 1000
    Timestamp:
      type: string
      format: date-time
    TimestampUUID:
      type: string
      pattern: ^[0-9]{10,13}_[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 47
      maxLength: 50
    Token:
      type: string
      pattern: ^[A-Za-z0-9+\/=]*$
      minLength: 1
      maxLength: 1000
    TroubleshootingText:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 1000
    UUID:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 36
      maxLength: 36
    UpdateAssessmentFrameworkControlSets:
      type: array
      items:
        $ref: '#/components/schemas/UpdateAssessmentFrameworkControlSet'
    UrlLink:
      type: string
      pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9-_]+([\.]+[a-zA-Z]+)+[\/\w]*$
      minLength: 1
      maxLength: 8192
    Username:
      type: string
      pattern: ^[a-zA-Z0-9-_()\s\+=,.@]+$
      minLength: 1
      maxLength: 128
    ValidationErrors:
      type: array
      items:
        $ref: '#/components/schemas/NonEmptyString'
    ValidationExceptionFieldList:
      type: array
      items:
        $ref: '#/components/schemas/ValidationExceptionField'
    ValidationExceptionReason:
      type: string
      enum:
      - unknownOperation
      - cannotParse
      - fieldValidationFailed
      - other
    organizationId:
      type: string
      pattern: ^o-[a-z0-9]{10,32}$
      minLength: 12
      maxLength: 34
