openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: auditmanager
  x-aws-serviceName: auditmanager
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-07-25'
  title: AWS Audit Manager
  description: |-
    Welcome to the Audit Manager API reference. This guide is for developers who need detailed information about the Audit Manager API operations, data types, and errors.

    Audit Manager is a service that provides automated evidence collection so that you can continually audit your Amazon Web Services usage. You can use it to assess the effectiveness of your controls, manage risk, and simplify compliance.

    Audit Manager provides prebuilt frameworks that structure and automate assessments for a given compliance standard. Frameworks include a prebuilt collection of controls with descriptions and testing procedures. These controls are grouped according to the requirements of the specified compliance standard or regulation. You can also customize frameworks and controls to support internal audits with specific requirements.

    Use the following links to get started with the Audit Manager API:

      * [Actions](https://docs.aws.amazon.com/audit-manager/latest/APIReference/API_Operations.html): An alphabetical list of all Audit Manager API operations.

      * [Data types](https://docs.aws.amazon.com/audit-manager/latest/APIReference/API_Types.html): An alphabetical list of all Audit Manager data types.

      * [Common parameters](https://docs.aws.amazon.com/audit-manager/latest/APIReference/CommonParameters.html): Parameters that all operations can use.

      * [Common errors](https://docs.aws.amazon.com/audit-manager/latest/APIReference/CommonErrors.html): Client and server errors that all operations can return.

    If you're new to Audit Manager, we recommend that you review the [ Audit Manager User Guide](https://docs.aws.amazon.com/audit-manager/latest/userguide/what-is.html).
servers:
- description: The AWS Audit Manager regional endpoint
  url: https://auditmanager.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AWSServiceName:
      type: string
      pattern: ^[a-zA-Z0-9-\s().]+$
      minLength: 1
      maxLength: 40
    AccountId:
      type: string
      pattern: ^[0-9]{12}$
      minLength: 12
      maxLength: 12
    AccountName:
      type: string
      pattern: ^[\u0020-\u007E]+$
      minLength: 1
      maxLength: 50
    ActionPlanInstructions:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 1000
    ActionPlanTitle:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 300
    AssessmentDescription:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 1000
    AssessmentEvidenceFolderName:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 1
      maxLength: 300
    AssessmentFrameworkDescription:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 1
      maxLength: 200
    AssessmentName:
      type: string
      pattern: ^[^\\]*$
      minLength: 1
      maxLength: 300
    AssessmentReportDescription:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 1000
    AssessmentReportName:
      type: string
      pattern: ^[a-zA-Z0-9-_\.]+$
      minLength: 1
      maxLength: 300
    AuditManagerArn:
      type: string
      pattern: '^arn:.*:auditmanager:'
      minLength: 20
      maxLength: 2048
    Boolean:
      type: boolean
    CloudTrailArn:
      type: string
      pattern: '^arn:.*:cloudtrail:'
      minLength: 20
      maxLength: 2048
    ComplianceType:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 100
    ControlCatalogId:
      type: string
      pattern: ^arn:.*:controlcatalog:.*|UNCATEGORIZED$
      minLength: 13
      maxLength: 2048
    ControlCommentBody:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 500
    ControlDescription:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 1000
    ControlDomainId:
      type: string
      pattern: ^arn:.*:controlcatalog:.*:.*:domain/.*|UNCATEGORIZED|^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 13
      maxLength: 2048
    ControlName:
      type: string
      pattern: ^[^\\]*$
      minLength: 1
      maxLength: 300
    ControlSetId:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 1
      maxLength: 300
    ControlSetName:
      type: string
      pattern: ^[^\\\_]*$
      minLength: 1
      maxLength: 300
    ControlSetsCount:
      type: integer
      default: 0
    ControlSources:
      type: string
      pattern: ^[a-zA-Z_0-9-\s.,]+$
      minLength: 1
      maxLength: 100
    ControlsCount:
      type: integer
      default: 0
    CreatedBy:
      type: string
      pattern: ^[a-zA-Z0-9\s-_()\[\]]+$
      minLength: 1
      maxLength: 100
    DelegationComment:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 350
    EmailAddress:
      type: string
      pattern: ^.*@.*$
      minLength: 1
      maxLength: 320
    ErrorCode:
      type: string
      pattern: ^[0-9]{3}$
      minLength: 3
      maxLength: 3
    ErrorMessage:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 300
    EventName:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 100
    EvidenceAttributeKey:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 100
    EvidenceAttributeValue:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 200
    Filename:
      type: string
      pattern: ^[\w,\s-]+\.[A-Za-z]+$
      minLength: 1
      maxLength: 255
    FrameworkDescription:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 1
      maxLength: 1000
    FrameworkName:
      type: string
      pattern: ^[^\\]*$
      minLength: 1
      maxLength: 300
    GenericArn:
      type: string
      pattern: '^arn:'
      minLength: 20
      maxLength: 2048
    HyperlinkName:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 1
      maxLength: 200
    IamArn:
      type: string
      pattern: '^arn:.*:iam:'
      minLength: 20
      maxLength: 2048
    Integer:
      type: integer
      default: 0
    KeywordValue:
      type: string
      pattern: ^[a-zA-Z_0-9-\s().:\/]+$
      minLength: 1
      maxLength: 100
    KmsKey:
      type: string
      pattern: ^arn:.*:kms:.*|DEFAULT$
      minLength: 7
      maxLength: 2048
    LastUpdatedBy:
      type: string
      pattern: ^[a-zA-Z0-9\s-_()\[\]]+$
      minLength: 1
      maxLength: 100
    ManualEvidenceLocalFileName:
      type: string
      pattern: ^[^\/]*$
      minLength: 1
      maxLength: 300
    ManualEvidenceTextResponse:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 1
      maxLength: 1000
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
      description: Max results in the page.
    NonEmptyString:
      type: string
      pattern: \S
      minLength: 1
      maxLength: 2048
    NullableInteger:
      type: integer
    QueryStatement:
      type: string
      pattern: ^(?s)
      minLength: 1
      maxLength: 10000
    Region:
      type: string
      pattern: ^[a-z]{2}-[a-z]+-[0-9]{1}$
    S3Url:
      type: string
      pattern: ^(S|s)3:\/\/[a-zA-Z0-9\-\.\(\)\'\*\_\!\/]+$
      minLength: 1
      maxLength: 1024
    SNSTopic:
      type: string
      pattern: ^[a-zA-Z0-9-_\(\)\[\]]+$
      minLength: 1
      maxLength: 255
    ShareRequestComment:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 500
    SnsArn:
      type: string
      pattern: ^arn:.*:sns:.*|NONE$
      minLength: 4
      maxLength: 2048
    SourceDescription:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 1000
    SourceName:
      type: string
      minLength: 1
      maxLength: 300
    String:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 2048
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^.{0,255}$
      minLength: 0
      maxLength: 256
    TestingInformation:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 1000
    TimestampUUID:
      type: string
      pattern: ^[0-9]{10,13}_[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 47
      maxLength: 50
    Token:
      type: string
      pattern: ^[A-Za-z0-9+\/=]*$
      minLength: 1
      maxLength: 1000
    TroubleshootingText:
      type: string
      pattern: ^[\w\W\s\S]*$
      minLength: 0
      maxLength: 1000
    UUID:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 36
      maxLength: 36
    UrlLink:
      type: string
      pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9-_]+([\.]+[a-zA-Z]+)+[\/\w]*$
      minLength: 1
      maxLength: 8192
    Username:
      type: string
      pattern: ^[a-zA-Z0-9-_()\s\+=,.@]+$
      minLength: 1
      maxLength: 128
    organizationId:
      type: string
      pattern: ^o-[a-z0-9]{10,32}$
      minLength: 12
      maxLength: 34
