openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: backup
  x-aws-serviceName: backup
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-11-15'
  title: AWS Backup
  description: |-
    Backup

    Backup is a unified backup service designed to protect Amazon Web Services services and their associated data. Backup simplifies the creation, migration, restoration, and deletion of backups, while also providing reporting and auditing.
servers:
- description: The AWS Backup regional endpoint
  url: https://backup.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ARN:
      type: string
    AccountId:
      type: string
      pattern: ^[0-9]{12}$
    AdvancedBackupSettings:
      type: array
      items:
        $ref: '#/components/schemas/AdvancedBackupSetting'
    AggregationPeriod:
      type: string
      enum:
      - ONE_DAY
      - SEVEN_DAYS
      - FOURTEEN_DAYS
    BackupJobChildJobsInState:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Long'
    BackupJobState:
      type: string
      enum:
      - CREATED
      - PENDING
      - RUNNING
      - ABORTING
      - ABORTED
      - COMPLETED
      - FAILED
      - EXPIRED
      - PARTIAL
    BackupJobStatus:
      type: string
      enum:
      - CREATED
      - PENDING
      - RUNNING
      - ABORTING
      - ABORTED
      - COMPLETED
      - FAILED
      - EXPIRED
      - PARTIAL
      - AGGREGATE_ALL
      - ANY
    BackupJobSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/BackupJobSummary'
    BackupJobsList:
      type: array
      items:
        $ref: '#/components/schemas/BackupJob'
    BackupOptionKey:
      type: string
      pattern: ^[a-zA-Z0-9\-\_\.]{1,50}$
    BackupOptionValue:
      type: string
      pattern: ^[a-zA-Z0-9\-\_\.]{1,50}$
    BackupOptions:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/BackupOptionValue'
    BackupPlanName:
      type: string
    BackupPlanTemplatesList:
      type: array
      items:
        $ref: '#/components/schemas/BackupPlanTemplatesListMember'
    BackupPlanVersionsList:
      type: array
      items:
        $ref: '#/components/schemas/BackupPlansListMember'
    BackupPlansList:
      type: array
      items:
        $ref: '#/components/schemas/BackupPlansListMember'
    BackupRuleName:
      type: string
      pattern: ^[a-zA-Z0-9\-\_\.]{1,50}$
    BackupRules:
      type: array
      items:
        $ref: '#/components/schemas/BackupRule'
    BackupRulesInput:
      type: array
      items:
        $ref: '#/components/schemas/BackupRuleInput'
    BackupSelectionName:
      type: string
      pattern: ^[a-zA-Z0-9\-\_\.]{1,50}$
    BackupSelectionsList:
      type: array
      items:
        $ref: '#/components/schemas/BackupSelectionsListMember'
    BackupVaultEvent:
      type: string
      enum:
      - BACKUP_JOB_STARTED
      - BACKUP_JOB_COMPLETED
      - BACKUP_JOB_SUCCESSFUL
      - BACKUP_JOB_FAILED
      - BACKUP_JOB_EXPIRED
      - RESTORE_JOB_STARTED
      - RESTORE_JOB_COMPLETED
      - RESTORE_JOB_SUCCESSFUL
      - RESTORE_JOB_FAILED
      - COPY_JOB_STARTED
      - COPY_JOB_SUCCESSFUL
      - COPY_JOB_FAILED
      - RECOVERY_POINT_MODIFIED
      - BACKUP_PLAN_CREATED
      - BACKUP_PLAN_MODIFIED
      - S3_BACKUP_OBJECT_FAILED
      - S3_RESTORE_OBJECT_FAILED
    BackupVaultEvents:
      type: array
      items:
        $ref: '#/components/schemas/BackupVaultEvent'
    BackupVaultList:
      type: array
      items:
        $ref: '#/components/schemas/BackupVaultListMember'
    BackupVaultName:
      type: string
      pattern: ^[a-zA-Z0-9\-\_]{2,50}$
    Boolean:
      type: boolean
    Boolean2:
      type: boolean
      default: false
    ComplianceResourceIdList:
      type: array
      items:
        $ref: '#/components/schemas/string'
    ConditionKey:
      type: string
    ConditionParameters:
      type: array
      items:
        $ref: '#/components/schemas/ConditionParameter'
    ConditionType:
      type: string
      enum:
      - STRINGEQUALS
    ConditionValue:
      type: string
    ControlInputParameters:
      type: array
      items:
        $ref: '#/components/schemas/ControlInputParameter'
    ControlName:
      type: string
    CopyActions:
      type: array
      items:
        $ref: '#/components/schemas/CopyAction'
    CopyJobChildJobsInState:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Long'
    CopyJobState:
      type: string
      enum:
      - CREATED
      - RUNNING
      - COMPLETED
      - FAILED
      - PARTIAL
    CopyJobStatus:
      type: string
      enum:
      - CREATED
      - RUNNING
      - ABORTING
      - ABORTED
      - COMPLETING
      - COMPLETED
      - FAILING
      - FAILED
      - PARTIAL
      - AGGREGATE_ALL
      - ANY
    CopyJobSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/CopyJobSummary'
    CopyJobsList:
      type: array
      items:
        $ref: '#/components/schemas/CopyJob'
    CronExpression:
      type: string
    FormatList:
      type: array
      items:
        $ref: '#/components/schemas/string'
    FrameworkControls:
      type: array
      items:
        $ref: '#/components/schemas/FrameworkControl'
    FrameworkDescription:
      type: string
      pattern: \S
      minLength: 0
      maxLength: 1024
    FrameworkList:
      type: array
      items:
        $ref: '#/components/schemas/Framework'
    FrameworkName:
      type: string
      pattern: ^[a-zA-Z][_a-zA-Z0-9]*$
      minLength: 1
      maxLength: 256
    GlobalSettings:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/GlobalSettingsValue'
    GlobalSettingsName:
      type: string
    GlobalSettingsValue:
      type: string
    IAMPolicy:
      type: string
    IAMRoleArn:
      type: string
    Index:
      type: string
      enum:
      - ENABLED
      - DISABLED
    IndexActions:
      type: array
      items:
        $ref: '#/components/schemas/IndexAction'
    IndexStatus:
      type: string
      enum:
      - PENDING
      - ACTIVE
      - FAILED
      - DELETING
    IndexedRecoveryPointList:
      type: array
      items:
        $ref: '#/components/schemas/IndexedRecoveryPoint'
    IsEnabled:
      type: boolean
      default: false
    KeyValueList:
      type: array
      items:
        $ref: '#/components/schemas/KeyValue'
    LegalHoldStatus:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - CANCELING
      - CANCELED
    LegalHoldsList:
      type: array
      items:
        $ref: '#/components/schemas/LegalHold'
    ListOfTags:
      type: array
      items:
        $ref: '#/components/schemas/Condition'
    ListRestoreTestingPlansInputMaxResultsInteger:
      type: integer
      minimum: 1
      maximum: 1000
    ListRestoreTestingSelectionsInputMaxResultsInteger:
      type: integer
      minimum: 1
      maximum: 1000
    Long:
      type: integer
      format: int64
    Long2:
      type: integer
      format: int64
      default: 0
    MaxFrameworkInputs:
      type: integer
      minimum: 1
      maximum: 1000
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
    MessageCategory:
      type: string
    Metadata:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/MetadataValue'
    MetadataKey:
      type: string
    MetadataValue:
      type: string
    ParameterName:
      type: string
    ParameterValue:
      type: string
    ProtectedResourcesList:
      type: array
      items:
        $ref: '#/components/schemas/ProtectedResource'
    RecoveryPointByBackupVaultList:
      type: array
      items:
        $ref: '#/components/schemas/RecoveryPointByBackupVault'
    RecoveryPointByResourceList:
      type: array
      items:
        $ref: '#/components/schemas/RecoveryPointByResource'
    RecoveryPointStatus:
      type: string
      enum:
      - COMPLETED
      - PARTIAL
      - DELETING
      - EXPIRED
    RecoveryPointsList:
      type: array
      items:
        $ref: '#/components/schemas/RecoveryPointMember'
    Region:
      type: string
    ReportJobId:
      type: string
    ReportJobList:
      type: array
      items:
        $ref: '#/components/schemas/ReportJob'
    ReportPlanDescription:
      type: string
      pattern: \S
      minLength: 0
      maxLength: 1024
    ReportPlanList:
      type: array
      items:
        $ref: '#/components/schemas/ReportPlan'
    ReportPlanName:
      type: string
      pattern: ^[a-zA-Z][_a-zA-Z0-9]*$
      minLength: 1
      maxLength: 256
    ResourceArns:
      type: array
      items:
        $ref: '#/components/schemas/ARN'
    ResourceIdentifiers:
      type: array
      items:
        $ref: '#/components/schemas/string'
    ResourceType:
      type: string
      pattern: ^[a-zA-Z0-9\-\_\.]{1,50}$
    ResourceTypeList:
      type: array
      items:
        $ref: '#/components/schemas/ARN'
    ResourceTypeManagementPreference:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/IsEnabled'
    ResourceTypeOptInPreference:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/IsEnabled'
    ResourceTypes:
      type: array
      items:
        $ref: '#/components/schemas/ResourceType'
    RestoreDeletionStatus:
      type: string
      enum:
      - DELETING
      - FAILED
      - SUCCESSFUL
    RestoreJobId:
      type: string
    RestoreJobState:
      type: string
      enum:
      - CREATED
      - PENDING
      - RUNNING
      - ABORTED
      - COMPLETED
      - FAILED
      - AGGREGATE_ALL
      - ANY
    RestoreJobStatus:
      type: string
      enum:
      - PENDING
      - RUNNING
      - COMPLETED
      - ABORTED
      - FAILED
    RestoreJobSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/RestoreJobSummary'
    RestoreJobsList:
      type: array
      items:
        $ref: '#/components/schemas/RestoreJobsListMember'
    RestoreTestingPlans:
      type: array
      items:
        $ref: '#/components/schemas/RestoreTestingPlanForList'
    RestoreTestingRecoveryPointSelectionAlgorithm:
      type: string
      enum:
      - LATEST_WITHIN_WINDOW
      - RANDOM_WITHIN_WINDOW
    RestoreTestingRecoveryPointType:
      type: string
      enum:
      - CONTINUOUS
      - SNAPSHOT
    RestoreTestingRecoveryPointTypeList:
      type: array
      items:
        $ref: '#/components/schemas/RestoreTestingRecoveryPointType'
    RestoreTestingSelections:
      type: array
      items:
        $ref: '#/components/schemas/RestoreTestingSelectionForList'
    RestoreValidationStatus:
      type: string
      enum:
      - FAILED
      - SUCCESSFUL
      - TIMED_OUT
      - VALIDATING
    SensitiveStringMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    StorageClass:
      type: string
      enum:
      - WARM
      - COLD
      - DELETED
    TagKey:
      type: string
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/string'
      x-sensitive: true
    TagValue:
      type: string
    Tags:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    Timezone:
      type: string
    VaultNames:
      type: array
      items:
        $ref: '#/components/schemas/string'
    VaultState:
      type: string
      enum:
      - CREATING
      - AVAILABLE
      - FAILED
    VaultType:
      type: string
      enum:
      - BACKUP_VAULT
      - LOGICALLY_AIR_GAPPED_BACKUP_VAULT
    WindowMinutes:
      type: integer
      format: int64
    integer:
      type: integer
      default: 0
    string:
      type: string
    stringList:
      type: array
      items:
        $ref: '#/components/schemas/string'
    stringMap:
      type: object
      additionalProperties:
        type: string
    timestamp:
      type: string
      format: date-time
