openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: backup
  x-aws-serviceName: backup
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-11-15'
  title: AWS Backup
  description: |-
    Backup

    Backup is a unified backup service designed to protect Amazon Web Services services and their associated data. Backup simplifies the creation, migration, restoration, and deletion of backups, while also providing reporting and auditing.
servers:
- description: The AWS Backup regional endpoint
  url: https://backup.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ARN:
      type: string
    AccountId:
      type: string
      pattern: ^[0-9]{12}$
    BackupOptionKey:
      type: string
      pattern: ^[a-zA-Z0-9\-\_\.]{1,50}$
    BackupOptionValue:
      type: string
      pattern: ^[a-zA-Z0-9\-\_\.]{1,50}$
    BackupPlanName:
      type: string
    BackupRuleName:
      type: string
      pattern: ^[a-zA-Z0-9\-\_\.]{1,50}$
    BackupSelectionName:
      type: string
      pattern: ^[a-zA-Z0-9\-\_\.]{1,50}$
    BackupVaultName:
      type: string
      pattern: ^[a-zA-Z0-9\-\_]{2,50}$
    Boolean:
      type: boolean
    Boolean2:
      type: boolean
      default: false
    ConditionKey:
      type: string
    ConditionValue:
      type: string
    ControlName:
      type: string
    CronExpression:
      type: string
    FrameworkDescription:
      type: string
      pattern: \S
      minLength: 0
      maxLength: 1024
    FrameworkName:
      type: string
      pattern: ^[a-zA-Z][_a-zA-Z0-9]*$
      minLength: 1
      maxLength: 256
    GlobalSettingsName:
      type: string
    GlobalSettingsValue:
      type: string
    IAMPolicy:
      type: string
    IAMRoleArn:
      type: string
    IsEnabled:
      type: boolean
      default: false
    ListRestoreTestingPlansInputMaxResultsInteger:
      type: integer
      minimum: 1
      maximum: 1000
    ListRestoreTestingSelectionsInputMaxResultsInteger:
      type: integer
      minimum: 1
      maximum: 1000
    MaxFrameworkInputs:
      type: integer
      minimum: 1
      maximum: 1000
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
    MessageCategory:
      type: string
    MetadataKey:
      type: string
    MetadataValue:
      type: string
    ParameterName:
      type: string
    ParameterValue:
      type: string
    Region:
      type: string
    ReportJobId:
      type: string
    ReportPlanDescription:
      type: string
      pattern: \S
      minLength: 0
      maxLength: 1024
    ReportPlanName:
      type: string
      pattern: ^[a-zA-Z][_a-zA-Z0-9]*$
      minLength: 1
      maxLength: 256
    ResourceType:
      type: string
      pattern: ^[a-zA-Z0-9\-\_\.]{1,50}$
    RestoreJobId:
      type: string
    TagKey:
      type: string
    TagValue:
      type: string
    Timezone:
      type: string
    integer:
      type: integer
      default: 0
    string:
      type: string
