openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: backupsearch
  x-aws-serviceName: backupsearch
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: AWS Backup Search
  description: |-
    Backup Search

    Backup Search is the recovery point and item level search for Backup.

    For additional information, see:

      * [Backup API Reference](https://docs.aws.amazon.com/aws-backup/latest/devguide/api-reference.html)

      * [Backup Developer Guide](https://docs.aws.amazon.com/aws-backup/latest/devguide/whatisbackup.html)
servers:
- description: The AWS Backup Search regional endpoint
  url: https://backup-search.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    EBSItemFilters:
      type: array
      items:
        $ref: '#/components/schemas/EBSItemFilter'
    EncryptionKeyArn:
      type: string
    ExportJobArn:
      type: string
    ExportJobStatus:
      type: string
      enum:
      - RUNNING
      - FAILED
      - COMPLETED
    ExportJobSummaries:
      type: array
      items:
        $ref: '#/components/schemas/ExportJobSummary'
    ExportSpecification:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/S3ExportSpecification'
        description: |-
          This specifies the destination Amazon S3 bucket for the export job. And, if included, it also specifies the destination prefix.
      description: |-
        This contains the export specification object.
    FilePath:
      type: string
    GenericId:
      type: string
    IamRoleArn:
      type: string
      pattern: ^arn:(?:aws|aws-cn|aws-us-gov):iam::[a-z0-9-]+:role/(.+)$
      minLength: 20
      maxLength: 2048
    LongConditionList:
      type: array
      items:
        $ref: '#/components/schemas/LongCondition'
    LongConditionOperator:
      type: string
      enum:
      - EQUALS_TO
      - NOT_EQUALS_TO
      - LESS_THAN_EQUAL_TO
      - GREATER_THAN_EQUAL_TO
    ObjectKey:
      type: string
    RecoveryPoint:
      type: string
    RecoveryPointArnList:
      type: array
      items:
        $ref: '#/components/schemas/RecoveryPoint'
    ResourceArnList:
      type: array
      items:
        type: string
    ResourceType:
      type: string
      enum:
      - S3
      - EBS
    ResourceTypeList:
      type: array
      items:
        $ref: '#/components/schemas/ResourceType'
    ResultItem:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/S3ResultItem'
        description: |-
          These are items returned in the search results of an Amazon S3 search.
      - allOf:
        - $ref: '#/components/schemas/EBSResultItem'
        description: |-
          These are items returned in the search results of an Amazon EBS search.
      description: |-
        This is an object representing the item returned in the results of a search for a specific resource type.
    Results:
      type: array
      items:
        $ref: '#/components/schemas/ResultItem'
    S3ItemFilters:
      type: array
      items:
        $ref: '#/components/schemas/S3ItemFilter'
    SearchJobArn:
      type: string
    SearchJobBackupsResults:
      type: array
      items:
        $ref: '#/components/schemas/SearchJobBackupsResult'
    SearchJobState:
      type: string
      enum:
      - RUNNING
      - COMPLETED
      - STOPPING
      - STOPPED
      - FAILED
    SearchJobs:
      type: array
      items:
        $ref: '#/components/schemas/SearchJobSummary'
    StringConditionList:
      type: array
      items:
        $ref: '#/components/schemas/StringCondition'
    StringConditionOperator:
      type: string
      enum:
      - EQUALS_TO
      - NOT_EQUALS_TO
      - CONTAINS
      - DOES_NOT_CONTAIN
      - BEGINS_WITH
      - ENDS_WITH
      - DOES_NOT_BEGIN_WITH
      - DOES_NOT_END_WITH
    TagKeys:
      type: array
      items:
        type: string
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    TimeConditionList:
      type: array
      items:
        $ref: '#/components/schemas/TimeCondition'
    TimeConditionOperator:
      type: string
      enum:
      - EQUALS_TO
      - NOT_EQUALS_TO
      - LESS_THAN_EQUAL_TO
      - GREATER_THAN_EQUAL_TO
