openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: batch
  x-aws-serviceName: batch
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2016-08-10'
  title: AWS Batch
  description: |-
    Batch

    Using Batch, you can run batch computing workloads on the Amazon Web Services Cloud. Batch computing is a common means for developers, scientists, and engineers to access large amounts of compute resources. Batch uses the advantages of the batch computing to remove the undifferentiated heavy lifting of configuring and managing required infrastructure. At the same time, it also adopts a familiar batch computing software approach. You can use Batch to efficiently provision resources, and work toward eliminating capacity constraints, reducing your overall compute costs, and delivering results more quickly.

    As a fully managed service, Batch can run batch computing workloads of any scale. Batch automatically provisions compute resources and optimizes workload distribution based on the quantity and scale of your specific workloads. With Batch, there's no need to install or manage batch computing software. This means that you can focus on analyzing results and solving your specific problems instead.
servers:
- description: The AWS Batch regional endpoint
  url: https://batch.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ArrayJobDependency:
      type: string
      enum:
      - N_TO_N
      - SEQUENTIAL
    ArrayJobStatusSummary:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Integer'
    AssignPublicIp:
      type: string
      enum:
      - ENABLED
      - DISABLED
    AttemptDetails:
      type: array
      items:
        $ref: '#/components/schemas/AttemptDetail'
    Boolean:
      type: boolean
    CEState:
      type: string
      enum:
      - ENABLED
      - DISABLED
    CEStatus:
      type: string
      enum:
      - CREATING
      - UPDATING
      - DELETING
      - DELETED
      - VALID
      - INVALID
    CEType:
      type: string
      enum:
      - MANAGED
      - UNMANAGED
    CRAllocationStrategy:
      type: string
      enum:
      - BEST_FIT
      - BEST_FIT_PROGRESSIVE
      - SPOT_CAPACITY_OPTIMIZED
      - SPOT_PRICE_CAPACITY_OPTIMIZED
    CRType:
      type: string
      enum:
      - EC2
      - SPOT
      - FARGATE
      - FARGATE_SPOT
    CRUpdateAllocationStrategy:
      type: string
      enum:
      - BEST_FIT_PROGRESSIVE
      - SPOT_CAPACITY_OPTIMIZED
      - SPOT_PRICE_CAPACITY_OPTIMIZED
    ClientRequestToken:
      type: string
      minLength: 1
      maxLength: 64
    ComputeEnvironmentDetailList:
      type: array
      items:
        $ref: '#/components/schemas/ComputeEnvironmentDetail'
    ComputeEnvironmentOrders:
      type: array
      items:
        $ref: '#/components/schemas/ComputeEnvironmentOrder'
    ConsumableResourceList:
      type: array
      items:
        $ref: '#/components/schemas/ConsumableResourceRequirement'
    ConsumableResourceSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/ConsumableResourceSummary'
    DeviceCgroupPermission:
      type: string
      enum:
      - READ
      - WRITE
      - MKNOD
    DeviceCgroupPermissions:
      type: array
      items:
        $ref: '#/components/schemas/DeviceCgroupPermission'
    DevicesList:
      type: array
      items:
        $ref: '#/components/schemas/Device'
    EFSAuthorizationConfigIAM:
      type: string
      enum:
      - ENABLED
      - DISABLED
    EFSTransitEncryption:
      type: string
      enum:
      - ENABLED
      - DISABLED
    Ec2ConfigurationList:
      type: array
      items:
        $ref: '#/components/schemas/Ec2Configuration'
    EksAnnotationsMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    EksAttemptContainerDetails:
      type: array
      items:
        $ref: '#/components/schemas/EksAttemptContainerDetail'
    EksAttemptDetails:
      type: array
      items:
        $ref: '#/components/schemas/EksAttemptDetail'
    EksContainerDetails:
      type: array
      items:
        $ref: '#/components/schemas/EksContainerDetail'
    EksContainerEnvironmentVariables:
      type: array
      items:
        $ref: '#/components/schemas/EksContainerEnvironmentVariable'
    EksContainerOverrideList:
      type: array
      items:
        $ref: '#/components/schemas/EksContainerOverride'
    EksContainerVolumeMounts:
      type: array
      items:
        $ref: '#/components/schemas/EksContainerVolumeMount'
    EksContainers:
      type: array
      items:
        $ref: '#/components/schemas/EksContainer'
    EksLabelsMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    EksLimits:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Quantity'
    EksRequests:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Quantity'
    EksVolumes:
      type: array
      items:
        $ref: '#/components/schemas/EksVolume'
    EnvironmentVariables:
      type: array
      items:
        $ref: '#/components/schemas/KeyValuePair'
    EvaluateOnExitList:
      type: array
      items:
        $ref: '#/components/schemas/EvaluateOnExit'
    FirelensConfigurationOptionsMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    FirelensConfigurationType:
      type: string
      enum:
      - fluentd
      - fluentbit
    Float:
      type: number
      format: float
    FrontOfQueueJobSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/FrontOfQueueJobSummary'
    ImageIdOverride:
      type: string
      minLength: 1
      maxLength: 256
    ImagePullSecrets:
      type: array
      items:
        $ref: '#/components/schemas/ImagePullSecret'
    ImageType:
      type: string
      minLength: 1
      maxLength: 256
    Integer:
      type: integer
    JQState:
      type: string
      enum:
      - ENABLED
      - DISABLED
    JQStatus:
      type: string
      enum:
      - CREATING
      - UPDATING
      - DELETING
      - DELETED
      - VALID
      - INVALID
    JobDefinitionList:
      type: array
      items:
        $ref: '#/components/schemas/JobDefinition'
    JobDefinitionType:
      type: string
      enum:
      - container
      - multinode
    JobDependencyList:
      type: array
      items:
        $ref: '#/components/schemas/JobDependency'
    JobDetailList:
      type: array
      items:
        $ref: '#/components/schemas/JobDetail'
    JobExecutionTimeoutMinutes:
      type: integer
      format: int64
      minimum: 1
      maximum: 360
    JobQueueDetailList:
      type: array
      items:
        $ref: '#/components/schemas/JobQueueDetail'
    JobStateTimeLimitActions:
      type: array
      items:
        $ref: '#/components/schemas/JobStateTimeLimitAction'
    JobStateTimeLimitActionsAction:
      type: string
      enum:
      - CANCEL
    JobStateTimeLimitActionsState:
      type: string
      enum:
      - RUNNABLE
    JobStatus:
      type: string
      enum:
      - SUBMITTED
      - PENDING
      - RUNNABLE
      - STARTING
      - RUNNING
      - SUCCEEDED
      - FAILED
    JobSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/JobSummary'
    KubernetesVersion:
      type: string
      minLength: 1
      maxLength: 256
    LaunchTemplateSpecificationOverrideList:
      type: array
      items:
        $ref: '#/components/schemas/LaunchTemplateSpecificationOverride'
    ListAttemptEcsTaskDetails:
      type: array
      items:
        $ref: '#/components/schemas/AttemptEcsTaskDetails'
    ListAttemptTaskContainerDetails:
      type: array
      items:
        $ref: '#/components/schemas/AttemptTaskContainerDetails'
    ListConsumableResourcesFilterList:
      type: array
      items:
        $ref: '#/components/schemas/KeyValuesPair'
    ListEcsTaskDetails:
      type: array
      items:
        $ref: '#/components/schemas/EcsTaskDetails'
    ListEcsTaskProperties:
      type: array
      items:
        $ref: '#/components/schemas/EcsTaskProperties'
    ListJobsByConsumableResourceFilterList:
      type: array
      items:
        $ref: '#/components/schemas/KeyValuesPair'
    ListJobsByConsumableResourceSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/ListJobsByConsumableResourceSummary'
    ListJobsFilterList:
      type: array
      items:
        $ref: '#/components/schemas/KeyValuesPair'
    ListTaskContainerDetails:
      type: array
      items:
        $ref: '#/components/schemas/TaskContainerDetails'
    ListTaskContainerOverrides:
      type: array
      items:
        $ref: '#/components/schemas/TaskContainerOverrides'
    ListTaskContainerProperties:
      type: array
      items:
        $ref: '#/components/schemas/TaskContainerProperties'
    ListTaskPropertiesOverride:
      type: array
      items:
        $ref: '#/components/schemas/TaskPropertiesOverride'
    LogConfigurationOptionsMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    LogDriver:
      type: string
      enum:
      - json-file
      - syslog
      - journald
      - gelf
      - fluentd
      - awslogs
      - splunk
      - awsfirelens
    Long:
      type: integer
      format: int64
    MountPoints:
      type: array
      items:
        $ref: '#/components/schemas/MountPoint'
    NetworkInterfaceList:
      type: array
      items:
        $ref: '#/components/schemas/NetworkInterface'
    NodePropertyOverrides:
      type: array
      items:
        $ref: '#/components/schemas/NodePropertyOverride'
    NodeRangeProperties:
      type: array
      items:
        $ref: '#/components/schemas/NodeRangeProperty'
    OrchestrationType:
      type: string
      enum:
      - ECS
      - EKS
    ParametersMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    PlatformCapability:
      type: string
      enum:
      - EC2
      - FARGATE
    PlatformCapabilityList:
      type: array
      items:
        $ref: '#/components/schemas/PlatformCapability'
    Quantity:
      type: string
      minLength: 1
      maxLength: 256
    ResourceRequirements:
      type: array
      items:
        $ref: '#/components/schemas/ResourceRequirement'
    ResourceType:
      type: string
      enum:
      - GPU
      - VCPU
      - MEMORY
    RetryAction:
      type: string
      enum:
      - RETRY
      - EXIT
    SchedulingPolicyDetailList:
      type: array
      items:
        $ref: '#/components/schemas/SchedulingPolicyDetail'
    SchedulingPolicyListingDetailList:
      type: array
      items:
        $ref: '#/components/schemas/SchedulingPolicyListingDetail'
    SecretList:
      type: array
      items:
        $ref: '#/components/schemas/Secret'
    ShareAttributesList:
      type: array
      items:
        $ref: '#/components/schemas/ShareAttributes'
    String:
      type: string
    StringList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagKeysList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TagrisTagsMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagsMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    TaskContainerDependencyList:
      type: array
      items:
        $ref: '#/components/schemas/TaskContainerDependency'
    TmpfsList:
      type: array
      items:
        $ref: '#/components/schemas/Tmpfs'
    Ulimits:
      type: array
      items:
        $ref: '#/components/schemas/Ulimit'
    Volumes:
      type: array
      items:
        $ref: '#/components/schemas/Volume'
