openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: bedrock_agent
  x-aws-serviceName: bedrockagent
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2023-06-05'
  title: Agents for Amazon Bedrock
  description: |-
    Describes the API operations for creating and managing Amazon Bedrock agents.
servers:
- description: The Agents for Amazon Bedrock regional endpoint
  url: https://bedrock-agent.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AgentAliasArn:
      type: string
      pattern: ^arn:aws:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:agent-alias/[0-9a-zA-Z]{10}/[0-9a-zA-Z]{10}$
      maxLength: 2048
    AgentAliasId:
      type: string
      pattern: ^(\bTSTALIASID\b|[0-9a-zA-Z]+)$
      minLength: 10
      maxLength: 10
    AgentArn:
      type: string
      pattern: ^arn:aws:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:agent/[0-9a-zA-Z]{10}$
      maxLength: 2048
    AgentRoleArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:iam::([0-9]{12})?:role/.+$
      maxLength: 2048
    AwsDataCatalogTableName:
      type: string
      pattern: ^.*\.*$
      minLength: 1
      maxLength: 200
    BasePromptTemplate:
      type: string
      minLength: 1
      maxLength: 100000
    BedrockEmbeddingModelArn:
      type: string
      pattern: ^(arn:aws(-[^:]{1,12})?:(bedrock|sagemaker):[a-z0-9-]{1,20}:([0-9]{12})?:([a-z-]+/)?)?([a-zA-Z0-9.-]{1,63}){0,2}(([:][a-z0-9-]{1,63}){0,2})?(/[a-z0-9]{1,12})?$
      minLength: 20
      maxLength: 2048
    BedrockModelArn:
      type: string
      pattern: ^(arn:aws(-[^:]{1,12})?:(bedrock):[a-z0-9-]{1,20}:([0-9]{12})?:([a-z-]+/)?)?([a-zA-Z0-9.-]{1,63}){0,2}(([:][a-z0-9-]{1,63}){0,2})?(/[a-z0-9]{1,12})?$
      minLength: 1
      maxLength: 2048
    BucketOwnerAccountId:
      type: string
      pattern: ^[0-9]{12}$
      minLength: 12
      maxLength: 12
    ClientToken:
      type: string
      pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,256}$
      minLength: 33
      maxLength: 256
    CollaborationInstruction:
      type: string
      minLength: 1
      maxLength: 4000
    ColumnName:
      type: string
      pattern: ^[a-zA-Z0-9_\-]+$
      maxLength: 63
    Data:
      type: string
      minLength: 1
      maxLength: 5242880
    Description:
      type: string
      minLength: 1
      maxLength: 200
    DescriptionString:
      type: string
      minLength: 1
      maxLength: 200
    Dimensions:
      type: integer
      minimum: 0
      maximum: 4096
    DraftVersion:
      type: string
      pattern: ^DRAFT$
      minLength: 5
      maxLength: 5
    ErrorMessage:
      type: string
      maxLength: 2048
    FailureReason:
      type: string
      maxLength: 2048
    FieldName:
      type: string
      pattern: ^.*$
      maxLength: 2048
    FilterPattern:
      type: string
      minLength: 1
      maxLength: 1000
    FilteredObjectType:
      type: string
      minLength: 1
      maxLength: 50
    FlowAliasArn:
      type: string
      pattern: ^arn:aws:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:flow/[0-9a-zA-Z]{10}/alias/(TSTALIASID|[0-9a-zA-Z]{10})$
    FlowAliasId:
      type: string
      pattern: ^(TSTALIASID|[0-9a-zA-Z]{10})$
    FlowAliasIdentifier:
      type: string
      pattern: ^(arn:aws:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:flow/[0-9a-zA-Z]{10}/alias/[0-9a-zA-Z]{10})|(TSTALIASID|[0-9a-zA-Z]{10})$
    FlowArn:
      type: string
      pattern: ^arn:aws:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:flow/[0-9a-zA-Z]{10}$
    FlowConditionExpression:
      type: string
      minLength: 1
      maxLength: 64
    FlowConditionName:
      type: string
      pattern: ^[a-zA-Z]([_]?[0-9a-zA-Z]){1,50}$
    FlowConnectionName:
      type: string
      pattern: ^[a-zA-Z]([_]?[0-9a-zA-Z]){1,100}$
    FlowDescription:
      type: string
      minLength: 1
      maxLength: 200
    FlowExecutionRoleArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:iam::([0-9]{12})?:role/(service-role/)?.+$
      maxLength: 2048
    FlowId:
      type: string
      pattern: ^[0-9a-zA-Z]{10}$
    FlowIdentifier:
      type: string
      pattern: ^(arn:aws:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:flow/[0-9a-zA-Z]{10})|([0-9a-zA-Z]{10})$
    FlowName:
      type: string
      pattern: ^([0-9a-zA-Z][_-]?){1,100}$
    FlowNodeInputExpression:
      type: string
      minLength: 1
      maxLength: 64
    FlowNodeInputName:
      type: string
      pattern: ^[a-zA-Z]([_]?[0-9a-zA-Z]){1,50}$
    FlowNodeName:
      type: string
      pattern: ^[a-zA-Z]([_]?[0-9a-zA-Z]){1,50}$
    FlowNodeOutputName:
      type: string
      pattern: ^[a-zA-Z]([_]?[0-9a-zA-Z]){1,50}$
    FunctionDescription:
      type: string
      minLength: 1
      maxLength: 1200
    GraphArn:
      type: string
      pattern: ^arn:aws(|-cn|-us-gov):neptune-graph:[a-zA-Z0-9-]*:[0-9]{12}:graph/g-[a-zA-Z0-9]{10}$
      minLength: 1
      maxLength: 255
    GuardrailIdentifier:
      type: string
      pattern: ^(([a-z0-9]+)|(arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:guardrail/[a-z0-9]+))$
      maxLength: 2048
    GuardrailVersion:
      type: string
      pattern: ^(([0-9]{1,8})|(DRAFT))$
    HttpsUrl:
      type: string
      pattern: ^https://[A-Za-z0-9][^\s]*$
    Id:
      type: string
      pattern: ^[0-9a-zA-Z]{10}$
    IngestionJobFilterValue:
      type: string
      pattern: ^.*$
      minLength: 0
      maxLength: 100
    Instruction:
      type: string
      minLength: 40
      maxLength: 4000
    KendraIndexArn:
      type: string
      pattern: ^arn:aws(|-cn|-us-gov):kendra:[a-z0-9-]{1,20}:([0-9]{12}|):index/([a-zA-Z0-9][a-zA-Z0-9-]{35}|[a-zA-Z0-9][a-zA-Z0-9-]{35}-[a-zA-Z0-9][a-zA-Z0-9-]{35})$
    Key:
      type: string
      minLength: 1
      maxLength: 200
    KmsKeyArn:
      type: string
      pattern: ^arn:aws(|-cn|-us-gov):kms:[a-zA-Z0-9-]*:[0-9]{12}:key/[a-zA-Z0-9-]{36}$
      minLength: 1
      maxLength: 2048
    KnowledgeBaseArn:
      type: string
      pattern: ^arn:aws(|-cn|-us-gov):bedrock:[a-zA-Z0-9-]*:[0-9]{12}:knowledge-base/[0-9a-zA-Z]+$
      maxLength: 128
    KnowledgeBaseId:
      type: string
      pattern: ^[0-9a-zA-Z]+$
      maxLength: 10
    KnowledgeBaseModelIdentifier:
      type: string
      pattern: ^(arn:aws(-[^:]{1,12})?:(bedrock|sagemaker):[a-z0-9-]{1,20}:([0-9]{12})?:([a-z-]+/)?)?([a-zA-Z0-9.-]{1,63}){0,2}(([:][a-z0-9-]{1,63}){0,2})?(/[a-z0-9]{1,12})?$
      minLength: 1
      maxLength: 2048
    KnowledgeBaseRoleArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:iam::([0-9]{12})?:role/.+$
      maxLength: 2048
    LambdaArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*)?:lambda:[a-z]{2}(-gov)?-[a-z]+-\d{1}:\d{12}:function:[a-zA-Z0-9-_\.]+(:(\$LATEST|[a-zA-Z0-9-_]+))?$
      maxLength: 2048
    LexBotAliasArn:
      type: string
      pattern: ^arn:aws(|-us-gov):lex:[a-z]{2}(-gov)?-[a-z]+-\d{1}:\d{12}:bot-alias/[0-9a-zA-Z]+/[0-9a-zA-Z]+$
      maxLength: 78
    LexBotLocaleId:
      type: string
      minLength: 1
      maxLength: 10
    MaxRecentSessions:
      type: integer
      minimum: 1
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
    MaximumLength:
      type: integer
      minimum: 0
    Microsoft365TenantId:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
      minLength: 36
      maxLength: 36
    ModelIdentifier:
      type: string
      pattern: ^(arn:aws(-[^:]{1,12})?:(bedrock|sagemaker):[a-z0-9-]{1,20}:([0-9]{12})?:([a-z-]+/)?)?([a-zA-Z0-9.-]{1,63}){0,2}(([:][a-z0-9-]{1,63}){0,2})?(/[a-z0-9]{1,12})?$
      minLength: 1
      maxLength: 2048
    MongoDbAtlasCollectionName:
      type: string
      pattern: ^.*$
      maxLength: 63
    MongoDbAtlasDatabaseName:
      type: string
      pattern: ^.*$
      maxLength: 63
    MongoDbAtlasEndpoint:
      type: string
      pattern: ^.*$
      maxLength: 2048
    MongoDbAtlasEndpointServiceName:
      type: string
      pattern: ^(?:arn:aws(?:-us-gov|-cn|-iso|-iso-[a-z])*:.+:.*:\d+:.+/.+$|[a-zA-Z0-9*]+[a-zA-Z0-9._-]*)$
      minLength: 1
      maxLength: 255
    MongoDbAtlasIndexName:
      type: string
      pattern: ^.*$
      maxLength: 2048
    Name:
      type: string
      pattern: ^([0-9a-zA-Z][_-]?){1,100}$
    NaturalLanguageString:
      type: string
      minLength: 1
      maxLength: 1000
    NextToken:
      type: string
      pattern: ^\S*$
      minLength: 1
      maxLength: 2048
    NonBlankString:
      type: string
      pattern: ^[\s\S]+$
    NonEmptyString:
      type: string
      minLength: 1
    NumericalVersion:
      type: string
      pattern: ^[0-9]{1,5}$
    OpenSearchManagedClusterDomainArn:
      type: string
      pattern: ^arn:aws(|-cn|-us-gov|-iso):es:[a-z]{2}(-gov)?-[a-z]+-\d{1}:\d{12}:domain/[a-z][a-z0-9-]{3,28}$
      maxLength: 2048
    OpenSearchManagedClusterDomainEndpoint:
      type: string
      pattern: ^https://.*$
      maxLength: 2048
    OpenSearchManagedClusterIndexName:
      type: string
      pattern: ^(?![\-_+.])[a-z0-9][a-z0-9\-_\.]*$
      minLength: 1
      maxLength: 2048
    OpenSearchServerlessCollectionArn:
      type: string
      pattern: ^arn:aws:aoss:[a-z]{2}(-gov)?-[a-z]+-\d{1}:\d{12}:collection/[a-z0-9-]{3,32}$
      maxLength: 2048
    OpenSearchServerlessIndexName:
      type: string
      pattern: ^.*$
      maxLength: 2048
    ParameterDescription:
      type: string
      minLength: 1
      maxLength: 500
    ParsingPromptText:
      type: string
      minLength: 1
      maxLength: 10000
    Payload:
      type: string
    PineconeConnectionString:
      type: string
      pattern: ^.*$
      maxLength: 2048
    PineconeNamespace:
      type: string
      pattern: ^.*$
      maxLength: 2048
    PromptArn:
      type: string
      pattern: ^(arn:aws:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:prompt/[0-9a-zA-Z]{10}(?::[0-9]{1,5})?)$
    PromptDescription:
      type: string
      minLength: 1
      maxLength: 200
    PromptId:
      type: string
      pattern: ^[0-9a-zA-Z]{10}$
    PromptIdentifier:
      type: string
      pattern: ^([0-9a-zA-Z]{10})|(arn:aws:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:prompt/[0-9a-zA-Z]{10})(?::[0-9]{1,5})?$
    PromptInputVariableName:
      type: string
      pattern: ^([0-9a-zA-Z][_-]?){1,100}$
    PromptMetadataKey:
      type: string
      pattern: ^[a-zA-Z0-9\s._:/=+@-]*$
      minLength: 1
      maxLength: 128
    PromptMetadataValue:
      type: string
      pattern: ^[a-zA-Z0-9\s._:/=+@-]*$
      minLength: 0
      maxLength: 1024
    PromptModelIdentifier:
      type: string
      pattern: ^(arn:aws(-[^:]{1,12})?:(bedrock|sagemaker):[a-z0-9-]{1,20}:([0-9]{12})?:([a-z-]+/)?)?([a-zA-Z0-9.-]{1,63}){0,2}(([:][a-z0-9-]{1,63}){0,2})?(/[a-z0-9]{1,12})?$
      minLength: 1
      maxLength: 2048
    PromptName:
      type: string
      pattern: ^([0-9a-zA-Z][_-]?){1,100}$
    PromptVariantName:
      type: string
      pattern: ^([0-9a-zA-Z][_-]?){1,100}$
    ProvisionedModelIdentifier:
      type: string
      pattern: ^((([0-9a-zA-Z][_-]?){1,63})|(arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:provisioned-model/[a-z0-9]{12}))$
      minLength: 1
      maxLength: 2048
    QueryExecutionTimeoutSeconds:
      type: integer
      minimum: 1
      maximum: 200
    QueryGenerationColumnName:
      type: string
      minLength: 1
      maxLength: 127
    QueryGenerationTableName:
      type: string
      pattern: ^.*\..*\..*$
    RdsArn:
      type: string
      pattern: ^arn:aws(|-cn|-us-gov):rds:[a-zA-Z0-9-]*:[0-9]{12}:cluster:[a-zA-Z0-9-]{1,63}$
    RdsDatabaseName:
      type: string
      pattern: ^[a-zA-Z0-9_\-]+$
      maxLength: 63
    RdsTableName:
      type: string
      pattern: ^[a-zA-Z0-9_\.\-]+$
      maxLength: 63
    RecommendedAction:
      type: string
      maxLength: 2048
    RedisEnterpriseCloudEndpoint:
      type: string
      pattern: ^.*$
      maxLength: 2048
    RedisEnterpriseCloudIndexName:
      type: string
      pattern: ^.*$
      maxLength: 2048
    RedshiftClusterIdentifier:
      type: string
      minLength: 1
      maxLength: 63
    RedshiftDatabase:
      type: string
      minLength: 1
      maxLength: 200
    S3BucketArn:
      type: string
      pattern: ^arn:aws(|-cn|-us-gov):s3:::[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$
      minLength: 1
      maxLength: 2048
    S3BucketName:
      type: string
      pattern: ^[a-z0-9][\.\-a-z0-9]{1,61}[a-z0-9]$
      minLength: 3
      maxLength: 63
    S3BucketUri:
      type: string
      pattern: ^s3://.{1,128}$
      minLength: 1
      maxLength: 2048
    S3ObjectKey:
      type: string
      pattern: ^[\.\-\!\*\_\'\(\)a-zA-Z0-9][\.\-\!\*\_\'\(\)\/a-zA-Z0-9]*$
      minLength: 1
      maxLength: 1024
    S3ObjectUri:
      type: string
      pattern: ^s3://[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]/.{1,1024}$
      minLength: 1
      maxLength: 1024
    S3Prefix:
      type: string
      minLength: 1
      maxLength: 300
    SecretArn:
      type: string
      pattern: ^arn:aws(|-cn|-us-gov):secretsmanager:[a-z0-9-]{1,20}:([0-9]{12}|):secret:[a-zA-Z0-9!/_+=.@-]{1,512}$
    SessionTTL:
      type: integer
      minimum: 60
      maximum: 3600
    SharePointDomain:
      type: string
      minLength: 1
      maxLength: 50
    SqlString:
      type: string
      minLength: 1
      maxLength: 1000
    StorageDays:
      type: integer
      default: 30
      minimum: 0
      maximum: 365
    StringValue:
      type: string
      minLength: 1
      maxLength: 2048
    TagKey:
      type: string
      pattern: ^[a-zA-Z0-9\s._:/=+@-]*$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^[a-zA-Z0-9\s._:/=+@-]*$
      minLength: 0
      maxLength: 256
    TaggableResourcesArn:
      type: string
      pattern: (^arn:aws:bedrock:[a-zA-Z0-9-]+:/d{12}:(agent|agent-alias|knowledge-base|flow|prompt)/[A-Z0-9]{10}(?:/[A-Z0-9]{10})?$|^arn:aws:bedrock:[a-zA-Z0-9-]+:/d{12}:flow/([A-Z0-9]{10})/alias/([A-Z0-9]{10})$|^arn:aws:bedrock:[a-zA-Z0-9-]+:/d{12}:prompt/([A-Z0-9]{10})?(?::/d+)?$)
      minLength: 20
      maxLength: 1011
    TextPrompt:
      type: string
      minLength: 1
    ToolName:
      type: string
      pattern: ^[a-zA-Z][a-zA-Z0-9_]*$
      minLength: 1
      maxLength: 64
    TopK:
      type: integer
      minimum: 0
      maximum: 500
    Url:
      type: string
      pattern: ^https?://[A-Za-z0-9][^\s]*$
    UserAgent:
      type: string
      minLength: 15
      maxLength: 40
    UserAgentHeader:
      type: string
      minLength: 61
      maxLength: 86
    Version:
      type: string
      pattern: ^(DRAFT|[0-9]{0,4}[1-9][0-9]{0,4})$
      minLength: 1
      maxLength: 5
    WorkgroupArn:
      type: string
      pattern: ^(arn:(aws(-[a-z]+)*):redshift-serverless:[a-z]{2}(-gov)?-[a-z]+-\d{1}:\d{12}:workgroup/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$
