openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: bedrock_agent_runtime
  x-aws-serviceName: bedrockagentruntime
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2023-07-26'
  title: Agents for Amazon Bedrock Runtime
  description: |-
    Contains APIs related to model invocation and querying of knowledge bases.
servers:
- description: The Agents for Amazon Bedrock Runtime regional endpoint
  url: https://bedrock-agent-runtime.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AWSResourceARN:
      type: string
      pattern: ^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:agent/[0-9a-zA-Z]{10}$
      maxLength: 2048
    ActionGroupName:
      type: string
    ActionGroupOutputString:
      type: string
    AdditionalModelRequestFieldsKey:
      type: string
      minLength: 1
      maxLength: 100
    AgentAliasArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:agent-alias/[0-9a-zA-Z]{10}/[0-9a-zA-Z]{10}$
      maxLength: 2048
    AgentAliasId:
      type: string
      pattern: ^[0-9a-zA-Z]+$
      maxLength: 10
    AgentCollaboratorPayloadString:
      type: string
    AgentId:
      type: string
      pattern: ^[0-9a-zA-Z]+$
      maxLength: 10
    AgentVersion:
      type: string
      pattern: ^(DRAFT|[0-9]{0,4}[1-9][0-9]{0,4})$
      minLength: 1
      maxLength: 5
    ApiPath:
      type: string
    BasePromptTemplate:
      type: string
      minLength: 1
      maxLength: 100000
    BedrockModelArn:
      type: string
      pattern: ^(arn:aws(-[^:]+)?:(bedrock|sagemaker):[a-z0-9-]{1,20}:([0-9]{12})?:([a-z-]+/)?)?([a-z0-9.-]{1,63}){0,2}(([:][a-z0-9-]{1,63}){0,2})?(/[a-z0-9]{1,12})?$
      minLength: 1
      maxLength: 2048
    BedrockRerankingModelArn:
      type: string
      pattern: ^(arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}::foundation-model/(.*))?$
      minLength: 1
      maxLength: 2048
    CollaborationInstruction:
      type: string
      minLength: 1
      maxLength: 4000
    ContentType:
      type: string
      pattern: '[a-z]{1,20}/.{1,20}'
    FailureReasonString:
      type: string
    FilterKey:
      type: string
      minLength: 1
      maxLength: 100
    FinalResponseString:
      type: string
    FlowAliasIdentifier:
      type: string
      pattern: ^(arn:aws:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:flow/[0-9a-zA-Z]{10}/alias/[0-9a-zA-Z]{10})|(\bTSTALIASID\b|[0-9a-zA-Z]+)$
      maxLength: 2048
    FlowExecutionId:
      type: string
      pattern: ^[0-9a-zA-Z._:-]+$
      minLength: 2
      maxLength: 100
    FlowIdentifier:
      type: string
      pattern: ^(arn:aws:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:flow/[0-9a-zA-Z]{10})|([0-9a-zA-Z]{10})$
      maxLength: 2048
    Function:
      type: string
    FunctionDescription:
      type: string
      minLength: 1
      maxLength: 1200
    GuardrailIdentifierWithArn:
      type: string
      pattern: ^(([a-z0-9]+)|(arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:guardrail/[a-z0-9]+))$
      maxLength: 2048
    GuardrailVersion:
      type: string
      pattern: ^(([1-9][0-9]{0,7})|(DRAFT))$
      minLength: 1
      maxLength: 5
    Identifier:
      type: string
      minLength: 1
      maxLength: 1024
    InputText:
      type: string
      maxLength: 25000000
    Instruction:
      type: string
      minLength: 40
    InvocationDescription:
      type: string
      minLength: 1
      maxLength: 200
    InvocationIdentifier:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
    KmsKeyArn:
      type: string
      pattern: ^arn:aws(|-cn|-us-gov):kms:[a-zA-Z0-9-]*:[0-9]{12}:key/[a-zA-Z0-9-]{36}$
      minLength: 1
      maxLength: 2048
    KnowledgeBaseArn:
      type: string
      pattern: ^arn:aws(|-cn|-us-gov):bedrock:[a-zA-Z0-9-]*:[0-9]{12}:knowledge-base/[0-9a-zA-Z]+$
      maxLength: 128
    KnowledgeBaseId:
      type: string
      pattern: ^[0-9a-zA-Z]+$
      maxLength: 10
    KnowledgeBaseLookupInputString:
      type: string
    LambdaArn:
      type: string
    LambdaResourceArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*)?:lambda:[a-z]{2}(-gov)?-[a-z]+-\d{1}:\d{12}:function:[a-zA-Z0-9-_\.]+(:(\$LATEST|[a-zA-Z0-9-_]+))?$
      maxLength: 2048
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
      description: Max Results.
    MaxTokens:
      type: integer
      minimum: 0
      maximum: 65536
    MaximumLength:
      type: integer
      minimum: 0
      maximum: 8192
    MemoryId:
      type: string
      pattern: ^[0-9a-zA-Z._:-]+$
      minLength: 2
      maxLength: 100
    MimeType:
      type: string
    ModelIdentifier:
      type: string
      pattern: (^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:(([0-9]{12}:custom-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}(([:][a-z0-9-]{1,63}){0,2})?/[a-z0-9]{12})|(:foundation-model/([a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.]?[a-z0-9-]{1,63})([:][a-z0-9-]{1,63}){0,2})))|(([a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.]?[a-z0-9-]{1,63})([:][a-z0-9-]{1,63}){0,2}))|(([0-9a-zA-Z][_-]?)+))$|(^arn:aws(|-us-gov|-cn|-iso|-iso-b):bedrock:(|[0-9a-z-]{1,20}):(|[0-9]{12}):inference-profile/[a-zA-Z0-9-:.]+)$
      minLength: 1
      maxLength: 2048
    Name:
      type: string
      pattern: ^([0-9a-zA-Z][_-]?){1,100}$
    NextToken:
      type: string
      pattern: ^\S*$
      minLength: 1
      maxLength: 2048
    NodeInputName:
      type: string
      pattern: ^[a-zA-Z]([_]?[0-9a-zA-Z]){0,99}$
    NodeName:
      type: string
      pattern: ^[a-zA-Z]([_]?[0-9a-zA-Z]){0,99}$
    NodeOutputName:
      type: string
      pattern: ^[a-zA-Z]([_]?[0-9a-zA-Z]){0,99}$
    NonBlankString:
      type: string
      pattern: ^[\s\S]*$
    OutputString:
      type: string
    ParameterDescription:
      type: string
      minLength: 1
      maxLength: 500
    ParameterName:
      type: string
      pattern: ^([0-9a-zA-Z][_-]?){1,100}$
    Payload:
      type: string
    PromptText:
      type: string
    RationaleString:
      type: string
    ResourceDescription:
      type: string
      minLength: 1
      maxLength: 200
    ResourceName:
      type: string
      pattern: ^([0-9a-zA-Z][_-]?){1,100}$
    RetrievalResultMetadataKey:
      type: string
      minLength: 1
      maxLength: 100
    S3BucketName:
      type: string
      pattern: ^[a-z0-9][\.\-a-z0-9]{1,61}[a-z0-9]$
      minLength: 3
      maxLength: 63
    S3ObjectKey:
      type: string
      pattern: ^[\.\-\!\*\_\'\(\)a-zA-Z0-9][\.\-\!\*\_\'\(\)\/a-zA-Z0-9]*$
      minLength: 1
      maxLength: 1024
    S3Uri:
      type: string
      pattern: ^s3://[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]/.{1,1024}$
      minLength: 1
      maxLength: 1024
    SessionArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]+:[0-9]{12}:session/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
    SessionId:
      type: string
      pattern: ^[0-9a-zA-Z._:-]+$
      minLength: 2
      maxLength: 100
    SessionIdentifier:
      type: string
      pattern: ^(arn:aws(-[^:]+)?:bedrock:[a-z0-9-]+:[0-9]{12}:session/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})|([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})$
    SessionMetadataKey:
      type: string
      minLength: 1
      maxLength: 100
    SessionMetadataValue:
      type: string
      minLength: 0
      maxLength: 5000
    SessionTTL:
      type: integer
      minimum: 60
      maximum: 3600
    SummaryText:
      type: string
      minLength: 0
      maxLength: 25000000
    TagKey:
      type: string
      pattern: ^[a-zA-Z0-9\s._:/=+@-]*$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^[a-zA-Z0-9\s._:/=+@-]*$
      minLength: 0
      maxLength: 256
    TaggableResourcesArn:
      type: string
      pattern: (^arn:aws(-[^:]+)?:bedrock:[a-zA-Z0-9-]+:[0-9]{12}:(session)/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$)
      minLength: 20
      maxLength: 1011
    TextPromptTemplate:
      type: string
      minLength: 1
      maxLength: 4000
    TopK:
      type: integer
      minimum: 0
      maximum: 500
    TraceId:
      type: string
      minLength: 2
      maxLength: 16
    TraceKnowledgeBaseId:
      type: string
    Uuid:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
    Verb:
      type: string
