openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: bedrock
  x-aws-serviceName: bedrock
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2023-04-20'
  title: Amazon Bedrock
  description: |-
    Describes the API operations for creating, managing, fine-turning, and evaluating Amazon Bedrock models.
servers:
- description: The Amazon Bedrock regional endpoint
  url: https://bedrock.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AcceptEula:
      type: boolean
      default: false
    AccountId:
      type: string
      pattern: ^[0-9]{12}$
    AdditionalModelRequestFieldsKey:
      type: string
      minLength: 1
      maxLength: 100
    Arn:
      type: string
      maxLength: 2048
    BaseModelIdentifier:
      type: string
      pattern: ^(arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:(([0-9]{12}:custom-model/([a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.]?[a-z0-9-]{1,63})([:][a-z0-9-]{1,63}){0,2})/[a-z0-9]{12})|(:foundation-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([:][a-z0-9-]{1,63}){0,2})))|([a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.]?[a-z0-9-]{1,63})([:][a-z0-9-]{1,63}){0,2})|(([0-9a-zA-Z][_-]?)+)$
      minLength: 1
      maxLength: 2048
    BedrockModelArn:
      type: string
      pattern: ^(arn:aws(-[^:]+)?:(bedrock|sagemaker):[a-z0-9-]{1,20}:([0-9]{12})?:([a-z-]+/)?)?([a-zA-Z0-9.-]{1,63}){0,2}(([:][a-z0-9-]{1,63}){0,2})?(/[a-z0-9]{1,12})?$
      minLength: 1
      maxLength: 2048
    BedrockModelId:
      type: string
      pattern: ^[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([a-z0-9-]{1,63}[.]){0,2}[a-z0-9-]{1,63}([:][a-z0-9-]{1,63}){0,2}(/[a-z0-9]{12}|)$
      maxLength: 140
    BrandedName:
      type: string
      pattern: ^.*$
      minLength: 1
      maxLength: 20
    BucketName:
      type: string
      minLength: 3
      maxLength: 63
    ContentType:
      type: string
      pattern: '[a-z]{1,20}/.{1,20}'
    CustomMetricInstructions:
      type: string
      minLength: 1
      maxLength: 5000
    CustomModelArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:custom-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([a-z0-9-]{1,63}[.]){0,2}[a-z0-9-]{1,63}([:][a-z0-9-]{1,63}){0,2}/[a-z0-9]{12}$
      minLength: 20
      maxLength: 1011
    CustomModelName:
      type: string
      pattern: ^([0-9a-zA-Z][_-]?){1,63}$
      minLength: 1
      maxLength: 63
    CustomModelUnitsVersion:
      type: string
      pattern: ^v\d+.\d+$
    EndpointName:
      type: string
      minLength: 1
      maxLength: 30
    ErrorMessage:
      type: string
      maxLength: 2048
    EvaluationBedrockModelIdentifier:
      type: string
      pattern: ^(arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:((:foundation-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.:]?[a-z0-9-]{1,63}))|([0-9]{12}:provisioned-model/[a-z0-9]{12})|([0-9]{12}:imported-model/[a-z0-9]{12})|([0-9]{12}:application-inference-profile/[a-z0-9]{12})|([0-9]{12}:inference-profile/(([a-z-]{2,8}.)[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.:]?[a-z0-9-]{1,63})))|([0-9]{12}:(default-prompt-router|prompt-router)/[a-zA-Z0-9-:.]+)))|(([a-z]{2,4}[.]{1})([a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.:]?[a-z0-9-]{1,63})))|([a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.:]?[a-z0-9-]{1,63}))|arn:aws(-[^:]+)?:sagemaker:[a-z0-9-]{1,20}:[0-9]{12}:endpoint/[a-z0-9-]{1,63}$
      minLength: 1
      maxLength: 2048
    EvaluationDatasetName:
      type: string
      pattern: ^[0-9a-zA-Z-_.]+$
      minLength: 1
      maxLength: 63
    EvaluationJobArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:evaluation-job/[a-z0-9]{12}$
      maxLength: 1011
    EvaluationJobDescription:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 200
    EvaluationJobIdentifier:
      type: string
      pattern: ^(arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:evaluation-job/[a-z0-9]{12})$
      maxLength: 1011
    EvaluationJobName:
      type: string
      pattern: ^[a-z0-9](-*[a-z0-9]){0,62}$
      minLength: 1
      maxLength: 63
    EvaluationMetricDescription:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 63
    EvaluationMetricName:
      type: string
      pattern: ^[0-9a-zA-Z-_.]+$
      minLength: 1
      maxLength: 63
    EvaluationModelInferenceParams:
      type: string
      minLength: 1
      maxLength: 1023
    EvaluationPrecomputedInferenceSourceIdentifier:
      type: string
      pattern: ^[a-zA-Z0-9]([a-zA-Z0-9._-]){0,255}$
      minLength: 1
      maxLength: 256
    EvaluationPrecomputedRagSourceIdentifier:
      type: string
      pattern: ^[a-zA-Z0-9]([a-zA-Z0-9._-]){0,255}$
      minLength: 1
      maxLength: 256
    EvaluationRatingMethod:
      type: string
      pattern: ^[0-9a-zA-Z-_]+$
      minLength: 1
      maxLength: 100
    EvaluatorModelIdentifier:
      type: string
      pattern: ^(arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:((:foundation-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.:]?[a-z0-9-]{1,63}))|([0-9]{12}:inference-profile/(([a-z-]{2,8}.)[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.:]?[a-z0-9-]{1,63})))))$|(^[a-z0-9-]+[.][a-z0-9-]+([.][a-z0-9-]+)*(:[a-z0-9-]+)?$)|^[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([a-z0-9-]{1,63}[.]){0,2}[a-z0-9-]{1,63}([:][a-z0-9-]{1,63}){0,2}(/[a-z0-9]{12}|)$
      minLength: 1
      maxLength: 2048
    FilterKey:
      type: string
      minLength: 1
      maxLength: 100
    FoundationModelArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}::foundation-model/[a-z0-9-]{1,63}[.]{1}([a-z0-9-]{1,63}[.]){0,2}[a-z0-9-]{1,63}([:][a-z0-9-]{1,63}){0,2}$
    GuardrailArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:guardrail/[a-z0-9]+$
      maxLength: 2048
    GuardrailBlockedMessaging:
      type: string
      minLength: 1
      maxLength: 500
    GuardrailDescription:
      type: string
      minLength: 1
      maxLength: 200
    GuardrailDraftVersion:
      type: string
      pattern: ^DRAFT$
      minLength: 5
      maxLength: 5
    GuardrailFailureRecommendation:
      type: string
      minLength: 1
      maxLength: 200
    GuardrailId:
      type: string
      pattern: ^[a-z0-9]+$
      maxLength: 64
    GuardrailIdentifier:
      type: string
      pattern: ^(([a-z0-9]+)|(arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:guardrail/[a-z0-9]+))$
      maxLength: 2048
    GuardrailName:
      type: string
      pattern: ^[0-9a-zA-Z-_]+$
      minLength: 1
      maxLength: 50
    GuardrailNumericalVersion:
      type: string
      pattern: ^[1-9][0-9]{0,7}$
    GuardrailStatusReason:
      type: string
      minLength: 1
      maxLength: 200
    GuardrailTopicDefinition:
      type: string
      minLength: 1
      maxLength: 200
    GuardrailTopicExample:
      type: string
      minLength: 1
      maxLength: 100
    GuardrailTopicName:
      type: string
      pattern: ^[0-9a-zA-Z-_ !?.]+$
      minLength: 1
      maxLength: 100
    GuardrailVersion:
      type: string
      pattern: ^(([1-9][0-9]{0,7})|(DRAFT))$
    HumanTaskInstructions:
      type: string
      pattern: ^[\S\s]+$
      minLength: 1
      maxLength: 5000
    IdempotencyToken:
      type: string
      pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*$
      minLength: 1
      maxLength: 256
    Identifier:
      type: string
      minLength: 1
      maxLength: 1024
    ImportedModelArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:imported-model/[a-z0-9]{12}$
      minLength: 20
      maxLength: 1011
    ImportedModelIdentifier:
      type: string
      pattern: ^(arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:imported-model/[a-z0-9]{12})|(([0-9a-zA-Z][_-]?)+)$
      minLength: 1
      maxLength: 1011
    ImportedModelName:
      type: string
      pattern: ^([0-9a-zA-Z][_-]?)+$
      minLength: 1
      maxLength: 63
    InferenceProfileArn:
      type: string
      pattern: ^arn:aws(|-us-gov|-cn|-iso|-iso-b):bedrock:(|[0-9a-z-]{0,20}):(|[0-9]{12}):(inference-profile|application-inference-profile)/[a-zA-Z0-9-:.]+$
      minLength: 1
      maxLength: 2048
    InferenceProfileDescription:
      type: string
      pattern: ^([0-9a-zA-Z:.][ _-]?)+$
      minLength: 1
      maxLength: 200
    InferenceProfileId:
      type: string
      pattern: ^[a-zA-Z0-9-:.]+$
      minLength: 1
      maxLength: 64
    InferenceProfileIdentifier:
      type: string
      pattern: ^(arn:aws(|-us-gov|-cn|-iso|-iso-b):bedrock:(|[0-9a-z-]{0,20}):(|[0-9]{12}):(inference-profile|application-inference-profile)/)?[a-zA-Z0-9-:.]+$
      minLength: 1
      maxLength: 2048
    InferenceProfileModelSourceArn:
      type: string
      pattern: ^arn:aws(|-us-gov|-cn|-iso|-iso-b):bedrock:(|[0-9a-z-]{0,20}):(|[0-9]{12}):(inference-profile|foundation-model)/[a-zA-Z0-9-:.]+$
      minLength: 1
      maxLength: 2048
    InferenceProfileName:
      type: string
      pattern: ^([0-9a-zA-Z][ _-]?)+$
      minLength: 1
      maxLength: 64
    InstanceCount:
      type: integer
      minimum: 1
    InstanceType:
      type: string
      minLength: 1
      maxLength: 50
    InstructSupported:
      type: boolean
    JobName:
      type: string
      pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9\+\-\.])*$
      minLength: 1
      maxLength: 63
    KeyPrefix:
      type: string
      maxLength: 1024
    KmsKeyArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:kms:[a-zA-Z0-9-]*:[0-9]{12}:key/[a-zA-Z0-9-]{36}$
      minLength: 1
      maxLength: 2048
    KmsKeyId:
      type: string
      pattern: ^(arn:aws(-[^:]+)?:kms:[a-zA-Z0-9-]*:[0-9]{12}:((key/[a-zA-Z0-9-]{36})|(alias/[a-zA-Z0-9-_/]+)))|([a-zA-Z0-9-]{36})|(alias/[a-zA-Z0-9-_/]+)$
      minLength: 1
      maxLength: 2048
    KnowledgeBaseId:
      type: string
      pattern: ^[0-9a-zA-Z]+$
      maxLength: 10
    LogGroupName:
      type: string
      minLength: 1
      maxLength: 512
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
    MaxTokens:
      type: integer
      minimum: 0
      maximum: 65536
    Message:
      type: string
      maxLength: 2048
    MetricName:
      type: string
      pattern: ^[0-9a-zA-Z-_.]+$
      minLength: 1
      maxLength: 63
    ModelArchitecture:
      type: string
    ModelArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:(([0-9]{12}:custom-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}(([:][a-z0-9-]{1,63}){0,2})?/[a-z0-9]{12})|(:foundation-model/[a-z0-9-]{1,63}[.]{1}([a-z0-9-]{1,63}[.]){0,2}[a-z0-9-]{1,63}([:][a-z0-9-]{1,63}){0,2}))$
      minLength: 20
      maxLength: 1011
    ModelCopyJobArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:model-copy-job/[a-z0-9]{12}$
      maxLength: 1011
    ModelCustomizationJobArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:model-customization-job/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([a-z0-9-]{1,63}[.]){0,2}[a-z0-9-]{1,63}([:][a-z0-9-]{1,63}){0,2}/[a-z0-9]{12}$
      maxLength: 1011
    ModelCustomizationJobIdentifier:
      type: string
      pattern: ^(arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:model-customization-job/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([a-z0-9-]{1,63}[.]){0,2}[a-z0-9-]{1,63}([:][a-z0-9-]{1,63}){0,2}/[a-z0-9]{12})|([a-zA-Z0-9](-*[a-zA-Z0-9\+\-\.])*)$
      maxLength: 1011
    ModelId:
      type: string
      pattern: ^(arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:(([0-9]{12}:custom-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-:]{1,63}/[a-z0-9]{12}$)|(:foundation-model/([a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.]?[a-z0-9-]{1,63})([:][a-z0-9-]{1,63}){0,2})|(([0-9a-zA-Z][_-]?)+)$)|([0-9]{12}:(inference-profile|application-inference-profile)/[a-zA-Z0-9-:.]+$)))|([a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.]?[a-z0-9-]{1,63})([:][a-z0-9-]{1,63}){0,2})|(([0-9a-zA-Z][_-]?)+)$
      minLength: 1
      maxLength: 2048
    ModelIdentifier:
      type: string
      pattern: ^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:(([0-9]{12}:custom-model/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}(([:][a-z0-9-]{1,63}){0,2})?/[a-z0-9]{12})|(:foundation-model/([a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.]?[a-z0-9-]{1,63})([:][a-z0-9-]{1,63}){0,2})))|(([a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.]?[a-z0-9-]{1,63})([:][a-z0-9-]{1,63}){0,2}))|(([0-9a-zA-Z][_-]?)+)$
      minLength: 1
      maxLength: 2048
    ModelImportJobArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:model-import-job/[a-z0-9]{12}$
      maxLength: 1011
    ModelImportJobIdentifier:
      type: string
      pattern: ^(arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:model-import-job/[a-z0-9]{12})|([a-zA-Z0-9](-*[a-zA-Z0-9\+\-\.])*)$
      maxLength: 1011
    ModelInvocationIdempotencyToken:
      type: string
      pattern: ^[a-zA-Z0-9]{1,256}(-*[a-zA-Z0-9]){0,256}$
      minLength: 1
      maxLength: 256
    ModelInvocationJobArn:
      type: string
      pattern: ^(arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:model-invocation-job/[a-z0-9]{12})$
      maxLength: 1011
    ModelInvocationJobIdentifier:
      type: string
      pattern: ^((arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:model-invocation-job/)?[a-z0-9]{12})$
      maxLength: 1011
    ModelInvocationJobName:
      type: string
      pattern: ^[a-zA-Z0-9]{1,63}(-*[a-zA-Z0-9\+\-\.]){0,63}$
      minLength: 1
      maxLength: 63
    ModelInvocationJobTimeoutDurationInHours:
      type: integer
      minimum: 24
      maximum: 168
    ModelName:
      type: string
      pattern: ^([a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63})$
      minLength: 1
      maxLength: 63
    ModelSourceIdentifier:
      type: string
      pattern: arn:aws:sagemaker:.*:hub-content/SageMakerPublicHub/Model/.*
      maxLength: 2048
    NonBlankString:
      type: string
      pattern: ^[\s\S]*$
    PaginationToken:
      type: string
      pattern: ^\S*$
      minLength: 1
      maxLength: 2048
    PositiveInteger:
      type: integer
      minimum: 1
    PromptRouterArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:default-prompt-router/[a-zA-Z0-9-:.]+$
      minLength: 1
      maxLength: 2048
    PromptRouterDescription:
      type: string
      pattern: ^([0-9a-zA-Z:.][ _-]?)+$
      minLength: 1
      maxLength: 200
    PromptRouterName:
      type: string
      pattern: ^([0-9a-zA-Z][ _-]?)+$
      minLength: 1
      maxLength: 64
    PromptRouterTargetModelArn:
      type: string
      pattern: (^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}::foundation-model/[a-z0-9-]{1,63}[.]{1}([a-z0-9-]{1,63}[.]){0,2}[a-z0-9-]{1,63}([:][a-z0-9-]{1,63}){0,2})|(^arn:aws(|-us-gov|-cn|-iso|-iso-b):bedrock:(|[0-9a-z-]{0,20}):(|[0-9]{12}):(inference-profile|application-inference-profile)/[a-zA-Z0-9-:.]+)$
      minLength: 1
      maxLength: 2048
    Provider:
      type: string
      pattern: ^[A-Za-z0-9- ]{1,63}$
    ProvisionedModelArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:provisioned-model/[a-z0-9]{12}$
    ProvisionedModelId:
      type: string
      pattern: ^((([0-9a-zA-Z][_-]?)+)|(arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:provisioned-model/[a-z0-9]{12}))$
    ProvisionedModelName:
      type: string
      pattern: ^([0-9a-zA-Z][_-]?)+$
      minLength: 1
      maxLength: 63
    RatingScaleItemDefinition:
      type: string
      minLength: 1
      maxLength: 100
    RoleArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:iam::([0-9]{12})?:role/.+$
      maxLength: 2048
    S3Uri:
      type: string
      pattern: ^s3://[a-z0-9][-.a-z0-9]{1,61}[a-z0-9](?:/[-!_*'().a-z0-9A-Z]+(?:/[-!_*'().a-z0-9A-Z]+)*)?/?$
      minLength: 1
      maxLength: 1024
    SageMakerFlowDefinitionArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:sagemaker:[a-z0-9-]{1,20}:[0-9]{12}:flow-definition/.*$
      maxLength: 1024
    SecurityGroupId:
      type: string
      pattern: ^[-0-9a-zA-Z]+$
      maxLength: 32
    SubnetId:
      type: string
      pattern: ^[-0-9a-zA-Z]+$
      maxLength: 32
    TagKey:
      type: string
      pattern: ^[a-zA-Z0-9\s._:/=+@-]*$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^[a-zA-Z0-9\s._:/=+@-]*$
      minLength: 0
      maxLength: 256
    TaggableResourcesArn:
      type: string
      pattern: (^[a-zA-Z0-9][a-zA-Z0-9\-]*$)|(^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:([0-9]{12}|)((:(fine-tuning-job|model-customization-job|custom-model)/[a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([a-z0-9-]{1,63}[.]){0,2}[a-z0-9-]{1,63}([:][a-z0-9-]{1,63}){0,2}(/[a-z0-9]{12})$)|(:guardrail/[a-z0-9]+$)|(:automated-reasoning-policy/[a-zA-Z0-9]+(:[a-zA-Z0-9]+)?$)|(:(inference-profile|application-inference-profile)/[a-zA-Z0-9-:.]+$)|(:(provisioned-model|model-invocation-job|model-evaluation-job|evaluation-job|model-import-job|imported-model|async-invoke|provisioned-model-v2|provisioned-model-reservation|prompt-router)/[a-z0-9]{12}$)))
      minLength: 20
      maxLength: 1011
    TeacherModelIdentifier:
      type: string
      pattern: ^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}::foundation-model/[a-z0-9-]{1,63}[.]{1}([a-z0-9-]{1,63}[.]){0,2}[a-z0-9-]{1,63}([:][a-z0-9-]{1,63}){0,2}|([a-z0-9-]{1,63}[.]{1}[a-z0-9-]{1,63}([.]?[a-z0-9-]{1,63})([:][a-z0-9-]{1,63}){0,2})|(([0-9a-zA-Z][_-]?)+)$
    TextPromptTemplate:
      type: string
      minLength: 1
      maxLength: 100000
    UsePromptResponse:
      type: boolean
      default: false
    kBS3Uri:
      type: string
      pattern: ^s3://[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]/.{1,1024}$
      minLength: 1
      maxLength: 1024
