openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: bedrock_data_automation
  x-aws-serviceName: bedrockdataautomation
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2023-07-26'
  title: Data Automation for Amazon Bedrock
  description: |-
    Amazon Bedrock Data Automation BuildTime
servers:
- description: The Data Automation for Amazon Bedrock regional endpoint
  url: https://bedrock-data-automation.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AudioExtractionCategoryType:
      type: string
      enum:
      - AUDIO_CONTENT_MODERATION
      - TRANSCRIPT
      - TOPIC_CONTENT_MODERATION
    AudioExtractionCategoryTypes:
      type: array
      items:
        $ref: '#/components/schemas/AudioExtractionCategoryType'
      description: List of Audio Extraction Category Type
    AudioStandardGenerativeFieldType:
      type: string
      enum:
      - AUDIO_SUMMARY
      - IAB
      - TOPIC_SUMMARY
    AudioStandardGenerativeFieldTypes:
      type: array
      items:
        $ref: '#/components/schemas/AudioStandardGenerativeFieldType'
      description: List of Audio Standard Generative Field Type
    BlueprintArn:
      type: string
      pattern: ^arn:aws(|-cn|-us-gov):bedrock:[a-zA-Z0-9-]*:(aws|[0-9]{12}):blueprint/(bedrock-data-automation-public-[a-zA-Z0-9-_]{1,30}|[a-zA-Z0-9-]{12,36})$
      maxLength: 128
    BlueprintItems:
      type: array
      items:
        $ref: '#/components/schemas/BlueprintItem'
      description: List of Blueprint Item
    BlueprintName:
      type: string
      pattern: ^[a-zA-Z0-9-_]+$
      minLength: 1
      maxLength: 128
    BlueprintSchema:
      type: string
      minLength: 1
      maxLength: 100000
    BlueprintStage:
      type: string
      enum:
      - DEVELOPMENT
      - LIVE
      description: Stage of the Blueprint
    BlueprintStageFilter:
      type: string
      enum:
      - DEVELOPMENT
      - LIVE
      - ALL
      description: Blueprint Stage filter
    BlueprintVersion:
      type: string
      pattern: ^[0-9]*$
      minLength: 1
      maxLength: 128
    Blueprints:
      type: array
      items:
        $ref: '#/components/schemas/BlueprintSummary'
      description: List of Blueprints
    ClientToken:
      type: string
      pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,256}$
      minLength: 33
      maxLength: 256
    DataAutomationProjectArn:
      type: string
      pattern: ^arn:aws(|-cn|-us-gov):bedrock:[a-zA-Z0-9-]*:(aws|[0-9]{12}):data-automation-project/[a-zA-Z0-9-]{12,36}$
      maxLength: 128
    DataAutomationProjectDescription:
      type: string
      minLength: 0
      maxLength: 300
    DataAutomationProjectName:
      type: string
      pattern: ^[a-zA-Z0-9-_]+$
      minLength: 1
      maxLength: 128
    DataAutomationProjectStage:
      type: string
      enum:
      - DEVELOPMENT
      - LIVE
      description: Stage of the Project
    DataAutomationProjectStageFilter:
      type: string
      enum:
      - DEVELOPMENT
      - LIVE
      - ALL
      description: Project Stage filter
    DataAutomationProjectStatus:
      type: string
      enum:
      - COMPLETED
      - IN_PROGRESS
      - FAILED
      description: Status of Data Automation Project
    DataAutomationProjectSummaries:
      type: array
      items:
        $ref: '#/components/schemas/DataAutomationProjectSummary'
      description: List of DataAutomationProjectSummary
    DateTimestamp:
      type: string
      format: date-time
      description: Time Stamp
    DesiredModality:
      type: string
      enum:
      - IMAGE
      - DOCUMENT
      - AUDIO
      - VIDEO
      description: Desired Modality types
    DocumentExtractionGranularityType:
      type: string
      enum:
      - DOCUMENT
      - PAGE
      - ELEMENT
      - WORD
      - LINE
    DocumentExtractionGranularityTypes:
      type: array
      items:
        $ref: '#/components/schemas/DocumentExtractionGranularityType'
      description: List of Document Extraction Granularity Type
    DocumentOutputTextFormatType:
      type: string
      enum:
      - PLAIN_TEXT
      - MARKDOWN
      - HTML
      - CSV
    DocumentOutputTextFormatTypes:
      type: array
      items:
        $ref: '#/components/schemas/DocumentOutputTextFormatType'
      description: List of Document Output Text Format Type
    EncryptionContextKey:
      type: string
      pattern: ^.*\S.*$
      minLength: 1
      maxLength: 2000
    EncryptionContextValue:
      type: string
      pattern: ^.*\S.*$
      minLength: 1
      maxLength: 2000
    ImageExtractionCategoryType:
      type: string
      enum:
      - CONTENT_MODERATION
      - TEXT_DETECTION
      - LOGOS
    ImageExtractionCategoryTypes:
      type: array
      items:
        $ref: '#/components/schemas/ImageExtractionCategoryType'
      description: List of Image Extraction Category
    ImageStandardGenerativeFieldType:
      type: string
      enum:
      - IMAGE_SUMMARY
      - IAB
    ImageStandardGenerativeFieldTypes:
      type: array
      items:
        $ref: '#/components/schemas/ImageStandardGenerativeFieldType'
      description: List of Image Standard Generative Field Type
    KmsEncryptionContext:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/EncryptionContextValue'
      description: KMS Encryption Context
    KmsKeyId:
      type: string
      pattern: ^[A-Za-z0-9][A-Za-z0-9:_/+=,@.-]+$
      minLength: 1
      maxLength: 2048
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
      description: Max Results
    NextToken:
      type: string
      pattern: ^\S*$
      minLength: 1
      maxLength: 2048
    NonBlankString:
      type: string
      pattern: ^[\s\S]+$
    ResourceOwner:
      type: string
      enum:
      - SERVICE
      - ACCOUNT
      description: Resource Owner
    State:
      type: string
      enum:
      - ENABLED
      - DISABLED
      description: State
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
      description: List of tag keys
    TagList:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
      description: List of tags
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TaggableResourceArn:
      type: string
      pattern: ^arn:aws(|-cn|-us-gov):bedrock:[a-z0-9-]*:[0-9]{12}:(blueprint|data-automation-project)/[a-zA-Z0-9-]{12,36}$
      minLength: 20
      maxLength: 1011
    Type:
      type: string
      enum:
      - DOCUMENT
      - IMAGE
      description: Type
    ValidationExceptionFieldList:
      type: array
      items:
        $ref: '#/components/schemas/ValidationExceptionField'
      description: list of ValidationExceptionField
    VideoExtractionCategoryType:
      type: string
      enum:
      - CONTENT_MODERATION
      - TEXT_DETECTION
      - TRANSCRIPT
      - LOGOS
    VideoExtractionCategoryTypes:
      type: array
      items:
        $ref: '#/components/schemas/VideoExtractionCategoryType'
      description: List of Video Extraction Category Type
    VideoStandardGenerativeFieldType:
      type: string
      enum:
      - VIDEO_SUMMARY
      - IAB
      - CHAPTER_SUMMARY
    VideoStandardGenerativeFieldTypes:
      type: array
      items:
        $ref: '#/components/schemas/VideoStandardGenerativeFieldType'
      description: List of Video Standard Generative Field Type
