openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: billingconductor
  x-aws-serviceName: billingconductor
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2021-07-30'
  title: AWSBillingConductor
  description: |-
    Amazon Web Services Billing Conductor is a fully managed service that you can use to customize a [proforma](https://docs.aws.amazon.com/billingconductor/latest/userguide/understanding-eb.html#eb-other-definitions) version of your billing data each month, to accurately show or chargeback your end customers. Amazon Web Services Billing Conductor doesn't change the way you're billed by Amazon Web Services each month by design. Instead, it provides you with a mechanism to configure, generate, and display rates to certain customers over a given billing period. You can also analyze the difference between the rates you apply to your accounting groupings relative to your actual rates from Amazon Web Services. As a result of your Amazon Web Services Billing Conductor configuration, the payer account can also see the custom rate applied on the billing details page of the [Amazon Web Services Billing console](https://console.aws.amazon.com/billing), or configure a cost and usage report per billing group.

    This documentation shows how you can configure Amazon Web Services Billing Conductor using its API. For more information about using the [Amazon Web Services Billing Conductor](https://console.aws.amazon.com/billingconductor/) user interface, see the [ Amazon Web Services Billing Conductor User Guide](https://docs.aws.amazon.com/billingconductor/latest/userguide/what-is-billingconductor.html).
servers:
- description: The AWSBillingConductor regional endpoint
  url: https://billingconductor.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AWSCost:
      type: string
    AccountEmail:
      type: string
    AccountId:
      type: string
      pattern: ^[0-9]{12}$
    AccountName:
      type: string
    Arn:
      type: string
      pattern: ^arn:aws(-cn)?:billingconductor::[0-9]{12}:billinggroup/?[0-9]{12}$|^arn:aws(-cn)?:billingconductor::[0-9]{12}:pricingplan/[a-zA-Z0-9]{10}$|^arn:aws(-cn)?:billingconductor::[0-9]{12}:pricingrule/[a-zA-Z0-9]{10}$|^(arn:aws(-cn)?:billingconductor::[0-9]{12}:customlineitem/)?[a-zA-Z0-9]{10}$
      minLength: 0
      maxLength: 100
    AssociateResourceErrorReason:
      type: string
      enum:
      - INVALID_ARN
      - SERVICE_LIMIT_EXCEEDED
      - ILLEGAL_CUSTOMLINEITEM
      - INTERNAL_SERVER_EXCEPTION
      - INVALID_BILLING_PERIOD_RANGE
    Association:
      type: string
      pattern: ^((arn:aws(-cn)?:billingconductor::[0-9]{12}:billinggroup/)?[0-9]{12}|MONITORED|UNMONITORED)$
    BillingEntity:
      type: string
      pattern: ^[a-zA-Z0-9 ]+$
    BillingGroupArn:
      type: string
      pattern: ^(arn:aws(-cn)?:billingconductor::[0-9]{12}:billinggroup/)?[0-9]{12}$
    BillingGroupDescription:
      type: string
      minLength: 0
      maxLength: 1024
    BillingGroupFullArn:
      type: string
      pattern: ^arn:aws(-cn)?:billingconductor::[0-9]{12}:billinggroup/[0-9]{12}$
    BillingGroupName:
      type: string
      pattern: ^[a-zA-Z0-9_\+=\.\-@]+$
      minLength: 1
      maxLength: 128
    BillingGroupStatus:
      type: string
      enum:
      - ACTIVE
      - PRIMARY_ACCOUNT_MISSING
    BillingGroupStatusReason:
      type: string
    BillingPeriod:
      type: string
      pattern: ^\d{4}-(0?[1-9]|1[012])$
    ClientToken:
      type: string
      pattern: ^[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 64
    ConflictExceptionReason:
      type: string
      enum:
      - RESOURCE_NAME_CONFLICT
      - PRICING_RULE_IN_PRICING_PLAN_CONFLICT
      - PRICING_PLAN_ATTACHED_TO_BILLING_GROUP_DELETE_CONFLICT
      - PRICING_RULE_ATTACHED_TO_PRICING_PLAN_DELETE_CONFLICT
      - WRITE_CONFLICT_RETRY
    Currency:
      type: string
    CurrencyCode:
      type: string
      enum:
      - USD
      - CNY
    CustomLineItemArn:
      type: string
      pattern: ^(arn:aws(-cn)?:billingconductor::[0-9]{12}:customlineitem/)?[a-zA-Z0-9]{10}$
    CustomLineItemAssociationElement:
      type: string
      pattern: ^(arn:aws(-cn)?:billingconductor::[0-9]{12}:(customlineitem|billinggroup)/)?[a-zA-Z0-9]{10,12}$
    CustomLineItemDescription:
      type: string
      minLength: 1
      maxLength: 255
    CustomLineItemName:
      type: string
      pattern: ^[a-zA-Z0-9_\+=\.\-@]+$
      minLength: 1
      maxLength: 128
    CustomLineItemProductCode:
      type: string
      minLength: 1
      maxLength: 29
    CustomLineItemRelationship:
      type: string
      enum:
      - PARENT
      - CHILD
    CustomLineItemType:
      type: string
      enum:
      - CREDIT
      - FEE
    GroupByAttributeName:
      type: string
      enum:
      - PRODUCT_NAME
      - BILLING_PERIOD
    LineItemFilterAttributeName:
      type: string
      enum:
      - LINE_ITEM_TYPE
    LineItemFilterValue:
      type: string
      enum:
      - SAVINGS_PLAN_NEGATION
    Margin:
      type: string
    MarginPercentage:
      type: string
    MatchOption:
      type: string
      enum:
      - NOT_EQUAL
    MaxBillingGroupCostReportResults:
      type: integer
      minimum: 200
      maximum: 300
    MaxBillingGroupResults:
      type: integer
      minimum: 1
      maximum: 100
    MaxCustomLineItemResults:
      type: integer
      minimum: 1
      maximum: 100
    MaxPricingPlanResults:
      type: integer
      minimum: 1
      maximum: 100
    MaxPricingRuleResults:
      type: integer
      minimum: 1
      maximum: 100
    Operation:
      type: string
      pattern: ^\S+$
      minLength: 1
      maxLength: 256
    PricingPlanArn:
      type: string
      pattern: ^(arn:aws(-cn)?:billingconductor::[0-9]{12}:pricingplan/)?[a-zA-Z0-9]{10}$
    PricingPlanDescription:
      type: string
      minLength: 0
      maxLength: 1024
    PricingPlanFullArn:
      type: string
      pattern: ^arn:aws(-cn)?:billingconductor::[0-9]{12}:pricingplan/[a-zA-Z0-9]{10}$
    PricingPlanName:
      type: string
      pattern: ^[a-zA-Z0-9_\+=\.\-@]+$
      minLength: 1
      maxLength: 128
    PricingRuleArn:
      type: string
      pattern: ^(arn:aws(-cn)?:billingconductor::[0-9]{12}:pricingrule/)?[a-zA-Z0-9]{10}$
    PricingRuleDescription:
      type: string
      minLength: 0
      maxLength: 1024
    PricingRuleName:
      type: string
      pattern: ^[a-zA-Z0-9_\+=\.\-@]+$
      minLength: 1
      maxLength: 128
    PricingRuleScope:
      type: string
      enum:
      - GLOBAL
      - SERVICE
      - BILLING_ENTITY
      - SKU
    PricingRuleType:
      type: string
      enum:
      - MARKUP
      - DISCOUNT
      - TIERING
    ProformaCost:
      type: string
    RetryAfterSeconds:
      type: integer
      default: 0
    Service:
      type: string
      pattern: ^[a-zA-Z0-9]+$
      minLength: 1
      maxLength: 128
    String:
      type: string
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TieringActivated:
      type: boolean
    Token:
      type: string
    UsageType:
      type: string
      pattern: ^\S+$
      minLength: 1
      maxLength: 256
    ValidationExceptionReason:
      type: string
      enum:
      - UNKNOWN_OPERATION
      - CANNOT_PARSE
      - FIELD_VALIDATION_FAILED
      - OTHER
      - PRIMARY_NOT_ASSOCIATED
      - PRIMARY_CANNOT_DISASSOCIATE
      - ACCOUNTS_NOT_ASSOCIATED
      - ACCOUNTS_ALREADY_ASSOCIATED
      - ILLEGAL_PRIMARY_ACCOUNT
      - ILLEGAL_ACCOUNTS
      - MISMATCHED_BILLINGGROUP_ARN
      - MISSING_BILLINGGROUP
      - MISMATCHED_CUSTOMLINEITEM_ARN
      - ILLEGAL_BILLING_PERIOD
      - ILLEGAL_BILLING_PERIOD_RANGE
      - TOO_MANY_ACCOUNTS_IN_REQUEST
      - DUPLICATE_ACCOUNT
      - INVALID_BILLING_GROUP_STATUS
      - MISMATCHED_PRICINGPLAN_ARN
      - MISSING_PRICINGPLAN
      - MISMATCHED_PRICINGRULE_ARN
      - DUPLICATE_PRICINGRULE_ARNS
      - ILLEGAL_EXPRESSION
      - ILLEGAL_SCOPE
      - ILLEGAL_SERVICE
      - PRICINGRULES_NOT_EXIST
      - PRICINGRULES_ALREADY_ASSOCIATED
      - PRICINGRULES_NOT_ASSOCIATED
      - INVALID_TIME_RANGE
      - INVALID_BILLINGVIEW_ARN
      - MISMATCHED_BILLINGVIEW_ARN
      - ILLEGAL_CUSTOMLINEITEM
      - MISSING_CUSTOMLINEITEM
      - ILLEGAL_CUSTOMLINEITEM_UPDATE
      - TOO_MANY_CUSTOMLINEITEMS_IN_REQUEST
      - ILLEGAL_CHARGE_DETAILS
      - ILLEGAL_UPDATE_CHARGE_DETAILS
      - INVALID_ARN
      - ILLEGAL_RESOURCE_ARNS
      - ILLEGAL_CUSTOMLINEITEM_MODIFICATION
      - MISSING_LINKED_ACCOUNT_IDS
      - MULTIPLE_LINKED_ACCOUNT_IDS
      - MISSING_PRICING_PLAN_ARN
      - MULTIPLE_PRICING_PLAN_ARN
      - ILLEGAL_CHILD_ASSOCIATE_RESOURCE
      - CUSTOM_LINE_ITEM_ASSOCIATION_EXISTS
      - INVALID_BILLING_GROUP
      - INVALID_BILLING_PERIOD_FOR_OPERATION
      - ILLEGAL_BILLING_ENTITY
      - ILLEGAL_MODIFIER_PERCENTAGE
      - ILLEGAL_TYPE
      - ILLEGAL_ENDED_BILLINGGROUP
      - ILLEGAL_TIERING_INPUT
      - ILLEGAL_OPERATION
      - ILLEGAL_USAGE_TYPE
      - INVALID_SKU_COMBO
      - INVALID_FILTER
      - TOO_MANY_AUTO_ASSOCIATE_BILLING_GROUPS
      - CANNOT_DELETE_AUTO_ASSOCIATE_BILLING_GROUP
      - ILLEGAL_ACCOUNT_ID
