openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: braket
  x-aws-serviceName: braket
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2019-09-01'
  title: Braket
  description: |-
    The Amazon Braket API Reference provides information about the operations and structures supported in Amazon Braket.

    Additional Resources:

      * [Amazon Braket Developer Guide](https://docs.aws.amazon.com/braket/latest/developerguide/what-is-braket.html)
servers:
- description: The Braket regional endpoint
  url: https://braket.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AssociationType:
      type: string
      enum:
      - RESERVATION_TIME_WINDOW_ARN
    Associations:
      type: array
      items:
        $ref: '#/components/schemas/Association'
    BraketResourceArn:
      type: string
      pattern: ^arn:aws[a-z\-]*:braket:[a-z0-9\-]*:[0-9]{12}:.*$
    CancellationStatus:
      type: string
      enum:
      - CANCELLING
      - CANCELLED
    CompressionType:
      type: string
      enum:
      - NONE
      - GZIP
    DeviceArn:
      type: string
      minLength: 1
      maxLength: 256
    DeviceQueueInfoList:
      type: array
      items:
        $ref: '#/components/schemas/DeviceQueueInfo'
    DeviceStatus:
      type: string
      enum:
      - ONLINE
      - OFFLINE
      - RETIRED
    DeviceSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/DeviceSummary'
    DeviceType:
      type: string
      enum:
      - QPU
      - SIMULATOR
    HybridJobAdditionalAttributeName:
      type: string
      enum:
      - QueueInfo
    HybridJobAdditionalAttributeNamesList:
      type: array
      items:
        $ref: '#/components/schemas/HybridJobAdditionalAttributeName'
    HyperParameters:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    InputConfigList:
      type: array
      items:
        $ref: '#/components/schemas/InputFileConfig'
    InstanceType:
      type: string
      enum:
      - ml.m4.xlarge
      - ml.m4.2xlarge
      - ml.m4.4xlarge
      - ml.m4.10xlarge
      - ml.m4.16xlarge
      - ml.g4dn.xlarge
      - ml.g4dn.2xlarge
      - ml.g4dn.4xlarge
      - ml.g4dn.8xlarge
      - ml.g4dn.12xlarge
      - ml.g4dn.16xlarge
      - ml.m5.large
      - ml.m5.xlarge
      - ml.m5.2xlarge
      - ml.m5.4xlarge
      - ml.m5.12xlarge
      - ml.m5.24xlarge
      - ml.c4.xlarge
      - ml.c4.2xlarge
      - ml.c4.4xlarge
      - ml.c4.8xlarge
      - ml.p2.xlarge
      - ml.p2.8xlarge
      - ml.p2.16xlarge
      - ml.p3.2xlarge
      - ml.p3.8xlarge
      - ml.p3.16xlarge
      - ml.p3dn.24xlarge
      - ml.p4d.24xlarge
      - ml.c5.xlarge
      - ml.c5.2xlarge
      - ml.c5.4xlarge
      - ml.c5.9xlarge
      - ml.c5.18xlarge
      - ml.c5n.xlarge
      - ml.c5n.2xlarge
      - ml.c5n.4xlarge
      - ml.c5n.9xlarge
      - ml.c5n.18xlarge
    JobArn:
      type: string
      pattern: ^arn:aws[a-z\-]*:braket:[a-z0-9\-]+:[0-9]{12}:job/.*$
    JobEventType:
      type: string
      enum:
      - WAITING_FOR_PRIORITY
      - QUEUED_FOR_EXECUTION
      - STARTING_INSTANCE
      - DOWNLOADING_DATA
      - RUNNING
      - DEPRIORITIZED_DUE_TO_INACTIVITY
      - UPLOADING_RESULTS
      - COMPLETED
      - FAILED
      - MAX_RUNTIME_EXCEEDED
      - CANCELLED
    JobEvents:
      type: array
      items:
        $ref: '#/components/schemas/JobEventDetails'
    JobPrimaryStatus:
      type: string
      enum:
      - QUEUED
      - RUNNING
      - COMPLETED
      - FAILED
      - CANCELLING
      - CANCELLED
    JobSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/JobSummary'
    JobToken:
      type: string
      minLength: 1
      maxLength: 128
    JsonValue:
      type: string
    QuantumTaskAdditionalAttributeName:
      type: string
      enum:
      - QueueInfo
    QuantumTaskAdditionalAttributeNamesList:
      type: array
      items:
        $ref: '#/components/schemas/QuantumTaskAdditionalAttributeName'
    QuantumTaskArn:
      type: string
      minLength: 0
      maxLength: 256
    QuantumTaskStatus:
      type: string
      enum:
      - CREATED
      - QUEUED
      - RUNNING
      - COMPLETED
      - FAILED
      - CANCELLING
      - CANCELLED
    QuantumTaskSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/QuantumTaskSummary'
    QueueName:
      type: string
      enum:
      - QUANTUM_TASKS_QUEUE
      - JOBS_QUEUE
    QueuePriority:
      type: string
      enum:
      - Normal
      - Priority
    RoleArn:
      type: string
      pattern: ^arn:aws[a-z\-]*:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$
    S3Path:
      type: string
      pattern: ^(https|s3)://([^/]+)/?(.*)$
      maxLength: 1024
    SearchDevicesFilterList:
      type: array
      items:
        $ref: '#/components/schemas/SearchDevicesFilter'
    SearchJobsFilterList:
      type: array
      items:
        $ref: '#/components/schemas/SearchJobsFilter'
    SearchJobsFilterOperator:
      type: string
      enum:
      - LT
      - LTE
      - EQUAL
      - GT
      - GTE
      - BETWEEN
      - CONTAINS
    SearchQuantumTasksFilterList:
      type: array
      items:
        $ref: '#/components/schemas/SearchQuantumTasksFilter'
    SearchQuantumTasksFilterOperator:
      type: string
      enum:
      - LT
      - LTE
      - EQUAL
      - GT
      - GTE
      - BETWEEN
    String1024:
      type: string
      minLength: 1
      maxLength: 1024
    String2048:
      type: string
      minLength: 1
      maxLength: 2048
    String256:
      type: string
      minLength: 1
      maxLength: 256
    String256List:
      type: array
      items:
        $ref: '#/components/schemas/String256'
    String4096:
      type: string
      minLength: 1
      maxLength: 4096
    String64:
      type: string
      minLength: 1
      maxLength: 64
    TagKeys:
      type: array
      items:
        type: string
    TagsMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    Uri:
      type: string
      pattern: \d{10,14}\.dkr\.ecr.[a-z0-9-]+\.amazonaws\.com\/.+(@sha256)?:.+
      minLength: 1
      maxLength: 255
