openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: chatbot
  x-aws-serviceName: chatbot
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-10-11'
  title: AWS Chatbot
  description: |-
    The _AWS Chatbot API Reference_ provides descriptions, API request parameters, and the XML response for each of the AWS Chatbot API actions.

    AWS Chatbot APIs are currently available in the following Regions:

      * US East (Ohio) - `us-east-2`

      * US West (Oregon) - `us-west-2`

      * Asia Pacific (Singapore) - `ap-southeast-1`

      * Europe (Ireland) - `eu-west-1`

    The AWS Chatbot console can only be used in US East (Ohio). Your configuration data however, is stored in each of the relevant available Regions.

    Your AWS CloudTrail events are logged in whatever Region you call from, not US East (N. Virginia) by default.
servers:
- description: The AWS Chatbot regional endpoint
  url: https://chatbot.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AmazonResourceName:
      type: string
      pattern: ^arn:aws:(wheatley|chatbot):[A-Za-z0-9_/.-]{0,63}:[A-Za-z0-9_/.-]{0,63}:[A-Za-z0-9][A-Za-z0-9:_/+=,@.-]{0,1023}$
      minLength: 1
      maxLength: 1011
    Arn:
      type: string
      pattern: ^arn:aws:[A-Za-z0-9][A-Za-z0-9_/.-]{0,62}:[A-Za-z0-9_/.-]{0,63}:[A-Za-z0-9_/.-]{0,63}:[A-Za-z0-9][A-Za-z0-9:_/+=,@.-]{0,1023}$
      minLength: 12
      maxLength: 1224
    AwsUserIdentity:
      type: string
      pattern: ^arn:aws:(iam|sts)::[A-Za-z0-9_/.-]{0,63}:[A-Za-z0-9][A-Za-z0-9:_/+=,@.-]{0,1023}$
      minLength: 15
      maxLength: 1101
    BooleanAccountPreference:
      type: boolean
    ChatConfigurationArn:
      type: string
      pattern: ^arn:aws:(wheatley|chatbot):[A-Za-z0-9_/.-]{0,63}:[A-Za-z0-9_/.-]{0,63}:[A-Za-z0-9][A-Za-z0-9:_/+=,@.-]{0,1023}$
      minLength: 19
      maxLength: 1169
    ChimeWebhookDescription:
      type: string
      minLength: 1
      maxLength: 255
    ChimeWebhookUrl:
      type: string
      pattern: ^https://hooks\.chime\.aws/incomingwebhooks/[A-Za-z0-9\-]+?\?token=[A-Za-z0-9\-]+$
      minLength: 1
      maxLength: 255
    ClientToken:
      type: string
      pattern: ^[\x21-\x7F]+$
      minLength: 33
      maxLength: 126
    ConfigurationName:
      type: string
      pattern: ^[A-Za-z0-9-_]+$
      minLength: 1
      maxLength: 128
    CustomActionAliasName:
      type: string
      pattern: ^[A-Za-z0-9-_]+$
      minLength: 1
      maxLength: 30
    CustomActionArn:
      type: string
      pattern: ^arn:aws:chatbot:[A-Za-z0-9_/.-]{0,63}:[A-Za-z0-9_/.-]{0,63}:custom-action/[a-zA-Z0-9_-]{1,64}$
      minLength: 1
      maxLength: 1011
    CustomActionAttachmentNotificationType:
      type: string
      pattern: ^[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 100
    CustomActionButtonText:
      type: string
      pattern: ^[\S\s]+$
      minLength: 1
      maxLength: 50
    CustomActionName:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,64}$
      minLength: 1
      maxLength: 64
    CustomerCwLogLevel:
      type: string
      pattern: ^(ERROR|INFO|NONE)$
      minLength: 4
      maxLength: 5
    ErrorMessage:
      type: string
    GuardrailPolicyArn:
      type: string
      pattern: ^(^$|(?!.*\/aws-service-role\/.*)arn:aws:iam:[A-Za-z0-9_\/.-]{0,63}:[A-Za-z0-9_\/.-]{0,63}:[A-Za-z0-9][A-Za-z0-9:_\/+=,@.-]{0,1023})$
      minLength: 11
      maxLength: 1163
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    PaginationToken:
      type: string
      pattern: ^[a-zA-Z0-9=\/+_.\-,#:\\"{}]{4,1276}$
      minLength: 1
      maxLength: 1276
    ResourceIdentifier:
      type: string
      pattern: ^arn:aws:chatbot:[A-Za-z0-9_/.-]{0,63}:[A-Za-z0-9_/.-]{0,63}:custom-action/[a-zA-Z0-9_-]{1,64}$
      minLength: 1
      maxLength: 1011
    ResourceState:
      type: string
      pattern: ^(ENABLED|DISABLED)$
    SlackChannelDisplayName:
      type: string
      minLength: 1
      maxLength: 255
    SlackChannelId:
      type: string
      pattern: ^[A-Za-z0-9]+$
      minLength: 1
      maxLength: 255
    SlackTeamId:
      type: string
      pattern: ^[0-9A-Z]{1,255}$
      minLength: 1
      maxLength: 255
    SlackTeamName:
      type: string
      minLength: 1
      maxLength: 255
    SlackUserId:
      type: string
      pattern: ^(.*)$
      minLength: 1
      maxLength: 255
    String:
      type: string
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TeamName:
      type: string
      pattern: ^(.*)$
      minLength: 1
      maxLength: 255
    TeamsChannelId:
      type: string
      pattern: ^([a-zA-Z0-9-_=+\/.,])*%3[aA]([a-zA-Z0-9-_=+\/.,])*%40([a-zA-Z0-9-_=+\/.,])*$
      minLength: 1
      maxLength: 255
    TeamsChannelName:
      type: string
      pattern: ^(.*)$
      minLength: 1
      maxLength: 1000
    UUID:
      type: string
      pattern: ^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$
      minLength: 36
      maxLength: 36
