openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: chime
  x-aws-serviceName: chime
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-01'
  title: Amazon Chime
  description: "**Most of these APIs are no longer supported and will not be updated.**\
    \ We recommend using the latest versions in the [Amazon Chime SDK API reference](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/welcome.html),\
    \ in the Amazon Chime SDK.\n\nUsing the latest versions requires migrating to\
    \ dedicated namespaces. For more information, refer to [Migrating from the Amazon\
    \ Chime namespace](https://docs.aws.amazon.com/chime-sdk/latest/dg/migrate-from-chm-namespace.html)\
    \ in the _Amazon Chime SDK Developer Guide_.\n\nThe Amazon Chime application programming\
    \ interface (API) is designed so administrators can perform key tasks, such as\
    \ creating and managing Amazon Chime accounts, users, and Voice Connectors. This\
    \ guide provides detailed information about the Amazon Chime API, including operations,\
    \ types, inputs and outputs, and error codes.\n\nYou can use an AWS SDK, the AWS\
    \ Command Line Interface (AWS CLI), or the REST API to make API calls for Amazon\
    \ Chime. We recommend using an AWS SDK or the AWS CLI. The page for each API action\
    \ contains a _See Also_ section that includes links to information about using\
    \ the action with a language-specific AWS SDK or the AWS CLI.\n\nUsing an AWS\
    \ SDK\n\n    \n\nYou don't need to write code to calculate a signature for request\
    \ authentication. The SDK clients authenticate your requests by using access keys\
    \ that you provide. For more information about AWS SDKs, see the [AWS Developer\
    \ Center](http://aws.amazon.com/developer/).\n\nUsing the AWS CLI\n\n    \n\n\
    Use your access keys with the AWS CLI to make API calls. For information about\
    \ setting up the AWS CLI, see [Installing the AWS Command Line Interface](https://docs.aws.amazon.com/cli/latest/userguide/installing.html)\
    \ in the _AWS Command Line Interface User Guide_. For a list of available Amazon\
    \ Chime commands, see the [Amazon Chime commands](https://docs.aws.amazon.com/cli/latest/reference/chime/index.html)\
    \ in the _AWS CLI Command Reference_.\n\nUsing REST APIs\n\n    \n\nIf you use\
    \ REST to make API calls, you must authenticate your request by providing a signature.\
    \ Amazon Chime supports Signature Version 4. For more information, see [Signature\
    \ Version 4 Signing Process](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html)\
    \ in the _Amazon Web Services General Reference_.\n\nWhen making REST API calls,\
    \ use the service name `chime` and REST endpoint `https://service.chime.aws.amazon.com`.\n\
    \nAdministrative permissions are controlled using AWS Identity and Access Management\
    \ (IAM). For more information, see [Identity and Access Management for Amazon\
    \ Chime](https://docs.aws.amazon.com/chime/latest/ag/security-iam.html) in the\
    \ _Amazon Chime Administration Guide_."
servers:
- description: The Amazon Chime regional endpoint
  url: https://chime.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccountList:
      type: array
      items:
        $ref: '#/components/schemas/Account'
    AccountName:
      type: string
      pattern: \S
      minLength: 1
      maxLength: 100
    AccountStatus:
      type: string
      enum:
      - Suspended
      - Active
    AccountType:
      type: string
      enum:
      - Team
      - EnterpriseDirectory
      - EnterpriseLWA
      - EnterpriseOIDC
    Alpha2CountryCode:
      type: string
      pattern: ^[A-Z]{2}$
    Boolean:
      type: boolean
    BotList:
      type: array
      items:
        $ref: '#/components/schemas/Bot'
    BotType:
      type: string
      enum:
      - ChatBot
    CallingName:
      type: string
      pattern: ^$|^[a-zA-Z0-9 ]{2,15}$
    CallingNameStatus:
      type: string
      enum:
      - Unassigned
      - UpdateInProgress
      - UpdateSucceeded
      - UpdateFailed
    ClientRequestToken:
      type: string
      pattern: ^[-_a-zA-Z0-9]*$
      minLength: 2
      maxLength: 64
    E164PhoneNumber:
      type: string
      pattern: ^\+?[1-9]\d{1,14}$
    E164PhoneNumberList:
      type: array
      items:
        $ref: '#/components/schemas/E164PhoneNumber'
    EmailAddress:
      type: string
      pattern: ^.+@.+\..+$
    EmailStatus:
      type: string
      enum:
      - NotSent
      - Sent
      - Failed
    ErrorCode:
      type: string
      enum:
      - BadRequest
      - Conflict
      - Forbidden
      - NotFound
      - PreconditionFailed
      - ResourceLimitExceeded
      - ServiceFailure
      - AccessDenied
      - ServiceUnavailable
      - Throttled
      - Throttling
      - Unauthorized
      - Unprocessable
      - VoiceConnectorGroupAssociationsExist
      - PhoneNumberAssociationsExist
    GuidString:
      type: string
      pattern: ^[a-fA-F0-9]{8}(?:-[a-fA-F0-9]{4}){3}-[a-fA-F0-9]{12}$
    InviteList:
      type: array
      items:
        $ref: '#/components/schemas/Invite'
    InviteStatus:
      type: string
      enum:
      - Pending
      - Accepted
      - Failed
    Iso8601Timestamp:
      type: string
      format: date-time
    JoinTokenString:
      type: string
      pattern: ^[a-zA-Z0-9+/]+$
      minLength: 2
      maxLength: 2048
    License:
      type: string
      enum:
      - Basic
      - Plus
      - Pro
      - ProTrial
    LicenseList:
      type: array
      items:
        $ref: '#/components/schemas/License'
    MemberErrorList:
      type: array
      items:
        $ref: '#/components/schemas/MemberError'
    MemberType:
      type: string
      enum:
      - User
      - Bot
      - Webhook
    MembershipItemList:
      type: array
      items:
        $ref: '#/components/schemas/MembershipItem'
    NonEmptyString:
      type: string
      pattern: \S
    NonEmptyStringList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    NullableBoolean:
      type: boolean
    OrderedPhoneNumberList:
      type: array
      items:
        $ref: '#/components/schemas/OrderedPhoneNumber'
    OrderedPhoneNumberStatus:
      type: string
      enum:
      - Processing
      - Acquired
      - Failed
    PhoneNumberAssociationList:
      type: array
      items:
        $ref: '#/components/schemas/PhoneNumberAssociation'
    PhoneNumberAssociationName:
      type: string
      enum:
      - AccountId
      - UserId
      - VoiceConnectorId
      - VoiceConnectorGroupId
      - SipRuleId
    PhoneNumberCountriesList:
      type: array
      items:
        $ref: '#/components/schemas/PhoneNumberCountry'
    PhoneNumberErrorList:
      type: array
      items:
        $ref: '#/components/schemas/PhoneNumberError'
    PhoneNumberList:
      type: array
      items:
        $ref: '#/components/schemas/PhoneNumber'
    PhoneNumberMaxResults:
      type: integer
      minimum: 1
      maximum: 500
    PhoneNumberOrderList:
      type: array
      items:
        $ref: '#/components/schemas/PhoneNumberOrder'
    PhoneNumberOrderStatus:
      type: string
      enum:
      - Processing
      - Successful
      - Failed
      - Partial
    PhoneNumberProductType:
      type: string
      enum:
      - BusinessCalling
      - VoiceConnector
      - SipMediaApplicationDialIn
    PhoneNumberStatus:
      type: string
      enum:
      - AcquireInProgress
      - AcquireFailed
      - Unassigned
      - Assigned
      - ReleaseInProgress
      - DeleteInProgress
      - ReleaseFailed
      - DeleteFailed
    PhoneNumberType:
      type: string
      enum:
      - Local
      - TollFree
    PhoneNumberTypeList:
      type: array
      items:
        $ref: '#/components/schemas/PhoneNumberType'
    ProfileServiceMaxResults:
      type: integer
      minimum: 1
      maximum: 200
    RegistrationStatus:
      type: string
      enum:
      - Unregistered
      - Registered
      - Suspended
    ResultMax:
      type: integer
      minimum: 1
      maximum: 99
    RetentionDays:
      type: integer
      minimum: 1
      maximum: 5475
    RoomList:
      type: array
      items:
        $ref: '#/components/schemas/Room'
    RoomMembershipList:
      type: array
      items:
        $ref: '#/components/schemas/RoomMembership'
    RoomMembershipRole:
      type: string
      enum:
      - Administrator
      - Member
    SensitiveString:
      type: string
    SigninDelegateGroupList:
      type: array
      items:
        $ref: '#/components/schemas/SigninDelegateGroup'
    String:
      type: string
    TollFreePrefix:
      type: string
      pattern: ^8(00|33|44|55|66|77|88)$
      minLength: 3
      maxLength: 3
    UpdatePhoneNumberRequestItemList:
      type: array
      items:
        $ref: '#/components/schemas/UpdatePhoneNumberRequestItem'
    UpdateUserRequestItemList:
      type: array
      items:
        $ref: '#/components/schemas/UpdateUserRequestItem'
    UserEmailList:
      type: array
      items:
        $ref: '#/components/schemas/EmailAddress'
    UserErrorList:
      type: array
      items:
        $ref: '#/components/schemas/UserError'
    UserIdList:
      type: array
      items:
        $ref: '#/components/schemas/NonEmptyString'
    UserList:
      type: array
      items:
        $ref: '#/components/schemas/User'
    UserType:
      type: string
      enum:
      - PrivateUser
      - SharedDevice
