openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: chime_sdk_voice
  x-aws-serviceName: chimesdkvoice
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2022-08-03'
  title: Amazon Chime SDK Voice
  description: |-
    The Amazon Chime SDK telephony APIs in this section enable developers to create PSTN calling solutions that use Amazon Chime SDK Voice Connectors, and Amazon Chime SDK SIP media applications. Developers can also order and manage phone numbers, create and manage Voice Connectors and SIP media applications, and run voice analytics.
servers:
- description: The Amazon Chime SDK Voice regional endpoint
  url: https://voice-chime.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AlexaSkillId:
      type: string
      pattern: ^amzn1\.application-oa2-client\.[0-9a-fA-F]{32}$
      minLength: 0
      maxLength: 64
    AlexaSkillIdList:
      type: array
      items:
        $ref: '#/components/schemas/AlexaSkillId'
    AlexaSkillStatus:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
    Alpha2CountryCode:
      type: string
      pattern: ^[A-Z]{2}$
    AreaCode:
      type: string
      pattern: ^$|^[0-9]{3,3}$
    Arn:
      type: string
      pattern: ^arn[\/\:\-\_\.a-zA-Z0-9]+$
      minLength: 1
      maxLength: 1024
    Boolean:
      type: boolean
    CallLegType:
      type: string
      enum:
      - Caller
      - Callee
    CallingName:
      type: string
      pattern: ^$|^[a-zA-Z0-9 ]{2,15}$
    CallingNameStatus:
      type: string
      enum:
      - Unassigned
      - UpdateInProgress
      - UpdateSucceeded
      - UpdateFailed
    CallingRegion:
      type: string
    CallingRegionList:
      type: array
      items:
        $ref: '#/components/schemas/CallingRegion'
    CandidateAddressList:
      type: array
      items:
        $ref: '#/components/schemas/CandidateAddress'
    Capability:
      type: string
      enum:
      - Voice
      - SMS
    CapabilityList:
      type: array
      items:
        $ref: '#/components/schemas/Capability'
    ClientRequestId:
      type: string
      pattern: ^[-_a-zA-Z0-9]*${2,64}$
    ConfidenceScore:
      type: number
      format: float
      default: 0
      minimum: 0
      maximum: 1
    ContactCenterSystemType:
      type: string
      enum:
      - GENESYS_ENGAGE_ON_PREMISES
      - AVAYA_AURA_CALL_CENTER_ELITE
      - AVAYA_AURA_CONTACT_CENTER
      - CISCO_UNIFIED_CONTACT_CENTER_ENTERPRISE
    ContactCenterSystemTypeList:
      type: array
      items:
        $ref: '#/components/schemas/ContactCenterSystemType'
    Country:
      type: string
      pattern: ^$|^[A-Z]{2,2}$
    CountryList:
      type: array
      items:
        $ref: '#/components/schemas/Country'
    CpsLimit:
      type: integer
      minimum: 1
    CredentialList:
      type: array
      items:
        $ref: '#/components/schemas/Credential'
    DNISEmergencyCallingConfigurationList:
      type: array
      items:
        $ref: '#/components/schemas/DNISEmergencyCallingConfiguration'
    DataRetentionInHours:
      type: integer
      minimum: 0
    E164PhoneNumber:
      type: string
      pattern: ^\+?[1-9]\d{1,14}$
    E164PhoneNumberList:
      type: array
      items:
        $ref: '#/components/schemas/E164PhoneNumber'
    ErrorCode:
      type: string
      enum:
      - BadRequest
      - Conflict
      - Forbidden
      - NotFound
      - PreconditionFailed
      - ResourceLimitExceeded
      - ServiceFailure
      - AccessDenied
      - ServiceUnavailable
      - Throttled
      - Throttling
      - Unauthorized
      - Unprocessable
      - VoiceConnectorGroupAssociationsExist
      - PhoneNumberAssociationsExist
      - Gone
    FunctionArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*)?:lambda:[a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1}:\d{12}:function:[a-zA-Z0-9-_]+(:(\$LATEST|[a-zA-Z0-9-_]+))?$
      minLength: 0
      maxLength: 10000
    GeoMatchLevel:
      type: string
      enum:
      - Country
      - AreaCode
    GuidString:
      type: string
      pattern: ^[a-fA-F0-9]{8}(?:-[a-fA-F0-9]{4}){3}-[a-fA-F0-9]{12}$
    Integer:
      type: integer
    Iso8601Timestamp:
      type: string
      format: date-time
    LanguageCode:
      type: string
      enum:
      - en-US
    NextTokenString:
      type: string
      minLength: 0
      maxLength: 65535
    NonEmptyString:
      type: string
      pattern: \S
    NonEmptyString128:
      type: string
      pattern: \S
      minLength: 1
      maxLength: 128
    NonEmptyString256:
      type: string
      pattern: \S
      minLength: 1
      maxLength: 256
    NonEmptyStringList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    NotificationTarget:
      type: string
      enum:
      - EventBridge
      - SNS
      - SQS
    NullableBoolean:
      type: boolean
    NumberSelectionBehavior:
      type: string
      enum:
      - PreferSticky
      - AvoidSticky
    OrderedPhoneNumberList:
      type: array
      items:
        $ref: '#/components/schemas/OrderedPhoneNumber'
    OrderedPhoneNumberStatus:
      type: string
      enum:
      - Processing
      - Acquired
      - Failed
    OriginationRouteList:
      type: array
      items:
        $ref: '#/components/schemas/OriginationRoute'
    OriginationRoutePriority:
      type: integer
      minimum: 1
      maximum: 100
    OriginationRouteProtocol:
      type: string
      enum:
      - TCP
      - UDP
    OriginationRouteWeight:
      type: integer
      minimum: 1
      maximum: 100
    ParticipantPhoneNumberList:
      type: array
      items:
        $ref: '#/components/schemas/E164PhoneNumber'
    Participants:
      type: array
      items:
        $ref: '#/components/schemas/Participant'
    PhoneNumberAssociationList:
      type: array
      items:
        $ref: '#/components/schemas/PhoneNumberAssociation'
    PhoneNumberAssociationName:
      type: string
      enum:
      - VoiceConnectorId
      - VoiceConnectorGroupId
      - SipRuleId
    PhoneNumberCountriesList:
      type: array
      items:
        $ref: '#/components/schemas/PhoneNumberCountry'
    PhoneNumberErrorList:
      type: array
      items:
        $ref: '#/components/schemas/PhoneNumberError'
    PhoneNumberList:
      type: array
      items:
        $ref: '#/components/schemas/PhoneNumber'
    PhoneNumberMaxResults:
      type: integer
      minimum: 1
      maximum: 500
    PhoneNumberName:
      type: string
      pattern: ^$|^[a-zA-Z0-9\,\.\_\-]+(\s+[a-zA-Z0-9\,\.\_\-]+)*$
      minLength: 0
      maxLength: 256
    PhoneNumberOrderList:
      type: array
      items:
        $ref: '#/components/schemas/PhoneNumberOrder'
    PhoneNumberOrderStatus:
      type: string
      enum:
      - Processing
      - Successful
      - Failed
      - Partial
      - PendingDocuments
      - Submitted
      - FOC
      - ChangeRequested
      - Exception
      - CancelRequested
      - Cancelled
    PhoneNumberOrderType:
      type: string
      enum:
      - New
      - Porting
    PhoneNumberProductType:
      type: string
      enum:
      - VoiceConnector
      - SipMediaApplicationDialIn
    PhoneNumberStatus:
      type: string
      enum:
      - Cancelled
      - PortinCancelRequested
      - PortinInProgress
      - AcquireInProgress
      - AcquireFailed
      - Unassigned
      - Assigned
      - ReleaseInProgress
      - DeleteInProgress
      - ReleaseFailed
      - DeleteFailed
    PhoneNumberType:
      type: string
      enum:
      - Local
      - TollFree
    PhoneNumberTypeList:
      type: array
      items:
        $ref: '#/components/schemas/PhoneNumberType'
    Port:
      type: integer
      minimum: 0
      maximum: 65535
    PositiveInteger:
      type: integer
      minimum: 1
    ProxySessionNameString:
      type: string
      pattern: ^$|^[a-zA-Z0-9 ]{0,30}$
    ProxySessionStatus:
      type: string
      enum:
      - Open
      - InProgress
      - Closed
    ProxySessions:
      type: array
      items:
        $ref: '#/components/schemas/ProxySession'
    ResultMax:
      type: integer
      minimum: 1
      maximum: 100
    SMACreateCallArgumentsMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/SensitiveString'
    SMAUpdateCallArgumentsMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/SensitiveString'
    SensitiveNonEmptyString:
      type: string
      pattern: \S
    SensitiveString:
      type: string
    SensitiveStringList:
      type: array
      items:
        $ref: '#/components/schemas/SensitiveString'
    SessionBorderControllerType:
      type: string
      enum:
      - RIBBON_SBC
      - ORACLE_ACME_PACKET_SBC
      - AVAYA_SBCE
      - CISCO_UNIFIED_BORDER_ELEMENT
      - AUDIOCODES_MEDIANT_SBC
    SessionBorderControllerTypeList:
      type: array
      items:
        $ref: '#/components/schemas/SessionBorderControllerType'
    SipApplicationPriority:
      type: integer
      minimum: 1
    SipHeadersMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/SensitiveString'
    SipMediaApplicationEndpointList:
      type: array
      items:
        $ref: '#/components/schemas/SipMediaApplicationEndpoint'
    SipMediaApplicationList:
      type: array
      items:
        $ref: '#/components/schemas/SipMediaApplication'
    SipMediaApplicationName:
      type: string
      pattern: ^[a-zA-Z0-9 _.-]+$
      minLength: 1
      maxLength: 256
    SipRuleList:
      type: array
      items:
        $ref: '#/components/schemas/SipRule'
    SipRuleName:
      type: string
      pattern: ^[a-zA-Z0-9 _.-]+$
      minLength: 1
      maxLength: 256
    SipRuleTargetApplicationList:
      type: array
      items:
        $ref: '#/components/schemas/SipRuleTargetApplication'
    SipRuleTriggerType:
      type: string
      enum:
      - ToPhoneNumber
      - RequestUriHostname
    SpeakerSearchResultList:
      type: array
      items:
        $ref: '#/components/schemas/SpeakerSearchResult'
    StreamingNotificationTargetList:
      type: array
      items:
        $ref: '#/components/schemas/StreamingNotificationTarget'
    String:
      type: string
    String128:
      type: string
      minLength: 0
      maxLength: 128
    StringList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagList:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TollFreePrefix:
      type: string
      pattern: ^8(00|33|44|55|66|77|88)$
      minLength: 3
      maxLength: 3
    UpdatePhoneNumberRequestItemList:
      type: array
      items:
        $ref: '#/components/schemas/UpdatePhoneNumberRequestItem'
    ValidationResult:
      type: integer
      default: 0
      minimum: 0
      maximum: 2
    VoiceConnectorAwsRegion:
      type: string
      enum:
      - us-east-1
      - us-west-2
      - ca-central-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - ap-northeast-2
      - ap-northeast-1
      - ap-southeast-1
      - ap-southeast-2
    VoiceConnectorAwsRegionList:
      type: array
      items:
        $ref: '#/components/schemas/VoiceConnectorAwsRegion'
    VoiceConnectorGroupList:
      type: array
      items:
        $ref: '#/components/schemas/VoiceConnectorGroup'
    VoiceConnectorGroupName:
      type: string
      pattern: ^[a-zA-Z0-9 _.-]+$
      minLength: 1
      maxLength: 256
    VoiceConnectorIntegrationType:
      type: string
      enum:
      - CONNECT_CALL_TRANSFER_CONNECTOR
      - CONNECT_ANALYTICS_CONNECTOR
    VoiceConnectorItemList:
      type: array
      items:
        $ref: '#/components/schemas/VoiceConnectorItem'
    VoiceConnectorItemPriority:
      type: integer
      minimum: 1
      maximum: 99
    VoiceConnectorList:
      type: array
      items:
        $ref: '#/components/schemas/VoiceConnector'
    VoiceConnectorName:
      type: string
      pattern: ^[a-zA-Z0-9 _.-]+$
      minLength: 1
      maxLength: 256
    VoiceProfileDomainDescription:
      type: string
      minLength: 0
      maxLength: 1024
    VoiceProfileDomainName:
      type: string
      pattern: ^[a-zA-Z0-9 _.-]+$
      minLength: 1
      maxLength: 256
    VoiceProfileDomainSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/VoiceProfileDomainSummary'
    VoiceProfileSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/VoiceProfileSummary'
