openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: chime_sdk_media_pipelines
  x-aws-serviceName: chimesdkmediapipelines
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2021-07-15'
  title: Amazon Chime SDK Media Pipelines
  description: |-
    The Amazon Chime SDK media pipeline APIs in this section allow software developers to create Amazon Chime SDK media pipelines that capture, concatenate, or stream your Amazon Chime SDK meetings. For more information about media pipelines, see [Amazon Chime SDK media pipelines](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_Operations_Amazon_Chime_SDK_Media_Pipelines.html).
servers:
- description: The Amazon Chime SDK Media Pipelines regional endpoint
  url: https://media-pipelines-chime.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AmazonResourceName:
      type: string
      pattern: ^arn[\/\:\-\_\.a-zA-Z0-9]+$
      minLength: 1
      maxLength: 1011
    Arn:
      type: string
      pattern: ^arn[\/\:\-\_\.a-zA-Z0-9]+$
      minLength: 1
      maxLength: 1024
    AudioSampleRateOption:
      type: string
      pattern: ^44100|48000$
    AwsRegion:
      type: string
      pattern: ^([a-z]+-){2,}\d+$
      minLength: 1
      maxLength: 32
    Boolean:
      type: boolean
      default: false
    BorderThickness:
      type: integer
      minimum: 1
      maximum: 20
    CategoryName:
      type: string
      pattern: ^[0-9a-zA-Z._-]+$
      minLength: 1
      maxLength: 200
    ChannelId:
      type: integer
      default: 0
      minimum: 0
      maximum: 1
    ClientRequestToken:
      type: string
      pattern: ^[-_a-zA-Z0-9]*$
      minLength: 2
      maxLength: 64
    CornerRadius:
      type: integer
      minimum: 1
      maximum: 20
    DataRetentionChangeInHours:
      type: integer
      minimum: 1
    DataRetentionInHours:
      type: integer
      minimum: 0
    ExternalUserIdType:
      type: string
      minLength: 2
      maxLength: 64
    FragmentNumberString:
      type: string
      pattern: ^[0-9]+$
      minLength: 1
      maxLength: 128
    GuidString:
      type: string
      pattern: ^[a-fA-F0-9]{8}(?:-[a-fA-F0-9]{4}){3}-[a-fA-F0-9]{12}$
      minLength: 36
      maxLength: 36
    Keyword:
      type: string
      pattern: ^[\s0-9a-zA-Z'-]+$
      minLength: 1
      maxLength: 100
    KinesisVideoStreamArn:
      type: string
      pattern: ^arn:[a-z\d-]+:kinesisvideo:[a-z0-9-]+:[0-9]+:[a-z]+/[a-zA-Z0-9_.-]+/[0-9]+$
      minLength: 1
      maxLength: 1024
    KinesisVideoStreamPoolId:
      type: string
      pattern: ^[0-9a-zA-Z._-]+$
      minLength: 1
      maxLength: 256
    KinesisVideoStreamPoolName:
      type: string
      pattern: ^[0-9a-zA-Z._-]+$
      minLength: 1
      maxLength: 128
    KinesisVideoStreamPoolSize:
      type: integer
      minimum: 0
    LanguageOptions:
      type: string
      pattern: ^[a-zA-Z-,]+$
      minLength: 1
      maxLength: 200
    MediaInsightsPipelineConfigurationNameString:
      type: string
      pattern: ^[0-9a-zA-Z._-]+$
      minLength: 2
      maxLength: 64
    MediaSampleRateHertz:
      type: integer
      minimum: 8000
      maximum: 48000
    ModelName:
      type: string
      pattern: ^[0-9a-zA-Z._-]+$
      minLength: 1
      maxLength: 200
    NonEmptyString:
      type: string
      pattern: \S
      minLength: 0
      maxLength: 1024
    NumberOfChannels:
      type: integer
      minimum: 1
      maximum: 2
    PiiEntityTypes:
      type: string
      pattern: ^[A-Z_, ]+$
      minLength: 1
      maxLength: 300
    ReservedStreamCapacity:
      type: integer
      minimum: 1
      maximum: 10
    ResultMax:
      type: integer
      minimum: 1
      maximum: 100
    RuleName:
      type: string
      pattern: ^[0-9a-zA-Z._-]+$
      minLength: 2
      maxLength: 64
    SensitiveString:
      type: string
      minLength: 1
      maxLength: 1024
    SentimentTimePeriodInSeconds:
      type: integer
      minimum: 60
      maximum: 1800
    String:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 4096
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TileAspectRatio:
      type: string
      pattern: ^\d{1,2}\/\d{1,2}$
    TileCount:
      type: integer
      minimum: 1
      maximum: 10
    VocabularyFilterName:
      type: string
      pattern: ^[0-9a-zA-Z._-]+$
      minLength: 1
      maxLength: 200
    VocabularyFilterNames:
      type: string
      pattern: ^[a-zA-Z0-9,-._]+$
      minLength: 1
      maxLength: 3000
    VocabularyName:
      type: string
      pattern: ^[0-9a-zA-Z._-]+$
      minLength: 1
      maxLength: 200
    VocabularyNames:
      type: string
      pattern: ^[a-zA-Z0-9,-._]+$
      minLength: 1
      maxLength: 3000
