openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: chime_sdk_media_pipelines
  x-aws-serviceName: chimesdkmediapipelines
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2021-07-15'
  title: Amazon Chime SDK Media Pipelines
  description: |-
    The Amazon Chime SDK media pipeline APIs in this section allow software developers to create Amazon Chime SDK media pipelines that capture, concatenate, or stream your Amazon Chime SDK meetings. For more information about media pipelines, see [Amazon Chime SDK media pipelines](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_Operations_Amazon_Chime_SDK_Media_Pipelines.html).
servers:
- description: The Amazon Chime SDK Media Pipelines regional endpoint
  url: https://media-pipelines-chime.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ActiveSpeakerPosition:
      type: string
      enum:
      - TopLeft
      - TopRight
      - BottomLeft
      - BottomRight
    AmazonResourceName:
      type: string
      pattern: ^arn[\/\:\-\_\.a-zA-Z0-9]+$
      minLength: 1
      maxLength: 1011
    Arn:
      type: string
      pattern: ^arn[\/\:\-\_\.a-zA-Z0-9]+$
      minLength: 1
      maxLength: 1024
    ArtifactsConcatenationState:
      type: string
      enum:
      - Enabled
      - Disabled
    ArtifactsState:
      type: string
      enum:
      - Enabled
      - Disabled
    AttendeeIdList:
      type: array
      items:
        $ref: '#/components/schemas/GuidString'
    AudioArtifactsConcatenationState:
      type: string
      enum:
      - Enabled
    AudioChannelsOption:
      type: string
      enum:
      - Stereo
      - Mono
    AudioMuxType:
      type: string
      enum:
      - AudioOnly
      - AudioWithActiveSpeakerVideo
      - AudioWithCompositedVideo
    AudioSampleRateOption:
      type: string
      pattern: ^44100|48000$
    AwsRegion:
      type: string
      pattern: ^([a-z]+-){2,}\d+$
      minLength: 1
      maxLength: 32
    Boolean:
      type: boolean
      default: false
    BorderColor:
      type: string
      enum:
      - Black
      - Blue
      - Red
      - Green
      - White
      - Yellow
    BorderThickness:
      type: integer
      minimum: 1
      maximum: 20
    CallAnalyticsLanguageCode:
      type: string
      enum:
      - en-US
      - en-GB
      - es-US
      - fr-CA
      - fr-FR
      - en-AU
      - it-IT
      - de-DE
      - pt-BR
    CanvasOrientation:
      type: string
      enum:
      - Landscape
      - Portrait
    CategoryName:
      type: string
      pattern: ^[0-9a-zA-Z._-]+$
      minLength: 1
      maxLength: 200
    CategoryNameList:
      type: array
      items:
        $ref: '#/components/schemas/CategoryName'
    ChannelDefinitions:
      type: array
      items:
        $ref: '#/components/schemas/ChannelDefinition'
    ChannelId:
      type: integer
      default: 0
      minimum: 0
      maximum: 1
    ClientRequestToken:
      type: string
      pattern: ^[-_a-zA-Z0-9]*$
      minLength: 2
      maxLength: 64
    ConcatenationSinkList:
      type: array
      items:
        $ref: '#/components/schemas/ConcatenationSink'
    ConcatenationSinkType:
      type: string
      enum:
      - S3Bucket
    ConcatenationSourceList:
      type: array
      items:
        $ref: '#/components/schemas/ConcatenationSource'
    ConcatenationSourceType:
      type: string
      enum:
      - MediaCapturePipeline
    ContentMuxType:
      type: string
      enum:
      - ContentOnly
    ContentRedactionOutput:
      type: string
      enum:
      - redacted
      - redacted_and_unredacted
    ContentShareLayoutOption:
      type: string
      enum:
      - PresenterOnly
      - Horizontal
      - Vertical
      - ActiveSpeakerOnly
    ContentType:
      type: string
      enum:
      - PII
    CornerRadius:
      type: integer
      minimum: 1
      maximum: 20
    DataRetentionChangeInHours:
      type: integer
      minimum: 1
    DataRetentionInHours:
      type: integer
      minimum: 0
    ErrorCode:
      type: string
      enum:
      - BadRequest
      - Forbidden
      - NotFound
      - ResourceLimitExceeded
      - ServiceFailure
      - ServiceUnavailable
      - Throttling
    ExternalUserIdList:
      type: array
      items:
        $ref: '#/components/schemas/ExternalUserIdType'
    ExternalUserIdType:
      type: string
      minLength: 2
      maxLength: 64
    FragmentNumberString:
      type: string
      pattern: ^[0-9]+$
      minLength: 1
      maxLength: 128
    FragmentSelectorType:
      type: string
      enum:
      - ProducerTimestamp
      - ServerTimestamp
    GuidString:
      type: string
      pattern: ^[a-fA-F0-9]{8}(?:-[a-fA-F0-9]{4}){3}-[a-fA-F0-9]{12}$
      minLength: 36
      maxLength: 36
    HighlightColor:
      type: string
      enum:
      - Black
      - Blue
      - Red
      - Green
      - White
      - Yellow
    HorizontalTilePosition:
      type: string
      enum:
      - Top
      - Bottom
    Iso8601Timestamp:
      type: string
      format: date-time
    Keyword:
      type: string
      pattern: ^[\s0-9a-zA-Z'-]+$
      minLength: 1
      maxLength: 100
    KeywordMatchWordList:
      type: array
      items:
        $ref: '#/components/schemas/Keyword'
    KinesisVideoStreamArn:
      type: string
      pattern: ^arn:[a-z\d-]+:kinesisvideo:[a-z0-9-]+:[0-9]+:[a-z]+/[a-zA-Z0-9_.-]+/[0-9]+$
      minLength: 1
      maxLength: 1024
    KinesisVideoStreamPoolId:
      type: string
      pattern: ^[0-9a-zA-Z._-]+$
      minLength: 1
      maxLength: 256
    KinesisVideoStreamPoolName:
      type: string
      pattern: ^[0-9a-zA-Z._-]+$
      minLength: 1
      maxLength: 128
    KinesisVideoStreamPoolSize:
      type: integer
      minimum: 0
    KinesisVideoStreamPoolStatus:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - UPDATING
      - DELETING
      - FAILED
    KinesisVideoStreamPoolSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/KinesisVideoStreamPoolSummary'
    LanguageOptions:
      type: string
      pattern: ^[a-zA-Z-,]+$
      minLength: 1
      maxLength: 200
    LayoutOption:
      type: string
      enum:
      - GridView
    LiveConnectorMuxType:
      type: string
      enum:
      - AudioWithCompositedVideo
      - AudioWithActiveSpeakerVideo
    LiveConnectorSinkList:
      type: array
      items:
        $ref: '#/components/schemas/LiveConnectorSinkConfiguration'
    LiveConnectorSinkType:
      type: string
      enum:
      - RTMP
    LiveConnectorSourceList:
      type: array
      items:
        $ref: '#/components/schemas/LiveConnectorSourceConfiguration'
    LiveConnectorSourceType:
      type: string
      enum:
      - ChimeSdkMeeting
    MediaCapturePipelineSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/MediaCapturePipelineSummary'
    MediaEncoding:
      type: string
      enum:
      - pcm
    MediaInsightsPipelineConfigurationElementType:
      type: string
      enum:
      - AmazonTranscribeCallAnalyticsProcessor
      - VoiceAnalyticsProcessor
      - AmazonTranscribeProcessor
      - KinesisDataStreamSink
      - LambdaFunctionSink
      - SqsQueueSink
      - SnsTopicSink
      - S3RecordingSink
      - VoiceEnhancementSink
    MediaInsightsPipelineConfigurationElements:
      type: array
      items:
        $ref: '#/components/schemas/MediaInsightsPipelineConfigurationElement'
    MediaInsightsPipelineConfigurationNameString:
      type: string
      pattern: ^[0-9a-zA-Z._-]+$
      minLength: 2
      maxLength: 64
    MediaInsightsPipelineConfigurationSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/MediaInsightsPipelineConfigurationSummary'
    MediaInsightsPipelineElementStatuses:
      type: array
      items:
        $ref: '#/components/schemas/MediaInsightsPipelineElementStatus'
    MediaInsightsRuntimeMetadata:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    MediaPipelineElementStatus:
      type: string
      enum:
      - NotStarted
      - NotSupported
      - Initializing
      - InProgress
      - Failed
      - Stopping
      - Stopped
      - Paused
    MediaPipelineList:
      type: array
      items:
        $ref: '#/components/schemas/MediaPipelineSummary'
    MediaPipelineSinkType:
      type: string
      enum:
      - S3Bucket
    MediaPipelineSourceType:
      type: string
      enum:
      - ChimeSdkMeeting
    MediaPipelineStatus:
      type: string
      enum:
      - Initializing
      - InProgress
      - Failed
      - Stopping
      - Stopped
      - Paused
      - NotStarted
    MediaPipelineStatusUpdate:
      type: string
      enum:
      - Pause
      - Resume
    MediaPipelineTaskStatus:
      type: string
      enum:
      - NotStarted
      - Initializing
      - InProgress
      - Failed
      - Stopping
      - Stopped
    MediaSampleRateHertz:
      type: integer
      minimum: 8000
      maximum: 48000
    MediaStreamPipelineSinkType:
      type: string
      enum:
      - KinesisVideoStreamPool
    MediaStreamSinkList:
      type: array
      items:
        $ref: '#/components/schemas/MediaStreamSink'
    MediaStreamSourceList:
      type: array
      items:
        $ref: '#/components/schemas/MediaStreamSource'
    MediaStreamType:
      type: string
      enum:
      - MixedAudio
      - IndividualAudio
    ModelName:
      type: string
      pattern: ^[0-9a-zA-Z._-]+$
      minLength: 1
      maxLength: 200
    NonEmptyString:
      type: string
      pattern: \S
      minLength: 0
      maxLength: 1024
    NumberOfChannels:
      type: integer
      minimum: 1
      maximum: 2
    PartialResultsStability:
      type: string
      enum:
      - high
      - medium
      - low
    ParticipantRole:
      type: string
      enum:
      - AGENT
      - CUSTOMER
    PiiEntityTypes:
      type: string
      pattern: ^[A-Z_, ]+$
      minLength: 1
      maxLength: 300
    PresenterPosition:
      type: string
      enum:
      - TopLeft
      - TopRight
      - BottomLeft
      - BottomRight
    RealTimeAlertRuleList:
      type: array
      items:
        $ref: '#/components/schemas/RealTimeAlertRule'
    RealTimeAlertRuleType:
      type: string
      enum:
      - KeywordMatch
      - Sentiment
      - IssueDetection
    RecordingFileFormat:
      type: string
      enum:
      - Wav
      - Opus
    RecordingStreamList:
      type: array
      items:
        $ref: '#/components/schemas/RecordingStreamConfiguration'
    ReservedStreamCapacity:
      type: integer
      minimum: 1
      maximum: 10
    ResolutionOption:
      type: string
      enum:
      - HD
      - FHD
    ResultMax:
      type: integer
      minimum: 1
      maximum: 100
    RuleName:
      type: string
      pattern: ^[0-9a-zA-Z._-]+$
      minLength: 2
      maxLength: 64
    SensitiveString:
      type: string
      minLength: 1
      maxLength: 1024
    SentimentTimePeriodInSeconds:
      type: integer
      minimum: 60
      maximum: 1800
    SentimentType:
      type: string
      enum:
      - NEGATIVE
    Streams:
      type: array
      items:
        $ref: '#/components/schemas/StreamConfiguration'
    String:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 4096
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagList:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TileAspectRatio:
      type: string
      pattern: ^\d{1,2}\/\d{1,2}$
    TileCount:
      type: integer
      minimum: 1
      maximum: 10
    TileOrder:
      type: string
      enum:
      - JoinSequence
      - SpeakerSequence
    Timestamp:
      type: string
      format: date-time
    VerticalTilePosition:
      type: string
      enum:
      - Left
      - Right
    VideoMuxType:
      type: string
      enum:
      - VideoOnly
    VocabularyFilterMethod:
      type: string
      enum:
      - remove
      - mask
      - tag
    VocabularyFilterName:
      type: string
      pattern: ^[0-9a-zA-Z._-]+$
      minLength: 1
      maxLength: 200
    VocabularyFilterNames:
      type: string
      pattern: ^[a-zA-Z0-9,-._]+$
      minLength: 1
      maxLength: 3000
    VocabularyName:
      type: string
      pattern: ^[0-9a-zA-Z._-]+$
      minLength: 1
      maxLength: 200
    VocabularyNames:
      type: string
      pattern: ^[a-zA-Z0-9,-._]+$
      minLength: 1
      maxLength: 3000
    VoiceAnalyticsConfigurationStatus:
      type: string
      enum:
      - Enabled
      - Disabled
    VoiceAnalyticsLanguageCode:
      type: string
      enum:
      - en-US
