openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: chime_sdk_messaging
  x-aws-serviceName: chimesdkmessaging
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2021-05-15'
  title: Amazon Chime SDK Messaging
  description: |-
    The Amazon Chime SDK messaging APIs in this section allow software developers to send and receive messages in custom messaging applications. These APIs depend on the frameworks provided by the Amazon Chime SDK identity APIs. For more information about the messaging APIs, see [Amazon Chime SDK messaging](https://docs.aws.amazon.com/chime/latest/APIReference/API_Operations_Amazon_Chime_SDK_Messaging.html).
servers:
- description: The Amazon Chime SDK Messaging regional endpoint
  url: https://messaging-chime.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    CallbackIdType:
      type: string
      minLength: 32
      maxLength: 64
    ChannelFlowExecutionOrder:
      type: integer
      minimum: 1
      maximum: 3
    ChannelId:
      type: string
      pattern: ^[A-Za-z0-9]([A-Za-z0-9\:\-\_\.\@]{0,62}[A-Za-z0-9])?$
      minLength: 1
      maxLength: 64
    ChimeArn:
      type: string
      pattern: ^arn:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[^/].{0,1023}$
      minLength: 5
      maxLength: 1600
    ClientRequestToken:
      type: string
      pattern: ^[-_a-zA-Z0-9]*$
      minLength: 2
      maxLength: 64
    Content:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 4096
    ContentType:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 45
    ExpirationDays:
      type: integer
      minimum: 1
      maximum: 5475
    FilterRule:
      type: string
      pattern: ^[\s\S]*$
      minLength: 1
    LambdaFunctionArn:
      type: string
      pattern: ^arn:aws:lambda:[a-z]{2}-[a-z]+-\d{1}:\d{12}:function:[a-zA-Z0-9\-_\.]+(:(\$LATEST|[a-zA-Z0-9\-_]+))?$
      minLength: 15
      maxLength: 2048
    MaxResults:
      type: integer
      minimum: 1
      maximum: 50
    MaximumSubChannels:
      type: integer
      minimum: 2
    MembershipCount:
      type: integer
    MessageAttributeName:
      type: string
      pattern: ^[\s\S]*$
      minLength: 1
      maxLength: 64
    MessageAttributeStringValue:
      type: string
      pattern: ^[\s\S]*$
      minLength: 1
      maxLength: 512
    MessageId:
      type: string
      pattern: ^[-_a-zA-Z0-9]*$
      minLength: 1
      maxLength: 128
    Metadata:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 1024
    MinimumMembershipPercentage:
      type: integer
      minimum: 1
      maximum: 40
    NextToken:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 2048
    NonEmptyContent:
      type: string
      pattern: ^[\s\S]*$
      minLength: 1
    NonEmptyResourceName:
      type: string
      pattern: ^[\u0009\u000A\u000D\u0020-\u007E\u0085\u00A0-\uD7FF\uE000-\uFFFD\u10000-\u10FFFF]*$
      minLength: 1
      maxLength: 256
    NonNullableBoolean:
      type: boolean
      default: false
    PushNotificationBody:
      type: string
      pattern: ^[\s\S]*$
      minLength: 1
      maxLength: 150
    PushNotificationTitle:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 50
    ResourceName:
      type: string
      pattern: ^[\u0009\u000A\u000D\u0020-\u007E\u0085\u00A0-\uD7FF\uE000-\uFFFD\u10000-\u10FFFF]*$
      minLength: 0
      maxLength: 256
    SearchFieldValue:
      type: string
      pattern: ^[\s\S]*$
      minLength: 1
      maxLength: 512
    StatusDetail:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 256
    String:
      type: string
    SubChannelId:
      type: string
      pattern: ^[-_a-zA-Z0-9]*$
      minLength: 1
      maxLength: 128
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 1
      maxLength: 256
    TargetMembershipsPerSubChannel:
      type: integer
      minimum: 2
    UrlType:
      type: string
      minLength: 0
      maxLength: 4096
