openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: chime_sdk_voice
  x-aws-serviceName: chimesdkvoice
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2022-08-03'
  title: Amazon Chime SDK Voice
  description: |-
    The Amazon Chime SDK telephony APIs in this section enable developers to create PSTN calling solutions that use Amazon Chime SDK Voice Connectors, and Amazon Chime SDK SIP media applications. Developers can also order and manage phone numbers, create and manage Voice Connectors and SIP media applications, and run voice analytics.
servers:
- description: The Amazon Chime SDK Voice regional endpoint
  url: https://voice-chime.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AlexaSkillId:
      type: string
      pattern: ^amzn1\.application-oa2-client\.[0-9a-fA-F]{32}$
      minLength: 0
      maxLength: 64
    Alpha2CountryCode:
      type: string
      pattern: ^[A-Z]{2}$
    AreaCode:
      type: string
      pattern: ^$|^[0-9]{3,3}$
    Arn:
      type: string
      pattern: ^arn[\/\:\-\_\.a-zA-Z0-9]+$
      minLength: 1
      maxLength: 1024
    Boolean:
      type: boolean
    CallingName:
      type: string
      pattern: ^$|^[a-zA-Z0-9 ]{2,15}$
    CallingRegion:
      type: string
    ClientRequestId:
      type: string
      pattern: ^[-_a-zA-Z0-9]*${2,64}$
    Country:
      type: string
      pattern: ^$|^[A-Z]{2,2}$
    CpsLimit:
      type: integer
      minimum: 1
    DataRetentionInHours:
      type: integer
      minimum: 0
    E164PhoneNumber:
      type: string
      pattern: ^\+?[1-9]\d{1,14}$
    FunctionArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*)?:lambda:[a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1}:\d{12}:function:[a-zA-Z0-9-_]+(:(\$LATEST|[a-zA-Z0-9-_]+))?$
      minLength: 0
      maxLength: 10000
    GuidString:
      type: string
      pattern: ^[a-fA-F0-9]{8}(?:-[a-fA-F0-9]{4}){3}-[a-fA-F0-9]{12}$
    Integer:
      type: integer
    NextTokenString:
      type: string
      minLength: 0
      maxLength: 65535
    NonEmptyString:
      type: string
      pattern: \S
    NonEmptyString128:
      type: string
      pattern: \S
      minLength: 1
      maxLength: 128
    NonEmptyString256:
      type: string
      pattern: \S
      minLength: 1
      maxLength: 256
    NullableBoolean:
      type: boolean
    OriginationRoutePriority:
      type: integer
      minimum: 1
      maximum: 100
    OriginationRouteWeight:
      type: integer
      minimum: 1
      maximum: 100
    PhoneNumberMaxResults:
      type: integer
      minimum: 1
      maximum: 500
    PhoneNumberName:
      type: string
      pattern: ^$|^[a-zA-Z0-9\,\.\_\-]+(\s+[a-zA-Z0-9\,\.\_\-]+)*$
      minLength: 0
      maxLength: 256
    Port:
      type: integer
      minimum: 0
      maximum: 65535
    PositiveInteger:
      type: integer
      minimum: 1
    ProxySessionNameString:
      type: string
      pattern: ^$|^[a-zA-Z0-9 ]{0,30}$
    ResultMax:
      type: integer
      minimum: 1
      maximum: 100
    SensitiveNonEmptyString:
      type: string
      pattern: \S
    SensitiveString:
      type: string
    SipApplicationPriority:
      type: integer
      minimum: 1
    SipMediaApplicationName:
      type: string
      pattern: ^[a-zA-Z0-9 _.-]+$
      minLength: 1
      maxLength: 256
    SipRuleName:
      type: string
      pattern: ^[a-zA-Z0-9 _.-]+$
      minLength: 1
      maxLength: 256
    String:
      type: string
    String128:
      type: string
      minLength: 0
      maxLength: 128
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TollFreePrefix:
      type: string
      pattern: ^8(00|33|44|55|66|77|88)$
      minLength: 3
      maxLength: 3
    ValidationResult:
      type: integer
      default: 0
      minimum: 0
      maximum: 2
    VoiceConnectorGroupName:
      type: string
      pattern: ^[a-zA-Z0-9 _.-]+$
      minLength: 1
      maxLength: 256
    VoiceConnectorItemPriority:
      type: integer
      minimum: 1
      maximum: 99
    VoiceConnectorName:
      type: string
      pattern: ^[a-zA-Z0-9 _.-]+$
      minLength: 1
      maxLength: 256
    VoiceProfileDomainDescription:
      type: string
      minLength: 0
      maxLength: 1024
    VoiceProfileDomainName:
      type: string
      pattern: ^[a-zA-Z0-9 _.-]+$
      minLength: 1
      maxLength: 256
