openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: cleanroomsml
  x-aws-serviceName: cleanroomsml
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2023-09-06'
  title: AWS Clean Rooms ML
  description: |-
    Welcome to the _Amazon Web Services Clean Rooms ML API Reference_.

    Amazon Web Services Clean Rooms ML provides a privacy-enhancing method for two parties to identify similar users in their data without the need to share their data with each other. The first party brings the training data to Clean Rooms so that they can create and configure an audience model (lookalike model) and associate it with a collaboration. The second party then brings their seed data to Clean Rooms and generates an audience (lookalike segment) that resembles the training data.

    To learn more about Amazon Web Services Clean Rooms ML concepts, procedures, and best practices, see the [Clean Rooms User Guide](https://docs.aws.amazon.com/clean-rooms/latest/userguide/machine-learning.html).

    To learn more about SQL commands, functions, and conditions supported in Clean Rooms, see the [Clean Rooms SQL Reference](https://docs.aws.amazon.com/clean-rooms/latest/sql-reference/sql-reference.html).
servers:
- description: The AWS Clean Rooms ML regional endpoint
  url: https://cleanrooms-ml.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccountId:
      type: string
      pattern: ^[0-9]{12}$
      minLength: 12
      maxLength: 12
    AlgorithmImage:
      type: string
      pattern: ^.*$
      minLength: 1
      maxLength: 255
    AnalysisTemplateArn:
      type: string
      pattern: ^arn:aws[-a-z]*:cleanrooms:[\w]{2}-[\w]{4,9}-[\d]:[\d]{12}:membership/[\d\w-]+/analysistemplate/[\d\w-]+$
      minLength: 0
      maxLength: 200
    AudienceExportJobArn:
      type: string
      pattern: ^arn:aws[-a-z]*:cleanrooms-ml:[-a-z0-9]+:[0-9]{12}:audience-export-job/[-a-zA-Z0-9_/.]+$
      minLength: 20
      maxLength: 2048
    AudienceGenerationJobArn:
      type: string
      pattern: ^arn:aws[-a-z]*:cleanrooms-ml:[-a-z0-9]+:[0-9]{12}:audience-generation-job/[-a-zA-Z0-9_/.]+$
      minLength: 20
      maxLength: 2048
    AudienceModelArn:
      type: string
      pattern: ^arn:aws[-a-z]*:cleanrooms-ml:[-a-z0-9]+:[0-9]{12}:audience-model/[-a-zA-Z0-9_/.]+$
      minLength: 20
      maxLength: 2048
    AudienceSizeValue:
      type: integer
      minimum: 1
      maximum: 20000000
    ColumnName:
      type: string
      pattern: ^[a-zA-Z0-9_](([a-zA-Z0-9_ ]+-)*([a-zA-Z0-9_ ]+))?$
      minLength: 1
      maxLength: 128
    ConfiguredAudienceModelArn:
      type: string
      pattern: ^arn:aws[-a-z]*:cleanrooms-ml:[-a-z0-9]+:[0-9]{12}:configured-audience-model/[-a-zA-Z0-9_/.]+$
      minLength: 20
      maxLength: 2048
    ConfiguredModelAlgorithmArn:
      type: string
      pattern: ^arn:aws[-a-z]*:cleanrooms-ml:[-a-z0-9]+:[0-9]{12}:configured-model-algorithm/[-a-zA-Z0-9_/.]+$
      minLength: 20
      maxLength: 2048
    ConfiguredModelAlgorithmAssociationArn:
      type: string
      pattern: ^arn:aws[-a-z]*:cleanrooms-ml:[-a-z0-9]+:[0-9]{12}:(membership/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/)?configured-model-algorithm-association/[-a-zA-Z0-9_/.]+$
      minLength: 20
      maxLength: 2048
    ContainerArgument:
      type: string
      pattern: ^.*$
      minLength: 1
      maxLength: 256
    ContainerEntrypointString:
      type: string
      pattern: ^.*$
      minLength: 1
      maxLength: 256
    GlueDatabaseName:
      type: string
      pattern: ^[a-zA-Z0-9_](([a-zA-Z0-9_]+-)*([a-zA-Z0-9_]+))?$
      minLength: 1
      maxLength: 128
    GlueTableName:
      type: string
      pattern: ^[a-zA-Z0-9_](([a-zA-Z0-9_ ]+-)*([a-zA-Z0-9_ ]+))?$
      minLength: 1
      maxLength: 128
    Hash:
      type: string
      pattern: ^[0-9a-f]+$
      minLength: 64
      maxLength: 128
    IamRoleArn:
      type: string
      pattern: ^arn:aws[-a-z]*:iam::[0-9]{12}:role/.+$
      minLength: 20
      maxLength: 2048
    KmsKeyArn:
      type: string
      pattern: ^arn:aws[-a-z]*:kms:[-a-z0-9]+:[0-9]{12}:key/.+$
      minLength: 20
      maxLength: 2048
    MLInputChannelArn:
      type: string
      pattern: ^arn:aws[-a-z]*:cleanrooms-ml:[-a-z0-9]+:[0-9]{12}:membership/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/ml-input-channel/[-a-zA-Z0-9_/.]+$
      minLength: 20
      maxLength: 2048
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    MetricName:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 255
    MetricRegex:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 500
    MinMatchingSeedSize:
      type: integer
      minimum: 25
      maximum: 500000
    ModelTrainingDataChannelName:
      type: string
      pattern: ^[A-Za-z0-9\.\-_]+$
      minLength: 1
      maxLength: 64
    NameString:
      type: string
      pattern: ^(?!\s*$)[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDBFF-\uDC00\uDFFF\t]*$
      minLength: 1
      maxLength: 63
    NextToken:
      type: string
      minLength: 1
      maxLength: 10240
    ParameterKey:
      type: string
      pattern: ^[0-9a-zA-Z_]+$
      minLength: 1
      maxLength: 100
    ParameterValue:
      type: string
      minLength: 0
      maxLength: 250
    ResourceDescription:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDBFF-\uDC00\uDFFF\t\r\n]*$
      maxLength: 255
    ResourcePolicy:
      type: string
      minLength: 1
      maxLength: 20480
    S3Path:
      type: string
      pattern: ^s3://.+$
      minLength: 1
      maxLength: 1285
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TaggableArn:
      type: string
      pattern: ^arn:aws[-a-z]*:cleanrooms-ml:[-a-z0-9]+:[0-9]{12}:(membership/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/(configured-model-algorithm-association|trained-model|trained-model-inference-job|ml-input-channel)|training-dataset|audience-model|configured-audience-model|audience-generation-job|configured-model-algorithm|configured-model-algorithm-association|trained-model|trained-model-inference-job)/[-a-zA-Z0-9_/.]+$
      minLength: 20
      maxLength: 2048
    TrainedModelArn:
      type: string
      pattern: ^arn:aws[-a-z]*:cleanrooms-ml:[-a-z0-9]+:[0-9]{12}:(membership/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/)?trained-model/[-a-zA-Z0-9_/.]+$
      minLength: 20
      maxLength: 2048
    TrainedModelExportJobArn:
      type: string
      pattern: ^arn:aws[-a-z]*:cleanrooms-ml:[-a-z0-9]+:[0-9]{12}:trained-model-export-job/[-a-zA-Z0-9_/.]+$
      minLength: 20
      maxLength: 2048
    TrainedModelInferenceJobArn:
      type: string
      pattern: ^arn:aws[-a-z]*:cleanrooms-ml:[-a-z0-9]+:[0-9]{12}:(membership/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/)?trained-model-inference-job/[-a-zA-Z0-9_/.]+$
      minLength: 20
      maxLength: 2048
    TrainingDatasetArn:
      type: string
      pattern: ^arn:aws[-a-z]*:cleanrooms-ml:[-a-z0-9]+:[0-9]{12}:training-dataset/[-a-zA-Z0-9_/.]+$
      minLength: 20
      maxLength: 2048
    UUID:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
      minLength: 36
      maxLength: 36
