openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: cleanrooms
  x-aws-serviceName: cleanrooms
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2022-02-17'
  title: AWS Clean Rooms Service
  description: |-
    Welcome to the _Clean Rooms API Reference_.

    Clean Rooms is an Amazon Web Services service that helps multiple parties to join their data together in a secure collaboration workspace. In the collaboration, members who can run queries and jobs and receive results can get insights into the collective datasets without either party getting access to the other party's raw data.

    To learn more about Clean Rooms concepts, procedures, and best practices, see the [Clean Rooms User Guide](https://docs.aws.amazon.com/clean-rooms/latest/userguide/what-is.html).

    To learn more about SQL commands, functions, and conditions supported in Clean Rooms, see the [Clean Rooms SQL Reference](https://docs.aws.amazon.com/clean-rooms/latest/sql-reference/sql-reference.html).
servers:
- description: The AWS Clean Rooms Service regional endpoint
  url: https://cleanrooms.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccessDeniedExceptionReason:
      type: string
      enum:
      - INSUFFICIENT_PERMISSIONS
    AccountId:
      type: string
      pattern: ^\d+$
      minLength: 12
      maxLength: 12
    AdditionalAnalysesResourceArn:
      type: string
      pattern: ^arn:aws:cleanrooms:[\w]{2}-[\w]{4,9}-[\d]:([\d]{12}|\*):membership\/[\*\d\w-]+\/configuredaudiencemodelassociation\/[\*\d\w-]+$|^arn:aws[-a-z]*:cleanrooms-ml:[-a-z0-9]+:([0-9]{12}|\*):membership\/[\*\d\w-]+\/configured-model-algorithm-association\/([-a-zA-Z0-9_\/.]+|\*)$
      maxLength: 256
    AggregateFunctionName:
      type: string
      enum:
      - SUM
      - SUM_DISTINCT
      - COUNT
      - COUNT_DISTINCT
      - AVG
    AggregationType:
      type: string
      enum:
      - COUNT_DISTINCT
    AnalysisRuleColumnName:
      type: string
      pattern: ^[a-z0-9_](([a-z0-9_ ]+-)*([a-z0-9_ ]+))?$
      minLength: 1
      maxLength: 127
    AnalysisTemplateArn:
      type: string
      pattern: ^arn:aws:cleanrooms:[\w]{2}-[\w]{4,9}-[\d]:[\d]{12}:membership/[\d\w-]+/analysistemplate/[\d\w-]+$
      maxLength: 200
    AnalysisTemplateArnOrQueryWildcard:
      type: string
      pattern: ^(ANY_QUERY|ANY_JOB|arn:aws:cleanrooms:[\w]{2}-[\w]{4,9}-[\d]:[\d]{12}:membership/[\d\w-]+/analysistemplate/[\d\w-]+)$
      maxLength: 200
    AnalysisTemplateIdentifier:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
      minLength: 36
      maxLength: 36
    AnalysisTemplateText:
      type: string
      minLength: 0
      maxLength: 90000
    AthenaDatabaseName:
      type: string
      pattern: ^[a-zA-Z0-9_](([a-zA-Z0-9_]+-)*([a-zA-Z0-9_]+))?$
      maxLength: 128
    AthenaOutputLocation:
      type: string
      pattern: ^s3://[a-z0-9.-]{3,63}(.*)$
      minLength: 8
      maxLength: 1024
    AthenaTableName:
      type: string
      pattern: ^[a-zA-Z0-9_](([a-zA-Z0-9_]+)*([a-zA-Z0-9_]+))?$
      maxLength: 128
    AthenaWorkGroup:
      type: string
      pattern: ^([a-zA-Z0-9._-])*$
      minLength: 1
      maxLength: 128
    CleanroomsArn:
      type: string
      pattern: ^arn:aws:cleanrooms:[\w]{2}-[\w]{4,9}-[\d]:[\d]{12}:[\d\w/-]+$
      maxLength: 100
    CollaborationArn:
      type: string
      pattern: ^arn:aws:[\w]+:[\w]{2}-[\w]{4,9}-[\d]:[\d]{12}:collaboration/[\d\w-]+$
      maxLength: 100
    CollaborationDescription:
      type: string
      pattern: ^(?!\s*$)[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDBFF-\uDC00\uDFFF\t\r\n]*$
      minLength: 1
      maxLength: 255
    CollaborationIdentifier:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
      minLength: 36
      maxLength: 36
    CollaborationName:
      type: string
      pattern: ^(?!\s*$)[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDBFF-\uDC00\uDFFF\t]*$
      minLength: 1
      maxLength: 100
    ColumnName:
      type: string
      pattern: ^[a-z0-9_](([a-z0-9_ ]+-)*([a-z0-9_ ]+))?$
      maxLength: 128
    ColumnTypeString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDBFF-\uDC00\uDFFF\t]*$
      maxLength: 255
    ConfiguredAudienceModelArn:
      type: string
      pattern: ^arn:aws[-a-z]*:cleanrooms-ml:[-a-z0-9]+:[0-9]{12}:configured-audience-model/[-a-zA-Z0-9_/.]+$
      minLength: 20
      maxLength: 2048
    ConfiguredAudienceModelAssociationArn:
      type: string
      pattern: ^arn:aws:cleanrooms:[\w]{2}-[\w]{4,9}-[\d]:[\d]{12}:membership/[\d\w-]+/configuredaudiencemodelassociation/[\d\w-]+$
      maxLength: 256
    ConfiguredAudienceModelAssociationIdentifier:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
      minLength: 36
      maxLength: 36
    ConfiguredAudienceModelAssociationName:
      type: string
      pattern: ^(?!\s*$)[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDBFF-\uDC00\uDFFF\t]*$
      minLength: 1
      maxLength: 100
    ConfiguredTableArn:
      type: string
      pattern: ^arn:aws:[\w]+:[\w]{2}-[\w]{4,9}-[\d]:[\d]{12}:configuredtable/[\d\w-]+$
      maxLength: 100
    ConfiguredTableAssociationArn:
      type: string
      pattern: ^arn:aws:[\w]+:[\w]{2}-[\w]{4,9}-[\d]:[\d]{12}:configuredtableassociation/[\d\w-]+/[\d\w-]+$
      maxLength: 100
    ConfiguredTableAssociationIdentifier:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
      minLength: 36
      maxLength: 36
    ConfiguredTableIdentifier:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
      minLength: 36
      maxLength: 36
    ConflictExceptionReason:
      type: string
      enum:
      - ALREADY_EXISTS
      - SUBRESOURCES_EXIST
      - INVALID_STATE
    DifferentialPrivacyAggregationExpression:
      type: string
      minLength: 1
    DisplayName:
      type: string
      pattern: ^(?!\s*$)[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDBFF-\uDC00\uDFFF\t]*$
      minLength: 1
      maxLength: 100
    Epsilon:
      type: integer
      minimum: 1
      maximum: 20
    FilterableMemberStatus:
      type: string
      enum:
      - INVITED
      - ACTIVE
    GenericResourceName:
      type: string
      pattern: ^(?!\s*$)[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDBFF-\uDC00\uDFFF\t]*$
      minLength: 1
      maxLength: 100
    GlueDatabaseName:
      type: string
      pattern: ^[a-zA-Z0-9_](([a-zA-Z0-9_]+-)*([a-zA-Z0-9_]+))?$
      maxLength: 128
    GlueTableName:
      type: string
      pattern: ^[a-zA-Z0-9_](([a-zA-Z0-9_ ]+-)*([a-zA-Z0-9_ ]+))?$
      maxLength: 128
    IdMappingTableArn:
      type: string
      pattern: ^arn:aws:cleanrooms:[\w]{2}-[\w]{4,9}-[\d]:[\d]{12}:membership/[\d\w-]+/idmappingtable/[\d\w-]+$
      maxLength: 200
    IdMappingTableInputReferenceArn:
      type: string
      pattern: ^arn:(aws|aws-us-gov|aws-cn):entityresolution:.*:[0-9]+:(idmappingworkflow/.*)$
      minLength: 20
      maxLength: 2048
    IdNamespaceAssociationArn:
      type: string
      pattern: ^arn:aws:cleanrooms:[\w]{2}-[\w]{4,9}-[\d]:[\d]{12}:membership/[\d\w-]+/idnamespaceassociation/[\d\w-]+$
      maxLength: 256
    IdNamespaceAssociationIdentifier:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
      minLength: 36
      maxLength: 36
    IdNamespaceAssociationInputReferenceArn:
      type: string
      pattern: ^arn:aws:entityresolution:[\w]{2}-[\w]{4,9}-[\d]:[\d]{12}:idnamespace/[\d\w-]+$
      maxLength: 256
    JoinOperator:
      type: string
      enum:
      - OR
      - AND
    JoinRequiredOption:
      type: string
      enum:
      - QUERY_RUNNER
    KMSKeyArn:
      type: string
      pattern: ^arn:aws:kms:[\w]{2}-[\w]{4,9}-[\d]:[\d]{12}:key/[a-zA-Z0-9-]+$
      minLength: 20
      maxLength: 2048
    KeyPrefix:
      type: string
      pattern: ^[\w!.=*/-]*$
      minLength: 0
      maxLength: 512
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    MemberStatus:
      type: string
      enum:
      - INVITED
      - ACTIVE
      - LEFT
      - REMOVED
    MembershipArn:
      type: string
      pattern: ^arn:aws:[\w]+:[\w]{2}-[\w]{4,9}-[\d]:[\d]{12}:membership/[\d\w-]+$
      maxLength: 100
    MembershipIdentifier:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
      minLength: 36
      maxLength: 36
    MembershipStatus:
      type: string
      enum:
      - ACTIVE
      - REMOVED
      - COLLABORATION_DELETED
    PaginationToken:
      type: string
      maxLength: 10240
    ParameterName:
      type: string
      pattern: ^[0-9a-zA-Z_]+$
      minLength: 1
      maxLength: 100
    ParameterValue:
      type: string
      minLength: 0
      maxLength: 250
    PrivacyBudgetTemplateArn:
      type: string
      pattern: ^arn:aws:[\w]+:[\w]{2}-[\w]{4,9}-[\d]:[\d]{12}:privacybudgettemplate/[\d\w-]+$
      maxLength: 100
    PrivacyBudgetTemplateIdentifier:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
      minLength: 36
      maxLength: 36
    ProtectedJobIdentifier:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
      minLength: 36
      maxLength: 36
    ProtectedQueryIdentifier:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
      minLength: 36
      maxLength: 36
    ProtectedQueryStatus:
      type: string
      enum:
      - SUBMITTED
      - STARTED
      - CANCELLED
      - CANCELLING
      - FAILED
      - SUCCESS
      - TIMED_OUT
    ProtectedQueryType:
      type: string
      enum:
      - SQL
    ResourceAlias:
      type: string
      pattern: ^[a-zA-Z0-9_](([a-zA-Z0-9_ ]+-)*([a-zA-Z0-9_ ]+))?$
      maxLength: 128
    ResourceDescription:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDBFF-\uDC00\uDFFF\t\r\n]*$
      maxLength: 255
    ResourceType:
      type: string
      enum:
      - CONFIGURED_TABLE
      - COLLABORATION
      - MEMBERSHIP
      - CONFIGURED_TABLE_ASSOCIATION
    ResultFormat:
      type: string
      enum:
      - CSV
      - PARQUET
    RoleArn:
      type: string
      pattern: ^arn:aws:iam::[\w]+:role/[\w+=./@-]+$
      minLength: 32
      maxLength: 512
    ScalarFunctions:
      type: string
      enum:
      - ABS
      - CAST
      - CEILING
      - COALESCE
      - CONVERT
      - CURRENT_DATE
      - DATEADD
      - EXTRACT
      - FLOOR
      - GETDATE
      - LN
      - LOG
      - LOWER
      - ROUND
      - RTRIM
      - SQRT
      - SUBSTRING
      - TO_CHAR
      - TO_DATE
      - TO_NUMBER
      - TO_TIMESTAMP
      - TRIM
      - TRUNC
      - UPPER
    SecretsManagerArn:
      type: string
      pattern: ^arn:aws:secretsmanager:[a-z]{2}-[a-z]+-[0-9]:\d{12}:secret:.*$
      maxLength: 256
    SnowflakeAccountIdentifier:
      type: string
      pattern: ^[\p{L}\p{M}\p{N}\p{Pc}\p{Pd}\p{Zs}.]+$
      minLength: 3
      maxLength: 256
    SnowflakeDatabaseName:
      type: string
      pattern: ^[\p{L}\p{M}\p{N}\p{Pc}\p{Pd}\p{Zs}]+$
      minLength: 1
      maxLength: 256
    SnowflakeSchemaName:
      type: string
      pattern: ^[\p{L}\p{M}\p{N}\p{Pc}\p{Pd}\p{Zs}]+$
      minLength: 1
      maxLength: 256
    SnowflakeTableName:
      type: string
      pattern: ^[\p{L}\p{M}\p{N}\p{Pc}\p{Pd}\p{Zs}]+$
      minLength: 1
      maxLength: 256
    TableAlias:
      type: string
      pattern: ^[a-zA-Z0-9_](([a-zA-Z0-9_ ]+-)*([a-zA-Z0-9_ ]+))?$
      maxLength: 128
    TableDescription:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDBFF-\uDC00\uDFFF\t\r\n]*$
      maxLength: 255
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TargetProtectedQueryStatus:
      type: string
      enum:
      - CANCELLED
    UUID:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
      minLength: 36
      maxLength: 36
    UsersNoisePerQuery:
      type: integer
      minimum: 10
      maximum: 100
    ValidationExceptionReason:
      type: string
      enum:
      - FIELD_VALIDATION_FAILED
      - INVALID_CONFIGURATION
      - INVALID_QUERY
      - IAM_SYNCHRONIZATION_DELAY
