openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: cloudtrail_data
  x-aws-serviceName: cloudtraildata
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-07'
  version: '2021-08-11'
  title: AWS CloudTrail Data Service
  description: |-
    The CloudTrail Data Service lets you ingest events into CloudTrail from any source in your hybrid environments, such as in-house or SaaS applications hosted on-premises or in the cloud, virtual machines, or containers. You can store, access, analyze, troubleshoot and take action on this data without maintaining multiple log aggregators and reporting tools. After you run `PutAuditEvents` to ingest your application activity into CloudTrail, you can use CloudTrail Lake to search, query, and analyze the data that is logged from your applications.
servers:
- description: The AWS CloudTrail Data Service regional endpoint
  url: https://cloudtrail-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths:
  /PutAuditEvents:
    post:
      operationId: PutAuditEvents
      description: |-
        Ingests your application events into CloudTrail Lake. A required parameter, `auditEvents`, accepts the JSON records (also called _payload_) of events that you want CloudTrail to ingest. You can add up to 100 of these events (or up to 1 MB) per `PutAuditEvents` request.
      parameters:
      - name: channelArn
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/ChannelArn'
      - name: externalId
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/ExternalId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                auditEvents:
                  $ref: '#/components/schemas/AuditEvents'
      responses:
        '200': {}
        '400':
          description: |-
            The operation requested is not supported in this region or account.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnsupportedOperationException'
components:
  schemas:
    AuditEvent:
      type: object
      properties:
        id:
          allOf:
          - $ref: '#/components/schemas/Uuid'
          description: The original event ID from the source event.
        eventData:
          allOf:
          - $ref: '#/components/schemas/String'
          description: The content of an audit event that comes from the event, such
            as `userIdentity`, `userAgent`, and `eventSource`.
        eventDataChecksum:
          allOf:
          - $ref: '#/components/schemas/String'
          description: 'A checksum is a base64-SHA256 algorithm that helps you verify
            that CloudTrail receives the event that matches with the checksum. Calculate
            the checksum by running a command like the following:


            `printf %s _$eventdata_ | openssl dgst -binary -sha256 | base64`'
      required:
      - id
      - eventData
      description: An event from a source outside of Amazon Web Services that you
        want CloudTrail to log.
    AuditEventResultEntries:
      type: array
      items:
        $ref: '#/components/schemas/AuditEventResultEntry'
    AuditEventResultEntry:
      type: object
      properties:
        id:
          allOf:
          - $ref: '#/components/schemas/Uuid'
          description: The original event ID from the source event.
        eventID:
          allOf:
          - $ref: '#/components/schemas/Uuid'
          description: The event ID assigned by CloudTrail.
      required:
      - id
      - eventID
      description: A response that includes successful and failed event results.
    AuditEvents:
      type: array
      items:
        $ref: '#/components/schemas/AuditEvent'
    ChannelArn:
      type: string
      pattern: ^arn:.*$
    ChannelInsufficientPermission:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/String'
      description: The caller's account ID must be the same as the channel owner's
        account ID.
    ChannelNotFound:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/String'
      description: The channel could not be found.
    ChannelUnsupportedSchema:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/String'
      description: The schema type of the event is not supported.
    DuplicatedAuditEventId:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/String'
      description: Two or more entries in the request have the same event ID.
    ErrorCode:
      type: string
      minLength: 1
      maxLength: 128
    ErrorMessage:
      type: string
      minLength: 1
      maxLength: 1024
    ExternalId:
      type: string
      pattern: ^[\w+=,.@:\/-]*$
      minLength: 2
      maxLength: 1224
    InvalidChannelARN:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/String'
      description: The specified channel ARN is not a valid channel ARN.
    PutAuditEventsRequest:
      type: object
      properties:
        auditEvents:
          allOf:
          - $ref: '#/components/schemas/AuditEvents'
          description: The JSON payload of events that you want to ingest. You can
            also point to the JSON event payload in a file.
        channelArn:
          allOf:
          - $ref: '#/components/schemas/ChannelArn'
          description: The ARN or ID (the ARN suffix) of a channel.
        externalId:
          allOf:
          - $ref: '#/components/schemas/ExternalId'
          description: A unique identifier that is conditionally required when the
            channel's resource policy includes an external ID. This value can be any
            string, such as a passphrase or account number.
      required:
      - auditEvents
      - channelArn
    PutAuditEventsResponse:
      type: object
      properties:
        successful:
          allOf:
          - $ref: '#/components/schemas/AuditEventResultEntries'
          description: Lists events in the provided event payload that were successfully
            ingested into CloudTrail.
        failed:
          allOf:
          - $ref: '#/components/schemas/ResultErrorEntries'
          description: Lists events in the provided event payload that could not be
            ingested into CloudTrail, and includes the error code and error message
            returned for events that could not be ingested.
      required:
      - successful
      - failed
    ResultErrorEntries:
      type: array
      items:
        $ref: '#/components/schemas/ResultErrorEntry'
    ResultErrorEntry:
      type: object
      properties:
        id:
          allOf:
          - $ref: '#/components/schemas/Uuid'
          description: The original event ID from the source event that could not
            be ingested by CloudTrail.
        errorCode:
          allOf:
          - $ref: '#/components/schemas/ErrorCode'
          description: 'The error code for events that could not be ingested by CloudTrail.
            Possible error codes include: `FieldTooLong`, `FieldNotFound`, `InvalidChecksum`,
            `InvalidData`, `InvalidRecipient`, `InvalidEventSource`, `AccountNotSubscribed`,
            `Throttling`, and `InternalFailure`.'
        errorMessage:
          allOf:
          - $ref: '#/components/schemas/ErrorMessage'
          description: The message that describes the error for events that could
            not be ingested by CloudTrail.
      required:
      - id
      - errorCode
      - errorMessage
      description: Includes the error code and error message for events that could
        not be ingested by CloudTrail.
    UnsupportedOperationException:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/String'
      description: The operation requested is not supported in this region or account.
    Uuid:
      type: string
      pattern: ^[-_A-Za-z0-9]+$
      minLength: 1
      maxLength: 128
