openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: cloudsearch_domain
  x-aws-serviceName: cloudsearchdomain
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2013-01-01'
  title: Amazon CloudSearch Domain
  description: |-
    You use the AmazonCloudSearch2013 API to upload documents to a search domain and search those documents.

    The endpoints for submitting `UploadDocuments`, `Search`, and `Suggest` requests are domain-specific. To get the endpoints for your domain, use the Amazon CloudSearch configuration service `DescribeDomains` action. The domain endpoints are also displayed on the domain dashboard in the Amazon CloudSearch console. You submit suggest requests to the search endpoint.

    For more information, see the [Amazon CloudSearch Developer Guide](http://docs.aws.amazon.com/cloudsearch/latest/developerguide).
servers:
- description: The Amazon CloudSearch Domain regional endpoint
  url: https://cloudsearchdomain.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Adds:
      type: integer
      format: int64
      default: 0
    Blob:
      type: string
      format: byte
    BucketList:
      type: array
      items:
        $ref: '#/components/schemas/Bucket'
    ContentType:
      type: string
      enum:
      - application/json
      - application/xml
    Cursor:
      type: string
    Deletes:
      type: integer
      format: int64
      default: 0
    DocumentServiceWarnings:
      type: array
      items:
        $ref: '#/components/schemas/DocumentServiceWarning'
    Double:
      type: number
      format: double
      default: 0
    Expr:
      type: string
    Exprs:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    Facet:
      type: string
    Facets:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/BucketInfo'
    FieldValue:
      type: array
      items:
        $ref: '#/components/schemas/String'
    Fields:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/FieldValue'
    FilterQuery:
      type: string
    Highlight:
      type: string
    Highlights:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    HitList:
      type: array
      items:
        $ref: '#/components/schemas/Hit'
    Long:
      type: integer
      format: int64
      default: 0
    Partial:
      type: boolean
      default: false
    Query:
      type: string
    QueryOptions:
      type: string
    QueryParser:
      type: string
      enum:
      - simple
      - structured
      - lucene
      - dismax
    Return:
      type: string
    Size:
      type: integer
      format: int64
      default: 0
    Sort:
      type: string
    Start:
      type: integer
      format: int64
      default: 0
    Stat:
      type: string
    Stats:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/FieldStats'
      description: <p>The statistics calculated in the request.</p>
    String:
      type: string
    Suggester:
      type: string
    Suggestions:
      type: array
      items:
        $ref: '#/components/schemas/SuggestionMatch'
    SuggestionsSize:
      type: integer
      format: int64
      default: 0
