openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: clouddirectory
  x-aws-serviceName: clouddirectory
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-01-11'
  title: Amazon CloudDirectory
  description: |-
    Amazon Cloud Directory

    Amazon Cloud Directory is a component of the AWS Directory Service that simplifies the development and management of cloud-scale web, mobile, and IoT applications. This guide describes the Cloud Directory operations that you can call programmatically and includes detailed information on data types and errors. For information about Cloud Directory features, see [AWS Directory Service](https://aws.amazon.com/directoryservice/) and the [Amazon Cloud Directory Developer Guide](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/what_is_cloud_directory.html).
servers:
- description: The Amazon CloudDirectory regional endpoint
  url: https://clouddirectory.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Arn:
      type: string
    Arns:
      type: array
      items:
        $ref: '#/components/schemas/Arn'
    AttributeKeyAndValueList:
      type: array
      items:
        $ref: '#/components/schemas/AttributeKeyAndValue'
    AttributeKeyList:
      type: array
      items:
        $ref: '#/components/schemas/AttributeKey'
    AttributeName:
      type: string
      pattern: ^[a-zA-Z0-9._:-]*$
      minLength: 1
      maxLength: 230
    AttributeNameAndValueList:
      type: array
      items:
        $ref: '#/components/schemas/AttributeNameAndValue'
    AttributeNameList:
      type: array
      items:
        $ref: '#/components/schemas/AttributeName'
    BatchOperationIndex:
      type: integer
      default: 0
    BatchReadExceptionType:
      type: string
      enum:
      - ValidationException
      - InvalidArnException
      - ResourceNotFoundException
      - InvalidNextTokenException
      - AccessDeniedException
      - NotNodeException
      - FacetValidationException
      - CannotListParentOfRootException
      - NotIndexException
      - NotPolicyException
      - DirectoryNotEnabledException
      - LimitExceededException
      - InternalServiceException
    BatchReadOperationList:
      type: array
      items:
        $ref: '#/components/schemas/BatchReadOperation'
    BatchReadOperationResponseList:
      type: array
      items:
        $ref: '#/components/schemas/BatchReadOperationResponse'
    BatchReferenceName:
      type: string
    BatchWriteExceptionType:
      type: string
      enum:
      - InternalServiceException
      - ValidationException
      - InvalidArnException
      - LinkNameAlreadyInUseException
      - StillContainsLinksException
      - FacetValidationException
      - ObjectNotDetachedException
      - ResourceNotFoundException
      - AccessDeniedException
      - InvalidAttachmentException
      - NotIndexException
      - NotNodeException
      - IndexedAttributeMissingException
      - ObjectAlreadyDetachedException
      - NotPolicyException
      - DirectoryNotEnabledException
      - LimitExceededException
      - UnsupportedIndexTypeException
    BatchWriteOperationList:
      type: array
      items:
        $ref: '#/components/schemas/BatchWriteOperation'
    BatchWriteOperationResponseList:
      type: array
      items:
        $ref: '#/components/schemas/BatchWriteOperationResponse'
    BinaryAttributeValue:
      type: string
      format: byte
    Bool:
      type: boolean
      default: false
    BooleanAttributeValue:
      type: boolean
    ConsistencyLevel:
      type: string
      enum:
      - SERIALIZABLE
      - EVENTUAL
    Date:
      type: string
      format: date-time
    DatetimeAttributeValue:
      type: string
      format: date-time
    DirectoryArn:
      type: string
    DirectoryList:
      type: array
      items:
        $ref: '#/components/schemas/Directory'
    DirectoryName:
      type: string
      pattern: ^[a-zA-Z0-9._-]*$
      minLength: 1
      maxLength: 64
    DirectoryState:
      type: string
      enum:
      - ENABLED
      - DISABLED
      - DELETED
    ExceptionMessage:
      type: string
    FacetAttributeList:
      type: array
      items:
        $ref: '#/components/schemas/FacetAttribute'
    FacetAttributeType:
      type: string
      enum:
      - STRING
      - BINARY
      - BOOLEAN
      - NUMBER
      - DATETIME
      - VARIANT
    FacetAttributeUpdateList:
      type: array
      items:
        $ref: '#/components/schemas/FacetAttributeUpdate'
    FacetName:
      type: string
      pattern: ^[a-zA-Z0-9._-]*$
      minLength: 1
      maxLength: 64
    FacetNameList:
      type: array
      items:
        $ref: '#/components/schemas/FacetName'
    FacetStyle:
      type: string
      enum:
      - STATIC
      - DYNAMIC
    IndexAttachmentList:
      type: array
      items:
        $ref: '#/components/schemas/IndexAttachment'
    LinkAttributeUpdateList:
      type: array
      items:
        $ref: '#/components/schemas/LinkAttributeUpdate'
    LinkName:
      type: string
      pattern: ^[^\/\[\]\(\):\{\}#@!?\s\\;]+$
      minLength: 1
      maxLength: 64
    LinkNameToObjectIdentifierMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ObjectIdentifier'
    NextToken:
      type: string
    NumberAttributeValue:
      type: string
    NumberResults:
      type: integer
      minimum: 1
    ObjectAttributeRangeList:
      type: array
      items:
        $ref: '#/components/schemas/ObjectAttributeRange'
    ObjectAttributeUpdateList:
      type: array
      items:
        $ref: '#/components/schemas/ObjectAttributeUpdate'
    ObjectIdentifier:
      type: string
    ObjectIdentifierAndLinkNameList:
      type: array
      items:
        $ref: '#/components/schemas/ObjectIdentifierAndLinkNameTuple'
    ObjectIdentifierList:
      type: array
      items:
        $ref: '#/components/schemas/ObjectIdentifier'
    ObjectIdentifierToLinkNameMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/LinkName'
    ObjectType:
      type: string
      enum:
      - NODE
      - LEAF_NODE
      - POLICY
      - INDEX
    PathString:
      type: string
    PathToObjectIdentifiersList:
      type: array
      items:
        $ref: '#/components/schemas/PathToObjectIdentifiers'
    PolicyAttachmentList:
      type: array
      items:
        $ref: '#/components/schemas/PolicyAttachment'
    PolicyToPathList:
      type: array
      items:
        $ref: '#/components/schemas/PolicyToPath'
    PolicyType:
      type: string
    RangeMode:
      type: string
      enum:
      - FIRST
      - LAST
      - LAST_BEFORE_MISSING_VALUES
      - INCLUSIVE
      - EXCLUSIVE
    RequiredAttributeBehavior:
      type: string
      enum:
      - REQUIRED_ALWAYS
      - NOT_REQUIRED
    RuleKey:
      type: string
      pattern: ^[a-zA-Z0-9._-]*$
      minLength: 1
      maxLength: 64
    RuleMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Rule'
    RuleParameterKey:
      type: string
    RuleParameterMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/RuleParameterValue'
    RuleParameterValue:
      type: string
    RuleType:
      type: string
      enum:
      - BINARY_LENGTH
      - NUMBER_COMPARISON
      - STRING_FROM_SET
      - STRING_LENGTH
    SchemaFacetList:
      type: array
      items:
        $ref: '#/components/schemas/SchemaFacet'
    SchemaJsonDocument:
      type: string
    SchemaName:
      type: string
      pattern: ^[a-zA-Z0-9._-]*$
      minLength: 1
      maxLength: 32
    SelectorObjectReference:
      type: string
    StringAttributeValue:
      type: string
    TagKey:
      type: string
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagList:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    TagValue:
      type: string
    TagsNumberResults:
      type: integer
      minimum: 50
    TypedAttributeValue:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/StringAttributeValue'
        description: |-
          A string data value.
      - allOf:
        - $ref: '#/components/schemas/BinaryAttributeValue'
        description: |-
          A binary data value.
      - allOf:
        - $ref: '#/components/schemas/BooleanAttributeValue'
        description: |-
          A Boolean data value.
      - allOf:
        - $ref: '#/components/schemas/NumberAttributeValue'
        description: |-
          A number data value.
      - allOf:
        - $ref: '#/components/schemas/DatetimeAttributeValue'
        description: |-
          A date and time value.
      description: |-
        Represents the data for a typed attribute. You can set one, and only one, of the elements. Each attribute in an item is a name-value pair. Attributes have a single value.
    TypedLinkAttributeDefinitionList:
      type: array
      items:
        $ref: '#/components/schemas/TypedLinkAttributeDefinition'
    TypedLinkAttributeRangeList:
      type: array
      items:
        $ref: '#/components/schemas/TypedLinkAttributeRange'
    TypedLinkFacetAttributeUpdateList:
      type: array
      items:
        $ref: '#/components/schemas/TypedLinkFacetAttributeUpdate'
    TypedLinkName:
      type: string
      pattern: ^[a-zA-Z0-9._-]*$
    TypedLinkNameList:
      type: array
      items:
        $ref: '#/components/schemas/TypedLinkName'
    TypedLinkSpecifierList:
      type: array
      items:
        $ref: '#/components/schemas/TypedLinkSpecifier'
    UpdateActionType:
      type: string
      enum:
      - CREATE_OR_UPDATE
      - DELETE
    Version:
      type: string
      pattern: ^[a-zA-Z0-9._-]*$
      minLength: 1
      maxLength: 10
