openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: cloudtrail_data
  x-aws-serviceName: cloudtraildata
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2021-08-11'
  title: AWS CloudTrail Data Service
  description: |-
    The CloudTrail Data Service lets you ingest events into CloudTrail from any source in your hybrid environments, such as in-house or SaaS applications hosted on-premises or in the cloud, virtual machines, or containers. You can store, access, analyze, troubleshoot and take action on this data without maintaining multiple log aggregators and reporting tools. After you run `PutAuditEvents` to ingest your application activity into CloudTrail, you can use CloudTrail Lake to search, query, and analyze the data that is logged from your applications.
servers:
- description: The AWS CloudTrail Data Service regional endpoint
  url: https://cloudtrail-data.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AuditEventResultEntries:
      type: array
      items:
        $ref: '#/components/schemas/AuditEventResultEntry'
    AuditEvents:
      type: array
      items:
        $ref: '#/components/schemas/AuditEvent'
    ChannelArn:
      type: string
      pattern: ^arn:.*$
    ErrorCode:
      type: string
      minLength: 1
      maxLength: 128
    ErrorMessage:
      type: string
      minLength: 1
      maxLength: 1024
    ExternalId:
      type: string
      pattern: ^[\w+=,.@:\/-]*$
      minLength: 2
      maxLength: 1224
    ResultErrorEntries:
      type: array
      items:
        $ref: '#/components/schemas/ResultErrorEntry'
    Uuid:
      type: string
      pattern: ^[-_A-Za-z0-9]+$
      minLength: 1
      maxLength: 128
