openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: codeguruprofiler
  x-aws-serviceName: codeguruprofiler
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2019-07-18'
  title: Amazon CodeGuru Profiler
  description: |-
    This section provides documentation for the Amazon CodeGuru Profiler API operations.

    Amazon CodeGuru Profiler collects runtime performance data from your live applications, and provides recommendations that can help you fine-tune your application performance. Using machine learning algorithms, CodeGuru Profiler can help you find your most expensive lines of code and suggest ways you can improve efficiency and remove CPU bottlenecks.

    Amazon CodeGuru Profiler provides different visualizations of profiling data to help you identify what code is running on the CPU, see how much time is consumed, and suggest ways to reduce CPU utilization.

    Amazon CodeGuru Profiler currently supports applications written in all Java virtual machine (JVM) languages and Python. While CodeGuru Profiler supports both visualizations and recommendations for applications written in Java, it can also generate visualizations and a subset of recommendations for applications written in other JVM languages and Python.

    For more information, see [What is Amazon CodeGuru Profiler](https://docs.aws.amazon.com/codeguru/latest/profiler-ug/what-is-codeguru-profiler.html) in the _Amazon CodeGuru Profiler User Guide_.
servers:
- description: The Amazon CodeGuru Profiler regional endpoint
  url: https://codeguru-profiler.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ActionGroup:
      type: string
      enum:
      - agentPermissions
    AgentParameterField:
      type: string
      enum:
      - SamplingIntervalInMilliseconds
      - ReportingIntervalInMilliseconds
      - MinimumTimeForReportingInMilliseconds
      - MemoryUsageLimitPercent
      - MaxStackDepth
    AggregationPeriod:
      type: string
      enum:
      - PT5M
      - PT1H
      - P1D
    AnomalyInstanceId:
      type: string
      pattern: '[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}'
    ChannelId:
      type: string
      pattern: '[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}'
    ChannelUri:
      type: string
    ClientToken:
      type: string
      pattern: ^[\w-]+$
      minLength: 1
      maxLength: 64
    ComputePlatform:
      type: string
      enum:
      - Default
      - AWSLambda
    EventPublisher:
      type: string
      enum:
      - AnomalyDetection
    FeedbackType:
      type: string
      enum:
      - Positive
      - Negative
    FindingsReportId:
      type: string
      pattern: '[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}'
    FleetInstanceId:
      type: string
      minLength: 1
      maxLength: 255
    Locale:
      type: string
    MaxDepth:
      type: integer
      minimum: 1
      maximum: 10000
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
    MetadataField:
      type: string
      enum:
      - ComputePlatform
      - AgentId
      - AwsRequestId
      - ExecutionEnvironment
      - LambdaFunctionArn
      - LambdaMemoryLimitInMB
      - LambdaRemainingTimeInMilliseconds
      - LambdaTimeGapBetweenInvokesInMilliseconds
      - LambdaPreviousExecutionTimeInMilliseconds
    MetricType:
      type: string
      enum:
      - AggregatedRelativeTotalTime
    OrderBy:
      type: string
      enum:
      - TimestampDescending
      - TimestampAscending
    PaginationToken:
      type: string
      pattern: ^[\w-]+$
      minLength: 1
      maxLength: 64
    Period:
      type: string
      minLength: 1
      maxLength: 64
    Principal:
      type: string
    ProfilingGroupArn:
      type: string
    ProfilingGroupName:
      type: string
      pattern: ^[\w-]+$
      minLength: 1
      maxLength: 255
    RevisionId:
      type: string
      pattern: '[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}'
