openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: codeguru_reviewer
  x-aws-serviceName: codegurureviewer
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2019-09-19'
  title: Amazon CodeGuru Reviewer
  description: |-
    This section provides documentation for the Amazon CodeGuru Reviewer API operations. CodeGuru Reviewer is a service that uses program analysis and machine learning to detect potential defects that are difficult for developers to find and recommends fixes in your Java and Python code.

    By proactively detecting and providing recommendations for addressing code defects and implementing best practices, CodeGuru Reviewer improves the overall quality and maintainability of your code base during the code review stage. For more information about CodeGuru Reviewer, see the _[Amazon CodeGuru Reviewer User Guide](https://docs.aws.amazon.com/codeguru/latest/reviewer-ug/welcome.html)._

    To improve the security of your CodeGuru Reviewer API calls, you can establish a private connection between your VPC and CodeGuru Reviewer by creating an _interface VPC endpoint_. For more information, see [CodeGuru Reviewer and interface VPC endpoints (Amazon Web Services PrivateLink)](https://docs.aws.amazon.com/codeguru/latest/reviewer-ug/vpc-interface-endpoints.html) in the _Amazon CodeGuru Reviewer User Guide_.
servers:
- description: The Amazon CodeGuru Reviewer regional endpoint
  url: https://codeguru-reviewer.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Arn:
      type: string
      pattern: ^arn:aws[^:\s]*:codeguru-reviewer:[^:\s]+:[\d]{12}:[a-z-]+:[\w-]+$
      minLength: 1
      maxLength: 1600
    AssociationArn:
      type: string
      pattern: ^arn:aws[^:\s]*:codeguru-reviewer:[^:\s]+:[\d]{12}:association:[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 1
      maxLength: 1600
    AssociationId:
      type: string
      minLength: 1
      maxLength: 64
    BranchName:
      type: string
      minLength: 1
      maxLength: 256
    BuildArtifactsObjectKey:
      type: string
      pattern: ^\S(.*\S)?$
      minLength: 1
      maxLength: 1024
    ClientRequestToken:
      type: string
      pattern: ^[\w-]+$
      minLength: 1
      maxLength: 64
    CodeReviewName:
      type: string
      pattern: ^[a-zA-Z0-9-_]*$
      minLength: 1
      maxLength: 100
    CommitId:
      type: string
      minLength: 6
      maxLength: 64
    ConnectionArn:
      type: string
      pattern: ^arn:aws(-[\w]+)*:.+:.+:[0-9]{12}:.+$
      minLength: 0
      maxLength: 256
    ErrorMessage:
      type: string
    EventName:
      type: string
      pattern: ^[ \-A-Z_a-z]+$
      minLength: 1
      maxLength: 32
    EventState:
      type: string
      pattern: ^[ \-A-Z_a-z]+$
      minLength: 1
      maxLength: 32
    FilePath:
      type: string
      minLength: 1
      maxLength: 1024
    KMSKeyId:
      type: string
      pattern: ^[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 2048
    LineNumber:
      type: integer
    ListCodeReviewsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListRecommendationsMaxResults:
      type: integer
      minimum: 1
      maximum: 300
    LongDescription:
      type: string
      pattern: ^\S(.*\S)?$
      minLength: 1
      maxLength: 1000
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    Name:
      type: string
      pattern: ^\S[\w.-]*$
      minLength: 1
      maxLength: 100
    NextToken:
      type: string
      minLength: 1
      maxLength: 2048
    Owner:
      type: string
      pattern: ^\S(.*\S)?$
      minLength: 1
      maxLength: 100
    PullRequestId:
      type: string
      minLength: 1
      maxLength: 64
    RecommendationId:
      type: string
      minLength: 1
      maxLength: 64
    RequestId:
      type: string
      minLength: 1
      maxLength: 64
    Requester:
      type: string
      pattern: ^\S(.*\S)?$
      minLength: 1
      maxLength: 100
    RuleId:
      type: string
      pattern: ^\S+\/[a-zA-Z0-9-]+@v\d+\.\d+$
      minLength: 1
      maxLength: 64
    RuleName:
      type: string
      pattern: ^\S(.*\S)?$
      minLength: 1
      maxLength: 100
    RuleTag:
      type: string
      pattern: ^\S(.*\S)?$
      minLength: 1
      maxLength: 50
    S3BucketName:
      type: string
      pattern: ^\S(.*\S)?$
      minLength: 3
      maxLength: 63
    ShortDescription:
      type: string
      pattern: ^\S(.*\S)?$
      minLength: 1
      maxLength: 200
    SourceCodeArtifactsObjectKey:
      type: string
      pattern: ^\S(.*\S)?$
      minLength: 1
      maxLength: 1024
    StateReason:
      type: string
      minLength: 0
      maxLength: 256
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    Text:
      type: string
      minLength: 1
      maxLength: 5000
    UserId:
      type: string
      minLength: 1
      maxLength: 256
