openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: codeguru_security
  x-aws-serviceName: codegurusecurity
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: Amazon CodeGuru Security
  description: |-
    Amazon CodeGuru Security is in preview release and is subject to change.

    This section provides documentation for the Amazon CodeGuru Security API operations. CodeGuru Security is a service that uses program analysis and machine learning to detect security policy violations and vulnerabilities, and recommends ways to address these security risks.

    By proactively detecting and providing recommendations for addressing security risks, CodeGuru Security improves the overall security of your application code. For more information about CodeGuru Security, see the [Amazon CodeGuru Security User Guide](https://docs.aws.amazon.com/codeguru/latest/security-ug/what-is-codeguru-security.html).
servers:
- description: The Amazon CodeGuru Security regional endpoint
  url: https://codeguru-security.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AnalysisType:
      type: string
      enum:
      - Security
      - All
    BatchGetFindingsErrors:
      type: array
      items:
        $ref: '#/components/schemas/BatchGetFindingsError'
    CategoriesWithMostFindings:
      type: array
      items:
        $ref: '#/components/schemas/CategoryWithFindingNum'
    ClientToken:
      type: string
      pattern: ^[\S]+$
      minLength: 1
      maxLength: 64
    CodeSnippet:
      type: array
      items:
        $ref: '#/components/schemas/CodeLine'
    DetectorTags:
      type: array
      items:
        type: string
    ErrorCode:
      type: string
      enum:
      - DUPLICATE_IDENTIFIER
      - ITEM_DOES_NOT_EXIST
      - INTERNAL_ERROR
      - INVALID_FINDING_ID
      - INVALID_SCAN_NAME
    ErrorMessage:
      type: string
      minLength: 1
    FindingIdentifiers:
      type: array
      items:
        $ref: '#/components/schemas/FindingIdentifier'
    Findings:
      type: array
      items:
        $ref: '#/components/schemas/Finding'
    FindingsMetricList:
      type: array
      items:
        $ref: '#/components/schemas/AccountFindingsMetric'
    HeaderKey:
      type: string
      minLength: 1
    HeaderValue:
      type: string
      minLength: 1
    KmsKeyArn:
      type: string
      pattern: ^arn:aws:kms:[\S]+:[\d]{12}:key\/(([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})|(mrk-[0-9a-zA-Z]{32}))$
      minLength: 1
      maxLength: 2048
    NextToken:
      type: string
      pattern: ^[\S]+$
      minLength: 1
      maxLength: 2048
    ReferenceUrls:
      type: array
      items:
        type: string
    RelatedVulnerabilities:
      type: array
      items:
        type: string
    RequestHeaderMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/HeaderValue'
    ResourceId:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/Uuid'
        description: |-
          The identifier for the code file uploaded to the resource object. Returned by `CreateUploadUrl` when you upload resources to be scanned.
      description: |-
        The identifier for a resource object that contains resources to scan. Specifying a codeArtifactId is required to create a scan.
    S3Url:
      type: string
      minLength: 1
    ScanName:
      type: string
      pattern: ^[a-zA-Z0-9-_$:.]*$
      minLength: 1
      maxLength: 140
    ScanNameArn:
      type: string
      pattern: ^arn:aws:codeguru-security:[\S]+:[\d]{12}:scans\/[a-zA-Z0-9-_$:.]*$
      minLength: 1
      maxLength: 300
    ScanState:
      type: string
      enum:
      - InProgress
      - Successful
      - Failed
    ScanSummaries:
      type: array
      items:
        $ref: '#/components/schemas/ScanSummary'
    ScanType:
      type: string
      enum:
      - Standard
      - Express
    ScansWithMostOpenCriticalFindings:
      type: array
      items:
        $ref: '#/components/schemas/ScanNameWithFindingNum'
    ScansWithMostOpenFindings:
      type: array
      items:
        $ref: '#/components/schemas/ScanNameWithFindingNum'
    Severity:
      type: string
      enum:
      - Critical
      - High
      - Medium
      - Low
      - Info
    Status:
      type: string
      enum:
      - Closed
      - Open
      - All
    SuggestedFixes:
      type: array
      items:
        $ref: '#/components/schemas/SuggestedFix'
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    Uuid:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
    ValidationExceptionFieldList:
      type: array
      items:
        $ref: '#/components/schemas/ValidationExceptionField'
    ValidationExceptionReason:
      type: string
      enum:
      - unknownOperation
      - cannotParse
      - fieldValidationFailed
      - other
      - lambdaCodeShaMisMatch
