openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: connectcampaignsv2
  x-aws-serviceName: connectcampaignsv2
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2024-04-23'
  title: AmazonConnectCampaignServiceV2
  description: |-
    Provide APIs to create and manage Amazon Connect Campaigns.
servers:
- description: The AmazonConnectCampaignServiceV2 regional endpoint
  url: https://connect-campaigns.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Arn:
      type: string
      pattern: ^arn:[a-zA-Z0-9-]+:[a-zA-Z0-9-]+:[a-z]{2}-[a-z]+-\d{1,2}:[a-zA-Z0-9-]+:[^:]+(?:/[^:]+)*(?:/[^:]+)?(?:\:[^:]+)?$
      minLength: 20
      maxLength: 500
    AttributeName:
      type: string
      pattern: ^[a-zA-Z0-9\-_]+$
      minLength: 0
      maxLength: 32767
    AttributeValue:
      type: string
      pattern: ^.*$
      minLength: 0
      maxLength: 32767
    CampaignArn:
      type: string
      minLength: 20
      maxLength: 500
    CampaignDeletionPolicy:
      type: string
      enum:
      - RETAIN_ALL
      - DELETE_ALL
    CampaignId:
      type: string
      pattern: ^[a-zA-Z0-9\-:/]*$
      minLength: 0
      maxLength: 256
    CampaignName:
      type: string
      minLength: 1
      maxLength: 127
    CampaignState:
      type: string
      enum:
      - Initialized
      - Running
      - Paused
      - Stopped
      - Failed
      - Completed
    ChannelSubtype:
      type: string
      enum:
      - TELEPHONY
      - SMS
      - EMAIL
    ClientToken:
      type: string
      pattern: ^[a-zA-Z0-9_\-.]*$
      minLength: 0
      maxLength: 200
    CommunicationLimitTimeUnit:
      type: string
      enum:
      - DAY
    CommunicationLimitsConfigType:
      type: string
      enum:
      - ALL_CHANNEL_SUBTYPES
    CommunicationTimeConfigType:
      type: string
      enum:
      - TELEPHONY
      - SMS
      - EMAIL
    ContactFlowId:
      type: string
      maxLength: 500
    DayOfWeek:
      type: string
      enum:
      - MONDAY
      - TUESDAY
      - WEDNESDAY
      - THURSDAY
      - FRIDAY
      - SATURDAY
      - SUNDAY
    DestinationPhoneNumber:
      type: string
      pattern: ^[\d\-+]*$
      minLength: 0
      maxLength: 20
    DialRequestId:
      type: string
      pattern: ^[a-zA-Z0-9_\-.]*$
      minLength: 0
      maxLength: 256
    EmailAddress:
      type: string
      pattern: '[^\s@]+@[^\s@]+\.[^\s@]+'
      minLength: 1
      maxLength: 255
    EmailDisplayName:
      type: string
      minLength: 0
      maxLength: 256
    Enabled:
      type: boolean
      default: false
      description: Boolean to indicate if custom encryption has been enabled.
    EncryptionKey:
      type: string
      maxLength: 500
    EncryptionType:
      type: string
      enum:
      - KMS
    EventType:
      type: string
      enum:
      - Campaign-Email
      - Campaign-SMS
      - Campaign-Telephony
      - Campaign-Orchestration
    FailureCode:
      type: string
      enum:
      - InvalidInput
      - RequestThrottled
      - UnknownError
      - BufferLimitExceeded
    GetCampaignStateBatchFailureCode:
      type: string
      enum:
      - ResourceNotFound
      - UnknownError
    InstanceId:
      type: string
      pattern: ^[a-zA-Z0-9_\-.]*$
      minLength: 0
      maxLength: 256
    InstanceIdFilterOperator:
      type: string
      enum:
      - Eq
    InstanceOnboardingJobFailureCode:
      type: string
      enum:
      - EVENT_BRIDGE_ACCESS_DENIED
      - EVENT_BRIDGE_MANAGED_RULE_LIMIT_EXCEEDED
      - IAM_ACCESS_DENIED
      - KMS_ACCESS_DENIED
      - KMS_KEY_NOT_FOUND
      - INTERNAL_FAILURE
    InstanceOnboardingJobStatusCode:
      type: string
      enum:
      - IN_PROGRESS
      - SUCCEEDED
      - FAILED
    Iso8601Date:
      type: string
      pattern: ^\d{4}-\d{2}-\d{2}$
    Iso8601Duration:
      type: string
      pattern: ^P(?:([-+]?[0-9]+)D)?(T(?:([-+]?[0-9]+)H)?(?:([-+]?[0-9]+)M)?(?:([-+]?[0-9]+)(?:[.,]([0-9]{0,9}))?S)?)?$
      minLength: 0
      maxLength: 50
    Iso8601Time:
      type: string
      pattern: ^T\d{2}:\d{2}$
    LocalTimeZoneDetectionType:
      type: string
      enum:
      - ZIP_CODE
      - AREA_CODE
    MaxResults:
      type: integer
      minimum: 1
      maximum: 50
      description: The maximum number of results to return per page.
    NextToken:
      type: string
      maxLength: 1000
    ObjectTypeName:
      type: string
      minLength: 1
      maxLength: 255
    ProfileId:
      type: string
      pattern: ^[a-f0-9]{32}$
    ProfileOutboundRequestFailureCode:
      type: string
      enum:
      - UnknownError
      - ResourceNotFound
      - Conflict
      - RequestThrottled
      - InvalidInput
    ProfileOutboundRequestId:
      type: string
      pattern: ^[a-zA-Z0-9_\-.]*$
      minLength: 0
      maxLength: 256
    QueueId:
      type: string
      maxLength: 500
    RestrictedPeriodName:
      type: string
      minLength: 1
      maxLength: 127
    ServiceLinkedRoleArn:
      type: string
      maxLength: 256
    SourcePhoneNumber:
      type: string
      maxLength: 100
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TimeZone:
      type: string
      pattern: ^[a-zA-Z0-9_\-/]*$
      minLength: 0
      maxLength: 50
    XAmazonErrorType:
      type: string
