openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: controltower
  x-aws-serviceName: controltower
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: AWS Control Tower
  description: "Amazon Web Services Control Tower offers application programming interface\
    \ (API) operations that support programmatic interaction with these types of resources:\n\
    \n  * [ _Controls_ ](https://docs.aws.amazon.com/controltower/latest/userguide/controls.html)\n\
    \n    * [DisableControl](https://docs.aws.amazon.com/controltower/latest/APIReference/API_DisableControl.html)\n\
    \n    * [EnableControl](https://docs.aws.amazon.com/controltower/latest/APIReference/API_EnableControl.html)\n\
    \n    * [GetEnabledControl](https://docs.aws.amazon.com/controltower/latest/APIReference/API_GetEnabledControl.html)\n\
    \n    * [ListControlOperations](https://docs.aws.amazon.com/controltower/latest/APIReference/API_ListControlOperations.html)\n\
    \n    * [ListEnabledControls](https://docs.aws.amazon.com/controltower/latest/APIReference/API_ListEnabledControls.html)\n\
    \n    * [UpdateEnabledControl](https://docs.aws.amazon.com/controltower/latest/APIReference/API_UpdateEnabledControl.html)\n\
    \n  * [ _Landing zones_ ](https://docs.aws.amazon.com/controltower/latest/userguide/lz-api-launch.html)\n\
    \n    * [CreateLandingZone](https://docs.aws.amazon.com/controltower/latest/APIReference/API_CreateLandingZone.html)\n\
    \n    * [DeleteLandingZone](https://docs.aws.amazon.com/controltower/latest/APIReference/API_DeleteLandingZone.html)\n\
    \n    * [GetLandingZone](https://docs.aws.amazon.com/controltower/latest/APIReference/API_GetLandingZone.html)\n\
    \n    * [GetLandingZoneOperation](https://docs.aws.amazon.com/controltower/latest/APIReference/API_GetLandingZoneOperation.html)\n\
    \n    * [ListLandingZones](https://docs.aws.amazon.com/controltower/latest/APIReference/API_ListLandingZones.html)\n\
    \n    * [ListLandingZoneOperations](https://docs.aws.amazon.com/controltower/latest/APIReference/API_ListLandingZoneOperations.html)\n\
    \n    * [ResetLandingZone](https://docs.aws.amazon.com/controltower/latest/APIReference/API_ResetLandingZone.html)\n\
    \n    * [UpdateLandingZone](https://docs.aws.amazon.com/controltower/latest/APIReference/API_UpdateLandingZone.html)\n\
    \n  * [ _Baselines_ ](https://docs.aws.amazon.com/controltower/latest/userguide/types-of-baselines.html)\n\
    \n    * [DisableBaseline](https://docs.aws.amazon.com/controltower/latest/APIReference/API_DisableBaseline.html)\n\
    \n    * [EnableBaseline](https://docs.aws.amazon.com/controltower/latest/APIReference/API_EnableBaseline.html)\n\
    \n    * [GetBaseline](https://docs.aws.amazon.com/controltower/latest/APIReference/API_GetBaseline.html)\n\
    \n    * [GetBaselineOperation](https://docs.aws.amazon.com/controltower/latest/APIReference/API_GetBaselineOperation.html)\n\
    \n    * [GetEnabledBaseline](https://docs.aws.amazon.com/controltower/latest/APIReference/API_GetEnabledBaseline.html)\n\
    \n    * [ListBaselines](https://docs.aws.amazon.com/controltower/latest/APIReference/API_ListBaselines.html)\n\
    \n    * [ListEnabledBaselines](https://docs.aws.amazon.com/controltower/latest/APIReference/API_ListEnabledBaselines.html)\n\
    \n    * [ResetEnabledBaseline](https://docs.aws.amazon.com/controltower/latest/APIReference/API_ResetEnabledBaseline.html)\n\
    \n    * [UpdateEnabledBaseline](https://docs.aws.amazon.com/controltower/latest/APIReference/API_UpdateEnabledBaseline.html)\n\
    \n  * [ _Tagging_ ](https://docs.aws.amazon.com/controltower/latest/controlreference/tagging.html)\n\
    \n    * [ListTagsForResource](https://docs.aws.amazon.com/controltower/latest/APIReference/API_ListTagsForResource.html)\n\
    \n    * [TagResource](https://docs.aws.amazon.com/controltower/latest/APIReference/API_TagResource.html)\n\
    \n    * [UntagResource](https://docs.aws.amazon.com/controltower/latest/APIReference/API_UntagResource.html)\n\
    \nFor more information about these types of resources, see the [ _Amazon Web Services\
    \ Control Tower User Guide_ ](https://docs.aws.amazon.com/controltower/latest/userguide/what-is-control-tower.html).\n\
    \n**About control APIs**\n\nThese interfaces allow you to apply the Amazon Web\
    \ Services library of pre-defined _controls_ to your organizational units, programmatically.\
    \ In Amazon Web Services Control Tower, the terms \"control\" and \"guardrail\"\
    \ are synonyms.\n\nTo call these APIs, you'll need to know:\n\n  * the `controlIdentifier`\
    \ for the control--or guardrail--you are targeting.\n\n  * the ARN associated\
    \ with the target organizational unit (OU), which we call the `targetIdentifier`.\n\
    \n  * the ARN associated with a resource that you wish to tag or untag.\n\n**To\
    \ get the`controlIdentifier` for your Amazon Web Services Control Tower control:**\n\
    \nThe `controlIdentifier` is an ARN that is specified for each control. You can\
    \ view the `controlIdentifier` in the console on the **Control details** page,\
    \ as well as in the documentation.\n\n**About identifiers for Amazon Web Services\
    \ Control Tower**\n\nThe Amazon Web Services Control Tower `controlIdentifier`\
    \ is unique in each Amazon Web Services Region for each control. You can find\
    \ the `controlIdentifier` for each Region and control in the [Tables of control\
    \ metadata](https://docs.aws.amazon.com/controltower/latest/controlreference/control-metadata-tables.html)\
    \ or the [Control availability by Region tables](https://docs.aws.amazon.com/controltower/latest/controlreference/control-region-tables.html)\
    \ in the _Amazon Web Services Control Tower Controls Reference Guide_.\n\nA quick-reference\
    \ list of control identifers for the Amazon Web Services Control Tower legacy\
    \ _Strongly recommended_ and _Elective_ controls is given in [Resource identifiers\
    \ for APIs and controls](https://docs.aws.amazon.com/controltower/latest/controlreference/control-identifiers.html.html)\
    \ in the [ _Amazon Web Services Control Tower Controls Reference Guide_ ](https://docs.aws.amazon.com/controltower/latest/controlreference/control-identifiers.html).\
    \ Remember that _Mandatory_ controls cannot be added or removed.\n\n**Some controls\
    \ have two identifiers**\n\n  * **ARN format for Amazon Web Services Control Tower:**\
    \ `arn:aws:controltower:{REGION}::control/{CONTROL_TOWER_OPAQUE_ID}`\n\n**Example:**\n\
    \n`arn:aws:controltower:us-west-2::control/AWS-GR_AUTOSCALING_LAUNCH_CONFIG_PUBLIC_IP_DISABLED`\n\
    \n  * **ARN format for Amazon Web Services Control Catalog:** `arn:{PARTITION}:controlcatalog:::control/{CONTROL_CATALOG_OPAQUE_ID}`\n\
    \nYou can find the `{CONTROL_CATALOG_OPAQUE_ID}` in the [ _Amazon Web Services\
    \ Control Tower Controls Reference Guide_ ](https://docs.aws.amazon.com/controltower/latest/controlreference/all-global-identifiers.html),\
    \ or in the Amazon Web Services Control Tower console, on the **Control details**\
    \ page.\n\nThe Amazon Web Services Control Tower APIs for enabled controls, such\
    \ as `GetEnabledControl` and `ListEnabledControls` always return an ARN of the\
    \ same type given when the control was enabled.\n\n**To get the`targetIdentifier`:**\n\
    \nThe `targetIdentifier` is the ARN for an OU.\n\nIn the Amazon Web Services Organizations\
    \ console, you can find the ARN for the OU on the **Organizational unit details**\
    \ page associated with that OU.\n\n**OU ARN format:**\n\n`arn:${Partition}:organizations::${MasterAccountId}:ou/o-${OrganizationId}/ou-${OrganizationalUnitId}`\n\
    \n**About landing zone APIs**\n\nYou can configure and launch an Amazon Web Services\
    \ Control Tower landing zone with APIs. For an introduction and steps, see [Getting\
    \ started with Amazon Web Services Control Tower using APIs](https://docs.aws.amazon.com/controltower/latest/userguide/getting-started-apis.html).\n\
    \nFor an overview of landing zone API operations, see [ Amazon Web Services Control\
    \ Tower supports landing zone APIs](https://docs.aws.amazon.com/controltower/latest/userguide/2023-all.html#landing-zone-apis).\
    \ The individual API operations for landing zones are detailed in this document,\
    \ the [API reference manual](https://docs.aws.amazon.com/controltower/latest/APIReference/API_Operations.html),\
    \ in the \"Actions\" section.\n\n**About baseline APIs**\n\nYou can apply the\
    \ `AWSControlTowerBaseline` baseline to an organizational unit (OU) as a way to\
    \ register the OU with Amazon Web Services Control Tower, programmatically. For\
    \ a general overview of this capability, see [Amazon Web Services Control Tower\
    \ supports APIs for OU registration and configuration with baselines](https://docs.aws.amazon.com/controltower/latest/userguide/2024-all.html#baseline-apis).\n\
    \nYou can call the baseline API operations to view the baselines that Amazon Web\
    \ Services Control Tower enables for your landing zone, on your behalf, when setting\
    \ up the landing zone. These baselines are read-only baselines.\n\nThe individual\
    \ API operations for baselines are detailed in this document, the [API reference\
    \ manual](https://docs.aws.amazon.com/controltower/latest/APIReference/API_Operations.html),\
    \ in the \"Actions\" section. For usage examples, see [Baseline API input and\
    \ output examples with CLI](https://docs.aws.amazon.com/controltower/latest/userguide/baseline-api-examples.html).\n\
    \n**About Amazon Web Services Control Catalog identifiers**\n\n  * The `EnableControl`\
    \ and `DisableControl` API operations can be called by specifying either the Amazon\
    \ Web Services Control Tower identifer or the Amazon Web Services Control Catalog\
    \ identifier. The API response returns the same type of identifier that you specified\
    \ when calling the API.\n\n  * If you use an Amazon Web Services Control Tower\
    \ identifier to call the `EnableControl` API, and then call `EnableControl` again\
    \ with an Amazon Web Services Control Catalog identifier, Amazon Web Services\
    \ Control Tower returns an error message stating that the control is already enabled.\
    \ Similar behavior applies to the `DisableControl` API operation. \n\n  * Mandatory\
    \ controls and the landing-zone-level Region deny control have Amazon Web Services\
    \ Control Tower identifiers only.\n\n**Details and examples**\n\n  * [Control\
    \ API input and output examples with CLI](https://docs.aws.amazon.com/controltower/latest/controlreference/control-api-examples-short.html)\n\
    \n  * [Baseline API input and output examples with CLI](https://docs.aws.amazon.com/controltower/latest/userguide/baseline-api-examples.html)\n\
    \n  * [Enable controls with CloudFormation](https://docs.aws.amazon.com/controltower/latest/controlreference/enable-controls.html)\n\
    \n  * [Launch a landing zone with CloudFormation](https://docs.aws.amazon.com/controltower/latest/userguide/lz-apis-cfn-setup.html)\n\
    \n  * [Control metadata tables (large page)](https://docs.aws.amazon.com/controltower/latest/controlreference/control-metadata-tables.html)\n\
    \n  * [Control availability by Region tables (large page)](https://docs.aws.amazon.com/controltower/latest/controlreference/control-region-tables.html)\n\
    \n  * [List of identifiers for legacy controls](https://docs.aws.amazon.com/controltower/latest/controlreference/control-identifiers.html)\n\
    \n  * [Controls reference guide](https://docs.aws.amazon.com/controltower/latest/controlreference/controls.html)\n\
    \n  * [Controls library groupings](https://docs.aws.amazon.com/controltower/latest/controlreference/controls-reference.html)\n\
    \n  * [Creating Amazon Web Services Control Tower resources with Amazon Web Services\
    \ CloudFormation](https://docs.aws.amazon.com/controltower/latest/userguide/creating-resources-with-cloudformation.html)\n\
    \nTo view the open source resource repository on GitHub, see [aws-cloudformation/aws-cloudformation-resource-providers-controltower](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-controltower)\n\
    \n**Recording API Requests**\n\nAmazon Web Services Control Tower supports Amazon\
    \ Web Services CloudTrail, a service that records Amazon Web Services API calls\
    \ for your Amazon Web Services account and delivers log files to an Amazon S3\
    \ bucket. By using information collected by CloudTrail, you can determine which\
    \ requests the Amazon Web Services Control Tower service received, who made the\
    \ request and when, and so on. For more about Amazon Web Services Control Tower\
    \ and its support for CloudTrail, see [Logging Amazon Web Services Control Tower\
    \ Actions with Amazon Web Services CloudTrail](https://docs.aws.amazon.com/controltower/latest/userguide/logging-using-cloudtrail.html)\
    \ in the Amazon Web Services Control Tower User Guide. To learn more about CloudTrail,\
    \ including how to turn it on and find your log files, see the Amazon Web Services\
    \ CloudTrail User Guide."
servers:
- description: The AWS Control Tower regional endpoint
  url: https://controltower.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas: {}
