openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: controlcatalog
  x-aws-serviceName: controlcatalog
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: AWS Control Catalog
  description: |-
    Welcome to the Amazon Web Services Control Catalog API reference. This guide is for developers who need detailed information about how to programmatically identify and filter the common controls and related metadata that are available to Amazon Web Services customers. This API reference provides descriptions, syntax, and usage examples for each of the actions and data types that are supported by Amazon Web Services Control Catalog.

    Use the following links to get started with the Amazon Web Services Control Catalog API:

      * [Actions](https://docs.aws.amazon.com/controlcatalog/latest/APIReference/API_Operations.html): An alphabetical list of all Control Catalog API operations.

      * [Data types](https://docs.aws.amazon.com/controlcatalog/latest/APIReference/API_Types.html): An alphabetical list of all Control Catalog data types.

      * [Common parameters](https://docs.aws.amazon.com/controlcatalog/latest/APIReference/CommonParameters.html): Parameters that all operations can use.

      * [Common errors](https://docs.aws.amazon.com/controlcatalog/latest/APIReference/CommonErrors.html): Client and server errors that all operations can return.
servers:
- description: The AWS Control Catalog regional endpoint
  url: https://controlcatalog.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    CommonControlArn:
      type: string
      pattern: ^arn:(aws(?:[-a-z]*)?):controlcatalog:::common-control/[0-9a-z]+$
      minLength: 41
      maxLength: 2048
    ControlArn:
      type: string
      pattern: ^arn:(aws(?:[-a-z]*)?):(controlcatalog|controltower):[a-zA-Z0-9-]*::control/[0-9a-zA-Z_\-]+$
      minLength: 34
      maxLength: 2048
    DomainArn:
      type: string
      pattern: ^arn:(aws(?:[-a-z]*)?):controlcatalog:::domain/[0-9a-z]+$
      minLength: 33
      maxLength: 2048
    ImplementationIdentifier:
      type: string
      pattern: ^[a-z0-9-]+$
      minLength: 1
      maxLength: 256
    ImplementationType:
      type: string
      pattern: ^[A-Za-z0-9]+(::[A-Za-z0-9_]+){2,3}$
      minLength: 7
      maxLength: 2048
    MaxListCommonControlsResults:
      type: integer
      minimum: 1
      maximum: 100
    MaxListControlsResults:
      type: integer
      minimum: 1
      maximum: 100
    MaxListDomainsResults:
      type: integer
      minimum: 1
      maximum: 100
    MaxListObjectivesResults:
      type: integer
      minimum: 1
      maximum: 100
    ObjectiveArn:
      type: string
      pattern: ^arn:(aws(?:[-a-z]*)?):controlcatalog:::objective/[0-9a-z]+$
      minLength: 36
      maxLength: 2048
    PaginationToken:
      type: string
      maxLength: 1024
    RegionCode:
      type: string
      pattern: ^[a-zA-Z0-9-]{1,128}$
