openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: customer_profiles
  x-aws-serviceName: customerprofiles
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-08-15'
  title: Amazon Connect Customer Profiles
  description: |-
    Amazon Connect Customer Profiles

      * [Customer Profiles actions](https://docs.aws.amazon.com/connect/latest/APIReference/API_Operations_Amazon_Connect_Customer_Profiles.html)

      * [Customer Profiles data types](https://docs.aws.amazon.com/connect/latest/APIReference/API_Types_Amazon_Connect_Customer_Profiles.html)

    Amazon Connect Customer Profiles is a unified customer profile for your contact center that has pre-built connectors powered by AppFlow that make it easy to combine customer information from third party applications, such as Salesforce (CRM), ServiceNow (ITSM), and your enterprise resource planning (ERP), with contact history from your Amazon Connect contact center.

    For more information about the Amazon Connect Customer Profiles feature, see [Use Customer Profiles](https://docs.aws.amazon.com/connect/latest/adminguide/customer-profiles.html) in the _Amazon Connect Administrator's Guide_.
servers:
- description: The Amazon Connect Customer Profiles regional endpoint
  url: https://profile.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    BucketName:
      type: string
      pattern: ^\S+$
      minLength: 3
      maxLength: 63
    BucketPrefix:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 512
    ConnectorProfileName:
      type: string
      pattern: ^[\w/!@#+=.-]+$
      minLength: 0
      maxLength: 256
    DatetimeTypeFieldName:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 256
    DestinationField:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 256
    End:
      type: integer
      default: 0
      minimum: 0
      maximum: 366
    FlowDescription:
      type: string
      pattern: ^[\w!@#\-.?,\s]*$
      minLength: 0
      maxLength: 2048
    FlowName:
      type: string
      pattern: ^[a-zA-Z0-9][\w!@#.-]+$
      minLength: 0
      maxLength: 256
    GetSegmentMembershipMessage:
      type: string
    GetSegmentMembershipStatus:
      type: integer
    JobScheduleTime:
      type: string
      pattern: ^([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$
      minLength: 3
      maxLength: 5
    KmsArn:
      type: string
      pattern: '^arn:aws:kms:.*:[0-9]+:'
      minLength: 20
      maxLength: 2048
    MaxAllowedRuleLevelForMatching:
      type: integer
      minimum: 1
      maximum: 15
    MaxAllowedRuleLevelForMerging:
      type: integer
      minimum: 1
      maximum: 15
    MaxSize500:
      type: integer
      minimum: 1
      maximum: 500
    Object:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 512
    ObjectCount:
      type: integer
      minimum: 1
      maximum: 100
    ProfileId:
      type: string
    Property:
      type: string
      pattern: ^.+$
      minLength: 0
      maxLength: 2048
    RoleArn:
      type: string
      pattern: '^arn:aws:iam:.*:[0-9]+:'
      minLength: 0
      maxLength: 512
    RuleLevel:
      type: integer
      minimum: 1
      maximum: 15
    ScheduleExpression:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 256
    SegmentDefinitionArn:
      type: string
      minLength: 1
      maxLength: 255
    Start:
      type: integer
      minimum: 1
      maximum: 366
    StatusCode:
      type: integer
      default: 0
    TagArn:
      type: string
      pattern: ^arn:[a-z0-9]{1,10}:profile$
      minLength: 0
      maxLength: 256
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    Timezone:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 256
    Value:
      type: integer
      minimum: 1
      maximum: 366
    attributeName:
      type: string
      pattern: ^[a-zA-Z0-9_.-]+$
      minLength: 1
      maxLength: 64
    boolean:
      type: boolean
      default: false
    displayName:
      type: string
      pattern: ^[a-zA-Z_][a-zA-Z_0-9-\s]*$
      minLength: 1
      maxLength: 255
    encryptionKey:
      type: string
      minLength: 0
      maxLength: 255
    expirationDaysInteger:
      type: integer
      minimum: 1
      maximum: 1098
    fieldName:
      type: string
      pattern: ^[a-zA-Z0-9_.-]+$
      minLength: 1
      maxLength: 64
    matchesNumber:
      type: integer
      minimum: 0
    maxSize100:
      type: integer
      minimum: 1
      maximum: 100
    maxSize1000:
      type: integer
      minimum: 1
      maximum: 1000
    maxSize24:
      type: integer
      minimum: 1
      maximum: 24
    message:
      type: string
    minSize0:
      type: integer
      minimum: 0
    minSize1:
      type: integer
      minimum: 1
    name:
      type: string
      pattern: ^[a-zA-Z0-9_-]+$
      minLength: 1
      maxLength: 64
    optionalBoolean:
      type: boolean
    s3BucketName:
      type: string
      pattern: ^[a-z0-9.-]+$
      minLength: 3
      maxLength: 63
    s3KeyName:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 1024
    s3KeyNameCustomerOutputConfig:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 800
    sensitiveString0To1000:
      type: string
      minLength: 0
      maxLength: 1000
    sensitiveString0To255:
      type: string
      minLength: 0
      maxLength: 255
    sensitiveString1To1000:
      type: string
      minLength: 1
      maxLength: 1000
    sensitiveString1To255:
      type: string
      minLength: 1
      maxLength: 255
    sensitiveText:
      type: string
      minLength: 1
      maxLength: 1000
    sqsQueueUrl:
      type: string
      minLength: 0
      maxLength: 255
    string0To255:
      type: string
      minLength: 0
      maxLength: 255
    string1To1000:
      type: string
      minLength: 1
      maxLength: 1000
    string1To255:
      type: string
      minLength: 1
      maxLength: 255
    stringTo2048:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 2048
    stringifiedJson:
      type: string
      minLength: 1
      maxLength: 256000
    text:
      type: string
      minLength: 1
      maxLength: 1000
    token:
      type: string
      minLength: 1
      maxLength: 1024
    typeName:
      type: string
      pattern: ^[a-zA-Z_][a-zA-Z_0-9-]*$
      minLength: 1
      maxLength: 255
    uuid:
      type: string
      pattern: ^[a-f0-9]{32}$
