openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: dataexchange
  x-aws-serviceName: dataexchange
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-07-25'
  title: AWS Data Exchange
  description: |-
    AWS Data Exchange is a service that makes it easy for AWS customers to exchange data in the cloud. You can use the AWS Data Exchange APIs to create, update, manage, and access file-based data set in the AWS Cloud.

    As a subscriber, you can view and access the data sets that you have an entitlement to through a subscription. You can use the APIs to download or copy your entitled data sets to Amazon Simple Storage Service (Amazon S3) for use across a variety of AWS analytics and machine learning services.

    As a provider, you can create and manage your data sets that you would like to publish to a product. Being able to package and provide your data sets into products requires a few steps to determine eligibility. For more information, visit the _AWS Data Exchange User Guide_.

    A data set is a collection of data that can be changed or updated over time. Data sets can be updated using revisions, which represent a new version or incremental change to a data set. A revision contains one or more assets. An asset in AWS Data Exchange is a piece of data that can be stored as an Amazon S3 object, Redshift datashare, API Gateway API, AWS Lake Formation data permission, or Amazon S3 data access. The asset can be a structured data file, an image file, or some other data file. Jobs are asynchronous import or export operations used to create or copy assets.
servers:
- description: The AWS Data Exchange regional endpoint
  url: https://dataexchange.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AcceptanceStateFilterValue:
      type: string
      enum:
      - PENDING_RECEIVER_ACCEPTANCE
      - ACCEPTED
    ApiDescription:
      type: string
    Arn:
      type: string
    AssetName:
      type: string
    AssetType:
      type: string
      enum:
      - S3_SNAPSHOT
      - REDSHIFT_DATA_SHARE
      - API_GATEWAY_API
      - S3_DATA_ACCESS
      - LAKE_FORMATION_DATA_PERMISSION
    AwsAccountId:
      type: string
      pattern: /^[\d]{12}$/
      minLength: 12
      maxLength: 12
    ClientToken:
      type: string
      pattern: ^[\x21-\x7E]{1,64}$
      minLength: 1
      maxLength: 64
    Code:
      type: string
      enum:
      - ACCESS_DENIED_EXCEPTION
      - INTERNAL_SERVER_EXCEPTION
      - MALWARE_DETECTED
      - RESOURCE_NOT_FOUND_EXCEPTION
      - SERVICE_QUOTA_EXCEEDED_EXCEPTION
      - VALIDATION_EXCEPTION
      - MALWARE_SCAN_ENCRYPTED_FILE
    DataGrantAcceptanceState:
      type: string
      enum:
      - PENDING_RECEIVER_ACCEPTANCE
      - ACCEPTED
    DataGrantArn:
      type: string
      pattern: ^arn:aws:dataexchange:[\-a-z0-9]*:(\d{12}):data-grants\/[a-zA-Z0-9]{30,40}$
    DataGrantDescription:
      type: string
      minLength: 1
      maxLength: 16384
    DataGrantId:
      type: string
      pattern: ^[a-zA-Z0-9]{30,40}$|^arn:aws:dataexchange:[\-a-z0-9]*:(\d{12}):data-grants\/[a-zA-Z0-9]{30,40}$
    DataGrantName:
      type: string
      minLength: 1
      maxLength: 256
    DatabaseLFTagPolicyPermission:
      type: string
      enum:
      - DESCRIBE
    Description:
      type: string
    ExceptionCause:
      type: string
      enum:
      - InsufficientS3BucketPolicy
      - S3AccessDenied
    GrantDistributionScope:
      type: string
      enum:
      - AWS_ORGANIZATION
      - NONE
    Id:
      type: string
    JobErrorLimitName:
      type: string
      enum:
      - Assets per revision
      - Asset size in GB
      - Amazon Redshift datashare assets per revision
      - AWS Lake Formation data permission assets per revision
      - Amazon S3 data access assets per revision
    JobErrorResourceTypes:
      type: string
      enum:
      - REVISION
      - ASSET
      - DATA_SET
    KmsKeyArn:
      type: string
      minLength: 1
      maxLength: 2048
    LFPermission:
      type: string
      enum:
      - DESCRIBE
      - SELECT
    LFResourceType:
      type: string
      enum:
      - TABLE
      - DATABASE
    LakeFormationDataPermissionType:
      type: string
      enum:
      - LFTagPolicy
    LimitName:
      type: string
      enum:
      - Products per account
      - Data sets per account
      - Data sets per product
      - Revisions per data set
      - Assets per revision
      - Assets per import job from Amazon S3
      - Asset per export job from Amazon S3
      - Asset size in GB
      - Concurrent in progress jobs to export assets to Amazon S3
      - Concurrent in progress jobs to export assets to a signed URL
      - Concurrent in progress jobs to import assets from Amazon S3
      - Concurrent in progress jobs to import assets from a signed URL
      - Concurrent in progress jobs to export revisions to Amazon S3
      - Event actions per account
      - Auto export event actions per data set
      - Amazon Redshift datashare assets per import job from Redshift
      - Concurrent in progress jobs to import assets from Amazon Redshift datashares
      - Revisions per Amazon Redshift datashare data set
      - Amazon Redshift datashare assets per revision
      - Concurrent in progress jobs to import assets from an API Gateway API
      - Amazon API Gateway API assets per revision
      - Revisions per Amazon API Gateway API data set
      - Concurrent in progress jobs to import assets from an AWS Lake Formation tag
        policy
      - AWS Lake Formation data permission assets per revision
      - Revisions per AWS Lake Formation data permission data set
      - Revisions per Amazon S3 data access data set
      - Amazon S3 data access assets per revision
      - Concurrent in progress jobs to create Amazon S3 data access assets from S3
        buckets
      - Active and pending data grants
      - Pending data grants per consumer
    MaxResults:
      type: integer
      default: 0
      minimum: 1
      maximum: 200
    Name:
      type: string
    NextToken:
      type: string
    NotificationType:
      type: string
      enum:
      - DATA_DELAY
      - DATA_UPDATE
      - DEPRECATION
      - SCHEMA_CHANGE
    Origin:
      type: string
      enum:
      - OWNED
      - ENTITLED
    ProtocolType:
      type: string
      enum:
      - REST
    ReceiverPrincipal:
      type: string
      pattern: ^\d{12}$
    ResourceType:
      type: string
      enum:
      - DATA_SET
      - REVISION
      - ASSET
      - JOB
      - EVENT_ACTION
      - DATA_GRANT
    RoleArn:
      type: string
      pattern: ^arn:aws:iam::(\d{12}):role\/.+$
    SchemaChangeType:
      type: string
      enum:
      - ADD
      - REMOVE
      - MODIFY
    SenderPrincipal:
      type: string
      pattern: ^\d{12}$
    ServerSideEncryptionTypes:
      type: string
      enum:
      - aws:kms
      - AES256
    State:
      type: string
      enum:
      - WAITING
      - IN_PROGRESS
      - ERROR
      - COMPLETED
      - CANCELLED
      - TIMED_OUT
    TableTagPolicyLFPermission:
      type: string
      enum:
      - DESCRIBE
      - SELECT
    Type:
      type: string
      enum:
      - IMPORT_ASSETS_FROM_S3
      - IMPORT_ASSET_FROM_SIGNED_URL
      - EXPORT_ASSETS_TO_S3
      - EXPORT_ASSET_TO_SIGNED_URL
      - EXPORT_REVISIONS_TO_S3
      - IMPORT_ASSETS_FROM_REDSHIFT_DATA_SHARES
      - IMPORT_ASSET_FROM_API_GATEWAY_API
      - CREATE_S3_DATA_ACCESS_FROM_S3_BUCKET
      - IMPORT_ASSETS_FROM_LAKE_FORMATION_TAG_POLICY
    __boolean:
      type: boolean
      default: false
    __string:
      type: string
    __stringMin0Max16384:
      type: string
      minLength: 0
      maxLength: 16384
    __stringMin0Max4096:
      type: string
      minLength: 0
      maxLength: 4096
    __stringMin10Max512:
      type: string
      minLength: 10
      maxLength: 512
    __stringMin24Max24PatternAZaZ094AZaZ092AZaZ093:
      type: string
      pattern: ^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
      minLength: 24
      maxLength: 24
