openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: databrew
  x-aws-serviceName: databrew
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-07-25'
  title: AWS Glue DataBrew
  description: |-
    Glue DataBrew is a visual, cloud-scale data-preparation service. DataBrew simplifies data preparation tasks, targeting data issues that are hard to spot and time-consuming to fix. DataBrew empowers users of all technical levels to visualize the data and perform one-click data transformations, with no coding required.
servers:
- description: The AWS Glue DataBrew regional endpoint
  url: https://databrew.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccountId:
      type: string
      minLength: 0
      maxLength: 255
    ActionId:
      type: integer
    AllowedStatisticList:
      type: array
      items:
        $ref: '#/components/schemas/AllowedStatistics'
    AnalyticsMode:
      type: string
      enum:
      - ENABLE
      - DISABLE
    Arn:
      type: string
      minLength: 20
      maxLength: 2048
    AssumeControl:
      type: boolean
      default: false
    Attempt:
      type: integer
      default: 0
    Bucket:
      type: string
      minLength: 3
      maxLength: 63
    BucketOwner:
      type: string
      pattern: ^[0-9]{12}$
      minLength: 12
      maxLength: 12
    CatalogId:
      type: string
      minLength: 1
      maxLength: 255
    ClientSessionId:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
      minLength: 1
      maxLength: 255
    ColumnName:
      type: string
      minLength: 1
      maxLength: 255
    ColumnNameList:
      type: array
      items:
        $ref: '#/components/schemas/ColumnName'
    ColumnRange:
      type: integer
      minimum: 0
      maximum: 20
    ColumnSelectorList:
      type: array
      items:
        $ref: '#/components/schemas/ColumnSelector'
    ColumnStatisticsConfigurationList:
      type: array
      items:
        $ref: '#/components/schemas/ColumnStatisticsConfiguration'
    CompressionFormat:
      type: string
      enum:
      - GZIP
      - LZ4
      - SNAPPY
      - BZIP2
      - DEFLATE
      - LZO
      - BROTLI
      - ZSTD
      - ZLIB
    Condition:
      type: string
      pattern: ^[A-Z\_]+$
      minLength: 1
      maxLength: 128
    ConditionExpressionList:
      type: array
      items:
        $ref: '#/components/schemas/ConditionExpression'
    ConditionValue:
      type: string
      minLength: 0
      maxLength: 1024
    CreateColumn:
      type: boolean
      default: false
    CreatedBy:
      type: string
    CronExpression:
      type: string
      minLength: 1
      maxLength: 512
    DataCatalogOutputList:
      type: array
      items:
        $ref: '#/components/schemas/DataCatalogOutput'
    DatabaseName:
      type: string
      minLength: 1
      maxLength: 255
    DatabaseOutputList:
      type: array
      items:
        $ref: '#/components/schemas/DatabaseOutput'
    DatabaseOutputMode:
      type: string
      enum:
      - NEW_TABLE
    DatabaseTableName:
      type: string
      minLength: 1
      maxLength: 255
    DatasetList:
      type: array
      items:
        $ref: '#/components/schemas/Dataset'
    DatasetName:
      type: string
      minLength: 1
      maxLength: 255
    Date:
      type: string
      format: date-time
    DatetimeFormat:
      type: string
      minLength: 2
      maxLength: 100
    Delimiter:
      type: string
      minLength: 1
      maxLength: 1
    Disabled:
      type: boolean
      default: false
    EncryptionKeyArn:
      type: string
      minLength: 20
      maxLength: 2048
    EncryptionMode:
      type: string
      enum:
      - SSE-KMS
      - SSE-S3
    EntityType:
      type: string
      pattern: ^[A-Z_][A-Z\\d_]*$
      minLength: 1
      maxLength: 128
    EntityTypeList:
      type: array
      items:
        $ref: '#/components/schemas/EntityType'
    ErrorCode:
      type: string
      pattern: ^[1-5][0-9][0-9]$
    ExecutionTime:
      type: integer
      default: 0
    Expression:
      type: string
      pattern: ^[<>0-9A-Za-z_.,:)(!= ]+$
      minLength: 4
      maxLength: 1024
    GlueConnectionName:
      type: string
      minLength: 1
      maxLength: 255
    HeaderRow:
      type: boolean
    HiddenColumnList:
      type: array
      items:
        $ref: '#/components/schemas/ColumnName'
    InputFormat:
      type: string
      enum:
      - CSV
      - JSON
      - PARQUET
      - EXCEL
      - ORC
    JobList:
      type: array
      items:
        $ref: '#/components/schemas/Job'
    JobName:
      type: string
      minLength: 1
      maxLength: 240
    JobNameList:
      type: array
      items:
        $ref: '#/components/schemas/JobName'
    JobRunErrorMessage:
      type: string
    JobRunId:
      type: string
      minLength: 1
      maxLength: 255
    JobRunList:
      type: array
      items:
        $ref: '#/components/schemas/JobRun'
    JobRunState:
      type: string
      enum:
      - STARTING
      - RUNNING
      - STOPPING
      - STOPPED
      - SUCCEEDED
      - FAILED
      - TIMEOUT
    JobSize:
      type: integer
      format: int64
    JobType:
      type: string
      enum:
      - PROFILE
      - RECIPE
    Key:
      type: string
      minLength: 1
      maxLength: 1280
    LastModifiedBy:
      type: string
    LocaleCode:
      type: string
      pattern: ^[A-Za-z0-9_\.#@\-]+$
      minLength: 2
      maxLength: 100
    LogGroupName:
      type: string
      minLength: 1
      maxLength: 512
    LogSubscription:
      type: string
      enum:
      - ENABLE
      - DISABLE
    MaxCapacity:
      type: integer
      default: 0
    MaxFiles:
      type: integer
      minimum: 1
    MaxOutputFiles:
      type: integer
      minimum: 1
      maximum: 999
    MaxResults100:
      type: integer
      minimum: 1
      maximum: 100
    MaxRetries:
      type: integer
      default: 0
      minimum: 0
    Message:
      type: string
    MultiLine:
      type: boolean
      default: false
    NextToken:
      type: string
      minLength: 1
      maxLength: 2000
    OpenedBy:
      type: string
    Operation:
      type: string
      pattern: ^[A-Z\_]+$
      minLength: 1
      maxLength: 128
    Order:
      type: string
      enum:
      - DESCENDING
      - ASCENDING
    OrderedBy:
      type: string
      enum:
      - LAST_MODIFIED_DATE
    OutputFormat:
      type: string
      enum:
      - CSV
      - JSON
      - PARQUET
      - GLUEPARQUET
      - AVRO
      - ORC
      - XML
      - TABLEAUHYPER
    OutputList:
      type: array
      items:
        $ref: '#/components/schemas/Output'
    OverwriteOutput:
      type: boolean
      default: false
    ParameterMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ParameterValue'
    ParameterName:
      type: string
      pattern: ^[A-Za-z0-9]+$
      minLength: 1
      maxLength: 128
    ParameterType:
      type: string
      enum:
      - Datetime
      - Number
      - String
    ParameterValue:
      type: string
      minLength: 1
      maxLength: 32768
    PathParameterName:
      type: string
      minLength: 1
      maxLength: 255
    PathParametersMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/DatasetParameter'
      description: "<p>A structure that map names of parameters used in the Amazon\
        \ S3 path of a dataset to their definitions. \n            A definition includes\
        \ parameter type and conditions.</p>"
    Preview:
      type: boolean
      default: false
    ProjectList:
      type: array
      items:
        $ref: '#/components/schemas/Project'
    ProjectName:
      type: string
      minLength: 1
      maxLength: 255
    PublishedBy:
      type: string
    QueryString:
      type: string
      minLength: 1
      maxLength: 10000
    RecipeDescription:
      type: string
      minLength: 0
      maxLength: 1024
    RecipeErrorList:
      type: array
      items:
        $ref: '#/components/schemas/RecipeVersionErrorDetail'
    RecipeErrorMessage:
      type: string
    RecipeList:
      type: array
      items:
        $ref: '#/components/schemas/Recipe'
    RecipeName:
      type: string
      minLength: 1
      maxLength: 255
    RecipeStepList:
      type: array
      items:
        $ref: '#/components/schemas/RecipeStep'
    RecipeVersion:
      type: string
      minLength: 1
      maxLength: 16
    RecipeVersionList:
      type: array
      items:
        $ref: '#/components/schemas/RecipeVersion'
    Result:
      type: string
    RowRange:
      type: integer
    RuleCount:
      type: integer
      default: 0
      minimum: 0
    RuleList:
      type: array
      items:
        $ref: '#/components/schemas/Rule'
    RuleName:
      type: string
      minLength: 1
      maxLength: 128
    RulesetDescription:
      type: string
      minLength: 0
      maxLength: 1024
    RulesetItemList:
      type: array
      items:
        $ref: '#/components/schemas/RulesetItem'
    RulesetName:
      type: string
      minLength: 1
      maxLength: 255
    SampleMode:
      type: string
      enum:
      - FULL_DATASET
      - CUSTOM_ROWS
    SampleSize:
      type: integer
      minimum: 1
      maximum: 5000
    SampleType:
      type: string
      enum:
      - FIRST_N
      - LAST_N
      - RANDOM
    ScheduleList:
      type: array
      items:
        $ref: '#/components/schemas/Schedule'
    ScheduleName:
      type: string
      minLength: 1
      maxLength: 255
    SessionStatus:
      type: string
      enum:
      - ASSIGNED
      - FAILED
      - INITIALIZING
      - PROVISIONING
      - READY
      - RECYCLING
      - ROTATING
      - TERMINATED
      - TERMINATING
      - UPDATING
    SheetIndex:
      type: integer
      minimum: 0
      maximum: 200
    SheetIndexList:
      type: array
      items:
        $ref: '#/components/schemas/SheetIndex'
    SheetName:
      type: string
      minLength: 1
      maxLength: 31
    SheetNameList:
      type: array
      items:
        $ref: '#/components/schemas/SheetName'
    Source:
      type: string
      enum:
      - S3
      - DATA-CATALOG
      - DATABASE
    StartColumnIndex:
      type: integer
      minimum: 0
    StartRowIndex:
      type: integer
      minimum: 0
    StartedBy:
      type: string
    Statistic:
      type: string
      pattern: ^[A-Z\_]+$
      minLength: 1
      maxLength: 128
    StatisticList:
      type: array
      items:
        $ref: '#/components/schemas/Statistic'
    StatisticOverrideList:
      type: array
      items:
        $ref: '#/components/schemas/StatisticOverride'
    StepIndex:
      type: integer
      minimum: 0
    TableName:
      type: string
      minLength: 1
      maxLength: 255
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TargetColumn:
      type: string
      minLength: 1
      maxLength: 1024
    ThresholdType:
      type: string
      enum:
      - GREATER_THAN_OR_EQUAL
      - LESS_THAN_OR_EQUAL
      - GREATER_THAN
      - LESS_THAN
    ThresholdUnit:
      type: string
      enum:
      - COUNT
      - PERCENTAGE
    ThresholdValue:
      type: number
      format: double
      default: 0
      minimum: 0
    Timeout:
      type: integer
      default: 0
      minimum: 0
    TimezoneOffset:
      type: string
      pattern: ^(Z|[-+](\d|\d{2}|\d{2}:?\d{2}))$
      minLength: 1
      maxLength: 6
    ValidationConfigurationList:
      type: array
      items:
        $ref: '#/components/schemas/ValidationConfiguration'
    ValidationMode:
      type: string
      enum:
      - CHECK_ALL
    ValueReference:
      type: string
      pattern: ^:[A-Za-z0-9_]+$
      minLength: 2
      maxLength: 128
    ValuesMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ConditionValue'
