openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: datazone
  x-aws-serviceName: datazone
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: Amazon DataZone
  description: |-
    Amazon DataZone is a data management service that enables you to catalog, discover, govern, share, and analyze your data. With Amazon DataZone, you can share and access your data across accounts and supported regions. Amazon DataZone simplifies your experience across Amazon Web Services services, including, but not limited to, Amazon Redshift, Amazon Athena, Amazon Web Services Glue, and Amazon Web Services Lake Formation.
servers:
- description: The Amazon DataZone regional endpoint
  url: https://datazone.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ActionLink:
      type: string
    AssetId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    AssetIdentifier:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    AssetName:
      type: string
      minLength: 1
      maxLength: 256
    AssetTypeIdentifier:
      type: string
      pattern: ^(?!\.)[\w\.]*\w$
      minLength: 1
      maxLength: 513
    Attribute:
      type: string
      minLength: 1
      maxLength: 128
    AuthorizedPrincipalIdentifier:
      type: string
      pattern: ^[a-zA-Z0-9:/._-]*$
    AwsAccountId:
      type: string
      pattern: ^\d{12}$
    AwsRegion:
      type: string
      pattern: ^[a-z]{2}-[a-z]{4,10}-\d$
    ClientToken:
      type: string
      pattern: ^[\x21-\x7E]+$
      minLength: 1
      maxLength: 128
    ConnectionId:
      type: string
      maxLength: 128
    ConnectionName:
      type: string
      maxLength: 64
    CreatedBy:
      type: string
    CronString:
      type: string
      pattern: cron\((\b[0-5]?[0-9]\b) (\b2[0-3]\b|\b[0-1]?[0-9]\b) ([-?*,/\dLW]){1,83}
        ([-*,/\d]|[a-zA-Z]{3}){1,23} ([-?#*,/\dL]|[a-zA-Z]{3}){1,13} ([^\)]+)\)
      minLength: 1
      maxLength: 256
    DataPointIdentifier:
      type: string
      pattern: ^[a-zA-Z0-9_-]{0,36}$
    DataProductDescription:
      type: string
      minLength: 1
      maxLength: 4096
    DataProductId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    DataProductName:
      type: string
      minLength: 1
      maxLength: 64
    DataSourceId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    DataSourceRunId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    DataSourceType:
      type: string
      minLength: 1
      maxLength: 256
    DecisionComment:
      type: string
      minLength: 1
      maxLength: 4096
    DeploymentMessage:
      type: string
    DeploymentOrder:
      type: integer
      minimum: 0
      maximum: 16
    Description:
      type: string
      maxLength: 2048
    DomainDescription:
      type: string
    DomainId:
      type: string
      pattern: ^dzd[-_][a-zA-Z0-9_-]{1,36}$
    DomainName:
      type: string
    DomainUnitDescription:
      type: string
      maxLength: 2048
    DomainUnitId:
      type: string
      pattern: ^[a-z0-9_\-]+$
      minLength: 1
      maxLength: 256
    DomainUnitName:
      type: string
      pattern: ^[\w -]+$
      minLength: 1
      maxLength: 128
    EditedValue:
      type: string
      minLength: 1
      maxLength: 5000
    EntityId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    EntityIdentifier:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    EnvironmentActionId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    EnvironmentBlueprintId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    EnvironmentBlueprintName:
      type: string
      pattern: ^[\w -]+$
      minLength: 1
      maxLength: 64
    EnvironmentConfigurationId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    EnvironmentConfigurationName:
      type: string
      pattern: ^[\w -]+$
      minLength: 1
      maxLength: 64
    EnvironmentConfigurationParameterName:
      type: string
      pattern: ^[a-zA-Z_][a-zA-Z0-9_]*$
    EnvironmentId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    EnvironmentName:
      type: string
      pattern: ^[\w -]+$
      minLength: 1
      maxLength: 64
    EnvironmentProfileId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{0,36}$
    EnvironmentProfileName:
      type: string
      pattern: ^[\w -]+$
      minLength: 1
      maxLength: 64
    ErrorMessage:
      type: string
    ExternalIdentifier:
      type: string
      minLength: 1
      maxLength: 600
    FilterId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    FilterName:
      type: string
      pattern: ^[\w -]+$
      minLength: 1
      maxLength: 64
    FirstName:
      type: string
    FormName:
      type: string
      pattern: ^(?![0-9_])\w+$|^_\w*[a-zA-Z0-9]\w*$
      minLength: 1
      maxLength: 128
    FormTypeIdentifier:
      type: string
      pattern: ^(?!\.)[\w\.]*\w$
      minLength: 1
      maxLength: 385
    FormTypeName:
      type: string
      pattern: ^(amazon.datazone.)?(?![0-9_])\w+$|^_\w*[a-zA-Z0-9]\w*$
      minLength: 1
      maxLength: 128
    Forms:
      type: string
    GlossaryDescription:
      type: string
      maxLength: 4096
    GlossaryId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    GlossaryName:
      type: string
      minLength: 1
      maxLength: 256
    GlossaryTermId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    GlossaryTermName:
      type: string
      minLength: 1
      maxLength: 256
    GroupIdentifier:
      type: string
      pattern: (^([0-9a-f]{10}-|)[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}$|[\p{L}\p{M}\p{S}\p{N}\p{P}\t\n\r  ]+)
    GroupProfileId:
      type: string
      pattern: ^([0-9a-f]{10}-|)[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}$
    GroupProfileName:
      type: string
      pattern: ^[a-zA-Z_0-9+=,.@-]+$
      minLength: 1
      maxLength: 1024
    GroupSearchText:
      type: string
      minLength: 0
      maxLength: 1024
    IamRoleArn:
      type: string
      pattern: ^arn:aws(|-cn|-us-gov):iam::\d{12}:(role|role/service-role)/[\w+=,.@-]*$
    KmsKeyArn:
      type: string
      pattern: ^arn:aws(|-cn|-us-gov):kms:[a-zA-Z0-9-]*:[0-9]{12}:key/[a-zA-Z0-9-]{36}$
      minLength: 1
      maxLength: 1024
    LastName:
      type: string
    LineageEventErrorMessage:
      type: string
    LineageEventIdentifier:
      type: string
      pattern: ^[a-z0-9]{14}$
    LineageNodeId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    LineageNodeIdentifier:
      type: string
      minLength: 1
      maxLength: 2086
    ListingId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    ListingName:
      type: string
      minLength: 1
      maxLength: 64
    LongDescription:
      type: string
      maxLength: 4096
    MaxResults:
      type: integer
      minimum: 1
      maximum: 50
    MaxResultsForListDomains:
      type: integer
      minimum: 1
      maximum: 25
    Message:
      type: string
      maxLength: 16384
    MetadataGenerationRunIdentifier:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    Name:
      type: string
      minLength: 1
      maxLength: 256
    PaginationToken:
      type: string
      minLength: 1
      maxLength: 8192
    ParameterStorePath:
      type: string
      minLength: 1
      maxLength: 2048
    Password:
      type: string
      maxLength: 64
    PolicyArn:
      type: string
      pattern: ^arn:aws[^:]*:iam::(aws|\d{12}):policy/[\w+=,.@-]*$
    ProjectId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    ProjectName:
      type: string
      pattern: ^[\w -]+$
      minLength: 1
      maxLength: 64
    ProjectProfileId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    ProjectProfileName:
      type: string
      pattern: ^[\w -]+$
      minLength: 1
      maxLength: 64
    RegionName:
      type: string
      pattern: ^[a-z]{2}-?(iso|gov)?-{1}[a-z]*-{1}[0-9]$
      minLength: 4
      maxLength: 16
    RequestReason:
      type: string
      minLength: 1
      maxLength: 4096
    Revision:
      type: string
      minLength: 1
      maxLength: 64
    RevisionInput:
      type: string
      pattern: ^[a-zA-Z0-9_-]+$
      minLength: 1
      maxLength: 64
    RoleArn:
      type: string
      pattern: ^arn:aws[^:]*:iam::\d{12}:(role|role/service-role)/[\w+=,.@-]*$
    RuleId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    RuleName:
      type: string
      pattern: ^[\w -]+$
      minLength: 1
      maxLength: 256
    RunIdentifier:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    S3Location:
      type: string
      pattern: ^s3://.+$
      minLength: 1
      maxLength: 1024
    SageMakerAssetType:
      type: string
      minLength: 1
      maxLength: 64
    SageMakerResourceArn:
      type: string
      pattern: ^arn:aws[^:]*:sagemaker:[a-z]{2}-?(iso|gov)?-{1}[a-z]*-{1}[0-9]:\d{12}:[\w+=,.@-]{1,128}/[\w+=,.@-]{1,256}$
    SearchText:
      type: string
      minLength: 1
      maxLength: 4096
    ShortDescription:
      type: string
      maxLength: 1024
    Smithy:
      type: string
      minLength: 1
      maxLength: 100000
    SubnetId:
      type: string
      pattern: ^subnet-[a-z0-9]+$
      maxLength: 32
    SubscriptionGrantId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    SubscriptionId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    SubscriptionRequestId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    SubscriptionTargetId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    SubscriptionTargetName:
      type: string
      minLength: 1
      maxLength: 256
    TagKey:
      type: string
      pattern: ^[\w \.:/=+@-]+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^[\w \.:/=+@-]*$
      maxLength: 256
    TaskId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    TimeSeriesDataPointIdentifier:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,36}$
    TimeSeriesFormName:
      type: string
      minLength: 1
      maxLength: 128
    Title:
      type: string
      maxLength: 1000
    TypeName:
      type: string
      pattern: ^[^\.]*
      minLength: 1
      maxLength: 256
    UpdatedBy:
      type: string
    UserIdentifier:
      type: string
      pattern: (^([0-9a-f]{10}-|)[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}$|^[a-zA-Z_0-9+=,.@-]+$|^arn:aws:iam::\d{12}:.+$)
    UserProfileId:
      type: string
      pattern: ^([0-9a-f]{10}-|)[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}$
    UserProfileName:
      type: string
      pattern: ^[a-zA-Z_0-9+=,.@-]+$
      minLength: 1
      maxLength: 1024
    UserSearchText:
      type: string
      minLength: 0
      maxLength: 1024
    Username:
      type: string
      maxLength: 64
