openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: databrew
  x-aws-serviceName: databrew
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-07-25'
  title: AWS Glue DataBrew
  description: |-
    Glue DataBrew is a visual, cloud-scale data-preparation service. DataBrew simplifies data preparation tasks, targeting data issues that are hard to spot and time-consuming to fix. DataBrew empowers users of all technical levels to visualize the data and perform one-click data transformations, with no coding required.
servers:
- description: The AWS Glue DataBrew regional endpoint
  url: https://databrew.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccountId:
      type: string
      minLength: 0
      maxLength: 255
    ActionId:
      type: integer
    Arn:
      type: string
      minLength: 20
      maxLength: 2048
    AssumeControl:
      type: boolean
      default: false
    Attempt:
      type: integer
      default: 0
    Bucket:
      type: string
      minLength: 3
      maxLength: 63
    BucketOwner:
      type: string
      pattern: ^[0-9]{12}$
      minLength: 12
      maxLength: 12
    CatalogId:
      type: string
      minLength: 1
      maxLength: 255
    ClientSessionId:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
      minLength: 1
      maxLength: 255
    ColumnName:
      type: string
      minLength: 1
      maxLength: 255
    ColumnRange:
      type: integer
      minimum: 0
      maximum: 20
    Condition:
      type: string
      pattern: ^[A-Z\_]+$
      minLength: 1
      maxLength: 128
    ConditionValue:
      type: string
      minLength: 0
      maxLength: 1024
    CreateColumn:
      type: boolean
      default: false
    CreatedBy:
      type: string
    CronExpression:
      type: string
      minLength: 1
      maxLength: 512
    DatabaseName:
      type: string
      minLength: 1
      maxLength: 255
    DatabaseTableName:
      type: string
      minLength: 1
      maxLength: 255
    DatasetName:
      type: string
      minLength: 1
      maxLength: 255
    DatetimeFormat:
      type: string
      minLength: 2
      maxLength: 100
    Delimiter:
      type: string
      minLength: 1
      maxLength: 1
    Disabled:
      type: boolean
      default: false
    EncryptionKeyArn:
      type: string
      minLength: 20
      maxLength: 2048
    EntityType:
      type: string
      pattern: ^[A-Z_][A-Z\\d_]*$
      minLength: 1
      maxLength: 128
    ErrorCode:
      type: string
      pattern: ^[1-5][0-9][0-9]$
    ExecutionTime:
      type: integer
      default: 0
    Expression:
      type: string
      pattern: ^[<>0-9A-Za-z_.,:)(!= ]+$
      minLength: 4
      maxLength: 1024
    GlueConnectionName:
      type: string
      minLength: 1
      maxLength: 255
    HeaderRow:
      type: boolean
    JobName:
      type: string
      minLength: 1
      maxLength: 240
    JobRunErrorMessage:
      type: string
    JobRunId:
      type: string
      minLength: 1
      maxLength: 255
    Key:
      type: string
      minLength: 1
      maxLength: 1280
    LastModifiedBy:
      type: string
    LocaleCode:
      type: string
      pattern: ^[A-Za-z0-9_\.#@\-]+$
      minLength: 2
      maxLength: 100
    LogGroupName:
      type: string
      minLength: 1
      maxLength: 512
    MaxCapacity:
      type: integer
      default: 0
    MaxFiles:
      type: integer
      minimum: 1
    MaxOutputFiles:
      type: integer
      minimum: 1
      maximum: 999
    MaxResults100:
      type: integer
      minimum: 1
      maximum: 100
    MaxRetries:
      type: integer
      default: 0
      minimum: 0
    Message:
      type: string
    MultiLine:
      type: boolean
      default: false
    NextToken:
      type: string
      minLength: 1
      maxLength: 2000
    OpenedBy:
      type: string
    Operation:
      type: string
      pattern: ^[A-Z\_]+$
      minLength: 1
      maxLength: 128
    OverwriteOutput:
      type: boolean
      default: false
    ParameterName:
      type: string
      pattern: ^[A-Za-z0-9]+$
      minLength: 1
      maxLength: 128
    ParameterValue:
      type: string
      minLength: 1
      maxLength: 32768
    PathParameterName:
      type: string
      minLength: 1
      maxLength: 255
    Preview:
      type: boolean
      default: false
    ProjectName:
      type: string
      minLength: 1
      maxLength: 255
    PublishedBy:
      type: string
    QueryString:
      type: string
      minLength: 1
      maxLength: 10000
    RecipeDescription:
      type: string
      minLength: 0
      maxLength: 1024
    RecipeErrorMessage:
      type: string
    RecipeName:
      type: string
      minLength: 1
      maxLength: 255
    RecipeVersion:
      type: string
      minLength: 1
      maxLength: 16
    Result:
      type: string
    RowRange:
      type: integer
    RuleCount:
      type: integer
      default: 0
      minimum: 0
    RuleName:
      type: string
      minLength: 1
      maxLength: 128
    RulesetDescription:
      type: string
      minLength: 0
      maxLength: 1024
    RulesetName:
      type: string
      minLength: 1
      maxLength: 255
    SampleSize:
      type: integer
      minimum: 1
      maximum: 5000
    ScheduleName:
      type: string
      minLength: 1
      maxLength: 255
    SheetIndex:
      type: integer
      minimum: 0
      maximum: 200
    SheetName:
      type: string
      minLength: 1
      maxLength: 31
    StartColumnIndex:
      type: integer
      minimum: 0
    StartRowIndex:
      type: integer
      minimum: 0
    StartedBy:
      type: string
    Statistic:
      type: string
      pattern: ^[A-Z\_]+$
      minLength: 1
      maxLength: 128
    StepIndex:
      type: integer
      minimum: 0
    TableName:
      type: string
      minLength: 1
      maxLength: 255
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TargetColumn:
      type: string
      minLength: 1
      maxLength: 1024
    Timeout:
      type: integer
      default: 0
      minimum: 0
    TimezoneOffset:
      type: string
      pattern: ^(Z|[-+](\d|\d{2}|\d{2}:?\d{2}))$
      minLength: 1
      maxLength: 6
    ValueReference:
      type: string
      pattern: ^:[A-Za-z0-9_]+$
      minLength: 2
      maxLength: 128
