openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: deadline
  x-aws-serviceName: deadline
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2023-10-12'
  title: AWSDeadlineCloud
  description: |-
    The Amazon Web Services Deadline Cloud API provides infrastructure and centralized management for your projects. Use the Deadline Cloud API to onboard users, assign projects, and attach permissions specific to their job function.

    With Deadline Cloud, content production teams can deploy resources for their workforce securely in the cloud, reducing the costs of added physical infrastructure. Keep your content production operations secure, while allowing your contributors to access the tools they need, such as scalable high-speed storage, licenses, and cost management services.
servers:
- description: The AWSDeadlineCloud regional endpoint
  url: https://deadline.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AcceleratorRuntime:
      type: string
      minLength: 1
      maxLength: 100
    AccessKeyId:
      type: string
    AggregationId:
      type: string
      pattern: ^[0-9a-f]{32}$
    AmountCapabilityName:
      type: string
      pattern: ^([a-zA-Z][a-zA-Z0-9]{0,63}:)?amount(\.[a-zA-Z][a-zA-Z0-9]{0,63})+$
      minLength: 1
      maxLength: 100
    AmountRequirementName:
      type: string
      maxLength: 1024
    AttributeCapabilityName:
      type: string
      pattern: ^([a-zA-Z][a-zA-Z0-9]{0,63}:)?attr(\.[a-zA-Z][a-zA-Z0-9]{0,63})+$
      minLength: 1
      maxLength: 100
    AttributeCapabilityValue:
      type: string
      pattern: ^[a-zA-Z_]([a-zA-Z0-9_\-]{0,99})$
      minLength: 1
      maxLength: 100
    BoundedString:
      type: string
      minLength: 1
      maxLength: 64
    BudgetId:
      type: string
      pattern: ^budget-[0-9a-f]{32}$
    ClientToken:
      type: string
      minLength: 1
      maxLength: 64
    CombinationExpression:
      type: string
      minLength: 1
      maxLength: 1280
    CreatedBy:
      type: string
    Description:
      type: string
      minLength: 0
      maxLength: 100
    DnsName:
      type: string
    EbsIops:
      type: integer
      minimum: 3000
      maximum: 16000
    EbsThroughputMiB:
      type: integer
      minimum: 125
      maximum: 1000
    EnvironmentId:
      type: string
      pattern: ^(STEP:step-[0-9a-f]{32}:.*)|(JOB:job-[0-9a-f]{32}:.*)$
      minLength: 1
      maxLength: 1024
    EnvironmentName:
      type: string
    EnvironmentTemplate:
      type: string
      minLength: 1
      maxLength: 15000
    FarmId:
      type: string
      pattern: ^farm-[0-9a-f]{32}$
    FileSystemLocationName:
      type: string
      pattern: ^[0-9A-Za-z ]*$
      minLength: 1
      maxLength: 64
    FleetId:
      type: string
      pattern: ^fleet-[0-9a-f]{32}$
    FloatString:
      type: string
      pattern: ^[-]?(0|[1-9][0-9]*)([.][0-9]+)?([eE][+-]?[0-9]+)?$
      minLength: 1
      maxLength: 26
    HostName:
      type: string
      pattern: ^[a-zA-Z0-9_\.\-]{0,255}$
    IamRoleArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*):iam::\d{12}:role(/[!-.0-~]+)*/[\w+=,.@-]+$
    IdentityCenterApplicationArn:
      type: string
    IdentityCenterInstanceArn:
      type: string
      pattern: ^arn:(aws|aws-us-gov|aws-cn|aws-iso|aws-iso-b):sso:::instance/(sso)?ins-[a-zA-Z0-9-.]{16}$
    IdentityCenterPrincipalId:
      type: string
      pattern: ^([0-9a-f]{10}-|)[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}$
      minLength: 1
      maxLength: 47
    IdentityStoreId:
      type: string
      pattern: ^d-[0-9a-f]{10}$|^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
      minLength: 1
      maxLength: 36
    InstanceType:
      type: string
      pattern: ^[a-zA-Z0-9]+\.[a-zA-Z0-9]+$
    IntString:
      type: string
      pattern: ^[-]?(0|[1-9][0-9]*)$
      minLength: 1
      maxLength: 20
    Integer:
      type: integer
    IpV4Address:
      type: string
      pattern: ^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$
    IpV6Address:
      type: string
      pattern: ^(?:[A-F0-9]{1,4}:){7}[A-F0-9]{1,4}$
    JobDescription:
      type: string
      minLength: 1
      maxLength: 2048
    JobId:
      type: string
      pattern: ^job-[0-9a-f]{32}$
    JobName:
      type: string
      minLength: 1
      maxLength: 128
    JobPriority:
      type: integer
      minimum: 0
      maximum: 100
    JobTemplate:
      type: string
      minLength: 1
      maxLength: 300000
    KmsKeyArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*):kms:[a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1}:\d{12}:key/[\w-]{1,120}$
    LicenseEndpointId:
      type: string
      pattern: ^le-[0-9a-f]{32}$
    LicenseProduct:
      type: string
    LimitId:
      type: string
      pattern: ^limit-[0-9a-f]{32}$
    LogDriver:
      type: string
      minLength: 1
      maxLength: 512
    LogError:
      type: string
      minLength: 1
      maxLength: 512
    MaxCount:
      type: integer
      minimum: -1
      maximum: 2147483647
    MaxFailedTasksCount:
      type: integer
      minimum: 0
      maximum: 2147483647
    MaxResults:
      type: integer
      default: 100
      minimum: 1
      maximum: 100
    MaxRetriesPerTask:
      type: integer
      minimum: 0
      maximum: 2147483647
    MaxWorkerCount:
      type: integer
      minimum: -1
      maximum: 2147483647
    MemoryAmountMiB:
      type: integer
      minimum: 512
      maximum: 2147483647
    MeteredProductId:
      type: string
      pattern: ^[0-9a-z]{1,32}-[.0-9a-z]{1,32}$
    MinOneMaxInteger:
      type: integer
      minimum: 1
      maximum: 2147483647
    MinOneMaxTenThousand:
      type: integer
      minimum: 1
      maximum: 10000
    MinZeroMaxInteger:
      type: integer
      minimum: 0
      maximum: 2147483647
    MonitorId:
      type: string
      pattern: ^monitor-[0-9a-f]{32}$
    NextItemOffset:
      type: integer
      minimum: 0
      maximum: 10000
    ParameterString:
      type: string
      minLength: 0
      maxLength: 1024
    ParameterValue:
      type: string
      minLength: 1
      maxLength: 256
    PathString:
      type: string
      minLength: 0
      maxLength: 1024
    PortNumber:
      type: integer
      minimum: 1024
      maximum: 65535
    Priority:
      type: integer
      minimum: 0
      maximum: 10000
    ProcessExitCode:
      type: integer
      minimum: -2147483648
      maximum: 2147483647
    QueueEnvironmentId:
      type: string
      pattern: ^queueenv-[0-9a-f]{32}$
    QueueId:
      type: string
      pattern: ^queue-[0-9a-f]{32}$
    ResourceName:
      type: string
      minLength: 1
      maxLength: 100
    S3BucketName:
      type: string
      minLength: 1
      maxLength: 255
    S3Key:
      type: string
      minLength: 1
      maxLength: 1024
    S3Prefix:
      type: string
      pattern: ^[a-zA-Z0-9-_/]+$
      minLength: 1
      maxLength: 63
    SearchTerm:
      type: string
      minLength: 1
      maxLength: 256
    SecretAccessKey:
      type: string
    SecurityGroupId:
      type: string
      pattern: ^sg-[\w]{1,120}$
    SessionActionId:
      type: string
      pattern: ^sessionaction-[0-9a-f]{32}-(0|([1-9][0-9]{0,9}))$
    SessionActionProgressMessage:
      type: string
      minLength: 0
      maxLength: 4096
    SessionId:
      type: string
      pattern: ^session-[0-9a-f]{32}$
    SessionToken:
      type: string
    StatusMessage:
      type: string
      minLength: 0
      maxLength: 1024
    StepDescription:
      type: string
      minLength: 1
      maxLength: 2048
    StepId:
      type: string
      pattern: ^step-[0-9a-f]{32}$
    StepName:
      type: string
      minLength: 1
      maxLength: 64
    StepParameterName:
      type: string
      minLength: 1
      maxLength: 64
    StorageProfileId:
      type: string
      pattern: ^sp-[0-9a-f]{32}$
    String:
      type: string
    StringFilter:
      type: string
      minLength: 1
      maxLength: 256
    Subdomain:
      type: string
      pattern: ^[a-z0-9-]{1,100}$
    SubnetId:
      type: string
      pattern: ^subnet-[\w]{1,120}$
      minLength: 1
      maxLength: 32
    TaskId:
      type: string
      pattern: ^task-[0-9a-f]{32}-(0|([1-9][0-9]{0,9}))$
    TaskRetryCount:
      type: integer
      minimum: 0
      maximum: 2147483647
    Timezone:
      type: string
      pattern: ^UTC[-+][01][0-9]:(30|00)$
      minLength: 9
      maxLength: 9
    TotalResults:
      type: integer
      minimum: 0
      maximum: 10000
    UpdateWorkerScheduleInterval:
      type: integer
      minimum: 0
    UpdatedBy:
      type: string
    Url:
      type: string
    UserId:
      type: string
    VpcId:
      type: string
      pattern: ^vpc-[\w]{1,120}$
      minLength: 1
      maxLength: 32
    WorkerId:
      type: string
      pattern: ^worker-[0-9a-f]{32}$
