openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: detective
  x-aws-serviceName: detective
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-10-26'
  title: Amazon Detective
  description: |-
    Detective uses machine learning and purpose-built visualizations to help you to analyze and investigate security issues across your Amazon Web Services (Amazon Web Services) workloads. Detective automatically extracts time-based events such as login attempts, API calls, and network traffic from CloudTrail and Amazon Virtual Private Cloud (Amazon VPC) flow logs. It also extracts findings detected by Amazon GuardDuty.

    The Detective API primarily supports the creation and management of behavior graphs. A behavior graph contains the extracted data from a set of member accounts, and is created and managed by an administrator account.

    To add a member account to the behavior graph, the administrator account sends an invitation to the account. When the account accepts the invitation, it becomes a member account in the behavior graph.

    Detective is also integrated with Organizations. The organization management account designates the Detective administrator account for the organization. That account becomes the administrator account for the organization behavior graph. The Detective administrator account is also the delegated administrator account for Detective in Organizations.

    The Detective administrator account can enable any organization account as a member account in the organization behavior graph. The organization accounts do not receive invitations. The Detective administrator account can also invite other accounts to the organization behavior graph.

    Every behavior graph is specific to a Region. You can only use the API to manage behavior graphs that belong to the Region that is associated with the currently selected endpoint.

    The administrator account for a behavior graph can use the Detective API to do the following:

      * Enable and disable Detective. Enabling Detective creates a new behavior graph.

      * View the list of member accounts in a behavior graph.

      * Add member accounts to a behavior graph.

      * Remove member accounts from a behavior graph.

      * Apply tags to a behavior graph.

    The organization management account can use the Detective API to select the delegated administrator for Detective.

    The Detective administrator account for an organization can use the Detective API to do the following:

      * Perform all of the functions of an administrator account.

      * Determine whether to automatically enable new organization accounts as member accounts in the organization behavior graph.

    An invited member account can use the Detective API to do the following:

      * View the list of behavior graphs that they are invited to.

      * Accept an invitation to contribute to a behavior graph.

      * Decline an invitation to contribute to a behavior graph.

      * Remove their account from a behavior graph.

    All API actions are logged as CloudTrail events. See [Logging Detective API Calls with CloudTrail](https://docs.aws.amazon.com/detective/latest/userguide/logging-using-cloudtrail.html).

    We replaced the term "master account" with the term "administrator account". An administrator account is used to centrally manage multiple accounts. In the case of Detective, the administrator account manages the accounts in their behavior graph.
servers:
- description: The Amazon Detective regional endpoint
  url: https://api.detective.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    APIFailureCount:
      type: integer
      format: int64
      default: 0
    APIName:
      type: string
    APISuccessCount:
      type: integer
      format: int64
      default: 0
    AccountId:
      type: string
      pattern: ^[0-9]+$
      minLength: 12
      maxLength: 12
    AccountIdExtendedList:
      type: array
      items:
        $ref: '#/components/schemas/AccountId'
    AccountIdList:
      type: array
      items:
        $ref: '#/components/schemas/AccountId'
    AccountList:
      type: array
      items:
        $ref: '#/components/schemas/Account'
    AdministratorList:
      type: array
      items:
        $ref: '#/components/schemas/Administrator'
    AiPaginationToken:
      type: string
      minLength: 1
      maxLength: 2048
    Aso:
      type: string
    Boolean:
      type: boolean
      default: false
    ByteValue:
      type: integer
      format: int64
    DatasourcePackage:
      type: string
      enum:
      - DETECTIVE_CORE
      - EKS_AUDIT
      - ASFF_SECURITYHUB_FINDING
    DatasourcePackageIngestDetails:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/DatasourcePackageIngestDetail'
    DatasourcePackageIngestHistory:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/LastIngestStateChangeDates'
    DatasourcePackageIngestState:
      type: string
      enum:
      - STARTED
      - STOPPED
      - DISABLED
    DatasourcePackageIngestStates:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/DatasourcePackageIngestState'
    DatasourcePackageList:
      type: array
      items:
        $ref: '#/components/schemas/DatasourcePackage'
    EmailAddress:
      type: string
      pattern: ^.+@(?:(?:(?!-)[A-Za-z0-9-]{1,62})?[A-Za-z0-9]{1}\.)+[A-Za-z]{2,63}$
      minLength: 1
      maxLength: 64
    EmailMessage:
      type: string
      minLength: 1
      maxLength: 1000
    EntityArn:
      type: string
      pattern: '^arn:'
    EntityType:
      type: string
      enum:
      - IAM_ROLE
      - IAM_USER
    ErrorCode:
      type: string
      enum:
      - INVALID_GRAPH_ARN
      - INVALID_REQUEST_BODY
      - INTERNAL_ERROR
    ErrorCodeReason:
      type: string
    ErrorMessage:
      type: string
    Field:
      type: string
      enum:
      - SEVERITY
      - STATUS
      - CREATED_TIME
    GraphArn:
      type: string
      pattern: ^arn:aws[-\w]{0,10}?:detective:[-\w]{2,20}?:\d{12}?:graph:[abcdef\d]{32}?$
    GraphArnList:
      type: array
      items:
        $ref: '#/components/schemas/GraphArn'
    GraphList:
      type: array
      items:
        $ref: '#/components/schemas/Graph'
    HourlyTimeDelta:
      type: integer
    Id:
      type: string
    IndicatorType:
      type: string
      enum:
      - TTP_OBSERVED
      - IMPOSSIBLE_TRAVEL
      - FLAGGED_IP_ADDRESS
      - NEW_GEOLOCATION
      - NEW_ASO
      - NEW_USER_AGENT
      - RELATED_FINDING
      - RELATED_FINDING_GROUP
    Indicators:
      type: array
      items:
        $ref: '#/components/schemas/Indicator'
    InvestigationDetails:
      type: array
      items:
        $ref: '#/components/schemas/InvestigationDetail'
    InvestigationId:
      type: string
      pattern: ^[0-9]+$
      minLength: 21
      maxLength: 21
    InvitationType:
      type: string
      enum:
      - INVITATION
      - ORGANIZATION
    IpAddress:
      type: string
    IsNewForEntireAccount:
      type: boolean
      default: false
    LastIngestStateChangeDates:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TimestampForCollection'
    Location:
      type: string
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    MemberDetailList:
      type: array
      items:
        $ref: '#/components/schemas/MemberDetail'
    MemberDisabledReason:
      type: string
      enum:
      - VOLUME_TOO_HIGH
      - VOLUME_UNKNOWN
    MemberResultsLimit:
      type: integer
      minimum: 1
      maximum: 200
    MemberStatus:
      type: string
      enum:
      - INVITED
      - VERIFICATION_IN_PROGRESS
      - VERIFICATION_FAILED
      - ENABLED
      - ACCEPTED_BUT_DISABLED
    MembershipDatasourcesList:
      type: array
      items:
        $ref: '#/components/schemas/MembershipDatasources'
    PaginationToken:
      type: string
      minLength: 1
      maxLength: 1024
    Percentage:
      type: number
      format: double
    Procedure:
      type: string
    Reason:
      type: string
      enum:
      - AWS_THREAT_INTELLIGENCE
    Resource:
      type: string
      minLength: 1
      maxLength: 64
    ResourceList:
      type: array
      items:
        $ref: '#/components/schemas/Resource'
    Severity:
      type: string
      enum:
      - INFORMATIONAL
      - LOW
      - MEDIUM
      - HIGH
      - CRITICAL
    SortOrder:
      type: string
      enum:
      - ASC
      - DESC
    State:
      type: string
      enum:
      - ACTIVE
      - ARCHIVED
    Status:
      type: string
      enum:
      - RUNNING
      - FAILED
      - SUCCESSFUL
    Tactic:
      type: string
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    Technique:
      type: string
    Timestamp:
      type: string
      format: date-time
    Type:
      type: string
    UnprocessedAccountList:
      type: array
      items:
        $ref: '#/components/schemas/UnprocessedAccount'
    UnprocessedGraphList:
      type: array
      items:
        $ref: '#/components/schemas/UnprocessedGraph'
    UnprocessedReason:
      type: string
    UserAgent:
      type: string
    Value:
      type: string
      minLength: 1
      maxLength: 500
    VolumeUsageByDatasourcePackage:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/DatasourcePackageUsageInfo'
