openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: devops_guru
  x-aws-serviceName: devopsguru
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-12-01'
  title: Amazon DevOps Guru
  description: |-
    Amazon DevOps Guru is a fully managed service that helps you identify anomalous behavior in business critical operational applications. You specify the Amazon Web Services resources that you want DevOps Guru to cover, then the Amazon CloudWatch metrics and Amazon Web Services CloudTrail events related to those resources are analyzed. When anomalous behavior is detected, DevOps Guru creates an _insight_ that includes recommendations, related events, and related metrics that can help you improve your operational applications. For more information, see [What is Amazon DevOps Guru](https://docs.aws.amazon.com/devops-guru/latest/userguide/welcome.html).

    You can specify 1 or 2 Amazon Simple Notification Service topics so you are notified every time a new insight is created. You can also enable DevOps Guru to generate an OpsItem in Amazon Web Services Systems Manager for each insight to help you manage and track your work addressing insights.

    To learn about the DevOps Guru workflow, see [How DevOps Guru works](https://docs.aws.amazon.com/devops-guru/latest/userguide/welcome.html#how-it-works). To learn about DevOps Guru concepts, see [Concepts in DevOps Guru](https://docs.aws.amazon.com/devops-guru/latest/userguide/concepts.html).
servers:
- description: The Amazon DevOps Guru regional endpoint
  url: https://devops-guru.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AnomalyDescription:
      type: string
    AnomalyId:
      type: string
      pattern: ^[\w~.-]*$
      minLength: 1
      maxLength: 100
    AnomalyName:
      type: string
    AnomalySource:
      type: string
    AppBoundaryKey:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
      minLength: 1
      maxLength: 128
    AwsAccountId:
      type: string
      pattern: ^\d{12}$
      minLength: 12
      maxLength: 12
    ClientToken:
      type: string
      pattern: ^[a-zA-Z0-9]+[a-zA-Z0-9-]*$
      minLength: 1
      maxLength: 100
    CloudWatchMetricsDimensionName:
      type: string
    CloudWatchMetricsDimensionValue:
      type: string
    CloudWatchMetricsMetricName:
      type: string
    CloudWatchMetricsNamespace:
      type: string
    CloudWatchMetricsPeriod:
      type: integer
      default: 0
    CloudWatchMetricsUnit:
      type: string
    CostEstimationServiceResourceCount:
      type: integer
      default: 0
    ErrorMessageString:
      type: string
    ErrorNameString:
      type: string
    ErrorQuotaCodeString:
      type: string
    ErrorServiceCodeString:
      type: string
    EventId:
      type: string
    EventName:
      type: string
      minLength: 0
      maxLength: 50
    EventResourceArn:
      type: string
      pattern: ^arn:aws[-a-z]*:[a-z0-9-]*:[a-z0-9-]*:\d{12}:.*$
      minLength: 36
      maxLength: 2048
    EventResourceName:
      type: string
      pattern: ^.*$
      minLength: 0
      maxLength: 2048
    EventResourceType:
      type: string
      pattern: ^.*$
      minLength: 0
      maxLength: 2048
    EventSource:
      type: string
      pattern: ^[a-z]+[a-z0-9]*\.amazonaws\.com|aws\.events$
      minLength: 10
      maxLength: 50
    Explanation:
      type: string
      minLength: 1
      maxLength: 2048
    InsightDescription:
      type: string
    InsightId:
      type: string
      pattern: ^[\w-]*$
      minLength: 1
      maxLength: 100
    InsightName:
      type: string
      pattern: ^[\s\S]*$
      minLength: 1
      maxLength: 530
    KMSKeyId:
      type: string
      pattern: ^.*$
      minLength: 1
      maxLength: 2048
    ListAnomaliesForInsightMaxResults:
      type: integer
      minimum: 1
      maximum: 500
    ListAnomalousLogGroupsMaxResults:
      type: integer
      minimum: 1
      maximum: 200
    ListEventsMaxResults:
      type: integer
      minimum: 1
      maximum: 200
    ListInsightsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListMonitoredResourcesMaxResults:
      type: integer
      minimum: 1
      maximum: 50
    LogAnomalyToken:
      type: string
      minLength: 1
      maxLength: 2048
    LogEventId:
      type: string
      minLength: 1
      maxLength: 512
    LogGroupName:
      type: string
      minLength: 1
      maxLength: 512
    LogStreamName:
      type: string
      minLength: 1
      maxLength: 512
    MonitoredResourceName:
      type: string
      pattern: ^[\.\-_\/#A-Za-z0-9]+$
      minLength: 1
      maxLength: 512
    NotificationChannelId:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 36
      maxLength: 36
    NumMetricsAnalyzed:
      type: integer
      default: 0
    NumOpenProactiveInsights:
      type: integer
      default: 0
    NumOpenReactiveInsights:
      type: integer
      default: 0
    NumProactiveInsights:
      type: integer
      default: 0
    NumReactiveInsights:
      type: integer
      default: 0
    NumberOfLogLinesOccurrences:
      type: integer
      default: 0
    NumberOfLogLinesScanned:
      type: integer
      default: 0
    OrganizationResourceCollectionMaxResults:
      type: integer
      minimum: 1
      maximum: 500
    OrganizationalUnitId:
      type: string
      pattern: ^ou-[0-9a-z]{4,32}-[a-z0-9]{8,32}$
      minLength: 0
      maxLength: 68
    PerformanceInsightsMetricDimension:
      type: string
    PerformanceInsightsMetricDisplayName:
      type: string
    PerformanceInsightsMetricFilterKey:
      type: string
    PerformanceInsightsMetricFilterValue:
      type: string
    PerformanceInsightsMetricGroup:
      type: string
    PerformanceInsightsMetricLimitInteger:
      type: integer
      minimum: 1
      maximum: 10
    PerformanceInsightsMetricName:
      type: string
    PerformanceInsightsMetricUnit:
      type: string
    PerformanceInsightsReferenceName:
      type: string
    PerformanceInsightsStatType:
      type: string
    RecommendationCategory:
      type: string
    RecommendationDescription:
      type: string
    RecommendationLink:
      type: string
    RecommendationName:
      type: string
    RecommendationReason:
      type: string
    RecommendationRelatedAnomalyResourceName:
      type: string
    RecommendationRelatedAnomalyResourceType:
      type: string
    RecommendationRelatedCloudWatchMetricsSourceMetricName:
      type: string
    RecommendationRelatedCloudWatchMetricsSourceNamespace:
      type: string
    RecommendationRelatedEventName:
      type: string
    RecommendationRelatedEventResourceName:
      type: string
    RecommendationRelatedEventResourceType:
      type: string
    ResourceArn:
      type: string
      minLength: 20
      maxLength: 2048
    ResourceIdString:
      type: string
    ResourceIdType:
      type: string
    ResourceName:
      type: string
    ResourceType:
      type: string
      pattern: ^[a-zA-Z]+[a-zA-Z0-9-_:]*$
      minLength: 1
      maxLength: 256
    RetryAfterSeconds:
      type: integer
      default: 0
    SearchInsightsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    SearchOrganizationInsightsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    SsmOpsItemId:
      type: string
      pattern: ^.*$
      minLength: 1
      maxLength: 100
    StackName:
      type: string
      pattern: ^[a-zA-Z*]+[a-zA-Z0-9-]*$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*|\*)$
      minLength: 0
      maxLength: 256
    TopicArn:
      type: string
      pattern: ^arn:aws[a-z0-9-]*:sns:[a-z0-9-]+:\d{12}:[^:]+$
      minLength: 36
      maxLength: 1024
    UuidNextToken:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 36
      maxLength: 36
