openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: dlm
  x-aws-serviceName: dlm
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-01-12'
  title: Amazon Data Lifecycle Manager
  description: |-
    Amazon Data Lifecycle Manager

    With Amazon Data Lifecycle Manager, you can manage the lifecycle of your Amazon Web Services resources. You create lifecycle policies, which are used to automate operations on the specified resources.

    Amazon Data Lifecycle Manager supports Amazon EBS volumes and snapshots. For information about using Amazon Data Lifecycle Manager with Amazon EBS, see [ Amazon Data Lifecycle Manager](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/snapshot-lifecycle.html) in the _Amazon EC2 User Guide_.
servers:
- description: The Amazon Data Lifecycle Manager regional endpoint
  url: https://dlm.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ActionList:
      type: array
      items:
        $ref: '#/components/schemas/Action'
    ActionName:
      type: string
      pattern: ^[0-9A-Za-z _-]+$
      minLength: 0
      maxLength: 120
    AvailabilityZone:
      type: string
      pattern: ^([a-z]+-){2,3}\d[a-z]$
      minLength: 0
      maxLength: 16
    AvailabilityZoneList:
      type: array
      items:
        $ref: '#/components/schemas/AvailabilityZone'
    AwsAccountId:
      type: string
      pattern: ^[0-9]{12}$
      minLength: 12
      maxLength: 12
    CmkArn:
      type: string
      pattern: ^arn:aws(-[a-z]{1,3}){0,2}:kms:([a-z]+-){2,3}\d:\d+:key/
      minLength: 0
      maxLength: 2048
    CopyTags:
      type: boolean
    CopyTagsNullable:
      type: boolean
    Count:
      type: integer
      minimum: 1
      maximum: 1000
    CreateInterval:
      type: integer
      minimum: 1
    CronExpression:
      type: string
      pattern: ^cron\([^\n]{11,100}\)$
      minLength: 17
      maxLength: 106
    CrossRegionCopyActionList:
      type: array
      items:
        $ref: '#/components/schemas/CrossRegionCopyAction'
    CrossRegionCopyRules:
      type: array
      items:
        $ref: '#/components/schemas/CrossRegionCopyRule'
    CrossRegionCopyTargetList:
      type: array
      items:
        $ref: '#/components/schemas/CrossRegionCopyTarget'
    DefaultPoliciesTypeValues:
      type: string
      enum:
      - VOLUME
      - INSTANCE
      - ALL
    DefaultPolicy:
      type: boolean
    DefaultPolicyTypeValues:
      type: string
      enum:
      - VOLUME
      - INSTANCE
    DescriptionRegex:
      type: string
      pattern: ^[\p{all}]*$
      minLength: 0
      maxLength: 1000
    Encrypted:
      type: boolean
    ErrorCode:
      type: string
    ErrorMessage:
      type: string
    EventSourceValues:
      type: string
      enum:
      - MANAGED_CWE
    EventTypeValues:
      type: string
      enum:
      - shareSnapshot
    ExcludeBootVolume:
      type: boolean
    ExcludeBootVolumes:
      type: boolean
    ExcludeDataVolumeTagList:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    ExcludeTagsList:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    ExcludeVolumeTypesList:
      type: array
      items:
        $ref: '#/components/schemas/VolumeTypeValues'
    ExecuteOperationOnScriptFailure:
      type: boolean
    ExecutionHandler:
      type: string
      pattern: ^([a-zA-Z0-9_\-.]{3,128}|[a-zA-Z0-9_\-.:/]{3,200}|[A-Z0-9_]+)$
      minLength: 0
      maxLength: 200
    ExecutionHandlerServiceValues:
      type: string
      enum:
      - AWS_SYSTEMS_MANAGER
    ExecutionRoleArn:
      type: string
      pattern: ^arn:aws(-[a-z]{1,3}){0,2}:iam::\d+:role/
      minLength: 0
      maxLength: 2048
    ExtendDeletion:
      type: boolean
    GettablePolicyStateValues:
      type: string
      enum:
      - ENABLED
      - DISABLED
      - ERROR
    Interval:
      type: integer
      minimum: 1
    IntervalUnitValues:
      type: string
      enum:
      - HOURS
    LifecyclePolicySummaryList:
      type: array
      items:
        $ref: '#/components/schemas/LifecyclePolicySummary'
    LocationValues:
      type: string
      enum:
      - CLOUD
      - OUTPOST_LOCAL
      - LOCAL_ZONE
    NoReboot:
      type: boolean
    Parameter:
      type: string
    ParameterList:
      type: array
      items:
        $ref: '#/components/schemas/Parameter'
    PolicyArn:
      type: string
      pattern: ^arn:aws(-[a-z]{1,3}){0,2}:dlm:[A-Za-z0-9_/.-]{0,63}:\d+:policy/[0-9A-Za-z_-]{1,128}$
      minLength: 0
      maxLength: 2048
    PolicyDescription:
      type: string
      pattern: ^[0-9A-Za-z _-]+$
      minLength: 0
      maxLength: 500
    PolicyId:
      type: string
      pattern: ^policy-[a-f0-9]+$
      minLength: 0
      maxLength: 64
    PolicyIdList:
      type: array
      items:
        $ref: '#/components/schemas/PolicyId'
    PolicyLanguageValues:
      type: string
      enum:
      - SIMPLIFIED
      - STANDARD
    PolicyTypeValues:
      type: string
      enum:
      - EBS_SNAPSHOT_MANAGEMENT
      - IMAGE_MANAGEMENT
      - EVENT_BASED_POLICY
    ResourceLocationList:
      type: array
      items:
        $ref: '#/components/schemas/ResourceLocationValues'
    ResourceLocationValues:
      type: string
      enum:
      - CLOUD
      - OUTPOST
      - LOCAL_ZONE
    ResourceTypeValues:
      type: string
      enum:
      - VOLUME
      - INSTANCE
    ResourceTypeValuesList:
      type: array
      items:
        $ref: '#/components/schemas/ResourceTypeValues'
    RetainInterval:
      type: integer
      minimum: 1
    RetentionIntervalUnitValues:
      type: string
      enum:
      - DAYS
      - WEEKS
      - MONTHS
      - YEARS
    ScheduleList:
      type: array
      items:
        $ref: '#/components/schemas/Schedule'
    ScheduleName:
      type: string
      pattern: ^[0-9A-Za-z _-]+$
      minLength: 0
      maxLength: 120
    ScriptExecutionTimeout:
      type: integer
      minimum: 10
      maximum: 120
    ScriptMaximumRetryCount:
      type: integer
      minimum: 0
      maximum: 3
    ScriptsList:
      type: array
      items:
        $ref: '#/components/schemas/Script'
    SettablePolicyStateValues:
      type: string
      enum:
      - ENABLED
      - DISABLED
    ShareRules:
      type: array
      items:
        $ref: '#/components/schemas/ShareRule'
    ShareTargetAccountList:
      type: array
      items:
        $ref: '#/components/schemas/AwsAccountId'
    SnapshotOwnerList:
      type: array
      items:
        $ref: '#/components/schemas/AwsAccountId'
    StageValues:
      type: string
      enum:
      - PRE
      - POST
    StagesList:
      type: array
      items:
        $ref: '#/components/schemas/StageValues'
    StandardTierRetainRuleCount:
      type: integer
      minimum: 0
      maximum: 1000
    StandardTierRetainRuleInterval:
      type: integer
      minimum: 0
    StatusMessage:
      type: string
      pattern: ^[\p{all}]*$
      minLength: 0
      maxLength: 500
    String:
      type: string
      pattern: ^[\p{all}]*$
      minLength: 0
      maxLength: 500
    TagFilter:
      type: string
      pattern: ^[\p{all}]*$
      minLength: 0
      maxLength: 256
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      pattern: ^[\p{all}]*$
      minLength: 0
      maxLength: 256
    TagsToAddFilterList:
      type: array
      items:
        $ref: '#/components/schemas/TagFilter'
    TagsToAddList:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    Target:
      type: string
      pattern: ^[\w:\-\/\*]+$
      minLength: 0
      maxLength: 2048
    TargetRegion:
      type: string
      pattern: ^([a-z]+-){2,3}\d$
      minLength: 0
      maxLength: 16
    TargetTagList:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    TargetTagsFilterList:
      type: array
      items:
        $ref: '#/components/schemas/TagFilter'
    Time:
      type: string
      pattern: ^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$
      minLength: 5
      maxLength: 5
    TimesList:
      type: array
      items:
        $ref: '#/components/schemas/Time'
    Timestamp:
      type: string
      format: date-time
    VariableTagsList:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    VolumeTypeValues:
      type: string
