openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: drs
  x-aws-serviceName: drs
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-02-26'
  title: Elastic Disaster Recovery Service
  description: |-
    AWS Elastic Disaster Recovery Service.
servers:
- description: The Elastic Disaster Recovery Service regional endpoint
  url: https://drs.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ARN:
      type: string
      pattern: ^arn:.{16,2044}$
      minLength: 20
      maxLength: 2048
    AccountID:
      type: string
      pattern: '[0-9]{12,}'
      minLength: 12
      maxLength: 12
    AgentVersion:
      type: string
      pattern: ^[0-9]{1,5}.[0-9]{1,5}.[0-9]{1,5}(.[0-9]{4}.[0-9]{3}.[0-9]{4})?$
    AwsAvailabilityZone:
      type: string
      pattern: ^(us(-gov)?|ap|ca|cn|eu|sa|af|me|il)-(central|north|(north(?:east|west))|south|south(?:east|west)|east|west)-[0-9][a-z]$
      minLength: 0
      maxLength: 255
    AwsRegion:
      type: string
      pattern: ^(us(-gov)?|ap|ca|cn|eu|sa|af|me|il)-(central|north|(north(?:east|west))|south|south(?:east|west)|east|west)-[0-9]$
      minLength: 0
      maxLength: 255
    BoundedString:
      type: string
      minLength: 0
      maxLength: 256
    CfnStackName:
      type: string
      pattern: ^[a-zA-Z][-a-zA-Z0-9]*$
      minLength: 1
      maxLength: 128
    DataReplicationErrorString:
      type: string
      enum:
      - AGENT_NOT_SEEN
      - SNAPSHOTS_FAILURE
      - NOT_CONVERGING
      - UNSTABLE_NETWORK
      - FAILED_TO_CREATE_SECURITY_GROUP
      - FAILED_TO_LAUNCH_REPLICATION_SERVER
      - FAILED_TO_BOOT_REPLICATION_SERVER
      - FAILED_TO_AUTHENTICATE_WITH_SERVICE
      - FAILED_TO_DOWNLOAD_REPLICATION_SOFTWARE
      - FAILED_TO_CREATE_STAGING_DISKS
      - FAILED_TO_ATTACH_STAGING_DISKS
      - FAILED_TO_PAIR_REPLICATION_SERVER_WITH_AGENT
      - FAILED_TO_CONNECT_AGENT_TO_REPLICATION_SERVER
      - FAILED_TO_START_DATA_TRANSFER
    DataReplicationInitiationStepName:
      type: string
      enum:
      - WAIT
      - CREATE_SECURITY_GROUP
      - LAUNCH_REPLICATION_SERVER
      - BOOT_REPLICATION_SERVER
      - AUTHENTICATE_WITH_SERVICE
      - DOWNLOAD_REPLICATION_SOFTWARE
      - CREATE_STAGING_DISKS
      - ATTACH_STAGING_DISKS
      - PAIR_REPLICATION_SERVER_WITH_AGENT
      - CONNECT_AGENT_TO_REPLICATION_SERVER
      - START_DATA_TRANSFER
    DataReplicationInitiationStepStatus:
      type: string
      enum:
      - NOT_STARTED
      - IN_PROGRESS
      - SUCCEEDED
      - FAILED
      - SKIPPED
    DataReplicationState:
      type: string
      enum:
      - STOPPED
      - INITIATING
      - INITIAL_SYNC
      - BACKLOG
      - CREATING_SNAPSHOT
      - CONTINUOUS
      - PAUSED
      - RESCAN
      - STALLED
      - DISCONNECTED
    EC2InstanceID:
      type: string
      pattern: ^i-[0-9a-fA-F]{8,}$
      minLength: 0
      maxLength: 255
    EC2InstanceState:
      type: string
      enum:
      - PENDING
      - RUNNING
      - STOPPING
      - STOPPED
      - SHUTTING-DOWN
      - TERMINATED
      - NOT_FOUND
    EC2InstanceType:
      type: string
      minLength: 0
      maxLength: 255
    EbsSnapshot:
      type: string
      pattern: ^snap-[0-9a-zA-Z]{17}$
    EbsVolumeID:
      type: string
      pattern: ^vol-([0-9a-fA-F]{8}|[0-9a-fA-F]{17})$
      minLength: 10
      maxLength: 19
    ExtensionStatus:
      type: string
      enum:
      - EXTENDED
      - EXTENSION_ERROR
      - NOT_EXTENDED
    FailbackLaunchType:
      type: string
      enum:
      - RECOVERY
      - DRILL
    FailbackReplicationError:
      type: string
      enum:
      - AGENT_NOT_SEEN
      - FAILBACK_CLIENT_NOT_SEEN
      - NOT_CONVERGING
      - UNSTABLE_NETWORK
      - FAILED_TO_ESTABLISH_RECOVERY_INSTANCE_COMMUNICATION
      - FAILED_TO_DOWNLOAD_REPLICATION_SOFTWARE_TO_FAILBACK_CLIENT
      - FAILED_TO_CONFIGURE_REPLICATION_SOFTWARE
      - FAILED_TO_PAIR_AGENT_WITH_REPLICATION_SOFTWARE
      - FAILED_TO_ESTABLISH_AGENT_REPLICATOR_SOFTWARE_COMMUNICATION
      - FAILED_GETTING_REPLICATION_STATE
      - SNAPSHOTS_FAILURE
      - FAILED_TO_CREATE_SECURITY_GROUP
      - FAILED_TO_LAUNCH_REPLICATION_SERVER
      - FAILED_TO_BOOT_REPLICATION_SERVER
      - FAILED_TO_AUTHENTICATE_WITH_SERVICE
      - FAILED_TO_DOWNLOAD_REPLICATION_SOFTWARE
      - FAILED_TO_CREATE_STAGING_DISKS
      - FAILED_TO_ATTACH_STAGING_DISKS
      - FAILED_TO_PAIR_REPLICATION_SERVER_WITH_AGENT
      - FAILED_TO_CONNECT_AGENT_TO_REPLICATION_SERVER
      - FAILED_TO_START_DATA_TRANSFER
    FailbackState:
      type: string
      enum:
      - FAILBACK_NOT_STARTED
      - FAILBACK_IN_PROGRESS
      - FAILBACK_READY_FOR_LAUNCH
      - FAILBACK_COMPLETED
      - FAILBACK_ERROR
      - FAILBACK_NOT_READY_FOR_LAUNCH
      - FAILBACK_LAUNCH_STATE_NOT_AVAILABLE
    FailureReason:
      type: string
      pattern: ^[0-9a-zA-Z ():/.,'-_#*;]*$
      minLength: 0
      maxLength: 256
    ISO8601DatetimeString:
      type: string
      pattern: ^[1-9][0-9]*-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([0-1][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?Z$
      minLength: 19
      maxLength: 32
    ISO8601DurationString:
      type: string
      minLength: 1
      maxLength: 64
    InitiatedBy:
      type: string
      enum:
      - START_RECOVERY
      - START_DRILL
      - FAILBACK
      - DIAGNOSTIC
      - TERMINATE_RECOVERY_INSTANCES
      - TARGET_ACCOUNT
      - CREATE_NETWORK_RECOVERY
      - UPDATE_NETWORK_RECOVERY
      - ASSOCIATE_NETWORK_RECOVERY
    JobID:
      type: string
      pattern: ^drsjob-[0-9a-zA-Z]{17}$
      minLength: 24
      maxLength: 24
    JobLogEvent:
      type: string
      enum:
      - JOB_START
      - SERVER_SKIPPED
      - CLEANUP_START
      - CLEANUP_END
      - CLEANUP_FAIL
      - SNAPSHOT_START
      - SNAPSHOT_END
      - SNAPSHOT_FAIL
      - USING_PREVIOUS_SNAPSHOT
      - USING_PREVIOUS_SNAPSHOT_FAILED
      - CONVERSION_START
      - CONVERSION_END
      - CONVERSION_FAIL
      - LAUNCH_START
      - LAUNCH_FAILED
      - JOB_CANCEL
      - JOB_END
      - DEPLOY_NETWORK_CONFIGURATION_START
      - DEPLOY_NETWORK_CONFIGURATION_END
      - DEPLOY_NETWORK_CONFIGURATION_FAILED
      - UPDATE_NETWORK_CONFIGURATION_START
      - UPDATE_NETWORK_CONFIGURATION_END
      - UPDATE_NETWORK_CONFIGURATION_FAILED
      - UPDATE_LAUNCH_TEMPLATE_START
      - UPDATE_LAUNCH_TEMPLATE_END
      - UPDATE_LAUNCH_TEMPLATE_FAILED
      - NETWORK_RECOVERY_FAIL
    JobStatus:
      type: string
      enum:
      - PENDING
      - STARTED
      - COMPLETED
    JobType:
      type: string
      enum:
      - LAUNCH
      - TERMINATE
      - CREATE_CONVERTED_SNAPSHOT
    LargeBoundedString:
      type: string
      minLength: 0
      maxLength: 65536
    LastLaunchResult:
      type: string
      enum:
      - NOT_STARTED
      - PENDING
      - SUCCEEDED
      - FAILED
    LastLaunchType:
      type: string
      enum:
      - RECOVERY
      - DRILL
    LaunchActionCategory:
      type: string
      enum:
      - MONITORING
      - VALIDATION
      - CONFIGURATION
      - SECURITY
      - OTHER
    LaunchActionDescription:
      type: string
      pattern: '^[0-9a-zA-Z ():/.,''-_#*;

        ]*$'
      minLength: 0
      maxLength: 1024
    LaunchActionId:
      type: string
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
      minLength: 1
      maxLength: 64
    LaunchActionName:
      type: string
      pattern: ^[A-Za-z0-9][A-Za-z0-9 /_-]*$
      minLength: 1
      maxLength: 256
    LaunchActionOrder:
      type: integer
      minimum: 2
      maximum: 10000
      description: <p>Launch action order.</p>
    LaunchActionParameterName:
      type: string
      pattern: ^([A-Za-z0-9])+$
      minLength: 1
      maxLength: 1011
    LaunchActionParameterType:
      type: string
      enum:
      - SSM_STORE
      - DYNAMIC
    LaunchActionParameterValue:
      type: string
      pattern: ^[A-Za-z0-9.-]+$
      minLength: 1
      maxLength: 1011
    LaunchActionResourceId:
      type: string
      pattern: ^(s-[0-9a-zA-Z]{17}$|lct-[0-9a-zA-Z]{17})$
    LaunchActionRunId:
      type: string
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
      minLength: 1
      maxLength: 64
    LaunchActionRunStatus:
      type: string
      enum:
      - IN_PROGRESS
      - SUCCEEDED
      - FAILED
    LaunchActionType:
      type: string
      enum:
      - SSM_AUTOMATION
      - SSM_COMMAND
    LaunchActionVersion:
      type: string
      pattern: ^(\$DEFAULT|\$LATEST|[0-9]+)$
      minLength: 1
      maxLength: 10
    LaunchConfigurationTemplateID:
      type: string
      pattern: ^lct-[0-9a-zA-Z]{17}$
      minLength: 21
      maxLength: 21
    LaunchDisposition:
      type: string
      enum:
      - STOPPED
      - STARTED
    LaunchStatus:
      type: string
      enum:
      - PENDING
      - IN_PROGRESS
      - LAUNCHED
      - FAILED
      - TERMINATED
    MaxResultsReplicatingSourceServers:
      type: integer
      minimum: 1
      maximum: 300
    MaxResultsType:
      type: integer
      minimum: 1
      maximum: 1000
    OriginEnvironment:
      type: string
      enum:
      - ON_PREMISES
      - AWS
    OutpostARN:
      type: string
      pattern: ^arn:aws([a-z-]+)?:outposts:[a-z\d-]+:\d{12}:outpost/op-[a-f0-9]{17}$
      minLength: 20
      maxLength: 255
    PITPolicyRuleUnits:
      type: string
      enum:
      - MINUTE
      - HOUR
      - DAY
    PaginationToken:
      type: string
      minLength: 0
      maxLength: 2048
    ProductCodeId:
      type: string
      pattern: ^([A-Za-z0-9])+$
      minLength: 25
      maxLength: 25
    ProductCodeMode:
      type: string
      enum:
      - ENABLED
      - DISABLED
    RecoveryInstanceDataReplicationInitiationStepName:
      type: string
      enum:
      - LINK_FAILBACK_CLIENT_WITH_RECOVERY_INSTANCE
      - COMPLETE_VOLUME_MAPPING
      - ESTABLISH_RECOVERY_INSTANCE_COMMUNICATION
      - DOWNLOAD_REPLICATION_SOFTWARE_TO_FAILBACK_CLIENT
      - CONFIGURE_REPLICATION_SOFTWARE
      - PAIR_AGENT_WITH_REPLICATION_SOFTWARE
      - ESTABLISH_AGENT_REPLICATOR_SOFTWARE_COMMUNICATION
      - WAIT
      - CREATE_SECURITY_GROUP
      - LAUNCH_REPLICATION_SERVER
      - BOOT_REPLICATION_SERVER
      - AUTHENTICATE_WITH_SERVICE
      - DOWNLOAD_REPLICATION_SOFTWARE
      - CREATE_STAGING_DISKS
      - ATTACH_STAGING_DISKS
      - PAIR_REPLICATION_SERVER_WITH_AGENT
      - CONNECT_AGENT_TO_REPLICATION_SERVER
      - START_DATA_TRANSFER
    RecoveryInstanceDataReplicationInitiationStepStatus:
      type: string
      enum:
      - NOT_STARTED
      - IN_PROGRESS
      - SUCCEEDED
      - FAILED
      - SKIPPED
    RecoveryInstanceDataReplicationState:
      type: string
      enum:
      - STOPPED
      - INITIATING
      - INITIAL_SYNC
      - BACKLOG
      - CREATING_SNAPSHOT
      - CONTINUOUS
      - PAUSED
      - RESCAN
      - STALLED
      - DISCONNECTED
      - REPLICATION_STATE_NOT_AVAILABLE
      - NOT_STARTED
    RecoveryInstanceID:
      type: string
      pattern: ^i-[0-9a-fA-F]{8,}$
      minLength: 10
      maxLength: 19
    RecoveryResult:
      type: string
      enum:
      - NOT_STARTED
      - IN_PROGRESS
      - SUCCESS
      - FAIL
      - PARTIAL_SUCCESS
      - ASSOCIATE_SUCCESS
      - ASSOCIATE_FAIL
    RecoverySnapshotID:
      type: string
      pattern: ^pit-[0-9a-zA-Z]{17}$
      minLength: 21
      maxLength: 21
    RecoverySnapshotsOrder:
      type: string
      enum:
      - ASC
      - DESC
    ReplicationConfigurationDataPlaneRouting:
      type: string
      enum:
      - PRIVATE_IP
      - PUBLIC_IP
    ReplicationConfigurationDefaultLargeStagingDiskType:
      type: string
      enum:
      - GP2
      - GP3
      - ST1
      - AUTO
    ReplicationConfigurationEbsEncryption:
      type: string
      enum:
      - DEFAULT
      - CUSTOM
      - NONE
    ReplicationConfigurationReplicatedDiskStagingDiskType:
      type: string
      enum:
      - AUTO
      - GP2
      - GP3
      - IO1
      - SC1
      - ST1
      - STANDARD
    ReplicationConfigurationTemplateID:
      type: string
      pattern: ^rct-[0-9a-zA-Z]{17}$
      minLength: 21
      maxLength: 21
    ReplicationDirection:
      type: string
      enum:
      - FAILOVER
      - FAILBACK
    ReplicationStatus:
      type: string
      enum:
      - STOPPED
      - IN_PROGRESS
      - PROTECTED
      - ERROR
    SecurityGroupID:
      type: string
      pattern: ^sg-[0-9a-fA-F]{8,}$
      minLength: 0
      maxLength: 255
    SensitiveBoundedString:
      type: string
      minLength: 0
      maxLength: 256
    SmallBoundedString:
      type: string
      minLength: 0
      maxLength: 128
    SourceNetworkID:
      type: string
      pattern: ^sn-[0-9a-zA-Z]{17}$
      minLength: 20
      maxLength: 20
    SourceServerARN:
      type: string
      pattern: ^arn:(?:[0-9a-zA-Z_-]+:){3}([0-9]{12,}):source-server/(s-[0-9a-zA-Z]{17})$
      minLength: 20
      maxLength: 2048
    SourceServerID:
      type: string
      pattern: ^s-[0-9a-zA-Z]{17}$
      minLength: 19
      maxLength: 19
    SsmDocumentName:
      type: string
      pattern: ^([A-Za-z0-9-/:])+$
      minLength: 1
      maxLength: 1011
    StrictlyPositiveInteger:
      type: integer
      minimum: 1
    SubnetID:
      type: string
      pattern: ^subnet-[0-9a-fA-F]{8,}$
      minLength: 0
      maxLength: 255
    TagKey:
      type: string
      minLength: 0
      maxLength: 256
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TargetInstanceTypeRightSizingMethod:
      type: string
      enum:
      - NONE
      - BASIC
      - IN_AWS
    ValidationExceptionReason:
      type: string
      enum:
      - unknownOperation
      - cannotParse
      - fieldValidationFailed
      - other
    VolumeStatus:
      type: string
      enum:
      - REGULAR
      - CONTAINS_MARKETPLACE_PRODUCT_CODES
      - MISSING_VOLUME_ATTRIBUTES
      - MISSING_VOLUME_ATTRIBUTES_AND_PRECHECK_UNAVAILABLE
      - PENDING
    VpcID:
      type: string
      pattern: ^vpc-[0-9a-fA-F]{8,}$
      minLength: 12
      maxLength: 21
