openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: dsql
  x-aws-serviceName: dsql
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: Amazon Aurora DSQL
  description: |-
    This is an interface reference for Amazon Aurora DSQL. It contains documentation for one of the programming or command line interfaces you can use to manage Amazon Aurora DSQL.

    Amazon Aurora DSQL is a serverless, distributed SQL database suitable for workloads of any size. Aurora DSQL is available in both single-Region and multi-Region configurations, so your clusters and databases are always available even if an Availability Zone or an Amazon Web Services Region are unavailable. Aurora DSQL lets you focus on using your data to acquire new insights for your business and customers.
servers:
- description: The Amazon Aurora DSQL regional endpoint
  url: https://dsql.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Arn:
      type: string
      pattern: ^arn:.+$
      minLength: 1
      maxLength: 1011
    ClientToken:
      type: string
      pattern: ^[!-~]+$
      minLength: 1
      maxLength: 128
    ClusterArn:
      type: string
    ClusterArnList:
      type: array
      items:
        $ref: '#/components/schemas/ClusterArn'
      description: List of cluster arns
    ClusterCreationTime:
      type: string
      format: date-time
      description: Timestamp when the Cluster was created
    ClusterId:
      type: string
      pattern: ^[a-z0-9]{26}$
    ClusterList:
      type: array
      items:
        $ref: '#/components/schemas/ClusterSummary'
      description: List of clusters
    ClusterPropertyMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/LinkedClusterProperties'
      description: Properties for each linked cluster
    ClusterStatus:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - UPDATING
      - DELETING
      - DELETED
      - FAILED
      description: Cluster Status
    DeletionProtectionEnabled:
      type: boolean
      description: Deletion Protection
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
      description: Max results that will be returned per page
    NextToken:
      type: string
    Region:
      type: string
      maxLength: 20
    RegionList:
      type: array
      items:
        $ref: '#/components/schemas/Region'
      description: List of regions
    ServiceName:
      type: string
      pattern: ^com\.amazonaws\.[a-z0-9-]+\.dsql-[a-f0-9]{6}$
      minLength: 1
      maxLength: 128
    TagKey:
      type: string
      pattern: ^[a-zA-Z0-9_.:/=+\-@ ]*$
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
      description: List of tag keys
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
      description: Map of tags
    TagValue:
      type: string
      pattern: ^[a-zA-Z0-9_.:/=+\-@ ]*$
      minLength: 0
      maxLength: 256
    ValidationExceptionFieldList:
      type: array
      items:
        $ref: '#/components/schemas/ValidationExceptionField'
      description: List of fields that caused the error
    ValidationExceptionReason:
      type: string
      enum:
      - unknownOperation
      - cannotParse
      - fieldValidationFailed
      - deletionProtectionEnabled
      - other
      description: Reason the request failed validation
