openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: efs
  x-aws-serviceName: efs
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2015-02-01'
  title: Amazon Elastic File System
  description: |-
    Amazon Elastic File System

    Amazon Elastic File System (Amazon EFS) provides simple, scalable file storage for use with Amazon EC2 Linux and Mac instances in the Amazon Web Services Cloud. With Amazon EFS, storage capacity is elastic, growing and shrinking automatically as you add and remove files, so that your applications have the storage they need, when they need it. For more information, see the [Amazon Elastic File System API Reference](https://docs.aws.amazon.com/efs/latest/ug/api-reference.html) and the [Amazon Elastic File System User Guide](https://docs.aws.amazon.com/efs/latest/ug/whatisefs.html).
servers:
- description: The Amazon Elastic File System regional endpoint
  url: https://elasticfilesystem.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccessPointArn:
      type: string
      pattern: ^arn:aws[-a-z]*:elasticfilesystem:[0-9a-z-:]+:access-point/fsap-[0-9a-f]{8,40}$
      minLength: 0
      maxLength: 128
    AccessPointDescriptions:
      type: array
      items:
        $ref: '#/components/schemas/AccessPointDescription'
    AccessPointId:
      type: string
      pattern: ^(arn:aws[-a-z]*:elasticfilesystem:[0-9a-z-:]+:access-point/fsap-[0-9a-f]{8,40}|fsap-[0-9a-f]{8,40})$
      minLength: 0
      maxLength: 128
    AvailabilityZoneId:
      type: string
    AvailabilityZoneName:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 64
    AwsAccountId:
      type: string
      pattern: ^(\d{12})|(\d{4}-\d{4}-\d{4})$
      minLength: 0
      maxLength: 14
    Backup:
      type: boolean
    BypassPolicyLockoutSafetyCheck:
      type: boolean
      default: false
    ClientToken:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 64
    CreationToken:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 64
    DeletionMode:
      type: string
      enum:
      - ALL_CONFIGURATIONS
      - LOCAL_CONFIGURATION_ONLY
    Destinations:
      type: array
      items:
        $ref: '#/components/schemas/Destination'
    DestinationsToCreate:
      type: array
      items:
        $ref: '#/components/schemas/DestinationToCreate'
    Encrypted:
      type: boolean
    ErrorCode:
      type: string
      minLength: 1
    ErrorMessage:
      type: string
    FileSystemArn:
      type: string
    FileSystemDescriptions:
      type: array
      items:
        $ref: '#/components/schemas/FileSystemDescription'
    FileSystemId:
      type: string
      pattern: ^(arn:aws[-a-z]*:elasticfilesystem:[0-9a-z-:]+:file-system/fs-[0-9a-f]{8,40}|fs-[0-9a-f]{8,40})$
      minLength: 0
      maxLength: 128
    FileSystemNullableSizeValue:
      type: integer
      format: int64
      minimum: 0
    FileSystemSizeValue:
      type: integer
      format: int64
      default: 0
      minimum: 0
    Gid:
      type: integer
      format: int64
      minimum: 0
      maximum: 4294967295
    IpAddress:
      type: string
      pattern: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$
      minLength: 7
      maxLength: 15
    KmsKeyId:
      type: string
      pattern: ^([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|mrk-[0-9a-f]{32}|alias/[a-zA-Z0-9/_-]+|(arn:aws[-a-z]*:kms:[a-z0-9-]+:\d{12}:((key/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})|(key/mrk-[0-9a-f]{32})|(alias/[a-zA-Z0-9/_-]+))))$
      minLength: 0
      maxLength: 2048
    LifeCycleState:
      type: string
      enum:
      - creating
      - available
      - updating
      - deleting
      - deleted
      - error
    LifecyclePolicies:
      type: array
      items:
        $ref: '#/components/schemas/LifecyclePolicy'
    Marker:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 128
    MaxItems:
      type: integer
      minimum: 1
    MaxResults:
      type: integer
      minimum: 1
      description: Max results used for pagination.
    MountTargetCount:
      type: integer
      default: 0
      minimum: 0
    MountTargetDescriptions:
      type: array
      items:
        $ref: '#/components/schemas/MountTargetDescription'
    MountTargetId:
      type: string
      pattern: ^fsmt-[0-9a-f]{8,40}$
      minLength: 13
      maxLength: 45
    Name:
      type: string
    NetworkInterfaceId:
      type: string
    OwnerGid:
      type: integer
      format: int64
      minimum: 0
      maximum: 4294967295
    OwnerUid:
      type: integer
      format: int64
      minimum: 0
      maximum: 4294967295
    Path:
      type: string
      pattern: ^(\/|(\/(?!\.)+[^$#<>;`|&?{}^*/\n]+){1,4})$
      minLength: 1
      maxLength: 100
    PerformanceMode:
      type: string
      enum:
      - generalPurpose
      - maxIO
    Permissions:
      type: string
      pattern: ^[0-7]{3,4}$
      minLength: 3
      maxLength: 4
    Policy:
      type: string
      pattern: ^[\s\S]+$
      minLength: 1
      maxLength: 20000
    ProvisionedThroughputInMibps:
      type: number
      format: double
      minimum: 1.0
    RegionName:
      type: string
      pattern: ^[a-z]{2}-((iso[a-z]{0,1}-)|(gov-)){0,1}[a-z]+-{0,1}[0-9]{0,1}$
      minLength: 1
      maxLength: 64
    ReplicationConfigurationDescriptions:
      type: array
      items:
        $ref: '#/components/schemas/ReplicationConfigurationDescription'
    ReplicationOverwriteProtection:
      type: string
      enum:
      - ENABLED
      - DISABLED
      - REPLICATING
    ReplicationStatus:
      type: string
      enum:
      - ENABLED
      - ENABLING
      - DELETING
      - ERROR
      - PAUSED
      - PAUSING
    Resource:
      type: string
      enum:
      - FILE_SYSTEM
      - MOUNT_TARGET
      description: An EFS resource, for example a file system or a mount target.
    ResourceId:
      type: string
      pattern: ^(arn:aws[-a-z]*:elasticfilesystem:[0-9a-z-:]+:(access-point/fsap|file-system/fs)-[0-9a-f]{8,40}|fs(ap)?-[0-9a-f]{8,40})$
      minLength: 0
      maxLength: 128
    ResourceIdType:
      type: string
      enum:
      - LONG_ID
      - SHORT_ID
      description: A preference indicating a choice to use 63bit/32bit IDs for all
        applicable resources.
    Resources:
      type: array
      items:
        $ref: '#/components/schemas/Resource'
      description: EFS resources to which a preference applies to.
    RoleArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$
      minLength: 0
      maxLength: 2048
    SecondaryGids:
      type: array
      items:
        $ref: '#/components/schemas/Gid'
    SecurityGroup:
      type: string
      pattern: ^sg-[0-9a-f]{8,40}$
      minLength: 11
      maxLength: 43
    SecurityGroups:
      type: array
      items:
        $ref: '#/components/schemas/SecurityGroup'
    Status:
      type: string
      enum:
      - ENABLED
      - ENABLING
      - DISABLED
      - DISABLING
    StatusMessage:
      type: string
    SubnetId:
      type: string
      pattern: ^subnet-[0-9a-f]{8,40}$
      minLength: 15
      maxLength: 47
    TagKey:
      type: string
      pattern: ^(?![aA]{1}[wW]{1}[sS]{1}:)([\p{L}\p{Z}\p{N}_.:/=+\-@]+)$
      minLength: 1
      maxLength: 128
    TagKeys:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagValue:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
      minLength: 0
      maxLength: 256
    Tags:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    ThroughputMode:
      type: string
      enum:
      - bursting
      - provisioned
      - elastic
    Timestamp:
      type: string
      format: date-time
    Token:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 128
    TransitionToArchiveRules:
      type: string
      enum:
      - AFTER_1_DAY
      - AFTER_7_DAYS
      - AFTER_14_DAYS
      - AFTER_30_DAYS
      - AFTER_60_DAYS
      - AFTER_90_DAYS
      - AFTER_180_DAYS
      - AFTER_270_DAYS
      - AFTER_365_DAYS
    TransitionToIARules:
      type: string
      enum:
      - AFTER_7_DAYS
      - AFTER_14_DAYS
      - AFTER_30_DAYS
      - AFTER_60_DAYS
      - AFTER_90_DAYS
      - AFTER_1_DAY
      - AFTER_180_DAYS
      - AFTER_270_DAYS
      - AFTER_365_DAYS
    TransitionToPrimaryStorageClassRules:
      type: string
      enum:
      - AFTER_1_ACCESS
    Uid:
      type: integer
      format: int64
      minimum: 0
      maximum: 4294967295
    VpcId:
      type: string
