openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: eks
  x-aws-serviceName: eks
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-11-01'
  title: Amazon Elastic Kubernetes Service
  description: |-
    Amazon Elastic Kubernetes Service (Amazon EKS) is a managed service that makes it easy for you to run Kubernetes on Amazon Web Services without needing to setup or maintain your own Kubernetes control plane. Kubernetes is an open-source system for automating the deployment, scaling, and management of containerized applications.

    Amazon EKS runs up-to-date versions of the open-source Kubernetes software, so you can use all the existing plugins and tooling from the Kubernetes community. Applications running on Amazon EKS are fully compatible with applications running on any standard Kubernetes environment, whether running in on-premises data centers or public clouds. This means that you can easily migrate any standard Kubernetes application to Amazon EKS without any code modification required.
servers:
- description: The Amazon Elastic Kubernetes Service regional endpoint
  url: https://eks.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AMITypes:
      type: string
      enum:
      - AL2_x86_64
      - AL2_x86_64_GPU
      - AL2_ARM_64
      - CUSTOM
      - BOTTLEROCKET_ARM_64
      - BOTTLEROCKET_x86_64
      - BOTTLEROCKET_ARM_64_FIPS
      - BOTTLEROCKET_x86_64_FIPS
      - BOTTLEROCKET_ARM_64_NVIDIA
      - BOTTLEROCKET_x86_64_NVIDIA
      - WINDOWS_CORE_2019_x86_64
      - WINDOWS_FULL_2019_x86_64
      - WINDOWS_CORE_2022_x86_64
      - WINDOWS_FULL_2022_x86_64
      - AL2023_x86_64_STANDARD
      - AL2023_ARM_64_STANDARD
      - AL2023_x86_64_NEURON
      - AL2023_x86_64_NVIDIA
      - AL2023_ARM_64_NVIDIA
    AccessPoliciesList:
      type: array
      items:
        $ref: '#/components/schemas/AccessPolicy'
    AccessScopeType:
      type: string
      enum:
      - cluster
      - namespace
    AdditionalInfoMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    AddonCompatibilityDetails:
      type: array
      items:
        $ref: '#/components/schemas/AddonCompatibilityDetail'
    AddonIssueCode:
      type: string
      enum:
      - AccessDenied
      - InternalFailure
      - ClusterUnreachable
      - InsufficientNumberOfReplicas
      - ConfigurationConflict
      - AdmissionRequestDenied
      - UnsupportedAddonModification
      - K8sResourceNotFound
      - AddonSubscriptionNeeded
      - AddonPermissionFailure
    AddonIssueList:
      type: array
      items:
        $ref: '#/components/schemas/AddonIssue'
    AddonPodIdentityAssociationsList:
      type: array
      items:
        $ref: '#/components/schemas/AddonPodIdentityAssociations'
    AddonPodIdentityConfigurationList:
      type: array
      items:
        $ref: '#/components/schemas/AddonPodIdentityConfiguration'
    AddonStatus:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - CREATE_FAILED
      - UPDATING
      - DELETING
      - DELETE_FAILED
      - DEGRADED
      - UPDATE_FAILED
    AddonVersionInfoList:
      type: array
      items:
        $ref: '#/components/schemas/AddonVersionInfo'
    Addons:
      type: array
      items:
        $ref: '#/components/schemas/AddonInfo'
    AssociatedAccessPoliciesList:
      type: array
      items:
        $ref: '#/components/schemas/AssociatedAccessPolicy'
    AuthenticationMode:
      type: string
      enum:
      - API
      - API_AND_CONFIG_MAP
      - CONFIG_MAP
    AutoScalingGroupList:
      type: array
      items:
        $ref: '#/components/schemas/AutoScalingGroup'
    Boolean:
      type: boolean
      default: false
    BoxedBoolean:
      type: boolean
    BoxedInteger:
      type: integer
    Capacity:
      type: integer
      minimum: 1
    CapacityTypes:
      type: string
      enum:
      - ON_DEMAND
      - SPOT
      - CAPACITY_BLOCK
    Category:
      type: string
      enum:
      - UPGRADE_READINESS
    CategoryList:
      type: array
      items:
        $ref: '#/components/schemas/Category'
    ClientStats:
      type: array
      items:
        $ref: '#/components/schemas/ClientStat'
    ClusterIssueCode:
      type: string
      enum:
      - AccessDenied
      - ClusterUnreachable
      - ConfigurationConflict
      - InternalFailure
      - ResourceLimitExceeded
      - ResourceNotFound
      - IamRoleNotFound
      - VpcNotFound
      - InsufficientFreeAddresses
      - Ec2ServiceNotSubscribed
      - Ec2SubnetNotFound
      - Ec2SecurityGroupNotFound
      - KmsGrantRevoked
      - KmsKeyNotFound
      - KmsKeyMarkedForDeletion
      - KmsKeyDisabled
      - StsRegionalEndpointDisabled
      - UnsupportedVersion
      - Other
    ClusterIssueList:
      type: array
      items:
        $ref: '#/components/schemas/ClusterIssue'
    ClusterName:
      type: string
      pattern: ^[0-9A-Za-z][A-Za-z0-9\-_]*$
      minLength: 1
      maxLength: 100
    ClusterStatus:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - DELETING
      - FAILED
      - UPDATING
      - PENDING
    ClusterVersionList:
      type: array
      items:
        $ref: '#/components/schemas/ClusterVersionInformation'
    ClusterVersionStatus:
      type: string
      enum:
      - unsupported
      - standard-support
      - extended-support
    Compatibilities:
      type: array
      items:
        $ref: '#/components/schemas/Compatibility'
    ConnectorConfigProvider:
      type: string
      enum:
      - EKS_ANYWHERE
      - ANTHOS
      - GKE
      - AKS
      - OPENSHIFT
      - TANZU
      - RANCHER
      - EC2
      - OTHER
    DeprecationDetails:
      type: array
      items:
        $ref: '#/components/schemas/DeprecationDetail'
    DescribeAddonVersionsRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    DescribeClusterVersionMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    EksAnywhereSubscriptionLicenseType:
      type: string
      enum:
      - Cluster
    EksAnywhereSubscriptionList:
      type: array
      items:
        $ref: '#/components/schemas/EksAnywhereSubscription'
    EksAnywhereSubscriptionName:
      type: string
      pattern: ^[0-9A-Za-z][A-Za-z0-9\-_]*$
      minLength: 1
      maxLength: 100
    EksAnywhereSubscriptionStatus:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - UPDATING
      - EXPIRING
      - EXPIRED
      - DELETING
    EksAnywhereSubscriptionStatusValues:
      type: array
      items:
        $ref: '#/components/schemas/EksAnywhereSubscriptionStatus'
    EksAnywhereSubscriptionTermUnit:
      type: string
      enum:
      - MONTHS
    EncryptionConfigList:
      type: array
      items:
        $ref: '#/components/schemas/EncryptionConfig'
    ErrorCode:
      type: string
      enum:
      - SubnetNotFound
      - SecurityGroupNotFound
      - EniLimitReached
      - IpNotAvailable
      - AccessDenied
      - OperationNotPermitted
      - VpcIdNotFound
      - Unknown
      - NodeCreationFailure
      - PodEvictionFailure
      - InsufficientFreeAddresses
      - ClusterUnreachable
      - InsufficientNumberOfReplicas
      - ConfigurationConflict
      - AdmissionRequestDenied
      - UnsupportedAddonModification
      - K8sResourceNotFound
    ErrorDetails:
      type: array
      items:
        $ref: '#/components/schemas/ErrorDetail'
    FargateProfileIssueCode:
      type: string
      enum:
      - PodExecutionRoleAlreadyInUse
      - AccessDenied
      - ClusterUnreachable
      - InternalFailure
    FargateProfileIssueList:
      type: array
      items:
        $ref: '#/components/schemas/FargateProfileIssue'
    FargateProfileLabel:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    FargateProfileSelectors:
      type: array
      items:
        $ref: '#/components/schemas/FargateProfileSelector'
    FargateProfileStatus:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - DELETING
      - CREATE_FAILED
      - DELETE_FAILED
    FargateProfilesRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    IdentityProviderConfigs:
      type: array
      items:
        $ref: '#/components/schemas/IdentityProviderConfig'
    IncludeClustersList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    InsightResourceDetails:
      type: array
      items:
        $ref: '#/components/schemas/InsightResourceDetail'
    InsightStatusValue:
      type: string
      enum:
      - PASSING
      - WARNING
      - ERROR
      - UNKNOWN
    InsightStatusValueList:
      type: array
      items:
        $ref: '#/components/schemas/InsightStatusValue'
    InsightSummaries:
      type: array
      items:
        $ref: '#/components/schemas/InsightSummary'
    Integer:
      type: integer
      default: 0
    IpFamily:
      type: string
      enum:
      - ipv4
      - ipv6
    IssueList:
      type: array
      items:
        $ref: '#/components/schemas/Issue'
    LicenseList:
      type: array
      items:
        $ref: '#/components/schemas/License'
    ListAccessEntriesRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListAccessPoliciesRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListAddonsRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListAssociatedAccessPoliciesRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListClustersRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListEksAnywhereSubscriptionsRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListIdentityProviderConfigsRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListInsightsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListNodegroupsRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListPodIdentityAssociationsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListUpdatesRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    LogSetups:
      type: array
      items:
        $ref: '#/components/schemas/LogSetup'
    LogType:
      type: string
      enum:
      - api
      - audit
      - authenticator
      - controllerManager
      - scheduler
    LogTypes:
      type: array
      items:
        $ref: '#/components/schemas/LogType'
    NodegroupIssueCode:
      type: string
      enum:
      - AutoScalingGroupNotFound
      - AutoScalingGroupInvalidConfiguration
      - Ec2SecurityGroupNotFound
      - Ec2SecurityGroupDeletionFailure
      - Ec2LaunchTemplateNotFound
      - Ec2LaunchTemplateVersionMismatch
      - Ec2SubnetNotFound
      - Ec2SubnetInvalidConfiguration
      - IamInstanceProfileNotFound
      - Ec2SubnetMissingIpv6Assignment
      - IamLimitExceeded
      - IamNodeRoleNotFound
      - NodeCreationFailure
      - AsgInstanceLaunchFailures
      - InstanceLimitExceeded
      - InsufficientFreeAddresses
      - AccessDenied
      - InternalFailure
      - ClusterUnreachable
      - AmiIdNotFound
      - AutoScalingGroupOptInRequired
      - AutoScalingGroupRateLimitExceeded
      - Ec2LaunchTemplateDeletionFailure
      - Ec2LaunchTemplateInvalidConfiguration
      - Ec2LaunchTemplateMaxLimitExceeded
      - Ec2SubnetListTooLong
      - IamThrottling
      - NodeTerminationFailure
      - PodEvictionFailure
      - SourceEc2LaunchTemplateNotFound
      - LimitExceeded
      - Unknown
      - AutoScalingGroupInstanceRefreshActive
      - KubernetesLabelInvalid
      - Ec2LaunchTemplateVersionMaxLimitExceeded
      - Ec2InstanceTypeDoesNotExist
    NodegroupStatus:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - UPDATING
      - DELETING
      - CREATE_FAILED
      - DELETE_FAILED
      - DEGRADED
    NodegroupUpdateStrategies:
      type: string
      enum:
      - DEFAULT
      - MINIMAL
    NonZeroInteger:
      type: integer
      minimum: 1
    PercentCapacity:
      type: integer
      minimum: 1
      maximum: 100
    PodIdentityAssociationSummaries:
      type: array
      items:
        $ref: '#/components/schemas/PodIdentityAssociationSummary'
    RemoteNodeNetworkList:
      type: array
      items:
        $ref: '#/components/schemas/RemoteNodeNetwork'
    RemotePodNetworkList:
      type: array
      items:
        $ref: '#/components/schemas/RemotePodNetwork'
    ResolveConflicts:
      type: string
      enum:
      - OVERWRITE
      - NONE
      - PRESERVE
    RoleArn:
      type: string
      minLength: 1
      maxLength: 255
    String:
      type: string
    StringList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    SupportType:
      type: string
      enum:
      - STANDARD
      - EXTENDED
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
      description: "<p>The metadata that you apply to a resource to help you categorize\
        \ and organize them.\n            Each tag consists of a key and an optional\
        \ value. You define them.</p>\n         <p>The following basic restrictions\
        \ apply to tags:</p>\n         <ul>\n            <li>\n               <p>Maximum\
        \ number of tags per resource – 50</p>\n            </li>\n            <li>\n\
        \               <p>For each resource, each tag key must be unique, and each\
        \ tag key can have only\n                    one value.</p>\n            </li>\n\
        \            <li>\n               <p>Maximum key length – 128 Unicode characters\
        \ in UTF-8</p>\n            </li>\n            <li>\n               <p>Maximum\
        \ value length – 256 Unicode characters in UTF-8</p>\n            </li>\n\
        \            <li>\n               <p>If your tagging schema is used across\
        \ multiple services and resources,\n                    remember that other\
        \ services may have restrictions on allowed characters.\n                \
        \    Generally allowed characters are: letters, numbers, and spaces representable\
        \ in\n                    UTF-8, and the following characters: + - = . _ :\
        \ / @.</p>\n            </li>\n            <li>\n               <p>Tag keys\
        \ and values are case-sensitive.</p>\n            </li>\n            <li>\n\
        \               <p>Do not use <code>aws:</code>, <code>AWS:</code>, or any\
        \ upper or lowercase\n                    combination of such as a prefix\
        \ for either keys or values as it is reserved for\n                    Amazon\
        \ Web Services use. You cannot edit or delete tag keys or values with this\
        \ prefix. Tags with\n                    this prefix do not count against\
        \ your tags per resource limit.</p>\n            </li>\n         </ul>"
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TaintEffect:
      type: string
      enum:
      - NO_SCHEDULE
      - NO_EXECUTE
      - PREFER_NO_SCHEDULE
    Timestamp:
      type: string
      format: date-time
    UpdateParamType:
      type: string
      enum:
      - Version
      - PlatformVersion
      - EndpointPrivateAccess
      - EndpointPublicAccess
      - ClusterLogging
      - DesiredSize
      - LabelsToAdd
      - LabelsToRemove
      - TaintsToAdd
      - TaintsToRemove
      - MaxSize
      - MinSize
      - ReleaseVersion
      - PublicAccessCidrs
      - LaunchTemplateName
      - LaunchTemplateVersion
      - IdentityProviderConfig
      - EncryptionConfig
      - AddonVersion
      - ServiceAccountRoleArn
      - ResolveConflicts
      - MaxUnavailable
      - MaxUnavailablePercentage
      - NodeRepairEnabled
      - UpdateStrategy
      - ConfigurationValues
      - SecurityGroups
      - Subnets
      - AuthenticationMode
      - PodIdentityAssociations
      - UpgradePolicy
      - ZonalShiftConfig
      - ComputeConfig
      - StorageConfig
      - KubernetesNetworkConfig
      - RemoteNetworkConfig
    UpdateParams:
      type: array
      items:
        $ref: '#/components/schemas/UpdateParam'
    UpdateStatus:
      type: string
      enum:
      - InProgress
      - Failed
      - Cancelled
      - Successful
    UpdateType:
      type: string
      enum:
      - VersionUpdate
      - EndpointAccessUpdate
      - LoggingUpdate
      - ConfigUpdate
      - AssociateIdentityProviderConfig
      - DisassociateIdentityProviderConfig
      - AssociateEncryptionConfig
      - AddonUpdate
      - VpcConfigUpdate
      - AccessConfigUpdate
      - UpgradePolicyUpdate
      - ZonalShiftConfigUpdate
      - AutoModeUpdate
      - RemoteNetworkConfigUpdate
    VersionStatus:
      type: string
      enum:
      - UNSUPPORTED
      - STANDARD_SUPPORT
      - EXTENDED_SUPPORT
    ZeroCapacity:
      type: integer
      minimum: 0
    configStatus:
      type: string
      enum:
      - CREATING
      - DELETING
      - ACTIVE
    labelKey:
      type: string
      minLength: 1
      maxLength: 63
    labelValue:
      type: string
      minLength: 1
      maxLength: 63
    labelsKeyList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    labelsMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/labelValue'
    requiredClaimsKey:
      type: string
      minLength: 1
      maxLength: 63
    requiredClaimsMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/requiredClaimsValue'
    requiredClaimsValue:
      type: string
      minLength: 1
      maxLength: 253
    taintKey:
      type: string
      minLength: 1
      maxLength: 63
    taintValue:
      type: string
      minLength: 0
      maxLength: 63
    taintsList:
      type: array
      items:
        $ref: '#/components/schemas/Taint'
