openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: eks
  x-aws-serviceName: eks
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-11-01'
  title: Amazon Elastic Kubernetes Service
  description: |-
    Amazon Elastic Kubernetes Service (Amazon EKS) is a managed service that makes it easy for you to run Kubernetes on Amazon Web Services without needing to setup or maintain your own Kubernetes control plane. Kubernetes is an open-source system for automating the deployment, scaling, and management of containerized applications.

    Amazon EKS runs up-to-date versions of the open-source Kubernetes software, so you can use all the existing plugins and tooling from the Kubernetes community. Applications running on Amazon EKS are fully compatible with applications running on any standard Kubernetes environment, whether running in on-premises data centers or public clouds. This means that you can easily migrate any standard Kubernetes application to Amazon EKS without any code modification required.
servers:
- description: The Amazon Elastic Kubernetes Service regional endpoint
  url: https://eks.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Boolean:
      type: boolean
      default: false
    BoxedBoolean:
      type: boolean
    BoxedInteger:
      type: integer
    Capacity:
      type: integer
      minimum: 1
    ClusterName:
      type: string
      pattern: ^[0-9A-Za-z][A-Za-z0-9\-_]*$
      minLength: 1
      maxLength: 100
    DescribeAddonVersionsRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    DescribeClusterVersionMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    EksAnywhereSubscriptionName:
      type: string
      pattern: ^[0-9A-Za-z][A-Za-z0-9\-_]*$
      minLength: 1
      maxLength: 100
    FargateProfilesRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    Integer:
      type: integer
      default: 0
    ListAccessEntriesRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListAccessPoliciesRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListAddonsRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListAssociatedAccessPoliciesRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListClustersRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListEksAnywhereSubscriptionsRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListIdentityProviderConfigsRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListInsightsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListNodegroupsRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListPodIdentityAssociationsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListUpdatesRequestMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    NonZeroInteger:
      type: integer
      minimum: 1
    PercentCapacity:
      type: integer
      minimum: 1
      maximum: 100
    RoleArn:
      type: string
      minLength: 1
      maxLength: 255
    String:
      type: string
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    ZeroCapacity:
      type: integer
      minimum: 0
    labelKey:
      type: string
      minLength: 1
      maxLength: 63
    labelValue:
      type: string
      minLength: 1
      maxLength: 63
    requiredClaimsKey:
      type: string
      minLength: 1
      maxLength: 63
    requiredClaimsValue:
      type: string
      minLength: 1
      maxLength: 253
    taintKey:
      type: string
      minLength: 1
      maxLength: 63
    taintValue:
      type: string
      minLength: 0
      maxLength: 63
