openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: elastic_transcoder
  x-aws-serviceName: elastictranscoder
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2012-09-25'
  title: Amazon Elastic Transcoder
  description: |-
    AWS Elastic Transcoder Service

    The AWS Elastic Transcoder Service.
servers:
- description: The Amazon Elastic Transcoder regional endpoint
  url: https://elastictranscoder.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccessControl:
      type: string
      pattern: ^(^FullControl$)|(^Read$)|(^ReadAcp$)|(^WriteAcp$)$
    Ascending:
      type: string
      pattern: ^(^true$)|(^false$)$
    AspectRatio:
      type: string
      pattern: ^(^auto$)|(^1:1$)|(^4:3$)|(^3:2$)|(^16:9$)$
    AudioBitDepth:
      type: string
      pattern: ^(^8$)|(^16$)|(^24$)|(^32$)$
    AudioBitOrder:
      type: string
      pattern: ^(^LittleEndian$)$
    AudioBitRate:
      type: string
      pattern: ^\d{1,3}$
    AudioChannels:
      type: string
      pattern: ^(^auto$)|(^0$)|(^1$)|(^2$)$
    AudioCodec:
      type: string
      pattern: ^(^AAC$)|(^vorbis$)|(^mp3$)|(^mp2$)|(^pcm$)|(^flac$)$
    AudioCodecProfile:
      type: string
      pattern: ^(^auto$)|(^AAC-LC$)|(^HE-AAC$)|(^HE-AACv2$)$
    AudioPackingMode:
      type: string
      pattern: ^(^SingleTrack$)|(^OneChannelPerTrack$)|(^OneChannelPerTrackWithMosTo8Tracks$)$
    AudioSampleRate:
      type: string
      pattern: ^(^auto$)|(^22050$)|(^32000$)|(^44100$)|(^48000$)|(^96000$)|(^192000$)$
    AudioSigned:
      type: string
      pattern: ^(^Unsigned$)|(^Signed$)$
    Base64EncodedString:
      type: string
      pattern: ^$|(^(?:[A-Za-z0-9\+/]{4})*(?:[A-Za-z0-9\+/]{2}==|[A-Za-z0-9\+/]{3}=)?$)$
    BucketName:
      type: string
      pattern: ^(\w|\.|-){1,255}$
    CaptionFormatFormat:
      type: string
      pattern: ^(^mov-text$)|(^srt$)|(^scc$)|(^webvtt$)|(^dfxp$)|(^cea-708$)$
    CaptionFormatPattern:
      type: string
      pattern: ^(^$)|(^.*\{language\}.*$)$
    CaptionMergePolicy:
      type: string
      pattern: ^(^MergeOverride$)|(^MergeRetain$)|(^Override$)$
    CodecOption:
      type: string
      minLength: 1
      maxLength: 255
    Description:
      type: string
      minLength: 0
      maxLength: 255
    Digits:
      type: string
      pattern: ^\d{1,5}$
    DigitsOrAuto:
      type: string
      pattern: ^(^auto$)|(^\d{2,4}$)$
    EncryptionMode:
      type: string
      pattern: ^(^s3$)|(^s3-aws-kms$)|(^aes-cbc-pkcs7$)|(^aes-ctr$)|(^aes-gcm$)$
    ExceptionMessage:
      type: string
    Filename:
      type: string
      minLength: 1
      maxLength: 255
    FixedGOP:
      type: string
      pattern: ^(^true$)|(^false$)$
    FloatString:
      type: string
      pattern: ^\d{1,5}(\.\d{0,5})?$
    FrameRate:
      type: string
      pattern: ^(^auto$)|(^10$)|(^15$)|(^23.97$)|(^24$)|(^25$)|(^29.97$)|(^30$)|(^50$)|(^60$)$
    Grantee:
      type: string
      minLength: 1
      maxLength: 255
    GranteeType:
      type: string
      pattern: ^(^Canonical$)|(^Email$)|(^Group$)$
    HlsContentProtectionMethod:
      type: string
      pattern: ^(^aes-128$)$
    HorizontalAlign:
      type: string
      pattern: ^(^Left$)|(^Right$)|(^Center$)$
    Id:
      type: string
      pattern: ^\d{13}-\w{6}$
    Interlaced:
      type: string
      pattern: ^(^auto$)|(^true$)|(^false$)$
    JobContainer:
      type: string
      pattern: ^(^auto$)|(^3gp$)|(^asf$)|(^avi$)|(^divx$)|(^flv$)|(^mkv$)|(^mov$)|(^mp4$)|(^mpeg$)|(^mpeg-ps$)|(^mpeg-ts$)|(^mxf$)|(^ogg$)|(^ts$)|(^vob$)|(^wav$)|(^webm$)|(^mp3$)|(^m4a$)|(^aac$)$
    JobStatus:
      type: string
      pattern: ^(^Submitted$)|(^Progressing$)|(^Complete$)|(^Canceled$)|(^Error$)$
    JpgOrPng:
      type: string
      pattern: ^(^jpg$)|(^png$)$
    Key:
      type: string
      minLength: 1
      maxLength: 255
    KeyArn:
      type: string
      minLength: 0
      maxLength: 255
    KeyIdGuid:
      type: string
      pattern: ^(^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$)|(^[0-9A-Fa-f]{32}$)$
    KeyStoragePolicy:
      type: string
      pattern: ^(^NoStore$)|(^WithVariantPlaylists$)$
    KeyframesMaxDist:
      type: string
      pattern: ^\d{1,6}$
    LongKey:
      type: string
      minLength: 1
      maxLength: 1024
    MaxFrameRate:
      type: string
      pattern: ^(^10$)|(^15$)|(^23.97$)|(^24$)|(^25$)|(^29.97$)|(^30$)|(^50$)|(^60$)$
    MergePolicy:
      type: string
      pattern: ^(^Replace$)|(^Prepend$)|(^Append$)|(^Fallback$)$
    Name:
      type: string
      minLength: 1
      maxLength: 40
    NonEmptyBase64EncodedString:
      type: string
      pattern: ^(^(?:[A-Za-z0-9\+/]{4})*(?:[A-Za-z0-9\+/]{2}==|[A-Za-z0-9\+/]{3}=)?$)$
    NullableInteger:
      type: integer
    OneTo512String:
      type: string
      minLength: 1
      maxLength: 512
    Opacity:
      type: string
      pattern: ^\d{1,3}(\.\d{0,20})?$
    PaddingPolicy:
      type: string
      pattern: ^(^Pad$)|(^NoPad$)$
    PipelineStatus:
      type: string
      pattern: ^(^Active$)|(^Paused$)$
    PixelsOrPercent:
      type: string
      pattern: ^(^\d{1,3}(\.\d{0,5})?%$)|(^\d{1,4}?px$)$
    PlayReadyDrmFormatString:
      type: string
      pattern: ^(^microsoft$)|(^discretix-3.0$)$
    PlaylistFormat:
      type: string
      pattern: ^(^HLSv3$)|(^HLSv4$)|(^Smooth$)|(^MPEG-DASH$)$
    PresetContainer:
      type: string
      pattern: ^(^mp4$)|(^ts$)|(^webm$)|(^mp3$)|(^flac$)|(^oga$)|(^ogg$)|(^fmp4$)|(^mpg$)|(^flv$)|(^gif$)|(^mxf$)|(^wav$)|(^mp2$)$
    PresetType:
      type: string
      pattern: ^(^System$)|(^Custom$)$
    PresetWatermarkId:
      type: string
      minLength: 1
      maxLength: 40
    Resolution:
      type: string
      pattern: ^(^auto$)|(^\d{1,5}x\d{1,5}$)$
    Role:
      type: string
      pattern: ^arn:aws:iam::\w{12}:role/.+$
    Rotate:
      type: string
      pattern: ^(^auto$)|(^0$)|(^90$)|(^180$)|(^270$)$
    SizingPolicy:
      type: string
      pattern: ^(^Fit$)|(^Fill$)|(^Stretch$)|(^Keep$)|(^ShrinkToFit$)|(^ShrinkToFill$)$
    SnsTopic:
      type: string
      pattern: ^(^$)|(^arn:aws:sns:.*:\w{12}:.+$)$
    StorageClass:
      type: string
      pattern: ^(^ReducedRedundancy$)|(^Standard$)$
    String:
      type: string
    Success:
      type: string
      pattern: ^(^true$)|(^false$)$
    Target:
      type: string
      pattern: ^(^Content$)|(^Frame$)$
    ThumbnailPattern:
      type: string
      pattern: ^(^$)|(^.*\{count\}.*$)$
    ThumbnailResolution:
      type: string
      pattern: ^\d{1,5}x\d{1,5}$
    Time:
      type: string
      pattern: ^(^\d{1,5}(\.\d{0,3})?$)|(^([0-1]?[0-9]:|2[0-3]:)?([0-5]?[0-9]:)?[0-5]?[0-9](\.\d{0,3})?$)$
    TimeOffset:
      type: string
      pattern: ^(^[+-]?\d{1,5}(\.\d{0,3})?$)|(^[+-]?([0-1]?[0-9]:|2[0-3]:)?([0-5]?[0-9]:)?[0-5]?[0-9](\.\d{0,3})?$)$
    VerticalAlign:
      type: string
      pattern: ^(^Top$)|(^Bottom$)|(^Center$)$
    VideoBitRate:
      type: string
      pattern: ^(^\d{2,5}$)|(^auto$)$
    VideoCodec:
      type: string
      pattern: ^(^H\.264$)|(^vp8$)|(^vp9$)|(^mpeg2$)|(^gif$)$
    WatermarkKey:
      type: string
      pattern: ^(^.{1,1020}.jpg$)|(^.{1,1019}.jpeg$)|(^.{1,1020}.png$)$
      minLength: 1
      maxLength: 1024
    WatermarkSizingPolicy:
      type: string
      pattern: ^(^Fit$)|(^Stretch$)|(^ShrinkToFit$)$
    ZeroTo255String:
      type: string
      minLength: 0
      maxLength: 255
    ZeroTo512String:
      type: string
      minLength: 0
      maxLength: 512
