openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: elasticsearch_service
  x-aws-serviceName: elasticsearchservice
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2015-01-01'
  title: Amazon Elasticsearch Service
  description: |-
    Amazon Elasticsearch Configuration Service

    Use the Amazon Elasticsearch Configuration API to create, configure, and manage Elasticsearch domains.

    For sample code that uses the Configuration API, see the [Amazon Elasticsearch Service Developer Guide](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-configuration-samples.html). The guide also contains [sample code for sending signed HTTP requests to the Elasticsearch APIs](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html).

    The endpoint for configuration service requests is region-specific: es._region_.amazonaws.com. For example, es.us-east-1.amazonaws.com. For a current list of supported regions and endpoints, see [Regions and Endpoints](http://docs.aws.amazon.com/general/latest/gr/rande.html#elasticsearch-service-regions).
servers:
- description: The Amazon Elasticsearch Service regional endpoint
  url: https://es.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ARN:
      type: string
    AWSAccount:
      type: string
      pattern: ^[0-9]+$
    BackendRole:
      type: string
      minLength: 1
      maxLength: 256
    Boolean:
      type: boolean
    ChangeProgressStageName:
      type: string
      minLength: 1
      maxLength: 64
    ChangeProgressStageStatus:
      type: string
      minLength: 1
      maxLength: 256
    ClientToken:
      type: string
      minLength: 1
      maxLength: 64
    CloudWatchLogsLogGroupArn:
      type: string
    CommitMessage:
      type: string
      minLength: 0
      maxLength: 160
    ConnectionAlias:
      type: string
      minLength: 0
      maxLength: 20
    CrossClusterSearchConnectionId:
      type: string
    CrossClusterSearchConnectionStatusMessage:
      type: string
    DeploymentType:
      type: string
      minLength: 2
      maxLength: 128
    DescribePackagesFilterValue:
      type: string
      pattern: ^[0-9a-zA-Z\*\.\\/\?-]*$
    Description:
      type: string
    DomainArn:
      type: string
      pattern: ^arn:aws[a-z\-]*:[a-z]+:[a-z0-9\-]+:[0-9]+:domain\/[a-z0-9\-]+$
      minLength: 1
      maxLength: 512
    DomainId:
      type: string
      minLength: 1
      maxLength: 64
    DomainName:
      type: string
      pattern: ^[a-z][a-z0-9\-]+$
      minLength: 3
      maxLength: 28
    DomainNameFqdn:
      type: string
      pattern: ^(((?!-)[A-Za-z0-9-]{0,62}[A-Za-z0-9])\.)+((?!-)[A-Za-z0-9-]{1,62}[A-Za-z0-9])$
      minLength: 1
      maxLength: 255
    DryRun:
      type: boolean
    ElasticsearchVersionString:
      type: string
      pattern: ^[0-9]{1}\.[0-9]{1,2}$|^OpenSearch_[0-9]{1,2}\.[0-9]{1,2}$|^OS_[0-9]{1,2}\.[0-9]{1,2}$
    Endpoint:
      type: string
      pattern: ^[A-Za-z0-9\-\.]+$
    ErrorMessage:
      type: string
    ErrorType:
      type: string
    GUID:
      type: string
      pattern: ^\p{XDigit}{8}-\p{XDigit}{4}-\p{XDigit}{4}-\p{XDigit}{4}-\p{XDigit}{12}$
    IdentityPoolId:
      type: string
      pattern: ^[\w-]+:[0-9a-f-]+$
      minLength: 1
      maxLength: 55
    InstanceCount:
      type: integer
      minimum: 1
      description: <p>Specifies the number of EC2 instances in the Elasticsearch domain.</p>
    InstanceRole:
      type: string
    Integer:
      type: integer
      default: 0
    IntegerClass:
      type: integer
    Issue:
      type: string
    KmsKeyId:
      type: string
      minLength: 1
      maxLength: 500
    LimitName:
      type: string
    LimitValue:
      type: string
    MaxResults:
      type: integer
      default: 0
      maximum: 100
      description: "<p>\n      Set this value to limit the number of results returned.\n\
        \    </p>"
    MaximumInstanceCount:
      type: integer
      default: 0
      description: "<p>\n      Maximum number of Instances that can be instantiated\
        \ for given InstanceType.\n    </p>"
    Message:
      type: string
      minLength: 0
      maxLength: 1024
    MinimumInstanceCount:
      type: integer
      default: 0
      description: "<p>\n      Minimum number of Instances that can be instantiated\
        \ for given InstanceType.\n    </p>"
    NextToken:
      type: string
    NonEmptyString:
      type: string
      minLength: 1
    OwnerId:
      type: string
      minLength: 12
      maxLength: 12
    PackageDescription:
      type: string
      minLength: 0
      maxLength: 1024
    PackageID:
      type: string
    PackageName:
      type: string
      pattern: ^[a-z][a-z0-9\-]+$
      minLength: 3
      maxLength: 28
    PackageVersion:
      type: string
    Password:
      type: string
      minLength: 8
    PolicyDocument:
      type: string
    ReferencePath:
      type: string
    Region:
      type: string
    ReservationToken:
      type: string
      minLength: 5
      maxLength: 64
    RoleArn:
      type: string
      minLength: 20
      maxLength: 2048
    S3BucketName:
      type: string
      minLength: 3
      maxLength: 63
    S3Key:
      type: string
    SAMLEntityId:
      type: string
      minLength: 8
      maxLength: 512
    SAMLMetadata:
      type: string
      minLength: 1
      maxLength: 1048576
    ScheduledAutoTuneDescription:
      type: string
    ServiceUrl:
      type: string
    StorageSubTypeName:
      type: string
    StorageTypeName:
      type: string
    String:
      type: string
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TotalNumberOfStages:
      type: integer
      default: 0
    UIntValue:
      type: integer
      default: 0
      minimum: 0
    UpgradeName:
      type: string
    UserPoolId:
      type: string
      pattern: ^[\w-]+_[0-9a-zA-Z]+$
      minLength: 1
      maxLength: 55
    Username:
      type: string
      minLength: 1
    VpcEndpointId:
      type: string
      pattern: ^aos-[a-zA-Z0-9]*$
      minLength: 5
      maxLength: 256
