openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: emr_serverless
  x-aws-serviceName: emrserverless
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2021-07-13'
  title: EMR Serverless
  description: |-
    Amazon EMR Serverless is a new deployment option for Amazon EMR. Amazon EMR Serverless provides a serverless runtime environment that simplifies running analytics applications using the latest open source frameworks such as Apache Spark and Apache Hive. With Amazon EMR Serverless, you don’t have to configure, optimize, secure, or operate clusters to run applications with these frameworks.

    The API reference to Amazon EMR Serverless is `emr-serverless`. The `emr-serverless` prefix is used in the following scenarios:

      * It is the prefix in the CLI commands for Amazon EMR Serverless. For example, `aws emr-serverless start-job-run`.

      * It is the prefix before IAM policy actions for Amazon EMR Serverless. For example, `"Action": ["emr-serverless:StartJobRun"]`. For more information, see [Policy actions for Amazon EMR Serverless](https://docs.aws.amazon.com/emr/latest/EMR-Serverless-UserGuide/security_iam_service-with-iam.html#security_iam_service-with-iam-id-based-policies-actions).

      * It is the prefix used in Amazon EMR Serverless service endpoints. For example, `emr-serverless.us-east-2.amazonaws.com`.
servers:
- description: The EMR Serverless regional endpoint
  url: https://emr-serverless.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ApplicationArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z0-9-]*):emr-serverless:.+:(\d{12}):\/applications\/[0-9a-zA-Z]+$
      minLength: 60
      maxLength: 1024
    ApplicationId:
      type: string
      pattern: ^[0-9a-z]+$
      minLength: 1
      maxLength: 64
    ApplicationName:
      type: string
      pattern: ^[A-Za-z0-9._/#-]+$
      minLength: 1
      maxLength: 64
    ApplicationState:
      type: string
      enum:
      - CREATING
      - CREATED
      - STARTING
      - STARTED
      - STOPPING
      - STOPPED
      - TERMINATED
    Architecture:
      type: string
      enum:
      - ARM64
      - X86_64
    AttemptNumber:
      type: integer
      minimum: 1
    ClientToken:
      type: string
      pattern: ^[A-Za-z0-9._-]+$
      minLength: 1
      maxLength: 64
    ConfigurationPropertyKey:
      type: string
      pattern: ^.*\S.*$
      minLength: 1
      maxLength: 1024
    ConfigurationPropertyValue:
      type: string
      pattern: ^.*\S.*$
      minLength: 0
      maxLength: 1024
    CpuSize:
      type: string
      pattern: ^[1-9][0-9]*(\s)?(vCPU|vcpu|VCPU)?$
      minLength: 1
      maxLength: 15
    DiskSize:
      type: string
      pattern: ^[1-9][0-9]*(\s)?(GB|gb|gB|Gb)$
      minLength: 1
      maxLength: 15
    DiskType:
      type: string
      pattern: ^(SHUFFLE_OPTIMIZED|[Ss]huffle_[Oo]ptimized|STANDARD|[Ss]tandard)$
    EncryptionKeyArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z0-9-]*):kms:[a-zA-Z0-9\-]*:([0-9]{12}):key\/[a-zA-Z0-9-]+$
      minLength: 20
      maxLength: 2048
    EngineType:
      type: string
      minLength: 1
      maxLength: 64
    EntryPointArgument:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 10280
    EntryPointPath:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 4096
    HiveCliParameters:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 102400
    IAMRoleArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z0-9-]*):iam::([0-9]{12}):(role((\u002F)|(\u002F[\u0021-\u007F]+\u002F))[\w+=,.@-]+)$
      minLength: 20
      maxLength: 2048
    ImageDigest:
      type: string
      pattern: ^sha256:[0-9a-f]{64}$
    ImageUri:
      type: string
      pattern: ^([0-9]{12})\.dkr\.ecr\.([a-z0-9-]+).([a-z0-9._-]+)\/((?:[a-z0-9]+(?:[-._][a-z0-9]+)*/)*[a-z0-9]+(?:[-._][a-z0-9]+)*)(?::([a-zA-Z0-9_]+[a-zA-Z0-9-._]*)|@(sha256:[0-9a-f]{64}))$
      minLength: 1
      maxLength: 1024
    InitScriptPath:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 256
    JobArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z0-9-]*):emr-serverless:.+:(\d{12}):\/applications\/[0-9a-zA-Z]+\/jobruns\/[0-9a-zA-Z]+$
      minLength: 60
      maxLength: 1024
    JobRunId:
      type: string
      pattern: ^[0-9a-z]+$
      minLength: 1
      maxLength: 64
    JobRunMode:
      type: string
      enum:
      - BATCH
      - STREAMING
    JobRunState:
      type: string
      enum:
      - SUBMITTED
      - PENDING
      - SCHEDULED
      - RUNNING
      - SUCCESS
      - FAILED
      - CANCELLING
      - CANCELLED
      - QUEUED
    JobRunType:
      type: string
    LogGroupName:
      type: string
      pattern: ^[\.\-_/#A-Za-z0-9]+$
      minLength: 1
      maxLength: 512
    LogStreamNamePrefix:
      type: string
      pattern: ^[^:*]*$
      minLength: 1
      maxLength: 512
    LogTypeString:
      type: string
      pattern: ^[a-zA-Z]+[-_]*[a-zA-Z]+$
      minLength: 1
      maxLength: 50
    MemorySize:
      type: string
      pattern: ^[1-9][0-9]*(\s)?(GB|gb|gB|Gb)?$
      minLength: 1
      maxLength: 15
    NextToken:
      type: string
      pattern: ^[A-Za-z0-9_=-]+$
      minLength: 1
      maxLength: 1024
    PrometheusUrlString:
      type: string
      pattern: ^https://aps-workspaces.([a-z]{2}-[a-z-]{1,20}-[1-9]).amazonaws(.[0-9A-Za-z]{2,4})+/workspaces/[-_.0-9A-Za-z]{1,100}/api/v1/remote_write$
      minLength: 1
      maxLength: 10280
    Query:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 10280
    ReleaseLabel:
      type: string
      pattern: ^[A-Za-z0-9._/-]+$
      minLength: 1
      maxLength: 64
    RequestIdentityUserArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z0-9-]*):(iam|sts)::(\d{12})?:[\w/+=,.@-]+$
      minLength: 20
      maxLength: 2048
    ResourceArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z0-9-]*):emr-serverless:.+:(\d{12}):\/applications\/[0-9a-zA-Z]+(\/jobruns\/[0-9a-zA-Z]+)?$
      minLength: 60
      maxLength: 1024
    SecurityGroupString:
      type: string
      pattern: ^[-0-9a-zA-Z]+
      minLength: 1
      maxLength: 32
    SparkSubmitParameters:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 102400
    String1024:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 1024
    String256:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 256
    SubnetString:
      type: string
      pattern: ^[-0-9a-zA-Z]+
      minLength: 1
      maxLength: 32
    TagKey:
      type: string
      pattern: ^[A-Za-z0-9 /_.:=+@-]+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^[A-Za-z0-9 /_.:=+@-]*$
      minLength: 0
      maxLength: 256
    UriString:
      type: string
      pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDBFF-\uDC00\uDFFF\r\n\t]*'
      minLength: 1
      maxLength: 10280
    Url:
      type: string
      minLength: 1
      maxLength: 2048
    WorkerTypeString:
      type: string
      pattern: ^[a-zA-Z]+[-_]*[a-zA-Z]+$
      minLength: 1
      maxLength: 50
