openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: entityresolution
  x-aws-serviceName: entityresolution
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: AWS EntityResolution
  description: |-
    Welcome to the _Entity Resolution API Reference_.

    Entity Resolution is an Amazon Web Services service that provides pre-configured entity resolution capabilities that enable developers and analysts at advertising and marketing companies to build an accurate and complete view of their consumers.

    With Entity Resolution, you can match source records containing consumer identifiers, such as name, email address, and phone number. This is true even when these records have incomplete or conflicting identifiers. For example, Entity Resolution can effectively match a source record from a customer relationship management (CRM) system with a source record from a marketing system containing campaign information.

    To learn more about Entity Resolution concepts, procedures, and best practices, see the [Entity Resolution User Guide](https://docs.aws.amazon.com/entityresolution/latest/userguide/what-is-service.html).
servers:
- description: The AWS EntityResolution regional endpoint
  url: https://entityresolution.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AttributeName:
      type: string
      pattern: ^[a-zA-Z_0-9- ]*$
      maxLength: 255
    AwsAccountId:
      type: string
      pattern: ^\d{12}$
    Description:
      type: string
      maxLength: 255
    EntityName:
      type: string
      pattern: ^[a-zA-Z_0-9-]*$
      minLength: 1
      maxLength: 255
    EntityNameOrIdMappingWorkflowArn:
      type: string
      pattern: ^[a-zA-Z_0-9-=+/]*$|^arn:(aws|aws-us-gov|aws-cn):entityresolution:[a-z]{2}-[a-z]{1,10}-[0-9]:[0-9]{12}:(idmappingworkflow/[a-zA-Z_0-9-]{1,255})$
    EntityNameOrIdNamespaceArn:
      type: string
      pattern: ^[a-zA-Z_0-9-=+/]*$|^arn:(aws|aws-us-gov|aws-cn):entityresolution:[a-z]{2}-[a-z]{1,10}-[0-9]:[0-9]{12}:(idnamespace/[a-zA-Z_0-9-]{1,255})$
    ErrorMessage:
      type: string
      minLength: 1
      maxLength: 2048
    HeaderSafeUniqueId:
      type: string
      pattern: ^[a-zA-Z_0-9-+=/,]*$
      minLength: 1
      maxLength: 780
    IdMappingRoleArn:
      type: string
      pattern: ^$|^arn:aws:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$
      minLength: 0
      maxLength: 512
    IdMappingWorkflowArn:
      type: string
      pattern: ^arn:(aws|aws-us-gov|aws-cn):entityresolution:[a-z]{2}-[a-z]{1,10}-[0-9]:[0-9]{12}:(idmappingworkflow/[a-zA-Z_0-9-]{1,255})$
    IdNamespaceArn:
      type: string
      pattern: ^arn:(aws|aws-us-gov|aws-cn):entityresolution:[a-z]{2}-[a-z]{1,10}-[0-9]:[0-9]{12}:(idnamespace/[a-zA-Z_0-9-]{1,255})$
    JobId:
      type: string
      pattern: ^[a-f0-9]{32}$
    KMSArn:
      type: string
      pattern: ^arn:aws:kms:.*:[0-9]+:.*$
    MatchingWorkflowArn:
      type: string
      pattern: ^arn:(aws|aws-us-gov|aws-cn):entityresolution:[a-z]{2}-[a-z]{1,10}-[0-9]:[0-9]{12}:(matchingworkflow/[a-zA-Z_0-9-]{1,255})$
    NextToken:
      type: string
      pattern: ^[a-zA-Z_0-9-=+/]*$
      minLength: 1
      maxLength: 1024
    PolicyDocument:
      type: string
      minLength: 1
      maxLength: 40960
    PolicyToken:
      type: string
      pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$
      minLength: 36
      maxLength: 36
    ProviderServiceArn:
      type: string
      pattern: ^arn:(aws|aws-us-gov|aws-cn):(entityresolution):([a-z]{2}-[a-z]{1,10}-[0-9])::providerservice/([a-zA-Z0-9_-]{1,255})/([a-zA-Z0-9_-]{1,255})$
      minLength: 20
      maxLength: 255
    ProviderServiceDisplayName:
      type: string
      maxLength: 255
    RoleArn:
      type: string
      pattern: ^arn:aws:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$
      minLength: 32
      maxLength: 512
    S3Path:
      type: string
      pattern: ^s3://[a-z0-9][\.\-a-z0-9]{1,61}[a-z0-9](/.*)?$
      minLength: 1
      maxLength: 1024
    SchemaMappingArn:
      type: string
      pattern: ^arn:(aws|aws-us-gov|aws-cn):entityresolution:[a-z]{2}-[a-z]{1,10}-[0-9]:[0-9]{12}:(schemamapping/[a-zA-Z_0-9-]{1,255})$
    StatementAction:
      type: string
      pattern: ^(entityresolution:[a-zA-Z0-9]+)$
      minLength: 3
      maxLength: 64
    StatementCondition:
      type: string
      minLength: 1
      maxLength: 40960
    StatementId:
      type: string
      pattern: ^[0-9A-Za-z]+$
      minLength: 1
      maxLength: 64
    StatementPrincipal:
      type: string
      pattern: ^(\d{12})|([a-z0-9\.]+)$
      minLength: 12
      maxLength: 64
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    VeniceGlobalArn:
      type: string
      pattern: ^arn:(aws|aws-us-gov|aws-cn):entityresolution:[a-z]{2}-[a-z]{1,10}-[0-9]:[0-9]{12}:((schemamapping|matchingworkflow|idmappingworkflow|idnamespace)/[a-zA-Z_0-9-]{1,255})$
