openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: evidently
  x-aws-serviceName: evidently
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2021-02-01'
  title: Amazon CloudWatch Evidently
  description: |-
    You can use Amazon CloudWatch Evidently to safely validate new features by serving them to a specified percentage of your users while you roll out the feature. You can monitor the performance of the new feature to help you decide when to ramp up traffic to your users. This helps you reduce risk and identify unintended consequences before you fully launch the feature.

    You can also conduct A/B experiments to make feature design decisions based on evidence and data. An experiment can test as many as five variations at once. Evidently collects experiment data and analyzes it using statistical methods. It also provides clear recommendations about which variations perform better. You can test both user-facing features and backend features.
servers:
- description: The Amazon CloudWatch Evidently regional endpoint
  url: https://evidently.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AppConfigResourceId:
      type: string
      pattern: '[a-z0-9]{4,7}'
    Arn:
      type: string
      pattern: arn:[^:]*:[^:]*:[^:]*:[^:]*:.*
      minLength: 0
      maxLength: 2048
    ChangeDirectionEnum:
      type: string
      enum:
      - INCREASE
      - DECREASE
    CwDimensionSafeName:
      type: string
      pattern: ^[\S]+$
      minLength: 1
      maxLength: 255
    CwLogGroupSafeName:
      type: string
      pattern: ^[-a-zA-Z0-9._/]+$
      minLength: 1
      maxLength: 512
    Description:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 160
    EntityId:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 512
    ErrorCodeEnum:
      type: string
      minLength: 1
      maxLength: 64
    ErrorMessage:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 1024
    EventType:
      type: string
      enum:
      - aws.evidently.evaluation
      - aws.evidently.custom
    ExperimentArn:
      type: string
      pattern: arn:[^:]*:[^:]*:[^:]*:[^:]*:project/[-a-zA-Z0-9._]*/experiment/[-a-zA-Z0-9._]*
      minLength: 0
      maxLength: 2048
    ExperimentBaseStat:
      type: string
      enum:
      - Mean
    ExperimentName:
      type: string
      pattern: ^[-a-zA-Z0-9._]*$
      minLength: 1
      maxLength: 127
    ExperimentReportName:
      type: string
      enum:
      - BayesianInference
    ExperimentResultRequestType:
      type: string
      enum:
      - BaseStat
      - TreatmentEffect
      - ConfidenceInterval
      - PValue
    ExperimentResultResponseType:
      type: string
      enum:
      - Mean
      - TreatmentEffect
      - ConfidenceIntervalUpperBound
      - ConfidenceIntervalLowerBound
      - PValue
    ExperimentStatus:
      type: string
      enum:
      - CREATED
      - UPDATING
      - RUNNING
      - COMPLETED
      - CANCELLED
    ExperimentStopDesiredState:
      type: string
      enum:
      - COMPLETED
      - CANCELLED
    ExperimentType:
      type: string
      enum:
      - aws.evidently.onlineab
    FeatureArn:
      type: string
      pattern: arn:[^:]*:[^:]*:[^:]*:[^:]*:project/[-a-zA-Z0-9._]*/feature/[-a-zA-Z0-9._]*
      minLength: 0
      maxLength: 2048
    FeatureEvaluationStrategy:
      type: string
      enum:
      - ALL_RULES
      - DEFAULT_VARIATION
    FeatureName:
      type: string
      pattern: ^[-a-zA-Z0-9._]*$
      minLength: 1
      maxLength: 127
    FeatureStatus:
      type: string
      enum:
      - AVAILABLE
      - UPDATING
    GroupName:
      type: string
      pattern: ^[-a-zA-Z0-9._]*$
      minLength: 1
      maxLength: 127
    JsonPath:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 256
    JsonValue:
      type: string
    LaunchArn:
      type: string
      pattern: arn:[^:]*:[^:]*:[^:]*:[^:]*:project/[-a-zA-Z0-9._]*/launch/[-a-zA-Z0-9._]*
      minLength: 0
      maxLength: 2048
    LaunchName:
      type: string
      pattern: ^[-a-zA-Z0-9._]*$
      minLength: 1
      maxLength: 127
    LaunchStatus:
      type: string
      enum:
      - CREATED
      - UPDATING
      - RUNNING
      - COMPLETED
      - CANCELLED
    LaunchStopDesiredState:
      type: string
      enum:
      - COMPLETED
      - CANCELLED
    LaunchType:
      type: string
      enum:
      - aws.evidently.splits
    MaxExperiments:
      type: integer
      minimum: 1
      maximum: 100
    MaxFeatures:
      type: integer
      minimum: 1
      maximum: 100
    MaxLaunches:
      type: integer
      minimum: 1
      maximum: 100
    MaxProjects:
      type: integer
      minimum: 1
      maximum: 50
    MaxReferences:
      type: integer
      minimum: 1
      maximum: 100
    MaxSegments:
      type: integer
      minimum: 1
      maximum: 50
    MetricUnitLabel:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 256
    NextToken:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 8192
    ProjectArn:
      type: string
      pattern: arn:[^:]*:[^:]*:[^:]*:[^:]*:project/[-a-zA-Z0-9._]*
      minLength: 0
      maxLength: 2048
    ProjectName:
      type: string
      pattern: ^[-a-zA-Z0-9._]*$
      minLength: 1
      maxLength: 127
    ProjectRef:
      type: string
      pattern: (^[a-zA-Z0-9._-]*$)|(arn:[^:]*:[^:]*:[^:]*:[^:]*:project/[a-zA-Z0-9._-]*)
      minLength: 0
      maxLength: 2048
    ProjectStatus:
      type: string
      enum:
      - AVAILABLE
      - UPDATING
    RandomizationSalt:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 127
    RuleName:
      type: string
      minLength: 0
      maxLength: 1024
    RuleType:
      type: string
      minLength: 0
      maxLength: 1024
    S3BucketSafeName:
      type: string
      pattern: ^[a-z0-9][-a-z0-9]*[a-z0-9]$
      minLength: 3
      maxLength: 63
    S3PrefixSafeName:
      type: string
      pattern: ^[-a-zA-Z0-9!_.*'()/]*$
      minLength: 1
      maxLength: 1024
    SegmentArn:
      type: string
      pattern: arn:[^:]*:[^:]*:[^:]*:[^:]*:segment/[-a-zA-Z0-9._]*
      minLength: 0
      maxLength: 2048
    SegmentName:
      type: string
      pattern: ^[-a-zA-Z0-9._]*$
      minLength: 1
      maxLength: 64
    SegmentPattern:
      type: string
      minLength: 1
      maxLength: 1024
    SegmentRef:
      type: string
      pattern: (^[-a-zA-Z0-9._]*$)|(arn:[^:]*:[^:]*:[^:]*:[^:]*:segment/[-a-zA-Z0-9._]*)
      minLength: 0
      maxLength: 2048
    SegmentReferenceResourceType:
      type: string
      enum:
      - EXPERIMENT
      - LAUNCH
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TreatmentName:
      type: string
      pattern: ^[-a-zA-Z0-9._]*$
      minLength: 1
      maxLength: 127
    Uuid:
      type: string
      pattern: '[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}'
      minLength: 36
      maxLength: 36
    ValidationExceptionReason:
      type: string
      enum:
      - unknownOperation
      - cannotParse
      - fieldValidationFailed
      - other
    VariationName:
      type: string
      pattern: ^[-a-zA-Z0-9._]*$
      minLength: 1
      maxLength: 127
    VariationValueType:
      type: string
      enum:
      - STRING
      - LONG
      - DOUBLE
      - BOOLEAN
