openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: fis
  x-aws-serviceName: fis
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-12-01'
  title: AWS Fault Injection Simulator
  description: |-
    Amazon Web Services Fault Injection Service is a managed service that enables you to perform fault injection experiments on your Amazon Web Services workloads. For more information, see the [Fault Injection Service User Guide](https://docs.aws.amazon.com/fis/latest/userguide/).
servers:
- description: The AWS Fault Injection Simulator regional endpoint
  url: https://fis.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ActionDescription:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 512
    ActionId:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 128
    ActionParameterDescription:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 512
    ActionParameterName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ActionParameterRequired:
      type: boolean
      default: false
    ActionTargetName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ClientToken:
      type: string
      pattern: ^[\S]+$
      minLength: 1
      maxLength: 1024
    CloudWatchLogGroupArn:
      type: string
      pattern: ^[\S]+$
      minLength: 20
      maxLength: 2048
    ExceptionMessage:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 1024
    ExperimentActionDescription:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 512
    ExperimentActionName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentActionParameter:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 1024
    ExperimentActionParameterName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentActionStartAfter:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentActionStatusReason:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 512
    ExperimentActionTargetName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentErrorAccountId:
      type: string
    ExperimentErrorCode:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 128
    ExperimentErrorLocation:
      type: string
    ExperimentId:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentReportErrorCode:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 128
    ExperimentReportReason:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 512
    ExperimentReportS3ReportArn:
      type: string
      pattern: ^[\s\S]+$
    ExperimentReportS3ReportType:
      type: string
      pattern: ^[\s\S]+$
    ExperimentStatusReason:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 512
    ExperimentTargetFilterPath:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 256
    ExperimentTargetFilterValue:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 128
    ExperimentTargetName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentTargetParameterName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentTargetParameterValue:
      type: string
      minLength: 1
      maxLength: 1024
    ExperimentTargetSelectionMode:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentTemplateActionDescription:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 512
    ExperimentTemplateActionName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentTemplateActionParameter:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 1024
    ExperimentTemplateActionParameterName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentTemplateActionStartAfter:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentTemplateActionTargetName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentTemplateDescription:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 512
    ExperimentTemplateId:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentTemplateTargetFilterPath:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 256
    ExperimentTemplateTargetFilterValue:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 128
    ExperimentTemplateTargetName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentTemplateTargetParameterName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentTemplateTargetParameterValue:
      type: string
      pattern: ^[\p{L}\p{Z}\p{N}_.:/=+\-@]+$
      minLength: 1
      maxLength: 1024
    ExperimentTemplateTargetSelectionMode:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ListActionsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListExperimentResolvedTargetsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListExperimentTemplatesMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListExperimentsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListTargetAccountConfigurationsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListTargetResourceTypesMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    LogSchemaVersion:
      type: integer
    NextToken:
      type: string
      pattern: ^[\S]+$
      minLength: 1
      maxLength: 1024
    ReportConfigurationCloudWatchDashboardIdentifier:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 512
    ReportConfigurationDuration:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 32
    ReportConfigurationS3OutputPrefix:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 256
    ResourceArn:
      type: string
      pattern: ^[\S]+$
      minLength: 20
      maxLength: 2048
    RoleArn:
      type: string
      pattern: ^[\S]+$
      minLength: 20
      maxLength: 2048
    S3BucketName:
      type: string
      pattern: ^[\S]+$
      minLength: 3
      maxLength: 63
    S3ObjectKey:
      type: string
      pattern: ^[\s\S]+$
      minLength: 1
      maxLength: 700
    SafetyLeverId:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    SafetyLeverStatusReason:
      type: string
    StopConditionSource:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    StopConditionValue:
      type: string
      pattern: ^[\s\S]+$
      minLength: 20
      maxLength: 2048
    TagKey:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 128
    TagValue:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 256
    TargetAccountConfigurationDescription:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 512
    TargetAccountId:
      type: string
      pattern: ^[\S]+$
      minLength: 12
      maxLength: 48
    TargetInformationKey:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    TargetInformationValue:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 2048
    TargetName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    TargetResourceTypeDescription:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 512
    TargetResourceTypeId:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 128
    TargetResourceTypeParameterDescription:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 512
    TargetResourceTypeParameterName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    TargetResourceTypeParameterRequired:
      type: boolean
      default: false
