openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: fis
  x-aws-serviceName: fis
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-12-01'
  title: AWS Fault Injection Simulator
  description: |-
    Amazon Web Services Fault Injection Service is a managed service that enables you to perform fault injection experiments on your Amazon Web Services workloads. For more information, see the [Fault Injection Service User Guide](https://docs.aws.amazon.com/fis/latest/userguide/).
servers:
- description: The AWS Fault Injection Simulator regional endpoint
  url: https://fis.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccountTargeting:
      type: string
      enum:
      - single-account
      - multi-account
    ActionDescription:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 512
    ActionId:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 128
    ActionParameterDescription:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 512
    ActionParameterMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ActionParameter'
    ActionParameterName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ActionParameterRequired:
      type: boolean
      default: false
    ActionSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/ActionSummary'
    ActionTargetMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ActionTarget'
    ActionTargetName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ActionsMode:
      type: string
      enum:
      - skip-all
      - run-all
    ClientToken:
      type: string
      pattern: ^[\S]+$
      minLength: 1
      maxLength: 1024
    CloudWatchLogGroupArn:
      type: string
      pattern: ^[\S]+$
      minLength: 20
      maxLength: 2048
    CreateExperimentTemplateActionInputMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/CreateExperimentTemplateActionInput'
    CreateExperimentTemplateStopConditionInputList:
      type: array
      items:
        $ref: '#/components/schemas/CreateExperimentTemplateStopConditionInput'
    CreateExperimentTemplateTargetInputMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/CreateExperimentTemplateTargetInput'
    CreationTime:
      type: string
      format: date-time
    EmptyTargetResolutionMode:
      type: string
      enum:
      - fail
      - skip
    ExceptionMessage:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 1024
    ExperimentActionDescription:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 512
    ExperimentActionEndTime:
      type: string
      format: date-time
    ExperimentActionMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ExperimentAction'
    ExperimentActionName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentActionParameter:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 1024
    ExperimentActionParameterMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ExperimentActionParameter'
    ExperimentActionParameterName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentActionStartAfter:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentActionStartAfterList:
      type: array
      items:
        $ref: '#/components/schemas/ExperimentActionStartAfter'
    ExperimentActionStartTime:
      type: string
      format: date-time
    ExperimentActionStatus:
      type: string
      enum:
      - pending
      - initiating
      - running
      - completed
      - cancelled
      - stopping
      - stopped
      - failed
      - skipped
    ExperimentActionStatusReason:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 512
    ExperimentActionTargetMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ExperimentTargetName'
    ExperimentActionTargetName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentEndTime:
      type: string
      format: date-time
    ExperimentErrorAccountId:
      type: string
    ExperimentErrorCode:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 128
    ExperimentErrorLocation:
      type: string
    ExperimentId:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentReportConfigurationCloudWatchDashboardList:
      type: array
      items:
        $ref: '#/components/schemas/ExperimentReportConfigurationCloudWatchDashboard'
    ExperimentReportErrorCode:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 128
    ExperimentReportReason:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 512
    ExperimentReportS3ReportArn:
      type: string
      pattern: ^[\s\S]+$
    ExperimentReportS3ReportList:
      type: array
      items:
        $ref: '#/components/schemas/ExperimentReportS3Report'
    ExperimentReportS3ReportType:
      type: string
      pattern: ^[\s\S]+$
    ExperimentReportStatus:
      type: string
      enum:
      - pending
      - running
      - completed
      - cancelled
      - failed
    ExperimentStartTime:
      type: string
      format: date-time
    ExperimentStatus:
      type: string
      enum:
      - pending
      - initiating
      - running
      - completed
      - stopping
      - stopped
      - failed
      - cancelled
    ExperimentStatusReason:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 512
    ExperimentStopConditionList:
      type: array
      items:
        $ref: '#/components/schemas/ExperimentStopCondition'
    ExperimentSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/ExperimentSummary'
    ExperimentTargetAccountConfigurationList:
      type: array
      items:
        $ref: '#/components/schemas/ExperimentTargetAccountConfigurationSummary'
    ExperimentTargetFilterList:
      type: array
      items:
        $ref: '#/components/schemas/ExperimentTargetFilter'
    ExperimentTargetFilterPath:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 256
    ExperimentTargetFilterValue:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 128
    ExperimentTargetFilterValues:
      type: array
      items:
        $ref: '#/components/schemas/ExperimentTargetFilterValue'
    ExperimentTargetMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ExperimentTarget'
    ExperimentTargetName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentTargetParameterMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ExperimentTargetParameterValue'
    ExperimentTargetParameterName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentTargetParameterValue:
      type: string
      minLength: 1
      maxLength: 1024
    ExperimentTargetSelectionMode:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentTemplateActionDescription:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 512
    ExperimentTemplateActionMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ExperimentTemplateAction'
    ExperimentTemplateActionName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentTemplateActionParameter:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 1024
    ExperimentTemplateActionParameterMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ExperimentTemplateActionParameter'
    ExperimentTemplateActionParameterName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentTemplateActionStartAfter:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentTemplateActionStartAfterList:
      type: array
      items:
        $ref: '#/components/schemas/ExperimentTemplateActionStartAfter'
    ExperimentTemplateActionTargetMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ExperimentTemplateTargetName'
    ExperimentTemplateActionTargetName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentTemplateDescription:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 512
    ExperimentTemplateId:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentTemplateReportConfigurationCloudWatchDashboardList:
      type: array
      items:
        $ref: '#/components/schemas/ExperimentTemplateReportConfigurationCloudWatchDashboard'
    ExperimentTemplateStopConditionList:
      type: array
      items:
        $ref: '#/components/schemas/ExperimentTemplateStopCondition'
    ExperimentTemplateSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/ExperimentTemplateSummary'
    ExperimentTemplateTargetFilterInputList:
      type: array
      items:
        $ref: '#/components/schemas/ExperimentTemplateTargetInputFilter'
    ExperimentTemplateTargetFilterList:
      type: array
      items:
        $ref: '#/components/schemas/ExperimentTemplateTargetFilter'
    ExperimentTemplateTargetFilterPath:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 256
    ExperimentTemplateTargetFilterValue:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 128
    ExperimentTemplateTargetFilterValues:
      type: array
      items:
        $ref: '#/components/schemas/ExperimentTemplateTargetFilterValue'
    ExperimentTemplateTargetMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ExperimentTemplateTarget'
    ExperimentTemplateTargetName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentTemplateTargetParameterMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ExperimentTemplateTargetParameterValue'
    ExperimentTemplateTargetParameterName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    ExperimentTemplateTargetParameterValue:
      type: string
      pattern: ^[\p{L}\p{Z}\p{N}_.:/=+\-@]+$
      minLength: 1
      maxLength: 1024
    ExperimentTemplateTargetSelectionMode:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    LastUpdateTime:
      type: string
      format: date-time
    ListActionsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListExperimentResolvedTargetsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListExperimentTemplatesMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListExperimentsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListTargetAccountConfigurationsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListTargetResourceTypesMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    LogSchemaVersion:
      type: integer
    NextToken:
      type: string
      pattern: ^[\S]+$
      minLength: 1
      maxLength: 1024
    ReportConfigurationCloudWatchDashboardIdentifier:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 512
    ReportConfigurationCloudWatchDashboardInputList:
      type: array
      items:
        $ref: '#/components/schemas/ReportConfigurationCloudWatchDashboardInput'
    ReportConfigurationDuration:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 32
    ReportConfigurationS3OutputPrefix:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 256
    ResolvedTargetList:
      type: array
      items:
        $ref: '#/components/schemas/ResolvedTarget'
    ResourceArn:
      type: string
      pattern: ^[\S]+$
      minLength: 20
      maxLength: 2048
    ResourceArnList:
      type: array
      items:
        $ref: '#/components/schemas/ResourceArn'
    RoleArn:
      type: string
      pattern: ^[\S]+$
      minLength: 20
      maxLength: 2048
    S3BucketName:
      type: string
      pattern: ^[\S]+$
      minLength: 3
      maxLength: 63
    S3ObjectKey:
      type: string
      pattern: ^[\s\S]+$
      minLength: 1
      maxLength: 700
    SafetyLeverId:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    SafetyLeverStatus:
      type: string
      enum:
      - disengaged
      - engaged
      - engaging
    SafetyLeverStatusInput:
      type: string
      enum:
      - disengaged
      - engaged
    SafetyLeverStatusReason:
      type: string
    StopConditionSource:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    StopConditionValue:
      type: string
      pattern: ^[\s\S]+$
      minLength: 20
      maxLength: 2048
    TagKey:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 256
    TargetAccountConfigurationDescription:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 512
    TargetAccountConfigurationList:
      type: array
      items:
        $ref: '#/components/schemas/TargetAccountConfigurationSummary'
    TargetAccountConfigurationsCount:
      type: integer
      format: int64
      minimum: 0
    TargetAccountId:
      type: string
      pattern: ^[\S]+$
      minLength: 12
      maxLength: 48
    TargetInformationKey:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    TargetInformationMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TargetInformationValue'
    TargetInformationValue:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 2048
    TargetName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    TargetResourceTypeDescription:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 512
    TargetResourceTypeId:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 128
    TargetResourceTypeParameterDescription:
      type: string
      pattern: ^[\s\S]+$
      minLength: 0
      maxLength: 512
    TargetResourceTypeParameterMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TargetResourceTypeParameter'
    TargetResourceTypeParameterName:
      type: string
      pattern: ^[\S]+$
      minLength: 0
      maxLength: 64
    TargetResourceTypeParameterRequired:
      type: boolean
      default: false
    TargetResourceTypeSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/TargetResourceTypeSummary'
    UpdateExperimentTemplateActionInputMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/UpdateExperimentTemplateActionInputItem'
    UpdateExperimentTemplateStopConditionInputList:
      type: array
      items:
        $ref: '#/components/schemas/UpdateExperimentTemplateStopConditionInput'
    UpdateExperimentTemplateTargetInputMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/UpdateExperimentTemplateTargetInput'
