openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: gameliftstreams
  x-aws-serviceName: gameliftstreams
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: Amazon GameLift Streams
  description: |-
    Amazon GameLift Streams

    Amazon GameLift Streams provides a global cloud solution for content streaming experiences. Use Amazon GameLift Streams tools to upload and configure content for streaming, deploy and scale computing resources to host streams, and manage stream session placement to meet customer demand.

    This Reference Guide describes the Amazon GameLift Streams service API. You can use the API through the Amazon Web Services SDK, the Command Line Interface (AWS CLI), or by making direct REST calls through HTTPS.

    See the _Amazon GameLift Streams Developer Guide_ for more information on how Amazon GameLift Streams works and how to work with it.
servers:
- description: The Amazon GameLift Streams regional endpoint
  url: https://gameliftstreams.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AlwaysOnCapacity:
      type: integer
      minimum: 0
    ApplicationLogOutputUri:
      type: string
      pattern: ^$|^s3://([a-zA-Z0-9][a-zA-Z0-9._-]{1,61}[a-zA-Z0-9])(/[a-zA-Z0-9._-]+)*/?$
      minLength: 0
      maxLength: 1024
    ApplicationSourceUri:
      type: string
      minLength: 1
      maxLength: 1024
    ApplicationStatus:
      type: string
      enum:
      - INITIALIZED
      - PROCESSING
      - READY
      - DELETING
      - ERROR
    ApplicationStatusReason:
      type: string
      enum:
      - internalError
      - accessDenied
    ApplicationSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/ApplicationSummary'
    Arn:
      type: string
      pattern: '^arn:aws:gameliftstreams:([^:

        ]*):([0-9]{12}):([^:

        ]*)$'
      minLength: 1
      maxLength: 128
    ArnList:
      type: array
      items:
        $ref: '#/components/schemas/Arn'
    CapacityValue:
      type: integer
      minimum: 0
    ClientToken:
      type: string
      pattern: ^[\x21-\x7E]+$
      minLength: 32
      maxLength: 128
    ConnectionTimeoutSeconds:
      type: integer
      minimum: 1
      maximum: 3600
    Description:
      type: string
      pattern: ^[a-zA-Z0-9-_.!+@/][a-zA-Z0-9-_.!+@/ ]*$
      minLength: 1
      maxLength: 80
    EnvironmentVariables:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    ExecutablePath:
      type: string
      minLength: 1
      maxLength: 1024
    ExportFilesReason:
      type: string
      minLength: 0
      maxLength: 1024
    ExportFilesStatus:
      type: string
      enum:
      - SUCCEEDED
      - FAILED
      - PENDING
    FileLocationUri:
      type: string
    FilePath:
      type: string
      minLength: 0
      maxLength: 1024
    FilePaths:
      type: array
      items:
        $ref: '#/components/schemas/FilePath'
    GameLaunchArgList:
      type: array
      items:
        type: string
    Id:
      type: string
      pattern: ^[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 32
    Identifier:
      type: string
      pattern: '^(^[a-zA-Z0-9-]+$)|(^arn:aws:gameliftstreams:([^:

        ]*):([0-9]{12}):([^:

        ]*)$)$'
      minLength: 1
      maxLength: 128
    Identifiers:
      type: array
      items:
        $ref: '#/components/schemas/Identifier'
    LocationConfigurations:
      type: array
      items:
        $ref: '#/components/schemas/LocationConfiguration'
    LocationList:
      type: array
      items:
        $ref: '#/components/schemas/LocationName'
    LocationName:
      type: string
      pattern: ^[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 20
    LocationStates:
      type: array
      items:
        $ref: '#/components/schemas/LocationState'
    LocationsList:
      type: array
      items:
        type: string
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    NextToken:
      type: string
    OnDemandCapacity:
      type: integer
      minimum: 0
    OutputUri:
      type: string
      pattern: ^s3://.*(/|\.zip|\.ZIP)$
      minLength: 0
      maxLength: 1024
    Protocol:
      type: string
      enum:
      - WebRTC
    ReplicationStatusType:
      type: string
      enum:
      - REPLICATING
      - COMPLETED
    ReplicationStatuses:
      type: array
      items:
        $ref: '#/components/schemas/ReplicationStatus'
    RuntimeEnvironmentType:
      type: string
      enum:
      - PROTON
      - WINDOWS
      - UBUNTU
    RuntimeEnvironmentVersion:
      type: string
      minLength: 1
      maxLength: 256
    SessionLengthSeconds:
      type: integer
      minimum: 1
      maximum: 86400
    SignalRequest:
      type: string
      minLength: 1
    SignalResponse:
      type: string
    StreamClass:
      type: string
      enum:
      - gen4n_high
      - gen4n_ultra
      - gen4n_win2022
      - gen5n_high
      - gen5n_ultra
      - gen5n_win2022
    StreamGroupLocationStatus:
      type: string
      enum:
      - ACTIVATING
      - ACTIVE
      - ERROR
      - REMOVING
    StreamGroupStatus:
      type: string
      enum:
      - ACTIVATING
      - UPDATING_LOCATIONS
      - ACTIVE
      - ACTIVE_WITH_ERRORS
      - ERROR
      - DELETING
    StreamGroupStatusReason:
      type: string
      enum:
      - internalError
      - noAvailableInstances
    StreamGroupSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/StreamGroupSummary'
    StreamSessionStatus:
      type: string
      enum:
      - ACTIVATING
      - ACTIVE
      - CONNECTED
      - PENDING_CLIENT_RECONNECTION
      - RECONNECTING
      - TERMINATING
      - TERMINATED
      - ERROR
    StreamSessionStatusReason:
      type: string
      enum:
      - internalError
      - invalidSignalRequest
      - placementTimeout
      - applicationLogS3DestinationError
    StreamSessionSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/StreamSessionSummary'
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    Tags:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    UserId:
      type: string
      pattern: ^[-_a-zA-Z0-9/=+]*$
      minLength: 0
      maxLength: 1024
    WebSdkProtocolUrl:
      type: string
