openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: gameliftstreams
  x-aws-serviceName: gameliftstreams
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: Amazon GameLift Streams
  description: |-
    Amazon GameLift Streams

    Amazon GameLift Streams provides a global cloud solution for content streaming experiences. Use Amazon GameLift Streams tools to upload and configure content for streaming, deploy and scale computing resources to host streams, and manage stream session placement to meet customer demand.

    This Reference Guide describes the Amazon GameLift Streams service API. You can use the API through the Amazon Web Services SDK, the Command Line Interface (AWS CLI), or by making direct REST calls through HTTPS.

    See the _Amazon GameLift Streams Developer Guide_ for more information on how Amazon GameLift Streams works and how to work with it.
servers:
- description: The Amazon GameLift Streams regional endpoint
  url: https://gameliftstreams.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AlwaysOnCapacity:
      type: integer
      minimum: 0
    ApplicationLogOutputUri:
      type: string
      pattern: ^$|^s3://([a-zA-Z0-9][a-zA-Z0-9._-]{1,61}[a-zA-Z0-9])(/[a-zA-Z0-9._-]+)*/?$
      minLength: 0
      maxLength: 1024
    ApplicationSourceUri:
      type: string
      minLength: 1
      maxLength: 1024
    Arn:
      type: string
      pattern: '^arn:aws:gameliftstreams:([^:

        ]*):([0-9]{12}):([^:

        ]*)$'
      minLength: 1
      maxLength: 128
    CapacityValue:
      type: integer
      minimum: 0
    ClientToken:
      type: string
      pattern: ^[\x21-\x7E]+$
      minLength: 32
      maxLength: 128
    ConnectionTimeoutSeconds:
      type: integer
      minimum: 1
      maximum: 3600
    Description:
      type: string
      pattern: ^[a-zA-Z0-9-_.!+@/][a-zA-Z0-9-_.!+@/ ]*$
      minLength: 1
      maxLength: 80
    ExecutablePath:
      type: string
      minLength: 1
      maxLength: 1024
    ExportFilesReason:
      type: string
      minLength: 0
      maxLength: 1024
    FileLocationUri:
      type: string
    FilePath:
      type: string
      minLength: 0
      maxLength: 1024
    Id:
      type: string
      pattern: ^[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 32
    Identifier:
      type: string
      pattern: '^(^[a-zA-Z0-9-]+$)|(^arn:aws:gameliftstreams:([^:

        ]*):([0-9]{12}):([^:

        ]*)$)$'
      minLength: 1
      maxLength: 128
    LocationName:
      type: string
      pattern: ^[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 20
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    NextToken:
      type: string
    OnDemandCapacity:
      type: integer
      minimum: 0
    OutputUri:
      type: string
      pattern: ^s3://.*(/|\.zip|\.ZIP)$
      minLength: 0
      maxLength: 1024
    RuntimeEnvironmentVersion:
      type: string
      minLength: 1
      maxLength: 256
    SessionLengthSeconds:
      type: integer
      minimum: 1
      maximum: 86400
    SignalRequest:
      type: string
      minLength: 1
    SignalResponse:
      type: string
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    UserId:
      type: string
      pattern: ^[-_a-zA-Z0-9/=+]*$
      minLength: 0
      maxLength: 1024
    WebSdkProtocolUrl:
      type: string
