openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: geo_maps
  x-aws-serviceName: geomaps
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-11-19'
  title: Amazon Location Service Maps V2
  description: |-
    Integrate high-quality base map data into your applications using [MapLibre](https://maplibre.org). Capabilities include:

      * Access to comprehensive base map data, allowing you to tailor the map display to your specific needs.

      * Multiple pre-designed map styles suited for various application types, such as navigation, logistics, or data visualization.

      * Generation of static map images for scenarios where interactive maps aren't suitable, such as:

        * Embedding in emails or documents

        * Displaying in low-bandwidth environments

        * Creating printable maps

        * Enhancing application performance by reducing client-side rendering
servers:
- description: The Amazon Location Service Maps V2 regional endpoint
  url: https://geo-maps.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ApiKey:
      type: string
      maxLength: 1000
    ColorScheme:
      type: string
      enum:
      - Light
      - Dark
    CompactOverlay:
      type: string
      minLength: 1
      maxLength: 7000
    CountryCode:
      type: string
      pattern: ^([A-Z]{2}|[A-Z]{3})$
      minLength: 2
      maxLength: 3
    GeoJsonOverlay:
      type: string
      minLength: 1
      maxLength: 7000
    LabelSize:
      type: string
      enum:
      - Small
      - Large
    LanguageTag:
      type: string
      minLength: 2
      maxLength: 35
    MapFeatureMode:
      type: string
      enum:
      - Enabled
      - Disabled
    MapStyle:
      type: string
      enum:
      - Standard
      - Monochrome
      - Hybrid
      - Satellite
    PositionListString:
      type: string
      pattern: ^(-?\d{1,3}(\.\d{1,14})?,-?\d{1,2}(\.\d{1,14})?)(,(-?\d{1,3}(\.\d{1,14})?,-?\d{1,2}(\.\d{1,14})?))*$
      minLength: 7
    PositionString:
      type: string
      pattern: ^-?\d{1,3}(\.\d{1,14})?,-?\d{1,2}(\.\d{1,14})?$
      minLength: 3
      maxLength: 36
    ScaleBarUnit:
      type: string
      enum:
      - Kilometers
      - KilometersMiles
      - Miles
      - MilesKilometers
    StaticMapStyle:
      type: string
      enum:
      - Satellite
      - Standard
    Tileset:
      type: string
      pattern: ^[-.\w]+$
      minLength: 1
      maxLength: 100
    ValidationExceptionReason:
      type: string
      enum:
      - UnknownOperation
      - Missing
      - CannotParse
      - FieldValidationFailed
      - Other
      - UnknownField
    Variant:
      type: string
      enum:
      - Default
