openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: geo_places
  x-aws-serviceName: geoplaces
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-11-19'
  title: Amazon Location Service Places V2
  description: |-
    The Places API enables powerful location search and geocoding capabilities for your applications, offering global coverage with rich, detailed information. Key features include:

      * Forward and reverse geocoding for addresses and coordinates

      * Comprehensive place searches with detailed information, including:

        * Business names and addresses

        * Contact information

        * Hours of operation

        * POI (Points of Interest) categories

        * Food types for restaurants

        * Chain affiliation for relevant businesses

      * Global data coverage with a wide range of POI categories

      * Regular data updates to ensure accuracy and relevance
servers:
- description: The Amazon Location Service Places V2 regional endpoint
  url: https://geo-places.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas: {}
