openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: geo_places
  x-aws-serviceName: geoplaces
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-11-19'
  title: Amazon Location Service Places V2
  description: |-
    The Places API enables powerful location search and geocoding capabilities for your applications, offering global coverage with rich, detailed information. Key features include:

      * Forward and reverse geocoding for addresses and coordinates

      * Comprehensive place searches with detailed information, including:

        * Business names and addresses

        * Contact information

        * Hours of operation

        * POI (Points of Interest) categories

        * Food types for restaurants

        * Chain affiliation for relevant businesses

      * Global data coverage with a wide range of POI categories

      * Regular data updates to ensure accuracy and relevance
servers:
- description: The Amazon Location Service Places V2 regional endpoint
  url: https://geo-places.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ApiKey:
      type: string
      maxLength: 1000
    AutocompleteAdditionalFeature:
      type: string
      enum:
      - Core
    AutocompleteFilterPlaceType:
      type: string
      enum:
      - Locality
      - PostalCode
    AutocompleteIntendedUse:
      type: string
      enum:
      - SingleUse
    CountryCode:
      type: string
      pattern: ^([A-Z]{2}|[A-Z]{3})$
      minLength: 2
      maxLength: 3
    CountryCode2:
      type: string
      pattern: ^[A-Z]{2}$
      minLength: 2
      maxLength: 2
    CountryCode3:
      type: string
      pattern: ^[A-Z]{3}$
      minLength: 3
      maxLength: 3
    GeocodeAdditionalFeature:
      type: string
      enum:
      - TimeZone
      - Access
    GeocodeFilterPlaceType:
      type: string
      enum:
      - Locality
      - PostalCode
      - Intersection
      - Street
      - PointAddress
      - InterpolatedAddress
    GeocodeIntendedUse:
      type: string
      enum:
      - SingleUse
      - Storage
    GetPlaceAdditionalFeature:
      type: string
      enum:
      - TimeZone
      - Phonemes
      - Access
      - Contact
    GetPlaceIntendedUse:
      type: string
      enum:
      - SingleUse
      - Storage
    IntersectionStreet:
      type: string
      minLength: 0
      maxLength: 200
    LanguageTag:
      type: string
      minLength: 2
      maxLength: 35
    OpeningHoursDisplay:
      type: string
      minLength: 0
      maxLength: 200
    PlaceType:
      type: string
      enum:
      - Country
      - Region
      - SubRegion
      - Locality
      - District
      - SubDistrict
      - PostalCode
      - Block
      - SubBlock
      - Intersection
      - Street
      - PointOfInterest
      - PointAddress
      - InterpolatedAddress
    PostalAuthority:
      type: string
      enum:
      - Usps
    PostalCodeMode:
      type: string
      enum:
      - MergeAllSpannedLocalities
      - EnumerateSpannedLocalities
    PostalCodeType:
      type: string
      enum:
      - UspsZip
      - UspsZipPlus4
    QueryType:
      type: string
      enum:
      - Category
      - BusinessChain
    RecordTypeCode:
      type: string
      enum:
      - Firm
      - General
      - HighRise
      - PostOfficeBox
      - Rural
      - Street
    ReverseGeocodeAdditionalFeature:
      type: string
      enum:
      - TimeZone
      - Access
    ReverseGeocodeFilterPlaceType:
      type: string
      enum:
      - Locality
      - Intersection
      - Street
      - PointAddress
      - InterpolatedAddress
    ReverseGeocodeIntendedUse:
      type: string
      enum:
      - SingleUse
      - Storage
    SearchNearbyAdditionalFeature:
      type: string
      enum:
      - TimeZone
      - Phonemes
      - Access
      - Contact
    SearchNearbyIntendedUse:
      type: string
      enum:
      - SingleUse
      - Storage
    SearchTextAdditionalFeature:
      type: string
      enum:
      - TimeZone
      - Phonemes
      - Access
      - Contact
    SearchTextIntendedUse:
      type: string
      enum:
      - SingleUse
      - Storage
    SensitiveString:
      type: string
    SuggestAdditionalFeature:
      type: string
      enum:
      - Core
      - TimeZone
      - Phonemes
      - Access
    SuggestIntendedUse:
      type: string
      enum:
      - SingleUse
    SuggestResultItemType:
      type: string
      enum:
      - Place
      - Query
    Token:
      type: string
      minLength: 1
      maxLength: 2000
    TypePlacement:
      type: string
      enum:
      - BeforeBaseName
      - AfterBaseName
    TypeSeparator:
      type: string
      pattern: ^$|^ $
      minLength: 0
      maxLength: 1
    ValidationExceptionReason:
      type: string
      enum:
      - UnknownOperation
      - Missing
      - CannotParse
      - FieldValidationFailed
      - Other
      - UnknownField
    ZipClassificationCode:
      type: string
      enum:
      - Military
      - PostOfficeBoxes
      - Unique
