openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: geo_places
  x-aws-serviceName: geoplaces
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-11-19'
  title: Amazon Location Service Places V2
  description: |-
    The Places API enables powerful location search and geocoding capabilities for your applications, offering global coverage with rich, detailed information. Key features include:

      * Forward and reverse geocoding for addresses and coordinates

      * Comprehensive place searches with detailed information, including:

        * Business names and addresses

        * Contact information

        * Hours of operation

        * POI (Points of Interest) categories

        * Food types for restaurants

        * Chain affiliation for relevant businesses

      * Global data coverage with a wide range of POI categories

      * Regular data updates to ensure accuracy and relevance
servers:
- description: The Amazon Location Service Places V2 regional endpoint
  url: https://geo-places.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccessPointList:
      type: array
      items:
        $ref: '#/components/schemas/AccessPoint'
    AccessRestrictionList:
      type: array
      items:
        $ref: '#/components/schemas/AccessRestriction'
    ApiKey:
      type: string
      maxLength: 1000
    AutocompleteAdditionalFeature:
      type: string
      enum:
      - Core
    AutocompleteAdditionalFeatureList:
      type: array
      items:
        $ref: '#/components/schemas/AutocompleteAdditionalFeature'
    AutocompleteFilterPlaceType:
      type: string
      enum:
      - Locality
      - PostalCode
    AutocompleteFilterPlaceTypeList:
      type: array
      items:
        $ref: '#/components/schemas/AutocompleteFilterPlaceType'
    AutocompleteIntendedUse:
      type: string
      enum:
      - SingleUse
    AutocompleteResultItemList:
      type: array
      items:
        $ref: '#/components/schemas/AutocompleteResultItem'
    BoundingBox:
      type: array
      items:
        type: number
      x-sensitive: true
    BusinessChainList:
      type: array
      items:
        $ref: '#/components/schemas/BusinessChain'
    CategoryList:
      type: array
      items:
        $ref: '#/components/schemas/Category'
    ContactDetailsList:
      type: array
      items:
        $ref: '#/components/schemas/ContactDetails'
    CountryCode:
      type: string
      pattern: ^([A-Z]{2}|[A-Z]{3})$
      minLength: 2
      maxLength: 3
    CountryCode2:
      type: string
      pattern: ^[A-Z]{2}$
      minLength: 2
      maxLength: 2
    CountryCode3:
      type: string
      pattern: ^[A-Z]{3}$
      minLength: 3
      maxLength: 3
    CountryCodeList:
      type: array
      items:
        $ref: '#/components/schemas/CountryCode'
    DistanceMeters:
      type: integer
      format: int64
      default: 0
      minimum: 0
      maximum: 4294967295
    DurationSeconds:
      type: integer
      format: int64
      default: 0
      minimum: 0
      maximum: 4294967295
    FilterBusinessChainList:
      type: array
      items:
        type: string
    FilterCategoryList:
      type: array
      items:
        type: string
    FilterFoodTypeList:
      type: array
      items:
        type: string
    FoodTypeList:
      type: array
      items:
        $ref: '#/components/schemas/FoodType'
    GeocodeAdditionalFeature:
      type: string
      enum:
      - TimeZone
      - Access
    GeocodeAdditionalFeatureList:
      type: array
      items:
        $ref: '#/components/schemas/GeocodeAdditionalFeature'
    GeocodeFilterPlaceType:
      type: string
      enum:
      - Locality
      - PostalCode
      - Intersection
      - Street
      - PointAddress
      - InterpolatedAddress
    GeocodeFilterPlaceTypeList:
      type: array
      items:
        $ref: '#/components/schemas/GeocodeFilterPlaceType'
    GeocodeIntendedUse:
      type: string
      enum:
      - SingleUse
      - Storage
    GeocodeResultItemList:
      type: array
      items:
        $ref: '#/components/schemas/GeocodeResultItem'
    GetPlaceAdditionalFeature:
      type: string
      enum:
      - TimeZone
      - Phonemes
      - Access
      - Contact
    GetPlaceAdditionalFeatureList:
      type: array
      items:
        $ref: '#/components/schemas/GetPlaceAdditionalFeature'
    GetPlaceIntendedUse:
      type: string
      enum:
      - SingleUse
      - Storage
    HighlightList:
      type: array
      items:
        $ref: '#/components/schemas/Highlight'
    IntersectionHighlightsList:
      type: array
      items:
        $ref: '#/components/schemas/HighlightList'
    IntersectionList:
      type: array
      items:
        $ref: '#/components/schemas/IntersectionStreet'
    IntersectionStreet:
      type: string
      minLength: 0
      maxLength: 200
    LanguageTag:
      type: string
      minLength: 2
      maxLength: 35
    MatchScore:
      type: number
      format: double
      default: 0
      minimum: 0
      maximum: 1
    MatchScoreList:
      type: array
      items:
        $ref: '#/components/schemas/MatchScore'
    OpeningHoursComponentsList:
      type: array
      items:
        $ref: '#/components/schemas/OpeningHoursComponents'
    OpeningHoursDisplay:
      type: string
      minLength: 0
      maxLength: 200
    OpeningHoursDisplayList:
      type: array
      items:
        $ref: '#/components/schemas/OpeningHoursDisplay'
    OpeningHoursList:
      type: array
      items:
        $ref: '#/components/schemas/OpeningHours'
    PhonemeTranscriptionList:
      type: array
      items:
        $ref: '#/components/schemas/PhonemeTranscription'
    PlaceType:
      type: string
      enum:
      - Country
      - Region
      - SubRegion
      - Locality
      - District
      - SubDistrict
      - PostalCode
      - Block
      - SubBlock
      - Intersection
      - Street
      - PointOfInterest
      - PointAddress
      - InterpolatedAddress
    Position:
      type: array
      items:
        type: number
      x-sensitive: true
    PostalAuthority:
      type: string
      enum:
      - Usps
    PostalCodeDetailsList:
      type: array
      items:
        $ref: '#/components/schemas/PostalCodeDetails'
    PostalCodeMode:
      type: string
      enum:
      - MergeAllSpannedLocalities
      - EnumerateSpannedLocalities
    PostalCodeType:
      type: string
      enum:
      - UspsZip
      - UspsZipPlus4
    QueryRefinementList:
      type: array
      items:
        $ref: '#/components/schemas/QueryRefinement'
    QueryType:
      type: string
      enum:
      - Category
      - BusinessChain
    RecordTypeCode:
      type: string
      enum:
      - Firm
      - General
      - HighRise
      - PostOfficeBox
      - Rural
      - Street
    ReverseGeocodeAdditionalFeature:
      type: string
      enum:
      - TimeZone
      - Access
    ReverseGeocodeAdditionalFeatureList:
      type: array
      items:
        $ref: '#/components/schemas/ReverseGeocodeAdditionalFeature'
    ReverseGeocodeFilterPlaceType:
      type: string
      enum:
      - Locality
      - Intersection
      - Street
      - PointAddress
      - InterpolatedAddress
    ReverseGeocodeFilterPlaceTypeList:
      type: array
      items:
        $ref: '#/components/schemas/ReverseGeocodeFilterPlaceType'
    ReverseGeocodeIntendedUse:
      type: string
      enum:
      - SingleUse
      - Storage
    ReverseGeocodeResultItemList:
      type: array
      items:
        $ref: '#/components/schemas/ReverseGeocodeResultItem'
    SearchNearbyAdditionalFeature:
      type: string
      enum:
      - TimeZone
      - Phonemes
      - Access
      - Contact
    SearchNearbyAdditionalFeatureList:
      type: array
      items:
        $ref: '#/components/schemas/SearchNearbyAdditionalFeature'
    SearchNearbyIntendedUse:
      type: string
      enum:
      - SingleUse
      - Storage
    SearchNearbyResultItemList:
      type: array
      items:
        $ref: '#/components/schemas/SearchNearbyResultItem'
    SearchTextAdditionalFeature:
      type: string
      enum:
      - TimeZone
      - Phonemes
      - Access
      - Contact
    SearchTextAdditionalFeatureList:
      type: array
      items:
        $ref: '#/components/schemas/SearchTextAdditionalFeature'
    SearchTextIntendedUse:
      type: string
      enum:
      - SingleUse
      - Storage
    SearchTextResultItemList:
      type: array
      items:
        $ref: '#/components/schemas/SearchTextResultItem'
    SensitiveString:
      type: string
    StreetComponentsList:
      type: array
      items:
        $ref: '#/components/schemas/StreetComponents'
    SuggestAdditionalFeature:
      type: string
      enum:
      - Core
      - TimeZone
      - Phonemes
      - Access
    SuggestAdditionalFeatureList:
      type: array
      items:
        $ref: '#/components/schemas/SuggestAdditionalFeature'
    SuggestIntendedUse:
      type: string
      enum:
      - SingleUse
    SuggestResultItemList:
      type: array
      items:
        $ref: '#/components/schemas/SuggestResultItem'
    SuggestResultItemType:
      type: string
      enum:
      - Place
      - Query
    Token:
      type: string
      minLength: 1
      maxLength: 2000
    TypePlacement:
      type: string
      enum:
      - BeforeBaseName
      - AfterBaseName
    TypeSeparator:
      type: string
      pattern: ^$|^ $
      minLength: 0
      maxLength: 1
    ValidationExceptionFieldList:
      type: array
      items:
        $ref: '#/components/schemas/ValidationExceptionField'
    ValidationExceptionReason:
      type: string
      enum:
      - UnknownOperation
      - Missing
      - CannotParse
      - FieldValidationFailed
      - Other
      - UnknownField
    ZipClassificationCode:
      type: string
      enum:
      - Military
      - PostOfficeBoxes
      - Unique
