openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: geo_routes
  x-aws-serviceName: georoutes
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-11-19'
  title: Amazon Location Service Routes V2
  description: |-
    With the Amazon Location Routes API you can calculate routes and estimate travel time based on up-to-date road network and live traffic information.

    Calculate optimal travel routes and estimate travel times using up-to-date road network and traffic data. Key features include:

      * Point-to-point routing with estimated travel time, distance, and turn-by-turn directions

      * Multi-point route optimization to minimize travel time or distance

      * Route matrices for efficient multi-destination planning

      * Isoline calculations to determine reachable areas within specified time or distance thresholds

      * Map-matching to align GPS traces with the road network
servers:
- description: The Amazon Location Service Routes V2 regional endpoint
  url: https://geo-routes.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ApiKey:
      type: string
      maxLength: 1000
    ClusterIndex:
      type: integer
      minimum: 0
    CountryCode:
      type: string
      pattern: ^([A-Z]{2}|[A-Z]{3})$
      minLength: 2
      maxLength: 3
    CountryCode3:
      type: string
      pattern: ^[A-Z]{3}$
      minLength: 3
      maxLength: 3
    CurrencyCode:
      type: string
      pattern: ^[A-Z]{3}$
      minLength: 3
      maxLength: 3
    DayOfWeek:
      type: string
      enum:
      - Monday
      - Tuesday
      - Wednesday
      - Thursday
      - Friday
      - Saturday
      - Sunday
    GeometryFormat:
      type: string
      enum:
      - FlexiblePolyline
      - Simple
    IsolineEngineType:
      type: string
      enum:
      - Electric
      - InternalCombustion
      - PluginHybrid
    IsolineHazardousCargoType:
      type: string
      enum:
      - Combustible
      - Corrosive
      - Explosive
      - Flammable
      - Gas
      - HarmfulToWater
      - Organic
      - Other
      - Poison
      - PoisonousInhalation
      - Radioactive
    IsolineOptimizationObjective:
      type: string
      enum:
      - AccurateCalculation
      - BalancedCalculation
      - FastCalculation
    IsolineTravelMode:
      type: string
      enum:
      - Car
      - Pedestrian
      - Scooter
      - Truck
    IsolineTruckType:
      type: string
      enum:
      - LightTruck
      - StraightTruck
      - Tractor
    IsolineZoneCategory:
      type: string
      enum:
      - CongestionPricing
      - Environmental
      - Vignette
    LanguageTag:
      type: string
      minLength: 2
      maxLength: 35
    MatchingStrategy:
      type: string
      enum:
      - MatchAny
      - MatchMostSignificantRoad
    MeasurementSystem:
      type: string
      enum:
      - Metric
      - Imperial
    Polyline:
      type: string
      minLength: 1
    PolylineRing:
      type: string
      minLength: 1
    RoadSnapHazardousCargoType:
      type: string
      enum:
      - Combustible
      - Corrosive
      - Explosive
      - Flammable
      - Gas
      - HarmfulToWater
      - Organic
      - Other
      - Poison
      - PoisonousInhalation
      - Radioactive
    RoadSnapNoticeCode:
      type: string
      enum:
      - TracePointsHeadingIgnored
      - TracePointsIgnored
      - TracePointsMovedByLargeDistance
      - TracePointsNotMatched
      - TracePointsOutOfSequence
      - TracePointsSpeedEstimated
      - TracePointsSpeedIgnored
    RoadSnapTravelMode:
      type: string
      enum:
      - Car
      - Pedestrian
      - Scooter
      - Truck
    RouteDirection:
      type: string
      enum:
      - East
      - North
      - South
      - West
    RouteEngineType:
      type: string
      enum:
      - Electric
      - InternalCombustion
      - PluginHybrid
    RouteFerryAfterTravelStepType:
      type: string
      enum:
      - Deboard
    RouteFerryBeforeTravelStepType:
      type: string
      enum:
      - Board
    RouteFerryNoticeCode:
      type: string
      enum:
      - AccuratePolylineUnavailable
      - NoSchedule
      - Other
      - ViolatedAvoidFerry
      - ViolatedAvoidRailFerry
      - SeasonalClosure
    RouteFerryTravelStepType:
      type: string
      enum:
      - Depart
      - Continue
      - Arrive
    RouteHazardousCargoType:
      type: string
      enum:
      - Combustible
      - Corrosive
      - Explosive
      - Flammable
      - Gas
      - HarmfulToWater
      - Organic
      - Other
      - Poison
      - PoisonousInhalation
      - Radioactive
    RouteLegAdditionalFeature:
      type: string
      enum:
      - Elevation
      - Incidents
      - PassThroughWaypoints
      - Summary
      - Tolls
      - TravelStepInstructions
      - TruckRoadTypes
      - TypicalDuration
      - Zones
    RouteLegTravelMode:
      type: string
      enum:
      - Car
      - Ferry
      - Pedestrian
      - Scooter
      - Truck
      - CarShuttleTrain
    RouteLegType:
      type: string
      enum:
      - Ferry
      - Pedestrian
      - Vehicle
    RouteMatrixErrorCode:
      type: string
      enum:
      - NoMatch
      - NoMatchDestination
      - NoMatchOrigin
      - NoRoute
      - OutOfBounds
      - OutOfBoundsDestination
      - OutOfBoundsOrigin
      - Other
      - Violation
    RouteMatrixHazardousCargoType:
      type: string
      enum:
      - Combustible
      - Corrosive
      - Explosive
      - Flammable
      - Gas
      - HarmfulToWater
      - Organic
      - Other
      - Poison
      - PoisonousInhalation
      - Radioactive
    RouteMatrixTravelMode:
      type: string
      enum:
      - Car
      - Pedestrian
      - Scooter
      - Truck
    RouteMatrixTruckType:
      type: string
      enum:
      - LightTruck
      - StraightTruck
      - Tractor
    RouteMatrixZoneCategory:
      type: string
      enum:
      - CongestionPricing
      - Environmental
      - Vignette
    RouteNoticeImpact:
      type: string
      enum:
      - High
      - Low
    RoutePedestrianNoticeCode:
      type: string
      enum:
      - AccuratePolylineUnavailable
      - Other
      - ViolatedAvoidDirtRoad
      - ViolatedAvoidTunnel
      - ViolatedPedestrianOption
    RoutePedestrianTravelStepType:
      type: string
      enum:
      - Arrive
      - Continue
      - Depart
      - Keep
      - RoundaboutEnter
      - RoundaboutExit
      - RoundaboutPass
      - Turn
      - Exit
      - Ramp
      - UTurn
    RouteResponseNoticeCode:
      type: string
      enum:
      - MainLanguageNotFound
      - Other
      - TravelTimeExceedsDriverWorkHours
    RouteRoadType:
      type: string
      enum:
      - Highway
      - Rural
      - Urban
    RouteSideOfStreet:
      type: string
      enum:
      - Left
      - Right
    RouteSpanAdditionalFeature:
      type: string
      enum:
      - BestCaseDuration
      - CarAccess
      - Country
      - Distance
      - Duration
      - DynamicSpeed
      - FunctionalClassification
      - Gates
      - Incidents
      - Names
      - Notices
      - PedestrianAccess
      - RailwayCrossings
      - Region
      - RoadAttributes
      - RouteNumbers
      - ScooterAccess
      - SpeedLimit
      - TollSystems
      - TruckAccess
      - TruckRoadTypes
      - TypicalDuration
      - Zones
      - Consumption
    RouteSpanCarAccessAttribute:
      type: string
      enum:
      - Allowed
      - NoThroughTraffic
      - TollRoad
    RouteSpanGateAttribute:
      type: string
      enum:
      - Emergency
      - KeyAccess
      - PermissionRequired
    RouteSpanPedestrianAccessAttribute:
      type: string
      enum:
      - Allowed
      - Indoors
      - NoThroughTraffic
      - Park
      - Stairs
      - TollRoad
    RouteSpanRailwayCrossingAttribute:
      type: string
      enum:
      - Protected
      - Unprotected
    RouteSpanRoadAttribute:
      type: string
      enum:
      - Bridge
      - BuiltUpArea
      - ControlledAccessHighway
      - DirtRoad
      - DividedRoad
      - Motorway
      - PrivateRoad
      - Ramp
      - RightHandTraffic
      - Roundabout
      - Tunnel
      - UnderConstruction
    RouteSpanScooterAccessAttribute:
      type: string
      enum:
      - Allowed
      - NoThroughTraffic
      - TollRoad
    RouteSpanTruckAccessAttribute:
      type: string
      enum:
      - Allowed
      - NoThroughTraffic
      - TollRoad
    RouteSteeringDirection:
      type: string
      enum:
      - Left
      - Right
      - Straight
    RouteTollPassValidityPeriodType:
      type: string
      enum:
      - Annual
      - Days
      - ExtendedAnnual
      - Minutes
      - Months
    RouteTollPaymentMethod:
      type: string
      enum:
      - BankCard
      - Cash
      - CashExact
      - CreditCard
      - PassSubscription
      - TravelCard
      - Transponder
      - VideoToll
    RouteTollVehicleCategory:
      type: string
      enum:
      - Minibus
    RouteTravelMode:
      type: string
      enum:
      - Car
      - Pedestrian
      - Scooter
      - Truck
    RouteTravelStepType:
      type: string
      enum:
      - Default
      - TurnByTurn
    RouteTruckType:
      type: string
      enum:
      - LightTruck
      - StraightTruck
      - Tractor
    RouteTurnIntensity:
      type: string
      enum:
      - Sharp
      - Slight
      - Typical
    RouteVehicleIncidentSeverity:
      type: string
      enum:
      - Critical
      - High
      - Medium
      - Low
    RouteVehicleIncidentType:
      type: string
      enum:
      - Accident
      - Congestion
      - Construction
      - DisabledVehicle
      - LaneRestriction
      - MassTransit
      - Other
      - PlannedEvent
      - RoadClosure
      - RoadHazard
      - Weather
    RouteVehicleNoticeCode:
      type: string
      enum:
      - AccuratePolylineUnavailable
      - Other
      - PotentialViolatedAvoidTollRoadUsage
      - PotentialViolatedCarpoolUsage
      - PotentialViolatedTurnRestrictionUsage
      - PotentialViolatedVehicleRestrictionUsage
      - PotentialViolatedZoneRestrictionUsage
      - SeasonalClosure
      - TollsDataTemporarilyUnavailable
      - TollsDataUnavailable
      - TollTransponder
      - ViolatedAvoidControlledAccessHighway
      - ViolatedAvoidDifficultTurns
      - ViolatedAvoidDirtRoad
      - ViolatedAvoidSeasonalClosure
      - ViolatedAvoidTollRoad
      - ViolatedAvoidTollTransponder
      - ViolatedAvoidTruckRoadType
      - ViolatedAvoidTunnel
      - ViolatedAvoidUTurns
      - ViolatedBlockedRoad
      - ViolatedCarpool
      - ViolatedEmergencyGate
      - ViolatedStartDirection
      - ViolatedTurnRestriction
      - ViolatedVehicleRestriction
      - ViolatedZoneRestriction
    RouteVehicleTravelStepType:
      type: string
      enum:
      - Arrive
      - Continue
      - ContinueHighway
      - Depart
      - EnterHighway
      - Exit
      - Keep
      - Ramp
      - RoundaboutEnter
      - RoundaboutExit
      - RoundaboutPass
      - Turn
      - UTurn
    RouteWeightConstraintType:
      type: string
      enum:
      - Current
      - Gross
      - Unknown
    RouteZoneCategory:
      type: string
      enum:
      - CongestionPricing
      - Environmental
      - Vignette
    RoutingObjective:
      type: string
      enum:
      - FastestRoute
      - ShortestRoute
    SensitiveString:
      type: string
    SideOfStreetMatchingStrategy:
      type: string
      enum:
      - AnyStreet
      - DividedStreetOnly
    TimeOfDay:
      type: string
      pattern: ^([0-1]?[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](Z|[+-]([0-1]?[0-9]|2[0-3]):[0-5][0-9])$
    TimestampWithTimezoneOffset:
      type: string
      pattern: ^([1-2][0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9]|60)(\.[0-9]{0,9})?(Z|[+-]([01][0-9]|2[0-3]):[0-5][0-9])$
    TrafficUsage:
      type: string
      enum:
      - IgnoreTrafficData
      - UseTrafficData
    TruckRoadType:
      type: string
      minLength: 1
      maxLength: 3
    TunnelRestrictionCode:
      type: string
      minLength: 1
      maxLength: 1
    ValidationExceptionReason:
      type: string
      enum:
      - UnknownOperation
      - Missing
      - CannotParse
      - FieldValidationFailed
      - Other
      - UnknownField
    WaypointId:
      type: string
      minLength: 1
      maxLength: 100
    WaypointIndex:
      type: integer
      default: 0
    WaypointOptimizationClusteringAlgorithm:
      type: string
      enum:
      - DrivingDistance
      - TopologySegment
    WaypointOptimizationConstraint:
      type: string
      enum:
      - AccessHours
      - AppointmentTime
      - Before
      - Heading
      - ServiceDuration
      - SideOfStreet
    WaypointOptimizationHazardousCargoType:
      type: string
      enum:
      - Combustible
      - Corrosive
      - Explosive
      - Flammable
      - Gas
      - HarmfulToWater
      - Organic
      - Other
      - Poison
      - PoisonousInhalation
      - Radioactive
    WaypointOptimizationSequencingObjective:
      type: string
      enum:
      - FastestRoute
      - ShortestRoute
    WaypointOptimizationServiceTimeTreatment:
      type: string
      enum:
      - Rest
      - Work
    WaypointOptimizationTravelMode:
      type: string
      enum:
      - Car
      - Pedestrian
      - Scooter
      - Truck
    WaypointOptimizationTruckType:
      type: string
      enum:
      - StraightTruck
      - Tractor
