openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: grafana
  x-aws-serviceName: grafana
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-08-18'
  title: Amazon Managed Grafana
  description: |-
    Amazon Managed Grafana is a fully managed and secure data visualization service that you can use to instantly query, correlate, and visualize operational metrics, logs, and traces from multiple sources. Amazon Managed Grafana makes it easy to deploy, operate, and scale Grafana, a widely deployed data visualization tool that is popular for its extensible data support.

    With Amazon Managed Grafana, you create logically isolated Grafana servers called _workspaces_. In a workspace, you can create Grafana dashboards and visualizations to analyze your metrics, logs, and traces without having to build, package, or deploy any hardware to run Grafana servers.
servers:
- description: The Amazon Managed Grafana regional endpoint
  url: https://grafana.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccountAccessType:
      type: string
      enum:
      - CURRENT_ACCOUNT
      - ORGANIZATION
    AllowedOrganization:
      type: string
      minLength: 1
      maxLength: 256
    AllowedOrganizations:
      type: array
      items:
        $ref: '#/components/schemas/AllowedOrganization'
    ApiKeyName:
      type: string
      minLength: 1
      maxLength: 100
    ApiKeyToken:
      type: string
    AssertionAttribute:
      type: string
      minLength: 1
      maxLength: 256
    AuthenticationProviderTypes:
      type: string
      enum:
      - AWS_SSO
      - SAML
    AuthenticationProviders:
      type: array
      items:
        $ref: '#/components/schemas/AuthenticationProviderTypes'
    ClientToken:
      type: string
      pattern: ^[!-~]{1,64}$
    DataSourceType:
      type: string
      enum:
      - AMAZON_OPENSEARCH_SERVICE
      - CLOUDWATCH
      - PROMETHEUS
      - XRAY
      - TIMESTREAM
      - SITEWISE
      - ATHENA
      - REDSHIFT
      - TWINMAKER
    DataSourceTypesList:
      type: array
      items:
        $ref: '#/components/schemas/DataSourceType'
    Description:
      type: string
      minLength: 0
      maxLength: 2048
    Endpoint:
      type: string
      minLength: 1
      maxLength: 2048
    GrafanaToken:
      type: string
      minLength: 1
      maxLength: 36
    GrafanaVersion:
      type: string
      minLength: 1
      maxLength: 255
    GrafanaVersionList:
      type: array
      items:
        $ref: '#/components/schemas/GrafanaVersion'
    IamRoleArn:
      type: string
      minLength: 1
      maxLength: 2048
    IdpMetadata:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/IdpMetadataUrl'
        description: |-
          The URL of the location containing the IdP metadata.
      - allOf:
        - $ref: '#/components/schemas/String'
        description: |-
          The full IdP metadata, in XML format.
      description: |-
        A structure containing the identity provider (IdP) metadata used to integrate the identity provider with this workspace. You can specify the metadata either by providing a URL to its location in the `url` parameter, or by specifying the full metadata in XML format in the `xml` parameter. Specifying both will cause an error.
    IdpMetadataUrl:
      type: string
      minLength: 1
      maxLength: 2048
    LicenseType:
      type: string
      enum:
      - ENTERPRISE
      - ENTERPRISE_FREE_TRIAL
    LoginValidityDuration:
      type: integer
      default: 0
    NotificationDestinationType:
      type: string
      enum:
      - SNS
    NotificationDestinationsList:
      type: array
      items:
        $ref: '#/components/schemas/NotificationDestinationType'
    OrganizationRoleName:
      type: string
      minLength: 1
      maxLength: 2048
    OrganizationalUnit:
      type: string
    OrganizationalUnitList:
      type: array
      items:
        $ref: '#/components/schemas/OrganizationalUnit'
      x-sensitive: true
    OverridableConfigurationJson:
      type: string
      minLength: 2
      maxLength: 65536
    PaginationToken:
      type: string
    PermissionEntryList:
      type: array
      items:
        $ref: '#/components/schemas/PermissionEntry'
    PermissionType:
      type: string
      enum:
      - CUSTOMER_MANAGED
      - SERVICE_MANAGED
    PrefixListId:
      type: string
      minLength: 1
      maxLength: 100
    PrefixListIds:
      type: array
      items:
        $ref: '#/components/schemas/PrefixListId'
    Role:
      type: string
      enum:
      - ADMIN
      - EDITOR
      - VIEWER
    RoleValue:
      type: string
      minLength: 1
      maxLength: 256
    RoleValueList:
      type: array
      items:
        $ref: '#/components/schemas/RoleValue'
      x-sensitive: true
    SSOClientId:
      type: string
    SamlConfigurationStatus:
      type: string
      enum:
      - CONFIGURED
      - NOT_CONFIGURED
    SecurityGroupId:
      type: string
      minLength: 0
      maxLength: 255
    SecurityGroupIds:
      type: array
      items:
        $ref: '#/components/schemas/SecurityGroupId'
    ServiceAccountList:
      type: array
      items:
        $ref: '#/components/schemas/ServiceAccountSummary'
    ServiceAccountName:
      type: string
      minLength: 1
      maxLength: 128
    ServiceAccountTokenKey:
      type: string
    ServiceAccountTokenList:
      type: array
      items:
        $ref: '#/components/schemas/ServiceAccountTokenSummary'
    ServiceAccountTokenName:
      type: string
      minLength: 1
      maxLength: 128
    SsoId:
      type: string
      minLength: 1
      maxLength: 47
    StackSetName:
      type: string
    SubnetId:
      type: string
      minLength: 0
      maxLength: 255
    SubnetIds:
      type: array
      items:
        $ref: '#/components/schemas/SubnetId'
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagKeys:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    UpdateAction:
      type: string
      enum:
      - ADD
      - REVOKE
    UpdateErrorList:
      type: array
      items:
        $ref: '#/components/schemas/UpdateError'
    UpdateInstructionBatch:
      type: array
      items:
        $ref: '#/components/schemas/UpdateInstruction'
    UserList:
      type: array
      items:
        $ref: '#/components/schemas/User'
    UserType:
      type: string
      enum:
      - SSO_USER
      - SSO_GROUP
    ValidationExceptionFieldList:
      type: array
      items:
        $ref: '#/components/schemas/ValidationExceptionField'
    ValidationExceptionReason:
      type: string
      enum:
      - UNKNOWN_OPERATION
      - CANNOT_PARSE
      - FIELD_VALIDATION_FAILED
      - OTHER
    VpceId:
      type: string
      minLength: 1
      maxLength: 100
    VpceIds:
      type: array
      items:
        $ref: '#/components/schemas/VpceId'
    WorkspaceId:
      type: string
      pattern: ^g-[0-9a-f]{10}$
    WorkspaceList:
      type: array
      items:
        $ref: '#/components/schemas/WorkspaceSummary'
    WorkspaceName:
      type: string
      pattern: ^[a-zA-Z0-9-._~]{1,255}$
    WorkspaceStatus:
      type: string
      enum:
      - ACTIVE
      - CREATING
      - DELETING
      - FAILED
      - UPDATING
      - UPGRADING
      - DELETION_FAILED
      - CREATION_FAILED
      - UPDATE_FAILED
      - UPGRADE_FAILED
      - LICENSE_REMOVAL_FAILED
      - VERSION_UPDATING
      - VERSION_UPDATE_FAILED
