openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: grafana
  x-aws-serviceName: grafana
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-08-18'
  title: Amazon Managed Grafana
  description: |-
    Amazon Managed Grafana is a fully managed and secure data visualization service that you can use to instantly query, correlate, and visualize operational metrics, logs, and traces from multiple sources. Amazon Managed Grafana makes it easy to deploy, operate, and scale Grafana, a widely deployed data visualization tool that is popular for its extensible data support.

    With Amazon Managed Grafana, you create logically isolated Grafana servers called _workspaces_. In a workspace, you can create Grafana dashboards and visualizations to analyze your metrics, logs, and traces without having to build, package, or deploy any hardware to run Grafana servers.
servers:
- description: The Amazon Managed Grafana regional endpoint
  url: https://grafana.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccountAccessType:
      type: string
      enum:
      - CURRENT_ACCOUNT
      - ORGANIZATION
    AllowedOrganization:
      type: string
      minLength: 1
      maxLength: 256
    ApiKeyName:
      type: string
      minLength: 1
      maxLength: 100
    ApiKeyToken:
      type: string
    AssertionAttribute:
      type: string
      minLength: 1
      maxLength: 256
    AuthenticationProviderTypes:
      type: string
      enum:
      - AWS_SSO
      - SAML
    ClientToken:
      type: string
      pattern: ^[!-~]{1,64}$
    DataSourceType:
      type: string
      enum:
      - AMAZON_OPENSEARCH_SERVICE
      - CLOUDWATCH
      - PROMETHEUS
      - XRAY
      - TIMESTREAM
      - SITEWISE
      - ATHENA
      - REDSHIFT
      - TWINMAKER
    Description:
      type: string
      minLength: 0
      maxLength: 2048
    Endpoint:
      type: string
      minLength: 1
      maxLength: 2048
    GrafanaToken:
      type: string
      minLength: 1
      maxLength: 36
    GrafanaVersion:
      type: string
      minLength: 1
      maxLength: 255
    IamRoleArn:
      type: string
      minLength: 1
      maxLength: 2048
    IdpMetadataUrl:
      type: string
      minLength: 1
      maxLength: 2048
    LicenseType:
      type: string
      enum:
      - ENTERPRISE
      - ENTERPRISE_FREE_TRIAL
    LoginValidityDuration:
      type: integer
      default: 0
    NotificationDestinationType:
      type: string
      enum:
      - SNS
    OrganizationRoleName:
      type: string
      minLength: 1
      maxLength: 2048
    OrganizationalUnit:
      type: string
    OverridableConfigurationJson:
      type: string
      minLength: 2
      maxLength: 65536
    PaginationToken:
      type: string
    PermissionType:
      type: string
      enum:
      - CUSTOMER_MANAGED
      - SERVICE_MANAGED
    PrefixListId:
      type: string
      minLength: 1
      maxLength: 100
    Role:
      type: string
      enum:
      - ADMIN
      - EDITOR
      - VIEWER
    RoleValue:
      type: string
      minLength: 1
      maxLength: 256
    SSOClientId:
      type: string
    SamlConfigurationStatus:
      type: string
      enum:
      - CONFIGURED
      - NOT_CONFIGURED
    SecurityGroupId:
      type: string
      minLength: 0
      maxLength: 255
    ServiceAccountName:
      type: string
      minLength: 1
      maxLength: 128
    ServiceAccountTokenKey:
      type: string
    ServiceAccountTokenName:
      type: string
      minLength: 1
      maxLength: 128
    SsoId:
      type: string
      minLength: 1
      maxLength: 47
    StackSetName:
      type: string
    SubnetId:
      type: string
      minLength: 0
      maxLength: 255
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    UpdateAction:
      type: string
      enum:
      - ADD
      - REVOKE
    UserType:
      type: string
      enum:
      - SSO_USER
      - SSO_GROUP
    ValidationExceptionReason:
      type: string
      enum:
      - UNKNOWN_OPERATION
      - CANNOT_PARSE
      - FIELD_VALIDATION_FAILED
      - OTHER
    VpceId:
      type: string
      minLength: 1
      maxLength: 100
    WorkspaceId:
      type: string
      pattern: ^g-[0-9a-f]{10}$
    WorkspaceName:
      type: string
      pattern: ^[a-zA-Z0-9-._~]{1,255}$
    WorkspaceStatus:
      type: string
      enum:
      - ACTIVE
      - CREATING
      - DELETING
      - FAILED
      - UPDATING
      - UPGRADING
      - DELETION_FAILED
      - CREATION_FAILED
      - UPDATE_FAILED
      - UPGRADE_FAILED
      - LICENSE_REMOVAL_FAILED
      - VERSION_UPDATING
      - VERSION_UPDATE_FAILED
