openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: greengrass
  x-aws-serviceName: greengrass
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-06-07'
  title: AWS Greengrass
  description: |-
    AWS IoT Greengrass seamlessly extends AWS onto physical devices so they can act locally on the data they generate, while still using the cloud for management, analytics, and durable storage. AWS IoT Greengrass ensures your devices can respond quickly to local events and operate with intermittent connectivity. AWS IoT Greengrass minimizes the cost of transmitting data to the cloud by allowing you to author AWS Lambda functions that execute locally.
servers:
- description: The AWS Greengrass regional endpoint
  url: https://greengrass.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    BulkDeploymentResults:
      type: array
      items:
        $ref: '#/components/schemas/BulkDeploymentResult'
    BulkDeploymentStatus:
      type: string
      enum:
      - Initializing
      - Running
      - Completed
      - Stopping
      - Stopped
      - Failed
      description: The current status of the bulk deployment.
    BulkDeployments:
      type: array
      items:
        $ref: '#/components/schemas/BulkDeployment'
    ConfigurationSyncStatus:
      type: string
      enum:
      - InSync
      - OutOfSync
    DeploymentType:
      type: string
      enum:
      - NewDeployment
      - Redeployment
      - ResetDeployment
      - ForceResetDeployment
      description: The type of deployment. When used for ''CreateDeployment'', only
        ''NewDeployment'' and ''Redeployment'' are valid.
    Deployments:
      type: array
      items:
        $ref: '#/components/schemas/Deployment'
    EncodingType:
      type: string
      enum:
      - binary
      - json
    ErrorDetails:
      type: array
      items:
        $ref: '#/components/schemas/ErrorDetail'
      description: A list of error details.
    FunctionIsolationMode:
      type: string
      enum:
      - GreengrassContainer
      - NoContainer
      description: Specifies whether the Lambda function runs in a Greengrass container
        (default) or without containerization. Unless your scenario requires that
        you run without containerization, we recommend that you run in a Greengrass
        container. Omit this value to run the Lambda function with the default containerization
        for the group.
    LoggerComponent:
      type: string
      enum:
      - GreengrassSystem
      - Lambda
    LoggerLevel:
      type: string
      enum:
      - DEBUG
      - INFO
      - WARN
      - ERROR
      - FATAL
    LoggerType:
      type: string
      enum:
      - FileSystem
      - AWSCloudWatch
    Permission:
      type: string
      enum:
      - ro
      - rw
      description: The type of permission a function has to access a resource.
    S3UrlSignerRole:
      type: string
    SoftwareToUpdate:
      type: string
      enum:
      - core
      - ota_agent
      description: The piece of software on the Greengrass core that will be updated.
    Tags:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/__string'
      description: The key-value pair for the resource tag.
    Telemetry:
      type: string
      enum:
      - 'On'
      - 'Off'
    UpdateAgentLogLevel:
      type: string
      enum:
      - NONE
      - TRACE
      - DEBUG
      - VERBOSE
      - INFO
      - WARN
      - ERROR
      - FATAL
      description: The minimum level of log statements that should be logged by the
        OTA Agent during an update.
    UpdateTargets:
      type: array
      items:
        $ref: '#/components/schemas/__string'
      description: The ARNs of the targets (IoT things or IoT thing groups) that this
        update will be applied to.
    UpdateTargetsArchitecture:
      type: string
      enum:
      - armv6l
      - armv7l
      - x86_64
      - aarch64
      description: The architecture of the cores which are the targets of an update.
    UpdateTargetsOperatingSystem:
      type: string
      enum:
      - ubuntu
      - raspbian
      - amazon_linux
      - openwrt
      description: The operating system of the cores which are the targets of an update.
    __boolean:
      type: boolean
    __integer:
      type: integer
    __listOfConnectivityInfo:
      type: array
      items:
        $ref: '#/components/schemas/ConnectivityInfo'
    __listOfConnector:
      type: array
      items:
        $ref: '#/components/schemas/Connector'
    __listOfCore:
      type: array
      items:
        $ref: '#/components/schemas/Core'
    __listOfDefinitionInformation:
      type: array
      items:
        $ref: '#/components/schemas/DefinitionInformation'
    __listOfDevice:
      type: array
      items:
        $ref: '#/components/schemas/Device'
    __listOfFunction:
      type: array
      items:
        $ref: '#/components/schemas/Function'
    __listOfGroupCertificateAuthorityProperties:
      type: array
      items:
        $ref: '#/components/schemas/GroupCertificateAuthorityProperties'
    __listOfGroupInformation:
      type: array
      items:
        $ref: '#/components/schemas/GroupInformation'
    __listOfLogger:
      type: array
      items:
        $ref: '#/components/schemas/Logger'
    __listOfResource:
      type: array
      items:
        $ref: '#/components/schemas/Resource'
    __listOfResourceAccessPolicy:
      type: array
      items:
        $ref: '#/components/schemas/ResourceAccessPolicy'
    __listOfSubscription:
      type: array
      items:
        $ref: '#/components/schemas/Subscription'
    __listOfVersionInformation:
      type: array
      items:
        $ref: '#/components/schemas/VersionInformation'
    __listOf__string:
      type: array
      items:
        $ref: '#/components/schemas/__string'
    __mapOf__string:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/__string'
    __string:
      type: string
