openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: greengrassv2
  x-aws-serviceName: greengrassv2
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-11-30'
  title: AWS IoT Greengrass V2
  description: |-
    IoT Greengrass brings local compute, messaging, data management, sync, and ML inference capabilities to edge devices. This enables devices to collect and analyze data closer to the source of information, react autonomously to local events, and communicate securely with each other on local networks. Local devices can also communicate securely with Amazon Web Services IoT Core and export IoT data to the Amazon Web Services Cloud. IoT Greengrass developers can use Lambda functions and components to create and deploy applications to fleets of edge devices for local operation.

    IoT Greengrass Version 2 provides a new major version of the IoT Greengrass Core software, new APIs, and a new console. Use this API reference to learn how to use the IoT Greengrass V2 API operations to manage components, manage deployments, and core devices.

    For more information, see [What is IoT Greengrass?](https://docs.aws.amazon.com/greengrass/v2/developerguide/what-is-iot-greengrass.html) in the _IoT Greengrass V2 Developer Guide_.
servers:
- description: The AWS IoT Greengrass V2 regional endpoint
  url: https://greengrass.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ClientTokenString:
      type: string
      pattern: ^[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 64
    ComponentARN:
      type: string
      pattern: ^arn:[^:]*:greengrass:[^:]*:(aws|[0-9]+):components:[^:]+$
    ComponentConfigurationPath:
      type: string
      minLength: 0
      maxLength: 256
    ComponentConfigurationString:
      type: string
      minLength: 1
      maxLength: 10485760
    ComponentNameString:
      type: string
      minLength: 1
      maxLength: 128
    ComponentVersionARN:
      type: string
      pattern: ^arn:[^:]*:greengrass:[^:]*:(aws|[0-9]+):components:[^:]+:versions:[^:]+$
    ComponentVersionString:
      type: string
      minLength: 1
      maxLength: 64
    CoreDeviceArchitectureString:
      type: string
      minLength: 1
      maxLength: 255
    CoreDevicePlatformString:
      type: string
      minLength: 1
      maxLength: 255
    CoreDeviceRuntimeString:
      type: string
      minLength: 1
      maxLength: 255
    CoreDeviceThingName:
      type: string
      minLength: 1
      maxLength: 128
    DefaultMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    DeploymentID:
      type: string
    DeploymentName:
      type: string
    DeploymentNameString:
      type: string
      minLength: 1
      maxLength: 256
    Description:
      type: string
      minLength: 1
      maxLength: 500
    DescriptionString:
      type: string
    EffectiveDeploymentErrorCode:
      type: string
      minLength: 1
      maxLength: 255
    EffectiveDeploymentErrorType:
      type: string
      minLength: 1
      maxLength: 255
    FileSystemPath:
      type: string
    GGCVersion:
      type: string
      minLength: 1
      maxLength: 255
    GenericV2ARN:
      type: string
      pattern: '^arn:[^:]*:greengrass:[^:]*:(aws|[0-9]+):(components|deployments|coreDevices):'
    InstalledComponentLifecycleStatusCode:
      type: string
      minLength: 1
      maxLength: 255
    IoTJobARN:
      type: string
      pattern: ^arn:[^:]*:iot:[^:]+:[0-9]+:job/.+$
    IoTJobId:
      type: string
      minLength: 1
      maxLength: 255
    IoTJobMaxExecutionsPerMin:
      type: integer
      minimum: 1
      maximum: 1000
    IoTJobMinimumNumberOfExecutedThings:
      type: integer
      minimum: 1
    IoTJobNumberOfThings:
      type: integer
      minimum: 1
    IoTJobRolloutBaseRatePerMinute:
      type: integer
      minimum: 1
      maximum: 1000
    IoTThingName:
      type: string
      minLength: 1
      maxLength: 128
    IsLatestForTarget:
      type: boolean
      default: false
    IsRoot:
      type: boolean
      default: false
    LambdaExecArg:
      type: string
    LifecycleStateDetails:
      type: string
      minLength: 1
      maxLength: 1000
    NextTokenString:
      type: string
    NonEmptyString:
      type: string
      minLength: 1
    NullableString:
      type: string
    OptionalBoolean:
      type: boolean
      default: false
    OptionalInteger:
      type: integer
      default: 0
    PortNumberInt:
      type: integer
      default: 0
      minimum: 0
      maximum: 65535
    PublisherString:
      type: string
    Reason:
      type: string
    RetryAfterSeconds:
      type: integer
      default: 0
    String:
      type: string
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TargetARN:
      type: string
      pattern: ^arn:[^:]*:iot:[^:]*:[0-9]+:(thing|thinggroup)/.+$
    ThingGroupARN:
      type: string
      pattern: ^arn:[^:]*:iot:[^:]*:[0-9]+:thinggroup/.+$
    TopicString:
      type: string
