openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: greengrassv2
  x-aws-serviceName: greengrassv2
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-11-30'
  title: AWS IoT Greengrass V2
  description: |-
    IoT Greengrass brings local compute, messaging, data management, sync, and ML inference capabilities to edge devices. This enables devices to collect and analyze data closer to the source of information, react autonomously to local events, and communicate securely with each other on local networks. Local devices can also communicate securely with Amazon Web Services IoT Core and export IoT data to the Amazon Web Services Cloud. IoT Greengrass developers can use Lambda functions and components to create and deploy applications to fleets of edge devices for local operation.

    IoT Greengrass Version 2 provides a new major version of the IoT Greengrass Core software, new APIs, and a new console. Use this API reference to learn how to use the IoT Greengrass V2 API operations to manage components, manage deployments, and core devices.

    For more information, see [What is IoT Greengrass?](https://docs.aws.amazon.com/greengrass/v2/developerguide/what-is-iot-greengrass.html) in the _IoT Greengrass V2 Developer Guide_.
servers:
- description: The AWS IoT Greengrass V2 regional endpoint
  url: https://greengrass.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AssociateClientDeviceWithCoreDeviceEntryList:
      type: array
      items:
        $ref: '#/components/schemas/AssociateClientDeviceWithCoreDeviceEntry'
    AssociateClientDeviceWithCoreDeviceErrorList:
      type: array
      items:
        $ref: '#/components/schemas/AssociateClientDeviceWithCoreDeviceErrorEntry'
    AssociatedClientDeviceList:
      type: array
      items:
        $ref: '#/components/schemas/AssociatedClientDevice'
    CPU:
      type: number
      format: double
      default: 0
      minimum: 0
    ClientTokenString:
      type: string
      pattern: ^[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 64
    CloudComponentState:
      type: string
      enum:
      - REQUESTED
      - INITIATED
      - DEPLOYABLE
      - FAILED
      - DEPRECATED
    ComponentARN:
      type: string
      pattern: ^arn:[^:]*:greengrass:[^:]*:(aws|[0-9]+):components:[^:]+$
    ComponentCandidateList:
      type: array
      items:
        $ref: '#/components/schemas/ComponentCandidate'
    ComponentConfigurationPath:
      type: string
      minLength: 0
      maxLength: 256
    ComponentConfigurationPathList:
      type: array
      items:
        $ref: '#/components/schemas/ComponentConfigurationPath'
    ComponentConfigurationString:
      type: string
      minLength: 1
      maxLength: 10485760
    ComponentDependencyMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ComponentDependencyRequirement'
    ComponentDependencyType:
      type: string
      enum:
      - HARD
      - SOFT
    ComponentDeploymentSpecifications:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ComponentDeploymentSpecification'
    ComponentList:
      type: array
      items:
        $ref: '#/components/schemas/Component'
    ComponentNameString:
      type: string
      minLength: 1
      maxLength: 128
    ComponentPlatformList:
      type: array
      items:
        $ref: '#/components/schemas/ComponentPlatform'
    ComponentVersionARN:
      type: string
      pattern: ^arn:[^:]*:greengrass:[^:]*:(aws|[0-9]+):components:[^:]+:versions:[^:]+$
    ComponentVersionList:
      type: array
      items:
        $ref: '#/components/schemas/ComponentVersionListItem'
    ComponentVersionRequirementMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/NonEmptyString'
    ComponentVersionString:
      type: string
      minLength: 1
      maxLength: 64
    ComponentVisibilityScope:
      type: string
      enum:
      - PRIVATE
      - PUBLIC
    CoreDeviceArchitectureString:
      type: string
      minLength: 1
      maxLength: 255
    CoreDevicePlatformString:
      type: string
      minLength: 1
      maxLength: 255
    CoreDeviceRuntimeString:
      type: string
      minLength: 1
      maxLength: 255
    CoreDeviceStatus:
      type: string
      enum:
      - HEALTHY
      - UNHEALTHY
    CoreDeviceThingName:
      type: string
      minLength: 1
      maxLength: 128
    CoreDevicesList:
      type: array
      items:
        $ref: '#/components/schemas/CoreDevice'
    DefaultMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    DeploymentComponentUpdatePolicyAction:
      type: string
      enum:
      - NOTIFY_COMPONENTS
      - SKIP_NOTIFY_COMPONENTS
    DeploymentFailureHandlingPolicy:
      type: string
      enum:
      - ROLLBACK
      - DO_NOTHING
    DeploymentHistoryFilter:
      type: string
      enum:
      - ALL
      - LATEST_ONLY
    DeploymentID:
      type: string
    DeploymentList:
      type: array
      items:
        $ref: '#/components/schemas/Deployment'
    DeploymentName:
      type: string
    DeploymentNameString:
      type: string
      minLength: 1
      maxLength: 256
    DeploymentStatus:
      type: string
      enum:
      - ACTIVE
      - COMPLETED
      - CANCELED
      - FAILED
      - INACTIVE
    Description:
      type: string
      minLength: 1
      maxLength: 500
    DescriptionString:
      type: string
    DisassociateClientDeviceFromCoreDeviceEntryList:
      type: array
      items:
        $ref: '#/components/schemas/DisassociateClientDeviceFromCoreDeviceEntry'
    DisassociateClientDeviceFromCoreDeviceErrorList:
      type: array
      items:
        $ref: '#/components/schemas/DisassociateClientDeviceFromCoreDeviceErrorEntry'
    EffectiveDeploymentErrorCode:
      type: string
      minLength: 1
      maxLength: 255
    EffectiveDeploymentErrorStack:
      type: array
      items:
        $ref: '#/components/schemas/EffectiveDeploymentErrorCode'
    EffectiveDeploymentErrorType:
      type: string
      minLength: 1
      maxLength: 255
    EffectiveDeploymentErrorTypeList:
      type: array
      items:
        $ref: '#/components/schemas/EffectiveDeploymentErrorType'
    EffectiveDeploymentExecutionStatus:
      type: string
      enum:
      - IN_PROGRESS
      - QUEUED
      - FAILED
      - COMPLETED
      - TIMED_OUT
      - CANCELED
      - REJECTED
      - SUCCEEDED
    EffectiveDeploymentsList:
      type: array
      items:
        $ref: '#/components/schemas/EffectiveDeployment'
    FileSystemPath:
      type: string
    GGCVersion:
      type: string
      minLength: 1
      maxLength: 255
    GenericV2ARN:
      type: string
      pattern: '^arn:[^:]*:greengrass:[^:]*:(aws|[0-9]+):(components|deployments|coreDevices):'
    InstalledComponentLifecycleState:
      type: string
      enum:
      - NEW
      - INSTALLED
      - STARTING
      - RUNNING
      - STOPPING
      - ERRORED
      - BROKEN
      - FINISHED
    InstalledComponentLifecycleStatusCode:
      type: string
      minLength: 1
      maxLength: 255
    InstalledComponentLifecycleStatusCodeList:
      type: array
      items:
        $ref: '#/components/schemas/InstalledComponentLifecycleStatusCode'
    InstalledComponentList:
      type: array
      items:
        $ref: '#/components/schemas/InstalledComponent'
    InstalledComponentTopologyFilter:
      type: string
      enum:
      - ALL
      - ROOT
    IoTJobARN:
      type: string
      pattern: ^arn:[^:]*:iot:[^:]+:[0-9]+:job/.+$
    IoTJobAbortAction:
      type: string
      enum:
      - CANCEL
    IoTJobAbortCriteriaList:
      type: array
      items:
        $ref: '#/components/schemas/IoTJobAbortCriteria'
    IoTJobAbortThresholdPercentage:
      type: number
      format: double
      default: 0
      maximum: 100
    IoTJobExecutionFailureType:
      type: string
      enum:
      - FAILED
      - REJECTED
      - TIMED_OUT
      - ALL
    IoTJobId:
      type: string
      minLength: 1
      maxLength: 255
    IoTJobInProgressTimeoutInMinutes:
      type: integer
      format: int64
      default: 0
    IoTJobMaxExecutionsPerMin:
      type: integer
      minimum: 1
      maximum: 1000
    IoTJobMinimumNumberOfExecutedThings:
      type: integer
      minimum: 1
    IoTJobNumberOfThings:
      type: integer
      minimum: 1
    IoTJobRolloutBaseRatePerMinute:
      type: integer
      minimum: 1
      maximum: 1000
    IoTJobRolloutIncrementFactor:
      type: number
      format: double
      minimum: 1
      maximum: 5
    IoTThingName:
      type: string
      minLength: 1
      maxLength: 128
    IotEndpointType:
      type: string
      enum:
      - fips
      - standard
    IsLatestForTarget:
      type: boolean
      default: false
    IsRoot:
      type: boolean
      default: false
    LambdaDeviceList:
      type: array
      items:
        $ref: '#/components/schemas/LambdaDeviceMount'
    LambdaEnvironmentVariables:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    LambdaEventSourceList:
      type: array
      items:
        $ref: '#/components/schemas/LambdaEventSource'
    LambdaEventSourceType:
      type: string
      enum:
      - PUB_SUB
      - IOT_CORE
    LambdaExecArg:
      type: string
    LambdaExecArgsList:
      type: array
      items:
        $ref: '#/components/schemas/LambdaExecArg'
    LambdaFilesystemPermission:
      type: string
      enum:
      - ro
      - rw
    LambdaInputPayloadEncodingType:
      type: string
      enum:
      - json
      - binary
    LambdaIsolationMode:
      type: string
      enum:
      - GreengrassContainer
      - NoContainer
    LambdaVolumeList:
      type: array
      items:
        $ref: '#/components/schemas/LambdaVolumeMount'
    LifecycleStateDetails:
      type: string
      minLength: 1
      maxLength: 1000
    Memory:
      type: integer
      format: int64
      default: 0
      minimum: 0
      maximum: 9223372036854771712
    NextTokenString:
      type: string
    NonEmptyString:
      type: string
      minLength: 1
    NullableString:
      type: string
    OptionalBoolean:
      type: boolean
      default: false
    OptionalInteger:
      type: integer
      default: 0
    PlatformAttributesMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/NonEmptyString'
    PortNumberInt:
      type: integer
      default: 0
      minimum: 0
      maximum: 65535
    PublisherString:
      type: string
    Reason:
      type: string
    RecipeBlob:
      type: string
      format: byte
    RecipeOutputFormat:
      type: string
      enum:
      - JSON
      - YAML
    ResolvedComponentVersionsList:
      type: array
      items:
        $ref: '#/components/schemas/ResolvedComponentVersion'
    RetryAfterSeconds:
      type: integer
      default: 0
    S3EndpointType:
      type: string
      enum:
      - REGIONAL
      - GLOBAL
    String:
      type: string
    StringMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/NonEmptyString'
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TargetARN:
      type: string
      pattern: ^arn:[^:]*:iot:[^:]*:[0-9]+:(thing|thinggroup)/.+$
    ThingGroupARN:
      type: string
      pattern: ^arn:[^:]*:iot:[^:]*:[0-9]+:thinggroup/.+$
    Timestamp:
      type: string
      format: date-time
    TopicString:
      type: string
    ValidationExceptionFieldList:
      type: array
      items:
        $ref: '#/components/schemas/ValidationExceptionField'
    ValidationExceptionReason:
      type: string
      enum:
      - UNKNOWN_OPERATION
      - CANNOT_PARSE
      - FIELD_VALIDATION_FAILED
      - OTHER
    VendorGuidance:
      type: string
      enum:
      - ACTIVE
      - DISCONTINUED
      - DELETED
    connectivityInfoList:
      type: array
      items:
        $ref: '#/components/schemas/ConnectivityInfo'
