openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: groundstation
  x-aws-serviceName: groundstation
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2019-05-23'
  title: AWS Ground Station
  description: |-
    Welcome to the AWS Ground Station API Reference. AWS Ground Station is a fully managed service that enables you to control satellite communications, downlink and process satellite data, and scale your satellite operations efficiently and cost-effectively without having to build or manage your own ground station infrastructure.
servers:
- description: The AWS Ground Station regional endpoint
  url: https://groundstation.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AWSRegion:
      type: string
      pattern: ^[\w-]+$
      minLength: 1
      maxLength: 128
    AnyArn:
      type: string
      pattern: ^(arn:aws:)[\s\S]{0,1024}$
      minLength: 5
      maxLength: 1024
    BucketArn:
      type: string
    CapabilityArn:
      type: string
    ComponentTypeString:
      type: string
      pattern: ^[a-zA-Z0-9_]{1,64}$
    ConfigArn:
      type: string
      pattern: ^arn:aws:groundstation:[-a-z0-9]{1,50}:[0-9]{12}:config/[a-z0-9]+(-[a-z0-9]+){0,4}/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(/.{1,256})?$
      minLength: 82
      maxLength: 424
    CustomerEphemerisPriority:
      type: integer
      minimum: 1
      maximum: 99999
    DataflowEndpointGroupArn:
      type: string
      pattern: ^arn:aws:groundstation:[-a-z0-9]{1,50}:[0-9]{12}:dataflow-endpoint-group/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 97
      maxLength: 146
    DataflowEndpointGroupDurationInSeconds:
      type: integer
      minimum: 120
      maximum: 480
    DurationInSeconds:
      type: integer
      minimum: 0
      maximum: 21600
    EphemerisPriority:
      type: integer
      minimum: 0
      maximum: 99999
    GroundStationName:
      type: string
      pattern: ^[ a-zA-Z0-9-._:=]{4,256}$
      minLength: 4
      maxLength: 500
    InstanceId:
      type: string
      pattern: ^[a-z0-9-]{10,64}$
      minLength: 10
      maxLength: 64
    InstanceType:
      type: string
      pattern: ^[a-z0-9.-]{1,64}$
      minLength: 1
      maxLength: 64
    IpV4Address:
      type: string
      pattern: ^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$
      minLength: 7
      maxLength: 16
    JsonString:
      type: string
      pattern: ^[{}\[\]:.,"0-9A-Za-z\-_\s]{2,8192}$
      minLength: 2
      maxLength: 8192
    KeyAliasArn:
      type: string
      pattern: ^arn:aws[a-zA-Z-]{0,16}:kms:[-a-z0-9]{1,50}:[0-9]{12}:((alias/[a-zA-Z0-9:/_-]{1,256}))$
      minLength: 1
      maxLength: 512
    KeyAliasName:
      type: string
      pattern: ^alias/[a-zA-Z0-9:/_-]+$
      minLength: 1
      maxLength: 256
    KeyArn:
      type: string
    MissionProfileArn:
      type: string
      pattern: ^arn:aws:groundstation:[-a-z0-9]{1,50}:[0-9]{12}:mission-profile/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 89
      maxLength: 138
    Month:
      type: integer
      minimum: 1
      maximum: 12
    PaginationMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    PaginationToken:
      type: string
      pattern: ^[A-Za-z0-9-/+_.=]+$
      minLength: 3
      maxLength: 1000
    PositiveDurationInSeconds:
      type: integer
      minimum: 1
      maximum: 21600
    RoleArn:
      type: string
    S3BucketName:
      type: string
      pattern: ^[a-z0-9.-]{3,63}$
      minLength: 3
      maxLength: 63
    S3KeyPrefix:
      type: string
      pattern: ^([a-zA-Z0-9_\-=/]|\{satellite_id\}|\{config\-name}|\{s3\-config-id}|\{year\}|\{month\}|\{day\}){1,900}$
      minLength: 1
      maxLength: 900
    S3ObjectKey:
      type: string
      pattern: ^[a-zA-Z0-9!*'\)\(./_-]{1,1024}$
      minLength: 1
      maxLength: 1024
    S3VersionId:
      type: string
      pattern: ^[\s\S]{1,1024}$
      minLength: 1
      maxLength: 1024
    SafeName:
      type: string
      pattern: ^[ a-zA-Z0-9_:-]{1,256}$
      minLength: 1
      maxLength: 256
    TleLineOne:
      type: string
      pattern: '^1 [ 0-9]{5}[A-Z] [ 0-9]{5}[ A-Z]{3} [ 0-9]{5}[.][ 0-9]{8} (?:(?:[
        0+-][.][ 0-9]{8})|(?: [ +-][.][ 0-9]{7})) [ +-][ 0-9]{5}[+-][ 0-9] [ +-][
        0-9]{5}[+-][ 0-9] [ 0-9] [ 0-9]{4}[ 0-9]$'
      minLength: 69
      maxLength: 69
    TleLineTwo:
      type: string
      pattern: ^2 [ 0-9]{5} [ 0-9]{3}[.][ 0-9]{4} [ 0-9]{3}[.][ 0-9]{4} [ 0-9]{7}
        [ 0-9]{3}[.][ 0-9]{4} [ 0-9]{3}[.][ 0-9]{4} [ 0-9]{2}[.][ 0-9]{13}[ 0-9]$
      minLength: 69
      maxLength: 69
    UnboundedString:
      type: string
      pattern: ^[\s\S]+$
      minLength: 1
    Uuid:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 36
      maxLength: 36
    VersionString:
      type: string
      pattern: ^(0|[1-9]\d*)(\.(0|[1-9]\d*))*$
      minLength: 1
      maxLength: 64
    Year:
      type: integer
      minimum: 2018
      maximum: 3000
    noradSatelliteID:
      type: integer
      default: 0
      minimum: 0
      maximum: 99999
    satelliteArn:
      type: string
      pattern: ^arn:aws:groundstation:([-a-z0-9]{1,50})?:[0-9]{12}:satellite/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 82
      maxLength: 132
