openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: groundstation
  x-aws-serviceName: groundstation
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2019-05-23'
  title: AWS Ground Station
  description: |-
    Welcome to the AWS Ground Station API Reference. AWS Ground Station is a fully managed service that enables you to control satellite communications, downlink and process satellite data, and scale your satellite operations efficiently and cost-effectively without having to build or manage your own ground station infrastructure.
servers:
- description: The AWS Ground Station regional endpoint
  url: https://groundstation.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AWSRegion:
      type: string
      pattern: ^[\w-]+$
      minLength: 1
      maxLength: 128
    AgentCpuCoresList:
      type: array
      items:
        type: integer
    AgentStatus:
      type: string
      enum:
      - SUCCESS
      - FAILED
      - ACTIVE
      - INACTIVE
    AngleUnits:
      type: string
      enum:
      - DEGREE_ANGLE
      - RADIAN
    AnyArn:
      type: string
      pattern: ^(arn:aws:)[\s\S]{0,1024}$
      minLength: 5
      maxLength: 1024
    AuditResults:
      type: string
      enum:
      - HEALTHY
      - UNHEALTHY
    BandwidthUnits:
      type: string
      enum:
      - GHz
      - MHz
      - kHz
    BucketArn:
      type: string
    CapabilityArn:
      type: string
    CapabilityArnList:
      type: array
      items:
        $ref: '#/components/schemas/CapabilityArn'
    CapabilityHealth:
      type: string
      enum:
      - HEALTHY
      - UNHEALTHY
    CapabilityHealthReason:
      type: string
      enum:
      - NO_REGISTERED_AGENT
      - INVALID_IP_OWNERSHIP
      - NOT_AUTHORIZED_TO_CREATE_SLR
      - UNVERIFIED_IP_OWNERSHIP
      - INITIALIZING_DATAPLANE
      - DATAPLANE_FAILURE
      - HEALTHY
    CapabilityHealthReasonList:
      type: array
      items:
        $ref: '#/components/schemas/CapabilityHealthReason'
    ComponentStatusList:
      type: array
      items:
        $ref: '#/components/schemas/ComponentStatusData'
    ComponentTypeString:
      type: string
      pattern: ^[a-zA-Z0-9_]{1,64}$
    ComponentVersionList:
      type: array
      items:
        $ref: '#/components/schemas/ComponentVersion'
    ConfigArn:
      type: string
      pattern: ^arn:aws:groundstation:[-a-z0-9]{1,50}:[0-9]{12}:config/[a-z0-9]+(-[a-z0-9]+){0,4}/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(/.{1,256})?$
      minLength: 82
      maxLength: 424
    ConfigCapabilityType:
      type: string
      enum:
      - antenna-downlink
      - antenna-downlink-demod-decode
      - tracking
      - dataflow-endpoint
      - antenna-uplink
      - uplink-echo
      - s3-recording
    ConfigDetails:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/EndpointDetails'
      - allOf:
        - $ref: '#/components/schemas/AntennaDemodDecodeDetails'
        description: |-
          Details for antenna demod decode `Config` in a contact.
      - allOf:
        - $ref: '#/components/schemas/S3RecordingDetails'
        description: |-
          Details for an S3 recording `Config` in a contact.
      description: |-
        Details for certain `Config` object types in a contact.
    ConfigList:
      type: array
      items:
        $ref: '#/components/schemas/ConfigListItem'
    ConfigTypeData:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/AntennaDownlinkConfig'
        description: |-
          Information about how AWS Ground Station should configure an antenna for downlink during a contact.
      - allOf:
        - $ref: '#/components/schemas/TrackingConfig'
        description: |-
          Object that determines whether tracking should be used during a contact executed with this `Config` in the mission profile.
      - allOf:
        - $ref: '#/components/schemas/DataflowEndpointConfig'
        description: |-
          Information about the dataflow endpoint `Config`.
      - allOf:
        - $ref: '#/components/schemas/AntennaDownlinkDemodDecodeConfig'
        description: |-
          Information about how AWS Ground Station should conﬁgure an antenna for downlink demod decode during a contact.
      - allOf:
        - $ref: '#/components/schemas/AntennaUplinkConfig'
        description: |-
          Information about how AWS Ground Station should conﬁgure an antenna for uplink during a contact.
      - allOf:
        - $ref: '#/components/schemas/UplinkEchoConfig'
        description: |-
          Information about an uplink echo `Config`.

          Parameters from the `AntennaUplinkConfig`, corresponding to the specified `AntennaUplinkConfigArn`, are used when this `UplinkEchoConfig` is used in a contact.
      - allOf:
        - $ref: '#/components/schemas/S3RecordingConfig'
        description: |-
          Information about an S3 recording `Config`.
      description: |-
        Object containing the parameters of a `Config`.

        See the subtype definitions for what each type of `Config` contains.
    ContactList:
      type: array
      items:
        $ref: '#/components/schemas/ContactData'
    ContactStatus:
      type: string
      enum:
      - SCHEDULING
      - FAILED_TO_SCHEDULE
      - SCHEDULED
      - CANCELLED
      - AWS_CANCELLED
      - PREPASS
      - PASS
      - POSTPASS
      - COMPLETED
      - FAILED
      - AVAILABLE
      - CANCELLING
      - AWS_FAILED
    Criticality:
      type: string
      enum:
      - REQUIRED
      - PREFERRED
      - REMOVED
    CustomerEphemerisPriority:
      type: integer
      minimum: 1
      maximum: 99999
    DataflowEdge:
      type: array
      items:
        $ref: '#/components/schemas/ConfigArn'
    DataflowEdgeList:
      type: array
      items:
        $ref: '#/components/schemas/DataflowEdge'
    DataflowEndpointGroupArn:
      type: string
      pattern: ^arn:aws:groundstation:[-a-z0-9]{1,50}:[0-9]{12}:dataflow-endpoint-group/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 97
      maxLength: 146
    DataflowEndpointGroupDurationInSeconds:
      type: integer
      minimum: 120
      maximum: 480
    DataflowEndpointGroupList:
      type: array
      items:
        $ref: '#/components/schemas/DataflowEndpointListItem'
    DataflowList:
      type: array
      items:
        $ref: '#/components/schemas/DataflowDetail'
    DurationInSeconds:
      type: integer
      minimum: 0
      maximum: 21600
    EirpUnits:
      type: string
      enum:
      - dBW
    EndpointDetailsList:
      type: array
      items:
        $ref: '#/components/schemas/EndpointDetails'
    EndpointStatus:
      type: string
      enum:
      - created
      - creating
      - deleted
      - deleting
      - failed
    EphemeridesList:
      type: array
      items:
        $ref: '#/components/schemas/EphemerisItem'
    EphemerisData:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/TLEEphemeris'
      - allOf:
        - $ref: '#/components/schemas/OEMEphemeris'
      description: |-
        Ephemeris data.
    EphemerisInvalidReason:
      type: string
      enum:
      - METADATA_INVALID
      - TIME_RANGE_INVALID
      - TRAJECTORY_INVALID
      - KMS_KEY_INVALID
      - VALIDATION_ERROR
    EphemerisPriority:
      type: integer
      minimum: 0
      maximum: 99999
    EphemerisSource:
      type: string
      enum:
      - CUSTOMER_PROVIDED
      - SPACE_TRACK
    EphemerisStatus:
      type: string
      enum:
      - VALIDATING
      - INVALID
      - ERROR
      - ENABLED
      - DISABLED
      - EXPIRED
    EphemerisStatusList:
      type: array
      items:
        $ref: '#/components/schemas/EphemerisStatus'
    EphemerisTypeDescription:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/EphemerisDescription'
      - allOf:
        - $ref: '#/components/schemas/EphemerisDescription'
      description: ""
    FrequencyUnits:
      type: string
      enum:
      - GHz
      - MHz
      - kHz
    GroundStationIdList:
      type: array
      items:
        $ref: '#/components/schemas/GroundStationName'
    GroundStationList:
      type: array
      items:
        $ref: '#/components/schemas/GroundStationData'
    GroundStationName:
      type: string
      pattern: ^[ a-zA-Z0-9-._:=]{4,256}$
      minLength: 4
      maxLength: 500
    InstanceId:
      type: string
      pattern: ^[a-z0-9-]{10,64}$
      minLength: 10
      maxLength: 64
    InstanceType:
      type: string
      pattern: ^[a-z0-9.-]{1,64}$
      minLength: 1
      maxLength: 64
    IpAddressList:
      type: array
      items:
        $ref: '#/components/schemas/IpV4Address'
    IpV4Address:
      type: string
      pattern: ^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$
      minLength: 7
      maxLength: 16
    JsonString:
      type: string
      pattern: ^[{}\[\]:.,"0-9A-Za-z\-_\s]{2,8192}$
      minLength: 2
      maxLength: 8192
    KeyAliasArn:
      type: string
      pattern: ^arn:aws[a-zA-Z-]{0,16}:kms:[-a-z0-9]{1,50}:[0-9]{12}:((alias/[a-zA-Z0-9:/_-]{1,256}))$
      minLength: 1
      maxLength: 512
    KeyAliasName:
      type: string
      pattern: ^alias/[a-zA-Z0-9:/_-]+$
      minLength: 1
      maxLength: 256
    KeyArn:
      type: string
    KmsKey:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/KeyArn'
        description: |-
          KMS Key Arn.
      - allOf:
        - $ref: '#/components/schemas/KeyAliasArn'
        description: |-
          KMS Alias Arn.
      - allOf:
        - $ref: '#/components/schemas/KeyAliasName'
        description: |-
          KMS Alias Name.
      description: |-
        KMS key info.
    MissionProfileArn:
      type: string
      pattern: ^arn:aws:groundstation:[-a-z0-9]{1,50}:[0-9]{12}:mission-profile/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 89
      maxLength: 138
    MissionProfileList:
      type: array
      items:
        $ref: '#/components/schemas/MissionProfileListItem'
    Month:
      type: integer
      minimum: 1
      maximum: 12
    PaginationMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    PaginationToken:
      type: string
      pattern: ^[A-Za-z0-9-/+_.=]+$
      minLength: 3
      maxLength: 1000
    Polarization:
      type: string
      enum:
      - RIGHT_HAND
      - LEFT_HAND
      - NONE
    PositiveDurationInSeconds:
      type: integer
      minimum: 1
      maximum: 21600
    RoleArn:
      type: string
    S3BucketName:
      type: string
      pattern: ^[a-z0-9.-]{3,63}$
      minLength: 3
      maxLength: 63
    S3KeyPrefix:
      type: string
      pattern: ^([a-zA-Z0-9_\-=/]|\{satellite_id\}|\{config\-name}|\{s3\-config-id}|\{year\}|\{month\}|\{day\}){1,900}$
      minLength: 1
      maxLength: 900
    S3ObjectKey:
      type: string
      pattern: ^[a-zA-Z0-9!*'\)\(./_-]{1,1024}$
      minLength: 1
      maxLength: 1024
    S3VersionId:
      type: string
      pattern: ^[\s\S]{1,1024}$
      minLength: 1
      maxLength: 1024
    SafeName:
      type: string
      pattern: ^[ a-zA-Z0-9_:-]{1,256}$
      minLength: 1
      maxLength: 256
    SatelliteList:
      type: array
      items:
        $ref: '#/components/schemas/SatelliteListItem'
    SecurityGroupIdList:
      type: array
      items:
        type: string
    SignatureMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Boolean'
    StatusList:
      type: array
      items:
        $ref: '#/components/schemas/ContactStatus'
    SubnetList:
      type: array
      items:
        type: string
    TLEDataList:
      type: array
      items:
        $ref: '#/components/schemas/TLEData'
    TagKeys:
      type: array
      items:
        $ref: '#/components/schemas/UnboundedString'
    TagsMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    TleLineOne:
      type: string
      pattern: '^1 [ 0-9]{5}[A-Z] [ 0-9]{5}[ A-Z]{3} [ 0-9]{5}[.][ 0-9]{8} (?:(?:[
        0+-][.][ 0-9]{8})|(?: [ +-][.][ 0-9]{7})) [ +-][ 0-9]{5}[+-][ 0-9] [ +-][
        0-9]{5}[+-][ 0-9] [ 0-9] [ 0-9]{4}[ 0-9]$'
      minLength: 69
      maxLength: 69
    TleLineTwo:
      type: string
      pattern: ^2 [ 0-9]{5} [ 0-9]{3}[.][ 0-9]{4} [ 0-9]{3}[.][ 0-9]{4} [ 0-9]{7}
        [ 0-9]{3}[.][ 0-9]{4} [ 0-9]{3}[.][ 0-9]{4} [ 0-9]{2}[.][ 0-9]{13}[ 0-9]$
      minLength: 69
      maxLength: 69
    UnboundedString:
      type: string
      pattern: ^[\s\S]+$
      minLength: 1
    Uuid:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 36
      maxLength: 36
    VersionString:
      type: string
      pattern: ^(0|[1-9]\d*)(\.(0|[1-9]\d*))*$
      minLength: 1
      maxLength: 64
    VersionStringList:
      type: array
      items:
        $ref: '#/components/schemas/VersionString'
    Year:
      type: integer
      minimum: 2018
      maximum: 3000
    noradSatelliteID:
      type: integer
      default: 0
      minimum: 0
      maximum: 99999
    satelliteArn:
      type: string
      pattern: ^arn:aws:groundstation:([-a-z0-9]{1,50})?:[0-9]{12}:satellite/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 82
      maxLength: 132
