openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: imagebuilder
  x-aws-serviceName: imagebuilder
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2019-12-02'
  title: EC2 Image Builder
  description: |-
    EC2 Image Builder is a fully managed Amazon Web Services service that makes it easier to automate the creation, management, and deployment of customized, secure, and up-to-date "golden" server images that are pre-installed and pre-configured with software and settings to meet specific IT standards.
servers:
- description: The EC2 Image Builder regional endpoint
  url: https://imagebuilder.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccountId:
      type: string
      pattern: ^[0-9]{12}$
    AmiNameString:
      type: string
      pattern: ^[-_A-Za-z0-9{][-_A-Za-z0-9\s:{}\.]+[-_A-Za-z0-9}]$
      minLength: 1
      maxLength: 127
    Arn:
      type: string
    Boolean:
      type: boolean
      default: false
    ClientToken:
      type: string
      minLength: 1
      maxLength: 36
    ComponentBuildVersionArn:
      type: string
      pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws(?:-[a-z-]+)?):component/[a-z0-9-_]+/[0-9]+\.[0-9]+\.[0-9]+/[0-9]+$
    ComponentData:
      type: string
    ComponentParameterDescription:
      type: string
      pattern: ^[^\x00]+$
      minLength: 1
      maxLength: 1024
    ComponentParameterName:
      type: string
      pattern: ^[^\x00]+$
      minLength: 1
      maxLength: 256
    ComponentParameterType:
      type: string
      pattern: ^String|Integer|Boolean|StringList$
      minLength: 1
      maxLength: 20
    ComponentParameterValue:
      type: string
      pattern: ^[^\x00]*$
      minLength: 0
    ComponentVersionArn:
      type: string
      pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws(?:-[a-z-]+)?):component/[a-z0-9-_]+/[0-9]+\.[0-9]+\.[0-9]+$
    ComponentVersionArnOrBuildVersionArn:
      type: string
      pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws(?:-[a-z-]+)?):component/[a-z0-9-_]+/(?:(?:([0-9]+|x)\.([0-9]+|x)\.([0-9]+|x))|(?:[0-9]+\.[0-9]+\.[0-9]+/[0-9]+))$
    ContainerRecipeArn:
      type: string
      pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws):container-recipe/[a-z0-9-_]+/[0-9]+\.[0-9]+\.[0-9]+$
    DateTime:
      type: string
    DistributionConfigurationArn:
      type: string
      pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws):distribution-configuration/[a-z0-9-_]+$
    DistributionTimeoutMinutes:
      type: integer
      minimum: 30
      maximum: 720
    DockerFileTemplate:
      type: string
    EbsIopsInteger:
      type: integer
      minimum: 100
      maximum: 64000
    EbsVolumeSizeInteger:
      type: integer
      minimum: 1
      maximum: 16000
    EbsVolumeThroughput:
      type: integer
      minimum: 125
      maximum: 1000
    EmptyString:
      type: string
      minLength: 0
      maxLength: 0
    ErrorMessage:
      type: string
    FilterName:
      type: string
      pattern: ^[a-zA-Z]{1,1024}$
    FilterValue:
      type: string
      pattern: ^[0-9a-zA-Z./_ :,{}"-]{1,1024}$
    HttpPutResponseHopLimit:
      type: integer
      minimum: 1
      maximum: 64
    HttpTokens:
      type: string
      pattern: ^optional|required$
    ImageBuildMessage:
      type: string
      minLength: 0
      maxLength: 500
    ImageBuildVersionArn:
      type: string
      pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws(?:-[a-z-]+)?):image/[a-z0-9-_]+/[0-9]+\.[0-9]+\.[0-9]+/[0-9]+$
    ImageBuilderArn:
      type: string
      pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws(?:-[a-z-]+)?):(?:image-recipe|container-recipe|infrastructure-configuration|distribution-configuration|component|image|image-pipeline|lifecycle-policy|workflow\/(?:build|test|distribution))/[a-z0-9-_]+(?:/(?:(?:x|[0-9]+)\.(?:x|[0-9]+)\.(?:x|[0-9]+))(?:/[0-9]+)?)?$
    ImagePipelineArn:
      type: string
      pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws):image-pipeline/[a-z0-9-_]+$
    ImageRecipeArn:
      type: string
      pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws):image-recipe/[a-z0-9-_]+/[0-9]+\.[0-9]+\.[0-9]+$
    ImageTestsTimeoutMinutes:
      type: integer
      minimum: 60
      maximum: 1440
    ImageVersionArn:
      type: string
      pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws(?:-[a-z-]+)?):image/[a-z0-9-_]+/[0-9]+\.[0-9]+\.[0-9]+$
    ImageVersionArnOrBuildVersionArn:
      type: string
      pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws(?:-[a-z-]+)?):image/[a-z0-9-_]+/(?:(?:([0-9]+|x)\.([0-9]+|x)\.([0-9]+|x))|(?:[0-9]+\.[0-9]+\.[0-9]+/[0-9]+))$
    InfrastructureConfigurationArn:
      type: string
      pattern: ^arn:aws[^:]*:imagebuilder:[^:]+:(?:[0-9]{12}|aws):infrastructure-configuration/[a-z0-9-_]+$
    InlineComponentData:
      type: string
      pattern: ^[^\x00]+$
      minLength: 1
      maxLength: 16000
    InlineDockerFileTemplate:
      type: string
      pattern: ^[^\x00]+$
      minLength: 1
      maxLength: 16000
    InlineWorkflowData:
      type: string
      pattern: ^[^\x00]+$
      minLength: 1
      maxLength: 16000
    InstanceProfileNameType:
      type: string
      pattern: ^[\w+=,.@-]+$
      minLength: 1
      maxLength: 256
    InstanceType:
      type: string
    LaunchTemplateId:
      type: string
      pattern: ^lt-[a-z0-9-_]{17}$
    LicenseConfigurationArn:
      type: string
      pattern: ^arn:aws[^:]*:license-manager:[^:]+:[0-9]{12}:license-configuration:lic-[a-z0-9-_]{32}$
    LifecycleExecutionId:
      type: string
      pattern: ^lce-[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
    LifecyclePolicyArn:
      type: string
      pattern: ^arn:aws(?:-[a-z]+)*:imagebuilder:[a-z]{2,}(?:-[a-z]+)+-[0-9]+:(?:[0-9]{12}|aws):lifecycle-policy/[a-z0-9-_]+$
      minLength: 0
      maxLength: 1024
    LifecyclePolicyDetailExclusionRulesAmisLastLaunchedValue:
      type: integer
      minimum: 1
      maximum: 365
    LifecyclePolicyDetailFilterRetainAtLeast:
      type: integer
      minimum: 1
      maximum: 10
    LifecyclePolicyDetailFilterValue:
      type: integer
      minimum: 1
      maximum: 1000
    MarketplaceResourceLocation:
      type: string
      pattern: ^s3://[^/]+/.+[^/]$
      minLength: 0
      maxLength: 1024
    MaxParallelLaunches:
      type: integer
      minimum: 1
    NonEmptyString:
      type: string
      minLength: 1
      maxLength: 1024
    NullableBoolean:
      type: boolean
    OrganizationArn:
      type: string
      pattern: ^arn:aws[^:]*:organizations::[0-9]{12}:organization/o-[a-z0-9]{10,32}$
    OrganizationalUnitArn:
      type: string
      pattern: ^arn:aws[^:]*:organizations::[0-9]{12}:ou/o-[a-z0-9]{10,32}/ou-[0-9a-z]{4,32}-[0-9a-z]{8,32}$
    OsVersion:
      type: string
      minLength: 1
    PackageArchitecture:
      type: string
    PackageEpoch:
      type: integer
    PaginationToken:
      type: string
      minLength: 1
      maxLength: 65535
    ParallelGroup:
      type: string
      pattern: ^[A-Za-z0-9][A-Za-z0-9-_+#]{0,99}$
      minLength: 1
      maxLength: 100
    ProductCodeId:
      type: string
      pattern: ^[A-Za-z0-9]{1,25}$
    ResourceName:
      type: string
      pattern: ^[-_A-Za-z-0-9][-_A-Za-z0-9 ]{1,126}[-_A-Za-z-0-9]$
    ResourcePolicyDocument:
      type: string
      minLength: 1
      maxLength: 30000
    RestrictedInteger:
      type: integer
      minimum: 1
      maximum: 25
    RoleNameOrArn:
      type: string
      pattern: ^(?:arn:aws(?:-[a-z]+)*:iam::[0-9]{12}:role/)?[a-zA-Z_0-9+=,.@\-_/]+$
      minLength: 1
      maxLength: 2048
    SnsTopicArn:
      type: string
      pattern: ^arn:aws[^:]*:sns:[^:]+:[0-9]{12}:[a-zA-Z0-9-_]{1,256}$
    SourceLayerHash:
      type: string
    SsmParameterName:
      type: string
      pattern: ^[a-zA-Z0-9_.\-\/]+$
      minLength: 1
      maxLength: 1011
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TargetResourceCount:
      type: integer
      minimum: 1
      maximum: 10000
    Timezone:
      type: string
      pattern: ^[a-zA-Z0-9]{2,}(?:\/[a-zA-Z0-9-_+]+)*$
      minLength: 3
      maxLength: 100
    Uri:
      type: string
    UserDataOverride:
      type: string
      pattern: ^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
      minLength: 1
      maxLength: 21847
    VersionNumber:
      type: string
      pattern: ^[0-9]+\.[0-9]+\.[0-9]+$
    VulnerabilityId:
      type: string
    WorkflowBuildVersionArn:
      type: string
      pattern: ^arn:aws(?:-[a-z]+)*:imagebuilder:[a-z]{2,}(?:-[a-z]+)+-[0-9]+:(?:[0-9]{12}|aws(?:-[a-z-]+)?):workflow/(build|test|distribution)/[a-z0-9-_]+/[0-9]+\.[0-9]+\.[0-9]+/[0-9]+$
      minLength: 0
      maxLength: 1024
    WorkflowData:
      type: string
    WorkflowExecutionId:
      type: string
      pattern: ^wf-[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
    WorkflowExecutionMessage:
      type: string
      minLength: 0
      maxLength: 500
    WorkflowNameArn:
      type: string
      pattern: ^arn:aws(?:-[a-z]+)*:imagebuilder:[a-z]{2,}(?:-[a-z]+)+-[0-9]+:(?:[0-9]{12}|aws(?:-[a-z-]+)?):workflow/(build|test|distribution)/[a-z0-9-_]+/x\.x\.x$
    WorkflowParameterDescription:
      type: string
      pattern: ^[^\x00]+$
      minLength: 0
      maxLength: 1024
    WorkflowParameterName:
      type: string
      pattern: ^[^\x00]+$
      minLength: 1
      maxLength: 128
    WorkflowParameterType:
      type: string
      pattern: ^string|integer|boolean|stringList$
      minLength: 1
      maxLength: 20
    WorkflowParameterValue:
      type: string
      pattern: ^[^\x00]*$
      minLength: 0
    WorkflowStepAction:
      type: string
      pattern: ^[A-Za-z][A-Za-z0-9-_]{1,99}$
    WorkflowStepCount:
      type: integer
      default: 0
    WorkflowStepDescription:
      type: string
      minLength: 0
      maxLength: 500
    WorkflowStepExecutionId:
      type: string
      pattern: ^step-[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
    WorkflowStepInputs:
      type: string
    WorkflowStepMessage:
      type: string
      minLength: 0
      maxLength: 500
    WorkflowStepName:
      type: string
      pattern: ^[A-Za-z][A-Za-z0-9-_]{1,99}$
    WorkflowStepOutputs:
      type: string
    WorkflowStepTimeoutSecondsInteger:
      type: integer
      minimum: 0
      maximum: 43200
    WorkflowVersionArn:
      type: string
      pattern: ^arn:aws(?:-[a-z]+)*:imagebuilder:[a-z]{2,}(?:-[a-z]+)+-[0-9]+:(?:[0-9]{12}|aws(?:-[a-z-]+)?):workflow/(build|test|distribution)/[a-z0-9-_]+/[0-9]+\.[0-9]+\.[0-9]+$
    WorkflowVersionArnOrBuildVersionArn:
      type: string
      pattern: ^arn:aws(?:-[a-z]+)*:imagebuilder:[a-z]{2,}(?:-[a-z]+)+-[0-9]+:(?:[0-9]{12}|aws(?:-[a-z-]+)?):workflow/(build|test|distribution)/[a-z0-9-_]+/(?:(?:([0-9]+|x)\.([0-9]+|x)\.([0-9]+|x))|(?:[0-9]+\.[0-9]+\.[0-9]+/[0-9]+))$
    WorkflowWildcardVersionArn:
      type: string
      pattern: ^arn:aws(?:-[a-z]+)*:imagebuilder:[a-z]{2,}(?:-[a-z]+)+-[0-9]+:(?:[0-9]{12}|aws(?:-[a-z-]+)?):workflow/(build|test|distribution)/[a-z0-9-_]+/(?:[0-9]+|x)\.(?:[0-9]+|x)\.(?:[0-9]+|x)$
