openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: inspector2
  x-aws-serviceName: inspector2
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-06-08'
  title: Inspector2
  description: |-
    Amazon Inspector is a vulnerability discovery service that automates continuous scanning for security vulnerabilities within your Amazon EC2, Amazon ECR, and Amazon Web Services Lambda environments.
servers:
- description: The Inspector2 regional endpoint
  url: https://inspector2.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccountId:
      type: string
      pattern: ^\d{12}$
      minLength: 12
      maxLength: 12
    AccountSortBy:
      type: string
      enum:
      - CRITICAL
      - HIGH
      - ALL
    AggregationFindingType:
      type: string
      enum:
      - NETWORK_REACHABILITY
      - PACKAGE_VULNERABILITY
      - CODE_VULNERABILITY
    AggregationResourceType:
      type: string
      enum:
      - AWS_EC2_INSTANCE
      - AWS_ECR_CONTAINER_IMAGE
      - AWS_LAMBDA_FUNCTION
    AggregationType:
      type: string
      enum:
      - FINDING_TYPE
      - PACKAGE
      - TITLE
      - REPOSITORY
      - AMI
      - AWS_EC2_INSTANCE
      - AWS_ECR_CONTAINER
      - IMAGE_LAYER
      - ACCOUNT
      - AWS_LAMBDA_FUNCTION
      - LAMBDA_LAYER
    AmiId:
      type: string
      pattern: ^ami-([a-z0-9]{8}|[a-z0-9]{17}|\*)$
    AmiSortBy:
      type: string
      enum:
      - CRITICAL
      - HIGH
      - ALL
      - AFFECTED_INSTANCES
    Architecture:
      type: string
      enum:
      - X86_64
      - ARM64
    Arn:
      type: string
      minLength: 1
      maxLength: 1011
    AwsEcrContainerSortBy:
      type: string
      enum:
      - CRITICAL
      - HIGH
      - ALL
    BenchmarkProfile:
      type: string
      maxLength: 128
    BenchmarkVersion:
      type: string
      maxLength: 8
    CheckCount:
      type: integer
      default: 0
      minimum: 0
      maximum: 65536
    CisFindingArn:
      type: string
      pattern: ^arn:aws(-gov|-cn)?:inspector2:[-.a-z0-9]{0,20}:\d{12}:owner/\d{12}/cis-finding/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
    CisOwnerId:
      type: string
      pattern: ^\d{12}|o-[a-z0-9]{10,32}$
    CisScanArn:
      type: string
      pattern: ^arn:aws(-us-gov|-cn)?:inspector2:[-.a-z0-9]{0,20}:\d{12}:owner/(\d{12}|o-[a-z0-9]{10,32})/cis-scan/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
    CisScanConfigurationArn:
      type: string
      pattern: ^arn:aws(-us-gov|-cn)?:inspector2:[a-z]{2}(-gov)?-[a-z]+-[0-9]{1}:[0-9]{12}:owner/(o-[a-z0-9]+|[0-9]{12})/cis-configuration/[0-9a-fA-F-]+$
    CisScanName:
      type: string
      minLength: 1
      maxLength: 128
    CisScanResultsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    CisaAction:
      type: string
      minLength: 0
    ClientToken:
      type: string
      minLength: 1
      maxLength: 64
    CodeSnippetErrorCode:
      type: string
      enum:
      - INTERNAL_ERROR
      - ACCESS_DENIED
      - CODE_SNIPPET_NOT_FOUND
      - INVALID_INPUT
    Component:
      type: string
    ComponentArn:
      type: string
    ComponentType:
      type: string
    CoverageMapComparison:
      type: string
      enum:
      - EQUALS
    CoverageResourceType:
      type: string
      enum:
      - AWS_EC2_INSTANCE
      - AWS_ECR_CONTAINER_IMAGE
      - AWS_ECR_REPOSITORY
      - AWS_LAMBDA_FUNCTION
    CoverageStringComparison:
      type: string
      enum:
      - EQUALS
      - NOT_EQUALS
    CoverageStringInput:
      type: string
      minLength: 1
      maxLength: 1024
    Currency:
      type: string
      enum:
      - USD
    Cvss2ScoringVector:
      type: string
      minLength: 0
    Cvss3ScoringVector:
      type: string
      minLength: 0
    Cwe:
      type: string
      minLength: 0
    DelegatedAdminStatus:
      type: string
      enum:
      - ENABLED
      - DISABLE_IN_PROGRESS
    Ec2DeepInspectionStatus:
      type: string
      enum:
      - ACTIVATED
      - DEACTIVATED
      - PENDING
      - FAILED
    Ec2InstanceSortBy:
      type: string
      enum:
      - NETWORK_FINDINGS
      - CRITICAL
      - HIGH
      - ALL
    Ec2Platform:
      type: string
      enum:
      - WINDOWS
      - LINUX
      - UNKNOWN
      - MACOS
    Ec2ScanMode:
      type: string
      enum:
      - EC2_SSM_AGENT_BASED
      - EC2_HYBRID
    Ec2ScanModeStatus:
      type: string
      enum:
      - SUCCESS
      - PENDING
    EcrPullDateRescanDuration:
      type: string
      enum:
      - DAYS_14
      - DAYS_30
      - DAYS_60
      - DAYS_90
      - DAYS_180
    EcrRescanDuration:
      type: string
      enum:
      - LIFETIME
      - DAYS_30
      - DAYS_180
      - DAYS_14
      - DAYS_60
      - DAYS_90
    EcrRescanDurationStatus:
      type: string
      enum:
      - SUCCESS
      - PENDING
      - FAILED
    EcrScanFrequency:
      type: string
      enum:
      - MANUAL
      - SCAN_ON_PUSH
      - CONTINUOUS_SCAN
    ErrorCode:
      type: string
      enum:
      - ALREADY_ENABLED
      - ENABLE_IN_PROGRESS
      - DISABLE_IN_PROGRESS
      - SUSPEND_IN_PROGRESS
      - RESOURCE_NOT_FOUND
      - ACCESS_DENIED
      - INTERNAL_ERROR
      - SSM_UNAVAILABLE
      - SSM_THROTTLED
      - EVENTBRIDGE_UNAVAILABLE
      - EVENTBRIDGE_THROTTLED
      - RESOURCE_SCAN_NOT_DISABLED
      - DISASSOCIATE_ALL_MEMBERS
      - ACCOUNT_IS_ISOLATED
      - EC2_SSM_RESOURCE_DATA_SYNC_LIMIT_EXCEEDED
      - EC2_SSM_ASSOCIATION_VERSION_LIMIT_EXCEEDED
    ErrorMessage:
      type: string
    EvidenceDetail:
      type: string
      minLength: 0
    EvidenceRule:
      type: string
      minLength: 0
    EvidenceSeverity:
      type: string
      minLength: 0
    ExecutionRoleArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$
    ExploitAvailable:
      type: string
      enum:
      - 'YES'
      - 'NO'
    ExternalReportStatus:
      type: string
      enum:
      - SUCCEEDED
      - IN_PROGRESS
      - CANCELLED
      - FAILED
    FilePath:
      type: string
      minLength: 1
      maxLength: 1024
    FilterAction:
      type: string
      enum:
      - NONE
      - SUPPRESS
    FilterArn:
      type: string
      minLength: 1
      maxLength: 128
    FilterDescription:
      type: string
      minLength: 1
      maxLength: 512
    FilterName:
      type: string
      minLength: 1
      maxLength: 128
    FilterReason:
      type: string
      minLength: 1
      maxLength: 512
    FindingArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*)?:inspector2:[a-z]{2}(-gov)?-[a-z]+-\d{1}:\d{12}:finding/[a-f0-9]{32}$
      minLength: 1
      maxLength: 100
    FindingDescription:
      type: string
      minLength: 1
      maxLength: 1024
    FindingDetailsErrorCode:
      type: string
      enum:
      - INTERNAL_ERROR
      - ACCESS_DENIED
      - FINDING_DETAILS_NOT_FOUND
      - INVALID_INPUT
    FindingStatus:
      type: string
      enum:
      - ACTIVE
      - SUPPRESSED
      - CLOSED
    FindingTitle:
      type: string
      minLength: 1
      maxLength: 1024
    FindingType:
      type: string
      enum:
      - NETWORK_REACHABILITY
      - PACKAGE_VULNERABILITY
      - CODE_VULNERABILITY
    FindingTypeSortBy:
      type: string
      enum:
      - CRITICAL
      - HIGH
      - ALL
    FixAvailable:
      type: string
      enum:
      - 'YES'
      - 'NO'
      - PARTIAL
    FreeTrialInfoErrorCode:
      type: string
      enum:
      - ACCESS_DENIED
      - INTERNAL_ERROR
    FreeTrialStatus:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
    FreeTrialType:
      type: string
      enum:
      - EC2
      - ECR
      - LAMBDA
      - LAMBDA_CODE
    FunctionName:
      type: string
      pattern: ^[a-zA-Z0-9-_\.]+(:(\$LATEST|[a-zA-Z0-9-_]+))?$
    GetCisScanResultDetailsMaxResults:
      type: integer
      minimum: 1
      maximum: 1000
    GroupKey:
      type: string
      enum:
      - SCAN_STATUS_CODE
      - SCAN_STATUS_REASON
      - ACCOUNT_ID
      - RESOURCE_TYPE
      - ECR_REPOSITORY_NAME
    ImageHash:
      type: string
      pattern: ^sha256:[a-z0-9]{64}$
      minLength: 71
      maxLength: 71
    ImageLayerSortBy:
      type: string
      enum:
      - CRITICAL
      - HIGH
      - ALL
    IpV4Address:
      type: string
      pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
      minLength: 7
      maxLength: 15
    IpV6Address:
      type: string
      minLength: 1
      maxLength: 47
    KmsKeyArn:
      type: string
      pattern: ^arn:aws(-(us-gov|cn))?:kms:([a-z0-9][-.a-z0-9]{0,62})?:[0-9]{12}?:key/(([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})|(mrk-[0-9a-zA-Z]{32}))$
    LambdaFunctionSortBy:
      type: string
      enum:
      - CRITICAL
      - HIGH
      - ALL
    LambdaLayerArn:
      type: string
      pattern: ^arn:[a-zA-Z0-9-]+:lambda:[a-zA-Z0-9-]+:\d{12}:layer:[a-zA-Z0-9-_]+:[0-9]+$
    LambdaLayerSortBy:
      type: string
      enum:
      - CRITICAL
      - HIGH
      - ALL
    ListAccountPermissionsMaxResults:
      type: integer
      minimum: 1
      maximum: 1024
    ListCisScanConfigurationsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListCisScansMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListCoverageMaxResults:
      type: integer
      minimum: 1
      maximum: 200
    ListDelegatedAdminMaxResults:
      type: integer
      minimum: 1
      maximum: 5
    ListFilterMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListFindingAggregationsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListFindingsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListMembersMaxResults:
      type: integer
      minimum: 1
      maximum: 50
    ListUsageTotalsMaxResults:
      type: integer
      minimum: 1
      maximum: 500
    ListUsageTotalsNextToken:
      type: string
      minLength: 1
    MapComparison:
      type: string
      enum:
      - EQUALS
    MapKey:
      type: string
      minLength: 1
      maxLength: 128
    MapValue:
      type: string
      maxLength: 256
    MeteringAccountId:
      type: string
      pattern: '[0-9]{12}'
    NetworkProtocol:
      type: string
      enum:
      - TCP
      - UDP
    NextToken:
      type: string
      maxLength: 1000000
    NonEmptyString:
      type: string
      minLength: 1
    Operation:
      type: string
      enum:
      - ENABLE_SCANNING
      - DISABLE_SCANNING
      - ENABLE_REPOSITORY
      - DISABLE_REPOSITORY
    OwnerId:
      type: string
      pattern: (^\d{12}$)|(^o-[a-z0-9]{10,32}$)
      minLength: 12
      maxLength: 34
    PackageArchitecture:
      type: string
      minLength: 1
      maxLength: 64
    PackageEpoch:
      type: integer
      default: 0
    PackageManager:
      type: string
      enum:
      - BUNDLER
      - CARGO
      - COMPOSER
      - NPM
      - NUGET
      - PIPENV
      - POETRY
      - YARN
      - GOBINARY
      - GOMOD
      - JAR
      - OS
      - PIP
      - PYTHONPKG
      - NODEPKG
      - POM
      - GEMSPEC
      - DOTNET_CORE
    PackageName:
      type: string
      minLength: 1
      maxLength: 1024
    PackageRelease:
      type: string
      minLength: 1
      maxLength: 1024
    PackageSortBy:
      type: string
      enum:
      - CRITICAL
      - HIGH
      - ALL
    PackageType:
      type: string
      enum:
      - IMAGE
      - ZIP
    PackageVersion:
      type: string
      minLength: 1
      maxLength: 1024
    Path:
      type: string
      pattern: ^(?:/(?:\.[-\w]+|[-\w]+(?:\.[-\w]+)?))+/?$
      minLength: 1
      maxLength: 512
    Platform:
      type: string
      minLength: 1
      maxLength: 1024
    PlatformVersion:
      type: string
      maxLength: 8
    Port:
      type: integer
      minimum: 0
      maximum: 65535
    Product:
      type: string
      maxLength: 32
    Reason:
      type: string
      maxLength: 1024
    RelatedVulnerability:
      type: string
      minLength: 0
    RelationshipStatus:
      type: string
      enum:
      - CREATED
      - INVITED
      - DISABLED
      - ENABLED
      - REMOVED
      - RESIGNED
      - DELETED
      - EMAIL_VERIFICATION_IN_PROGRESS
      - EMAIL_VERIFICATION_FAILED
      - REGION_DISABLED
      - ACCOUNT_SUSPENDED
      - CANNOT_CREATE_DETECTOR_IN_ORG_MASTER
    ReportFormat:
      type: string
      enum:
      - CSV
      - JSON
    ReportId:
      type: string
      pattern: \b[a-f0-9]{8}\b-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-\b[a-f0-9]{12}\b
    ReportingErrorCode:
      type: string
      enum:
      - INTERNAL_ERROR
      - INVALID_PERMISSIONS
      - NO_FINDINGS_FOUND
      - BUCKET_NOT_FOUND
      - INCOMPATIBLE_BUCKET_REGION
      - MALFORMED_KMS_KEY
    RepositorySortBy:
      type: string
      enum:
      - CRITICAL
      - HIGH
      - ALL
      - AFFECTED_IMAGES
    ResourceId:
      type: string
      pattern: (^arn:.*:ecr:.*:\d{12}:repository\/(?:[a-z0-9]+(?:[._-][a-z0-9]+)*\/)*[a-z0-9]+(?:[._-][a-z0-9]+)*(\/sha256:[a-z0-9]{64})?$)|(^i-([a-z0-9]{8}|[a-z0-9]{17}|\\*)$|(^arn:(aws[a-zA-Z-]*)?:lambda:[a-z]{2}(-gov)?-[a-z]+-\d{1}:\d{12}:function:[a-zA-Z0-9-_\.]+(:(\$LATEST|[a-zA-Z0-9-_]+))?$))
      minLength: 10
      maxLength: 341
    ResourceMapComparison:
      type: string
      enum:
      - EQUALS
    ResourceScanType:
      type: string
      enum:
      - EC2
      - ECR
      - LAMBDA
      - LAMBDA_CODE
    ResourceStringComparison:
      type: string
      enum:
      - EQUALS
      - NOT_EQUALS
    ResourceStringInput:
      type: string
      minLength: 1
      maxLength: 1024
    ResourceType:
      type: string
      enum:
      - AWS_EC2_INSTANCE
      - AWS_ECR_CONTAINER_IMAGE
      - AWS_ECR_REPOSITORY
      - AWS_LAMBDA_FUNCTION
    RiskScore:
      type: integer
    RuleId:
      type: string
      minLength: 1
      maxLength: 500
    Runtime:
      type: string
      enum:
      - NODEJS
      - NODEJS_12_X
      - NODEJS_14_X
      - NODEJS_16_X
      - JAVA_8
      - JAVA_8_AL2
      - JAVA_11
      - PYTHON_3_7
      - PYTHON_3_8
      - PYTHON_3_9
      - UNSUPPORTED
      - NODEJS_18_X
      - GO_1_X
      - JAVA_17
      - PYTHON_3_10
      - PYTHON_3_11
      - DOTNETCORE_3_1
      - DOTNET_6
      - DOTNET_7
      - RUBY_2_7
      - RUBY_3_2
    SbomReportFormat:
      type: string
      enum:
      - CYCLONEDX_1_4
      - SPDX_2_3
    ScanMode:
      type: string
      enum:
      - EC2_SSM_AGENT_BASED
      - EC2_AGENTLESS
    ScanStatusCode:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
    ScanStatusReason:
      type: string
      enum:
      - PENDING_INITIAL_SCAN
      - ACCESS_DENIED
      - INTERNAL_ERROR
      - UNMANAGED_EC2_INSTANCE
      - UNSUPPORTED_OS
      - SCAN_ELIGIBILITY_EXPIRED
      - RESOURCE_TERMINATED
      - SUCCESSFUL
      - NO_RESOURCES_FOUND
      - IMAGE_SIZE_EXCEEDED
      - SCAN_FREQUENCY_MANUAL
      - SCAN_FREQUENCY_SCAN_ON_PUSH
      - EC2_INSTANCE_STOPPED
      - PENDING_DISABLE
      - NO_INVENTORY
      - STALE_INVENTORY
      - EXCLUDED_BY_TAG
      - UNSUPPORTED_RUNTIME
      - UNSUPPORTED_MEDIA_TYPE
      - UNSUPPORTED_CONFIG_FILE
      - DEEP_INSPECTION_PACKAGE_COLLECTION_LIMIT_EXCEEDED
      - DEEP_INSPECTION_DAILY_SSM_INVENTORY_LIMIT_EXCEEDED
      - DEEP_INSPECTION_COLLECTION_TIME_LIMIT_EXCEEDED
      - DEEP_INSPECTION_NO_INVENTORY
      - AGENTLESS_INSTANCE_STORAGE_LIMIT_EXCEEDED
      - AGENTLESS_INSTANCE_COLLECTION_TIME_LIMIT_EXCEEDED
    ScanType:
      type: string
      enum:
      - NETWORK
      - PACKAGE
      - CODE
    SecurityGroupId:
      type: string
      pattern: ^sg-([a-z0-9]{8}|[a-z0-9]{17}|\*)$
    Service:
      type: string
      enum:
      - EC2
      - ECR
      - LAMBDA
    Severity:
      type: string
      enum:
      - INFORMATIONAL
      - LOW
      - MEDIUM
      - HIGH
      - CRITICAL
      - UNTRIAGED
    SortField:
      type: string
      enum:
      - AWS_ACCOUNT_ID
      - FINDING_TYPE
      - SEVERITY
      - FIRST_OBSERVED_AT
      - LAST_OBSERVED_AT
      - FINDING_STATUS
      - RESOURCE_TYPE
      - ECR_IMAGE_PUSHED_AT
      - ECR_IMAGE_REPOSITORY_NAME
      - ECR_IMAGE_REGISTRY
      - NETWORK_PROTOCOL
      - COMPONENT_TYPE
      - VULNERABILITY_ID
      - VULNERABILITY_SOURCE
      - INSPECTOR_SCORE
      - VENDOR_SEVERITY
      - EPSS_SCORE
    SortOrder:
      type: string
      enum:
      - ASC
      - DESC
    SourceLayerHash:
      type: string
      pattern: ^sha256:[a-z0-9]{64}$
      minLength: 71
      maxLength: 71
    Status:
      type: string
      enum:
      - ENABLING
      - ENABLED
      - DISABLING
      - DISABLED
      - SUSPENDING
      - SUSPENDED
    StringComparison:
      type: string
      enum:
      - EQUALS
      - PREFIX
      - NOT_EQUALS
    StringInput:
      type: string
      minLength: 1
      maxLength: 1024
    SubnetId:
      type: string
      pattern: ^subnet-([a-z0-9]{8}|[a-z0-9]{17}|\*)$
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    Target:
      type: string
      minLength: 0
      maxLength: 50
    TargetAccount:
      type: string
      pattern: ^\d{12}|ALL_ACCOUNTS|SELF$
    TargetResourceTagsKey:
      type: string
      pattern: ^[\p{L}\p{Z}\p{N}_.:/=\-@]*$
      minLength: 1
      maxLength: 128
    TargetResourceTagsValue:
      type: string
      minLength: 1
      maxLength: 256
    TimeOfDay:
      type: string
      pattern: ^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$
    Timezone:
      type: string
      minLength: 1
      maxLength: 50
    TitleSortBy:
      type: string
      enum:
      - CRITICAL
      - HIGH
      - ALL
    Tool:
      type: string
      minLength: 0
    Ttp:
      type: string
      minLength: 0
      maxLength: 30
    UUID:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
    UsageAccountId:
      type: string
      pattern: '[0-9]{12}'
    UsageType:
      type: string
      enum:
      - EC2_INSTANCE_HOURS
      - ECR_INITIAL_SCAN
      - ECR_RESCAN
      - LAMBDA_FUNCTION_HOURS
      - LAMBDA_FUNCTION_CODE_HOURS
    ValidationExceptionReason:
      type: string
      enum:
      - CANNOT_PARSE
      - FIELD_VALIDATION_FAILED
      - OTHER
    Vendor:
      type: string
      maxLength: 16
    VendorSeverity:
      type: string
      minLength: 1
      maxLength: 64
    Version:
      type: string
      pattern: ^\$LATEST|[0-9]+$
    VpcId:
      type: string
      pattern: ^vpc-([a-z0-9]{8}|[a-z0-9]{17}|\*)$
    VulnId:
      type: string
      pattern: ^CVE-[12][0-9]{3}-[0-9]{1,10}$
    VulnerabilityDescription:
      type: string
    VulnerabilityId:
      type: string
      minLength: 1
      maxLength: 128
    VulnerabilityReferenceUrl:
      type: string
      minLength: 0
    VulnerabilitySource:
      type: string
      enum:
      - NVD
    VulnerabilitySourceUrl:
      type: string
      minLength: 0
    VulnerablePackageRemediation:
      type: string
      minLength: 1
      maxLength: 1024
