openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: iotanalytics
  x-aws-serviceName: iotanalytics
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-11-27'
  title: AWS IoT Analytics
  description: |-
    IoT Analytics allows you to collect large amounts of device data, process messages, and store them. You can then query the data and run sophisticated analytics on it. IoT Analytics enables advanced data exploration through integration with Jupyter Notebooks and data visualization through integration with Amazon QuickSight.

    Traditional analytics and business intelligence tools are designed to process structured data. IoT data often comes from devices that record noisy processes (such as temperature, motion, or sound). As a result the data from these devices can have significant gaps, corrupted messages, and false readings that must be cleaned up before analysis can occur. Also, IoT data is often only meaningful in the context of other data from external sources.

    IoT Analytics automates the steps required to analyze data from IoT devices. IoT Analytics filters, transforms, and enriches IoT data before storing it in a time-series data store for analysis. You can set up the service to collect only the data you need from your devices, apply mathematical transforms to process the data, and enrich the data with device-specific metadata such as device type and location before storing it. Then, you can analyze your data by running queries using the built-in SQL query engine, or perform more complex analytics and machine learning inference. IoT Analytics includes pre-built models for common IoT use cases so you can answer questions like which devices are about to fail or which customers are at risk of abandoning their wearable devices.
servers:
- description: The AWS IoT Analytics regional endpoint
  url: https://iotanalytics.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ActivityBatchSize:
      type: integer
      minimum: 1
      maximum: 1000
    ActivityName:
      type: string
      minLength: 1
      maxLength: 128
    AttributeName:
      type: string
      minLength: 1
      maxLength: 256
    AttributeNameMapping:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/AttributeName'
    AttributeNames:
      type: array
      items:
        $ref: '#/components/schemas/AttributeName'
    BatchPutMessageErrorEntries:
      type: array
      items:
        $ref: '#/components/schemas/BatchPutMessageErrorEntry'
    BucketKeyExpression:
      type: string
      pattern: ^[a-zA-Z0-9!_.*'()/{}:-]*$
      minLength: 1
      maxLength: 255
    BucketName:
      type: string
      pattern: ^[a-zA-Z0-9.\-_]*$
      minLength: 3
      maxLength: 255
    ChannelArn:
      type: string
    ChannelName:
      type: string
      pattern: ^(^(?!_{2}))(^[a-zA-Z0-9_]+$)$
      minLength: 1
      maxLength: 128
    ChannelStatus:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - DELETING
    ChannelSummaries:
      type: array
      items:
        $ref: '#/components/schemas/ChannelSummary'
    ColumnDataType:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 1
      maxLength: 131072
    ColumnName:
      type: string
      pattern: ^[A-Za-z_]([A-Za-z0-9]*|[A-Za-z0-9][A-Za-z0-9_]*)$
      minLength: 1
      maxLength: 255
    Columns:
      type: array
      items:
        $ref: '#/components/schemas/Column'
    ComputeType:
      type: string
      enum:
      - ACU_1
      - ACU_2
    DatasetActionName:
      type: string
      pattern: ^[a-zA-Z0-9_]+$
      minLength: 1
      maxLength: 128
    DatasetActionSummaries:
      type: array
      items:
        $ref: '#/components/schemas/DatasetActionSummary'
    DatasetActionType:
      type: string
      enum:
      - QUERY
      - CONTAINER
    DatasetActions:
      type: array
      items:
        $ref: '#/components/schemas/DatasetAction'
    DatasetArn:
      type: string
    DatasetContentDeliveryRules:
      type: array
      items:
        $ref: '#/components/schemas/DatasetContentDeliveryRule'
    DatasetContentState:
      type: string
      enum:
      - CREATING
      - SUCCEEDED
      - FAILED
    DatasetContentSummaries:
      type: array
      items:
        $ref: '#/components/schemas/DatasetContentSummary'
    DatasetContentVersion:
      type: string
      minLength: 7
      maxLength: 36
    DatasetEntries:
      type: array
      items:
        $ref: '#/components/schemas/DatasetEntry'
    DatasetName:
      type: string
      pattern: ^(^(?!_{2}))(^[a-zA-Z0-9_]+$)$
      minLength: 1
      maxLength: 128
    DatasetStatus:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - DELETING
    DatasetSummaries:
      type: array
      items:
        $ref: '#/components/schemas/DatasetSummary'
    DatasetTriggers:
      type: array
      items:
        $ref: '#/components/schemas/DatasetTrigger'
    DatastoreArn:
      type: string
    DatastoreName:
      type: string
      pattern: ^(^(?!_{2}))(^[a-zA-Z0-9_]+$)$
      minLength: 1
      maxLength: 128
    DatastoreStatus:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - DELETING
    DatastoreStorage:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/ServiceManagedDatastoreS3Storage'
        description: |-
          Used to store data in an Amazon S3 bucket managed by IoT Analytics. You can't change the choice of Amazon S3 storage after your data store is created.
      - allOf:
        - $ref: '#/components/schemas/CustomerManagedDatastoreS3Storage'
        description: |-
          S3-customer-managed; When you choose customer-managed storage, the `retentionPeriod` parameter is ignored. You can't change the choice of Amazon S3 storage after your data store is created.
      - allOf:
        - $ref: '#/components/schemas/DatastoreIotSiteWiseMultiLayerStorage'
        description: |-
          Used to store data used by IoT SiteWise in an Amazon S3 bucket that you manage. You can't change the choice of Amazon S3 storage after your data store is created.
      description: |-
        Where data in a data store is stored.. You can choose `serviceManagedS3` storage, `customerManagedS3` storage, or `iotSiteWiseMultiLayerStorage` storage. The default is `serviceManagedS3`. You can't change the choice of Amazon S3 storage after your data store is created.
    DatastoreSummaries:
      type: array
      items:
        $ref: '#/components/schemas/DatastoreSummary'
    DoubleValue:
      type: number
      format: double
      default: 0
    EndTime:
      type: string
      format: date-time
    EntryName:
      type: string
    ErrorCode:
      type: string
    ErrorMessage:
      type: string
    FileFormatType:
      type: string
      enum:
      - JSON
      - PARQUET
    FilterExpression:
      type: string
      minLength: 1
      maxLength: 256
    GlueDatabaseName:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 1
      maxLength: 150
    GlueTableName:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 1
      maxLength: 150
    Image:
      type: string
      minLength: 0
      maxLength: 255
    IncludeStatisticsFlag:
      type: boolean
      default: false
    IotEventsInputName:
      type: string
      pattern: ^[a-zA-Z][a-zA-Z0-9_]*$
      minLength: 1
      maxLength: 128
    LambdaName:
      type: string
      pattern: ^[a-zA-Z0-9_-]+$
      minLength: 1
      maxLength: 64
    LateDataRuleName:
      type: string
      pattern: ^[a-zA-Z0-9_]+$
      minLength: 1
      maxLength: 128
    LateDataRules:
      type: array
      items:
        $ref: '#/components/schemas/LateDataRule'
    LogResult:
      type: string
    LoggingEnabled:
      type: boolean
      default: false
    LoggingLevel:
      type: string
      enum:
      - ERROR
    MathExpression:
      type: string
      minLength: 1
      maxLength: 256
    MaxMessages:
      type: integer
      minimum: 1
      maximum: 10
    MaxResults:
      type: integer
      minimum: 1
      maximum: 250
    MaxVersions:
      type: integer
      minimum: 1
      maximum: 1000
    MessageId:
      type: string
      pattern: ^\p{ASCII}*$
      minLength: 1
      maxLength: 128
    MessagePayload:
      type: string
      format: byte
    MessagePayloads:
      type: array
      items:
        $ref: '#/components/schemas/MessagePayload'
    Messages:
      type: array
      items:
        $ref: '#/components/schemas/Message'
    NextToken:
      type: string
    OffsetSeconds:
      type: integer
    OutputFileName:
      type: string
      pattern: ^[\w\.-]{1,255}$
    PartitionAttributeName:
      type: string
      pattern: ^[a-zA-Z0-9_]+$
      minLength: 1
      maxLength: 128
    Partitions:
      type: array
      items:
        $ref: '#/components/schemas/DatastorePartition'
    PipelineActivities:
      type: array
      items:
        $ref: '#/components/schemas/PipelineActivity'
    PipelineArn:
      type: string
    PipelineName:
      type: string
      pattern: ^(^(?!_{2}))(^[a-zA-Z0-9_]+$)$
      minLength: 1
      maxLength: 128
    PipelineSummaries:
      type: array
      items:
        $ref: '#/components/schemas/PipelineSummary'
    PresignedURI:
      type: string
    QueryFilters:
      type: array
      items:
        $ref: '#/components/schemas/QueryFilter'
    Reason:
      type: string
    ReprocessingId:
      type: string
    ReprocessingStatus:
      type: string
      enum:
      - RUNNING
      - SUCCEEDED
      - CANCELLED
      - FAILED
    ReprocessingSummaries:
      type: array
      items:
        $ref: '#/components/schemas/ReprocessingSummary'
    ResourceArn:
      type: string
      minLength: 20
      maxLength: 2048
    ResourceArn2:
      type: string
    RetentionPeriodInDays:
      type: integer
      minimum: 1
    RoleArn:
      type: string
      minLength: 20
      maxLength: 2048
    S3KeyPrefix:
      type: string
      pattern: ^[a-zA-Z0-9!_.*'()/{}:-]*/$
      minLength: 1
      maxLength: 255
    S3PathChannelMessage:
      type: string
      pattern: ^[a-zA-Z0-9/_!'(){}\*\s\.\-\=\:]+$
      minLength: 1
      maxLength: 1024
    S3PathChannelMessages:
      type: array
      items:
        $ref: '#/components/schemas/S3PathChannelMessage'
    ScheduleExpression:
      type: string
    SessionTimeoutInMinutes:
      type: integer
      minimum: 1
      maximum: 60
    SizeInBytes:
      type: number
      format: double
    SqlQuery:
      type: string
    StartTime:
      type: string
      format: date-time
    StringValue:
      type: string
      minLength: 0
      maxLength: 1024
    TagKey:
      type: string
      minLength: 1
      maxLength: 256
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagList:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    TagValue:
      type: string
      minLength: 1
      maxLength: 256
    TimeExpression:
      type: string
    Timestamp:
      type: string
      format: date-time
    TimestampFormat:
      type: string
      pattern: ^[a-zA-Z0-9\s\[\]_,.'/:-]*$
      minLength: 1
      maxLength: 50
    UnlimitedRetentionPeriod:
      type: boolean
      default: false
    UnlimitedVersioning:
      type: boolean
      default: false
    VariableName:
      type: string
      minLength: 1
      maxLength: 256
    Variables:
      type: array
      items:
        $ref: '#/components/schemas/Variable'
    VolumeSizeInGB:
      type: integer
      minimum: 1
      maximum: 50
    resourceId:
      type: string
