openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: iotanalytics
  x-aws-serviceName: iotanalytics
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-11-27'
  title: AWS IoT Analytics
  description: |-
    IoT Analytics allows you to collect large amounts of device data, process messages, and store them. You can then query the data and run sophisticated analytics on it. IoT Analytics enables advanced data exploration through integration with Jupyter Notebooks and data visualization through integration with Amazon QuickSight.

    Traditional analytics and business intelligence tools are designed to process structured data. IoT data often comes from devices that record noisy processes (such as temperature, motion, or sound). As a result the data from these devices can have significant gaps, corrupted messages, and false readings that must be cleaned up before analysis can occur. Also, IoT data is often only meaningful in the context of other data from external sources.

    IoT Analytics automates the steps required to analyze data from IoT devices. IoT Analytics filters, transforms, and enriches IoT data before storing it in a time-series data store for analysis. You can set up the service to collect only the data you need from your devices, apply mathematical transforms to process the data, and enrich the data with device-specific metadata such as device type and location before storing it. Then, you can analyze your data by running queries using the built-in SQL query engine, or perform more complex analytics and machine learning inference. IoT Analytics includes pre-built models for common IoT use cases so you can answer questions like which devices are about to fail or which customers are at risk of abandoning their wearable devices.
servers:
- description: The AWS IoT Analytics regional endpoint
  url: https://iotanalytics.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ActivityBatchSize:
      type: integer
      minimum: 1
      maximum: 1000
    ActivityName:
      type: string
      minLength: 1
      maxLength: 128
    AttributeName:
      type: string
      minLength: 1
      maxLength: 256
    BucketKeyExpression:
      type: string
      pattern: ^[a-zA-Z0-9!_.*'()/{}:-]*$
      minLength: 1
      maxLength: 255
    BucketName:
      type: string
      pattern: ^[a-zA-Z0-9.\-_]*$
      minLength: 3
      maxLength: 255
    ChannelArn:
      type: string
    ChannelName:
      type: string
      pattern: ^(^(?!_{2}))(^[a-zA-Z0-9_]+$)$
      minLength: 1
      maxLength: 128
    ColumnDataType:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 1
      maxLength: 131072
    ColumnName:
      type: string
      pattern: ^[A-Za-z_]([A-Za-z0-9]*|[A-Za-z0-9][A-Za-z0-9_]*)$
      minLength: 1
      maxLength: 255
    DatasetActionName:
      type: string
      pattern: ^[a-zA-Z0-9_]+$
      minLength: 1
      maxLength: 128
    DatasetArn:
      type: string
    DatasetContentVersion:
      type: string
      minLength: 7
      maxLength: 36
    DatasetName:
      type: string
      pattern: ^(^(?!_{2}))(^[a-zA-Z0-9_]+$)$
      minLength: 1
      maxLength: 128
    DatastoreArn:
      type: string
    DatastoreName:
      type: string
      pattern: ^(^(?!_{2}))(^[a-zA-Z0-9_]+$)$
      minLength: 1
      maxLength: 128
    EntryName:
      type: string
    ErrorCode:
      type: string
    ErrorMessage:
      type: string
    FilterExpression:
      type: string
      minLength: 1
      maxLength: 256
    GlueDatabaseName:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 1
      maxLength: 150
    GlueTableName:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 1
      maxLength: 150
    Image:
      type: string
      minLength: 0
      maxLength: 255
    IncludeStatisticsFlag:
      type: boolean
      default: false
    IotEventsInputName:
      type: string
      pattern: ^[a-zA-Z][a-zA-Z0-9_]*$
      minLength: 1
      maxLength: 128
    LambdaName:
      type: string
      pattern: ^[a-zA-Z0-9_-]+$
      minLength: 1
      maxLength: 64
    LateDataRuleName:
      type: string
      pattern: ^[a-zA-Z0-9_]+$
      minLength: 1
      maxLength: 128
    LogResult:
      type: string
    LoggingEnabled:
      type: boolean
      default: false
    MathExpression:
      type: string
      minLength: 1
      maxLength: 256
    MaxMessages:
      type: integer
      minimum: 1
      maximum: 10
    MaxResults:
      type: integer
      minimum: 1
      maximum: 250
    MaxVersions:
      type: integer
      minimum: 1
      maximum: 1000
    MessageId:
      type: string
      pattern: ^\p{ASCII}*$
      minLength: 1
      maxLength: 128
    NextToken:
      type: string
    OffsetSeconds:
      type: integer
    OutputFileName:
      type: string
      pattern: ^[\w\.-]{1,255}$
    PartitionAttributeName:
      type: string
      pattern: ^[a-zA-Z0-9_]+$
      minLength: 1
      maxLength: 128
    PipelineArn:
      type: string
    PipelineName:
      type: string
      pattern: ^(^(?!_{2}))(^[a-zA-Z0-9_]+$)$
      minLength: 1
      maxLength: 128
    PresignedURI:
      type: string
    Reason:
      type: string
    ReprocessingId:
      type: string
    ResourceArn:
      type: string
      minLength: 20
      maxLength: 2048
    ResourceArn2:
      type: string
    RetentionPeriodInDays:
      type: integer
      minimum: 1
    RoleArn:
      type: string
      minLength: 20
      maxLength: 2048
    S3KeyPrefix:
      type: string
      pattern: ^[a-zA-Z0-9!_.*'()/{}:-]*/$
      minLength: 1
      maxLength: 255
    S3PathChannelMessage:
      type: string
      pattern: ^[a-zA-Z0-9/_!'(){}\*\s\.\-\=\:]+$
      minLength: 1
      maxLength: 1024
    ScheduleExpression:
      type: string
    SessionTimeoutInMinutes:
      type: integer
      minimum: 1
      maximum: 60
    SqlQuery:
      type: string
    StringValue:
      type: string
      minLength: 0
      maxLength: 1024
    TagKey:
      type: string
      minLength: 1
      maxLength: 256
    TagValue:
      type: string
      minLength: 1
      maxLength: 256
    TimeExpression:
      type: string
    TimestampFormat:
      type: string
      pattern: ^[a-zA-Z0-9\s\[\]_,.'/:-]*$
      minLength: 1
      maxLength: 50
    UnlimitedRetentionPeriod:
      type: boolean
      default: false
    UnlimitedVersioning:
      type: boolean
      default: false
    VariableName:
      type: string
      minLength: 1
      maxLength: 256
    VolumeSizeInGB:
      type: integer
      minimum: 1
      maximum: 50
    resourceId:
      type: string
