openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: iotdeviceadvisor
  x-aws-serviceName: iotdeviceadvisor
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-09-18'
  title: AWS IoT Core Device Advisor
  description: |-
    Amazon Web Services IoT Core Device Advisor is a cloud-based, fully managed test capability for validating IoT devices during device software development. Device Advisor provides pre-built tests that you can use to validate IoT devices for reliable and secure connectivity with Amazon Web Services IoT Core before deploying devices to production. By using Device Advisor, you can confirm that your devices can connect to Amazon Web Services IoT Core, follow security best practices and, if applicable, receive software updates from IoT Device Management. You can also download signed qualification reports to submit to the Amazon Web Services Partner Network to get your device qualified for the Amazon Web Services Partner Device Catalog without the need to send your device in and wait for it to be tested.
servers:
- description: The AWS IoT Core Device Advisor regional endpoint
  url: https://api.iotdeviceadvisor.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AmazonResourceName:
      type: string
      minLength: 20
      maxLength: 2048
    AuthenticationMethod:
      type: string
      enum:
      - X509ClientCertificate
      - SignatureVersion4
    ClientToken:
      type: string
      pattern: ^[\u0021-\u007E]+$
      minLength: 1
      maxLength: 64
    DeviceUnderTestList:
      type: array
      items:
        $ref: '#/components/schemas/DeviceUnderTest'
    Endpoint:
      type: string
      minLength: 45
      maxLength: 75
    ErrorReason:
      type: string
    Failure:
      type: string
    GroupName:
      type: string
    GroupResultList:
      type: array
      items:
        $ref: '#/components/schemas/GroupResult'
      description: <p>Group Result list.</p>
    IntendedForQualificationBoolean:
      type: boolean
    IsLongDurationTestBoolean:
      type: boolean
    LogUrl:
      type: string
    MaxResults:
      type: integer
      minimum: 1
      maximum: 50
    Message:
      type: string
      minLength: 1
      maxLength: 2048
    ParallelRun:
      type: boolean
    Protocol:
      type: string
      enum:
      - MqttV3_1_1
      - MqttV5
      - MqttV3_1_1_OverWebSocket
      - MqttV5_OverWebSocket
    QualificationReportDownloadUrl:
      type: string
    RootGroup:
      type: string
      minLength: 0
      maxLength: 2048
    SelectedTestList:
      type: array
      items:
        $ref: '#/components/schemas/UUID'
    Status:
      type: string
      enum:
      - PASS
      - FAIL
      - CANCELED
      - PENDING
      - RUNNING
      - STOPPING
      - STOPPED
      - PASS_WITH_WARNINGS
      - ERROR
    String128:
      type: string
      minLength: 1
      maxLength: 128
    String256:
      type: string
      minLength: 1
      maxLength: 256
    SuiteDefinitionInformationList:
      type: array
      items:
        $ref: '#/components/schemas/SuiteDefinitionInformation'
    SuiteDefinitionName:
      type: string
      minLength: 1
      maxLength: 256
    SuiteDefinitionVersion:
      type: string
      minLength: 2
      maxLength: 255
    SuiteRunResultCount:
      type: integer
      minimum: 0
      maximum: 500
    SuiteRunStatus:
      type: string
      enum:
      - PASS
      - FAIL
      - CANCELED
      - PENDING
      - RUNNING
      - STOPPING
      - STOPPED
      - PASS_WITH_WARNINGS
      - ERROR
    SuiteRunsList:
      type: array
      items:
        $ref: '#/components/schemas/SuiteRunInformation'
    SystemMessage:
      type: string
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/String128'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String256'
    TestCaseDefinitionName:
      type: string
    TestCaseRuns:
      type: array
      items:
        $ref: '#/components/schemas/TestCaseRun'
      description: <p>Tests under each group result.</p>
    TestCaseScenarioId:
      type: string
    TestCaseScenarioStatus:
      type: string
      enum:
      - PASS
      - FAIL
      - CANCELED
      - PENDING
      - RUNNING
      - STOPPING
      - STOPPED
      - PASS_WITH_WARNINGS
      - ERROR
    TestCaseScenarioType:
      type: string
      enum:
      - Advanced
      - Basic
    TestCaseScenariosList:
      type: array
      items:
        $ref: '#/components/schemas/TestCaseScenario'
    Timestamp:
      type: string
      format: date-time
    Token:
      type: string
      minLength: 0
      maxLength: 2000
    UUID:
      type: string
      minLength: 12
      maxLength: 36
    Warnings:
      type: string
