openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: iot_data_plane
  x-aws-serviceName: iotdataplane
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2015-05-28'
  title: AWS IoT Data Plane
  description: |-
    IoT data

    IoT data enables secure, bi-directional communication between Internet-connected things (such as sensors, actuators, embedded devices, or smart appliances) and the Amazon Web Services cloud. It implements a broker for applications and things to publish messages over HTTP (Publish) and retrieve, update, and delete shadows. A shadow is a persistent representation of your things and their state in the Amazon Web Services cloud.

    Find the endpoint address for actions in IoT data by running this CLI command:

    `aws iot describe-endpoint --endpoint-type iot:Data-ATS`

    The service name used by [Amazon Web ServicesSignature Version 4](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html) to sign requests is: _iotdevicegateway_.
servers:
- description: The AWS IoT Data Plane regional endpoint
  url: https://data-ats.iot.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ContentType:
      type: string
    CorrelationData:
      type: string
    JsonDocument:
      type: string
      format: byte
    MaxResults:
      type: integer
      minimum: 1
      maximum: 200
    MessageExpiry:
      type: integer
      format: int64
      default: 0
    NamedShadowList:
      type: array
      items:
        $ref: '#/components/schemas/ShadowName'
    NextToken:
      type: string
    PageSize:
      type: integer
      minimum: 1
      maximum: 100
    Payload:
      type: string
      format: byte
    PayloadFormatIndicator:
      type: string
      enum:
      - UNSPECIFIED_BYTES
      - UTF8_DATA
    PayloadSize:
      type: integer
      format: int64
      default: 0
    Qos:
      type: integer
      default: 0
      minimum: 0
      maximum: 1
    ResponseTopic:
      type: string
    Retain:
      type: boolean
      default: false
    RetainedMessageList:
      type: array
      items:
        $ref: '#/components/schemas/RetainedMessageSummary'
    ShadowName:
      type: string
      pattern: ^[$a-zA-Z0-9:_-]+$
      minLength: 1
      maxLength: 64
    SynthesizedJsonUserProperties:
      type: string
    ThingName:
      type: string
      pattern: ^[a-zA-Z0-9:_-]+$
      minLength: 1
      maxLength: 128
    Timestamp:
      type: integer
      format: int64
      default: 0
    Topic:
      type: string
    UserPropertiesBlob:
      type: string
      format: byte
    errorMessage:
      type: string
