openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: iot_events_data
  x-aws-serviceName: ioteventsdata
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-10-23'
  title: AWS IoT Events Data
  description: |-
    IoT Events monitors your equipment or device fleets for failures or changes in operation, and triggers actions when such events occur. You can use IoT Events Data API commands to send inputs to detectors, list detectors, and view or update a detector's status.

    For more information, see [What is IoT Events?](https://docs.aws.amazon.com/iotevents/latest/developerguide/what-is-iotevents.html) in the _IoT Events Developer Guide_.
servers:
- description: The AWS IoT Events Data regional endpoint
  url: https://data.iotevents.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AlarmModelName:
      type: string
      pattern: ^[a-zA-Z0-9_-]+$
      minLength: 1
      maxLength: 128
    AlarmModelVersion:
      type: string
      minLength: 1
      maxLength: 128
    DetectorModelName:
      type: string
      pattern: ^[a-zA-Z0-9_-]+$
      minLength: 1
      maxLength: 128
    DetectorModelVersion:
      type: string
      minLength: 1
      maxLength: 128
    EphemeralInputName:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9_.-]*$
      minLength: 1
      maxLength: 128
    ErrorMessage:
      type: string
    InputPropertyValue:
      type: string
    KeyValue:
      type: string
      pattern: ^[a-zA-Z0-9\-_:]+$
      minLength: 1
      maxLength: 128
    MaxResults:
      type: integer
      minimum: 1
      maximum: 250
    MessageId:
      type: string
      pattern: ^[a-zA-Z0-9_-]+$
      minLength: 1
      maxLength: 64
    NextToken:
      type: string
    Note:
      type: string
      minLength: 0
      maxLength: 256
    RequestId:
      type: string
      pattern: ^[a-zA-Z0-9_-]+$
      minLength: 1
      maxLength: 64
    Seconds:
      type: integer
    Severity:
      type: integer
      minimum: 0
      maximum: 2147483647
    SnoozeDuration:
      type: integer
    StateName:
      type: string
      minLength: 1
      maxLength: 128
    ThresholdValue:
      type: string
    TimerName:
      type: string
      minLength: 1
      maxLength: 128
    VariableName:
      type: string
      pattern: ^[a-zA-Z][a-zA-Z0-9_]*$
      minLength: 1
      maxLength: 128
    VariableValue:
      type: string
      minLength: 1
      maxLength: 1024
