openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: iot_events
  x-aws-serviceName: iotevents
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-07-27'
  title: AWS IoT Events
  description: |-
    AWS IoT Events monitors your equipment or device fleets for failures or changes in operation, and triggers actions when such events occur. You can use AWS IoT Events API operations to create, read, update, and delete inputs and detector models, and to list their versions.
servers:
- description: The AWS IoT Events regional endpoint
  url: https://iotevents.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AcknowledgeFlowEnabled:
      type: boolean
    Actions:
      type: array
      items:
        $ref: '#/components/schemas/Action'
    AlarmActions:
      type: array
      items:
        $ref: '#/components/schemas/AlarmAction'
    AlarmModelArn:
      type: string
    AlarmModelDescription:
      type: string
      minLength: 0
      maxLength: 1024
    AlarmModelName:
      type: string
      pattern: ^[a-zA-Z0-9_-]+$
      minLength: 1
      maxLength: 128
    AlarmModelSummaries:
      type: array
      items:
        $ref: '#/components/schemas/AlarmModelSummary'
    AlarmModelVersion:
      type: string
      minLength: 1
      maxLength: 128
    AlarmModelVersionStatus:
      type: string
      enum:
      - ACTIVE
      - ACTIVATING
      - INACTIVE
      - FAILED
    AlarmModelVersionSummaries:
      type: array
      items:
        $ref: '#/components/schemas/AlarmModelVersionSummary'
    AmazonResourceName:
      type: string
      minLength: 1
      maxLength: 2048
    AnalysisId:
      type: string
    AnalysisMessage:
      type: string
    AnalysisResultLevel:
      type: string
      enum:
      - INFO
      - WARNING
      - ERROR
    AnalysisResultLocationPath:
      type: string
    AnalysisResultLocations:
      type: array
      items:
        $ref: '#/components/schemas/AnalysisResultLocation'
    AnalysisResults:
      type: array
      items:
        $ref: '#/components/schemas/AnalysisResult'
    AnalysisStatus:
      type: string
      enum:
      - RUNNING
      - COMPLETE
      - FAILED
    AnalysisType:
      type: string
    AssetId:
      type: string
    AssetModelId:
      type: string
    AssetPropertyAlias:
      type: string
    AssetPropertyBooleanValue:
      type: string
    AssetPropertyDoubleValue:
      type: string
    AssetPropertyEntryId:
      type: string
    AssetPropertyId:
      type: string
    AssetPropertyIntegerValue:
      type: string
    AssetPropertyOffsetInNanos:
      type: string
    AssetPropertyQuality:
      type: string
    AssetPropertyStringValue:
      type: string
    AssetPropertyTimeInSeconds:
      type: string
    AttributeJsonPath:
      type: string
      pattern: ^((`[\w\- ]+`)|([\w\-]+))(\.((`[\w- ]+`)|([\w\-]+)))*$
      minLength: 1
      maxLength: 128
    Attributes:
      type: array
      items:
        $ref: '#/components/schemas/Attribute'
    ComparisonOperator:
      type: string
      enum:
      - GREATER
      - GREATER_OR_EQUAL
      - LESS
      - LESS_OR_EQUAL
      - EQUAL
      - NOT_EQUAL
    Condition:
      type: string
      minLength: 0
      maxLength: 512
    ContentExpression:
      type: string
      minLength: 1
    DeliveryStreamName:
      type: string
    DetectorDebugOptions:
      type: array
      items:
        $ref: '#/components/schemas/DetectorDebugOption'
    DetectorModelArn:
      type: string
    DetectorModelDescription:
      type: string
      minLength: 0
      maxLength: 1024
    DetectorModelName:
      type: string
      pattern: ^[a-zA-Z0-9_-]+$
      minLength: 1
      maxLength: 128
    DetectorModelSummaries:
      type: array
      items:
        $ref: '#/components/schemas/DetectorModelSummary'
    DetectorModelVersion:
      type: string
      minLength: 1
      maxLength: 128
    DetectorModelVersionStatus:
      type: string
      enum:
      - ACTIVE
      - ACTIVATING
      - INACTIVE
      - DEPRECATED
      - DRAFT
      - PAUSED
      - FAILED
    DetectorModelVersionSummaries:
      type: array
      items:
        $ref: '#/components/schemas/DetectorModelVersionSummary'
    DisabledOnInitialization:
      type: boolean
    DynamoKeyField:
      type: string
    DynamoKeyType:
      type: string
    DynamoKeyValue:
      type: string
    DynamoOperation:
      type: string
    DynamoTableName:
      type: string
    EmailConfigurations:
      type: array
      items:
        $ref: '#/components/schemas/EmailConfiguration'
    EmailSubject:
      type: string
    EvaluationMethod:
      type: string
      enum:
      - BATCH
      - SERIAL
    EventName:
      type: string
      minLength: 0
      maxLength: 128
    Events:
      type: array
      items:
        $ref: '#/components/schemas/Event'
    FirehoseSeparator:
      type: string
      pattern: ^([\n\t])|(\r\n)|(,)$
    FromEmail:
      type: string
    IdentityStoreId:
      type: string
    InputArn:
      type: string
    InputDescription:
      type: string
      minLength: 0
      maxLength: 1024
    InputName:
      type: string
      pattern: ^[a-zA-Z][a-zA-Z0-9_]*$
      minLength: 1
      maxLength: 128
    InputProperty:
      type: string
      minLength: 1
      maxLength: 512
    InputStatus:
      type: string
      enum:
      - CREATING
      - UPDATING
      - ACTIVE
      - DELETING
    InputSummaries:
      type: array
      items:
        $ref: '#/components/schemas/InputSummary'
    KeyValue:
      type: string
      pattern: ^[a-zA-Z0-9\-_:]+$
      minLength: 1
      maxLength: 128
    LoggingEnabled:
      type: boolean
      default: false
    LoggingLevel:
      type: string
      enum:
      - ERROR
      - INFO
      - DEBUG
    MQTTTopic:
      type: string
      minLength: 1
      maxLength: 128
    MaxAnalysisResults:
      type: integer
    MaxResults:
      type: integer
      minimum: 1
      maximum: 250
    NextToken:
      type: string
    NotificationActions:
      type: array
      items:
        $ref: '#/components/schemas/NotificationAction'
    NotificationAdditionalMessage:
      type: string
    PayloadType:
      type: string
      enum:
      - STRING
      - JSON
    QueueUrl:
      type: string
    RecipientDetails:
      type: array
      items:
        $ref: '#/components/schemas/RecipientDetail'
    ResourceName:
      type: string
    RoutedResources:
      type: array
      items:
        $ref: '#/components/schemas/RoutedResource'
    SMSConfigurations:
      type: array
      items:
        $ref: '#/components/schemas/SMSConfiguration'
    SMSSenderId:
      type: string
    SSOReferenceId:
      type: string
    Seconds:
      type: integer
      minimum: 1
      maximum: 31622400
    Severity:
      type: integer
      minimum: 0
      maximum: 2147483647
    StateName:
      type: string
      minLength: 1
      maxLength: 128
    States:
      type: array
      items:
        $ref: '#/components/schemas/State'
    StatusMessage:
      type: string
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagKeys:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    Tags:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    Threshold:
      type: string
      minLength: 1
      maxLength: 512
    TimerName:
      type: string
      minLength: 1
      maxLength: 128
    Timestamp:
      type: string
      format: date-time
    TransitionEvents:
      type: array
      items:
        $ref: '#/components/schemas/TransitionEvent'
    UseBase64:
      type: boolean
    VariableName:
      type: string
      pattern: ^[a-zA-Z][a-zA-Z0-9_]*$
      minLength: 1
      maxLength: 128
    VariableValue:
      type: string
      minLength: 1
      maxLength: 1024
    errorMessage:
      type: string
    resourceArn:
      type: string
    resourceId:
      type: string
