openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: iot_events_data
  x-aws-serviceName: ioteventsdata
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-10-23'
  title: AWS IoT Events Data
  description: |-
    IoT Events monitors your equipment or device fleets for failures or changes in operation, and triggers actions when such events occur. You can use IoT Events Data API commands to send inputs to detectors, list detectors, and view or update a detector's status.

    For more information, see [What is IoT Events?](https://docs.aws.amazon.com/iotevents/latest/developerguide/what-is-iotevents.html) in the _IoT Events Developer Guide_.
servers:
- description: The AWS IoT Events Data regional endpoint
  url: https://data.iotevents.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AcknowledgeAlarmActionRequests:
      type: array
      items:
        $ref: '#/components/schemas/AcknowledgeAlarmActionRequest'
    AlarmModelName:
      type: string
      pattern: ^[a-zA-Z0-9_-]+$
      minLength: 1
      maxLength: 128
    AlarmModelVersion:
      type: string
      minLength: 1
      maxLength: 128
    AlarmStateName:
      type: string
      enum:
      - DISABLED
      - NORMAL
      - ACTIVE
      - ACKNOWLEDGED
      - SNOOZE_DISABLED
      - LATCHED
    AlarmSummaries:
      type: array
      items:
        $ref: '#/components/schemas/AlarmSummary'
    BatchAlarmActionErrorEntries:
      type: array
      items:
        $ref: '#/components/schemas/BatchAlarmActionErrorEntry'
    BatchDeleteDetectorErrorEntries:
      type: array
      items:
        $ref: '#/components/schemas/BatchDeleteDetectorErrorEntry'
    BatchPutMessageErrorEntries:
      type: array
      items:
        $ref: '#/components/schemas/BatchPutMessageErrorEntry'
    BatchUpdateDetectorErrorEntries:
      type: array
      items:
        $ref: '#/components/schemas/BatchUpdateDetectorErrorEntry'
    ComparisonOperator:
      type: string
      enum:
      - GREATER
      - GREATER_OR_EQUAL
      - LESS
      - LESS_OR_EQUAL
      - EQUAL
      - NOT_EQUAL
    CustomerActionName:
      type: string
      enum:
      - SNOOZE
      - ENABLE
      - DISABLE
      - ACKNOWLEDGE
      - RESET
    DeleteDetectorRequests:
      type: array
      items:
        $ref: '#/components/schemas/DeleteDetectorRequest'
    DetectorModelName:
      type: string
      pattern: ^[a-zA-Z0-9_-]+$
      minLength: 1
      maxLength: 128
    DetectorModelVersion:
      type: string
      minLength: 1
      maxLength: 128
    DetectorSummaries:
      type: array
      items:
        $ref: '#/components/schemas/DetectorSummary'
    DisableAlarmActionRequests:
      type: array
      items:
        $ref: '#/components/schemas/DisableAlarmActionRequest'
    EnableAlarmActionRequests:
      type: array
      items:
        $ref: '#/components/schemas/EnableAlarmActionRequest'
    EphemeralInputName:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9_.-]*$
      minLength: 1
      maxLength: 128
    EpochMilliTimestamp:
      type: integer
      format: int64
      minimum: 1
      maximum: 9223372036854775807
    ErrorCode:
      type: string
      enum:
      - ResourceNotFoundException
      - InvalidRequestException
      - InternalFailureException
      - ServiceUnavailableException
      - ThrottlingException
    ErrorMessage:
      type: string
    EventType:
      type: string
      enum:
      - STATE_CHANGE
    InputPropertyValue:
      type: string
    KeyValue:
      type: string
      pattern: ^[a-zA-Z0-9\-_:]+$
      minLength: 1
      maxLength: 128
    MaxResults:
      type: integer
      minimum: 1
      maximum: 250
    MessageId:
      type: string
      pattern: ^[a-zA-Z0-9_-]+$
      minLength: 1
      maxLength: 64
    Messages:
      type: array
      items:
        $ref: '#/components/schemas/Message'
    NextToken:
      type: string
    Note:
      type: string
      minLength: 0
      maxLength: 256
    Payload:
      type: string
      format: byte
    RequestId:
      type: string
      pattern: ^[a-zA-Z0-9_-]+$
      minLength: 1
      maxLength: 64
    ResetAlarmActionRequests:
      type: array
      items:
        $ref: '#/components/schemas/ResetAlarmActionRequest'
    Seconds:
      type: integer
    Severity:
      type: integer
      minimum: 0
      maximum: 2147483647
    SnoozeAlarmActionRequests:
      type: array
      items:
        $ref: '#/components/schemas/SnoozeAlarmActionRequest'
    SnoozeDuration:
      type: integer
    StateName:
      type: string
      minLength: 1
      maxLength: 128
    ThresholdValue:
      type: string
    TimerDefinitions:
      type: array
      items:
        $ref: '#/components/schemas/TimerDefinition'
    TimerName:
      type: string
      minLength: 1
      maxLength: 128
    Timers:
      type: array
      items:
        $ref: '#/components/schemas/Timer'
    Timestamp:
      type: string
      format: date-time
    TriggerType:
      type: string
      enum:
      - SNOOZE_TIMEOUT
    UpdateDetectorRequests:
      type: array
      items:
        $ref: '#/components/schemas/UpdateDetectorRequest'
    VariableDefinitions:
      type: array
      items:
        $ref: '#/components/schemas/VariableDefinition'
    VariableName:
      type: string
      pattern: ^[a-zA-Z][a-zA-Z0-9_]*$
      minLength: 1
      maxLength: 128
    VariableValue:
      type: string
      minLength: 1
      maxLength: 1024
    Variables:
      type: array
      items:
        $ref: '#/components/schemas/Variable'
