openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: iot_managed_integrations
  x-aws-serviceName: iotmanagedintegrations
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2025-03-03'
  title: Managed integrations for AWS IoT Device Management
  description: |-
    Managed integrations is a feature of AWS IoT Device Management that enables developers to quickly build innovative IoT solutions. Customers can use managed integrations to automate device setup workflows and support interoperability across many devices, regardless of device vendor or connectivity protocol. This allows developers to use a single user-interface to control, manage, and operate a range of devices.
servers:
- description: The Managed integrations for AWS IoT Device Management regional endpoint
  url: https://api.iotmanagedintegrations.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ActionName:
      type: string
      pattern: ^[/a-zA-Z0-9\._ ]+$
      minLength: 1
      maxLength: 128
    ActionReference:
      type: string
      pattern: ^[a-zA-Z.]+$
    ActionTraceId:
      type: string
      pattern: ^[a-zA-Z0-9]+=(?:_[0-9]+)?$
      minLength: 16
      maxLength: 20
    AdvertisedProductId:
      type: string
      pattern: ^([A-Za-z0-9!#$%&()*\+\-;<=>?@^_`{|}~])+$
      minLength: 5
      maxLength: 5
    AttributeName:
      type: string
      pattern: '[a-zA-Z0-9_.,@/:#-]+'
      maxLength: 128
    AttributeValue:
      type: string
      pattern: '[a-zA-Z0-9_.,@/:#-]*'
      maxLength: 800
    AuthMaterialString:
      type: string
      pattern: '^[0-9A-Za-z!#$%&()*\+\-;<=>?@^_`{|}~\/: ]+$'
      minLength: 1
      maxLength: 512
    BaseRatePerMinute:
      type: integer
      minimum: 1
      maximum: 100
    Brand:
      type: string
      pattern: ^[A-Za-z0-9-_ ]+$
      minLength: 1
      maxLength: 128
    CaCertificate:
      type: string
      pattern: ^-----BEGIN CERTIFICATE-----.*(.|\n)*-----END CERTIFICATE-----\n?$
    Capabilities:
      type: string
      pattern: ^[a-zA-Z0-9\s'\x{0022},.:\\\/{$}\[\]=_\-\+]+$
      minLength: 1
      maxLength: 65535
    CapabilityActionName:
      type: string
      pattern: ^[/a-zA-Z]+$
    CapabilityId:
      type: string
      pattern: ^[a-zA-Z0-9./]+(@\d+\.\d+)?$
      minLength: 1
      maxLength: 128
    CapabilityName:
      type: string
      pattern: ^[/a-zA-Z0-9\._ ]+$
      minLength: 1
      maxLength: 128
    CapabilityReportVersion:
      type: string
      pattern: ^1\.0\.0$
      minLength: 1
      maxLength: 10
    CapabilityVersion:
      type: string
      pattern: ^(0|[1-9][0-9]*)$
      minLength: 1
      maxLength: 64
    ClaimCertificate:
      type: string
    ClaimCertificatePrivateKey:
      type: string
    Classification:
      type: string
      minLength: 1
      maxLength: 64
    ClientToken:
      type: string
      pattern: ^[a-zA-Z0-9=_-]+$
      minLength: 1
      maxLength: 64
    ConfigurationErrorCode:
      type: string
      pattern: ^[a-zA-Z0-9_-]+$
      minLength: 1
      maxLength: 256
    ConfigurationErrorMessage:
      type: string
      pattern: ^[a-zA-Z0-9\-._,]+$
      minLength: 1
      maxLength: 65535
    ConnectivityStatus:
      type: boolean
    ConnectorAssociationId:
      type: string
      pattern: ^[0-9a-zA-Z]+$
      minLength: 1
      maxLength: 64
    ConnectorDeviceId:
      type: string
      pattern: ^[a-zA-Z0-9_.,@-]+$
      minLength: 1
      maxLength: 256
    ConnectorPolicyId:
      type: string
      pattern: ^[A-Za-z0-9-_]+$
      minLength: 1
      maxLength: 64
    CredentialLockerArn:
      type: string
      pattern: ^arn:aws:iotmanagedintegrations:[0-9a-zA-Z-]+:[0-9]+:credential-locker/[0-9a-zA-Z]+$
      minLength: 32
      maxLength: 1011
    CredentialLockerId:
      type: string
      pattern: ^[a-zA-Z0-9]*$
      minLength: 1
      maxLength: 64
    CredentialLockerName:
      type: string
      pattern: ^[A-Za-z0-9-_ ]+$
      minLength: 1
      maxLength: 128
    DeleteLocalStoreAfterUpload:
      type: boolean
    DeliveryDestinationArn:
      type: string
      pattern: ^arn:aws:[0-9a-zA-Z]+:[0-9a-zA-Z-]+:[0-9]+:[0-9a-zA-Z]+/[0-9a-zA-Z._-]+$
      minLength: 20
      maxLength: 2048
    DeliveryDestinationRoleArn:
      type: string
    DestinationDescription:
      type: string
      pattern: ^[0-9A-Za-z_\- ]+$
      minLength: 1
      maxLength: 256
    DestinationName:
      type: string
      pattern: ^[\p{L}\p{N} ._-]+$
      minLength: 1
      maxLength: 128
    DeviceDiscoveryArn:
      type: string
      pattern: ^arn:aws:iotmanagedintegrations:[0-9a-zA-Z-]+:[0-9]+:device-discovery/[0-9a-zA-Z]+$
    DeviceDiscoveryId:
      type: string
      pattern: ^[A-Za-z0-9]+$
      minLength: 1
      maxLength: 200
    DeviceSpecificKey:
      type: string
      pattern: ^[a-zA-Z0-9=_.,@\+\-]+$
      minLength: 1
      maxLength: 128
    DeviceType:
      type: string
      pattern: ^[a-zA-Z0-9=_. ,@\+\-/]+$
      maxLength: 256
    DiscoveryAuthMaterialString:
      type: string
      pattern: ^[0-9A-Za-z_\-\+=\/:; ]+$
      minLength: 1
      maxLength: 64
    DurationInMinutes:
      type: integer
      minimum: 1
      maximum: 1430
    EndTime:
      type: string
    EndpointAddress:
      type: string
      pattern: ^[A-Za-z0-9._@-]+$
      minLength: 1
      maxLength: 256
    EndpointId:
      type: string
      pattern: ^[0-9a-zA-Z]+$
      minLength: 1
      maxLength: 64
    ErrorMessage:
      type: string
    EventName:
      type: string
      pattern: ^[/a-zA-Z0-9\._ ]+$
      minLength: 1
      maxLength: 128
    InternationalArticleNumber:
      type: string
      pattern: ^[0-9]+$
      minLength: 8
      maxLength: 13
    KmsKeyArn:
      type: string
      pattern: ^arn:aws:kms:[0-9a-zA-Z-]+:[0-9]+:key/[0-9a-zA-Z-]+$
      minLength: 1
      maxLength: 200
    LocalStoreFileRotationMaxBytes:
      type: integer
    LocalStoreFileRotationMaxFiles:
      type: integer
    LocalStoreLocation:
      type: string
    LogConfigurationId:
      type: string
      pattern: ^[A-Za-z0-9]+$
      minLength: 1
      maxLength: 200
    MacAddress:
      type: string
      minLength: 1
      maxLength: 128
    ManagedThingArn:
      type: string
      pattern: ^arn:aws:iotmanagedintegrations:[0-9a-zA-Z-]+:[0-9]+:managed-thing/([0-9a-zA-Z:_-])+$
      minLength: 32
      maxLength: 1011
    ManagedThingId:
      type: string
      pattern: ^[a-zA-Z0-9:_-]*$
      minLength: 1
      maxLength: 64
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
    MaximumPerMinute:
      type: integer
      minimum: 1
    MinNumberOfExecutedThings:
      type: integer
      minimum: 1
      maximum: 100
    MinNumberOfRetries:
      type: integer
      minimum: 0
      maximum: 10
    Model:
      type: string
      pattern: ^[A-Za-z0-9-_ ]+$
      minLength: 1
      maxLength: 128
    Name:
      type: string
      pattern: ^[\p{L}\p{N} ._-]+$
      minLength: 1
      maxLength: 128
    NextToken:
      type: string
      pattern: ^[a-zA-Z0-9=_-]+$
      minLength: 1
      maxLength: 65535
    NodeId:
      type: string
      pattern: ^[a-zA-Z0-9=_.,@\+\-/]+$
      minLength: 1
      maxLength: 64
    NumberOfNotifiedThings:
      type: integer
      minimum: 1
      maximum: 100
    NumberOfSucceededThings:
      type: integer
      minimum: 1
      maximum: 100
    OtaDescription:
      type: string
      pattern: ^[0-9A-Za-z_\- ]+$
      minLength: 1
      maxLength: 256
    OtaNextToken:
      type: string
      pattern: ^[a-zA-Z0-9=_+/-]+$
      minLength: 1
      maxLength: 65535
    OtaTargetQueryString:
      type: string
    OtaTaskArn:
      type: string
      pattern: ^arn:aws:iotmanagedintegrations:[0-9a-zA-Z-]+:[0-9]+:ota-task/[0-9a-zA-Z]+$
      minLength: 0
      maxLength: 1011
    OtaTaskConfigurationId:
      type: string
      pattern: ^[a-zA-Z0-9]*$
      minLength: 1
      maxLength: 64
    OtaTaskConfigurationName:
      type: string
      pattern: ^[A-Za-z0-9-_ ]+$
      minLength: 1
      maxLength: 128
    OtaTaskId:
      type: string
      pattern: ^[A-Za-z0-9]+$
      minLength: 1
      maxLength: 200
    Owner:
      type: string
      pattern: ^[a-zA-Z0-9_.,@-]+$
      minLength: 1
      maxLength: 64
    ParentControllerId:
      type: string
      pattern: ^[A-Za-z0-9]+$
      minLength: 1
      maxLength: 64
    PropertyName:
      type: string
      pattern: ^[/a-zA-Z0-9\._ ]+$
      minLength: 1
      maxLength: 128
    ProvisioningProfileArn:
      type: string
      pattern: ^arn:aws:iotmanagedintegrations:[0-9a-zA-Z-]+:[0-9]+:provisioning-profile/[0-9a-zA-Z]+$
      minLength: 32
      maxLength: 64
    ProvisioningProfileId:
      type: string
      pattern: ^[A-Za-z0-9-_]+$
      minLength: 1
      maxLength: 64
    ProvisioningProfileName:
      type: string
      pattern: ^[0-9A-Za-z_-]+$
      minLength: 1
      maxLength: 36
    RetryAttempt:
      type: integer
    S3Url:
      type: string
      minLength: 1
      maxLength: 1000
    ScheduleStartTime:
      type: string
    SchemaId:
      type: string
      pattern: ^[a-zA-Z0-9./]+$
      minLength: 1
      maxLength: 128
    SchemaVersionDescription:
      type: string
      pattern: ^[a-zA-Z0-9., ]+$
      minLength: 1
      maxLength: 256
    SchemaVersionNamespaceName:
      type: string
      pattern: ^[a-z]+$
      minLength: 1
      maxLength: 256
    SchemaVersionVersion:
      type: string
      pattern: ^(\d+\.\d+|\$latest)$
      minLength: 1
      maxLength: 256
    SchemaVersionedId:
      type: string
      pattern: ^[a-zA-Z0-9.\/]+(@(\d+\.\d+|\$latest))?$
      minLength: 1
      maxLength: 128
    SerialNumber:
      type: string
      pattern: ^[A-Za-z0-9-_ ]+$
      minLength: 1
      maxLength: 128
    SmartHomeResourceId:
      type: string
      pattern: ^[a-zA-Z0-9+*]*$
      minLength: 1
      maxLength: 200
    SmartHomeResourceType:
      type: string
      pattern: ^[*]$|^(managed-thing|credential-locker|provisioning-profile|ota-task)$
    StartTime:
      type: string
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TraceId:
      type: string
      pattern: ^[a-zA-Z0-9:=_-]+$
      minLength: 1
      maxLength: 128
    UniversalProductCode:
      type: string
      pattern: ^[0-9]+$
      minLength: 12
      maxLength: 12
    UploadLog:
      type: boolean
    UploadPeriodMinutes:
      type: integer
