openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: iot_managed_integrations
  x-aws-serviceName: iotmanagedintegrations
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2025-03-03'
  title: Managed integrations for AWS IoT Device Management
  description: |-
    Managed integrations is a feature of AWS IoT Device Management that enables developers to quickly build innovative IoT solutions. Customers can use managed integrations to automate device setup workflows and support interoperability across many devices, regardless of device vendor or connectivity protocol. This allows developers to use a single user-interface to control, manage, and operate a range of devices.
servers:
- description: The Managed integrations for AWS IoT Device Management regional endpoint
  url: https://api.iotmanagedintegrations.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AbortConfigCriteriaList:
      type: array
      items:
        $ref: '#/components/schemas/AbortConfigCriteria'
    AbortCriteriaAction:
      type: string
      enum:
      - CANCEL
    AbortCriteriaFailureType:
      type: string
      enum:
      - FAILED
      - REJECTED
      - TIMED_OUT
      - ALL
    ActionName:
      type: string
      pattern: ^[/a-zA-Z0-9\._ ]+$
      minLength: 1
      maxLength: 128
    ActionReference:
      type: string
      pattern: ^[a-zA-Z.]+$
    ActionTraceId:
      type: string
      pattern: ^[a-zA-Z0-9]+=(?:_[0-9]+)?$
      minLength: 16
      maxLength: 20
    AdvertisedProductId:
      type: string
      pattern: ^([A-Za-z0-9!#$%&()*\+\-;<=>?@^_`{|}~])+$
      minLength: 5
      maxLength: 5
    AttributeName:
      type: string
      pattern: '[a-zA-Z0-9_.,@/:#-]+'
      maxLength: 128
    AttributeValue:
      type: string
      pattern: '[a-zA-Z0-9_.,@/:#-]*'
      maxLength: 800
    AuthMaterialString:
      type: string
      pattern: '^[0-9A-Za-z!#$%&()*\+\-;<=>?@^_`{|}~\/: ]+$'
      minLength: 1
      maxLength: 512
    AuthMaterialType:
      type: string
      enum:
      - WIFI_SETUP_QR_BAR_CODE
      - ZWAVE_QR_BAR_CODE
      - ZIGBEE_QR_BAR_CODE
    BaseRatePerMinute:
      type: integer
      minimum: 1
      maximum: 100
    Brand:
      type: string
      pattern: ^[A-Za-z0-9-_ ]+$
      minLength: 1
      maxLength: 128
    CaCertificate:
      type: string
      pattern: ^-----BEGIN CERTIFICATE-----.*(.|\n)*-----END CERTIFICATE-----\n?$
    Capabilities:
      type: string
      pattern: ^[a-zA-Z0-9\s'\x{0022},.:\\\/{$}\[\]=_\-\+]+$
      minLength: 1
      maxLength: 65535
    CapabilityActionName:
      type: string
      pattern: ^[/a-zA-Z]+$
    CapabilityActions:
      type: array
      items:
        $ref: '#/components/schemas/CapabilityAction'
    CapabilityId:
      type: string
      pattern: ^[a-zA-Z0-9./]+(@\d+\.\d+)?$
      minLength: 1
      maxLength: 128
    CapabilityName:
      type: string
      pattern: ^[/a-zA-Z0-9\._ ]+$
      minLength: 1
      maxLength: 128
    CapabilityProperties:
      type: object
      additionalProperties: true
      x-sensitive: true
    CapabilityReportActions:
      type: array
      items:
        $ref: '#/components/schemas/ActionName'
    CapabilityReportCapabilities:
      type: array
      items:
        $ref: '#/components/schemas/CapabilityReportCapability'
    CapabilityReportEndpoints:
      type: array
      items:
        $ref: '#/components/schemas/CapabilityReportEndpoint'
    CapabilityReportEvents:
      type: array
      items:
        $ref: '#/components/schemas/EventName'
    CapabilityReportProperties:
      type: array
      items:
        $ref: '#/components/schemas/PropertyName'
    CapabilityReportVersion:
      type: string
      pattern: ^1\.0\.0$
      minLength: 1
      maxLength: 10
    CapabilityVersion:
      type: string
      pattern: ^(0|[1-9][0-9]*)$
      minLength: 1
      maxLength: 64
    ClaimCertificate:
      type: string
    ClaimCertificatePrivateKey:
      type: string
    Classification:
      type: string
      minLength: 1
      maxLength: 64
    ClientToken:
      type: string
      pattern: ^[a-zA-Z0-9=_-]+$
      minLength: 1
      maxLength: 64
    CommandCapabilities:
      type: array
      items:
        $ref: '#/components/schemas/CommandCapability'
    CommandEndpoints:
      type: array
      items:
        $ref: '#/components/schemas/CommandEndpoint'
    ConfigurationErrorCode:
      type: string
      pattern: ^[a-zA-Z0-9_-]+$
      minLength: 1
      maxLength: 256
    ConfigurationErrorMessage:
      type: string
      pattern: ^[a-zA-Z0-9\-._,]+$
      minLength: 1
      maxLength: 65535
    ConfigurationState:
      type: string
      enum:
      - ENABLED
      - UPDATE_IN_PROGRESS
      - UPDATE_FAILED
    ConnectivityStatus:
      type: boolean
    ConnectivityTimestamp:
      type: string
      format: date-time
    ConnectorAssociationId:
      type: string
      pattern: ^[0-9a-zA-Z]+$
      minLength: 1
      maxLength: 64
    ConnectorDeviceId:
      type: string
      pattern: ^[a-zA-Z0-9_.,@-]+$
      minLength: 1
      maxLength: 256
    ConnectorPolicyId:
      type: string
      pattern: ^[A-Za-z0-9-_]+$
      minLength: 1
      maxLength: 64
    CreatedAt:
      type: string
      format: date-time
    CredentialLockerArn:
      type: string
      pattern: ^arn:aws:iotmanagedintegrations:[0-9a-zA-Z-]+:[0-9]+:credential-locker/[0-9a-zA-Z]+$
      minLength: 32
      maxLength: 1011
    CredentialLockerCreatedAt:
      type: string
      format: date-time
    CredentialLockerId:
      type: string
      pattern: ^[a-zA-Z0-9]*$
      minLength: 1
      maxLength: 64
    CredentialLockerListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/CredentialLockerSummary'
    CredentialLockerName:
      type: string
      pattern: ^[A-Za-z0-9-_ ]+$
      minLength: 1
      maxLength: 128
    DeleteLocalStoreAfterUpload:
      type: boolean
    DeliveryDestinationArn:
      type: string
      pattern: ^arn:aws:[0-9a-zA-Z]+:[0-9a-zA-Z-]+:[0-9]+:[0-9a-zA-Z]+/[0-9a-zA-Z._-]+$
      minLength: 20
      maxLength: 2048
    DeliveryDestinationRoleArn:
      type: string
    DeliveryDestinationType:
      type: string
      enum:
      - KINESIS
    DestinationCreatedAt:
      type: string
      format: date-time
    DestinationDescription:
      type: string
      pattern: ^[0-9A-Za-z_\- ]+$
      minLength: 1
      maxLength: 256
    DestinationListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/DestinationSummary'
    DestinationName:
      type: string
      pattern: ^[\p{L}\p{N} ._-]+$
      minLength: 1
      maxLength: 128
    DestinationUpdatedAt:
      type: string
      format: date-time
    DeviceDiscoveryArn:
      type: string
      pattern: ^arn:aws:iotmanagedintegrations:[0-9a-zA-Z-]+:[0-9]+:device-discovery/[0-9a-zA-Z]+$
    DeviceDiscoveryId:
      type: string
      pattern: ^[A-Za-z0-9]+$
      minLength: 1
      maxLength: 200
    DeviceDiscoveryStatus:
      type: string
      enum:
      - RUNNING
      - SUCCEEDED
      - FAILED
      - TIMED_OUT
    DeviceSpecificKey:
      type: string
      pattern: ^[a-zA-Z0-9=_.,@\+\-]+$
      minLength: 1
      maxLength: 128
    DeviceType:
      type: string
      pattern: ^[a-zA-Z0-9=_. ,@\+\-/]+$
      maxLength: 256
    DeviceTypes:
      type: array
      items:
        $ref: '#/components/schemas/DeviceType'
    DisconnectReasonValue:
      type: string
      enum:
      - AUTH_ERROR
      - CLIENT_INITIATED_DISCONNECT
      - CLIENT_ERROR
      - CONNECTION_LOST
      - DUPLICATE_CLIENTID
      - FORBIDDEN_ACCESS
      - MQTT_KEEP_ALIVE_TIMEOUT
      - SERVER_ERROR
      - SERVER_INITIATED_DISCONNECT
      - THROTTLED
      - WEBSOCKET_TTL_EXPIRATION
      - CUSTOMAUTH_TTL_EXPIRATION
      - UNKNOWN
      - NONE
    DiscoveryAuthMaterialString:
      type: string
      pattern: ^[0-9A-Za-z_\-\+=\/:; ]+$
      minLength: 1
      maxLength: 64
    DiscoveryAuthMaterialType:
      type: string
      enum:
      - ZWAVE_INSTALL_CODE
    DiscoveryFinishedAt:
      type: string
      format: date-time
    DiscoveryStartedAt:
      type: string
      format: date-time
    DiscoveryType:
      type: string
      enum:
      - ZWAVE
      - ZIGBEE
      - CLOUD
    DurationInMinutes:
      type: integer
      minimum: 1
      maximum: 1430
    EncryptionType:
      type: string
      enum:
      - MANAGED_INTEGRATIONS_DEFAULT_ENCRYPTION
      - CUSTOMER_KEY_ENCRYPTION
    EndTime:
      type: string
    EndpointAddress:
      type: string
      pattern: ^[A-Za-z0-9._@-]+$
      minLength: 1
      maxLength: 256
    EndpointId:
      type: string
      pattern: ^[0-9a-zA-Z]+$
      minLength: 1
      maxLength: 64
    ErrorMessage:
      type: string
    EventLogConfigurationListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/EventLogConfigurationSummary'
    EventName:
      type: string
      pattern: ^[/a-zA-Z0-9\._ ]+$
      minLength: 1
      maxLength: 128
    EventType:
      type: string
      enum:
      - DEVICE_COMMAND
      - DEVICE_COMMAND_REQUEST
      - DEVICE_EVENT
      - DEVICE_LIFE_CYCLE
      - DEVICE_STATE
      - DEVICE_OTA
      - CONNECTOR_ASSOCIATION
      - CONNECTOR_ERROR_REPORT
    ExecutionNumber:
      type: integer
      format: int64
    HubConfigurationUpdatedAt:
      type: string
      format: date-time
    HubNetworkMode:
      type: string
      enum:
      - STANDARD
      - NETWORK_WIDE_EXCLUSION
    HubTokenTimerExpirySettingInSeconds:
      type: integer
      format: int64
      minimum: 1
    InProgressTimeoutInMinutes:
      type: integer
      format: int64
      minimum: 1
      maximum: 10080
    IncrementFactor:
      type: number
      format: double
      minimum: 1.1
      maximum: 5
    InternationalArticleNumber:
      type: string
      pattern: ^[0-9]+$
      minLength: 8
      maxLength: 13
    KmsKeyArn:
      type: string
      pattern: ^arn:aws:kms:[0-9a-zA-Z-]+:[0-9]+:key/[0-9a-zA-Z-]+$
      minLength: 1
      maxLength: 200
    LastUpdatedAt:
      type: string
      format: date-time
    LocalStoreFileRotationMaxBytes:
      type: integer
    LocalStoreFileRotationMaxFiles:
      type: integer
    LocalStoreLocation:
      type: string
    LogConfigurationId:
      type: string
      pattern: ^[A-Za-z0-9]+$
      minLength: 1
      maxLength: 200
    LogLevel:
      type: string
      enum:
      - DEBUG
      - ERROR
      - INFO
      - WARN
    MacAddress:
      type: string
      minLength: 1
      maxLength: 128
    ManagedThingArn:
      type: string
      pattern: ^arn:aws:iotmanagedintegrations:[0-9a-zA-Z-]+:[0-9]+:managed-thing/([0-9a-zA-Z:_-])+$
      minLength: 32
      maxLength: 1011
    ManagedThingId:
      type: string
      pattern: ^[a-zA-Z0-9:_-]*$
      minLength: 1
      maxLength: 64
    ManagedThingListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/ManagedThingSummary'
    ManagedThingSchemaListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/ManagedThingSchemaListItem'
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
    MaximumPerMinute:
      type: integer
      minimum: 1
    MetaData:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/AttributeValue'
    MinNumberOfExecutedThings:
      type: integer
      minimum: 1
      maximum: 100
    MinNumberOfRetries:
      type: integer
      minimum: 0
      maximum: 10
    Model:
      type: string
      pattern: ^[A-Za-z0-9-_ ]+$
      minLength: 1
      maxLength: 128
    Name:
      type: string
      pattern: ^[\p{L}\p{N} ._-]+$
      minLength: 1
      maxLength: 128
    NextToken:
      type: string
      pattern: ^[a-zA-Z0-9=_-]+$
      minLength: 1
      maxLength: 65535
    NodeId:
      type: string
      pattern: ^[a-zA-Z0-9=_.,@\+\-/]+$
      minLength: 1
      maxLength: 64
    NotificationConfigurationCreatedAt:
      type: string
      format: date-time
    NotificationConfigurationListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/NotificationConfigurationSummary'
    NotificationConfigurationUpdatedAt:
      type: string
      format: date-time
    NumberOfNotifiedThings:
      type: integer
      minimum: 1
      maximum: 100
    NumberOfSucceededThings:
      type: integer
      minimum: 1
      maximum: 100
    OtaDescription:
      type: string
      pattern: ^[0-9A-Za-z_\- ]+$
      minLength: 1
      maxLength: 256
    OtaMechanism:
      type: string
      enum:
      - PUSH
    OtaNextToken:
      type: string
      pattern: ^[a-zA-Z0-9=_+/-]+$
      minLength: 1
      maxLength: 65535
    OtaProtocol:
      type: string
      enum:
      - HTTP
    OtaStatus:
      type: string
      enum:
      - IN_PROGRESS
      - CANCELED
      - COMPLETED
      - DELETION_IN_PROGRESS
      - SCHEDULED
    OtaTargetQueryString:
      type: string
    OtaTaskArn:
      type: string
      pattern: ^arn:aws:iotmanagedintegrations:[0-9a-zA-Z-]+:[0-9]+:ota-task/[0-9a-zA-Z]+$
      minLength: 0
      maxLength: 1011
    OtaTaskConfigurationId:
      type: string
      pattern: ^[a-zA-Z0-9]*$
      minLength: 1
      maxLength: 64
    OtaTaskConfigurationListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/OtaTaskConfigurationSummary'
    OtaTaskConfigurationName:
      type: string
      pattern: ^[A-Za-z0-9-_ ]+$
      minLength: 1
      maxLength: 128
    OtaTaskExecutionStatus:
      type: string
      enum:
      - QUEUED
      - IN_PROGRESS
      - SUCCEEDED
      - FAILED
      - TIMED_OUT
      - REJECTED
      - REMOVED
      - CANCELED
    OtaTaskExecutionSummariesListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/OtaTaskExecutionSummaries'
    OtaTaskId:
      type: string
      pattern: ^[A-Za-z0-9]+$
      minLength: 1
      maxLength: 200
    OtaTaskListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/OtaTaskSummary'
    OtaType:
      type: string
      enum:
      - ONE_TIME
      - CONTINUOUS
    Owner:
      type: string
      pattern: ^[a-zA-Z0-9_.,@-]+$
      minLength: 1
      maxLength: 64
    ParentControllerId:
      type: string
      pattern: ^[A-Za-z0-9]+$
      minLength: 1
      maxLength: 64
    PropertyName:
      type: string
      pattern: ^[/a-zA-Z0-9\._ ]+$
      minLength: 1
      maxLength: 128
    ProvisioningProfileArn:
      type: string
      pattern: ^arn:aws:iotmanagedintegrations:[0-9a-zA-Z-]+:[0-9]+:provisioning-profile/[0-9a-zA-Z]+$
      minLength: 32
      maxLength: 64
    ProvisioningProfileId:
      type: string
      pattern: ^[A-Za-z0-9-_]+$
      minLength: 1
      maxLength: 64
    ProvisioningProfileListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/ProvisioningProfileSummary'
    ProvisioningProfileName:
      type: string
      pattern: ^[0-9A-Za-z_-]+$
      minLength: 1
      maxLength: 36
    ProvisioningStatus:
      type: string
      enum:
      - UNASSOCIATED
      - PRE_ASSOCIATED
      - DISCOVERED
      - ACTIVATED
      - DELETION_FAILED
      - DELETE_IN_PROGRESS
      - ISOLATED
      - DELETED
    ProvisioningType:
      type: string
      enum:
      - FLEET_PROVISIONING
      - JITR
    QueuedAt:
      type: string
      format: date-time
    RetryAttempt:
      type: integer
    RetryConfigCriteriaList:
      type: array
      items:
        $ref: '#/components/schemas/RetryConfigCriteria'
    RetryCriteriaFailureType:
      type: string
      enum:
      - FAILED
      - TIMED_OUT
      - ALL
    Role:
      type: string
      enum:
      - CONTROLLER
      - DEVICE
    S3Url:
      type: string
      minLength: 1
      maxLength: 1000
    ScheduleMaintenanceWindowList:
      type: array
      items:
        $ref: '#/components/schemas/ScheduleMaintenanceWindow'
    ScheduleStartTime:
      type: string
    SchedulingConfigEndBehavior:
      type: string
      enum:
      - STOP_ROLLOUT
      - CANCEL
      - FORCE_CANCEL
    SchemaId:
      type: string
      pattern: ^[a-zA-Z0-9./]+$
      minLength: 1
      maxLength: 128
    SchemaVersionDescription:
      type: string
      pattern: ^[a-zA-Z0-9., ]+$
      minLength: 1
      maxLength: 256
    SchemaVersionFormat:
      type: string
      enum:
      - AWS
      - ZCL
      - CONNECTOR
    SchemaVersionList:
      type: array
      items:
        $ref: '#/components/schemas/SchemaVersionListItem'
    SchemaVersionNamespaceName:
      type: string
      pattern: ^[a-z]+$
      minLength: 1
      maxLength: 256
    SchemaVersionSchema:
      type: object
      additionalProperties: true
    SchemaVersionType:
      type: string
      enum:
      - capability
      - definition
    SchemaVersionVersion:
      type: string
      pattern: ^(\d+\.\d+|\$latest)$
      minLength: 1
      maxLength: 256
    SchemaVersionVisibility:
      type: string
      enum:
      - PUBLIC
      - PRIVATE
    SchemaVersionedId:
      type: string
      pattern: ^[a-zA-Z0-9.\/]+(@(\d+\.\d+|\$latest))?$
      minLength: 1
      maxLength: 128
    SerialNumber:
      type: string
      pattern: ^[A-Za-z0-9-_ ]+$
      minLength: 1
      maxLength: 128
    SetupAt:
      type: string
      format: date-time
    SmartHomeResourceId:
      type: string
      pattern: ^[a-zA-Z0-9+*]*$
      minLength: 1
      maxLength: 200
    SmartHomeResourceType:
      type: string
      pattern: ^[*]$|^(managed-thing|credential-locker|provisioning-profile|ota-task)$
    StartTime:
      type: string
    StartedAt:
      type: string
      format: date-time
    StateCapabilities:
      type: array
      items:
        $ref: '#/components/schemas/StateCapability'
    StateEndpoints:
      type: array
      items:
        $ref: '#/components/schemas/StateEndpoint'
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TagsMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    Target:
      type: array
      items:
        type: string
    ThresholdPercentage:
      type: number
      format: double
      maximum: 100
    TraceId:
      type: string
      pattern: ^[a-zA-Z0-9:=_-]+$
      minLength: 1
      maxLength: 128
    UniversalProductCode:
      type: string
      pattern: ^[0-9]+$
      minLength: 12
      maxLength: 12
    UpdatedAt:
      type: string
      format: date-time
    UploadLog:
      type: boolean
    UploadPeriodMinutes:
      type: integer
    ValidationSchema:
      type: object
      additionalProperties: true
