openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: iottwinmaker
  x-aws-serviceName: iottwinmaker
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2021-11-29'
  title: AWS IoT TwinMaker
  description: |-
    IoT TwinMaker is a service with which you can build operational digital twins of physical systems. IoT TwinMaker overlays measurements and analysis from real-world sensors, cameras, and enterprise applications so you can create data visualizations to monitor your physical factory, building, or industrial plant. You can use this real-world data to monitor operations and diagnose and repair errors.
servers:
- description: The AWS IoT TwinMaker regional endpoint
  url: https://iottwinmaker.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Boolean:
      type: boolean
    BundleName:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 256
    ColumnName:
      type: string
      pattern: ^.*$
    ColumnType:
      type: string
      enum:
      - NODE
      - EDGE
      - VALUE
    ComponentPath:
      type: string
      pattern: ^[a-zA-Z_\-0-9/]+$
      minLength: 1
      maxLength: 2048
    ComponentTypeId:
      type: string
      pattern: ^[a-zA-Z_\.\-0-9:]+$
      minLength: 1
      maxLength: 256
    ComponentTypeName:
      type: string
      pattern: '[^\u0000-\u001F\u007F]*'
      minLength: 0
      maxLength: 256
    ComponentUpdateType:
      type: string
      enum:
      - CREATE
      - UPDATE
      - DELETE
    Description:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 2048
    DestinationType:
      type: string
      enum:
      - s3
      - iotsitewise
      - iottwinmaker
    EntityId:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|^[a-zA-Z0-9][a-zA-Z_\-0-9.:]*[a-zA-Z0-9]+$
      minLength: 1
      maxLength: 128
    EntityName:
      type: string
      pattern: ^[^\u0000-\u001F\u007F]+$
      minLength: 1
      maxLength: 256
    ErrorCode:
      type: string
      enum:
      - VALIDATION_ERROR
      - INTERNAL_FAILURE
      - SYNC_INITIALIZING_ERROR
      - SYNC_CREATING_ERROR
      - SYNC_PROCESSING_ERROR
      - SYNC_DELETING_ERROR
      - PROCESSING_ERROR
      - COMPOSITE_COMPONENT_FAILURE
    ErrorMessage:
      type: string
      minLength: 0
      maxLength: 2048
    ExceptionMessage:
      type: string
    Expression:
      type: string
      pattern: ^(^\$\{Parameters\.[a-zA-z]+([a-zA-z_0-9]*)}$)$
      minLength: 1
      maxLength: 316
    GroupType:
      type: string
      enum:
      - TABULAR
    Id:
      type: string
      pattern: ^[a-zA-Z_0-9][a-zA-Z_\-0-9]*[a-zA-Z0-9]+$
      minLength: 1
      maxLength: 128
    IdOrArn:
      type: string
      pattern: ^[a-zA-Z_0-9][a-zA-Z_\-0-9]*[a-zA-Z0-9]+$|^arn:((aws)|(aws-cn)|(aws-us-gov)):iottwinmaker:[a-z0-9-]+:[0-9]{12}:[\/a-zA-Z0-9_-]+$
      minLength: 1
      maxLength: 2048
    Integer:
      type: integer
    InterpolationType:
      type: string
      enum:
      - LINEAR
    LambdaArn:
      type: string
      pattern: ^arn:((aws)|(aws-cn)|(aws-us-gov)):lambda:[a-z0-9-]+:[0-9]{12}:function:[\/a-zA-Z0-9_-]+$
      minLength: 20
      maxLength: 2048
    LinkedService:
      type: string
      pattern: ^[a-zA-Z_0-9]+$
    MaxResults:
      type: integer
      minimum: 0
      maximum: 200
    MetadataTransferJobState:
      type: string
      enum:
      - VALIDATING
      - PENDING
      - RUNNING
      - CANCELLING
      - ERROR
      - COMPLETED
      - CANCELLED
    Name:
      type: string
      pattern: ^[a-zA-Z_\-0-9]+$
      minLength: 1
      maxLength: 256
    NextToken:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 17880
    Order:
      type: string
      enum:
      - ASCENDING
      - DESCENDING
    OrderByTime:
      type: string
      enum:
      - ASCENDING
      - DESCENDING
    ParentEntityId:
      type: string
      pattern: ^\$ROOT|^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|^[a-zA-Z0-9][a-zA-Z_\-0-9.:]*[a-zA-Z0-9]+$
      minLength: 1
      maxLength: 128
    ParentEntityUpdateType:
      type: string
      enum:
      - UPDATE
      - DELETE
    PricingMode:
      type: string
      enum:
      - BASIC
      - STANDARD
      - TIERED_BUNDLE
    PricingTier:
      type: string
      enum:
      - TIER_1
      - TIER_2
      - TIER_3
      - TIER_4
    PropertyDisplayName:
      type: string
      pattern: '[^\u0000-\u001F\u007F]*'
      minLength: 0
      maxLength: 256
    PropertyGroupUpdateType:
      type: string
      enum:
      - UPDATE
      - DELETE
      - CREATE
    PropertyUpdateType:
      type: string
      enum:
      - UPDATE
      - DELETE
      - CREATE
      - RESET_VALUE
    QueryServiceMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    QueryStatement:
      type: string
      pattern: ^[\s\S]+$
      minLength: 1
      maxLength: 1000
    RoleArn:
      type: string
      pattern: ^arn:((aws)|(aws-cn)|(aws-us-gov)):iam::[0-9]{12}:role/
      minLength: 20
      maxLength: 2048
    S3DestinationLocation:
      type: string
      pattern: (^arn:((aws)|(aws-cn)|(aws-us-gov)):s3:::)([/a-zA-Z0-9_-]+$)
    S3Location:
      type: string
      pattern: (^arn:((aws)|(aws-cn)|(aws-us-gov)):s3:::)([a-zA-Z0-9_-]+$)
      minLength: 0
      maxLength: 1024
    S3SourceLocation:
      type: string
      pattern: (^arn:((aws)|(aws-cn)|(aws-us-gov)):s3:::)([a-zA-Z0-9_-]+)\/([/.a-zA-Z0-9_-]+$)
    S3Url:
      type: string
      pattern: ^[sS]3://[A-Za-z0-9._/-]+$
      minLength: 0
      maxLength: 256
    SceneCapability:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 256
    SceneErrorCode:
      type: string
      enum:
      - MATTERPORT_ERROR
    SceneMetadataValue:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 2048
    Scope:
      type: string
      enum:
      - ENTITY
      - WORKSPACE
    SiteWiseExternalId:
      type: string
      pattern: '[a-zA-Z0-9_][a-zA-Z_\-0-9.:]*[a-zA-Z0-9_]+'
      minLength: 2
      maxLength: 128
    SourceType:
      type: string
      enum:
      - s3
      - iotsitewise
      - iottwinmaker
    State:
      type: string
      enum:
      - CREATING
      - UPDATING
      - DELETING
      - ACTIVE
      - ERROR
    String:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 256
    SyncJobState:
      type: string
      enum:
      - CREATING
      - INITIALIZING
      - ACTIVE
      - DELETING
      - ERROR
    SyncResourceState:
      type: string
      enum:
      - INITIALIZING
      - PROCESSING
      - DELETED
      - IN_SYNC
      - ERROR
    SyncResourceType:
      type: string
      enum:
      - ENTITY
      - COMPONENT_TYPE
    SyncSource:
      type: string
      pattern: ^[a-zA-Z_0-9]+$
    TagKey:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 256
    Time:
      type: string
      minLength: 20
      maxLength: 35
    TwinMakerArn:
      type: string
      pattern: ^arn:((aws)|(aws-cn)|(aws-us-gov)):iottwinmaker:[a-z0-9-]+:[0-9]{12}:[\/a-zA-Z0-9_\-\.:]+$
      minLength: 20
      maxLength: 2048
    Type:
      type: string
      enum:
      - RELATIONSHIP
      - STRING
      - LONG
      - BOOLEAN
      - INTEGER
      - DOUBLE
      - LIST
      - MAP
    UpdateReason:
      type: string
      enum:
      - DEFAULT
      - PRICING_TIER_UPDATE
      - ENTITY_COUNT_UPDATE
      - PRICING_MODE_UPDATE
      - OVERWRITTEN
    Uuid:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
      minLength: 36
      maxLength: 36
    Value:
      type: string
      pattern: .*
    WorkspaceDeleteMessage:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 2048
