openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: iottwinmaker
  x-aws-serviceName: iottwinmaker
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2021-11-29'
  title: AWS IoT TwinMaker
  description: |-
    IoT TwinMaker is a service with which you can build operational digital twins of physical systems. IoT TwinMaker overlays measurements and analysis from real-world sensors, cameras, and enterprise applications so you can create data visualizations to monitor your physical factory, building, or industrial plant. You can use this real-world data to monitor operations and diagnose and repair errors.
servers:
- description: The AWS IoT TwinMaker regional endpoint
  url: https://iottwinmaker.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Boolean:
      type: boolean
    BundleName:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 256
    ColumnDescriptions:
      type: array
      items:
        $ref: '#/components/schemas/ColumnDescription'
    ColumnName:
      type: string
      pattern: ^.*$
    ColumnType:
      type: string
      enum:
      - NODE
      - EDGE
      - VALUE
    ComponentPath:
      type: string
      pattern: ^[a-zA-Z_\-0-9/]+$
      minLength: 1
      maxLength: 2048
    ComponentPropertyGroupRequests:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ComponentPropertyGroupRequest'
    ComponentPropertyGroupResponses:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ComponentPropertyGroupResponse'
    ComponentSummaries:
      type: array
      items:
        $ref: '#/components/schemas/ComponentSummary'
    ComponentTypeId:
      type: string
      pattern: ^[a-zA-Z_\.\-0-9:]+$
      minLength: 1
      maxLength: 256
    ComponentTypeName:
      type: string
      pattern: '[^\u0000-\u001F\u007F]*'
      minLength: 0
      maxLength: 256
    ComponentTypeSummaries:
      type: array
      items:
        $ref: '#/components/schemas/ComponentTypeSummary'
    ComponentUpdateType:
      type: string
      enum:
      - CREATE
      - UPDATE
      - DELETE
    ComponentUpdatesMapRequest:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ComponentUpdateRequest'
    ComponentsMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ComponentResponse'
    ComponentsMapRequest:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ComponentRequest'
    CompositeComponentResponse:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ComponentSummary'
    CompositeComponentTypesRequest:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/CompositeComponentTypeRequest'
    CompositeComponentTypesResponse:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/CompositeComponentTypeResponse'
    CompositeComponentUpdatesMapRequest:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/CompositeComponentUpdateRequest'
    CompositeComponentsMapRequest:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/CompositeComponentRequest'
    Configuration:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Value'
    DataValueList:
      type: array
      items:
        $ref: '#/components/schemas/DataValue'
    DataValueMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/DataValue'
    Description:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 2048
    DestinationType:
      type: string
      enum:
      - s3
      - iotsitewise
      - iottwinmaker
    Double:
      type: number
      format: double
    EntityId:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|^[a-zA-Z0-9][a-zA-Z_\-0-9.:]*[a-zA-Z0-9]+$
      minLength: 1
      maxLength: 128
    EntityName:
      type: string
      pattern: ^[^\u0000-\u001F\u007F]+$
      minLength: 1
      maxLength: 256
    EntitySummaries:
      type: array
      items:
        $ref: '#/components/schemas/EntitySummary'
    Entries:
      type: array
      items:
        $ref: '#/components/schemas/PropertyValueEntry'
    ErrorCode:
      type: string
      enum:
      - VALIDATION_ERROR
      - INTERNAL_FAILURE
      - SYNC_INITIALIZING_ERROR
      - SYNC_CREATING_ERROR
      - SYNC_PROCESSING_ERROR
      - SYNC_DELETING_ERROR
      - PROCESSING_ERROR
      - COMPOSITE_COMPONENT_FAILURE
    ErrorEntries:
      type: array
      items:
        $ref: '#/components/schemas/BatchPutPropertyErrorEntry'
    ErrorMessage:
      type: string
      minLength: 0
      maxLength: 2048
    Errors:
      type: array
      items:
        $ref: '#/components/schemas/BatchPutPropertyError'
    ExceptionMessage:
      type: string
    Expression:
      type: string
      pattern: ^(^\$\{Parameters\.[a-zA-z]+([a-zA-z_0-9]*)}$)$
      minLength: 1
      maxLength: 316
    ExtendsFrom:
      type: array
      items:
        $ref: '#/components/schemas/ComponentTypeId'
    ExternalIdProperty:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    FunctionsRequest:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/FunctionRequest'
    FunctionsResponse:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/FunctionResponse'
    GeneratedSceneMetadataMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/SceneMetadataValue'
    GroupType:
      type: string
      enum:
      - TABULAR
    Id:
      type: string
      pattern: ^[a-zA-Z_0-9][a-zA-Z_\-0-9]*[a-zA-Z0-9]+$
      minLength: 1
      maxLength: 128
    IdOrArn:
      type: string
      pattern: ^[a-zA-Z_0-9][a-zA-Z_\-0-9]*[a-zA-Z0-9]+$|^arn:((aws)|(aws-cn)|(aws-us-gov)):iottwinmaker:[a-z0-9-]+:[0-9]{12}:[\/a-zA-Z0-9_-]+$
      minLength: 1
      maxLength: 2048
    Integer:
      type: integer
    InterpolationType:
      type: string
      enum:
      - LINEAR
    IntervalInSeconds:
      type: integer
      format: int64
    IotSiteWiseSourceConfigurationFilter:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/FilterByAssetModel'
        description: |-
          Filter by asset model.
      - allOf:
        - $ref: '#/components/schemas/FilterByAsset'
        description: |-
          Filter by asset.
      description: |-
        The AWS IoT SiteWise soucre configuration filter.[need held with desc here]
    IotSiteWiseSourceConfigurationFilters:
      type: array
      items:
        $ref: '#/components/schemas/IotSiteWiseSourceConfigurationFilter'
    IotTwinMakerSourceConfigurationFilter:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/FilterByComponentType'
        description: |-
          Filter by component type.
      - allOf:
        - $ref: '#/components/schemas/FilterByEntity'
        description: |-
          Filter by entity.
      description: |-
        The metadata transfer job AWS IoT TwinMaker source configuration filter.
    IotTwinMakerSourceConfigurationFilters:
      type: array
      items:
        $ref: '#/components/schemas/IotTwinMakerSourceConfigurationFilter'
    LambdaArn:
      type: string
      pattern: ^arn:((aws)|(aws-cn)|(aws-us-gov)):lambda:[a-z0-9-]+:[0-9]{12}:function:[\/a-zA-Z0-9_-]+$
      minLength: 20
      maxLength: 2048
    LinkedService:
      type: string
      pattern: ^[a-zA-Z_0-9]+$
    LinkedServices:
      type: array
      items:
        $ref: '#/components/schemas/LinkedService'
    ListComponentTypesFilter:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/ComponentTypeId'
        description: |-
          The component type that the component types in the list extend.
      - allOf:
        - $ref: '#/components/schemas/String'
        description: |-
          The namespace to which the component types in the list belong.
      - allOf:
        - $ref: '#/components/schemas/Boolean'
        description: |-
          A Boolean value that specifies whether the component types in the list are abstract.
      description: |-
        An object that filters items in a list of component types.

        Only one object is accepted as a valid input.
    ListComponentTypesFilters:
      type: array
      items:
        $ref: '#/components/schemas/ListComponentTypesFilter'
    ListEntitiesFilter:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/ParentEntityId'
        description: |-
          The parent of the entities in the list.
      - allOf:
        - $ref: '#/components/schemas/ComponentTypeId'
        description: |-
          The ID of the component type in the entities in the list.
      - allOf:
        - $ref: '#/components/schemas/String'
        description: |-
          The external-Id property of a component. The external-Id property is the primary key of an external storage system.
      description: |-
        An object that filters items in a list of entities.
    ListEntitiesFilters:
      type: array
      items:
        $ref: '#/components/schemas/ListEntitiesFilter'
    ListMetadataTransferJobsFilter:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/Id'
        description: |-
          The workspace Id.
      - allOf:
        - $ref: '#/components/schemas/MetadataTransferJobState'
        description: |-
          The filter state.
      description: |-
        The ListMetadataTransferJobs filter.
    ListMetadataTransferJobsFilters:
      type: array
      items:
        $ref: '#/components/schemas/ListMetadataTransferJobsFilter'
    Long:
      type: integer
      format: int64
    MaxResults:
      type: integer
      minimum: 0
      maximum: 200
    MetadataTransferJobState:
      type: string
      enum:
      - VALIDATING
      - PENDING
      - RUNNING
      - CANCELLING
      - ERROR
      - COMPLETED
      - CANCELLED
    MetadataTransferJobSummaries:
      type: array
      items:
        $ref: '#/components/schemas/MetadataTransferJobSummary'
    Name:
      type: string
      pattern: ^[a-zA-Z_\-0-9]+$
      minLength: 1
      maxLength: 256
    NextToken:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 17880
    Order:
      type: string
      enum:
      - ASCENDING
      - DESCENDING
    OrderByList:
      type: array
      items:
        $ref: '#/components/schemas/OrderBy'
    OrderByTime:
      type: string
      enum:
      - ASCENDING
      - DESCENDING
    ParentEntityId:
      type: string
      pattern: ^\$ROOT|^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|^[a-zA-Z0-9][a-zA-Z_\-0-9.:]*[a-zA-Z0-9]+$
      minLength: 1
      maxLength: 128
    ParentEntityUpdateType:
      type: string
      enum:
      - UPDATE
      - DELETE
    PricingBundles:
      type: array
      items:
        $ref: '#/components/schemas/BundleName'
    PricingMode:
      type: string
      enum:
      - BASIC
      - STANDARD
      - TIERED_BUNDLE
    PricingTier:
      type: string
      enum:
      - TIER_1
      - TIER_2
      - TIER_3
      - TIER_4
    PropertyDefinitionsRequest:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/PropertyDefinitionRequest'
    PropertyDefinitionsResponse:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/PropertyDefinitionResponse'
    PropertyDisplayName:
      type: string
      pattern: '[^\u0000-\u001F\u007F]*'
      minLength: 0
      maxLength: 256
    PropertyFilters:
      type: array
      items:
        $ref: '#/components/schemas/PropertyFilter'
    PropertyGroupUpdateType:
      type: string
      enum:
      - UPDATE
      - DELETE
      - CREATE
    PropertyGroupsRequest:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/PropertyGroupRequest'
    PropertyGroupsResponse:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/PropertyGroupResponse'
    PropertyLatestValueMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/PropertyLatestValue'
    PropertyNames:
      type: array
      items:
        $ref: '#/components/schemas/Name'
    PropertyRequests:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/PropertyRequest'
    PropertyResponses:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/PropertyResponse'
    PropertySummaries:
      type: array
      items:
        $ref: '#/components/schemas/PropertySummary'
    PropertyTableValue:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/DataValue'
    PropertyUpdateType:
      type: string
      enum:
      - UPDATE
      - DELETE
      - CREATE
      - RESET_VALUE
    PropertyValueList:
      type: array
      items:
        $ref: '#/components/schemas/PropertyValueHistory'
    PropertyValues:
      type: array
      items:
        $ref: '#/components/schemas/PropertyValue'
    QueryResultValue:
      type: object
      additionalProperties: true
    QueryServiceMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    QueryStatement:
      type: string
      pattern: ^[\s\S]+$
      minLength: 1
      maxLength: 1000
    RequiredProperties:
      type: array
      items:
        $ref: '#/components/schemas/Name'
    RoleArn:
      type: string
      pattern: ^arn:((aws)|(aws-cn)|(aws-us-gov)):iam::[0-9]{12}:role/
      minLength: 20
      maxLength: 2048
    RowData:
      type: array
      items:
        $ref: '#/components/schemas/QueryResultValue'
    Rows:
      type: array
      items:
        $ref: '#/components/schemas/Row'
    S3DestinationLocation:
      type: string
      pattern: (^arn:((aws)|(aws-cn)|(aws-us-gov)):s3:::)([/a-zA-Z0-9_-]+$)
    S3Location:
      type: string
      pattern: (^arn:((aws)|(aws-cn)|(aws-us-gov)):s3:::)([a-zA-Z0-9_-]+$)
      minLength: 0
      maxLength: 1024
    S3SourceLocation:
      type: string
      pattern: (^arn:((aws)|(aws-cn)|(aws-us-gov)):s3:::)([a-zA-Z0-9_-]+)\/([/.a-zA-Z0-9_-]+$)
    S3Url:
      type: string
      pattern: ^[sS]3://[A-Za-z0-9._/-]+$
      minLength: 0
      maxLength: 256
    SceneCapabilities:
      type: array
      items:
        $ref: '#/components/schemas/SceneCapability'
    SceneCapability:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 256
    SceneErrorCode:
      type: string
      enum:
      - MATTERPORT_ERROR
    SceneMetadataMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/SceneMetadataValue'
    SceneMetadataValue:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 2048
    SceneSummaries:
      type: array
      items:
        $ref: '#/components/schemas/SceneSummary'
    Scope:
      type: string
      enum:
      - ENTITY
      - WORKSPACE
    SelectedPropertyList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    SiteWiseExternalId:
      type: string
      pattern: '[a-zA-Z0-9_][a-zA-Z_\-0-9.:]*[a-zA-Z0-9_]+'
      minLength: 2
      maxLength: 128
    SourceConfigurations:
      type: array
      items:
        $ref: '#/components/schemas/SourceConfiguration'
    SourceType:
      type: string
      enum:
      - s3
      - iotsitewise
      - iottwinmaker
    State:
      type: string
      enum:
      - CREATING
      - UPDATING
      - DELETING
      - ACTIVE
      - ERROR
    String:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 256
    SyncJobState:
      type: string
      enum:
      - CREATING
      - INITIALIZING
      - ACTIVE
      - DELETING
      - ERROR
    SyncJobSummaries:
      type: array
      items:
        $ref: '#/components/schemas/SyncJobSummary'
    SyncResourceFilter:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/SyncResourceState'
        description: |-
          The sync resource filter's state.
      - allOf:
        - $ref: '#/components/schemas/SyncResourceType'
        description: |-
          The sync resource filter resource type
      - allOf:
        - $ref: '#/components/schemas/Id'
        description: |-
          The sync resource filter resource ID.
      - allOf:
        - $ref: '#/components/schemas/Id'
        description: |-
          The external ID.
      description: |-
        The sync resource filter.
    SyncResourceFilters:
      type: array
      items:
        $ref: '#/components/schemas/SyncResourceFilter'
    SyncResourceState:
      type: string
      enum:
      - INITIALIZING
      - PROCESSING
      - DELETED
      - IN_SYNC
      - ERROR
    SyncResourceSummaries:
      type: array
      items:
        $ref: '#/components/schemas/SyncResourceSummary'
    SyncResourceType:
      type: string
      enum:
      - ENTITY
      - COMPONENT_TYPE
    SyncSource:
      type: string
      pattern: ^[a-zA-Z_0-9]+$
    TabularPropertyValue:
      type: array
      items:
        $ref: '#/components/schemas/PropertyTableValue'
    TabularPropertyValues:
      type: array
      items:
        $ref: '#/components/schemas/TabularPropertyValue'
    TagKey:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 256
    Time:
      type: string
      minLength: 20
      maxLength: 35
    Timestamp:
      type: string
      format: date-time
      description: supports epoch seconds value
    TwinMakerArn:
      type: string
      pattern: ^arn:((aws)|(aws-cn)|(aws-us-gov)):iottwinmaker:[a-z0-9-]+:[0-9]{12}:[\/a-zA-Z0-9_\-\.:]+$
      minLength: 20
      maxLength: 2048
    Type:
      type: string
      enum:
      - RELATIONSHIP
      - STRING
      - LONG
      - BOOLEAN
      - INTEGER
      - DOUBLE
      - LIST
      - MAP
    UpdateReason:
      type: string
      enum:
      - DEFAULT
      - PRICING_TIER_UPDATE
      - ENTITY_COUNT_UPDATE
      - PRICING_MODE_UPDATE
      - OVERWRITTEN
    Uuid:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
      minLength: 36
      maxLength: 36
    Value:
      type: string
      pattern: .*
    Values:
      type: array
      items:
        $ref: '#/components/schemas/PropertyValue'
    WorkspaceDeleteMessage:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 2048
    WorkspaceSummaries:
      type: array
      items:
        $ref: '#/components/schemas/WorkspaceSummary'
