openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: ivs
  x-aws-serviceName: ivs
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-07-14'
  title: Amazon Interactive Video Service
  description: |-
    **Introduction**

    The Amazon Interactive Video Service (IVS) API is REST compatible, using a standard HTTP API and an Amazon Web Services EventBridge event stream for responses. JSON is used for both requests and responses, including errors.

    The API is an Amazon Web Services regional service. For a list of supported regions and Amazon IVS HTTPS service endpoints, see the [Amazon IVS page](https://docs.aws.amazon.com/general/latest/gr/ivs.html) in the _Amazon Web Services General Reference_.

    _**All API request parameters and URLs are case sensitive.** _

    For a summary of notable documentation changes in each release, see [ Document History](https://docs.aws.amazon.com/ivs/latest/userguide/doc-history.html).

    **Allowed Header Values**

      * ` **Accept:** ` application/json

      * ` **Accept-Encoding:** ` gzip, deflate

      * ` **Content-Type:** `application/json

    **Key Concepts**

      * **Channel** — Stores configuration data related to your live stream. You first create a channel and then use the channel’s stream key to start your live stream.

      * **Stream key** — An identifier assigned by Amazon IVS when you create a channel, which is then used to authorize streaming. _**Treat the stream key like a secret, since it allows anyone to stream to the channel.** _

      * **Playback key pair** — Video playback may be restricted using playback-authorization tokens, which use public-key encryption. A playback key pair is the public-private pair of keys used to sign and validate the playback-authorization token.

      * **Recording configuration** — Stores configuration related to recording a live stream and where to store the recorded content. Multiple channels can reference the same recording configuration.

      * **Playback restriction policy** — Restricts playback by countries and/or origin sites.

    For more information about your IVS live stream, also see [Getting Started with IVS Low-Latency Streaming](https://docs.aws.amazon.com/ivs/latest/LowLatencyUserGuide/getting-started.html).

    **Tagging**

    A _tag_ is a metadata label that you assign to an Amazon Web Services resource. A tag comprises a _key_ and a _value_ , both set by you. For example, you might set a tag as `topic:nature` to label a particular video category. See [Best practices and strategies](https://docs.aws.amazon.com/tag-editor/latest/userguide/best-practices-and-strats.html) in _Tagging Amazon Web Services Resources and Tag Editor_ for details, including restrictions that apply to tags and "Tag naming limits and requirements"; Amazon IVS has no service-specific constraints beyond what is documented there.

    Tags can help you identify and organize your Amazon Web Services resources. For example, you can use the same tag for different resources to indicate that they are related. You can also use tags to manage access (see [ Access Tags](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_tags.html)).

    The Amazon IVS API has these tag-related operations: TagResource, UntagResource, and ListTagsForResource. The following resources support tagging: Channels, Stream Keys, Playback Key Pairs, and Recording Configurations.

    At most 50 tags can be applied to a resource.

    **Authentication versus Authorization**

    Note the differences between these concepts:

      * _Authentication_ is about verifying identity. You need to be authenticated to sign Amazon IVS API requests.

      * _Authorization_ is about granting permissions. Your IAM roles need to have permissions for Amazon IVS API requests. In addition, authorization is needed to view [Amazon IVS private channels](https://docs.aws.amazon.com/ivs/latest/userguide/private-channels.html). (Private channels are channels that are enabled for "playback authorization.")

    **Authentication**

    All Amazon IVS API requests must be authenticated with a signature. The Amazon Web Services Command-Line Interface (CLI) and Amazon IVS Player SDKs take care of signing the underlying API calls for you. However, if your application calls the Amazon IVS API directly, it’s your responsibility to sign the requests.

    You generate a signature using valid Amazon Web Services credentials that have permission to perform the requested action. For example, you must sign PutMetadata requests with a signature generated from a user account that has the `ivs:PutMetadata` permission.

    For more information:

      * Authentication and generating signatures — See [Authenticating Requests (Amazon Web Services Signature Version 4)](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html) in the _Amazon Web Services General Reference_.

      * Managing Amazon IVS permissions — See [Identity and Access Management](https://docs.aws.amazon.com/ivs/latest/userguide/security-iam.html) on the Security page of the _Amazon IVS User Guide_.

    **Amazon Resource Names (ARNs)**

    ARNs uniquely identify AWS resources. An ARN is required when you need to specify a resource unambiguously across all of AWS, such as in IAM policies and API calls. For more information, see [Amazon Resource Names](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html) in the _AWS General Reference_.
servers:
- description: The Amazon Interactive Video Service regional endpoint
  url: https://ivs.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Boolean:
      type: boolean
      default: false
    ChannelArn:
      type: string
      pattern: ^arn:aws:ivs:[a-z0-9-]+:[0-9]+:channel/[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 128
    ChannelLatencyMode:
      type: string
      enum:
      - NORMAL
      - LOW
    ChannelName:
      type: string
      pattern: ^[a-zA-Z0-9-_]*$
      minLength: 0
      maxLength: 128
    ChannelPlaybackRestrictionPolicyArn:
      type: string
      pattern: ^^$|^arn:aws:ivs:[a-z0-9-]+:[0-9]+:playback-restriction-policy/[a-zA-Z0-9-]+$$
      minLength: 0
      maxLength: 128
    ChannelRecordingConfigurationArn:
      type: string
      pattern: ^^$|^arn:aws:ivs:[a-z0-9-]+:[0-9]+:recording-configuration/[a-zA-Z0-9-]+$$
      minLength: 0
      maxLength: 128
    ContainerFormat:
      type: string
      enum:
      - TS
      - FRAGMENTED_MP4
    IngestEndpoint:
      type: string
    InsecureIngest:
      type: boolean
      default: false
    IsAuthorized:
      type: boolean
      default: false
    IsMultitrackInputEnabled:
      type: boolean
      default: false
    MaxChannelResults:
      type: integer
      minimum: 1
      maximum: 100
    MaxPlaybackKeyPairResults:
      type: integer
      minimum: 1
      maximum: 100
    MaxPlaybackRestrictionPolicyResults:
      type: integer
      minimum: 1
      maximum: 100
    MaxRecordingConfigurationResults:
      type: integer
      minimum: 1
      maximum: 100
    MaxStreamKeyResults:
      type: integer
      minimum: 1
      maximum: 50
    MaxStreamResults:
      type: integer
      minimum: 1
      maximum: 100
    PaginationToken:
      type: string
      pattern: ^[a-zA-Z0-9+/=_-]*$
      minLength: 0
      maxLength: 1024
    PlaybackKeyPairArn:
      type: string
      pattern: ^arn:aws:ivs:[a-z0-9-]+:[0-9]+:playback-key/[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 128
    PlaybackKeyPairFingerprint:
      type: string
    PlaybackKeyPairName:
      type: string
      pattern: ^[a-zA-Z0-9-_]*$
      minLength: 0
      maxLength: 128
    PlaybackPublicKeyMaterial:
      type: string
    PlaybackRestrictionPolicyAllowedCountry:
      type: string
      minLength: 2
      maxLength: 2
    PlaybackRestrictionPolicyAllowedOrigin:
      type: string
      minLength: 0
      maxLength: 128
    PlaybackRestrictionPolicyArn:
      type: string
      pattern: ^arn:aws:ivs:[a-z0-9-]+:[0-9]+:playback-restriction-policy/[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 128
    PlaybackRestrictionPolicyEnableStrictOriginEnforcement:
      type: boolean
    PlaybackRestrictionPolicyName:
      type: string
      pattern: ^[a-zA-Z0-9-_]*$
      minLength: 0
      maxLength: 128
    PlaybackURL:
      type: string
    RecordingConfigurationArn:
      type: string
      pattern: ^arn:aws:ivs:[a-z0-9-]+:[0-9]+:recording-configuration/[a-zA-Z0-9-]+$
      minLength: 0
      maxLength: 128
    RecordingConfigurationName:
      type: string
      pattern: ^[a-zA-Z0-9-_]*$
      minLength: 0
      maxLength: 128
    RecordingConfigurationState:
      type: string
      enum:
      - CREATING
      - CREATE_FAILED
      - ACTIVE
    RecordingMode:
      type: string
      enum:
      - DISABLED
      - INTERVAL
    RecordingReconnectWindowSeconds:
      type: integer
      default: 0
      minimum: 0
      maximum: 300
    RenditionConfigurationRenditionSelection:
      type: string
      enum:
      - ALL
      - NONE
      - CUSTOM
    ResourceArn:
      type: string
      pattern: ^arn:aws:ivs:[a-z0-9-]+:[0-9]+:[a-z-]/[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 128
    S3DestinationBucketName:
      type: string
      pattern: ^[a-z0-9-.]+$
      minLength: 3
      maxLength: 63
    SrtEndpoint:
      type: string
    SrtPassphrase:
      type: string
    StreamHealth:
      type: string
      enum:
      - HEALTHY
      - STARVING
      - UNKNOWN
    StreamId:
      type: string
      pattern: ^st-[a-zA-Z0-9]+$
      minLength: 26
      maxLength: 26
    StreamKeyArn:
      type: string
      pattern: ^arn:aws:ivs:[a-z0-9-]+:[0-9]+:stream-key/[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 128
    StreamKeyValue:
      type: string
    StreamMetadata:
      type: string
      minLength: 1
    StreamState:
      type: string
      enum:
      - LIVE
      - OFFLINE
    String:
      type: string
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      maxLength: 256
    ThumbnailConfigurationStorage:
      type: string
      enum:
      - SEQUENTIAL
      - LATEST
    ViewerId:
      type: string
      minLength: 1
      maxLength: 40
    ViewerSessionVersion:
      type: integer
      default: 0
      minimum: 0
    errorCode:
      type: string
    errorMessage:
      type: string
