openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: kafkaconnect
  x-aws-serviceName: kafkaconnect
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2021-09-14'
  title: Managed Streaming for Kafka Connect
  description: ""
servers:
- description: The Managed Streaming for Kafka Connect regional endpoint
  url: https://kafkaconnect.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ConnectorConfiguration:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/__string'
    ConnectorConfigurationUpdate:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/__string'
    ConnectorOperationState:
      type: string
      enum:
      - PENDING
      - UPDATE_IN_PROGRESS
      - UPDATE_COMPLETE
      - UPDATE_FAILED
      - ROLLBACK_IN_PROGRESS
      - ROLLBACK_FAILED
      - ROLLBACK_COMPLETE
    ConnectorOperationStepState:
      type: string
      enum:
      - PENDING
      - IN_PROGRESS
      - COMPLETED
      - FAILED
      - CANCELLED
    ConnectorOperationStepType:
      type: string
      enum:
      - INITIALIZE_UPDATE
      - FINALIZE_UPDATE
      - UPDATE_WORKER_SETTING
      - UPDATE_CONNECTOR_CONFIGURATION
      - VALIDATE_UPDATE
    ConnectorOperationType:
      type: string
      enum:
      - UPDATE_WORKER_SETTING
      - UPDATE_CONNECTOR_CONFIGURATION
      - ISOLATE_CONNECTOR
      - RESTORE_CONNECTOR
    ConnectorState:
      type: string
      enum:
      - RUNNING
      - CREATING
      - UPDATING
      - DELETING
      - FAILED
    CustomPluginContentType:
      type: string
      enum:
      - JAR
      - ZIP
    CustomPluginState:
      type: string
      enum:
      - CREATING
      - CREATE_FAILED
      - ACTIVE
      - UPDATING
      - UPDATE_FAILED
      - DELETING
    KafkaClusterClientAuthenticationType:
      type: string
      enum:
      - NONE
      - IAM
    KafkaClusterEncryptionInTransitType:
      type: string
      enum:
      - PLAINTEXT
      - TLS
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    Tags:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    WorkerConfigurationState:
      type: string
      enum:
      - ACTIVE
      - DELETING
    __boolean:
      type: boolean
      default: false
    __integer:
      type: integer
      default: 0
    __integerMin1Max100:
      type: integer
      default: 0
      minimum: 1
      maximum: 100
    __integerMin1Max8:
      type: integer
      default: 0
      minimum: 1
      maximum: 8
    __listOfConnectorOperationStep:
      type: array
      items:
        $ref: '#/components/schemas/ConnectorOperationStep'
    __listOfConnectorOperationSummary:
      type: array
      items:
        $ref: '#/components/schemas/ConnectorOperationSummary'
    __listOfConnectorSummary:
      type: array
      items:
        $ref: '#/components/schemas/ConnectorSummary'
    __listOfCustomPluginSummary:
      type: array
      items:
        $ref: '#/components/schemas/CustomPluginSummary'
    __listOfPlugin:
      type: array
      items:
        $ref: '#/components/schemas/Plugin'
    __listOfPluginDescription:
      type: array
      items:
        $ref: '#/components/schemas/PluginDescription'
    __listOfWorkerConfigurationSummary:
      type: array
      items:
        $ref: '#/components/schemas/WorkerConfigurationSummary'
    __listOf__string:
      type: array
      items:
        $ref: '#/components/schemas/__string'
    __long:
      type: integer
      format: int64
      default: 0
    __longMin1:
      type: integer
      format: int64
      default: 0
      minimum: 1
      maximum: 9223372036854775807
    __sensitiveString:
      type: string
    __string:
      type: string
    __stringMax1024:
      type: string
      minLength: 0
      maxLength: 1024
    __stringMin1Max128:
      type: string
      minLength: 1
      maxLength: 128
    __timestampIso8601:
      type: string
      format: date-time
