openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: kafka
  x-aws-serviceName: kafka
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-11-14'
  title: Managed Streaming for Kafka
  description: |-
    The operations for managing an Amazon MSK cluster.
servers:
- description: The Managed Streaming for Kafka regional endpoint
  url: https://kafka.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    __boolean:
      type: boolean
    __integer:
      type: integer
    __integerMin1Max15:
      type: integer
      minimum: 1
      maximum: 15
    __integerMin1Max16384:
      type: integer
      minimum: 1
      maximum: 16384
    __string:
      type: string
    __stringMax1024:
      type: string
      minLength: 0
      maxLength: 1024
    __stringMax249:
      type: string
      minLength: 0
      maxLength: 249
    __stringMax256:
      type: string
      minLength: 0
      maxLength: 256
    __stringMin1Max128:
      type: string
      minLength: 1
      maxLength: 128
    __stringMin1Max128Pattern09AZaZ09AZaZ0:
      type: string
      pattern: ^[0-9A-Za-z][0-9A-Za-z-]{0,}$
      minLength: 1
      maxLength: 128
    __stringMin1Max64:
      type: string
      minLength: 1
      maxLength: 64
    __stringMin5Max32:
      type: string
      minLength: 5
      maxLength: 32
