openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: kafka
  x-aws-serviceName: kafka
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-11-14'
  title: Managed Streaming for Kafka
  description: |-
    The operations for managing an Amazon MSK cluster.
servers:
- description: The Managed Streaming for Kafka regional endpoint
  url: https://kafka.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    BrokerAZDistribution:
      type: string
      enum:
      - DEFAULT
      description: "<p>The distribution of broker nodes across Availability Zones.\
        \ This is an optional parameter. If you don't specify it, Amazon MSK gives\
        \ it the value DEFAULT. You can also explicitly set this parameter to the\
        \ value DEFAULT. No other values are currently allowed.</p>\n         <p>Amazon\
        \ MSK distributes the broker nodes evenly across the Availability Zones that\
        \ correspond to the subnets you provide when you create the cluster.</p>"
    ClientBroker:
      type: string
      enum:
      - TLS
      - TLS_PLAINTEXT
      - PLAINTEXT
      description: <p>Client-broker encryption in transit setting.</p>
    ClusterState:
      type: string
      enum:
      - ACTIVE
      - CREATING
      - DELETING
      - FAILED
      - HEALING
      - MAINTENANCE
      - REBOOTING_BROKER
      - UPDATING
      description: <p>The state of the Apache Kafka cluster.</p>
    ClusterType:
      type: string
      enum:
      - PROVISIONED
      - SERVERLESS
      description: <p>The type of cluster.</p>
    ConfigurationState:
      type: string
      enum:
      - ACTIVE
      - DELETING
      - DELETE_FAILED
      description: <p>The state of a configuration.</p>
    CustomerActionStatus:
      type: string
      enum:
      - CRITICAL_ACTION_REQUIRED
      - ACTION_RECOMMENDED
      - NONE
      description: <p>A type of an action required from the customer.</p>
    EnhancedMonitoring:
      type: string
      enum:
      - DEFAULT
      - PER_BROKER
      - PER_TOPIC_PER_BROKER
      - PER_TOPIC_PER_PARTITION
      description: '<p>Specifies which metrics are gathered for the MSK cluster. This
        property has the following possible values: DEFAULT, PER_BROKER, PER_TOPIC_PER_BROKER,
        and PER_TOPIC_PER_PARTITION. For a list of the metrics associated with each
        of these levels of monitoring, see <a href="https://docs.aws.amazon.com/msk/latest/developerguide/monitoring.html">Monitoring</a>.</p>'
    KafkaVersionStatus:
      type: string
      enum:
      - ACTIVE
      - DEPRECATED
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    NodeType:
      type: string
      enum:
      - BROKER
      description: <p>The broker or Zookeeper node.</p>
    ReplicationStartingPositionType:
      type: string
      enum:
      - LATEST
      - EARLIEST
      description: <p>The type of replication starting position.</p>
    ReplicationTopicNameConfigurationType:
      type: string
      enum:
      - PREFIXED_WITH_SOURCE_CLUSTER_ALIAS
      - IDENTICAL
      description: <p>The type of replicated topic name.</p>
    ReplicatorState:
      type: string
      enum:
      - RUNNING
      - CREATING
      - UPDATING
      - DELETING
      - FAILED
      description: <p>The state of a replicator.</p>
    StorageMode:
      type: string
      enum:
      - LOCAL
      - TIERED
      description: Controls storage mode for various supported storage tiers.
    TargetCompressionType:
      type: string
      enum:
      - NONE
      - GZIP
      - SNAPPY
      - LZ4
      - ZSTD
      description: <p>The type of compression to use producing records to the target
        cluster.</p>
    UserIdentityType:
      type: string
      enum:
      - AWSACCOUNT
      - AWSSERVICE
      description: <p>The identity type of the requester that calls the API operation.</p>
    VpcConnectionState:
      type: string
      enum:
      - CREATING
      - AVAILABLE
      - INACTIVE
      - DEACTIVATING
      - DELETING
      - FAILED
      - REJECTED
      - REJECTING
      description: <p>The state of a VPC connection.</p>
    __blob:
      type: string
      format: byte
    __boolean:
      type: boolean
    __double:
      type: number
      format: double
    __integer:
      type: integer
    __integerMin1Max15:
      type: integer
      minimum: 1
      maximum: 15
    __integerMin1Max16384:
      type: integer
      minimum: 1
      maximum: 16384
    __listOfBrokerEBSVolumeInfo:
      type: array
      items:
        $ref: '#/components/schemas/BrokerEBSVolumeInfo'
    __listOfClientVpcConnection:
      type: array
      items:
        $ref: '#/components/schemas/ClientVpcConnection'
    __listOfCluster:
      type: array
      items:
        $ref: '#/components/schemas/Cluster'
    __listOfClusterInfo:
      type: array
      items:
        $ref: '#/components/schemas/ClusterInfo'
    __listOfClusterOperationInfo:
      type: array
      items:
        $ref: '#/components/schemas/ClusterOperationInfo'
    __listOfClusterOperationStep:
      type: array
      items:
        $ref: '#/components/schemas/ClusterOperationStep'
    __listOfClusterOperationV2Summary:
      type: array
      items:
        $ref: '#/components/schemas/ClusterOperationV2Summary'
    __listOfCompatibleKafkaVersion:
      type: array
      items:
        $ref: '#/components/schemas/CompatibleKafkaVersion'
    __listOfConfiguration:
      type: array
      items:
        $ref: '#/components/schemas/Configuration'
    __listOfConfigurationRevision:
      type: array
      items:
        $ref: '#/components/schemas/ConfigurationRevision'
    __listOfKafkaCluster:
      type: array
      items:
        $ref: '#/components/schemas/KafkaCluster'
    __listOfKafkaClusterDescription:
      type: array
      items:
        $ref: '#/components/schemas/KafkaClusterDescription'
    __listOfKafkaClusterSummary:
      type: array
      items:
        $ref: '#/components/schemas/KafkaClusterSummary'
    __listOfKafkaVersion:
      type: array
      items:
        $ref: '#/components/schemas/KafkaVersion'
    __listOfNodeInfo:
      type: array
      items:
        $ref: '#/components/schemas/NodeInfo'
    __listOfReplicationInfo:
      type: array
      items:
        $ref: '#/components/schemas/ReplicationInfo'
    __listOfReplicationInfoDescription:
      type: array
      items:
        $ref: '#/components/schemas/ReplicationInfoDescription'
    __listOfReplicationInfoSummary:
      type: array
      items:
        $ref: '#/components/schemas/ReplicationInfoSummary'
    __listOfReplicatorSummary:
      type: array
      items:
        $ref: '#/components/schemas/ReplicatorSummary'
    __listOfUnprocessedScramSecret:
      type: array
      items:
        $ref: '#/components/schemas/UnprocessedScramSecret'
    __listOfVpcConfig:
      type: array
      items:
        $ref: '#/components/schemas/VpcConfig'
    __listOfVpcConnection:
      type: array
      items:
        $ref: '#/components/schemas/VpcConnection'
    __listOf__double:
      type: array
      items:
        $ref: '#/components/schemas/__double'
    __listOf__string:
      type: array
      items:
        $ref: '#/components/schemas/__string'
    __listOf__stringMax249:
      type: array
      items:
        $ref: '#/components/schemas/__stringMax249'
    __listOf__stringMax256:
      type: array
      items:
        $ref: '#/components/schemas/__stringMax256'
    __long:
      type: integer
      format: int64
    __mapOf__string:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/__string'
    __string:
      type: string
    __stringMax1024:
      type: string
      minLength: 0
      maxLength: 1024
    __stringMax249:
      type: string
      minLength: 0
      maxLength: 249
    __stringMax256:
      type: string
      minLength: 0
      maxLength: 256
    __stringMin1Max128:
      type: string
      minLength: 1
      maxLength: 128
    __stringMin1Max128Pattern09AZaZ09AZaZ0:
      type: string
      pattern: ^[0-9A-Za-z][0-9A-Za-z-]{0,}$
      minLength: 1
      maxLength: 128
    __stringMin1Max64:
      type: string
      minLength: 1
      maxLength: 64
    __stringMin5Max32:
      type: string
      minLength: 5
      maxLength: 32
    __timestampIso8601:
      type: string
      format: date-time
