openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: kinesis_video_archived_media
  x-aws-serviceName: kinesisvideoarchivedmedia
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-09-30'
  title: Amazon Kinesis Video Streams Archived Media
  description: ""
servers:
- description: The Amazon Kinesis Video Streams Archived Media regional endpoint
  url: https://kinesisvideo.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ClipFragmentSelectorType:
      type: string
      enum:
      - PRODUCER_TIMESTAMP
      - SERVER_TIMESTAMP
    ContainerFormat:
      type: string
      enum:
      - FRAGMENTED_MP4
      - MPEG_TS
    ContentType:
      type: string
      pattern: ^[a-zA-Z0-9_\.\-]+$
      minLength: 1
      maxLength: 128
    DASHDisplayFragmentNumber:
      type: string
      enum:
      - ALWAYS
      - NEVER
    DASHDisplayFragmentTimestamp:
      type: string
      enum:
      - ALWAYS
      - NEVER
    DASHFragmentSelectorType:
      type: string
      enum:
      - PRODUCER_TIMESTAMP
      - SERVER_TIMESTAMP
    DASHMaxResults:
      type: integer
      format: int64
      minimum: 1
      maximum: 5000
    DASHPlaybackMode:
      type: string
      enum:
      - LIVE
      - LIVE_REPLAY
      - ON_DEMAND
    DASHStreamingSessionURL:
      type: string
    ErrorMessage:
      type: string
    Expires:
      type: integer
      minimum: 300
      maximum: 43200
    Format:
      type: string
      enum:
      - JPEG
      - PNG
    FormatConfig:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/FormatConfigValue'
    FormatConfigKey:
      type: string
      enum:
      - JPEGQuality
    FormatConfigValue:
      type: string
      pattern: ^[a-zA-Z_0-9]+$
      minLength: 0
      maxLength: 256
    FragmentList:
      type: array
      items:
        $ref: '#/components/schemas/Fragment'
    FragmentNumberList:
      type: array
      items:
        $ref: '#/components/schemas/FragmentNumberString'
    FragmentNumberString:
      type: string
      pattern: ^[0-9]+$
      minLength: 1
      maxLength: 128
    FragmentSelectorType:
      type: string
      enum:
      - PRODUCER_TIMESTAMP
      - SERVER_TIMESTAMP
    GetImagesMaxResults:
      type: integer
      format: int64
      minimum: 1
      maximum: 100
    HLSDiscontinuityMode:
      type: string
      enum:
      - ALWAYS
      - NEVER
      - ON_DISCONTINUITY
    HLSDisplayFragmentTimestamp:
      type: string
      enum:
      - ALWAYS
      - NEVER
    HLSFragmentSelectorType:
      type: string
      enum:
      - PRODUCER_TIMESTAMP
      - SERVER_TIMESTAMP
    HLSMaxResults:
      type: integer
      format: int64
      minimum: 1
      maximum: 5000
    HLSPlaybackMode:
      type: string
      enum:
      - LIVE
      - LIVE_REPLAY
      - ON_DEMAND
    HLSStreamingSessionURL:
      type: string
    HeightPixels:
      type: integer
      minimum: 1
      maximum: 2160
    ImageContent:
      type: string
      minLength: 1
      maxLength: 6291456
    ImageError:
      type: string
      enum:
      - NO_MEDIA
      - MEDIA_ERROR
    ImageSelectorType:
      type: string
      enum:
      - PRODUCER_TIMESTAMP
      - SERVER_TIMESTAMP
    Images:
      type: array
      items:
        $ref: '#/components/schemas/Image'
    ListFragmentsMaxResults:
      type: integer
      format: int64
      minimum: 1
      maximum: 1000
    Long:
      type: integer
      format: int64
      default: 0
    NextToken:
      type: string
      pattern: ^[a-zA-Z0-9+/]+={0,2}$
      minLength: 1
      maxLength: 4096
    Payload:
      type: string
      format: byte
    ResourceARN:
      type: string
      pattern: ^arn:[a-z\d-]+:kinesisvideo:[a-z0-9-]+:[0-9]+:[a-z]+/[a-zA-Z0-9_.-]+/[0-9]+$
      minLength: 1
      maxLength: 1024
    SamplingInterval:
      type: integer
    StreamName:
      type: string
      pattern: ^[a-zA-Z0-9_.-]+$
      minLength: 1
      maxLength: 256
    Timestamp:
      type: string
      format: date-time
    WidthPixels:
      type: integer
      minimum: 1
      maximum: 3840
