openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: kinesis_video_archived_media
  x-aws-serviceName: kinesisvideoarchivedmedia
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-09-30'
  title: Amazon Kinesis Video Streams Archived Media
  description: ""
servers:
- description: The Amazon Kinesis Video Streams Archived Media regional endpoint
  url: https://kinesisvideo.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ContentType:
      type: string
      pattern: ^[a-zA-Z0-9_\.\-]+$
      minLength: 1
      maxLength: 128
    DASHStreamingSessionURL:
      type: string
    ErrorMessage:
      type: string
    Expires:
      type: integer
      minimum: 300
      maximum: 43200
    FormatConfigValue:
      type: string
      pattern: ^[a-zA-Z_0-9]+$
      minLength: 0
      maxLength: 256
    FragmentNumberString:
      type: string
      pattern: ^[0-9]+$
      minLength: 1
      maxLength: 128
    HLSStreamingSessionURL:
      type: string
    HeightPixels:
      type: integer
      minimum: 1
      maximum: 2160
    ImageContent:
      type: string
      minLength: 1
      maxLength: 6291456
    NextToken:
      type: string
      pattern: ^[a-zA-Z0-9+/]+={0,2}$
      minLength: 1
      maxLength: 4096
    ResourceARN:
      type: string
      pattern: ^arn:[a-z\d-]+:kinesisvideo:[a-z0-9-]+:[0-9]+:[a-z]+/[a-zA-Z0-9_.-]+/[0-9]+$
      minLength: 1
      maxLength: 1024
    SamplingInterval:
      type: integer
    StreamName:
      type: string
      pattern: ^[a-zA-Z0-9_.-]+$
      minLength: 1
      maxLength: 256
    WidthPixels:
      type: integer
      minimum: 1
      maximum: 3840
