openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: kinesis_video
  x-aws-serviceName: kinesisvideo
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-09-30'
  title: Amazon Kinesis Video Streams
  description: ""
servers:
- description: The Amazon Kinesis Video Streams regional endpoint
  url: https://kinesisvideo.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ChannelName:
      type: string
      pattern: ^[a-zA-Z0-9_.-]+$
      minLength: 1
      maxLength: 256
    DataEndpoint:
      type: string
    DataRetentionChangeInHours:
      type: integer
      minimum: 1
    DataRetentionInHours:
      type: integer
      minimum: 0
    DeleteAfterUpload:
      type: boolean
    DestinationRegion:
      type: string
      pattern: ^[a-z]+(-[a-z]+)?-[a-z]+-[0-9]$
      minLength: 9
      maxLength: 14
    DestinationUri:
      type: string
      pattern: ^[a-zA-Z_0-9]+:(//)?([^/]+)/?([^*]*)$
      minLength: 1
      maxLength: 255
    DeviceName:
      type: string
      pattern: ^[a-zA-Z0-9_.-]+$
      minLength: 1
      maxLength: 128
    DurationInSeconds:
      type: integer
      minimum: 60
      maximum: 3600
    EdgeRetentionInHours:
      type: integer
      minimum: 1
      maximum: 720
    ErrorMessage:
      type: string
    FailedStatusDetails:
      type: string
    FormatConfigValue:
      type: string
      pattern: ^[a-zA-Z_0-9]+$
      minLength: 0
      maxLength: 256
    HeightPixels:
      type: integer
      minimum: 1
      maximum: 2160
    HubDeviceArn:
      type: string
      pattern: ^arn:[a-z\d-]+:iot:[a-z0-9-]+:[0-9]+:thing/[a-zA-Z0-9_.-]+$
      minLength: 1
      maxLength: 1024
    JobStatusDetails:
      type: string
    KmsKeyId:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 2048
    ListEdgeAgentConfigurationsInputLimit:
      type: integer
      minimum: 1
      maximum: 10
    ListStreamsInputLimit:
      type: integer
      minimum: 1
      maximum: 10000
    MappedResourceConfigurationListLimit:
      type: integer
      minimum: 1
      maximum: 1
    MaxLocalMediaSizeInMB:
      type: integer
      minimum: 64
      maximum: 2000000
    MediaType:
      type: string
      pattern: ^[\w\-\.\+]+/[\w\-\.\+]+(,[\w\-\.\+]+/[\w\-\.\+]+)*$
      minLength: 1
      maxLength: 128
    MediaUriSecretArn:
      type: string
      pattern: ^arn:[a-z\d-]+:secretsmanager:[a-z0-9-]+:[0-9]+:secret:[a-zA-Z0-9_.-]+$
      minLength: 20
      maxLength: 2048
    MessageTtlSeconds:
      type: integer
      minimum: 5
      maximum: 120
    NextToken:
      type: string
      pattern: ^[a-zA-Z0-9+/=]*$
      minLength: 0
      maxLength: 1024
    ResourceARN:
      type: string
      pattern: ^arn:[a-z\d-]+:kinesisvideo:[a-z0-9-]+:[0-9]+:[a-z]+/[a-zA-Z0-9_.-]+/[0-9]+$
      minLength: 1
      maxLength: 1024
    ResourceEndpoint:
      type: string
    SamplingInterval:
      type: integer
    ScheduleExpression:
      type: string
      pattern: ^[^\n]{11,100}$
      minLength: 11
      maxLength: 100
    StreamName:
      type: string
      pattern: ^[a-zA-Z0-9_.-]+$
      minLength: 1
      maxLength: 256
    TagKey:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^[\p{L}\p{Z}\p{N}_.:/=+\-@]*$
      minLength: 0
      maxLength: 256
    Type:
      type: string
    Version:
      type: string
      pattern: ^[a-zA-Z0-9]+$
      minLength: 1
      maxLength: 64
    WidthPixels:
      type: integer
      minimum: 1
      maximum: 3840
