openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: lakeformation
  x-aws-serviceName: lakeformation
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-03-31'
  title: AWS Lake Formation
  description: |-
    Lake Formation

    Defines the public endpoint for the Lake Formation service.
servers:
- description: The AWS Lake Formation regional endpoint
  url: https://lakeformation.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccessKeyIdString:
      type: string
    ApplicationArn:
      type: string
    AuditContextString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 0
      maxLength: 2048
    Boolean:
      type: boolean
      default: false
    BooleanNullable:
      type: boolean
    CatalogIdString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 1
      maxLength: 255
    ContextKey:
      type: string
      minLength: 1
      maxLength: 128
    ContextValue:
      type: string
      minLength: 0
      maxLength: 256
    CredentialTimeoutDurationSecondInteger:
      type: integer
      minimum: 900
      maximum: 43200
    DataLakePrincipalString:
      type: string
      minLength: 1
      maxLength: 255
    DescriptionString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*$
      minLength: 0
      maxLength: 2048
    ETagString:
      type: string
      pattern: ^[\p{L}\p{N}\p{P}]*$
      minLength: 1
      maxLength: 255
    ErrorMessageString:
      type: string
    ExpressionString:
      type: string
      minLength: 0
      maxLength: 3000
    GetQueryStateRequestQueryIdString:
      type: string
      minLength: 36
      maxLength: 36
    GetQueryStatisticsRequestQueryIdString:
      type: string
      minLength: 36
      maxLength: 36
    GetWorkUnitResultsRequestQueryIdString:
      type: string
      minLength: 36
      maxLength: 36
    GetWorkUnitsRequestQueryIdString:
      type: string
      minLength: 36
      maxLength: 36
    HashString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 1
      maxLength: 255
    IAMRoleArn:
      type: string
      pattern: ^arn:aws:iam::[0-9]*:role/
    IAMSAMLProviderArn:
      type: string
      pattern: ^arn:aws:iam::[0-9]*:saml-provider/
    Identifier:
      type: string
      minLength: 1
      maxLength: 255
    IdentityCenterInstanceArn:
      type: string
    IdentityString:
      type: string
    KeyString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 1
      maxLength: 255
    LFTagKey:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:\/=+\-@%]*)$
      minLength: 1
      maxLength: 128
    LFTagValue:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:\*\/=+\-@%]*)$
      minLength: 0
      maxLength: 256
    MessageString:
      type: string
    NameString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 1
      maxLength: 255
    NullableBoolean:
      type: boolean
    NullableString:
      type: string
    PageSize:
      type: integer
      minimum: 1
      maximum: 1000
    ParametersMapValue:
      type: string
      minLength: 0
      maxLength: 512000
    PartitionValueString:
      type: string
      minLength: 0
      maxLength: 1024
    PathString:
      type: string
    PredicateString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*$
      minLength: 0
      maxLength: 2048
    QueryIdString:
      type: string
    QueryPlanningContextDatabaseNameString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 1
    RAMResourceShareArn:
      type: string
    ResourceArnString:
      type: string
    Result:
      type: string
    SAMLAssertionString:
      type: string
      minLength: 4
      maxLength: 100000
    ScopeTarget:
      type: string
    SearchPageSize:
      type: integer
      minimum: 1
      maximum: 100
    SecretAccessKeyString:
      type: string
    SessionTokenString:
      type: string
    StorageOptimizerConfigKey:
      type: string
    StorageOptimizerConfigValue:
      type: string
    StringValue:
      type: string
    SyntheticGetWorkUnitResultsRequestWorkUnitTokenString:
      type: string
      minLength: 1
    SyntheticStartQueryPlanningRequestQueryString:
      type: string
      minLength: 1
    Token:
      type: string
    TokenString:
      type: string
      minLength: 0
      maxLength: 4096
    TransactionIdString:
      type: string
      pattern: ^[\p{L}\p{N}\p{P}]*$
      minLength: 1
      maxLength: 255
    TrueFalseString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 1
      maxLength: 5
    URI:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*$
      minLength: 1
      maxLength: 1024
    ValueString:
      type: string
    VersionString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 1
      maxLength: 255
    WorkUnitTokenString:
      type: string
