openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: lakeformation
  x-aws-serviceName: lakeformation
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-03-31'
  title: AWS Lake Formation
  description: |-
    Lake Formation

    Defines the public endpoint for the Lake Formation service.
servers:
- description: The AWS Lake Formation regional endpoint
  url: https://lakeformation.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccessKeyIdString:
      type: string
    AdditionalContextMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ContextValue'
    ApplicationArn:
      type: string
    ApplicationStatus:
      type: string
      enum:
      - ENABLED
      - DISABLED
    AuditContextString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 0
      maxLength: 2048
    AuthorizedSessionTagValueList:
      type: array
      items:
        $ref: '#/components/schemas/NameString'
    BatchPermissionsFailureList:
      type: array
      items:
        $ref: '#/components/schemas/BatchPermissionsFailureEntry'
    BatchPermissionsRequestEntryList:
      type: array
      items:
        $ref: '#/components/schemas/BatchPermissionsRequestEntry'
    Boolean:
      type: boolean
      default: false
    BooleanNullable:
      type: boolean
    CatalogIdString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 1
      maxLength: 255
    ColumnLFTagsList:
      type: array
      items:
        $ref: '#/components/schemas/ColumnLFTag'
    ColumnNames:
      type: array
      items:
        $ref: '#/components/schemas/NameString'
    ComparisonOperator:
      type: string
      enum:
      - EQ
      - NE
      - LE
      - LT
      - GE
      - GT
      - CONTAINS
      - NOT_CONTAINS
      - BEGINS_WITH
      - IN
      - BETWEEN
    ContextKey:
      type: string
      minLength: 1
      maxLength: 128
    ContextValue:
      type: string
      minLength: 0
      maxLength: 256
    CredentialTimeoutDurationSecondInteger:
      type: integer
      minimum: 900
      maximum: 43200
    DataCellsFilterList:
      type: array
      items:
        $ref: '#/components/schemas/DataCellsFilter'
    DataLakePrincipalList:
      type: array
      items:
        $ref: '#/components/schemas/DataLakePrincipal'
    DataLakePrincipalString:
      type: string
      minLength: 1
      maxLength: 255
    DataLakeResourceType:
      type: string
      enum:
      - CATALOG
      - DATABASE
      - TABLE
      - DATA_LOCATION
      - LF_TAG
      - LF_TAG_POLICY
      - LF_TAG_POLICY_DATABASE
      - LF_TAG_POLICY_TABLE
      - LF_NAMED_TAG_EXPRESSION
    DatabaseLFTagsList:
      type: array
      items:
        $ref: '#/components/schemas/TaggedDatabase'
    DateTime:
      type: string
      format: date-time
    DescriptionString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*$
      minLength: 0
      maxLength: 2048
    ETagString:
      type: string
      pattern: ^[\p{L}\p{N}\p{P}]*$
      minLength: 1
      maxLength: 255
    EnableStatus:
      type: string
      enum:
      - ENABLED
      - DISABLED
    ErrorMessageString:
      type: string
    ExpirationTimestamp:
      type: string
      format: date-time
    Expression:
      type: array
      items:
        $ref: '#/components/schemas/LFTag'
    ExpressionString:
      type: string
      minLength: 0
      maxLength: 3000
    FieldNameString:
      type: string
      enum:
      - RESOURCE_ARN
      - ROLE_ARN
      - LAST_MODIFIED
    FilterConditionList:
      type: array
      items:
        $ref: '#/components/schemas/FilterCondition'
    GetQueryStateRequestQueryIdString:
      type: string
      minLength: 36
      maxLength: 36
    GetQueryStatisticsRequestQueryIdString:
      type: string
      minLength: 36
      maxLength: 36
    GetWorkUnitResultsRequestQueryIdString:
      type: string
      minLength: 36
      maxLength: 36
    GetWorkUnitResultsRequestWorkUnitIdLong:
      type: integer
      format: int64
      default: 0
      minimum: 0
    GetWorkUnitsRequestQueryIdString:
      type: string
      minLength: 36
      maxLength: 36
    HashString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 1
      maxLength: 255
    IAMRoleArn:
      type: string
      pattern: ^arn:aws:iam::[0-9]*:role/
    IAMSAMLProviderArn:
      type: string
      pattern: ^arn:aws:iam::[0-9]*:saml-provider/
    Identifier:
      type: string
      minLength: 1
      maxLength: 255
    IdentityCenterInstanceArn:
      type: string
    IdentityString:
      type: string
    KeyString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 1
      maxLength: 255
    LFTagErrors:
      type: array
      items:
        $ref: '#/components/schemas/LFTagError'
    LFTagExpressionsList:
      type: array
      items:
        $ref: '#/components/schemas/LFTagExpression'
    LFTagKey:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:\/=+\-@%]*)$
      minLength: 1
      maxLength: 128
    LFTagValue:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:\*\/=+\-@%]*)$
      minLength: 0
      maxLength: 256
    LFTagsList:
      type: array
      items:
        $ref: '#/components/schemas/LFTagPair'
    LakeFormationOptInsInfoList:
      type: array
      items:
        $ref: '#/components/schemas/LakeFormationOptInsInfo'
    LastModifiedTimestamp:
      type: string
      format: date-time
    MessageString:
      type: string
    NameString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 1
      maxLength: 255
    NullableBoolean:
      type: boolean
    NullableString:
      type: string
    NumberOfBytes:
      type: integer
      format: int64
      default: 0
    NumberOfItems:
      type: integer
      format: int64
      default: 0
    NumberOfMilliseconds:
      type: integer
      format: int64
      default: 0
    ObjectSize:
      type: integer
      format: int64
      default: 0
    OptimizerType:
      type: string
      enum:
      - COMPACTION
      - GARBAGE_COLLECTION
      - ALL
    PageSize:
      type: integer
      minimum: 1
      maximum: 1000
    ParametersMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ParametersMapValue'
    ParametersMapValue:
      type: string
      minLength: 0
      maxLength: 512000
    PartitionValueString:
      type: string
      minLength: 0
      maxLength: 1024
    PartitionValuesList:
      type: array
      items:
        $ref: '#/components/schemas/PartitionValueString'
    PartitionedTableObjectsList:
      type: array
      items:
        $ref: '#/components/schemas/PartitionObjects'
    PathString:
      type: string
    PathStringList:
      type: array
      items:
        $ref: '#/components/schemas/PathString'
    Permission:
      type: string
      enum:
      - ALL
      - SELECT
      - ALTER
      - DROP
      - DELETE
      - INSERT
      - DESCRIBE
      - CREATE_DATABASE
      - CREATE_TABLE
      - DATA_LOCATION_ACCESS
      - CREATE_LF_TAG
      - ASSOCIATE
      - GRANT_WITH_LF_TAG_EXPRESSION
      - CREATE_LF_TAG_EXPRESSION
      - CREATE_CATALOG
      - SUPER_USER
    PermissionList:
      type: array
      items:
        $ref: '#/components/schemas/Permission'
    PermissionType:
      type: string
      enum:
      - COLUMN_PERMISSION
      - CELL_FILTER_PERMISSION
      - NESTED_PERMISSION
      - NESTED_CELL_PERMISSION
    PermissionTypeList:
      type: array
      items:
        $ref: '#/components/schemas/PermissionType'
    PredicateString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*$
      minLength: 0
      maxLength: 2048
    PrincipalPermissionsList:
      type: array
      items:
        $ref: '#/components/schemas/PrincipalPermissions'
    PrincipalResourcePermissionsList:
      type: array
      items:
        $ref: '#/components/schemas/PrincipalResourcePermissions'
    QueryIdString:
      type: string
    QueryParameterMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    QueryPlanningContextDatabaseNameString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 1
    QueryStateString:
      type: string
      enum:
      - PENDING
      - WORKUNITS_AVAILABLE
      - ERROR
      - FINISHED
      - EXPIRED
    RAMResourceShareArn:
      type: string
    ResourceArnString:
      type: string
    ResourceInfoList:
      type: array
      items:
        $ref: '#/components/schemas/ResourceInfo'
    ResourceShareList:
      type: array
      items:
        $ref: '#/components/schemas/RAMResourceShareArn'
    ResourceShareType:
      type: string
      enum:
      - FOREIGN
      - ALL
    ResourceType:
      type: string
      enum:
      - DATABASE
      - TABLE
    Result:
      type: string
    ResultStream:
      type: string
      format: byte
    SAMLAssertionString:
      type: string
      minLength: 4
      maxLength: 100000
    ScopeTarget:
      type: string
    ScopeTargets:
      type: array
      items:
        $ref: '#/components/schemas/ScopeTarget'
    SearchPageSize:
      type: integer
      minimum: 1
      maximum: 100
    SecretAccessKeyString:
      type: string
    SessionTokenString:
      type: string
    StorageOptimizerConfig:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/StorageOptimizerConfigValue'
    StorageOptimizerConfigKey:
      type: string
    StorageOptimizerConfigMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/StorageOptimizerConfig'
    StorageOptimizerConfigValue:
      type: string
    StorageOptimizerList:
      type: array
      items:
        $ref: '#/components/schemas/StorageOptimizer'
    StringValue:
      type: string
    StringValueList:
      type: array
      items:
        $ref: '#/components/schemas/StringValue'
    SyntheticGetWorkUnitResultsRequestWorkUnitTokenString:
      type: string
      minLength: 1
    SyntheticStartQueryPlanningRequestQueryString:
      type: string
      minLength: 1
    TableLFTagsList:
      type: array
      items:
        $ref: '#/components/schemas/TaggedTable'
    TableObjectList:
      type: array
      items:
        $ref: '#/components/schemas/TableObject'
    TagValueList:
      type: array
      items:
        $ref: '#/components/schemas/LFTagValue'
    Timestamp:
      type: string
      format: date-time
    Token:
      type: string
    TokenString:
      type: string
      minLength: 0
      maxLength: 4096
    TransactionDescriptionList:
      type: array
      items:
        $ref: '#/components/schemas/TransactionDescription'
    TransactionIdString:
      type: string
      pattern: ^[\p{L}\p{N}\p{P}]*$
      minLength: 1
      maxLength: 255
    TransactionStatus:
      type: string
      enum:
      - ACTIVE
      - COMMITTED
      - ABORTED
      - COMMIT_IN_PROGRESS
    TransactionStatusFilter:
      type: string
      enum:
      - ALL
      - COMPLETED
      - ACTIVE
      - COMMITTED
      - ABORTED
    TransactionType:
      type: string
      enum:
      - READ_AND_WRITE
      - READ_ONLY
    TrueFalseString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 1
      maxLength: 5
    TrustedResourceOwners:
      type: array
      items:
        $ref: '#/components/schemas/CatalogIdString'
    URI:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*$
      minLength: 1
      maxLength: 1024
    ValueString:
      type: string
    ValueStringList:
      type: array
      items:
        $ref: '#/components/schemas/ValueString'
    VersionString:
      type: string
      pattern: ^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$
      minLength: 1
      maxLength: 255
    VirtualObjectList:
      type: array
      items:
        $ref: '#/components/schemas/VirtualObject'
    WorkUnitIdLong:
      type: integer
      format: int64
      default: 0
    WorkUnitRangeList:
      type: array
      items:
        $ref: '#/components/schemas/WorkUnitRange'
    WorkUnitTokenString:
      type: string
    WriteOperationList:
      type: array
      items:
        $ref: '#/components/schemas/WriteOperation'
