openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: lambda
  x-aws-serviceName: lambda
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2015-03-31'
  title: AWS Lambda
  description: "Lambda\n\n**Overview**\n\nLambda is a compute service that lets you\
    \ run code without provisioning or managing servers. Lambda runs your code on\
    \ a high-availability compute infrastructure and performs all of the administration\
    \ of the compute resources, including server and operating system maintenance,\
    \ capacity provisioning and automatic scaling, code monitoring and logging. With\
    \ Lambda, you can run code for virtually any type of application or backend service.\
    \ For more information about the Lambda service, see [What is Lambda](https://docs.aws.amazon.com/lambda/latest/dg/welcome.html)\
    \ in the **Lambda Developer Guide**.\n\nThe _Lambda API Reference_ provides information\
    \ about each of the API methods, including details about the parameters in each\
    \ API request and response.\n\nYou can use Software Development Kits (SDKs), Integrated\
    \ Development Environment (IDE) Toolkits, and command line tools to access the\
    \ API. For installation instructions, see [Tools for Amazon Web Services](http://aws.amazon.com/tools/).\n\
    \nFor a list of Region-specific endpoints that Lambda supports, see [Lambda endpoints\
    \ and quotas ](https://docs.aws.amazon.com/general/latest/gr/lambda-service.html)\
    \ in the _Amazon Web Services General Reference._.\n\nWhen making the API calls,\
    \ you will need to authenticate your request by providing a signature. Lambda\
    \ supports signature version 4. For more information, see [Signature Version 4\
    \ signing process](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html)\
    \ in the _Amazon Web Services General Reference._.\n\n**CA certificates**\n\n\
    Because Amazon Web Services SDKs use the CA certificates from your computer, changes\
    \ to the certificates on the Amazon Web Services servers can cause connection\
    \ failures when you attempt to use an SDK. You can prevent these failures by keeping\
    \ your computer's CA certificates and operating system up-to-date. If you encounter\
    \ this issue in a corporate environment and do not manage your own computer, you\
    \ might need to ask an administrator to assist with the update process. The following\
    \ list shows minimum operating system and Java versions:\n\n  * Microsoft Windows\
    \ versions that have updates from January 2005 or later installed contain at least\
    \ one of the required CAs in their trust list. \n\n  * Mac OS X 10.4 with Java\
    \ for Mac OS X 10.4 Release 5 (February 2007), Mac OS X 10.5 (October 2007), and\
    \ later versions contain at least one of the required CAs in their trust list.\
    \ \n\n  * Red Hat Enterprise Linux 5 (March 2007), 6, and 7 and CentOS 5, 6, and\
    \ 7 all contain at least one of the required CAs in their default trusted CA list.\
    \ \n\n  * Java 1.4.2_12 (May 2006), 5 Update 2 (March 2005), and all later versions,\
    \ including Java 6 (December 2006), 7, and 8, contain at least one of the required\
    \ CAs in their default trusted CA list. \n\nWhen accessing the Lambda management\
    \ console or Lambda API endpoints, whether through browsers or programmatically,\
    \ you will need to ensure your client machines support any of the following CAs:\n\
    \n  * Amazon Root CA 1\n\n  * Starfield Services Root Certificate Authority -\
    \ G2\n\n  * Starfield Class 2 Certification Authority\n\nRoot certificates from\
    \ the first two authorities are available from [Amazon trust services](https://www.amazontrust.com/repository/),\
    \ but keeping your computer up-to-date is the more straightforward solution. To\
    \ learn more about ACM-provided certificates, see [Amazon Web Services Certificate\
    \ Manager FAQs.](http://aws.amazon.com/certificate-manager/faqs/#certificates)"
servers:
- description: The AWS Lambda regional endpoint
  url: https://lambda.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Action:
      type: string
      pattern: ^(lambda:[*]|lambda:[a-zA-Z]+|[*])$
    AdditionalVersion:
      type: string
      pattern: ^[0-9]+$
      minLength: 1
      maxLength: 1024
    Alias:
      type: string
      pattern: ^(?!^[0-9]+$)([a-zA-Z0-9-_]+)$
      minLength: 1
      maxLength: 128
    AllowCredentials:
      type: boolean
    Arn:
      type: string
      pattern: ^arn:(aws[a-zA-Z0-9-]*):([a-zA-Z0-9\-])+:([a-z]{2}(-gov)?-[a-z]+-\d{1})?:(\d{12})?:(.*)$
    BatchSize:
      type: integer
      minimum: 1
      maximum: 10000
    BisectBatchOnFunctionError:
      type: boolean
    Boolean:
      type: boolean
      default: false
    CodeSigningConfigArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*)?:lambda:[a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1}:\d{12}:code-signing-config:csc-[a-z0-9]{17}$
      minLength: 0
      maxLength: 200
    CodeSigningConfigId:
      type: string
      pattern: ^csc-[a-zA-Z0-9-_\.]{17}$
    CollectionName:
      type: string
      pattern: ^(^(?!(system\x2e)))(^[_a-zA-Z0-9])([^$]*)$
      minLength: 1
      maxLength: 57
    DatabaseName:
      type: string
      pattern: ^[^ /\.$\x22]*$
      minLength: 1
      maxLength: 63
    Description:
      type: string
      minLength: 0
      maxLength: 256
    DestinationArn:
      type: string
      pattern: ^$|arn:(aws[a-zA-Z0-9-]*):([a-zA-Z0-9\-])+:([a-z]{2}(-gov)?-[a-z]+-\d{1})?:(\d{12})?:(.*)$
      minLength: 0
      maxLength: 350
    Enabled:
      type: boolean
    Endpoint:
      type: string
      pattern: ^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9]):[0-9]{1,5}$
      minLength: 1
      maxLength: 300
    EnvironmentVariableName:
      type: string
      pattern: ^[a-zA-Z]([a-zA-Z0-9_])+$
    EnvironmentVariableValue:
      type: string
    EphemeralStorageSize:
      type: integer
      minimum: 512
      maximum: 10240
    EventSourceMappingArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*)?:lambda:[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:event-source-mapping:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
      minLength: 85
      maxLength: 120
    EventSourceToken:
      type: string
      pattern: ^[a-zA-Z0-9._\-]+$
      minLength: 0
      maxLength: 256
    FileSystemArn:
      type: string
      pattern: ^arn:aws[a-zA-Z-]*:elasticfilesystem:[a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1}:\d{12}:access-point/fsap-[a-f0-9]{17}$
      minLength: 0
      maxLength: 200
    FilterCriteriaErrorCode:
      type: string
      pattern: ^[A-Za-z]+Exception$
      minLength: 10
      maxLength: 50
    FilterCriteriaErrorMessage:
      type: string
      pattern: .*
      minLength: 10
      maxLength: 2048
    FunctionArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*)?:lambda:[a-z]{2}(-gov)?-[a-z]+-\d{1}:\d{12}:function:[a-zA-Z0-9-_]+(:(\$LATEST|[a-zA-Z0-9-_]+))?$
    FunctionName:
      type: string
      pattern: ^(arn:(aws[a-zA-Z-]*)?:lambda:)?([a-z]{2}(-gov)?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?$
      minLength: 1
      maxLength: 140
    FunctionUrl:
      type: string
      minLength: 40
      maxLength: 100
    FunctionUrlQualifier:
      type: string
      pattern: ^(^\$LATEST$)|((?!^[0-9]+$)([a-zA-Z0-9-_]+))$
      minLength: 1
      maxLength: 128
    Handler:
      type: string
      pattern: ^[^\s]+$
      minLength: 0
      maxLength: 128
    Header:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 1024
    HttpStatus:
      type: integer
      default: 0
    Integer:
      type: integer
      default: 0
    KMSKeyArn:
      type: string
      pattern: ^(arn:(aws[a-zA-Z-]*)?:[a-z0-9-.]+:.*)|()$
    LastUpdateStatusReason:
      type: string
    LayerArn:
      type: string
      pattern: ^arn:[a-zA-Z0-9-]+:lambda:[a-zA-Z0-9-]+:\d{12}:layer:[a-zA-Z0-9-_]+$
      minLength: 1
      maxLength: 140
    LayerName:
      type: string
      pattern: ^(arn:[a-zA-Z0-9-]+:lambda:[a-zA-Z0-9-]+:\d{12}:layer:[a-zA-Z0-9-_]+)|[a-zA-Z0-9-_]+$
      minLength: 1
      maxLength: 140
    LayerPermissionAllowedAction:
      type: string
      pattern: ^lambda:GetLayerVersion$
      minLength: 0
      maxLength: 22
    LayerPermissionAllowedPrincipal:
      type: string
      pattern: ^\d{12}|\*|arn:(aws[a-zA-Z-]*):iam::\d{12}:root$
    LayerVersionArn:
      type: string
      pattern: ^arn:[a-zA-Z0-9-]+:lambda:[a-zA-Z0-9-]+:\d{12}:layer:[a-zA-Z0-9-_]+:[0-9]+$
      minLength: 1
      maxLength: 140
    LicenseInfo:
      type: string
      minLength: 0
      maxLength: 512
    LocalMountPath:
      type: string
      pattern: ^/mnt/[a-zA-Z0-9-_.]+$
      minLength: 0
      maxLength: 160
    LogGroup:
      type: string
      pattern: ^[\.\-_/#A-Za-z0-9]+$
      minLength: 1
      maxLength: 512
    MasterRegion:
      type: string
      pattern: ^ALL|[a-z]{2}(-gov)?-[a-z]+-\d{1}$
    MaxAge:
      type: integer
      minimum: 0
      maximum: 86400
    MaxFunctionEventInvokeConfigListItems:
      type: integer
      minimum: 1
      maximum: 50
    MaxItems:
      type: integer
      minimum: 1
      maximum: 50
    MaxLayerListItems:
      type: integer
      minimum: 1
      maximum: 50
    MaxListItems:
      type: integer
      minimum: 1
      maximum: 10000
    MaxProvisionedConcurrencyConfigListItems:
      type: integer
      minimum: 1
      maximum: 50
    MaximumBatchingWindowInSeconds:
      type: integer
      minimum: 0
      maximum: 300
    MaximumConcurrency:
      type: integer
      minimum: 2
      maximum: 1000
    MaximumEventAgeInSeconds:
      type: integer
      minimum: 60
      maximum: 21600
    MaximumNumberOfPollers:
      type: integer
      minimum: 1
      maximum: 2000
    MaximumRecordAgeInSeconds:
      type: integer
      minimum: -1
      maximum: 604800
    MaximumRetryAttempts:
      type: integer
      minimum: 0
      maximum: 2
    MaximumRetryAttemptsEventSourceMapping:
      type: integer
      minimum: -1
      maximum: 10000
    MemorySize:
      type: integer
      minimum: 128
      maximum: 10240
    Method:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 6
    MinimumNumberOfPollers:
      type: integer
      minimum: 1
      maximum: 200
    NameSpacedFunctionArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*)?:lambda:[a-z]{2}(-gov)?-[a-z]+-\d{1}:\d{12}:function:[a-zA-Z0-9-_\.]+(:(\$LATEST|[a-zA-Z0-9-_]+))?$
    NamespacedFunctionName:
      type: string
      pattern: ^(arn:(aws[a-zA-Z-]*)?:lambda:)?([a-z]{2}(-gov)?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?$
      minLength: 1
      maxLength: 170
    NamespacedStatementId:
      type: string
      pattern: ^([a-zA-Z0-9-_.]+)$
      minLength: 1
      maxLength: 100
    NonNegativeInteger:
      type: integer
      minimum: 0
    NullableBoolean:
      type: boolean
    OrganizationId:
      type: string
      pattern: ^o-[a-z0-9]{10,32}$
      minLength: 0
      maxLength: 34
    Origin:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 253
    ParallelizationFactor:
      type: integer
      minimum: 1
      maximum: 10
    Pattern:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 4096
    PositiveInteger:
      type: integer
      minimum: 1
    Principal:
      type: string
      pattern: ^[^\s]+$
    PrincipalOrgID:
      type: string
      pattern: ^o-[a-z0-9]{10,32}$
      minLength: 12
      maxLength: 34
    Qualifier:
      type: string
      pattern: ^(|[a-zA-Z0-9$_-]+)$
      minLength: 1
      maxLength: 128
    Queue:
      type: string
      pattern: ^[\s\S]*$
      minLength: 1
      maxLength: 1000
    ReservedConcurrentExecutions:
      type: integer
      minimum: 0
    ResourceArn:
      type: string
      pattern: ^(arn:(aws[a-zA-Z-]*)?:[a-z0-9-.]+:.*)|()$
    RoleArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$
    RuntimeVersionArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*):lambda:[a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1}::runtime:.+$
      minLength: 26
      maxLength: 2048
    S3Bucket:
      type: string
      pattern: ^[0-9A-Za-z\.\-_]*(?<!\.)$
      minLength: 3
      maxLength: 63
    S3Key:
      type: string
      minLength: 1
      maxLength: 1024
    S3ObjectVersion:
      type: string
      minLength: 1
      maxLength: 1024
    SecurityGroupId:
      type: string
    SensitiveString:
      type: string
    SourceOwner:
      type: string
      pattern: ^\d{12}$
      minLength: 0
      maxLength: 12
    StateReason:
      type: string
    StatementId:
      type: string
      pattern: ^([a-zA-Z0-9-_]+)$
      minLength: 1
      maxLength: 100
    String:
      type: string
    SubnetId:
      type: string
    TagKey:
      type: string
    TagValue:
      type: string
    TaggableResource:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*):lambda:[a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:\d{12}:(function:[a-zA-Z0-9-_]+(:(\$LATEST|[a-zA-Z0-9-_]+))?|code-signing-config:csc-[a-z0-9]{17}|event-source-mapping:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$
      minLength: 1
      maxLength: 256
    TagsErrorCode:
      type: string
      pattern: ^[A-Za-z]+Exception$
      minLength: 10
      maxLength: 21
    TagsErrorMessage:
      type: string
      pattern: ^.*$
      minLength: 84
      maxLength: 1000
    Timeout:
      type: integer
      minimum: 1
    Timestamp:
      type: string
    Topic:
      type: string
      pattern: ^[^.]([a-zA-Z0-9\-_.]+)$
      minLength: 1
      maxLength: 249
    TumblingWindowInSeconds:
      type: integer
      minimum: 0
      maximum: 900
    URI:
      type: string
      pattern: ^[a-zA-Z0-9-\/*:_+=.@-]*$
      minLength: 1
      maxLength: 200
    UnqualifiedFunctionName:
      type: string
      pattern: ^(arn:(aws[a-zA-Z-]*)?:lambda:)?([a-z]{2}((-gov)|(-iso([a-z]?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_]+)$
      minLength: 1
      maxLength: 140
    UnreservedConcurrentExecutions:
      type: integer
      minimum: 0
    Version:
      type: string
      pattern: ^(\$LATEST|[0-9]+)$
      minLength: 1
      maxLength: 1024
    VpcId:
      type: string
    WorkingDirectory:
      type: string
      minLength: 0
      maxLength: 1000
