openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: lambda
  x-aws-serviceName: lambda
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2015-03-31'
  title: AWS Lambda
  description: "Lambda\n\n**Overview**\n\nLambda is a compute service that lets you\
    \ run code without provisioning or managing servers. Lambda runs your code on\
    \ a high-availability compute infrastructure and performs all of the administration\
    \ of the compute resources, including server and operating system maintenance,\
    \ capacity provisioning and automatic scaling, code monitoring and logging. With\
    \ Lambda, you can run code for virtually any type of application or backend service.\
    \ For more information about the Lambda service, see [What is Lambda](https://docs.aws.amazon.com/lambda/latest/dg/welcome.html)\
    \ in the **Lambda Developer Guide**.\n\nThe _Lambda API Reference_ provides information\
    \ about each of the API methods, including details about the parameters in each\
    \ API request and response.\n\nYou can use Software Development Kits (SDKs), Integrated\
    \ Development Environment (IDE) Toolkits, and command line tools to access the\
    \ API. For installation instructions, see [Tools for Amazon Web Services](http://aws.amazon.com/tools/).\n\
    \nFor a list of Region-specific endpoints that Lambda supports, see [Lambda endpoints\
    \ and quotas ](https://docs.aws.amazon.com/general/latest/gr/lambda-service.html)\
    \ in the _Amazon Web Services General Reference._.\n\nWhen making the API calls,\
    \ you will need to authenticate your request by providing a signature. Lambda\
    \ supports signature version 4. For more information, see [Signature Version 4\
    \ signing process](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html)\
    \ in the _Amazon Web Services General Reference._.\n\n**CA certificates**\n\n\
    Because Amazon Web Services SDKs use the CA certificates from your computer, changes\
    \ to the certificates on the Amazon Web Services servers can cause connection\
    \ failures when you attempt to use an SDK. You can prevent these failures by keeping\
    \ your computer's CA certificates and operating system up-to-date. If you encounter\
    \ this issue in a corporate environment and do not manage your own computer, you\
    \ might need to ask an administrator to assist with the update process. The following\
    \ list shows minimum operating system and Java versions:\n\n  * Microsoft Windows\
    \ versions that have updates from January 2005 or later installed contain at least\
    \ one of the required CAs in their trust list. \n\n  * Mac OS X 10.4 with Java\
    \ for Mac OS X 10.4 Release 5 (February 2007), Mac OS X 10.5 (October 2007), and\
    \ later versions contain at least one of the required CAs in their trust list.\
    \ \n\n  * Red Hat Enterprise Linux 5 (March 2007), 6, and 7 and CentOS 5, 6, and\
    \ 7 all contain at least one of the required CAs in their default trusted CA list.\
    \ \n\n  * Java 1.4.2_12 (May 2006), 5 Update 2 (March 2005), and all later versions,\
    \ including Java 6 (December 2006), 7, and 8, contain at least one of the required\
    \ CAs in their default trusted CA list. \n\nWhen accessing the Lambda management\
    \ console or Lambda API endpoints, whether through browsers or programmatically,\
    \ you will need to ensure your client machines support any of the following CAs:\n\
    \n  * Amazon Root CA 1\n\n  * Starfield Services Root Certificate Authority -\
    \ G2\n\n  * Starfield Class 2 Certification Authority\n\nRoot certificates from\
    \ the first two authorities are available from [Amazon trust services](https://www.amazontrust.com/repository/),\
    \ but keeping your computer up-to-date is the more straightforward solution. To\
    \ learn more about ACM-provided certificates, see [Amazon Web Services Certificate\
    \ Manager FAQs.](http://aws.amazon.com/certificate-manager/faqs/#certificates)"
servers:
- description: The AWS Lambda regional endpoint
  url: https://lambda.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas: {}
