openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: launch_wizard
  x-aws-serviceName: launchwizard
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: AWS Launch Wizard
  description: |-
    Launch Wizard offers a guided way of sizing, configuring, and deploying Amazon Web Services resources for third party applications, such as Microsoft SQL Server Always On and HANA based SAP systems, without the need to manually identify and provision individual Amazon Web Services resources.
servers:
- description: The AWS Launch Wizard regional endpoint
  url: https://launchwizard.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AllowedValues:
      type: array
      items:
        $ref: '#/components/schemas/ValueString'
    DeploymentDataSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/DeploymentDataSummary'
    DeploymentEventDataSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/DeploymentEventDataSummary'
    DeploymentFilterKey:
      type: string
      enum:
      - WORKLOAD_NAME
      - DEPLOYMENT_STATUS
    DeploymentFilterList:
      type: array
      items:
        $ref: '#/components/schemas/DeploymentFilter'
    DeploymentFilterValues:
      type: array
      items:
        type: string
    DeploymentId:
      type: string
      pattern: ^[a-zA-Z0-9-]+$
      minLength: 2
      maxLength: 128
    DeploymentName:
      type: string
      pattern: ^[A-Za-z0-9_\.-]+$
      minLength: 1
      maxLength: 50
    DeploymentPatternName:
      type: string
      pattern: ^[A-Za-z0-9][a-zA-Z0-9-]*$
      minLength: 1
      maxLength: 256
    DeploymentSpecifications:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ValueString'
    DeploymentSpecificationsData:
      type: array
      items:
        $ref: '#/components/schemas/DeploymentSpecificationsField'
    DeploymentStatus:
      type: string
      enum:
      - COMPLETED
      - CREATING
      - DELETE_IN_PROGRESS
      - DELETE_INITIATING
      - DELETE_FAILED
      - DELETED
      - FAILED
      - IN_PROGRESS
      - VALIDATING
    EventId:
      type: string
      minLength: 1
      maxLength: 32
    EventStatus:
      type: string
      enum:
      - CANCELED
      - CANCELING
      - COMPLETED
      - CREATED
      - FAILED
      - IN_PROGRESS
      - PENDING
      - TIMED_OUT
    KeyString:
      type: string
      pattern: ^[a-zA-Z0-9-:]+$
      minLength: 3
      maxLength: 256
    MaxDeploymentEventResults:
      type: integer
      minimum: 1
      maximum: 100
    MaxDeploymentResults:
      type: integer
      minimum: 1
      maximum: 100
    MaxWorkloadDeploymentPatternResults:
      type: integer
      minimum: 1
      maximum: 100
    MaxWorkloadResults:
      type: integer
      minimum: 1
      maximum: 100
    NextToken:
      type: string
      minLength: 1
      maxLength: 1024
    SettingsSetName:
      type: string
      pattern: ^[a-zA-Z0-9-]{2,50}$
    SpecificationsConditionalData:
      type: array
      items:
        $ref: '#/components/schemas/DeploymentConditionalField'
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    Tags:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    ValueString:
      type: string
      minLength: 1
      maxLength: 1500
    WorkloadDataSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/WorkloadDataSummary'
    WorkloadDeploymentPatternDataSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/WorkloadDeploymentPatternDataSummary'
    WorkloadDeploymentPatternStatus:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
      - DISABLED
      - DELETED
    WorkloadName:
      type: string
      pattern: ^[A-Za-z][a-zA-Z0-9-_]*$
      minLength: 1
      maxLength: 100
    WorkloadStatus:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
      - DISABLED
      - DELETED
    WorkloadVersionName:
      type: string
      pattern: ^[A-Za-z0-9][a-zA-Z0-9-]*$
      minLength: 5
      maxLength: 30
