openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: lex_models_v2
  x-aws-serviceName: lexmodelsv2
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-08-07'
  title: Amazon Lex Model Building V2
  description: ""
servers:
- description: The Amazon Lex Model Building V2 regional endpoint
  url: https://models-v2-lex.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ActiveContextName:
      type: string
      pattern: ^([A-Za-z]_?)+$
      minLength: 1
      maxLength: 100
    AmazonResourceName:
      type: string
      minLength: 1
      maxLength: 1011
    AnalyticsChannel:
      type: string
      minLength: 1
      maxLength: 50
    AnalyticsFilterValue:
      type: string
    AnalyticsGroupByValue:
      type: string
    AnalyticsNodeCount:
      type: integer
    AnalyticsNodeLevel:
      type: integer
      minimum: 0
      maximum: 100
    AnalyticsOriginatingRequestId:
      type: string
    AnalyticsPath:
      type: string
      minLength: 1
      maxLength: 1024
    AnalyticsSessionId:
      type: string
      pattern: ^[0-9a-zA-Z._:-]$
    AnswerField:
      type: string
    AttachmentTitle:
      type: string
      minLength: 1
      maxLength: 250
    AttachmentUrl:
      type: string
      minLength: 1
      maxLength: 250
    AudioFileS3Location:
      type: string
      pattern: ^s3://([a-z0-9\\.-]+)/(.+)$
      minLength: 1
      maxLength: 1024
    BedrockGuardrailIdentifier:
      type: string
      pattern: ^(([a-z0-9]+)|(arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}:[0-9]{12}:guardrail/[a-z0-9]+))$
      minLength: 1
      maxLength: 2048
    BedrockGuardrailVersion:
      type: string
      pattern: ^(([1-9][0-9]{0,7})|(DRAFT))$
    BedrockKnowledgeBaseArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,40}:[0-9]{12}:knowledge-base\/[A-Za-z0-9]{10}$|^[A-Za-z0-9]{10}$
      minLength: 1
      maxLength: 200
    BedrockModelArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}::foundation-model\/[a-z0-9-]{1,63}[.]{1}([a-z0-9-]{1,63}[.]){0,2}[a-z0-9-]{1,63}([:][a-z0-9-]{1,63}){0,2}$
    BedrockModelCustomPrompt:
      type: string
      minLength: 1
      maxLength: 4000
    Boolean:
      type: boolean
      default: false
    BotAliasId:
      type: string
      pattern: ^(\bTSTALIASID\b|[0-9a-zA-Z]+)$
      minLength: 10
      maxLength: 10
    BotAliasName:
      type: string
      pattern: ^(\bAmazonLexTestAlias\b|[0-9a-zA-Z][_-]?)+$
      minLength: 1
      maxLength: 100
    BotLocaleHistoryEventDescription:
      type: string
    BotVersion:
      type: string
      pattern: ^(DRAFT|[0-9]+)$
      minLength: 1
      maxLength: 5
    BoxedBoolean:
      type: boolean
    BuiltInOrCustomSlotTypeId:
      type: string
      pattern: ^((AMAZON\.)[a-zA-Z_]+?|[0-9a-zA-Z]+)$
      minLength: 1
      maxLength: 25
    BuiltInsMaxResults:
      type: integer
      minimum: 20
      maximum: 20
    ButtonText:
      type: string
      minLength: 1
      maxLength: 50
    ButtonValue:
      type: string
      minLength: 1
      maxLength: 50
    ChildDirected:
      type: boolean
      default: false
    CloudWatchLogGroupArn:
      type: string
      pattern: ^arn:[\w\-]+:logs:[\w\-]+:[\d]{12}:log-group:[\.\-_/#A-Za-z0-9]{1,512}(?::\*)?$
      minLength: 1
      maxLength: 2048
    CodeHookInterfaceVersion:
      type: string
      minLength: 1
      maxLength: 5
    ConditionExpression:
      type: string
      minLength: 1
      maxLength: 1024
    ConditionKey:
      type: string
      minLength: 1
      maxLength: 1024
    ConditionOperator:
      type: string
      minLength: 1
    ConditionValue:
      type: string
      minLength: 1
      maxLength: 1024
    ContextTimeToLiveInSeconds:
      type: integer
      minimum: 5
      maximum: 86400
    ContextTurnsToLive:
      type: integer
      minimum: 1
      maximum: 20
    Count:
      type: integer
    CustomPayloadValue:
      type: string
      minLength: 1
      maxLength: 1000
    DTMFCharacter:
      type: string
      pattern: ^[A-D0-9#*]{1}$
    Description:
      type: string
      minLength: 0
      maxLength: 200
    DomainEndpoint:
      type: string
      pattern: ^(http|https):\/\/+[^\s]+[\w]$
    DraftBotVersion:
      type: string
      pattern: ^DRAFT$
      minLength: 5
      maxLength: 5
    Enabled:
      type: boolean
      default: false
    ErrorMessage:
      type: string
    ExceptionMessage:
      type: string
    FailureReason:
      type: string
    FilePassword:
      type: string
      minLength: 0
      maxLength: 1024
    FilterValue:
      type: string
      pattern: ^[0-9a-zA-Z_()\s-]+$
      minLength: 1
      maxLength: 100
    FulfillmentStartResponseDelay:
      type: integer
      minimum: 1
      maximum: 900
    FulfillmentTimeout:
      type: integer
      minimum: 1
      maximum: 900
    FulfillmentUpdateResponseFrequency:
      type: integer
      minimum: 1
      maximum: 900
    GenerationInput:
      type: string
      minLength: 100
      maxLength: 2000
    HitCount:
      type: integer
    Id:
      type: string
      pattern: ^[0-9a-zA-Z]+$
      minLength: 10
      maxLength: 10
    ImportExportFilePassword:
      type: string
      minLength: 1
      maxLength: 1024
    ImportedResourceId:
      type: string
      pattern: ^([0-9a-zA-Z_])+$
      minLength: 5
      maxLength: 10
    IncludeField:
      type: string
    IntentSignature:
      type: string
    ItemId:
      type: string
      minLength: 1
      maxLength: 32
    KendraIndexArn:
      type: string
      pattern: ^arn:aws:kendra:[a-z]+-[a-z]+-[0-9]:[0-9]{12}:index\/[a-zA-Z0-9][a-zA-Z0-9_-]*$
      minLength: 32
      maxLength: 2048
    KmsKeyArn:
      type: string
      pattern: ^arn:[\w\-]+:kms:[\w\-]+:[\d]{12}:(?:key\/[\w\-]+|alias\/[a-zA-Z0-9:\/_\-]{1,256})$
      minLength: 20
      maxLength: 2048
    LambdaARN:
      type: string
      pattern: ^arn:aws:lambda:[a-z]+-[a-z]+-[0-9]:[0-9]{12}:function:[a-zA-Z0-9-_]+(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})?(:[a-zA-Z0-9-_]+)?$
      minLength: 20
      maxLength: 2048
    LocaleId:
      type: string
    LocaleName:
      type: string
    LogPrefix:
      type: string
      minLength: 0
      maxLength: 1024
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
    MaxUtteranceDigits:
      type: integer
      minimum: 1
      maximum: 1024
    MissedCount:
      type: integer
    Name:
      type: string
      pattern: ^([0-9a-zA-Z][_-]?){1,100}$
      minLength: 1
      maxLength: 100
    NextIndex:
      type: integer
      minimum: 0
      maximum: 10000000
    NextToken:
      type: string
    NonEmptyString:
      type: string
      minLength: 1
    NumericalBotVersion:
      type: string
      pattern: ^[0-9]+$
      minLength: 1
      maxLength: 5
    OSIndexName:
      type: string
      pattern: ^(?![_-])[a-z0-9][a-z0-9_\-]{0,254}$
      minLength: 1
      maxLength: 255
    ObjectPrefix:
      type: string
      pattern: ^[\/]?+[a-zA-Z0-9!_.*'()-]+(\/[a-zA-Z0-9!_.*'()-]+)*$
      minLength: 1
    Operation:
      type: string
      pattern: ^lex:[a-zA-Z*]+$
      minLength: 5
      maxLength: 50
    Phrase:
      type: string
      minLength: 1
      maxLength: 100
    PlainTextMessageValue:
      type: string
      minLength: 1
      maxLength: 1000
    Policy:
      type: string
      minLength: 2
    PresignedS3Url:
      type: string
      minLength: 1
      maxLength: 1024
    PrincipalArn:
      type: string
      pattern: ^arn:aws:iam::[0-9]{12}:(root|(user|role)/.*)$
      minLength: 30
      maxLength: 1024
    PriorityValue:
      type: integer
      minimum: 0
      maximum: 100
    PromptMaxRetries:
      type: integer
      minimum: 0
      maximum: 5
    QInConnectAssistantARN:
      type: string
      pattern: ^arn:[a-z-]*?:wisdom:[a-z0-9-]*?:[0-9]{12}:[a-z-]*?/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(?:/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}){0,2}$
    QueryFilterString:
      type: string
      minLength: 1
      maxLength: 5000
    QuestionField:
      type: string
    RecommendedAction:
      type: string
    RegexPattern:
      type: string
      minLength: 1
      maxLength: 300
    ReplicaRegion:
      type: string
      minLength: 2
      maxLength: 25
    ResourceCount:
      type: integer
    RetryAfterSeconds:
      type: integer
      default: 0
    RevisionId:
      type: string
      pattern: ^[0-9]+$
      minLength: 1
      maxLength: 5
    RoleArn:
      type: string
      pattern: ^arn:aws:iam::[0-9]{12}:role/.*$
      minLength: 32
      maxLength: 2048
    RuntimeHintPhrase:
      type: string
      minLength: 1
      maxLength: 140
    S3BucketArn:
      type: string
      pattern: ^arn:[\w\-]+:s3:::[a-z0-9][\.\-a-z0-9]{1,61}[a-z0-9]$
      minLength: 1
      maxLength: 2048
    S3BucketName:
      type: string
      pattern: ^[a-z0-9][\.\-a-z0-9]{1,61}[a-z0-9]$
      minLength: 3
      maxLength: 63
    S3ObjectPath:
      type: string
      pattern: ^[\.\-\!\*\_\'\(\)a-zA-Z0-9][\.\-\!\*\_\'\(\)\/a-zA-Z0-9]*$
      minLength: 1
      maxLength: 1024
    SSMLMessageValue:
      type: string
      minLength: 1
      maxLength: 1000
    SampleUtterancesCount:
      type: integer
    ServicePrincipal:
      type: string
      pattern: ^[0-9a-zA-Z_.]+$
      minLength: 15
      maxLength: 1024
    SessionId:
      type: string
      pattern: ^[0-9a-zA-Z._:-]+$
      minLength: 2
      maxLength: 100
    SessionTTL:
      type: integer
      minimum: 60
      maximum: 86400
    SkipResourceInUseCheck:
      type: boolean
      default: false
    SlotDefaultValueString:
      type: string
      minLength: 1
      maxLength: 202
    SlotTypeSignature:
      type: string
    StillWaitingResponseFrequency:
      type: integer
      minimum: 1
      maximum: 300
    StillWaitingResponseTimeout:
      type: integer
      minimum: 1
      maximum: 900
    String:
      type: string
    SubSlotExpression:
      type: string
      pattern: ^[0-9A-Za-z_\-\s\(\)]+$
      minLength: 0
      maxLength: 640
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TestResultSlotName:
      type: string
      pattern: ^([0-9a-zA-Z][_.-]?)+$
      minLength: 1
      maxLength: 100
    TestSetAgentPrompt:
      type: string
      minLength: 1
      maxLength: 1024
    TestSetConversationId:
      type: string
      pattern: ^([0-9a-zA-Z][_-]?)+$
      minLength: 1
      maxLength: 50
    TestSetUtteranceText:
      type: string
      minLength: 1
      maxLength: 1024
    TimeInMilliSeconds:
      type: integer
      minimum: 1
    TimeValue:
      type: integer
      minimum: 1
      maximum: 24
    Transcript:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 6000000
    TurnNumber:
      type: integer
      minimum: 0
      maximum: 30
    Utterance:
      type: string
    UtteranceUnderstood:
      type: boolean
      default: false
    Value:
      type: string
      minLength: 1
      maxLength: 140
    VoiceId:
      type: string
    Weight:
      type: integer
      minimum: 0
      maximum: 3
