openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: lex_runtime_v2
  x-aws-serviceName: lexruntimev2
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-08-07'
  title: Amazon Lex Runtime V2
  description: |-
    This section contains documentation for the Amazon Lex V2 Runtime V2 API operations.
servers:
- description: The Amazon Lex Runtime V2 regional endpoint
  url: https://runtime-v2-lex.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ActiveContextName:
      type: string
      pattern: ^([A-Za-z0-9]_?)+$
      minLength: 1
      maxLength: 100
    ActiveContextTimeToLiveInSeconds:
      type: integer
      minimum: 5
      maximum: 86400
    ActiveContextTurnsToLive:
      type: integer
      minimum: 1
      maximum: 20
    AttachmentTitle:
      type: string
      minLength: 1
      maxLength: 250
    AttachmentUrl:
      type: string
      minLength: 1
      maxLength: 250
    Boolean:
      type: boolean
      default: false
    BotAliasIdentifier:
      type: string
    BotIdentifier:
      type: string
      pattern: ^[0-9a-zA-Z]+$
      minLength: 10
      maxLength: 10
    ButtonText:
      type: string
      minLength: 1
      maxLength: 50
    ButtonValue:
      type: string
      minLength: 1
      maxLength: 50
    DTMFRegex:
      type: string
      pattern: ^[A-D0-9#*]{1}$
      minLength: 1
      maxLength: 1
    EventId:
      type: string
      pattern: ^[0-9a-zA-Z._:-]+$
      minLength: 2
      maxLength: 100
    LocaleId:
      type: string
      minLength: 1
    Name:
      type: string
      pattern: ^([0-9a-zA-Z][_-]?)+$
      minLength: 1
      maxLength: 100
    NonEmptyString:
      type: string
      minLength: 1
    ParameterName:
      type: string
      minLength: 1
      maxLength: 100
    RuntimeHintPhrase:
      type: string
      minLength: 1
      maxLength: 140
    SensitiveNonEmptyString:
      type: string
    SessionId:
      type: string
      pattern: ^[0-9a-zA-Z._:-]+$
      minLength: 2
      maxLength: 100
    String:
      type: string
    Text:
      type: string
      minLength: 1
      maxLength: 1024
