openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: license_manager_linux_subscriptions
  x-aws-serviceName: licensemanagerlinuxsubscriptions
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: AWS License Manager Linux Subscriptions
  description: |-
    With License Manager, you can discover and track your commercial Linux subscriptions on running Amazon EC2 instances.
servers:
- description: The AWS License Manager Linux Subscriptions regional endpoint
  url: https://license-manager-linux-subscriptions.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    BoxInteger:
      type: integer
    BoxLong:
      type: integer
      format: int64
    FilterList:
      type: array
      items:
        $ref: '#/components/schemas/Filter'
    InstanceList:
      type: array
      items:
        $ref: '#/components/schemas/Instance'
    LinuxSubscriptionsDiscovery:
      type: string
      enum:
      - Enabled
      - Disabled
    Operator:
      type: string
      enum:
      - Equal
      - NotEqual
      - Contains
      minLength: 1
      maxLength: 20
    OrganizationIntegration:
      type: string
      enum:
      - Enabled
      - Disabled
    ProductCodeList:
      type: array
      items:
        type: string
    RegisteredSubscriptionProviderList:
      type: array
      items:
        $ref: '#/components/schemas/RegisteredSubscriptionProvider'
    SecretArn:
      type: string
      pattern: ^arn:[a-z0-9-\.]{1,63}:secretsmanager:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:secret:[^/]{1,1023}$
    Status:
      type: string
      enum:
      - InProgress
      - Completed
      - Successful
      - Failed
    StringList:
      type: array
      items:
        type: string
    StringMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    SubscriptionList:
      type: array
      items:
        $ref: '#/components/schemas/Subscription'
    SubscriptionProviderArn:
      type: string
      pattern: ^arn:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{1,510}/[a-z0-9-\.]{1,510}$
    SubscriptionProviderSource:
      type: string
      enum:
      - RedHat
    SubscriptionProviderSourceList:
      type: array
      items:
        $ref: '#/components/schemas/SubscriptionProviderSource'
    SubscriptionProviderStatus:
      type: string
      enum:
      - ACTIVE
      - INVALID
      - PENDING
    TagKeyList:
      type: array
      items:
        type: string
      x-sensitive: true
    Tags:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
