openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: license_manager_user_subscriptions
  x-aws-serviceName: licensemanagerusersubscriptions
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: AWS License Manager User Subscriptions
  description: |-
    With License Manager, you can create user-based subscriptions to utilize licensed software with a per user subscription fee on Amazon EC2 instances.
servers:
- description: The AWS License Manager User Subscriptions regional endpoint
  url: https://license-manager-user-subscriptions.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ActiveDirectoryType:
      type: string
      enum:
      - SELF_MANAGED
      - AWS_MANAGED
    Arn:
      type: string
      pattern: ^arn:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{1,63}:[a-zA-Z0-9-\.]{1,510}/[a-zA-Z0-9-\.]{1,510}$
    BoxInteger:
      type: integer
    Directory:
      type: string
      pattern: ^(d|sd)-[0-9a-f]{10}$
    IpV4:
      type: string
      pattern: ^(?:(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])(\.(?!$)|$)){4}$
    LicenseServerEndpointId:
      type: string
    LicenseServerEndpointProvisioningStatus:
      type: string
      enum:
      - PROVISIONING
      - PROVISIONING_FAILED
      - PROVISIONED
      - DELETING
      - DELETION_FAILED
      - DELETED
    LicenseServerHealthStatus:
      type: string
      enum:
      - HEALTHY
      - UNHEALTHY
      - NOT_APPLICABLE
    ResourceArn:
      type: string
      pattern: ^arn:([a-z0-9-\.]{1,63}):([a-z0-9-\.]{1,63}):([a-z0-9-\.]{1,63}):([a-z0-9-\.]{1,63}):([a-z0-9-\.]{1,510})/([a-z0-9-\.]{1,510})$
    SecurityGroup:
      type: string
      pattern: ^sg-(([0-9a-z]{8})|([0-9a-z]{17}))$
      minLength: 5
      maxLength: 200
    ServerType:
      type: string
      enum:
      - RDS_SAL
    Subnet:
      type: string
      pattern: ^subnet-[a-z0-9]{8,17}
