openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: license_manager_user_subscriptions
  x-aws-serviceName: licensemanagerusersubscriptions
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: AWS License Manager User Subscriptions
  description: |-
    With License Manager, you can create user-based subscriptions to utilize licensed software with a per user subscription fee on Amazon EC2 instances.
servers:
- description: The AWS License Manager User Subscriptions regional endpoint
  url: https://license-manager-user-subscriptions.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ActiveDirectoryType:
      type: string
      enum:
      - SELF_MANAGED
      - AWS_MANAGED
    Arn:
      type: string
      pattern: ^arn:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{1,63}:[a-zA-Z0-9-\.]{1,510}/[a-zA-Z0-9-\.]{1,510}$
    BoxInteger:
      type: integer
    CredentialsProvider:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/SecretsManagerCredentialsProvider'
        description: |-
          Identifies the Secrets Manager secret that contains credentials needed for user administration in the Active Directory.
      description: |-
        Contains information about the credential provider for user administration.
    Directory:
      type: string
      pattern: ^(d|sd)-[0-9a-f]{10}$
    FilterList:
      type: array
      items:
        $ref: '#/components/schemas/Filter'
    IdentityProvider:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/ActiveDirectoryIdentityProvider'
        description: |-
          The `ActiveDirectoryIdentityProvider` resource contains settings and other details about a specific Active Directory identity provider.
      description: |-
        Refers to an identity provider.
    IdentityProviderSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/IdentityProviderSummary'
    InstanceSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/InstanceSummary'
    InstanceUserSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/InstanceUserSummary'
    IpV4:
      type: string
      pattern: ^(?:(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])(\.(?!$)|$)){4}$
    IpV4List:
      type: array
      items:
        $ref: '#/components/schemas/IpV4'
    LicenseServerEndpointId:
      type: string
    LicenseServerEndpointList:
      type: array
      items:
        $ref: '#/components/schemas/LicenseServerEndpoint'
    LicenseServerEndpointProvisioningStatus:
      type: string
      enum:
      - PROVISIONING
      - PROVISIONING_FAILED
      - PROVISIONED
      - DELETING
      - DELETION_FAILED
      - DELETED
    LicenseServerHealthStatus:
      type: string
      enum:
      - HEALTHY
      - UNHEALTHY
      - NOT_APPLICABLE
    LicenseServerList:
      type: array
      items:
        $ref: '#/components/schemas/LicenseServer'
    ProductUserSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/ProductUserSummary'
    ResourceArn:
      type: string
      pattern: ^arn:([a-z0-9-\.]{1,63}):([a-z0-9-\.]{1,63}):([a-z0-9-\.]{1,63}):([a-z0-9-\.]{1,63}):([a-z0-9-\.]{1,510})/([a-z0-9-\.]{1,510})$
    SecurityGroup:
      type: string
      pattern: ^sg-(([0-9a-z]{8})|([0-9a-z]{17}))$
      minLength: 5
      maxLength: 200
    ServerSettings:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/RdsSalSettings'
        description: |-
          The `RdsSalSettings` resource contains settings to configure a specific Remote Desktop Services (RDS) license server.
      description: |-
        Contains settings for a specific server.
    ServerType:
      type: string
      enum:
      - RDS_SAL
    StringList:
      type: array
      items:
        type: string
    Subnet:
      type: string
      pattern: ^subnet-[a-z0-9]{8,17}
    Subnets:
      type: array
      items:
        $ref: '#/components/schemas/Subnet'
    TagKeyList:
      type: array
      items:
        type: string
      x-sensitive: true
    Tags:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
