openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: location
  x-aws-serviceName: location
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-11-19'
  title: Amazon Location Service
  description: |-
    "Suite of geospatial services including Maps, Places, Routes, Tracking, and Geofencing"
servers:
- description: The Amazon Location Service regional endpoint
  url: https://geo.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ApiKey:
      type: string
      maxLength: 1000
    ApiKeyAction:
      type: string
      pattern: ^(geo|geo-routes|geo-places|geo-maps):\w*\*?$
      minLength: 5
      maxLength: 200
    Arn:
      type: string
      pattern: ^arn(:[a-z0-9]+([.-][a-z0-9]+)*){2}(:([a-z0-9]+([.-][a-z0-9]+)*)?){2}:([^/].*)?$
      maxLength: 1600
    BatchItemErrorCode:
      type: string
      enum:
      - AccessDeniedError
      - ConflictError
      - InternalServerError
      - ResourceNotFoundError
      - ThrottlingError
      - ValidationError
    CountryCode3:
      type: string
      pattern: ^[A-Z]{3}$
      minLength: 3
      maxLength: 3
    CountryCode3OrEmpty:
      type: string
      pattern: ^[A-Z]{3}$|^$
      minLength: 0
      maxLength: 3
    CustomLayer:
      type: string
      pattern: ^[-._\w]+$
      minLength: 1
      maxLength: 100
    DimensionUnit:
      type: string
      enum:
      - Meters
      - Feet
    DistanceUnit:
      type: string
      enum:
      - Kilometers
      - Miles
    Earfcn:
      type: integer
      default: 0
      minimum: 0
      maximum: 262143
    EutranCellId:
      type: integer
      default: 0
      minimum: 0
      maximum: 268435455
    ForecastedGeofenceEventType:
      type: string
      enum:
      - ENTER
      - EXIT
      - IDLE
    GeoArn:
      type: string
      pattern: ^arn(:[a-z0-9]+([.-][a-z0-9]+)*):geo(:([a-z0-9]+([.-][a-z0-9]+)*))(:[0-9]+):((\*)|([-a-z]+[/][*-._\w]+))$
      maxLength: 1600
    GeoArnV2:
      type: string
      pattern: (^arn(:[a-z0-9]+([.-][a-z0-9]+)*):geo(:([a-z0-9]+([.-][a-z0-9]+)*))(:[0-9]+):((\*)|([-a-z]+[/][*-._\w]+))$)|(^arn(:[a-z0-9]+([.-][a-z0-9]+)*):(geo-routes|geo-places|geo-maps)(:((\*)|([a-z0-9]+([.-][a-z0-9]+)*)))::((provider[\/][*-._\w]+))$)
      maxLength: 1600
    Id:
      type: string
      pattern: ^[-._\p{L}\p{N}]+$
      minLength: 1
      maxLength: 100
    IntendedUse:
      type: string
      enum:
      - SingleUse
      - Storage
    KmsKeyId:
      type: string
      minLength: 1
      maxLength: 2048
    LanguageTag:
      type: string
      minLength: 2
      maxLength: 35
    LargeToken:
      type: string
      minLength: 1
      maxLength: 60000
    MapStyle:
      type: string
      pattern: ^[-._\w]+$
      minLength: 1
      maxLength: 100
    OptimizationMode:
      type: string
      enum:
      - FastestRoute
      - ShortestRoute
    Pci:
      type: integer
      default: 0
      minimum: 0
      maximum: 503
    PlaceCategory:
      type: string
      maxLength: 35
    PlaceId:
      type: string
    PlaceIndexSearchResultLimit:
      type: integer
      minimum: 1
      maximum: 50
    PlaceSupplementalCategory:
      type: string
      maxLength: 35
    PositionFiltering:
      type: string
      enum:
      - TimeBased
      - DistanceBased
      - AccuracyBased
    PricingPlan:
      type: string
      enum:
      - RequestBasedUsage
      - MobileAssetTracking
      - MobileAssetManagement
    RefererPattern:
      type: string
      pattern: ^([$\-._+!*\x{60}(),;/?:@=&\w]|%([0-9a-fA-F?]{2}|[0-9a-fA-F?]?[*]))+$
      maxLength: 253
    ResourceDescription:
      type: string
      minLength: 0
      maxLength: 1000
    ResourceName:
      type: string
      pattern: ^[-._\w]+$
      minLength: 1
      maxLength: 100
    RouteMatrixErrorCode:
      type: string
      enum:
      - RouteNotFound
      - RouteTooLong
      - PositionsNotFound
      - DestinationPositionNotFound
      - DeparturePositionNotFound
      - OtherValidationError
    Rsrp:
      type: integer
      minimum: -140
      maximum: -44
    SensitiveString:
      type: string
    SpeedUnit:
      type: string
      enum:
      - KilometersPerHour
      - MilesPerHour
    Status:
      type: string
      enum:
      - Active
      - Expired
    TagKey:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.,:/=+\-@]*)$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.,:/=+\-@]*)$
      minLength: 0
      maxLength: 256
    Token:
      type: string
      minLength: 1
      maxLength: 2000
    TravelMode:
      type: string
      enum:
      - Car
      - Truck
      - Walking
      - Bicycle
      - Motorcycle
    Uuid:
      type: string
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
    ValidationExceptionReason:
      type: string
      enum:
      - UnknownOperation
      - Missing
      - CannotParse
      - FieldValidationFailed
      - Other
      - UnknownField
    VehicleWeightUnit:
      type: string
      enum:
      - Kilograms
      - Pounds
