openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: location
  x-aws-serviceName: location
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-11-19'
  title: Amazon Location Service
  description: |-
    "Suite of geospatial services including Maps, Places, Routes, Tracking, and Geofencing"
servers:
- description: The Amazon Location Service regional endpoint
  url: https://geo.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ApiKey:
      type: string
      maxLength: 1000
    ApiKeyAction:
      type: string
      pattern: ^(geo|geo-routes|geo-places|geo-maps):\w*\*?$
      minLength: 5
      maxLength: 200
    ApiKeyActionList:
      type: array
      items:
        $ref: '#/components/schemas/ApiKeyAction'
    Arn:
      type: string
      pattern: ^arn(:[a-z0-9]+([.-][a-z0-9]+)*){2}(:([a-z0-9]+([.-][a-z0-9]+)*)?){2}:([^/].*)?$
      maxLength: 1600
    ArnList:
      type: array
      items:
        $ref: '#/components/schemas/Arn'
    Base64EncodedGeobuf:
      type: string
      format: byte
      maxLength: 600000
      x-sensitive: true
    BatchDeleteDevicePositionHistoryErrorList:
      type: array
      items:
        $ref: '#/components/schemas/BatchDeleteDevicePositionHistoryError'
    BatchDeleteGeofenceErrorList:
      type: array
      items:
        $ref: '#/components/schemas/BatchDeleteGeofenceError'
    BatchEvaluateGeofencesErrorList:
      type: array
      items:
        $ref: '#/components/schemas/BatchEvaluateGeofencesError'
    BatchGetDevicePositionErrorList:
      type: array
      items:
        $ref: '#/components/schemas/BatchGetDevicePositionError'
    BatchItemErrorCode:
      type: string
      enum:
      - AccessDeniedError
      - ConflictError
      - InternalServerError
      - ResourceNotFoundError
      - ThrottlingError
      - ValidationError
    BatchPutGeofenceErrorList:
      type: array
      items:
        $ref: '#/components/schemas/BatchPutGeofenceError'
    BatchPutGeofenceRequestEntryList:
      type: array
      items:
        $ref: '#/components/schemas/BatchPutGeofenceRequestEntry'
    BatchPutGeofenceSuccessList:
      type: array
      items:
        $ref: '#/components/schemas/BatchPutGeofenceSuccess'
    BatchUpdateDevicePositionErrorList:
      type: array
      items:
        $ref: '#/components/schemas/BatchUpdateDevicePositionError'
    BoundingBox:
      type: array
      items:
        type: number
      x-sensitive: true
    CountryCode3:
      type: string
      pattern: ^[A-Z]{3}$
      minLength: 3
      maxLength: 3
    CountryCode3OrEmpty:
      type: string
      pattern: ^[A-Z]{3}$|^$
      minLength: 0
      maxLength: 3
    CountryCodeList:
      type: array
      items:
        $ref: '#/components/schemas/CountryCode3'
    CustomLayer:
      type: string
      pattern: ^[-._\w]+$
      minLength: 1
      maxLength: 100
    CustomLayerList:
      type: array
      items:
        $ref: '#/components/schemas/CustomLayer'
    DeviceIdsList:
      type: array
      items:
        $ref: '#/components/schemas/Id'
    DevicePositionList:
      type: array
      items:
        $ref: '#/components/schemas/DevicePosition'
    DevicePositionUpdateList:
      type: array
      items:
        $ref: '#/components/schemas/DevicePositionUpdate'
    DimensionUnit:
      type: string
      enum:
      - Meters
      - Feet
    DistanceUnit:
      type: string
      enum:
      - Kilometers
      - Miles
    Earfcn:
      type: integer
      default: 0
      minimum: 0
      maximum: 262143
    EutranCellId:
      type: integer
      default: 0
      minimum: 0
      maximum: 268435455
    FilterPlaceCategoryList:
      type: array
      items:
        $ref: '#/components/schemas/PlaceCategory'
    ForecastedEventsList:
      type: array
      items:
        $ref: '#/components/schemas/ForecastedEvent'
    ForecastedGeofenceEventType:
      type: string
      enum:
      - ENTER
      - EXIT
      - IDLE
    GeoArn:
      type: string
      pattern: ^arn(:[a-z0-9]+([.-][a-z0-9]+)*):geo(:([a-z0-9]+([.-][a-z0-9]+)*))(:[0-9]+):((\*)|([-a-z]+[/][*-._\w]+))$
      maxLength: 1600
    GeoArnList:
      type: array
      items:
        $ref: '#/components/schemas/GeoArnV2'
    GeoArnV2:
      type: string
      pattern: (^arn(:[a-z0-9]+([.-][a-z0-9]+)*):geo(:([a-z0-9]+([.-][a-z0-9]+)*))(:[0-9]+):((\*)|([-a-z]+[/][*-._\w]+))$)|(^arn(:[a-z0-9]+([.-][a-z0-9]+)*):(geo-routes|geo-places|geo-maps)(:((\*)|([a-z0-9]+([.-][a-z0-9]+)*)))::((provider[\/][*-._\w]+))$)
      maxLength: 1600
    Id:
      type: string
      pattern: ^[-._\p{L}\p{N}]+$
      minLength: 1
      maxLength: 100
    IdList:
      type: array
      items:
        $ref: '#/components/schemas/Id'
    IntendedUse:
      type: string
      enum:
      - SingleUse
      - Storage
    KmsKeyId:
      type: string
      minLength: 1
      maxLength: 2048
    LanguageTag:
      type: string
      minLength: 2
      maxLength: 35
    LargeToken:
      type: string
      minLength: 1
      maxLength: 60000
    LegList:
      type: array
      items:
        $ref: '#/components/schemas/Leg'
    LineString:
      type: array
      items:
        $ref: '#/components/schemas/Position'
    LinearRing:
      type: array
      items:
        $ref: '#/components/schemas/Position'
    LinearRings:
      type: array
      items:
        $ref: '#/components/schemas/LinearRing'
    ListDevicePositionsResponseEntryList:
      type: array
      items:
        $ref: '#/components/schemas/ListDevicePositionsResponseEntry'
    ListGeofenceCollectionsResponseEntryList:
      type: array
      items:
        $ref: '#/components/schemas/ListGeofenceCollectionsResponseEntry'
    ListGeofenceResponseEntryList:
      type: array
      items:
        $ref: '#/components/schemas/ListGeofenceResponseEntry'
    ListKeysResponseEntryList:
      type: array
      items:
        $ref: '#/components/schemas/ListKeysResponseEntry'
    ListMapsResponseEntryList:
      type: array
      items:
        $ref: '#/components/schemas/ListMapsResponseEntry'
    ListPlaceIndexesResponseEntryList:
      type: array
      items:
        $ref: '#/components/schemas/ListPlaceIndexesResponseEntry'
    ListRouteCalculatorsResponseEntryList:
      type: array
      items:
        $ref: '#/components/schemas/ListRouteCalculatorsResponseEntry'
    ListTrackersResponseEntryList:
      type: array
      items:
        $ref: '#/components/schemas/ListTrackersResponseEntry'
    LteCellDetailsList:
      type: array
      items:
        $ref: '#/components/schemas/LteCellDetails'
    LteNetworkMeasurementsList:
      type: array
      items:
        $ref: '#/components/schemas/LteNetworkMeasurements'
    MapStyle:
      type: string
      pattern: ^[-._\w]+$
      minLength: 1
      maxLength: 100
    NearestDistance:
      type: number
      format: double
      default: 0
      minimum: 0
    OptimizationMode:
      type: string
      enum:
      - FastestRoute
      - ShortestRoute
    Pci:
      type: integer
      default: 0
      minimum: 0
      maximum: 503
    PlaceCategory:
      type: string
      maxLength: 35
    PlaceCategoryList:
      type: array
      items:
        $ref: '#/components/schemas/PlaceCategory'
    PlaceId:
      type: string
    PlaceIndexSearchResultLimit:
      type: integer
      minimum: 1
      maximum: 50
    PlaceSupplementalCategory:
      type: string
      maxLength: 35
    PlaceSupplementalCategoryList:
      type: array
      items:
        $ref: '#/components/schemas/PlaceSupplementalCategory'
    Position:
      type: array
      items:
        type: number
      x-sensitive: true
    PositionFiltering:
      type: string
      enum:
      - TimeBased
      - DistanceBased
      - AccuracyBased
    PositionList:
      type: array
      items:
        $ref: '#/components/schemas/Position'
    PositionPropertyMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    PricingPlan:
      type: string
      enum:
      - RequestBasedUsage
      - MobileAssetTracking
      - MobileAssetManagement
    PropertyMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    RefererPattern:
      type: string
      pattern: ^([$\-._+!*\x{60}(),;/?:@=&\w]|%([0-9a-fA-F?]{2}|[0-9a-fA-F?]?[*]))+$
      maxLength: 253
    RefererPatternList:
      type: array
      items:
        $ref: '#/components/schemas/RefererPattern'
    ResourceDescription:
      type: string
      minLength: 0
      maxLength: 1000
    ResourceName:
      type: string
      pattern: ^[-._\w]+$
      minLength: 1
      maxLength: 100
    RouteMatrix:
      type: array
      items:
        $ref: '#/components/schemas/RouteMatrixRow'
    RouteMatrixErrorCode:
      type: string
      enum:
      - RouteNotFound
      - RouteTooLong
      - PositionsNotFound
      - DestinationPositionNotFound
      - DeparturePositionNotFound
      - OtherValidationError
    RouteMatrixRow:
      type: array
      items:
        $ref: '#/components/schemas/RouteMatrixEntry'
    Rsrp:
      type: integer
      minimum: -140
      maximum: -44
    Rsrq:
      type: number
      format: float
      minimum: -19.5
      maximum: -3
    SearchForPositionResultList:
      type: array
      items:
        $ref: '#/components/schemas/SearchForPositionResult'
    SearchForSuggestionsResultList:
      type: array
      items:
        $ref: '#/components/schemas/SearchForSuggestionsResult'
    SearchForTextResultList:
      type: array
      items:
        $ref: '#/components/schemas/SearchForTextResult'
    SensitiveString:
      type: string
    SpeedUnit:
      type: string
      enum:
      - KilometersPerHour
      - MilesPerHour
    Status:
      type: string
      enum:
      - Active
      - Expired
    StepList:
      type: array
      items:
        $ref: '#/components/schemas/Step'
    TagKey:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.,:/=+\-@]*)$
      minLength: 1
      maxLength: 128
    TagKeys:
      type: array
      items:
        type: string
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.,:/=+\-@]*)$
      minLength: 0
      maxLength: 256
    Timestamp:
      type: string
      format: date-time
    Token:
      type: string
      minLength: 1
      maxLength: 2000
    TravelMode:
      type: string
      enum:
      - Car
      - Truck
      - Walking
      - Bicycle
      - Motorcycle
    Uuid:
      type: string
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
    ValidationExceptionFieldList:
      type: array
      items:
        $ref: '#/components/schemas/ValidationExceptionField'
    ValidationExceptionReason:
      type: string
      enum:
      - UnknownOperation
      - Missing
      - CannotParse
      - FieldValidationFailed
      - Other
      - UnknownField
    VehicleWeightUnit:
      type: string
      enum:
      - Kilograms
      - Pounds
    WaypointPositionList:
      type: array
      items:
        $ref: '#/components/schemas/Position'
    WiFiAccessPointList:
      type: array
      items:
        $ref: '#/components/schemas/WiFiAccessPoint'
