openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: m2
  x-aws-serviceName: m2
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2021-04-28'
  title: AWSMainframeModernization
  description: |-
    Amazon Web Services Mainframe Modernization provides tools and resources to help you plan and implement migration and modernization from mainframes to Amazon Web Services managed runtime environments. It provides tools for analyzing existing mainframe applications, developing or updating mainframe applications using COBOL or PL/I, and implementing an automated pipeline for continuous integration and continuous delivery (CI/CD) of the applications.
servers:
- description: The AWSMainframeModernization regional endpoint
  url: https://m2.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ApplicationDeploymentLifecycle:
      type: string
      enum:
      - Deploying
      - Deployed
    ApplicationLifecycle:
      type: string
      enum:
      - Creating
      - Created
      - Available
      - Ready
      - Starting
      - Running
      - Stopping
      - Stopped
      - Failed
      - Deleting
      - Deleting From Environment
    ApplicationVersionLifecycle:
      type: string
      enum:
      - Creating
      - Available
      - Failed
    Arn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-iso|aws-iso-[a-z]{1}|aws-us-gov):[A-Za-z0-9][A-Za-z0-9_/.-]{0,62}:([a-z]{2}-((iso[a-z]{0,1}-)|(gov-)){0,1}[a-z]+-[0-9]|):[0-9]{12}:[A-Za-z0-9/][A-Za-z0-9:_/+=,@.-]{0,1023}$
    AuthSecretsManagerArn:
      type: string
      minLength: 20
      maxLength: 2048
    BatchJobExecutionStatus:
      type: string
      enum:
      - Submitting
      - Holding
      - Dispatching
      - Running
      - Cancelling
      - Cancelled
      - Succeeded
      - Failed
      - Purged
      - Succeeded With Warning
    BatchJobType:
      type: string
      enum:
      - VSE
      - JES2
      - JES3
    BatchParamKey:
      type: string
      pattern: ^[A-Za-z][A-Za-z0-9]{1,31}$
      minLength: 1
      maxLength: 32
    BatchParamValue:
      type: string
      minLength: 0
      maxLength: 1024
    Boolean:
      type: boolean
      default: false
    CapacityValue:
      type: integer
    ClientToken:
      type: string
      pattern: ^[!-~]+$
      maxLength: 128
    DataSetTaskLifecycle:
      type: string
      enum:
      - Creating
      - Running
      - Completed
      - Failed
    DeploymentLifecycle:
      type: string
      enum:
      - Deploying
      - Succeeded
      - Failed
      - Updating Deployment
    EngineType:
      type: string
      enum:
      - microfocus
      - bluage
    EngineVersion:
      type: string
      pattern: ^\S{1,10}$
    EntityDescription:
      type: string
      minLength: 0
      maxLength: 500
    EntityName:
      type: string
      pattern: ^[A-Za-z0-9][A-Za-z0-9_\-]{1,59}$
    EnvironmentLifecycle:
      type: string
      enum:
      - Creating
      - Available
      - Updating
      - Deleting
      - Failed
      - UnHealthy
    Identifier:
      type: string
      pattern: ^\S{1,80}$
    Integer:
      type: integer
      default: 0
    KMSKeyId:
      type: string
      pattern: ^[a-zA-Z0-9:/_-]+$
      minLength: 1
      maxLength: 256
    LogGroupIdentifier:
      type: string
      minLength: 1
      maxLength: 512
    MaxResults:
      type: integer
      minimum: 1
      maximum: 2000
    NetworkType:
      type: string
      enum:
      - ipv4
      - dual
    NextToken:
      type: string
      pattern: ^\S{1,2000}$
    String100:
      type: string
      pattern: ^\S{1,100}$
    String20:
      type: string
      pattern: ^\S{1,20}$
    String200:
      type: string
      pattern: ^\S{1,200}$
    String2000:
      type: string
      pattern: ^\S{1,2000}$
    String50:
      type: string
      pattern: ^\S{1,50}$
    StringFree65000:
      type: string
      minLength: 1
      maxLength: 65000
    TagKey:
      type: string
      pattern: ^(?!aws:).+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    ValidationExceptionReason:
      type: string
      enum:
      - unknownOperation
      - cannotParse
      - featureNotAvailable
      - unsupportedEngineVersion
      - fieldValidationFailed
      - other
    Version:
      type: integer
      minimum: 1
