openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: macie2
  x-aws-serviceName: macie2
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-01-01'
  title: Amazon Macie 2
  description: |-
    Amazon Macie
servers:
- description: The Amazon Macie 2 regional endpoint
  url: https://macie2.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ClassificationScopeId:
      type: string
      pattern: ^[0-9a-z]*$
    ClassificationScopeName:
      type: string
      pattern: ^[0-9a-zA-Z_\\-]*$
    MaxResults:
      type: integer
      minimum: 1
      maximum: 25
    NextToken:
      type: string
      pattern: ^.*$
    S3BucketName:
      type: string
      pattern: ^[A-Za-z0-9.\-_]{3,255}$
    SensitivityInspectionTemplateId:
      type: string
    __boolean:
      type: boolean
    __integer:
      type: integer
    __string:
      type: string
    __stringMin1Max1024PatternSS:
      type: string
      pattern: ^[\s\S]+$
      minLength: 1
      maxLength: 1024
    __stringMin1Max128:
      type: string
      minLength: 1
      maxLength: 128
    __stringMin1Max128Pattern:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 128
    __stringMin1Max2048:
      type: string
      minLength: 1
      maxLength: 2048
    __stringMin1Max512PatternSS:
      type: string
      pattern: ^[\s\S]+$
      minLength: 1
      maxLength: 512
    __stringMin1Max64PatternW:
      type: string
      pattern: ^[\w+=,.@-]*$
      minLength: 1
      maxLength: 64
    __stringMin22Max22PatternAZ0922:
      type: string
      pattern: ^[a-z0-9]{22}$
      minLength: 22
      maxLength: 22
    __stringMin3Max255PatternAZaZ093255:
      type: string
      pattern: ^[A-Za-z0-9.\-_]{3,255}$
      minLength: 3
      maxLength: 255
    __stringMin71Max89PatternArnAwsAwsCnAwsUsGovMacie2AZ19920D12AllowListAZ0922:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-us-gov):macie2:[a-z1-9-]{9,20}:\d{12}:allow-list\/[a-z0-9]{22}$
      minLength: 71
      maxLength: 89
