openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: managedblockchain
  x-aws-serviceName: managedblockchain
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-09-24'
  title: Amazon Managed Blockchain
  description: |-
    Amazon Managed Blockchain is a fully managed service for creating and managing blockchain networks using open-source frameworks. Blockchain allows you to build applications where multiple parties can securely and transparently run transactions and share data without the need for a trusted, central authority.

    Managed Blockchain supports the Hyperledger Fabric and Ethereum open-source frameworks. Because of fundamental differences between the frameworks, some API actions or data types may only apply in the context of one framework and not the other. For example, actions related to Hyperledger Fabric network members such as `CreateMember` and `DeleteMember` don't apply to Ethereum.

    The description for each action indicates the framework or frameworks to which it applies. Data types and properties that apply only in the context of a particular framework are similarly indicated.
servers:
- description: The Amazon Managed Blockchain regional endpoint
  url: https://managedblockchain.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccessorBillingTokenString:
      type: string
      minLength: 42
      maxLength: 42
    AccessorListMaxResults:
      type: integer
      minimum: 1
      maximum: 50
    ArnString:
      type: string
      pattern: ^arn:.+:.+:.+:.+:.+$
      minLength: 1
      maxLength: 1011
    AvailabilityZoneString:
      type: string
    ClientRequestTokenString:
      type: string
      minLength: 1
      maxLength: 64
    DescriptionString:
      type: string
      minLength: 0
      maxLength: 128
    Enabled:
      type: boolean
    ExceptionMessage:
      type: string
    FrameworkVersionString:
      type: string
      minLength: 1
      maxLength: 8
    InstanceTypeString:
      type: string
    IsOwned:
      type: boolean
    MemberListMaxResults:
      type: integer
      minimum: 1
      maximum: 20
    NameString:
      type: string
      pattern: \S
      minLength: 1
      maxLength: 64
    NetworkListMaxResults:
      type: integer
      minimum: 1
      maximum: 10
    NetworkMemberNameString:
      type: string
      pattern: ^(?!-|[0-9])(?!.*-$)(?!.*?--)[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 64
    NodeListMaxResults:
      type: integer
      minimum: 1
      maximum: 20
    PaginationToken:
      type: string
      minLength: 0
      maxLength: 128
    PasswordString:
      type: string
      pattern: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?!.*[@'\\"/])[a-zA-Z0-9\S]*$
      minLength: 8
      maxLength: 32
    PrincipalString:
      type: string
    ProposalDurationInt:
      type: integer
      minimum: 1
      maximum: 168
    ProposalListMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ResourceIdString:
      type: string
      minLength: 1
      maxLength: 32
    String:
      type: string
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    ThresholdPercentageInt:
      type: integer
      minimum: 0
      maximum: 100
    UsernameString:
      type: string
      pattern: ^[a-zA-Z][a-zA-Z0-9]*$
      minLength: 1
      maxLength: 16
    VoteCount:
      type: integer
