openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: marketplace_deployment
  x-aws-serviceName: marketplacedeployment
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2023-01-25'
  title: AWS Marketplace Deployment Service
  description: |-
    The AWS Marketplace Deployment Service supports the Quick Launch experience, which is a deployment option for software as a service (SaaS) products. Quick Launch simplifies and reduces the time, resources, and steps required to configure, deploy, and launch a products. The AWS Marketplace Deployment Service provides sellers with a secure method for passing deployment parameters, such as API keys and external IDs, to buyers during the Quick Launch experience.
servers:
- description: The AWS Marketplace Deployment Service regional endpoint
  url: https://deployment-marketplace.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Catalog:
      type: string
      pattern: ^[a-zA-Z_-]+$
      minLength: 1
      maxLength: 64
    ClientToken:
      type: string
      pattern: ^[a-zA-Z0-9/_+=.:@-]+$
      minLength: 32
      maxLength: 64
    DeploymentParameterName:
      type: string
      pattern: ^[a-zA-Z0-9/_+=.@-]+$
      minLength: 1
      maxLength: 400
    DeploymentParameterResourceIdentifier:
      type: string
      pattern: ^dp-[a-zA-Z0-9]+$
      minLength: 1
      maxLength: 32
    ResourceArn:
      type: string
      pattern: ^[a-zA-Z0-9:*/-]+$
      minLength: 1
      maxLength: 2048
    ResourceId:
      type: string
      pattern: ^[A-Za-z0-9_/-]+$
      minLength: 1
      maxLength: 64
    SecretString:
      type: string
      minLength: 1
      maxLength: 15000
    TagKey:
      type: string
      pattern: ^[a-zA-Z0-9/_+=.:@-]+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^[a-zA-Z0-9/_+=.:@-]+$
      minLength: 1
      maxLength: 256
