openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: marketplace_catalog
  x-aws-serviceName: marketplacecatalog
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-09-17'
  title: AWS Marketplace Catalog Service
  description: |-
    Catalog API actions allow you to manage your entities through list, describe, and update capabilities. An entity can be a product or an offer on AWS Marketplace.

    You can automate your entity update process by integrating the AWS Marketplace Catalog API with your AWS Marketplace product build or deployment pipelines. You can also create your own applications on top of the Catalog API to manage your products on AWS Marketplace.
servers:
- description: The AWS Marketplace Catalog Service regional endpoint
  url: https://catalog.marketplace.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ARN:
      type: string
      pattern: ^[a-zA-Z0-9:*/-]+$
      minLength: 1
      maxLength: 2048
    AmiProductEntityIdString:
      type: string
      pattern: ^[a-zA-Z0-9][.a-zA-Z0-9/-]+[a-zA-Z0-9]$
      minLength: 1
      maxLength: 255
    AmiProductTitleString:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 255
    BatchDescribeErrorCodeString:
      type: string
      pattern: ^[a-zA-Z_]+$
      minLength: 1
      maxLength: 72
    BatchDescribeErrorMessageContent:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 2048
    Catalog:
      type: string
      pattern: ^[a-zA-Z]+$
      minLength: 1
      maxLength: 64
    ChangeName:
      type: string
      pattern: ^[a-zA-Z]$
      minLength: 1
      maxLength: 72
    ChangeSetName:
      type: string
      pattern: ^[\w\s+=.:@-]+$
      minLength: 1
      maxLength: 100
    ChangeType:
      type: string
      pattern: ^[A-Z][\w]*$
      minLength: 1
      maxLength: 255
    ClientRequestToken:
      type: string
      pattern: ^[!-~]+$
      minLength: 1
      maxLength: 64
    ContainerProductEntityIdString:
      type: string
      pattern: ^[a-zA-Z0-9][.a-zA-Z0-9/-]+[a-zA-Z0-9]$
      minLength: 1
      maxLength: 255
    ContainerProductTitleString:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 255
    DataProductEntityIdString:
      type: string
      pattern: ^[a-zA-Z0-9][.a-zA-Z0-9/-]+[a-zA-Z0-9]$
      minLength: 1
      maxLength: 255
    DataProductTitleString:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 255
    DateTimeISO8601:
      type: string
      pattern: ^([\d]{4})\-(1[0-2]|0[1-9])\-(3[01]|0[1-9]|[12][\d])T(2[0-3]|[01][\d]):([0-5][\d]):([0-5][\d])Z$
      minLength: 20
      maxLength: 20
    EntityId:
      type: string
      pattern: ^[a-zA-Z0-9][.a-zA-Z0-9/-]+[a-zA-Z0-9]$
      minLength: 1
      maxLength: 255
    EntityNameString:
      type: string
      pattern: ^\\S+[\\S\\s]*$
      minLength: 1
      maxLength: 255
    EntityType:
      type: string
      pattern: ^[a-zA-Z]+$
      minLength: 1
      maxLength: 255
    ErrorCodeString:
      type: string
      pattern: ^[a-zA-Z_]+$
      minLength: 1
      maxLength: 72
    ExceptionMessageContent:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 2048
    FilterName:
      type: string
      pattern: ^[a-zA-Z]+$
      minLength: 1
      maxLength: 255
    FilterValueContent:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 255
    Identifier:
      type: string
      pattern: ^[\w\-@]+$
      minLength: 1
      maxLength: 255
    Json:
      type: string
      pattern: ^[\s]*\{[\s\S]*\}[\s]*$
      minLength: 2
      maxLength: 16384
    ListChangeSetsMaxResultInteger:
      type: integer
      minimum: 1
      maximum: 20
    ListEntitiesMaxResultInteger:
      type: integer
      minimum: 1
      maximum: 50
    NextToken:
      type: string
      pattern: ^[\w+=.:@\-\/]$
      minLength: 1
      maxLength: 2048
    OfferBuyerAccountsFilterWildcard:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 255
    OfferBuyerAccountsString:
      type: string
      pattern: ^\d{12}$
      minLength: 12
      maxLength: 12
    OfferEntityIdString:
      type: string
      pattern: ^[a-zA-Z0-9][.a-zA-Z0-9/-]+[a-zA-Z0-9]$
      minLength: 1
      maxLength: 255
    OfferNameString:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 150
    OfferProductIdString:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 255
    OfferResaleAuthorizationIdString:
      type: string
      pattern: ^[a-zA-Z0-9][.a-zA-Z0-9/-]+[a-zA-Z0-9]$
      minLength: 1
      maxLength: 255
    ResaleAuthorizationEntityIdString:
      type: string
      pattern: ^[a-zA-Z0-9][.a-zA-Z0-9/-]+[a-zA-Z0-9]$
      minLength: 1
      maxLength: 255
    ResaleAuthorizationManufacturerAccountIdFilterWildcard:
      type: string
      pattern: ^\d{12}$
      minLength: 12
      maxLength: 12
    ResaleAuthorizationManufacturerAccountIdString:
      type: string
      pattern: ^\d{12}$
      minLength: 12
      maxLength: 12
    ResaleAuthorizationManufacturerLegalNameFilterWildcard:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 255
    ResaleAuthorizationManufacturerLegalNameString:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 255
    ResaleAuthorizationNameFilterWildcard:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 255
    ResaleAuthorizationNameString:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 255
    ResaleAuthorizationOfferExtendedStatusString:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 255
    ResaleAuthorizationProductIdFilterWildcard:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 255
    ResaleAuthorizationProductIdString:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 255
    ResaleAuthorizationProductNameFilterWildcard:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 255
    ResaleAuthorizationProductNameString:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 255
    ResaleAuthorizationResellerAccountIDFilterWildcard:
      type: string
      pattern: ^\d{12}$
      minLength: 12
      maxLength: 12
    ResaleAuthorizationResellerAccountIDString:
      type: string
      pattern: ^\d{12}$
      minLength: 12
      maxLength: 12
    ResaleAuthorizationResellerLegalNameFilterWildcard:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 255
    ResaleAuthorizationResellerLegalNameString:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 255
    ResourceARN:
      type: string
      pattern: ^arn:[\w+=/,.@-]+:aws-marketplace:[\w+=/,.@-]*:[0-9]+:[\w+=,.@-]+(/[\w+=,.@-]+)*$
      minLength: 1
      maxLength: 255
    ResourceId:
      type: string
      pattern: ^[\w\-]+$
      minLength: 1
      maxLength: 255
    ResourcePolicyJson:
      type: string
      pattern: ^[\u0009\u000A\u000D\u0020-\u00FF]+$
      minLength: 1
      maxLength: 10240
    SaaSProductEntityIdString:
      type: string
      pattern: ^[a-zA-Z0-9][.a-zA-Z0-9/-]+[a-zA-Z0-9]$
      minLength: 1
      maxLength: 255
    SaaSProductTitleString:
      type: string
      pattern: ^(.)+$
      minLength: 1
      maxLength: 255
    SortBy:
      type: string
      pattern: ^[a-zA-Z]+$
      minLength: 1
      maxLength: 255
    TagKey:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
      minLength: 0
      maxLength: 256
    VisibilityValue:
      type: string
      pattern: ^[a-zA-Z]+$
      minLength: 1
      maxLength: 64
