openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: mediapackage_vod
  x-aws-serviceName: mediapackagevod
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-11-07'
  title: AWS Elemental MediaPackage VOD
  description: |-
    AWS Elemental MediaPackage VOD
servers:
- description: The AWS Elemental MediaPackage VOD regional endpoint
  url: https://mediapackage-vod.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AdMarkers:
      type: string
      enum:
      - NONE
      - SCTE35_ENHANCED
      - PASSTHROUGH
    EncryptionMethod:
      type: string
      enum:
      - AES_128
      - SAMPLE_AES
    ManifestLayout:
      type: string
      enum:
      - FULL
      - COMPACT
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
    PresetSpeke20Audio:
      type: string
      enum:
      - PRESET-AUDIO-1
      - PRESET-AUDIO-2
      - PRESET-AUDIO-3
      - SHARED
      - UNENCRYPTED
    PresetSpeke20Video:
      type: string
      enum:
      - PRESET-VIDEO-1
      - PRESET-VIDEO-2
      - PRESET-VIDEO-3
      - PRESET-VIDEO-4
      - PRESET-VIDEO-5
      - PRESET-VIDEO-6
      - PRESET-VIDEO-7
      - PRESET-VIDEO-8
      - SHARED
      - UNENCRYPTED
    Profile:
      type: string
      enum:
      - NONE
      - HBBTV_1_5
    ScteMarkersSource:
      type: string
      enum:
      - SEGMENTS
      - MANIFEST
    SegmentTemplateFormat:
      type: string
      enum:
      - NUMBER_WITH_TIMELINE
      - TIME_WITH_TIMELINE
      - NUMBER_WITH_DURATION
    StreamOrder:
      type: string
      enum:
      - ORIGINAL
      - VIDEO_BITRATE_ASCENDING
      - VIDEO_BITRATE_DESCENDING
    Tags:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/__string'
      description: A collection of tags associated with a resource
    __PeriodTriggersElement:
      type: string
      enum:
      - ADS
    __boolean:
      type: boolean
    __integer:
      type: integer
    __listOfAssetShallow:
      type: array
      items:
        $ref: '#/components/schemas/AssetShallow'
    __listOfDashManifest:
      type: array
      items:
        $ref: '#/components/schemas/DashManifest'
    __listOfEgressEndpoint:
      type: array
      items:
        $ref: '#/components/schemas/EgressEndpoint'
    __listOfHlsManifest:
      type: array
      items:
        $ref: '#/components/schemas/HlsManifest'
    __listOfMssManifest:
      type: array
      items:
        $ref: '#/components/schemas/MssManifest'
    __listOfPackagingConfiguration:
      type: array
      items:
        $ref: '#/components/schemas/PackagingConfiguration'
    __listOfPackagingGroup:
      type: array
      items:
        $ref: '#/components/schemas/PackagingGroup'
    __listOf__PeriodTriggersElement:
      type: array
      items:
        $ref: '#/components/schemas/__PeriodTriggersElement'
    __listOf__string:
      type: array
      items:
        $ref: '#/components/schemas/__string'
    __mapOf__string:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/__string'
    __string:
      type: string
