openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: mediapackage
  x-aws-serviceName: mediapackage
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-10-12'
  title: AWS Elemental MediaPackage
  description: |-
    AWS Elemental MediaPackage
servers:
- description: The AWS Elemental MediaPackage regional endpoint
  url: https://mediapackage.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AdMarkers:
      type: string
      enum:
      - NONE
      - SCTE35_ENHANCED
      - PASSTHROUGH
      - DATERANGE
    AdTriggers:
      type: array
      items:
        $ref: '#/components/schemas/__AdTriggersElement'
      description: 'A list of SCTE-35 message types that are treated as ad markers
        in the output.  If empty, no

        ad markers are output.  Specify multiple items to create ad markers for all
        of the included

        message types.'
    AdsOnDeliveryRestrictions:
      type: string
      enum:
      - NONE
      - RESTRICTED
      - UNRESTRICTED
      - BOTH
      description: 'This setting allows the delivery restriction flags on SCTE-35
        segmentation descriptors to

        determine whether a message signals an ad.  Choosing "NONE" means no SCTE-35
        messages become

        ads.  Choosing "RESTRICTED" means SCTE-35 messages of the types specified
        in AdTriggers that

        contain delivery restrictions will be treated as ads.  Choosing "UNRESTRICTED"
        means SCTE-35

        messages of the types specified in AdTriggers that do not contain delivery
        restrictions will

        be treated as ads.  Choosing "BOTH" means all SCTE-35 messages of the types
        specified in

        AdTriggers will be treated as ads.  Note that Splice Insert messages do not
        have these flags

        and are always treated as ads if specified in AdTriggers.'
    CmafEncryptionMethod:
      type: string
      enum:
      - SAMPLE_AES
      - AES_CTR
      description: The encryption method to use.
    EncryptionMethod:
      type: string
      enum:
      - AES_128
      - SAMPLE_AES
    ManifestLayout:
      type: string
      enum:
      - FULL
      - COMPACT
      - DRM_TOP_LEVEL_COMPACT
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
    Origination:
      type: string
      enum:
      - ALLOW
      - DENY
    PlaylistType:
      type: string
      enum:
      - NONE
      - EVENT
      - VOD
    PresetSpeke20Audio:
      type: string
      enum:
      - PRESET-AUDIO-1
      - PRESET-AUDIO-2
      - PRESET-AUDIO-3
      - SHARED
      - UNENCRYPTED
    PresetSpeke20Video:
      type: string
      enum:
      - PRESET-VIDEO-1
      - PRESET-VIDEO-2
      - PRESET-VIDEO-3
      - PRESET-VIDEO-4
      - PRESET-VIDEO-5
      - PRESET-VIDEO-6
      - PRESET-VIDEO-7
      - PRESET-VIDEO-8
      - SHARED
      - UNENCRYPTED
    Profile:
      type: string
      enum:
      - NONE
      - HBBTV_1_5
      - HYBRIDCAST
      - DVB_DASH_2014
    SegmentTemplateFormat:
      type: string
      enum:
      - NUMBER_WITH_TIMELINE
      - TIME_WITH_TIMELINE
      - NUMBER_WITH_DURATION
    SensitiveString:
      type: string
    Status:
      type: string
      enum:
      - IN_PROGRESS
      - SUCCEEDED
      - FAILED
    StreamOrder:
      type: string
      enum:
      - ORIGINAL
      - VIDEO_BITRATE_ASCENDING
      - VIDEO_BITRATE_DESCENDING
    Tags:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/__string'
      description: A collection of tags associated with a resource
    UtcTiming:
      type: string
      enum:
      - NONE
      - HTTP-HEAD
      - HTTP-ISO
      - HTTP-XSDATE
    __AdTriggersElement:
      type: string
      enum:
      - SPLICE_INSERT
      - BREAK
      - PROVIDER_ADVERTISEMENT
      - DISTRIBUTOR_ADVERTISEMENT
      - PROVIDER_PLACEMENT_OPPORTUNITY
      - DISTRIBUTOR_PLACEMENT_OPPORTUNITY
      - PROVIDER_OVERLAY_PLACEMENT_OPPORTUNITY
      - DISTRIBUTOR_OVERLAY_PLACEMENT_OPPORTUNITY
    __PeriodTriggersElement:
      type: string
      enum:
      - ADS
    __boolean:
      type: boolean
    __integer:
      type: integer
    __listOfChannel:
      type: array
      items:
        $ref: '#/components/schemas/Channel'
    __listOfHarvestJob:
      type: array
      items:
        $ref: '#/components/schemas/HarvestJob'
    __listOfHlsManifest:
      type: array
      items:
        $ref: '#/components/schemas/HlsManifest'
    __listOfHlsManifestCreateOrUpdateParameters:
      type: array
      items:
        $ref: '#/components/schemas/HlsManifestCreateOrUpdateParameters'
    __listOfIngestEndpoint:
      type: array
      items:
        $ref: '#/components/schemas/IngestEndpoint'
    __listOfOriginEndpoint:
      type: array
      items:
        $ref: '#/components/schemas/OriginEndpoint'
    __listOf__PeriodTriggersElement:
      type: array
      items:
        $ref: '#/components/schemas/__PeriodTriggersElement'
    __listOf__string:
      type: array
      items:
        $ref: '#/components/schemas/__string'
    __mapOf__string:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/__string'
    __string:
      type: string
