openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: medialive
  x-aws-serviceName: medialive
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-10-14'
  title: AWS Elemental MediaLive
  description: |-
    API for AWS Elemental MediaLive
servers:
- description: The AWS Elemental MediaLive regional endpoint
  url: https://medialive.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
      description: Placeholder documentation for MaxResults
    __boolean:
      type: boolean
      description: Placeholder documentation for __boolean
    __integer:
      type: integer
      description: Placeholder documentation for __integer
    __integerMax5:
      type: integer
      maximum: 5
      description: Placeholder documentation for __integerMax5
    __integerMin0:
      type: integer
      minimum: 0
      description: Placeholder documentation for __integerMin0
    __integerMin0Max10:
      type: integer
      minimum: 0
      maximum: 10
      description: Placeholder documentation for __integerMin0Max10
    __integerMin0Max100:
      type: integer
      minimum: 0
      maximum: 100
      description: Placeholder documentation for __integerMin0Max100
    __integerMin0Max1000:
      type: integer
      minimum: 0
      maximum: 1000
      description: Placeholder documentation for __integerMin0Max1000
    __integerMin0Max10000:
      type: integer
      minimum: 0
      maximum: 10000
      description: Placeholder documentation for __integerMin0Max10000
    __integerMin0Max1000000:
      type: integer
      minimum: 0
      maximum: 1000000
      description: Placeholder documentation for __integerMin0Max1000000
    __integerMin0Max100000000:
      type: integer
      minimum: 0
      maximum: 100000000
      description: Placeholder documentation for __integerMin0Max100000000
    __integerMin0Max128:
      type: integer
      minimum: 0
      maximum: 128
      description: Placeholder documentation for __integerMin0Max128
    __integerMin0Max15:
      type: integer
      minimum: 0
      maximum: 15
      description: Placeholder documentation for __integerMin0Max15
    __integerMin0Max2000:
      type: integer
      minimum: 0
      maximum: 2000
      description: Placeholder documentation for __integerMin0Max2000
    __integerMin0Max255:
      type: integer
      minimum: 0
      maximum: 255
      description: Placeholder documentation for __integerMin0Max255
    __integerMin0Max30:
      type: integer
      minimum: 0
      maximum: 30
      description: Placeholder documentation for __integerMin0Max30
    __integerMin0Max32768:
      type: integer
      minimum: 0
      maximum: 32768
      description: Placeholder documentation for __integerMin0Max32768
    __integerMin0Max3600:
      type: integer
      minimum: 0
      maximum: 3600
      description: Placeholder documentation for __integerMin0Max3600
    __integerMin0Max500:
      type: integer
      minimum: 0
      maximum: 500
      description: Placeholder documentation for __integerMin0Max500
    __integerMin0Max600:
      type: integer
      minimum: 0
      maximum: 600
      description: Placeholder documentation for __integerMin0Max600
    __integerMin0Max65535:
      type: integer
      minimum: 0
      maximum: 65535
      description: Placeholder documentation for __integerMin0Max65535
    __integerMin0Max65536:
      type: integer
      minimum: 0
      maximum: 65536
      description: Placeholder documentation for __integerMin0Max65536
    __integerMin0Max7:
      type: integer
      minimum: 0
      maximum: 7
      description: Placeholder documentation for __integerMin0Max7
    __integerMin0Max8191:
      type: integer
      minimum: 0
      maximum: 8191
      description: Placeholder documentation for __integerMin0Max8191
    __integerMin1:
      type: integer
      minimum: 1
      description: Placeholder documentation for __integerMin1
    __integerMin100:
      type: integer
      minimum: 100
      description: Placeholder documentation for __integerMin100
    __integerMin1000:
      type: integer
      minimum: 1000
      description: Placeholder documentation for __integerMin1000
    __integerMin1000000Max100000000:
      type: integer
      minimum: 1000000
      maximum: 100000000
      description: Placeholder documentation for __integerMin1000000Max100000000
    __integerMin100000Max100000000:
      type: integer
      minimum: 100000
      maximum: 100000000
      description: Placeholder documentation for __integerMin100000Max100000000
    __integerMin100000Max40000000:
      type: integer
      minimum: 100000
      maximum: 40000000
      description: Placeholder documentation for __integerMin100000Max40000000
    __integerMin100000Max80000000:
      type: integer
      minimum: 100000
      maximum: 80000000
      description: Placeholder documentation for __integerMin100000Max80000000
    __integerMin1000Max30000:
      type: integer
      minimum: 1000
      maximum: 30000
      description: Placeholder documentation for __integerMin1000Max30000
    __integerMin10Max86400:
      type: integer
      minimum: 10
      maximum: 86400
      description: Placeholder documentation for __integerMin10Max86400
    __integerMin1Max10:
      type: integer
      minimum: 1
      maximum: 10
      description: Placeholder documentation for __integerMin1Max10
    __integerMin1Max1000000:
      type: integer
      minimum: 1
      maximum: 1000000
      description: Placeholder documentation for __integerMin1Max1000000
    __integerMin1Max16:
      type: integer
      minimum: 1
      maximum: 16
      description: Placeholder documentation for __integerMin1Max16
    __integerMin1Max20:
      type: integer
      minimum: 1
      maximum: 20
      description: Placeholder documentation for __integerMin1Max20
    __integerMin1Max3003:
      type: integer
      minimum: 1
      maximum: 3003
      description: Placeholder documentation for __integerMin1Max3003
    __integerMin1Max31:
      type: integer
      minimum: 1
      maximum: 31
      description: Placeholder documentation for __integerMin1Max31
    __integerMin1Max32:
      type: integer
      minimum: 1
      maximum: 32
      description: Placeholder documentation for __integerMin1Max32
    __integerMin1Max3600000:
      type: integer
      minimum: 1
      maximum: 3600000
      description: Placeholder documentation for __integerMin1Max3600000
    __integerMin1Max4:
      type: integer
      minimum: 1
      maximum: 4
      description: Placeholder documentation for __integerMin1Max4
    __integerMin1Max5:
      type: integer
      minimum: 1
      maximum: 5
      description: Placeholder documentation for __integerMin1Max5
    __integerMin1Max51:
      type: integer
      minimum: 1
      maximum: 51
      description: Placeholder documentation for __integerMin1Max51
    __integerMin1Max6:
      type: integer
      minimum: 1
      maximum: 6
      description: Placeholder documentation for __integerMin1Max6
    __integerMin1Max8:
      type: integer
      minimum: 1
      maximum: 8
      description: Placeholder documentation for __integerMin1Max8
    __integerMin1Max800:
      type: integer
      minimum: 1
      maximum: 800
      description: Placeholder documentation for __integerMin1Max800
    __integerMin256Max3840:
      type: integer
      minimum: 256
      maximum: 3840
      description: Placeholder documentation for __integerMin256Max3840
    __integerMin25Max10000:
      type: integer
      minimum: 25
      maximum: 10000
      description: Placeholder documentation for __integerMin25Max10000
    __integerMin25Max2000:
      type: integer
      minimum: 25
      maximum: 2000
      description: Placeholder documentation for __integerMin25Max2000
    __integerMin3:
      type: integer
      minimum: 3
      description: Placeholder documentation for __integerMin3
    __integerMin30:
      type: integer
      minimum: 30
      description: Placeholder documentation for __integerMin30
    __integerMin32Max8191:
      type: integer
      minimum: 32
      maximum: 8191
      description: Placeholder documentation for __integerMin32Max8191
    __integerMin40Max16000:
      type: integer
      minimum: 40
      maximum: 16000
      description: Placeholder documentation for __integerMin40Max16000
    __integerMin4Max20:
      type: integer
      minimum: 4
      maximum: 20
      description: Placeholder documentation for __integerMin4Max20
    __integerMin50000Max16000000:
      type: integer
      minimum: 50000
      maximum: 16000000
      description: Placeholder documentation for __integerMin50000Max16000000
    __integerMin50000Max8000000:
      type: integer
      minimum: 50000
      maximum: 8000000
      description: Placeholder documentation for __integerMin50000Max8000000
    __integerMin64Max2160:
      type: integer
      minimum: 64
      maximum: 2160
      description: Placeholder documentation for __integerMin64Max2160
    __integerMin800Max3000:
      type: integer
      minimum: 800
      maximum: 3000
      description: Placeholder documentation for __integerMin800Max3000
    __integerMin80Max800:
      type: integer
      minimum: 80
      maximum: 800
      description: Placeholder documentation for __integerMin80Max800
    __integerMin96Max600:
      type: integer
      minimum: 96
      maximum: 600
      description: Placeholder documentation for __integerMin96Max600
    __integerMinNegative1000Max1000:
      type: integer
      minimum: -1000
      maximum: 1000
      description: Placeholder documentation for __integerMinNegative1000Max1000
    __integerMinNegative5Max5:
      type: integer
      minimum: -5
      maximum: 5
      description: Placeholder documentation for __integerMinNegative5Max5
    __integerMinNegative60Max6:
      type: integer
      minimum: -60
      maximum: 6
      description: Placeholder documentation for __integerMinNegative60Max6
    __integerMinNegative60Max60:
      type: integer
      minimum: -60
      maximum: 60
      description: Placeholder documentation for __integerMinNegative60Max60
    __string:
      type: string
    __stringMax100:
      type: string
      minLength: 0
      maxLength: 100
    __stringMax1000:
      type: string
      minLength: 0
      maxLength: 1000
    __stringMax2048:
      type: string
      minLength: 0
      maxLength: 2048
    __stringMax255:
      type: string
      minLength: 0
      maxLength: 255
    __stringMax256:
      type: string
      minLength: 0
      maxLength: 256
    __stringMax32:
      type: string
      minLength: 0
      maxLength: 32
    __stringMax64:
      type: string
      minLength: 0
      maxLength: 64
    __stringMin0Max1024:
      type: string
      minLength: 0
      maxLength: 1024
    __stringMin1:
      type: string
      minLength: 1
    __stringMin1Max2048:
      type: string
      minLength: 1
      maxLength: 2048
    __stringMin1Max2048PatternArn:
      type: string
      pattern: ^arn.+$
      minLength: 1
      maxLength: 2048
    __stringMin1Max255:
      type: string
      minLength: 1
      maxLength: 255
    __stringMin1Max255PatternS:
      type: string
      pattern: ^[^\s]+$
      minLength: 1
      maxLength: 255
    __stringMin1Max256:
      type: string
      minLength: 1
      maxLength: 256
    __stringMin1Max256PatternS:
      type: string
      pattern: ^[\S]+$
      minLength: 1
      maxLength: 256
    __stringMin1Max35:
      type: string
      minLength: 1
      maxLength: 35
    __stringMin1Max7:
      type: string
      minLength: 1
      maxLength: 7
    __stringMin2Max2:
      type: string
      minLength: 2
      maxLength: 2
    __stringMin32Max32:
      type: string
      minLength: 32
      maxLength: 32
    __stringMin34Max34:
      type: string
      minLength: 34
      maxLength: 34
    __stringMin3Max3:
      type: string
      minLength: 3
      maxLength: 3
    __stringMin6Max6:
      type: string
      minLength: 6
      maxLength: 6
    __stringMin7Max11PatternAws097:
      type: string
      pattern: ^(aws-)?[0-9]{7}$
      minLength: 7
      maxLength: 11
    __stringPattern010920300:
      type: string
      pattern: ^([0,1]?[0-9]|2[0-3]):00$
    __stringPatternArnMedialiveCloudwatchAlarmTemplate:
      type: string
      pattern: ^arn:.+:medialive:.+:cloudwatch-alarm-template:.+$
    __stringPatternArnMedialiveCloudwatchAlarmTemplateGroup:
      type: string
      pattern: ^arn:.+:medialive:.+:cloudwatch-alarm-template-group:.+$
    __stringPatternArnMedialiveEventbridgeRuleTemplate:
      type: string
      pattern: ^arn:.+:medialive:.+:eventbridge-rule-template:.+$
    __stringPatternArnMedialiveEventbridgeRuleTemplateGroup:
      type: string
      pattern: ^arn:.+:medialive:.+:eventbridge-rule-template-group:.+$
    __stringPatternArnMedialiveSignalMap:
      type: string
      pattern: ^arn:.+:medialive:.+:signal-map:.+$
    __stringPatternS:
      type: string
      pattern: ^[^\s]+$
