openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: mediaconnect
  x-aws-serviceName: mediaconnect
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-11-14'
  title: AWS MediaConnect
  description: |-
    Welcome to the Elemental MediaConnect API reference.

    MediaConnect is a service that lets you ingest live video content into the cloud and distribute it to destinations all over the world, both inside and outside the Amazon Web Services cloud. This API reference provides descriptions, syntax, and usage examples for each of the actions and data types that are supported by MediaConnect.

    Use the following links to get started with the MediaConnect API:

      * [Actions](https://docs.aws.amazon.com/mediaconnect/latest/api/API_Operations.html): An alphabetical list of all MediaConnect API operations.

      * [Data types](https://docs.aws.amazon.com/mediaconnect/latest/api/API_Types.html): An alphabetical list of all MediaConnect data types.

      * [Common parameters](https://docs.aws.amazon.com/mediaconnect/latest/api/CommonParameters.html): Parameters that all operations can use.

      * [Common errors](https://docs.aws.amazon.com/mediaconnect/latest/api/CommonErrors.html): Client and server errors that all operations can return.
servers:
- description: The AWS MediaConnect regional endpoint
  url: https://mediaconnect.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Algorithm:
      type: string
      enum:
      - aes128
      - aes192
      - aes256
    BridgeArn:
      type: string
    BridgePlacement:
      type: string
      enum:
      - AVAILABLE
      - LOCKED
    BridgeState:
      type: string
      enum:
      - CREATING
      - STANDBY
      - STARTING
      - DEPLOYING
      - ACTIVE
      - STOPPING
      - DELETING
      - DELETED
      - START_FAILED
      - START_PENDING
      - STOP_FAILED
      - UPDATING
    Colorimetry:
      type: string
      enum:
      - BT601
      - BT709
      - BT2020
      - BT2100
      - ST2065-1
      - ST2065-3
      - XYZ
    ConnectionStatus:
      type: string
      enum:
      - CONNECTED
      - DISCONNECTED
    ContentQualityAnalysisState:
      type: string
      enum:
      - ENABLED
      - DISABLED
    DesiredState:
      type: string
      enum:
      - ACTIVE
      - STANDBY
      - DELETED
    DurationUnits:
      type: string
      enum:
      - MONTHS
    EncoderProfile:
      type: string
      enum:
      - main
      - high
    EncodingName:
      type: string
      enum:
      - jxsv
      - raw
      - smpte291
      - pcm
    EntitlementStatus:
      type: string
      enum:
      - ENABLED
      - DISABLED
    FailoverMode:
      type: string
      enum:
      - MERGE
      - FAILOVER
    FlowArn:
      type: string
    FlowSize:
      type: string
      enum:
      - MEDIUM
      - LARGE
    GatewayArn:
      type: string
    GatewayInstanceArn:
      type: string
    GatewayState:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - UPDATING
      - ERROR
      - DELETING
      - DELETED
    InstanceState:
      type: string
      enum:
      - REGISTERING
      - ACTIVE
      - DEREGISTERING
      - DEREGISTERED
      - REGISTRATION_ERROR
      - DEREGISTRATION_ERROR
    KeyType:
      type: string
      enum:
      - speke
      - static-key
      - srt-password
    MaintenanceDay:
      type: string
      enum:
      - Monday
      - Tuesday
      - Wednesday
      - Thursday
      - Friday
      - Saturday
      - Sunday
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
    MediaStreamType:
      type: string
      enum:
      - video
      - audio
      - ancillary-data
    NdiState:
      type: string
      enum:
      - ENABLED
      - DISABLED
    NetworkInterfaceType:
      type: string
      enum:
      - ena
      - efa
    OfferingArn:
      type: string
    OutputStatus:
      type: string
      enum:
      - ENABLED
      - DISABLED
    PriceUnits:
      type: string
      enum:
      - HOURLY
    Protocol:
      type: string
      enum:
      - zixi-push
      - rtp-fec
      - rtp
      - zixi-pull
      - rist
      - st2110-jpegxs
      - cdi
      - srt-listener
      - srt-caller
      - fujitsu-qos
      - udp
      - ndi-speed-hq
    Range:
      type: string
      enum:
      - NARROW
      - FULL
      - FULLPROTECT
    ReservationArn:
      type: string
    ReservationState:
      type: string
      enum:
      - ACTIVE
      - EXPIRED
      - PROCESSING
      - CANCELED
    ResourceType:
      type: string
      enum:
      - Mbps_Outbound_Bandwidth
    ScanMode:
      type: string
      enum:
      - progressive
      - interlace
      - progressive-segmented-frame
    SourceType:
      type: string
      enum:
      - OWNED
      - ENTITLED
    State:
      type: string
      enum:
      - ENABLED
      - DISABLED
    Status:
      type: string
      enum:
      - STANDBY
      - ACTIVE
      - UPDATING
      - DELETING
      - STARTING
      - STOPPING
      - ERROR
    Tcs:
      type: string
      enum:
      - SDR
      - PQ
      - HLG
      - LINEAR
      - BT2100LINPQ
      - BT2100LINHLG
      - ST2065-1
      - ST428-1
      - DENSITY
    ThumbnailState:
      type: string
      enum:
      - ENABLED
      - DISABLED
    __listOfAddBridgeOutputRequest:
      type: array
      items:
        $ref: '#/components/schemas/AddBridgeOutputRequest'
    __listOfAddBridgeSourceRequest:
      type: array
      items:
        $ref: '#/components/schemas/AddBridgeSourceRequest'
    __listOfAddMediaStreamRequest:
      type: array
      items:
        $ref: '#/components/schemas/AddMediaStreamRequest'
    __listOfAddOutputRequest:
      type: array
      items:
        $ref: '#/components/schemas/AddOutputRequest'
    __listOfAudioMonitoringSetting:
      type: array
      items:
        $ref: '#/components/schemas/AudioMonitoringSetting'
    __listOfBridgeOutput:
      type: array
      items:
        $ref: '#/components/schemas/BridgeOutput'
    __listOfBridgeSource:
      type: array
      items:
        $ref: '#/components/schemas/BridgeSource'
    __listOfDestinationConfiguration:
      type: array
      items:
        $ref: '#/components/schemas/DestinationConfiguration'
    __listOfDestinationConfigurationRequest:
      type: array
      items:
        $ref: '#/components/schemas/DestinationConfigurationRequest'
    __listOfEntitlement:
      type: array
      items:
        $ref: '#/components/schemas/Entitlement'
    __listOfGatewayNetwork:
      type: array
      items:
        $ref: '#/components/schemas/GatewayNetwork'
    __listOfGrantEntitlementRequest:
      type: array
      items:
        $ref: '#/components/schemas/GrantEntitlementRequest'
    __listOfInputConfiguration:
      type: array
      items:
        $ref: '#/components/schemas/InputConfiguration'
    __listOfInputConfigurationRequest:
      type: array
      items:
        $ref: '#/components/schemas/InputConfigurationRequest'
    __listOfInteger:
      type: array
      items:
        type: integer
    __listOfListedBridge:
      type: array
      items:
        $ref: '#/components/schemas/ListedBridge'
    __listOfListedEntitlement:
      type: array
      items:
        $ref: '#/components/schemas/ListedEntitlement'
    __listOfListedFlow:
      type: array
      items:
        $ref: '#/components/schemas/ListedFlow'
    __listOfListedGateway:
      type: array
      items:
        $ref: '#/components/schemas/ListedGateway'
    __listOfListedGatewayInstance:
      type: array
      items:
        $ref: '#/components/schemas/ListedGatewayInstance'
    __listOfMediaStream:
      type: array
      items:
        $ref: '#/components/schemas/MediaStream'
    __listOfMediaStreamOutputConfiguration:
      type: array
      items:
        $ref: '#/components/schemas/MediaStreamOutputConfiguration'
    __listOfMediaStreamOutputConfigurationRequest:
      type: array
      items:
        $ref: '#/components/schemas/MediaStreamOutputConfigurationRequest'
    __listOfMediaStreamSourceConfiguration:
      type: array
      items:
        $ref: '#/components/schemas/MediaStreamSourceConfiguration'
    __listOfMediaStreamSourceConfigurationRequest:
      type: array
      items:
        $ref: '#/components/schemas/MediaStreamSourceConfigurationRequest'
    __listOfMessageDetail:
      type: array
      items:
        $ref: '#/components/schemas/MessageDetail'
    __listOfNdiDiscoveryServerConfig:
      type: array
      items:
        $ref: '#/components/schemas/NdiDiscoveryServerConfig'
    __listOfOffering:
      type: array
      items:
        $ref: '#/components/schemas/Offering'
    __listOfOutput:
      type: array
      items:
        $ref: '#/components/schemas/Output'
    __listOfReservation:
      type: array
      items:
        $ref: '#/components/schemas/Reservation'
    __listOfSetSourceRequest:
      type: array
      items:
        $ref: '#/components/schemas/SetSourceRequest'
    __listOfSource:
      type: array
      items:
        $ref: '#/components/schemas/Source'
    __listOfString:
      type: array
      items:
        type: string
    __listOfTransportStream:
      type: array
      items:
        $ref: '#/components/schemas/TransportStream'
    __listOfTransportStreamProgram:
      type: array
      items:
        $ref: '#/components/schemas/TransportStreamProgram'
    __listOfVideoMonitoringSetting:
      type: array
      items:
        $ref: '#/components/schemas/VideoMonitoringSetting'
    __listOfVpcInterface:
      type: array
      items:
        $ref: '#/components/schemas/VpcInterface'
    __listOfVpcInterfaceRequest:
      type: array
      items:
        $ref: '#/components/schemas/VpcInterfaceRequest'
    __mapOfString:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
