openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: medical_imaging
  x-aws-serviceName: medicalimaging
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2023-07-19'
  title: AWS Health Imaging
  description: |-
    This is the _AWS HealthImaging API Reference_. AWS HealthImaging is a HIPAA eligible service that empowers healthcare providers, life science organizations, and their software partners to store, analyze, and share medical images in the cloud at petabyte scale. For an introduction to the service, see the [ _AWS HealthImaging Developer Guide_ ](https://docs.aws.amazon.com/healthimaging/latest/devguide/what-is.html).

    We recommend using one of the AWS Software Development Kits (SDKs) for your programming language, as they take care of request authentication, serialization, and connection management. For more information, see [Tools to build on AWS](http://aws.amazon.com/developer/tools).

    The following sections list AWS HealthImaging API actions categorized according to functionality. Links are provided to actions within this Reference, along with links back to corresponding sections in the _AWS HealthImaging Developer Guide_ where you can view tested code examples.

    **Data store actions**

      * [CreateDatastore](https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_CreateDatastore.html) – See [Creating a data store](https://docs.aws.amazon.com/healthimaging/latest/devguide/create-data-store.html).

      * [GetDatastore](https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_GetDatastore.html) – See [Getting data store properties](https://docs.aws.amazon.com/healthimaging/latest/devguide/get-data-store.html).

      * [ListDatastores](https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_ListDatastores.html) – See [Listing data stores](https://docs.aws.amazon.com/healthimaging/latest/devguide/list-data-stores.html).

      * [DeleteDatastore](https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_DeleteDatastore.html) – See [Deleting a data store](https://docs.aws.amazon.com/healthimaging/latest/devguide/delete-data-store.html).

    **Import job actions**

      * [StartDICOMImportJob](https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_StartDICOMImportJob.html) – See [Starting an import job](https://docs.aws.amazon.com/healthimaging/latest/devguide/start-dicom-import-job.html).

      * [GetDICOMImportJob](https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_GetDICOMImportJob.html) – See [Getting import job properties](https://docs.aws.amazon.com/healthimaging/latest/devguide/get-dicom-import-job.html).

      * [ListDICOMImportJobs](https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_ListDICOMImportJobs.html) – See [Listing import jobs](https://docs.aws.amazon.com/healthimaging/latest/devguide/list-dicom-import-jobs.html).

    **Image set access actions**

      * [SearchImageSets](https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_SearchImageSets.html) – See [Searching image sets](https://docs.aws.amazon.com/healthimaging/latest/devguide/search-image-sets.html).

      * [GetImageSet](https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_GetImageSet.html) – See [Getting image set properties](https://docs.aws.amazon.com/healthimaging/latest/devguide/get-image-set-properties.html).

      * [GetImageSetMetadata](https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_GetImageSetMetadata.html) – See [Getting image set metadata](https://docs.aws.amazon.com/healthimaging/latest/devguide/get-image-set-metadata.html).

      * [GetImageFrame](https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_GetImageFrame.html) – See [Getting image set pixel data](https://docs.aws.amazon.com/healthimaging/latest/devguide/get-image-frame.html).

    **Image set modification actions**

      * [ListImageSetVersions](https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_ListImageSetVersions.html) – See [Listing image set versions](https://docs.aws.amazon.com/healthimaging/latest/devguide/list-image-set-versions.html).

      * [UpdateImageSetMetadata](https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_UpdateImageSetMetadata.html) – See [Updating image set metadata](https://docs.aws.amazon.com/healthimaging/latest/devguide/update-image-set-metadata.html).

      * [CopyImageSet](https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_CopyImageSet.html) – See [Copying an image set](https://docs.aws.amazon.com/healthimaging/latest/devguide/copy-image-set.html).

      * [DeleteImageSet](https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_DeleteImageSet.html) – See [Deleting an image set](https://docs.aws.amazon.com/healthimaging/latest/devguide/delete-image-set.html).

    **Tagging actions**

      * [TagResource](https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_TagResource.html) – See [Tagging a resource](https://docs.aws.amazon.com/healthimaging/latest/devguide/tag-resource.html).

      * [ListTagsForResource](https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_ListTagsForResource.html) – See [Listing tags for a resource](https://docs.aws.amazon.com/healthimaging/latest/devguide/list-tag-resource.html).

      * [UntagResource](https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_UntagResource.html) – See [Untagging a resource](https://docs.aws.amazon.com/healthimaging/latest/devguide/untag-resource.html).
servers:
- description: The AWS Health Imaging regional endpoint
  url: https://medical-imaging.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Arn:
      type: string
      pattern: ^arn:aws((-us-gov)|(-iso)|(-iso-b)|(-cn))?:medical-imaging:[a-z0-9-]+:[0-9]{12}:datastore/[0-9a-z]{32}(/imageset/[0-9a-z]{32})?$
    AwsAccountId:
      type: string
      pattern: ^\d+$
      minLength: 12
      maxLength: 12
    ClientToken:
      type: string
      pattern: ^[A-Za-z0-9._-]+$
      minLength: 1
      maxLength: 64
    CopiableAttributes:
      type: string
      minLength: 1
      maxLength: 260000
    DICOMAccessionNumber:
      type: string
      minLength: 0
      maxLength: 256
    DICOMAttribute:
      type: string
      format: byte
      minLength: 1
      maxLength: 10000
      x-sensitive: true
    DICOMImportJobSummaries:
      type: array
      items:
        $ref: '#/components/schemas/DICOMImportJobSummary'
    DICOMNumberOfStudyRelatedInstances:
      type: integer
      default: 0
      minimum: 0
      maximum: 10000
    DICOMNumberOfStudyRelatedSeries:
      type: integer
      default: 0
      minimum: 0
      maximum: 1000000
    DICOMPatientBirthDate:
      type: string
      minLength: 0
      maxLength: 18
    DICOMPatientId:
      type: string
      minLength: 0
      maxLength: 256
    DICOMPatientName:
      type: string
      minLength: 0
      maxLength: 256
    DICOMPatientSex:
      type: string
      minLength: 0
      maxLength: 16
    DICOMSeriesBodyPart:
      type: string
      minLength: 0
      maxLength: 64
    DICOMSeriesInstanceUID:
      type: string
      pattern: ^(?:[0-9][0-9]*|0)(\.(?:[1-9][0-9]*|0))*$
      minLength: 0
      maxLength: 256
    DICOMSeriesModality:
      type: string
      minLength: 0
      maxLength: 16
    DICOMSeriesNumber:
      type: integer
      minimum: -2147483648
      maximum: 2147483647
    DICOMStudyDate:
      type: string
      minLength: 0
      maxLength: 18
    DICOMStudyDescription:
      type: string
      minLength: 0
      maxLength: 64
    DICOMStudyId:
      type: string
      minLength: 0
      maxLength: 16
    DICOMStudyInstanceUID:
      type: string
      pattern: ^(?:[0-9][0-9]*|0)(\.(?:[1-9][0-9]*|0))*$
      minLength: 0
      maxLength: 256
    DICOMStudyTime:
      type: string
      minLength: 0
      maxLength: 28
    DatastoreId:
      type: string
      pattern: ^[0-9a-z]{32}$
    DatastoreName:
      type: string
      pattern: ^[A-Za-z0-9._/#-]+$
      minLength: 1
      maxLength: 256
    DatastoreStatus:
      type: string
      enum:
      - CREATING
      - CREATE_FAILED
      - ACTIVE
      - DELETING
      - DELETED
    DatastoreSummaries:
      type: array
      items:
        $ref: '#/components/schemas/DatastoreSummary'
    Date:
      type: string
      format: date-time
    ImageFrameId:
      type: string
      pattern: ^[0-9a-z]{32}$
    ImageSetExternalVersionId:
      type: string
      pattern: ^\d+$
    ImageSetId:
      type: string
      pattern: ^[0-9a-z]{32}$
    ImageSetMetadataBlob:
      type: string
      format: byte
    ImageSetPropertiesList:
      type: array
      items:
        $ref: '#/components/schemas/ImageSetProperties'
    ImageSetState:
      type: string
      enum:
      - ACTIVE
      - LOCKED
      - DELETED
    ImageSetWorkflowStatus:
      type: string
      enum:
      - CREATED
      - COPIED
      - COPYING
      - COPYING_WITH_READ_ONLY_ACCESS
      - COPY_FAILED
      - UPDATING
      - UPDATED
      - UPDATE_FAILED
      - DELETING
      - DELETED
    ImageSetsMetadataSummaries:
      type: array
      items:
        $ref: '#/components/schemas/ImageSetsMetadataSummary'
    JobId:
      type: string
      pattern: ^[0-9a-z]+$
      minLength: 1
      maxLength: 32
    JobName:
      type: string
      pattern: ^[A-Za-z0-9._/#-]+$
      minLength: 1
      maxLength: 64
    JobStatus:
      type: string
      enum:
      - SUBMITTED
      - IN_PROGRESS
      - COMPLETED
      - FAILED
    KmsKeyArn:
      type: string
      pattern: ^arn:aws[a-zA-Z-]{0,16}:kms:[a-z]{2}(-[a-z]{1,16}){1,3}-\d{1}:\d{12}:((key/[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})|(alias/[a-zA-Z0-9:/_-]{1,256}))$
      minLength: 1
      maxLength: 512
    Message:
      type: string
      pattern: ^[\w -:]+$
      minLength: 1
      maxLength: 2048
    MetadataUpdates:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/DICOMUpdates'
        description: |-
          The object containing `removableAttributes` and `updatableAttributes`.
      - allOf:
        - $ref: '#/components/schemas/ImageSetExternalVersionId'
        description: |-
          Specifies the previous image set version ID to revert the current image set back to.

          You must provide either `revertToVersionId` or `DICOMUpdates` in your request. A `ValidationException` error is thrown if both parameters are provided at the same time.
      description: |-
        Contains DICOMUpdates.
    NextToken:
      type: string
      pattern: ^\p{ASCII}{0,8192}$
      minLength: 1
      maxLength: 8192
    Operator:
      type: string
      enum:
      - EQUAL
      - BETWEEN
    PayloadBlob:
      type: string
      format: byte
    RoleArn:
      type: string
      pattern: ^arn:aws(-[^:]+)?:iam::[0-9]{12}:role/.+$
      minLength: 20
      maxLength: 2048
    S3Uri:
      type: string
      pattern: ^s3://[a-z0-9][\.\-a-z0-9]{1,61}[a-z0-9](/.*)?$
      minLength: 1
      maxLength: 1024
    SearchByAttributeValue:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/DICOMPatientId'
        description: |-
          The patient ID input for search.
      - allOf:
        - $ref: '#/components/schemas/DICOMAccessionNumber'
        description: |-
          The DICOM accession number for search.
      - allOf:
        - $ref: '#/components/schemas/DICOMStudyId'
        description: |-
          The DICOM study ID for search.
      - allOf:
        - $ref: '#/components/schemas/DICOMStudyInstanceUID'
        description: |-
          The DICOM study instance UID for search.
      - allOf:
        - $ref: '#/components/schemas/DICOMSeriesInstanceUID'
        description: |-
          The Series Instance UID input for search.
      - allOf:
        - $ref: '#/components/schemas/Date'
        description: |-
          The created at time of the image set provided for search.
      - allOf:
        - $ref: '#/components/schemas/Date'
        description: |-
          The timestamp input for search.
      - allOf:
        - $ref: '#/components/schemas/DICOMStudyDateAndTime'
        description: |-
          The aggregated structure containing DICOM study date and study time for search.
      description: |-
        The search input attribute value.
    SearchByAttributeValues:
      type: array
      items:
        $ref: '#/components/schemas/SearchByAttributeValue'
    SearchFilters:
      type: array
      items:
        $ref: '#/components/schemas/SearchFilter'
    SortField:
      type: string
      enum:
      - updatedAt
      - createdAt
      - DICOMStudyDateAndTime
    SortOrder:
      type: string
      enum:
      - ASC
      - DESC
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
