openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: mediaconvert
  x-aws-serviceName: mediaconvert
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-08-29'
  title: AWS Elemental MediaConvert
  description: |-
    AWS Elemental MediaConvert
servers:
- description: The AWS Elemental MediaConvert regional endpoint
  url: https://mediaconvert.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    __integer:
      type: integer
    __integerMin0Max0:
      type: integer
      minimum: 0
      maximum: 0
    __integerMin0Max1:
      type: integer
      minimum: 0
      maximum: 1
    __integerMin0Max10:
      type: integer
      minimum: 0
      maximum: 10
    __integerMin0Max100:
      type: integer
      minimum: 0
      maximum: 100
    __integerMin0Max1000:
      type: integer
      minimum: 0
      maximum: 1000
    __integerMin0Max10000:
      type: integer
      minimum: 0
      maximum: 10000
    __integerMin0Max1152000000:
      type: integer
      minimum: 0
      maximum: 1152000000
    __integerMin0Max128:
      type: integer
      minimum: 0
      maximum: 128
    __integerMin0Max1466400000:
      type: integer
      minimum: 0
      maximum: 1466400000
    __integerMin0Max15:
      type: integer
      minimum: 0
      maximum: 15
    __integerMin0Max16:
      type: integer
      minimum: 0
      maximum: 16
    __integerMin0Max2147483647:
      type: integer
      minimum: 0
      maximum: 2147483647
    __integerMin0Max255:
      type: integer
      minimum: 0
      maximum: 255
    __integerMin0Max3:
      type: integer
      minimum: 0
      maximum: 3
    __integerMin0Max30:
      type: integer
      minimum: 0
      maximum: 30
    __integerMin0Max30000:
      type: integer
      minimum: 0
      maximum: 30000
    __integerMin0Max3600:
      type: integer
      minimum: 0
      maximum: 3600
    __integerMin0Max4:
      type: integer
      minimum: 0
      maximum: 4
    __integerMin0Max4000:
      type: integer
      minimum: 0
      maximum: 4000
    __integerMin0Max4194303:
      type: integer
      minimum: 0
      maximum: 4194303
    __integerMin0Max47185920:
      type: integer
      minimum: 0
      maximum: 47185920
    __integerMin0Max5:
      type: integer
      minimum: 0
      maximum: 5
    __integerMin0Max500:
      type: integer
      minimum: 0
      maximum: 500
    __integerMin0Max50000:
      type: integer
      minimum: 0
      maximum: 50000
    __integerMin0Max65534:
      type: integer
      minimum: 0
      maximum: 65534
    __integerMin0Max65535:
      type: integer
      minimum: 0
      maximum: 65535
    __integerMin0Max7:
      type: integer
      minimum: 0
      maximum: 7
    __integerMin0Max8:
      type: integer
      minimum: 0
      maximum: 8
    __integerMin0Max9:
      type: integer
      minimum: 0
      maximum: 9
    __integerMin0Max96:
      type: integer
      minimum: 0
      maximum: 96
    __integerMin0Max99:
      type: integer
      minimum: 0
      maximum: 99
    __integerMin100000Max100000000:
      type: integer
      minimum: 100000
      maximum: 100000000
    __integerMin1000Max1152000000:
      type: integer
      minimum: 1000
      maximum: 1152000000
    __integerMin1000Max1466400000:
      type: integer
      minimum: 1000
      maximum: 1466400000
    __integerMin1000Max288000000:
      type: integer
      minimum: 1000
      maximum: 288000000
    __integerMin1000Max30000:
      type: integer
      minimum: 1000
      maximum: 30000
    __integerMin1000Max300000000:
      type: integer
      minimum: 1000
      maximum: 300000000
    __integerMin1000Max480000000:
      type: integer
      minimum: 1000
      maximum: 480000000
    __integerMin100Max1000:
      type: integer
      minimum: 100
      maximum: 1000
    __integerMin10Max48:
      type: integer
      minimum: 10
      maximum: 48
    __integerMin16000Max320000:
      type: integer
      minimum: 16000
      maximum: 320000
    __integerMin16000Max48000:
      type: integer
      minimum: 16000
      maximum: 48000
    __integerMin16Max24:
      type: integer
      minimum: 16
      maximum: 24
    __integerMin1Max1:
      type: integer
      minimum: 1
      maximum: 1
    __integerMin1Max10:
      type: integer
      minimum: 1
      maximum: 10
    __integerMin1Max100:
      type: integer
      minimum: 1
      maximum: 100
    __integerMin1Max10000000:
      type: integer
      minimum: 1
      maximum: 10000000
    __integerMin1Max1001:
      type: integer
      minimum: 1
      maximum: 1001
    __integerMin1Max150:
      type: integer
      minimum: 1
      maximum: 150
    __integerMin1Max17895697:
      type: integer
      minimum: 1
      maximum: 17895697
    __integerMin1Max2:
      type: integer
      minimum: 1
      maximum: 2
    __integerMin1Max20:
      type: integer
      minimum: 1
      maximum: 20
    __integerMin1Max2048:
      type: integer
      minimum: 1
      maximum: 2048
    __integerMin1Max2147483640:
      type: integer
      minimum: 1
      maximum: 2147483640
    __integerMin1Max2147483647:
      type: integer
      minimum: 1
      maximum: 2147483647
    __integerMin1Max31:
      type: integer
      minimum: 1
      maximum: 31
    __integerMin1Max32:
      type: integer
      minimum: 1
      maximum: 32
    __integerMin1Max4:
      type: integer
      minimum: 1
      maximum: 4
    __integerMin1Max4096:
      type: integer
      minimum: 1
      maximum: 4096
    __integerMin1Max512:
      type: integer
      minimum: 1
      maximum: 512
    __integerMin1Max6:
      type: integer
      minimum: 1
      maximum: 6
    __integerMin1Max60000:
      type: integer
      minimum: 1
      maximum: 60000
    __integerMin1Max64:
      type: integer
      minimum: 1
      maximum: 64
    __integerMin1Max8:
      type: integer
      minimum: 1
      maximum: 8
    __integerMin22050Max48000:
      type: integer
      minimum: 22050
      maximum: 48000
    __integerMin24Max60000:
      type: integer
      minimum: 24
      maximum: 60000
    __integerMin25Max10000:
      type: integer
      minimum: 25
      maximum: 10000
    __integerMin25Max2000:
      type: integer
      minimum: 25
      maximum: 2000
    __integerMin2Max2147483647:
      type: integer
      minimum: 2
      maximum: 2147483647
    __integerMin2Max4096:
      type: integer
      minimum: 2
      maximum: 4096
    __integerMin32000Max192000:
      type: integer
      minimum: 32000
      maximum: 192000
    __integerMin32000Max3024000:
      type: integer
      minimum: 32000
      maximum: 3024000
    __integerMin32000Max384000:
      type: integer
      minimum: 32000
      maximum: 384000
    __integerMin32000Max48000:
      type: integer
      minimum: 32000
      maximum: 48000
    __integerMin32Max8182:
      type: integer
      minimum: 32
      maximum: 8182
    __integerMin32Max8192:
      type: integer
      minimum: 32
      maximum: 8192
    __integerMin384000Max1024000:
      type: integer
      minimum: 384000
      maximum: 1024000
    __integerMin3Max15:
      type: integer
      minimum: 3
      maximum: 15
    __integerMin48000Max48000:
      type: integer
      minimum: 48000
      maximum: 48000
    __integerMin4Max12:
      type: integer
      minimum: 4
      maximum: 12
    __integerMin50Max86400000:
      type: integer
      minimum: 50
      maximum: 86400000
    __integerMin6000Max1024000:
      type: integer
      minimum: 6000
      maximum: 1024000
    __integerMin64000Max640000:
      type: integer
      minimum: 64000
      maximum: 640000
    __integerMin8000Max192000:
      type: integer
      minimum: 8000
      maximum: 192000
    __integerMin8000Max96000:
      type: integer
      minimum: 8000
      maximum: 96000
    __integerMin8Max12:
      type: integer
      minimum: 8
      maximum: 12
    __integerMin8Max4096:
      type: integer
      minimum: 8
      maximum: 4096
    __integerMin90Max105:
      type: integer
      minimum: 90
      maximum: 105
    __integerMin920Max1023:
      type: integer
      minimum: 920
      maximum: 1023
    __integerMin96Max600:
      type: integer
      minimum: 96
      maximum: 600
    __integerMinNegative10000Max10000:
      type: integer
      minimum: -10000
      maximum: 10000
    __integerMinNegative1000Max1000:
      type: integer
      minimum: -1000
      maximum: 1000
    __integerMinNegative180Max180:
      type: integer
      minimum: -180
      maximum: 180
    __integerMinNegative1Max10:
      type: integer
      minimum: -1
      maximum: 10
    __integerMinNegative1Max2147483647:
      type: integer
      minimum: -1
      maximum: 2147483647
    __integerMinNegative1Max3:
      type: integer
      minimum: -1
      maximum: 3
    __integerMinNegative2147483648Max2147483647:
      type: integer
      minimum: -2147483648
      maximum: 2147483647
    __integerMinNegative2Max3:
      type: integer
      minimum: -2
      maximum: 3
    __integerMinNegative50Max50:
      type: integer
      minimum: -50
      maximum: 50
    __integerMinNegative5Max10:
      type: integer
      minimum: -5
      maximum: 10
    __integerMinNegative60Max6:
      type: integer
      minimum: -60
      maximum: 6
    __integerMinNegative70Max0:
      type: integer
      minimum: -70
      maximum: 0
    __string:
      type: string
    __stringMax1000:
      type: string
      minLength: 0
      maxLength: 1000
    __stringMax2048:
      type: string
      minLength: 0
      maxLength: 2048
    __stringMax2048PatternS3Https:
      type: string
      pattern: ^s3://([^\/]+\/+)+((([^\/]*)))|^https?://[^\/].*[^&]$
      minLength: 0
      maxLength: 2048
    __stringMax256:
      type: string
      minLength: 0
      maxLength: 256
    __stringMin0:
      type: string
      minLength: 0
    __stringMin1:
      type: string
      minLength: 1
    __stringMin11Max11Pattern01D20305D205D:
      type: string
      pattern: ^((([0-1]\d)|(2[0-3]))(:[0-5]\d){2}([:;][0-5]\d))$
      minLength: 11
      maxLength: 11
    __stringMin14PatternS3BmpBMPPngPNGHttpsBmpBMPPngPNG:
      type: string
      pattern: ^((s3://(.*?)\.(bmp|BMP|png|PNG))|(https?://(.*?)\.(bmp|BMP|png|PNG)(\?([^&=]+=[^&]+&)*[^&=]+=[^&]+)?))$
      minLength: 14
    __stringMin14PatternS3BmpBMPPngPNGTgaTGAHttpsBmpBMPPngPNGTgaTGA:
      type: string
      pattern: ^((s3://(.*?)\.(bmp|BMP|png|PNG|tga|TGA))|(https?://(.*?)\.(bmp|BMP|png|PNG|tga|TGA)(\?([^&=]+=[^&]+&)*[^&=]+=[^&]+)?))$
      minLength: 14
    __stringMin14PatternS3CubeCUBEHttpsCubeCUBE:
      type: string
      pattern: ^((s3://(.*?)\.(cube|CUBE))|(https?://(.*?)\.(cube|CUBE)(\?([^&=]+=[^&]+&)*[^&=]+=[^&]+)?))$
      minLength: 14
    __stringMin14PatternS3Mov09PngHttpsMov09Png:
      type: string
      pattern: ^((s3://(.*)(\.mov|[0-9]+\.png))|(https?://(.*)(\.mov|[0-9]+\.png)(\?([^&=]+=[^&]+&)*[^&=]+=[^&]+)?))$
      minLength: 14
    ? __stringMin14PatternS3SccSCCTtmlTTMLDfxpDFXPStlSTLSrtSRTXmlXMLSmiSMIVttVTTWebvttWEBVTTHttpsSccSCCTtmlTTMLDfxpDFXPStlSTLSrtSRTXmlXMLSmiSMIVttVTTWebvttWEBVTT
    : type: string
      pattern: ^((s3://(.*?)\.(scc|SCC|ttml|TTML|dfxp|DFXP|stl|STL|srt|SRT|xml|XML|smi|SMI|vtt|VTT|webvtt|WEBVTT))|(https?://(.*?)\.(scc|SCC|ttml|TTML|dfxp|DFXP|stl|STL|srt|SRT|xml|XML|smi|SMI|vtt|VTT|webvtt|WEBVTT)(\?([^&=]+=[^&]+&)*[^&=]+=[^&]+)?))$
      minLength: 14
    __stringMin14PatternS3XmlXMLHttpsXmlXML:
      type: string
      pattern: ^((s3://(.*?)\.(xml|XML))|(https?://(.*?)\.(xml|XML)(\?([^&=]+=[^&]+&)*[^&=]+=[^&]+)?))$
      minLength: 14
    __stringMin16Max24PatternAZaZ0922AZaZ0916:
      type: string
      pattern: ^[A-Za-z0-9+\/]{22}==$|^[A-Za-z0-9+\/]{16}$
      minLength: 16
      maxLength: 24
    __stringMin1Max100000:
      type: string
      minLength: 1
      maxLength: 100000
    __stringMin1Max20:
      type: string
      minLength: 1
      maxLength: 20
    __stringMin1Max2048PatternArnAZSecretsmanagerWD12SecretAZAZ09:
      type: string
      pattern: ^(arn:[a-z-]+:secretsmanager:[\w-]+:\d{12}:secret:)?[a-zA-Z0-9_\/_+=.@-]*$
      minLength: 1
      maxLength: 2048
    __stringMin1Max256:
      type: string
      minLength: 1
      maxLength: 256
    __stringMin1Max50:
      type: string
      minLength: 1
      maxLength: 50
    __stringMin1Max50PatternAZAZ09:
      type: string
      pattern: ^[a-zA-Z0-9_\/_+=.@-]*$
      minLength: 1
      maxLength: 50
    __stringMin24Max512PatternAZaZ0902:
      type: string
      pattern: ^[A-Za-z0-9+\/]+={0,2}$
      minLength: 24
      maxLength: 512
    __stringMin32Max32Pattern09aFAF32:
      type: string
      pattern: ^[0-9a-fA-F]{32}$
      minLength: 32
      maxLength: 32
    __stringMin36Max36Pattern09aFAF809aFAF409aFAF409aFAF409aFAF12:
      type: string
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
      minLength: 36
      maxLength: 36
    __stringMin3Max3Pattern1809aFAF09aEAE:
      type: string
      pattern: ^[1-8][0-9a-fA-F][0-9a-eA-E]$
      minLength: 3
      maxLength: 3
    __stringMin3Max3PatternAZaZ3:
      type: string
      pattern: ^[A-Za-z]{3}$
      minLength: 3
      maxLength: 3
    __stringMin6Max8Pattern09aFAF609aFAF2:
      type: string
      pattern: ^[0-9a-fA-F]{6}([0-9a-fA-F]{2})?$
      minLength: 6
      maxLength: 8
    __stringMin9Max19PatternAZ26EastWestCentralNorthSouthEastWest1912:
      type: string
      pattern: ^[a-z-]{2,6}-(east|west|central|((north|south)(east|west)?))-[1-9]{1,2}$
      minLength: 9
      maxLength: 19
    __stringPattern:
      type: string
      pattern: ^[ -~]+$
    __stringPattern010920405090509092:
      type: string
      pattern: ^([01][0-9]|2[0-4]):[0-5][0-9]:[0-5][0-9][:;][0-9]{2}$
    __stringPattern010920405090509092090909:
      type: string
      pattern: ^([01][0-9]|2[0-4]):[0-5][0-9]:[0-5][0-9][:;][0-9]{2}(@[0-9]+(\.[0-9]+)?(:[0-9]+)?)?$
    __stringPattern01D20305D205D:
      type: string
      pattern: ^((([0-1]\d)|(2[0-3]))(:[0-5]\d){2}([:;][0-5]\d))$
    __stringPattern0940191020191209301:
      type: string
      pattern: ^([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$
    __stringPattern09aFAF809aFAF409aFAF409aFAF409aFAF12:
      type: string
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
    __stringPattern0xAFaF0908190908:
      type: string
      pattern: ^(^0x[A-Fa-f0-9]{0,8}$|^[1-9][0-9]{0,8}$)$
    __stringPatternAZaZ0902:
      type: string
      pattern: ^[A-Za-z0-9+\/]+={0,2}$
    __stringPatternAZaZ0932:
      type: string
      pattern: ^[A-Za-z0-9]{32}$
    __stringPatternAZaZ23AZaZ:
      type: string
      pattern: ^[A-Za-z]{2,3}(-[A-Za-z-]+)?$
    __stringPatternAZaZ23AZaZ09:
      type: string
      pattern: ^[A-Za-z]{2,3}(-[A-Za-z0-9-]+)?$
    __stringPatternArnAwsUsGovAcm:
      type: string
      pattern: ^arn:aws(-us-gov)?:acm:$
    ? __stringPatternArnAwsUsGovCnKmsAZ26EastWestCentralNorthSouthEastWest1912D12KeyAFAF098AFAF094AFAF094AFAF094AFAF0912MrkAFAF0932
    : type: string
      pattern: ^arn:aws(-us-gov|-cn)?:kms:[a-z-]{2,6}-(east|west|central|((north|south)(east|west)?))-[1-9]{1,2}:\d{12}:key/([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}|mrk-[a-fA-F0-9]{32})$
    __stringPatternDD:
      type: string
      pattern: ^(\d+(\/\d+)*)$
    __stringPatternHttps:
      type: string
      pattern: ^https:\/\/$
    __stringPatternHttpsD:
      type: string
      pattern: ^https:\/\/[^:@\/]*(:\d*)?(\/.*)?$
    __stringPatternHttpsKantarmedia:
      type: string
      pattern: ^https:\/\/.*.kantarmedia.*$
    __stringPatternIdentityAZaZ26AZaZ09163:
      type: string
      pattern: ^(identity|[A-Za-z]{2,6}(\.[A-Za-z0-9-]{1,63})+)$
    __stringPatternS3:
      type: string
      pattern: ^s3:\/\/$
    __stringPatternS3ASSETMAPXml:
      type: string
      pattern: ^s3:\/\/.*\/(ASSETMAP.xml)?$
    __stringPatternS3Https:
      type: string
      pattern: ^s3://([^\/]+\/+)+((([^\/]*)))|^https?://[^\/].*[^&]$
    __stringPatternS3TtfHttpsTtf:
      type: string
      pattern: ^((s3://(.*?)\.(ttf))|(https?://(.*?)\.(ttf)(\?([^&=]+=[^&]+&)*[^&=]+=[^&]+)?))$
    __stringPatternSNManifestConfirmConditionNotificationNS:
      type: string
      pattern: ^\s*<(.|\n)*ManifestConfirmConditionNotification(.|\n)*>\s*$
    __stringPatternSNSignalProcessingNotificationNS:
      type: string
      pattern: ^\s*<(.|\n)*SignalProcessingNotification(.|\n)*>\s*$
    __stringPatternW:
      type: string
      pattern: ^[\w-]+$
    __stringPatternWS:
      type: string
      pattern: ^[\w\s]*$
