openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: mediatailor
  x-aws-serviceName: mediatailor
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-04-23'
  title: AWS MediaTailor
  description: |-
    Use the AWS Elemental MediaTailor SDKs and CLI to configure scalable ad insertion and linear channels. With MediaTailor, you can assemble existing content into a linear stream and serve targeted ads to viewers while maintaining broadcast quality in over-the-top (OTT) video applications. For information about using the service, including detailed information about the settings covered in this guide, see the [AWS Elemental MediaTailor User Guide](https://docs.aws.amazon.com/mediatailor/latest/ug/).

    Through the SDKs and the CLI you manage AWS Elemental MediaTailor configurations and channels the same as you do through the console. For example, you specify ad insertion behavior and mapping information for the origin server and the ad decision server (ADS).
servers:
- description: The AWS MediaTailor regional endpoint
  url: https://api.mediatailor.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccessType:
      type: string
      enum:
      - S3_SIGV4
      - SECRETS_MANAGER_ACCESS_TOKEN
      - AUTODETECT_SIGV4
    AdBreakMetadataList:
      type: array
      items:
        $ref: '#/components/schemas/KeyValuePair'
    AdBreakOpportunities:
      type: array
      items:
        $ref: '#/components/schemas/AdBreakOpportunity'
      description: <p>The list of ad break opportunities detected within the VOD source.</p>
    AdMarkupType:
      type: string
      enum:
      - DATERANGE
      - SCTE35_ENHANCED
    AdsInteractionExcludeEventType:
      type: string
      enum:
      - AD_MARKER_FOUND
      - NON_AD_MARKER_FOUND
      - MAKING_ADS_REQUEST
      - MODIFIED_TARGET_URL
      - VAST_REDIRECT
      - EMPTY_VAST_RESPONSE
      - EMPTY_VMAP_RESPONSE
      - VAST_RESPONSE
      - REDIRECTED_VAST_RESPONSE
      - FILLED_AVAIL
      - FILLED_OVERLAY_AVAIL
      - BEACON_FIRED
      - WARNING_NO_ADVERTISEMENTS
      - WARNING_VPAID_AD_DROPPED
      - WARNING_URL_VARIABLE_SUBSTITUTION_FAILED
      - ERROR_UNKNOWN
      - ERROR_UNKNOWN_HOST
      - ERROR_DISALLOWED_HOST
      - ERROR_ADS_IO
      - ERROR_ADS_TIMEOUT
      - ERROR_ADS_RESPONSE_PARSE
      - ERROR_ADS_RESPONSE_UNKNOWN_ROOT_ELEMENT
      - ERROR_ADS_INVALID_RESPONSE
      - ERROR_VAST_REDIRECT_EMPTY_RESPONSE
      - ERROR_VAST_REDIRECT_MULTIPLE_VAST
      - ERROR_VAST_REDIRECT_FAILED
      - ERROR_VAST_MISSING_MEDIAFILES
      - ERROR_VAST_MISSING_CREATIVES
      - ERROR_VAST_MISSING_OVERLAYS
      - ERROR_VAST_MISSING_IMPRESSION
      - ERROR_VAST_INVALID_VAST_AD_TAG_URI
      - ERROR_VAST_MULTIPLE_TRACKING_EVENTS
      - ERROR_VAST_MULTIPLE_LINEAR
      - ERROR_VAST_INVALID_MEDIA_FILE
      - ERROR_FIRING_BEACON_FAILED
      - ERROR_PERSONALIZATION_DISABLED
      - VOD_TIME_BASED_AVAIL_PLAN_VAST_RESPONSE_FOR_OFFSET
      - VOD_TIME_BASED_AVAIL_PLAN_SUCCESS
      - VOD_TIME_BASED_AVAIL_PLAN_WARNING_NO_ADVERTISEMENTS
      - INTERSTITIAL_VOD_SUCCESS
      - INTERSTITIAL_VOD_FAILURE
    AdsInteractionPublishOptInEventType:
      type: string
      enum:
      - RAW_ADS_RESPONSE
    AlertCategory:
      type: string
      enum:
      - SCHEDULING_ERROR
      - PLAYBACK_WARNING
      - INFO
    Audiences:
      type: array
      items:
        type: string
    ChannelState:
      type: string
      enum:
      - RUNNING
      - STOPPED
    ConfigurationAliasesRequest:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/__mapOf__string'
      description: <p>The predefined aliases for dynamic variables.</p>
    ConfigurationAliasesResponse:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/__mapOf__string'
      description: <p>The predefined aliases for dynamic variables.</p>
    FillPolicy:
      type: string
      enum:
      - FULL_AVAIL_ONLY
      - PARTIAL_AVAIL
    HttpPackageConfigurations:
      type: array
      items:
        $ref: '#/components/schemas/HttpPackageConfiguration'
      description: <p>The VOD source's HTTP package configuration settings.</p>
    InsertionMode:
      type: string
      enum:
      - STITCHED_ONLY
      - PLAYER_SELECT
      description: <p>Insertion Mode controls whether players can use stitched or
        guided ad insertion.</p>
    ListPrefetchScheduleType:
      type: string
      enum:
      - SINGLE
      - RECURRING
      - ALL
    LogType:
      type: string
      enum:
      - AS_RUN
    LogTypes:
      type: array
      items:
        $ref: '#/components/schemas/LogType'
    LoggingStrategy:
      type: string
      enum:
      - VENDED_LOGS
      - LEGACY_CLOUDWATCH
    ManifestServiceExcludeEventType:
      type: string
      enum:
      - GENERATED_MANIFEST
      - ORIGIN_MANIFEST
      - SESSION_INITIALIZED
      - TRACKING_RESPONSE
      - CONFIG_SYNTAX_ERROR
      - CONFIG_SECURITY_ERROR
      - UNKNOWN_HOST
      - TIMEOUT_ERROR
      - CONNECTION_ERROR
      - IO_ERROR
      - UNKNOWN_ERROR
      - HOST_DISALLOWED
      - PARSING_ERROR
      - MANIFEST_ERROR
      - NO_MASTER_OR_MEDIA_PLAYLIST
      - NO_MASTER_PLAYLIST
      - NO_MEDIA_PLAYLIST
      - INCOMPATIBLE_HLS_VERSION
      - SCTE35_PARSING_ERROR
      - INVALID_SINGLE_PERIOD_DASH_MANIFEST
      - UNSUPPORTED_SINGLE_PERIOD_DASH_MANIFEST
      - LAST_PERIOD_MISSING_AUDIO
      - LAST_PERIOD_MISSING_AUDIO_WARNING
      - ERROR_ORIGIN_PREFIX_INTERPOLATION
      - ERROR_ADS_INTERPOLATION
      - ERROR_LIVE_PRE_ROLL_ADS_INTERPOLATION
      - ERROR_CDN_AD_SEGMENT_INTERPOLATION
      - ERROR_CDN_CONTENT_SEGMENT_INTERPOLATION
      - ERROR_SLATE_AD_URL_INTERPOLATION
      - ERROR_PROFILE_NAME_INTERPOLATION
      - ERROR_BUMPER_START_INTERPOLATION
      - ERROR_BUMPER_END_INTERPOLATION
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    MessageType:
      type: string
      enum:
      - SPLICE_INSERT
      - TIME_SIGNAL
    Mode:
      type: string
      enum:
      - 'OFF'
      - BEHIND_LIVE_EDGE
      - AFTER_LIVE_EDGE
    Operator:
      type: string
      enum:
      - EQUALS
    OriginManifestType:
      type: string
      enum:
      - SINGLE_PERIOD
      - MULTI_PERIOD
    PlaybackMode:
      type: string
      enum:
      - LOOP
      - LINEAR
    PrefetchScheduleType:
      type: string
      enum:
      - SINGLE
      - RECURRING
    RelativePosition:
      type: string
      enum:
      - BEFORE_PROGRAM
      - AFTER_PROGRAM
    RequestOutputs:
      type: array
      items:
        $ref: '#/components/schemas/RequestOutputItem'
      description: <p>An object that represents an object in the CreateChannel request.</p>
    ResponseOutputs:
      type: array
      items:
        $ref: '#/components/schemas/ResponseOutputItem'
    ScheduleEntryType:
      type: string
      enum:
      - PROGRAM
      - FILLER_SLATE
      - ALTERNATE_MEDIA
    SegmentationDescriptorList:
      type: array
      items:
        $ref: '#/components/schemas/SegmentationDescriptor'
    StreamingMediaFileConditioning:
      type: string
      enum:
      - TRANSCODE
      - NONE
    Tier:
      type: string
      enum:
      - BASIC
      - STANDARD
    TrafficShapingType:
      type: string
      enum:
      - RETRIEVAL_WINDOW
    Type:
      type: string
      enum:
      - DASH
      - HLS
    __adsInteractionExcludeEventTypesList:
      type: array
      items:
        $ref: '#/components/schemas/AdsInteractionExcludeEventType'
    __adsInteractionPublishOptInEventTypesList:
      type: array
      items:
        $ref: '#/components/schemas/AdsInteractionPublishOptInEventType'
    __boolean:
      type: boolean
    __integer:
      type: integer
    __integerMin1:
      type: integer
      minimum: 1
    __integerMin1Max100:
      type: integer
      minimum: 1
      maximum: 100
    __listOfAdBreak:
      type: array
      items:
        $ref: '#/components/schemas/AdBreak'
    __listOfAlert:
      type: array
      items:
        $ref: '#/components/schemas/Alert'
    __listOfAlternateMedia:
      type: array
      items:
        $ref: '#/components/schemas/AlternateMedia'
    __listOfAudienceMedia:
      type: array
      items:
        $ref: '#/components/schemas/AudienceMedia'
    __listOfAvailMatchingCriteria:
      type: array
      items:
        $ref: '#/components/schemas/AvailMatchingCriteria'
    __listOfChannel:
      type: array
      items:
        $ref: '#/components/schemas/Channel'
    __listOfLiveSource:
      type: array
      items:
        $ref: '#/components/schemas/LiveSource'
    __listOfLoggingStrategies:
      type: array
      items:
        $ref: '#/components/schemas/LoggingStrategy'
    __listOfPlaybackConfiguration:
      type: array
      items:
        $ref: '#/components/schemas/PlaybackConfiguration'
    __listOfPrefetchSchedule:
      type: array
      items:
        $ref: '#/components/schemas/PrefetchSchedule'
    __listOfScheduleAdBreak:
      type: array
      items:
        $ref: '#/components/schemas/ScheduleAdBreak'
    __listOfScheduleEntry:
      type: array
      items:
        $ref: '#/components/schemas/ScheduleEntry'
    __listOfSegmentDeliveryConfiguration:
      type: array
      items:
        $ref: '#/components/schemas/SegmentDeliveryConfiguration'
    __listOfSourceLocation:
      type: array
      items:
        $ref: '#/components/schemas/SourceLocation'
    __listOfVodSource:
      type: array
      items:
        $ref: '#/components/schemas/VodSource'
    __listOf__string:
      type: array
      items:
        $ref: '#/components/schemas/__string'
    __long:
      type: integer
      format: int64
    __manifestServiceExcludeEventTypesList:
      type: array
      items:
        $ref: '#/components/schemas/ManifestServiceExcludeEventType'
    __mapOf__string:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/__string'
    __string:
      type: string
    __timestampUnix:
      type: string
      format: date-time
    adMarkupTypes:
      type: array
      items:
        $ref: '#/components/schemas/AdMarkupType'
