openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: mediapackagev2
  x-aws-serviceName: mediapackagev2
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2022-12-25'
  title: AWS Elemental MediaPackage v2
  description: |-
    This guide is intended for creating AWS Elemental MediaPackage resources in MediaPackage Version 2 (v2) starting from May 2023. To get started with MediaPackage v2, create your MediaPackage resources. There isn't an automated process to migrate your resources from MediaPackage v1 to MediaPackage v2.

    The names of the entities that you use to access this API, like URLs and ARNs, all have the versioning information added, like "v2", to distinguish from the prior version. If you used MediaPackage prior to this release, you can't use the MediaPackage v2 CLI or the MediaPackage v2 API to access any MediaPackage v1 resources.

    If you created resources in MediaPackage v1, use video on demand (VOD) workflows, and aren't looking to migrate to MediaPackage v2 yet, see the [MediaPackage v1 Live API Reference](https://docs.aws.amazon.com/mediapackage/latest/apireference/what-is.html).

    This is the AWS Elemental MediaPackage v2 Live REST API Reference. It describes all the MediaPackage API operations for live content in detail, and provides sample requests, responses, and errors for the supported web services protocols.

    We assume that you have the IAM permissions that you need to use MediaPackage via the REST API. We also assume that you are familiar with the features and operations of MediaPackage, as described in the AWS Elemental MediaPackage User Guide.
servers:
- description: The AWS Elemental MediaPackage v2 regional endpoint
  url: https://mediapackagev2.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AdMarkerDash:
      type: string
      enum:
      - BINARY
      - XML
    AdMarkerHls:
      type: string
      enum:
      - DATERANGE
    ChannelGroupsList:
      type: array
      items:
        $ref: '#/components/schemas/ChannelGroupListConfiguration'
    ChannelList:
      type: array
      items:
        $ref: '#/components/schemas/ChannelListConfiguration'
    CmafEncryptionMethod:
      type: string
      enum:
      - CENC
      - CBCS
    ConflictExceptionType:
      type: string
      enum:
      - RESOURCE_IN_USE
      - RESOURCE_ALREADY_EXISTS
      - IDEMPOTENT_PARAMETER_MISMATCH
      - CONFLICTING_OPERATION
    ContainerType:
      type: string
      enum:
      - TS
      - CMAF
    CreateDashManifests:
      type: array
      items:
        $ref: '#/components/schemas/CreateDashManifestConfiguration'
    CreateHlsManifests:
      type: array
      items:
        $ref: '#/components/schemas/CreateHlsManifestConfiguration'
    CreateLowLatencyHlsManifests:
      type: array
      items:
        $ref: '#/components/schemas/CreateLowLatencyHlsManifestConfiguration'
    DashDrmSignaling:
      type: string
      enum:
      - INDIVIDUAL
      - REFERENCED
    DashPeriodTrigger:
      type: string
      enum:
      - AVAILS
      - DRM_KEY_ROTATION
      - SOURCE_CHANGES
      - SOURCE_DISRUPTIONS
      - NONE
    DashPeriodTriggers:
      type: array
      items:
        $ref: '#/components/schemas/DashPeriodTrigger'
    DashSegmentTemplateFormat:
      type: string
      enum:
      - NUMBER_WITH_TIMELINE
    DashUtcTimingMode:
      type: string
      enum:
      - HTTP_HEAD
      - HTTP_ISO
      - HTTP_XSDATE
      - UTC_DIRECT
    DrmSystem:
      type: string
      enum:
      - CLEAR_KEY_AES_128
      - FAIRPLAY
      - PLAYREADY
      - WIDEVINE
      - IRDETO
    DrmSystems:
      type: array
      items:
        $ref: '#/components/schemas/DrmSystem'
    EndpointErrorCondition:
      type: string
      enum:
      - STALE_MANIFEST
      - INCOMPLETE_MANIFEST
      - MISSING_DRM_KEY
      - SLATE_INPUT
    EndpointErrorConditions:
      type: array
      items:
        $ref: '#/components/schemas/EndpointErrorCondition'
    EntityTag:
      type: string
      pattern: ^[\S]+$
      minLength: 1
      maxLength: 256
    GetDashManifests:
      type: array
      items:
        $ref: '#/components/schemas/GetDashManifestConfiguration'
    GetHlsManifests:
      type: array
      items:
        $ref: '#/components/schemas/GetHlsManifestConfiguration'
    GetLowLatencyHlsManifests:
      type: array
      items:
        $ref: '#/components/schemas/GetLowLatencyHlsManifestConfiguration'
    HarvestJobStatus:
      type: string
      enum:
      - QUEUED
      - IN_PROGRESS
      - CANCELLED
      - COMPLETED
      - FAILED
    HarvestJobsList:
      type: array
      items:
        $ref: '#/components/schemas/HarvestJob'
    HarvestedDashManifestsList:
      type: array
      items:
        $ref: '#/components/schemas/HarvestedDashManifest'
    HarvestedHlsManifestsList:
      type: array
      items:
        $ref: '#/components/schemas/HarvestedHlsManifest'
    HarvestedLowLatencyHlsManifestsList:
      type: array
      items:
        $ref: '#/components/schemas/HarvestedLowLatencyHlsManifest'
    IdempotencyToken:
      type: string
      pattern: ^[\S]+$
      minLength: 1
      maxLength: 256
    IngestEndpointList:
      type: array
      items:
        $ref: '#/components/schemas/IngestEndpoint'
      description: <p>The list of ingest endpoints.</p>
    InputType:
      type: string
      enum:
      - HLS
      - CMAF
    ListDashManifests:
      type: array
      items:
        $ref: '#/components/schemas/ListDashManifestConfiguration'
    ListHlsManifests:
      type: array
      items:
        $ref: '#/components/schemas/ListHlsManifestConfiguration'
    ListLowLatencyHlsManifests:
      type: array
      items:
        $ref: '#/components/schemas/ListLowLatencyHlsManifestConfiguration'
    ListResourceMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ManifestName:
      type: string
      pattern: ^[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 256
    OriginEndpointsList:
      type: array
      items:
        $ref: '#/components/schemas/OriginEndpointListConfiguration'
    PolicyText:
      type: string
      maxLength: 6144
    PresetSpeke20Audio:
      type: string
      enum:
      - PRESET_AUDIO_1
      - PRESET_AUDIO_2
      - PRESET_AUDIO_3
      - SHARED
      - UNENCRYPTED
    PresetSpeke20Video:
      type: string
      enum:
      - PRESET_VIDEO_1
      - PRESET_VIDEO_2
      - PRESET_VIDEO_3
      - PRESET_VIDEO_4
      - PRESET_VIDEO_5
      - PRESET_VIDEO_6
      - PRESET_VIDEO_7
      - PRESET_VIDEO_8
      - SHARED
      - UNENCRYPTED
    ResourceDescription:
      type: string
      minLength: 0
      maxLength: 1024
    ResourceName:
      type: string
      pattern: ^[a-zA-Z0-9_-]+$
      minLength: 1
      maxLength: 256
    ResourceTypeNotFound:
      type: string
      enum:
      - CHANNEL_GROUP
      - CHANNEL
      - ORIGIN_ENDPOINT
      - HARVEST_JOB
    S3BucketName:
      type: string
      minLength: 3
      maxLength: 63
    S3DestinationPath:
      type: string
      pattern: ^[\S]+$
      minLength: 1
      maxLength: 1024
    ScteFilter:
      type: string
      enum:
      - SPLICE_INSERT
      - BREAK
      - PROVIDER_ADVERTISEMENT
      - DISTRIBUTOR_ADVERTISEMENT
      - PROVIDER_PLACEMENT_OPPORTUNITY
      - DISTRIBUTOR_PLACEMENT_OPPORTUNITY
      - PROVIDER_OVERLAY_PLACEMENT_OPPORTUNITY
      - DISTRIBUTOR_OVERLAY_PLACEMENT_OPPORTUNITY
      - PROGRAM
    ScteFilterList:
      type: array
      items:
        $ref: '#/components/schemas/ScteFilter'
    TagArn:
      type: string
    TagKey:
      type: string
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
    TsEncryptionMethod:
      type: string
      enum:
      - AES_128
      - SAMPLE_AES
    ValidationExceptionType:
      type: string
      enum:
      - CONTAINER_TYPE_IMMUTABLE
      - INVALID_PAGINATION_TOKEN
      - INVALID_PAGINATION_MAX_RESULTS
      - INVALID_POLICY
      - INVALID_ROLE_ARN
      - MANIFEST_NAME_COLLISION
      - ENCRYPTION_METHOD_CONTAINER_TYPE_MISMATCH
      - CENC_IV_INCOMPATIBLE
      - ENCRYPTION_CONTRACT_WITHOUT_AUDIO_RENDITION_INCOMPATIBLE
      - ENCRYPTION_CONTRACT_UNENCRYPTED
      - ENCRYPTION_CONTRACT_SHARED
      - NUM_MANIFESTS_LOW
      - NUM_MANIFESTS_HIGH
      - MANIFEST_DRM_SYSTEMS_INCOMPATIBLE
      - DRM_SYSTEMS_ENCRYPTION_METHOD_INCOMPATIBLE
      - ROLE_ARN_NOT_ASSUMABLE
      - ROLE_ARN_LENGTH_OUT_OF_RANGE
      - ROLE_ARN_INVALID_FORMAT
      - URL_INVALID
      - URL_SCHEME
      - URL_USER_INFO
      - URL_PORT
      - URL_UNKNOWN_HOST
      - URL_LOCAL_ADDRESS
      - URL_LOOPBACK_ADDRESS
      - URL_LINK_LOCAL_ADDRESS
      - URL_MULTICAST_ADDRESS
      - MEMBER_INVALID
      - MEMBER_MISSING
      - MEMBER_MIN_VALUE
      - MEMBER_MAX_VALUE
      - MEMBER_MIN_LENGTH
      - MEMBER_MAX_LENGTH
      - MEMBER_INVALID_ENUM_VALUE
      - MEMBER_DOES_NOT_MATCH_PATTERN
      - INVALID_MANIFEST_FILTER
      - INVALID_TIME_DELAY_SECONDS
      - END_TIME_EARLIER_THAN_START_TIME
      - TS_CONTAINER_TYPE_WITH_DASH_MANIFEST
      - DIRECT_MODE_WITH_TIMING_SOURCE
      - NONE_MODE_WITH_TIMING_SOURCE
      - TIMING_SOURCE_MISSING
      - UPDATE_PERIOD_SMALLER_THAN_SEGMENT_DURATION
      - PERIOD_TRIGGERS_NONE_SPECIFIED_WITH_ADDITIONAL_VALUES
      - DRM_SIGNALING_MISMATCH_SEGMENT_ENCRYPTION_STATUS
      - ONLY_CMAF_INPUT_TYPE_ALLOW_FORCE_ENDPOINT_ERROR_CONFIGURATION
      - SOURCE_DISRUPTIONS_ENABLED_INCORRECTLY
      - HARVESTED_MANIFEST_HAS_START_END_FILTER_CONFIGURATION
      - HARVESTED_MANIFEST_NOT_FOUND_ON_ENDPOINT
      - TOO_MANY_IN_PROGRESS_HARVEST_JOBS
      - HARVEST_JOB_INELIGIBLE_FOR_CANCELLATION
      - INVALID_HARVEST_JOB_DURATION
      - HARVEST_JOB_S3_DESTINATION_MISSING_OR_INCOMPLETE
      - HARVEST_JOB_UNABLE_TO_WRITE_TO_S3_DESTINATION
      - HARVEST_JOB_CUSTOMER_ENDPOINT_READ_ACCESS_DENIED
      - CLIP_START_TIME_WITH_START_OR_END
      - START_TAG_TIME_OFFSET_INVALID
      - ONLY_CMAF_INPUT_TYPE_ALLOW_MQCS_INPUT_SWITCHING
      - ONLY_CMAF_INPUT_TYPE_ALLOW_MQCS_OUTPUT_CONFIGURATION
