openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: mgn
  x-aws-serviceName: mgn
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-02-26'
  title: Application Migration Service
  description: |-
    The Application Migration Service service.
servers:
- description: The Application Migration Service regional endpoint
  url: https://mgn.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ARN:
      type: string
      minLength: 20
      maxLength: 2048
    AccountID:
      type: string
      pattern: '[0-9]{12,}'
      minLength: 12
      maxLength: 12
    ActionCategory:
      type: string
      enum:
      - DISASTER_RECOVERY
      - OPERATING_SYSTEM
      - LICENSE_AND_SUBSCRIPTION
      - VALIDATION
      - OBSERVABILITY
      - REFACTORING
      - SECURITY
      - NETWORKING
      - CONFIGURATION
      - BACKUP
      - OTHER
    ActionDescription:
      type: string
      pattern: '^[0-9a-zA-Z ():/.,''-_#*;

        ]*$'
      minLength: 0
      maxLength: 256
    ActionID:
      type: string
      pattern: '[0-9a-zA-Z]$'
      minLength: 1
      maxLength: 64
    ActionName:
      type: string
      pattern: ^[^\s\x00]( *[^\s\x00])*$
      minLength: 1
      maxLength: 256
    ApplianceID:
      type: string
      pattern: ^appliance-[0-9a-zA-Z]{17}$
      minLength: 27
      maxLength: 27
    ApplicationDescription:
      type: string
      pattern: ^[^\x00]*$
      minLength: 0
      maxLength: 600
    ApplicationHealthStatus:
      type: string
      enum:
      - HEALTHY
      - LAGGING
      - ERROR
    ApplicationID:
      type: string
      pattern: ^app-[0-9a-zA-Z]{17}$
      minLength: 21
      maxLength: 21
    ApplicationName:
      type: string
      pattern: ^[^\s\x00]( *[^\s\x00])*$
      minLength: 1
      maxLength: 256
    ApplicationProgressStatus:
      type: string
      enum:
      - NOT_STARTED
      - IN_PROGRESS
      - COMPLETED
    BootMode:
      type: string
      enum:
      - LEGACY_BIOS
      - UEFI
      - USE_SOURCE
    BoundedString:
      type: string
      minLength: 0
      maxLength: 256
    ChangeServerLifeCycleStateSourceServerLifecycleState:
      type: string
      enum:
      - READY_FOR_TEST
      - READY_FOR_CUTOVER
      - CUTOVER
    ClientIdempotencyToken:
      type: string
      minLength: 0
      maxLength: 64
    CloudWatchLogGroupName:
      type: string
      pattern: ^[\.\-_/#A-Za-z0-9]+$
      minLength: 1
      maxLength: 512
    ConnectorArn:
      type: string
      pattern: ^arn:[\w-]+:mgn:([a-z]{2}-(gov-)?[a-z]+-\d{1})?:(\d{12})?:connector\/(connector-[0-9a-zA-Z]{17})$
      minLength: 27
      maxLength: 100
    ConnectorID:
      type: string
      pattern: ^connector-[0-9a-zA-Z]{17}$
      minLength: 27
      maxLength: 27
    ConnectorName:
      type: string
      pattern: ^[A-Za-z0-9_-]+$
      minLength: 1
      maxLength: 256
    DataReplicationErrorString:
      type: string
      enum:
      - AGENT_NOT_SEEN
      - SNAPSHOTS_FAILURE
      - NOT_CONVERGING
      - UNSTABLE_NETWORK
      - FAILED_TO_CREATE_SECURITY_GROUP
      - FAILED_TO_LAUNCH_REPLICATION_SERVER
      - FAILED_TO_BOOT_REPLICATION_SERVER
      - FAILED_TO_AUTHENTICATE_WITH_SERVICE
      - FAILED_TO_DOWNLOAD_REPLICATION_SOFTWARE
      - FAILED_TO_CREATE_STAGING_DISKS
      - FAILED_TO_ATTACH_STAGING_DISKS
      - FAILED_TO_PAIR_REPLICATION_SERVER_WITH_AGENT
      - FAILED_TO_CONNECT_AGENT_TO_REPLICATION_SERVER
      - FAILED_TO_START_DATA_TRANSFER
      - UNSUPPORTED_VM_CONFIGURATION
      - LAST_SNAPSHOT_JOB_FAILED
    DataReplicationInitiationStepName:
      type: string
      enum:
      - WAIT
      - CREATE_SECURITY_GROUP
      - LAUNCH_REPLICATION_SERVER
      - BOOT_REPLICATION_SERVER
      - AUTHENTICATE_WITH_SERVICE
      - DOWNLOAD_REPLICATION_SOFTWARE
      - CREATE_STAGING_DISKS
      - ATTACH_STAGING_DISKS
      - PAIR_REPLICATION_SERVER_WITH_AGENT
      - CONNECT_AGENT_TO_REPLICATION_SERVER
      - START_DATA_TRANSFER
    DataReplicationInitiationStepStatus:
      type: string
      enum:
      - NOT_STARTED
      - IN_PROGRESS
      - SUCCEEDED
      - FAILED
      - SKIPPED
    DataReplicationState:
      type: string
      enum:
      - STOPPED
      - INITIATING
      - INITIAL_SYNC
      - BACKLOG
      - CREATING_SNAPSHOT
      - CONTINUOUS
      - PAUSED
      - RESCAN
      - STALLED
      - DISCONNECTED
      - PENDING_SNAPSHOT_SHIPPING
      - SHIPPING_SNAPSHOT
    DocumentVersion:
      type: string
      pattern: ^(\$DEFAULT|\$LATEST|[0-9]+)$
    EC2InstanceID:
      type: string
      pattern: ^i-[0-9a-fA-F]{8,}$
      minLength: 0
      maxLength: 255
    EC2InstanceType:
      type: string
      minLength: 0
      maxLength: 255
    EC2LaunchConfigurationTemplateID:
      type: string
      pattern: ^lt-[0-9a-z]{17}$
      minLength: 20
      maxLength: 20
    ExportID:
      type: string
      pattern: ^export-[0-9a-zA-Z]{17}$
      minLength: 24
      maxLength: 24
    ExportStatus:
      type: string
      enum:
      - PENDING
      - STARTED
      - FAILED
      - SUCCEEDED
    FirstBoot:
      type: string
      enum:
      - WAITING
      - SUCCEEDED
      - UNKNOWN
      - STOPPED
    ISO8601DatetimeString:
      type: string
      pattern: ^[1-9][0-9]*-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([0-1][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?Z$
      minLength: 19
      maxLength: 32
    ISO8601DurationString:
      type: string
      minLength: 1
      maxLength: 64
    ImportErrorType:
      type: string
      enum:
      - VALIDATION_ERROR
      - PROCESSING_ERROR
    ImportID:
      type: string
      pattern: ^import-[0-9a-zA-Z]{17}$
      minLength: 24
      maxLength: 24
    ImportStatus:
      type: string
      enum:
      - PENDING
      - STARTED
      - FAILED
      - SUCCEEDED
    InitiatedBy:
      type: string
      enum:
      - START_TEST
      - START_CUTOVER
      - DIAGNOSTIC
      - TERMINATE
    JmesPathString:
      type: string
      pattern: ^[a-zA-Z0-9_]+(\.[a-zA-Z0-9_\[\]]+)*$
      minLength: 1
      maxLength: 1011
    JobID:
      type: string
      pattern: ^mgnjob-[0-9a-zA-Z]{17}$
      minLength: 24
      maxLength: 24
    JobLogEvent:
      type: string
      enum:
      - JOB_START
      - SERVER_SKIPPED
      - CLEANUP_START
      - CLEANUP_END
      - CLEANUP_FAIL
      - SNAPSHOT_START
      - SNAPSHOT_END
      - SNAPSHOT_FAIL
      - USING_PREVIOUS_SNAPSHOT
      - CONVERSION_START
      - CONVERSION_END
      - CONVERSION_FAIL
      - LAUNCH_START
      - LAUNCH_FAILED
      - JOB_CANCEL
      - JOB_END
    JobStatus:
      type: string
      enum:
      - PENDING
      - STARTED
      - COMPLETED
    JobType:
      type: string
      enum:
      - LAUNCH
      - TERMINATE
    LargeBoundedString:
      type: string
      minLength: 0
      maxLength: 65536
    LaunchConfigurationTemplateID:
      type: string
      pattern: ^lct-[0-9a-zA-Z]{17}$
      minLength: 21
      maxLength: 21
    LaunchDisposition:
      type: string
      enum:
      - STOPPED
      - STARTED
    LaunchStatus:
      type: string
      enum:
      - PENDING
      - IN_PROGRESS
      - LAUNCHED
      - FAILED
      - TERMINATED
    LifeCycleState:
      type: string
      enum:
      - STOPPED
      - NOT_READY
      - READY_FOR_TEST
      - TESTING
      - READY_FOR_CUTOVER
      - CUTTING_OVER
      - CUTOVER
      - DISCONNECTED
      - DISCOVERED
      - PENDING_INSTALLATION
    MaxResultsType:
      type: integer
      minimum: 1
      maximum: 1000
    OperatingSystemString:
      type: string
      pattern: ^(linux|windows)$
    OrderType:
      type: integer
      minimum: 1001
      maximum: 10000
    PaginationToken:
      type: string
      minLength: 0
      maxLength: 2048
    PostLaunchActionExecutionStatus:
      type: string
      enum:
      - IN_PROGRESS
      - SUCCESS
      - FAILED
    PostLaunchActionsDeploymentType:
      type: string
      enum:
      - TEST_AND_CUTOVER
      - CUTOVER_ONLY
      - TEST_ONLY
    ReplicationConfigurationDataPlaneRouting:
      type: string
      enum:
      - PRIVATE_IP
      - PUBLIC_IP
    ReplicationConfigurationDefaultLargeStagingDiskType:
      type: string
      enum:
      - GP2
      - ST1
      - GP3
    ReplicationConfigurationEbsEncryption:
      type: string
      enum:
      - DEFAULT
      - CUSTOM
    ReplicationConfigurationReplicatedDiskStagingDiskType:
      type: string
      enum:
      - AUTO
      - GP2
      - IO1
      - SC1
      - ST1
      - STANDARD
      - GP3
      - IO2
    ReplicationConfigurationTemplateID:
      type: string
      pattern: ^rct-[0-9a-zA-Z]{17}$
      minLength: 21
      maxLength: 21
    ReplicationType:
      type: string
      enum:
      - AGENT_BASED
      - SNAPSHOT_SHIPPING
    S3BucketName:
      type: string
      pattern: ^[a-zA-Z0-9.\-_]{1,255}$
    S3Key:
      type: string
      pattern: ^[^\x00]{1,1020}\.csv$
    S3LogBucketName:
      type: string
      minLength: 3
      maxLength: 63
    SecretArn:
      type: string
      pattern: ^arn:[\w-]+:secretsmanager:([a-z]{2}-(gov-)?[a-z]+-\d{1})?:(\d{12})?:secret:(.+)$
      minLength: 20
      maxLength: 100
    SecurityGroupID:
      type: string
      pattern: ^sg-[0-9a-fA-F]{8,}$
      minLength: 0
      maxLength: 255
    SmallBoundedString:
      type: string
      minLength: 0
      maxLength: 128
    SourceServerID:
      type: string
      pattern: ^s-[0-9a-zA-Z]{17}$
      minLength: 19
      maxLength: 19
    SsmDocumentName:
      type: string
      pattern: ^([A-Za-z0-9/:_\.-])+$
      minLength: 3
      maxLength: 172
    SsmDocumentParameterName:
      type: string
      pattern: ^([A-Za-z0-9])+$
      minLength: 1
      maxLength: 1011
    SsmDocumentType:
      type: string
      enum:
      - AUTOMATION
      - COMMAND
    SsmInstanceID:
      type: string
      pattern: (^i-[0-9a-zA-Z]{17}$)|(^mi-[0-9a-zA-Z]{17}$)
      minLength: 19
      maxLength: 20
    SsmParameterStoreParameterName:
      type: string
      pattern: ^([A-Za-z0-9_\.-])+$
      minLength: 1
      maxLength: 1011
    SsmParameterStoreParameterType:
      type: string
      enum:
      - STRING
    StrictlyPositiveInteger:
      type: integer
      minimum: 1
    SubnetID:
      type: string
      pattern: ^subnet-[0-9a-fA-F]{8,}$
      minLength: 0
      maxLength: 255
    TagKey:
      type: string
      minLength: 0
      maxLength: 256
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TargetInstanceTypeRightSizingMethod:
      type: string
      enum:
      - NONE
      - BASIC
    ValidationExceptionReason:
      type: string
      enum:
      - unknownOperation
      - cannotParse
      - fieldValidationFailed
      - other
    VcenterClientID:
      type: string
      pattern: ^vcc-[0-9a-zA-Z]{17}$
      minLength: 21
      maxLength: 21
    VolumeType:
      type: string
      enum:
      - io1
      - io2
      - gp3
      - gp2
      - st1
      - sc1
      - standard
    WaveDescription:
      type: string
      pattern: ^[^\x00]*$
      minLength: 0
      maxLength: 600
    WaveHealthStatus:
      type: string
      enum:
      - HEALTHY
      - LAGGING
      - ERROR
    WaveID:
      type: string
      pattern: ^wave-[0-9a-zA-Z]{17}$
      minLength: 22
      maxLength: 22
    WaveName:
      type: string
      pattern: ^[^\s\x00]( *[^\s\x00])*$
      minLength: 1
      maxLength: 256
    WaveProgressStatus:
      type: string
      enum:
      - NOT_STARTED
      - IN_PROGRESS
      - COMPLETED
