openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: migrationhubstrategy
  x-aws-serviceName: migrationhubstrategy
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-02-19'
  title: Migration Hub Strategy Recommendations
  description: |-
    Migration Hub Strategy Recommendations

    This API reference provides descriptions, syntax, and other details about each of the actions and data types for Migration Hub Strategy Recommendations (Strategy Recommendations). The topic for each action shows the API request parameters and the response. Alternatively, you can use one of the AWS SDKs to access an API that is tailored to the programming language or platform that you're using. For more information, see [AWS SDKs](http://aws.amazon.com/tools/#SDKs).
servers:
- description: The Migration Hub Strategy Recommendations regional endpoint
  url: https://migrationhub-strategy.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AnalysisType:
      type: string
      enum:
      - SOURCE_CODE_ANALYSIS
      - DATABASE_ANALYSIS
      - RUNTIME_ANALYSIS
      - BINARY_ANALYSIS
    AntipatternReportStatus:
      type: string
      enum:
      - FAILED
      - IN_PROGRESS
      - SUCCESS
    AppType:
      type: string
      enum:
      - DotNetFramework
      - Java
      - SQLServer
      - IIS
      - Oracle
      - Other
      - Tomcat
      - JBoss
      - Spring
      - Mongo DB
      - DB2
      - Maria DB
      - MySQL
      - Sybase
      - PostgreSQLServer
      - Cassandra
      - IBM WebSphere
      - Oracle WebLogic
      - Visual Basic
      - Unknown
      - DotnetCore
      - Dotnet
    AppUnitErrorCategory:
      type: string
      enum:
      - CREDENTIAL_ERROR
      - CONNECTIVITY_ERROR
      - PERMISSION_ERROR
      - UNSUPPORTED_ERROR
      - OTHER_ERROR
    ApplicationComponentCriteria:
      type: string
      enum:
      - NOT_DEFINED
      - APP_NAME
      - SERVER_ID
      - APP_TYPE
      - STRATEGY
      - DESTINATION
      - ANALYSIS_STATUS
      - ERROR_CATEGORY
    ApplicationComponentId:
      type: string
      pattern: '[0-9a-zA-Z-]+'
      maxLength: 44
    ApplicationMode:
      type: string
      enum:
      - ALL
      - KNOWN
      - UNKNOWN
    AssessmentDataSourceType:
      type: string
      enum:
      - StrategyRecommendationsApplicationDataCollector
      - ManualImport
      - ApplicationDiscoveryService
    AssessmentStatus:
      type: string
      enum:
      - IN_PROGRESS
      - COMPLETE
      - FAILED
      - STOPPED
    AssessmentStatusMessage:
      type: string
      pattern: .*\S.*
      minLength: 0
      maxLength: 512
    AsyncTaskId:
      type: string
      pattern: '[0-9a-z-:]+'
      minLength: 0
      maxLength: 52
    AuthType:
      type: string
      enum:
      - NTLM
      - SSH
      - CERT
    AwsManagedTargetDestination:
      type: string
      enum:
      - None specified
      - AWS Elastic BeanStalk
      - AWS Fargate
    BinaryAnalyzerName:
      type: string
      enum:
      - DLL_ANALYZER
      - BYTECODE_ANALYZER
    Boolean:
      type: boolean
    BusinessGoalsInteger:
      type: integer
      minimum: 1
      maximum: 5
    CollectorHealth:
      type: string
      enum:
      - COLLECTOR_HEALTHY
      - COLLECTOR_UNHEALTHY
    Condition:
      type: string
      enum:
      - EQUALS
      - NOT_EQUALS
      - CONTAINS
      - NOT_CONTAINS
    DataSourceType:
      type: string
      enum:
      - ApplicationDiscoveryService
      - MPA
      - Import
      - StrategyRecommendationsApplicationDataCollector
    DatabaseManagementPreference:
      type: string
      enum:
      - AWS-managed
      - Self-manage
      - No preference
    GroupName:
      type: string
      enum:
      - ExternalId
      - ExternalSourceType
    HeterogeneousTargetDatabaseEngine:
      type: string
      enum:
      - None specified
      - Amazon Aurora
      - AWS PostgreSQL
      - MySQL
      - Microsoft SQL Server
      - Oracle Database
      - MariaDB
      - SAP
      - Db2 LUW
      - MongoDB
    HomogeneousTargetDatabaseEngine:
      type: string
      enum:
      - None specified
    IPAddress:
      type: string
      pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
      minLength: 0
      maxLength: 15
    ImportFileTaskStatus:
      type: string
      enum:
      - ImportInProgress
      - ImportFailed
      - ImportPartialSuccess
      - ImportSuccess
      - DeleteInProgress
      - DeleteFailed
      - DeletePartialSuccess
      - DeleteSuccess
    InclusionStatus:
      type: string
      enum:
      - excludeFromAssessment
      - includeInAssessment
    Integer:
      type: integer
    InterfaceName:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 1024
    Location:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 128
    MacAddress:
      type: string
      pattern: ^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})|([0-9a-fA-F]{4}\\.[0-9a-fA-F]{4}\\.[0-9a-fA-F]{4})$”$
      minLength: 0
      maxLength: 17
    MaxResult:
      type: integer
    NetMask:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 1024
    NextToken:
      type: string
      pattern: .*\S.*
      minLength: 0
      maxLength: 2048
    NoPreferenceTargetDestination:
      type: string
      enum:
      - None specified
      - AWS Elastic BeanStalk
      - AWS Fargate
      - Amazon Elastic Cloud Compute (EC2)
      - Amazon Elastic Container Service (ECS)
      - Amazon Elastic Kubernetes Service (EKS)
    OSType:
      type: string
      enum:
      - LINUX
      - WINDOWS
    OSVersion:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 64
    OutputFormat:
      type: string
      enum:
      - Excel
      - Json
    PipelineType:
      type: string
      enum:
      - AZURE_DEVOPS
    ProjectName:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 128
    RecommendationReportStatus:
      type: string
      enum:
      - FAILED
      - IN_PROGRESS
      - SUCCESS
    RecommendationReportStatusMessage:
      type: string
      pattern: .*\S.*
      minLength: 0
      maxLength: 512
    RecommendationTaskId:
      type: string
      pattern: '[0-9a-z-:]+'
      minLength: 0
      maxLength: 52
    ResourceId:
      type: string
      pattern: ^[0-9a-b]+
      minLength: 0
      maxLength: 44
    ResourceName:
      type: string
    ResourceSubType:
      type: string
      enum:
      - Database
      - Process
      - DatabaseProcess
    RunTimeAnalyzerName:
      type: string
      enum:
      - A2C_ANALYZER
      - REHOST_ANALYZER
      - EMP_PA_ANALYZER
      - DATABASE_ANALYZER
      - SCT_ANALYZER
    RunTimeAssessmentStatus:
      type: string
      enum:
      - dataCollectionTaskToBeScheduled
      - dataCollectionTaskScheduled
      - dataCollectionTaskStarted
      - dataCollectionTaskStopped
      - dataCollectionTaskSuccess
      - dataCollectionTaskFailed
      - dataCollectionTaskPartialSuccess
    RuntimeAnalysisStatus:
      type: string
      enum:
      - ANALYSIS_TO_BE_SCHEDULED
      - ANALYSIS_STARTED
      - ANALYSIS_SUCCESS
      - ANALYSIS_FAILED
    S3Bucket:
      type: string
      pattern: '[0-9a-z]+[0-9a-z\.\-]*[0-9a-z]+'
      minLength: 0
      maxLength: 63
    S3Key:
      type: string
      pattern: .*\S.*
      minLength: 0
      maxLength: 1024
    SecretsManagerKey:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 512
    SelfManageTargetDestination:
      type: string
      enum:
      - None specified
      - Amazon Elastic Cloud Compute (EC2)
      - Amazon Elastic Container Service (ECS)
      - Amazon Elastic Kubernetes Service (EKS)
    ServerCriteria:
      type: string
      enum:
      - NOT_DEFINED
      - OS_NAME
      - STRATEGY
      - DESTINATION
      - SERVER_ID
      - ANALYSIS_STATUS
      - ERROR_CATEGORY
    ServerErrorCategory:
      type: string
      enum:
      - CONNECTIVITY_ERROR
      - CREDENTIAL_ERROR
      - PERMISSION_ERROR
      - ARCHITECTURE_ERROR
      - OTHER_ERROR
    ServerId:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 27
    ServerOsType:
      type: string
      enum:
      - WindowsServer
      - AmazonLinux
      - EndOfSupportWindowsServer
      - Redhat
      - Other
    Severity:
      type: string
      enum:
      - HIGH
      - MEDIUM
      - LOW
    SortOrder:
      type: string
      enum:
      - ASC
      - DESC
    SourceCodeAnalyzerName:
      type: string
      enum:
      - CSHARP_ANALYZER
      - JAVA_ANALYZER
      - BYTECODE_ANALYZER
      - PORTING_ASSISTANT
    SourceVersion:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 40
    SrcCodeOrDbAnalysisStatus:
      type: string
      enum:
      - ANALYSIS_TO_BE_SCHEDULED
      - ANALYSIS_STARTED
      - ANALYSIS_SUCCESS
      - ANALYSIS_FAILED
      - ANALYSIS_PARTIAL_SUCCESS
      - UNCONFIGURED
      - CONFIGURED
    StatusMessage:
      type: string
      pattern: .*\S.*
      minLength: 0
      maxLength: 1024
    Strategy:
      type: string
      enum:
      - Rehost
      - Retirement
      - Refactor
      - Replatform
      - Retain
      - Relocate
      - Repurchase
    StrategyRecommendation:
      type: string
      enum:
      - recommended
      - viableOption
      - notRecommended
      - potential
    String:
      type: string
      pattern: .*\S.*
      minLength: 0
      maxLength: 1024
    TargetDatabaseEngine:
      type: string
      enum:
      - None specified
      - Amazon Aurora
      - AWS PostgreSQL
      - MySQL
      - Microsoft SQL Server
      - Oracle Database
      - MariaDB
      - SAP
      - Db2 LUW
      - MongoDB
    TargetDestination:
      type: string
      enum:
      - None specified
      - AWS Elastic BeanStalk
      - AWS Fargate
      - Amazon Elastic Cloud Compute (EC2)
      - Amazon Elastic Container Service (ECS)
      - Amazon Elastic Kubernetes Service (EKS)
      - Aurora MySQL
      - Aurora PostgreSQL
      - Amazon Relational Database Service on MySQL
      - Amazon Relational Database Service on PostgreSQL
      - Amazon DocumentDB
      - Amazon DynamoDB
      - Amazon Relational Database Service
      - Babelfish for Aurora PostgreSQL
    TranformationToolDescription:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 1024
    TranformationToolInstallationLink:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 1024
    TransformationToolName:
      type: string
      enum:
      - App2Container
      - Porting Assistant For .NET
      - End of Support Migration
      - Windows Web Application Migration Assistant
      - Application Migration Service
      - Strategy Recommendation Support
      - In Place Operating System Upgrade
      - Schema Conversion Tool
      - Database Migration Service
      - Native SQL Server Backup/Restore
    VersionControl:
      type: string
      enum:
      - GITHUB
      - GITHUB_ENTERPRISE
      - AZURE_DEVOPS_GIT
    VersionControlType:
      type: string
      enum:
      - GITHUB
      - GITHUB_ENTERPRISE
      - AZURE_DEVOPS_GIT
    errorMessage:
      type: string
    importS3Bucket:
      type: string
      pattern: '[0-9a-z]+[0-9a-z\.\-]*[0-9a-z]+'
      minLength: 0
      maxLength: 63
    importS3Key:
      type: string
      pattern: .*\S.*
      minLength: 0
      maxLength: 1024
