openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: migration_hub_refactor_spaces
  x-aws-serviceName: migrationhubrefactorspaces
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2021-10-26'
  title: AWS Migration Hub Refactor Spaces
  description: |-
    Amazon Web Services Migration Hub Refactor Spaces

    This API reference provides descriptions, syntax, and other details about each of the actions and data types for Amazon Web Services Migration Hub Refactor Spaces (Refactor Spaces). The topic for each action shows the API request parameters and the response. Alternatively, you can use one of the Amazon Web Services SDKs to access an API that is tailored to the programming language or platform that you're using. For more information, see [Amazon Web Services SDKs](https://aws.amazon.com/tools/#SDKs).

    To share Refactor Spaces environments with other Amazon Web Services accounts or with Organizations and their OUs, use Resource Access Manager's `CreateResourceShare` API. See [CreateResourceShare](https://docs.aws.amazon.com/ram/latest/APIReference/API_CreateResourceShare.html) in the _Amazon Web Services RAM API Reference_.
servers:
- description: The AWS Migration Hub Refactor Spaces regional endpoint
  url: https://refactor-spaces.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccountId:
      type: string
      pattern: ^\d{12}$
      minLength: 12
      maxLength: 12
    AdditionalDetailsKey:
      type: string
      minLength: 1
      maxLength: 50
    AdditionalDetailsValue:
      type: string
      minLength: 1
      maxLength: 2048
    ApiGatewayEndpointType:
      type: string
      enum:
      - REGIONAL
      - PRIVATE
    ApiGatewayId:
      type: string
      pattern: ^[a-z0-9]{10}$
      minLength: 10
      maxLength: 10
    ApplicationId:
      type: string
      pattern: ^app-[0-9A-Za-z]{10}$
      minLength: 14
      maxLength: 14
    ApplicationName:
      type: string
      pattern: ^(?!app-)[a-zA-Z0-9]+[a-zA-Z0-9-_ ]+$
      minLength: 3
      maxLength: 63
    ApplicationState:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - DELETING
      - FAILED
      - UPDATING
    Boolean:
      type: boolean
    CidrBlock:
      type: string
    ClientToken:
      type: string
      pattern: ^[\x20-\x7E]{1,64}$
      minLength: 1
      maxLength: 64
    Description:
      type: string
      pattern: ^[a-zA-Z0-9-_\s\.\!\*\#\@\']+$
      minLength: 1
      maxLength: 256
    Ec2TagValue:
      type: string
      pattern: ^.*$
      minLength: 0
      maxLength: 255
    EnvironmentId:
      type: string
      pattern: ^env-[0-9A-Za-z]{10}$
      minLength: 14
      maxLength: 14
    EnvironmentName:
      type: string
      pattern: ^(?!env-)[a-zA-Z0-9]+[a-zA-Z0-9-_ ]+$
      minLength: 3
      maxLength: 63
    EnvironmentState:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - DELETING
      - FAILED
    ErrorCode:
      type: string
      enum:
      - INVALID_RESOURCE_STATE
      - RESOURCE_LIMIT_EXCEEDED
      - RESOURCE_CREATION_FAILURE
      - RESOURCE_UPDATE_FAILURE
      - SERVICE_ENDPOINT_HEALTH_CHECK_FAILURE
      - RESOURCE_DELETION_FAILURE
      - RESOURCE_RETRIEVAL_FAILURE
      - RESOURCE_IN_USE
      - RESOURCE_NOT_FOUND
      - STATE_TRANSITION_FAILURE
      - REQUEST_LIMIT_EXCEEDED
      - NOT_AUTHORIZED
    ErrorMessage:
      type: string
      pattern: ^[\p{Alnum}\p{Punct}\p{Blank}]*$
      minLength: 0
      maxLength: 255
    ErrorResourceType:
      type: string
      enum:
      - ENVIRONMENT
      - APPLICATION
      - ROUTE
      - SERVICE
      - TRANSIT_GATEWAY
      - TRANSIT_GATEWAY_ATTACHMENT
      - API_GATEWAY
      - NLB
      - TARGET_GROUP
      - LOAD_BALANCER_LISTENER
      - VPC_LINK
      - LAMBDA
      - VPC
      - SUBNET
      - ROUTE_TABLE
      - SECURITY_GROUP
      - VPC_ENDPOINT_SERVICE_CONFIGURATION
      - RESOURCE_SHARE
      - IAM_ROLE
    HttpMethod:
      type: string
      enum:
      - DELETE
      - GET
      - HEAD
      - OPTIONS
      - PATCH
      - POST
      - PUT
    LambdaArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*)?:lambda:[a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1}:\d{12}:function:[a-zA-Z0-9-_]+(:(\$LATEST|[a-zA-Z0-9-_]+))?$
      minLength: 1
      maxLength: 2048
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    NetworkFabricType:
      type: string
      enum:
      - TRANSIT_GATEWAY
      - NONE
    NextToken:
      type: string
      pattern: ^[a-zA-Z0-9/\+\=]{0,2048}$
      minLength: 1
      maxLength: 2048
    NlbArn:
      type: string
      pattern: ^arn:aws:elasticloadbalancing:[a-zA-Z0-9\-]+:\w{12}:[a-zA-Z_0-9+=,.@\-_/]+$
      minLength: 20
      maxLength: 2048
    NlbName:
      type: string
      pattern: ^(?!internal-)[a-zA-Z0-9]+[a-zA-Z0-9-_ ]+.*[^-]$
      minLength: 1
      maxLength: 32
    PathResourceToIdKey:
      type: string
      minLength: 1
      maxLength: 2048
    PathResourceToIdValue:
      type: string
      pattern: ^[a-z0-9]{10}$
      minLength: 10
      maxLength: 10
    PolicyString:
      type: string
      pattern: ^.*\S.*$
      minLength: 1
      maxLength: 300000
    ProxyType:
      type: string
      enum:
      - API_GATEWAY
    ResourceArn:
      type: string
      pattern: ^arn:aws:refactor-spaces:[a-zA-Z0-9\-]+:\w{12}:[a-zA-Z_0-9+=,.@\-_/]+$
      minLength: 20
      maxLength: 2048
    ResourceIdentifier:
      type: string
      pattern: (^(env|svc|pxy|rte|app)-([0-9A-Za-z]{10}$))
      minLength: 3
      maxLength: 63
    ResourcePolicyIdentifier:
      type: string
      pattern: ^arn:aws:refactor-spaces:[a-zA-Z0-9\-]+:\w{12}:[a-zA-Z_0-9+=,.@\-_/]+$
      minLength: 20
      maxLength: 2048
    RetryAfterSeconds:
      type: integer
      default: 0
    RouteActivationState:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
    RouteId:
      type: string
      pattern: ^rte-[0-9A-Za-z]{10}$
      minLength: 14
      maxLength: 14
    RouteState:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - DELETING
      - FAILED
      - UPDATING
      - INACTIVE
    RouteType:
      type: string
      enum:
      - DEFAULT
      - URI_PATH
    ServiceEndpointType:
      type: string
      enum:
      - LAMBDA
      - URL
    ServiceId:
      type: string
      pattern: ^svc-[0-9A-Za-z]{10}$
      minLength: 14
      maxLength: 14
    ServiceName:
      type: string
      pattern: ^(?!svc-)[a-zA-Z0-9]+[a-zA-Z0-9-_ ]+$
      minLength: 3
      maxLength: 63
    ServiceState:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - DELETING
      - FAILED
    StageName:
      type: string
      pattern: ^[-a-zA-Z0-9_]*$
      minLength: 1
      maxLength: 128
    String:
      type: string
    TransitGatewayId:
      type: string
      pattern: ^tgw-[-a-f0-9]{17}$
      minLength: 21
      maxLength: 21
    Uri:
      type: string
      pattern: ^https?://[-a-zA-Z0-9+\x38@#/%?=~_|!:,.;]*[-a-zA-Z0-9+\x38@#/%=~_|]$
      minLength: 1
      maxLength: 2048
    UriPath:
      type: string
      pattern: ^(/([a-zA-Z0-9._:-]+|\{[a-zA-Z0-9._:-]+\}))+$
      minLength: 1
      maxLength: 2048
    VpcId:
      type: string
      pattern: ^vpc-[-a-f0-9]{8}([-a-f0-9]{9})?$
      minLength: 12
      maxLength: 21
    VpcLinkId:
      type: string
      pattern: ^[a-z0-9]{10}$
      minLength: 10
      maxLength: 10
