openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: migrationhuborchestrator
  x-aws-serviceName: migrationhuborchestrator
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2021-08-28'
  title: AWS Migration Hub Orchestrator
  description: |-
    This API reference provides descriptions, syntax, and other details about each of the actions and data types for AWS Migration Hub Orchestrator. The topic for each action shows the API request parameters and responses. Alternatively, you can use one of the AWS SDKs to access an API that is tailored to the programming language or platform that you're using.
servers:
- description: The AWS Migration Hub Orchestrator regional endpoint
  url: https://migrationhub-orchestrator.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ApplicationConfigurationName:
      type: string
      pattern: ^[-a-zA-Z0-9_.+]+[-a-zA-Z0-9_.+ ]*$
      minLength: 1
      maxLength: 100
    ClientToken:
      type: string
      pattern: ^[-a-zA-Z0-9]*$
      minLength: 1
      maxLength: 256
    DataType:
      type: string
      enum:
      - STRING
      - INTEGER
      - STRINGLIST
      - STRINGMAP
    IPAddress:
      type: string
      pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
      minLength: 0
      maxLength: 15
    MaxResults:
      type: integer
      default: 0
      minimum: 0
      maximum: 100
    MaxStringValue:
      type: string
      minLength: 0
      maxLength: 2048
    MigrationWorkflowDescription:
      type: string
      pattern: ^[-a-zA-Z0-9_.+, ]*$
      minLength: 0
      maxLength: 500
    MigrationWorkflowId:
      type: string
      pattern: ^[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 100
    MigrationWorkflowName:
      type: string
      pattern: ^[-a-zA-Z0-9_.+]+[-a-zA-Z0-9_.+ ]*$
      minLength: 1
      maxLength: 100
    MigrationWorkflowStatusEnum:
      type: string
      enum:
      - CREATING
      - NOT_STARTED
      - CREATION_FAILED
      - STARTING
      - IN_PROGRESS
      - WORKFLOW_FAILED
      - PAUSED
      - PAUSING
      - PAUSING_FAILED
      - USER_ATTENTION_REQUIRED
      - DELETING
      - DELETION_FAILED
      - DELETED
      - COMPLETED
    NextToken:
      type: string
      pattern: .*\S.*
      minLength: 0
      maxLength: 2048
    Owner:
      type: string
      enum:
      - AWS_MANAGED
      - CUSTOM
    PluginHealth:
      type: string
      enum:
      - HEALTHY
      - UNHEALTHY
    PluginId:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 60
    PluginVersion:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 1024
    ResourceArn:
      type: string
      pattern: ^arn:aws:migrationhub-orchestrator:[a-z0-9-]+:[0-9]+:(template|workflow)/[.]*$
    RunEnvironment:
      type: string
      enum:
      - AWS
      - ONPREMISE
    S3Bucket:
      type: string
      pattern: ^[0-9a-z]+[0-9a-z\.\-]*[0-9a-z]+$
      minLength: 0
      maxLength: 63
    S3Key:
      type: string
      minLength: 0
      maxLength: 1024
    StepActionType:
      type: string
      enum:
      - MANUAL
      - AUTOMATED
    StepDescription:
      type: string
      pattern: ^[-a-zA-Z0-9_.+, ]*$
      minLength: 0
      maxLength: 500
    StepGroupDescription:
      type: string
      pattern: ^[-a-zA-Z0-9_.+, ]*$
      minLength: 0
      maxLength: 500
    StepGroupId:
      type: string
      pattern: ^[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 100
    StepGroupName:
      type: string
      pattern: ^[-a-zA-Z0-9_.+]+[-a-zA-Z0-9_.+ ]*$
      minLength: 1
      maxLength: 100
    StepGroupStatus:
      type: string
      enum:
      - AWAITING_DEPENDENCIES
      - READY
      - IN_PROGRESS
      - COMPLETED
      - FAILED
      - PAUSED
      - PAUSING
      - USER_ATTENTION_REQUIRED
    StepId:
      type: string
      pattern: ^[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 100
    StepInputParametersKey:
      type: string
      pattern: ^[a-zA-Z0-9-_ ()]+$
      minLength: 1
      maxLength: 100
    StepName:
      type: string
      pattern: ^[-a-zA-Z0-9_.+]+[-a-zA-Z0-9_.+ ]*$
      minLength: 1
      maxLength: 100
    StepStatus:
      type: string
      enum:
      - AWAITING_DEPENDENCIES
      - SKIPPED
      - READY
      - IN_PROGRESS
      - COMPLETED
      - FAILED
      - PAUSED
      - USER_ATTENTION_REQUIRED
    StringListMember:
      type: string
      minLength: 0
      maxLength: 500
    StringMapKey:
      type: string
      pattern: ^[a-zA-Z0-9-_ ()]+$
      minLength: 1
      maxLength: 100
    StringMapValue:
      type: string
      minLength: 0
      maxLength: 100
    StringValue:
      type: string
      minLength: 0
      maxLength: 100
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TargetType:
      type: string
      enum:
      - SINGLE
      - ALL
      - NONE
    TemplateId:
      type: string
      pattern: ^[-a-zA-Z0-9_.+]+[-a-zA-Z0-9_.+ ]*$
      minLength: 1
      maxLength: 100
    TemplateInputName:
      type: string
      pattern: ^[-a-zA-Z0-9_.+]+[-a-zA-Z0-9_.+ ]*$
      minLength: 1
      maxLength: 100
    TemplateName:
      type: string
      pattern: ^[-a-zA-Z0-9_.+]+[-a-zA-Z0-9_.+ ]*$
      minLength: 1
      maxLength: 100
    TemplateStatus:
      type: string
      enum:
      - CREATED
      - READY
      - PENDING_CREATION
      - CREATING
      - CREATION_FAILED
    WorkflowStepOutputName:
      type: string
      pattern: ^[-a-zA-Z0-9_.+]+[-a-zA-Z0-9_.+ ]*$
      minLength: 1
      maxLength: 100
