openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: mq
  x-aws-serviceName: mq
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-11-27'
  title: AmazonMQ
  description: |-
    Amazon MQ is a managed message broker service for Apache ActiveMQ and RabbitMQ that makes it easy to set up and operate message brokers in the cloud. A message broker allows software applications and components to communicate using various programming languages, operating systems, and formal messaging protocols.
servers:
- description: The AmazonMQ regional endpoint
  url: https://mq.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AuthenticationStrategy:
      type: string
      enum:
      - SIMPLE
      - LDAP
      description: <p>Optional. The authentication strategy used to secure the broker.
        The default is SIMPLE.</p>
    BrokerState:
      type: string
      enum:
      - CREATION_IN_PROGRESS
      - CREATION_FAILED
      - DELETION_IN_PROGRESS
      - RUNNING
      - REBOOT_IN_PROGRESS
      - CRITICAL_ACTION_REQUIRED
      - REPLICA
      description: <p>The broker's status.</p>
    BrokerStorageType:
      type: string
      enum:
      - EBS
      - EFS
      description: <p>The broker's storage type.</p> <important><p>EFS is not supported
        for RabbitMQ engine type.</p></important>
    ChangeType:
      type: string
      enum:
      - CREATE
      - UPDATE
      - DELETE
      description: <p>The type of change pending for the ActiveMQ user.</p>
    DataReplicationMode:
      type: string
      enum:
      - NONE
      - CRDR
      description: <p>Specifies whether a broker is a part of a data replication pair.</p>
    DayOfWeek:
      type: string
      enum:
      - MONDAY
      - TUESDAY
      - WEDNESDAY
      - THURSDAY
      - FRIDAY
      - SATURDAY
      - SUNDAY
    DeploymentMode:
      type: string
      enum:
      - SINGLE_INSTANCE
      - ACTIVE_STANDBY_MULTI_AZ
      - CLUSTER_MULTI_AZ
      description: <p>The broker's deployment mode.</p>
    EngineType:
      type: string
      enum:
      - ACTIVEMQ
      - RABBITMQ
      description: <p>The type of broker engine. Amazon MQ supports ActiveMQ and RabbitMQ.</p>
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    PromoteMode:
      type: string
      enum:
      - SWITCHOVER
      - FAILOVER
      description: <p>The Promote mode requested.</p>
    SanitizationWarningReason:
      type: string
      enum:
      - DISALLOWED_ELEMENT_REMOVED
      - DISALLOWED_ATTRIBUTE_REMOVED
      - INVALID_ATTRIBUTE_VALUE_REMOVED
      description: <p>The reason for which the configuration elements or attributes
        were sanitized.</p>
    __boolean:
      type: boolean
    __integer:
      type: integer
    __integerMin5Max100:
      type: integer
      minimum: 5
      maximum: 100
    __listOfActionRequired:
      type: array
      items:
        $ref: '#/components/schemas/ActionRequired'
    __listOfAvailabilityZone:
      type: array
      items:
        $ref: '#/components/schemas/AvailabilityZone'
    __listOfBrokerEngineType:
      type: array
      items:
        $ref: '#/components/schemas/BrokerEngineType'
    __listOfBrokerInstance:
      type: array
      items:
        $ref: '#/components/schemas/BrokerInstance'
    __listOfBrokerInstanceOption:
      type: array
      items:
        $ref: '#/components/schemas/BrokerInstanceOption'
    __listOfBrokerSummary:
      type: array
      items:
        $ref: '#/components/schemas/BrokerSummary'
    __listOfConfiguration:
      type: array
      items:
        $ref: '#/components/schemas/Configuration'
    __listOfConfigurationId:
      type: array
      items:
        $ref: '#/components/schemas/ConfigurationId'
    __listOfConfigurationRevision:
      type: array
      items:
        $ref: '#/components/schemas/ConfigurationRevision'
    __listOfDeploymentMode:
      type: array
      items:
        $ref: '#/components/schemas/DeploymentMode'
    __listOfEngineVersion:
      type: array
      items:
        $ref: '#/components/schemas/EngineVersion'
    __listOfSanitizationWarning:
      type: array
      items:
        $ref: '#/components/schemas/SanitizationWarning'
    __listOfUser:
      type: array
      items:
        $ref: '#/components/schemas/User'
    __listOfUserSummary:
      type: array
      items:
        $ref: '#/components/schemas/UserSummary'
    __listOf__string:
      type: array
      items:
        $ref: '#/components/schemas/__string'
    __mapOf__string:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/__string'
    __string:
      type: string
    __timestampIso8601:
      type: string
      format: date-time
