openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: neptune_graph
  x-aws-serviceName: neptunegraph
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2023-11-29'
  title: Amazon Neptune Graph
  description: |-
    Neptune Analytics is a new analytics database engine for Amazon Neptune that helps customers get to insights faster by quickly processing large amounts of graph data, invoking popular graph analytic algorithms in low-latency queries, and getting analytics results in seconds.
servers:
- description: The Amazon Neptune Graph regional endpoint
  url: https://neptune-graph.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Arn:
      type: string
      pattern: ^arn:.+$
      minLength: 1
      maxLength: 1011
    BlankNodeHandling:
      type: string
      enum:
      - convertToIri
    ConflictExceptionReason:
      type: string
      enum:
      - CONCURRENT_MODIFICATION
    DocumentValuedMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Document'
    EdgeLabels:
      type: array
      items:
        type: string
    EdgeProperties:
      type: array
      items:
        type: string
    EdgeStructures:
      type: array
      items:
        $ref: '#/components/schemas/EdgeStructure'
    ExplainMode:
      type: string
      enum:
      - STATIC
      - DETAILS
    ExportFilterLabel:
      type: string
      minLength: 1
      maxLength: 128
    ExportFilterOutputDataType:
      type: string
      pattern: ^(Any|Byte|Short|Int|Long|Float|Double|String|Bool|Boolean|Float\[\]|Double\[\])$
    ExportFilterOutputPropertyName:
      type: string
      pattern: ^[a-zA-Z0-9_]+$
      minLength: 1
      maxLength: 128
    ExportFilterPerLabelMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ExportFilterElement'
    ExportFilterPropertyMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ExportFilterPropertyAttributes'
    ExportFilterSourcePropertyName:
      type: string
      minLength: 1
      maxLength: 128
    ExportFormat:
      type: string
      enum:
      - PARQUET
      - CSV
    ExportTaskId:
      type: string
      pattern: ^t-[a-z0-9]{10}$
    ExportTaskStatus:
      type: string
      enum:
      - INITIALIZING
      - EXPORTING
      - SUCCEEDED
      - FAILED
      - CANCELLING
      - CANCELLED
      - DELETED
    ExportTaskSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/ExportTaskSummary'
    Format:
      type: string
      enum:
      - CSV
      - OPEN_CYPHER
      - PARQUET
      - NTRIPLES
    GraphId:
      type: string
      pattern: ^g-[a-z0-9]{10}$
    GraphIdentifier:
      type: string
      pattern: ^g-[a-z0-9]{10}$
    GraphName:
      type: string
      pattern: ^(?!g-)[a-z][a-z0-9]*(-[a-z0-9]+)*$
      minLength: 1
      maxLength: 63
    GraphSnapshotSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/GraphSnapshotSummary'
    GraphStatus:
      type: string
      enum:
      - CREATING
      - AVAILABLE
      - DELETING
      - RESETTING
      - UPDATING
      - SNAPSHOTTING
      - FAILED
      - IMPORTING
    GraphSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/GraphSummary'
    GraphSummaryMode:
      type: string
      enum:
      - BASIC
      - DETAILED
    ImportOptions:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/NeptuneImportOptions'
        description: |-
          Options for importing data from a Neptune database.
      description: |-
        Options for how to perform an import.
    ImportTaskStatus:
      type: string
      enum:
      - INITIALIZING
      - EXPORTING
      - ANALYZING_DATA
      - IMPORTING
      - REPROVISIONING
      - ROLLING_BACK
      - SUCCEEDED
      - FAILED
      - CANCELLING
      - CANCELLED
      - DELETED
    ImportTaskSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/ImportTaskSummary'
    KmsKeyArn:
      type: string
      pattern: ^arn:aws(|-cn|-us-gov):kms:[a-zA-Z0-9-]*:[0-9]{12}:key/[a-zA-Z0-9-]{36}$
      minLength: 1
      maxLength: 1024
    LongValuedMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Long'
    LongValuedMapList:
      type: array
      items:
        $ref: '#/components/schemas/LongValuedMap'
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    MultiValueHandlingType:
      type: string
      enum:
      - TO_LIST
      - PICK_FIRST
    NodeLabels:
      type: array
      items:
        type: string
    NodeProperties:
      type: array
      items:
        type: string
    NodeStructures:
      type: array
      items:
        $ref: '#/components/schemas/NodeStructure'
    OutgoingEdgeLabels:
      type: array
      items:
        type: string
    PaginationToken:
      type: string
      minLength: 1
      maxLength: 8192
    ParquetType:
      type: string
      enum:
      - COLUMNAR
    PlanCacheType:
      type: string
      enum:
      - ENABLED
      - DISABLED
      - AUTO
    PrivateGraphEndpointStatus:
      type: string
      enum:
      - CREATING
      - AVAILABLE
      - DELETING
      - FAILED
    PrivateGraphEndpointSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/PrivateGraphEndpointSummary'
    ProvisionedMemory:
      type: integer
      minimum: 16
      maximum: 24576
    QueryLanguage:
      type: string
      enum:
      - OPEN_CYPHER
    QueryResponseBlob:
      type: string
      format: byte
    QueryState:
      type: string
      enum:
      - RUNNING
      - WAITING
      - CANCELLING
    QueryStateInput:
      type: string
      enum:
      - ALL
      - RUNNING
      - WAITING
      - CANCELLING
    QuerySummaryList:
      type: array
      items:
        $ref: '#/components/schemas/QuerySummary'
    ReplicaCount:
      type: integer
      minimum: 0
      maximum: 2
    RoleArn:
      type: string
      pattern: ^arn:aws[^:]*:iam::\d{12}:(role|role/service-role)(/[\w+=,.@-]+)+$
    SecurityGroupId:
      type: string
      pattern: ^sg-[a-z0-9]+$
    SecurityGroupIds:
      type: array
      items:
        $ref: '#/components/schemas/SecurityGroupId'
    SnapshotId:
      type: string
      pattern: ^gs-[a-z0-9]{10}$
    SnapshotIdentifier:
      type: string
      pattern: ^gs-[a-z0-9]{10}$
    SnapshotName:
      type: string
      pattern: ^(?!gs-)[a-z][a-z0-9]*(-[a-z0-9]+)*$
      minLength: 1
      maxLength: 63
    SnapshotStatus:
      type: string
      enum:
      - CREATING
      - AVAILABLE
      - DELETING
      - FAILED
    SubnetId:
      type: string
      pattern: ^subnet-[a-z0-9]+$
    SubnetIds:
      type: array
      items:
        $ref: '#/components/schemas/SubnetId'
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TaskId:
      type: string
      pattern: ^t-[a-z0-9]{10}$
    UnprocessableExceptionReason:
      type: string
      enum:
      - QUERY_TIMEOUT
      - INTERNAL_LIMIT_EXCEEDED
      - MEMORY_LIMIT_EXCEEDED
      - STORAGE_LIMIT_EXCEEDED
      - PARTITION_FULL
    ValidationExceptionReason:
      type: string
      enum:
      - CONSTRAINT_VIOLATION
      - ILLEGAL_ARGUMENT
      - MALFORMED_QUERY
      - QUERY_CANCELLED
      - QUERY_TOO_LARGE
      - UNSUPPORTED_OPERATION
      - BAD_REQUEST
    VectorSearchDimension:
      type: integer
      minimum: 1
      maximum: 65536
    VpcEndpointId:
      type: string
      pattern: ^vpce-[0-9a-f]{17}$
    VpcId:
      type: string
      pattern: ^vpc-[a-z0-9]+$
