openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: neptunedata
  x-aws-serviceName: neptunedata
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2023-08-01'
  title: Amazon NeptuneData
  description: |-
    Neptune Data API

    The Amazon Neptune data API provides SDK support for more than 40 of Neptune's data operations, including data loading, query execution, data inquiry, and machine learning. It supports the Gremlin and openCypher query languages, and is available in all SDK languages. It automatically signs API requests and greatly simplifies integrating Neptune into your applications.
servers:
- description: The Amazon NeptuneData regional endpoint
  url: https://neptune-db.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Action:
      type: string
      enum:
      - initiateDatabaseReset
      - performDatabaseReset
    Classes:
      type: array
      items:
        type: string
    DocumentValuedMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Document'
    EdgeLabels:
      type: array
      items:
        type: string
    EdgeProperties:
      type: array
      items:
        type: string
    EdgeStructures:
      type: array
      items:
        $ref: '#/components/schemas/EdgeStructure'
    Encoding:
      type: string
      enum:
      - gzip
    Format:
      type: string
      enum:
      - csv
      - opencypher
      - ntriples
      - nquads
      - rdfxml
      - turtle
    GraphSummaryType:
      type: string
      enum:
      - basic
      - detailed
    GremlinQueries:
      type: array
      items:
        $ref: '#/components/schemas/GremlinQueryStatus'
    IteratorType:
      type: string
      enum:
      - AT_SEQUENCE_NUMBER
      - AFTER_SEQUENCE_NUMBER
      - TRIM_HORIZON
      - LATEST
    LongValuedMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Long'
    LongValuedMapList:
      type: array
      items:
        $ref: '#/components/schemas/LongValuedMap'
    MlModels:
      type: array
      items:
        $ref: '#/components/schemas/MlConfigDefinition'
    Mode:
      type: string
      enum:
      - RESUME
      - NEW
      - AUTO
    Models:
      type: array
      items:
        $ref: '#/components/schemas/MlConfigDefinition'
    NodeLabels:
      type: array
      items:
        type: string
    NodeProperties:
      type: array
      items:
        type: string
    NodeStructures:
      type: array
      items:
        $ref: '#/components/schemas/NodeStructure'
    OpenCypherExplainMode:
      type: string
      enum:
      - static
      - dynamic
      - details
    OpenCypherQueries:
      type: array
      items:
        $ref: '#/components/schemas/GremlinQueryStatus'
    OutgoingEdgeLabels:
      type: array
      items:
        type: string
    Parallelism:
      type: string
      enum:
      - LOW
      - MEDIUM
      - HIGH
      - OVERSUBSCRIBE
    PositiveInteger:
      type: integer
      minimum: 1
    Predicates:
      type: array
      items:
        type: string
    PropertygraphRecordsList:
      type: array
      items:
        $ref: '#/components/schemas/PropertygraphRecord'
    ReportAsText:
      type: string
      format: byte
    S3BucketRegion:
      type: string
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - ca-central-1
      - sa-east-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - me-south-1
      - af-south-1
      - ap-east-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-southeast-1
      - ap-southeast-2
      - ap-south-1
      - cn-north-1
      - cn-northwest-1
      - us-gov-west-1
      - us-gov-east-1
    SparqlRecordsList:
      type: array
      items:
        $ref: '#/components/schemas/SparqlRecord'
    StatisticsAutoGenerationMode:
      type: string
      enum:
      - disableAutoCompute
      - enableAutoCompute
      - refresh
    StringList:
      type: array
      items:
        type: string
    StringValuedMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    SubjectStructures:
      type: array
      items:
        $ref: '#/components/schemas/SubjectStructure'
