openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: networkmanager
  x-aws-serviceName: networkmanager
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2019-07-05'
  title: AWS Network Manager
  description: |-
    Amazon Web Services enables you to centrally manage your Amazon Web Services Cloud WAN core network and your Transit Gateway network across Amazon Web Services accounts, Regions, and on-premises locations.
servers:
- description: The AWS Network Manager regional endpoint
  url: https://networkmanager.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AWSAccountId:
      type: string
      pattern: ^[\s\S]*$
      minLength: 12
      maxLength: 12
    AccountId:
      type: string
      minLength: 0
      maxLength: 50
    AccountStatusList:
      type: array
      items:
        $ref: '#/components/schemas/AccountStatus'
    Action:
      type: string
      minLength: 0
      maxLength: 50
    AttachmentErrorCode:
      type: string
      enum:
      - VPC_NOT_FOUND
      - SUBNET_NOT_FOUND
      - SUBNET_DUPLICATED_IN_AVAILABILITY_ZONE
      - SUBNET_NO_FREE_ADDRESSES
      - SUBNET_UNSUPPORTED_AVAILABILITY_ZONE
      - SUBNET_NO_IPV6_CIDRS
      - VPN_CONNECTION_NOT_FOUND
      - MAXIMUM_NO_ENCAP_LIMIT_EXCEEDED
      - DIRECT_CONNECT_GATEWAY_NOT_FOUND
      - DIRECT_CONNECT_GATEWAY_EXISTING_ATTACHMENTS
      - DIRECT_CONNECT_GATEWAY_NO_PRIVATE_VIF
    AttachmentErrorList:
      type: array
      items:
        $ref: '#/components/schemas/AttachmentError'
    AttachmentId:
      type: string
      pattern: ^attachment-([0-9a-f]{8,17})$
      minLength: 0
      maxLength: 50
    AttachmentList:
      type: array
      items:
        $ref: '#/components/schemas/Attachment'
    AttachmentState:
      type: string
      enum:
      - REJECTED
      - PENDING_ATTACHMENT_ACCEPTANCE
      - CREATING
      - FAILED
      - AVAILABLE
      - UPDATING
      - PENDING_NETWORK_UPDATE
      - PENDING_TAG_ACCEPTANCE
      - DELETING
    AttachmentType:
      type: string
      enum:
      - CONNECT
      - SITE_TO_SITE_VPN
      - VPC
      - DIRECT_CONNECT_GATEWAY
      - TRANSIT_GATEWAY_ROUTE_TABLE
    Boolean:
      type: boolean
      default: false
    ChangeAction:
      type: string
      enum:
      - ADD
      - MODIFY
      - REMOVE
    ChangeSetState:
      type: string
      enum:
      - PENDING_GENERATION
      - FAILED_GENERATION
      - READY_TO_EXECUTE
      - EXECUTING
      - EXECUTION_SUCCEEDED
      - OUT_OF_DATE
    ChangeStatus:
      type: string
      enum:
      - NOT_STARTED
      - IN_PROGRESS
      - COMPLETE
      - FAILED
    ChangeType:
      type: string
      enum:
      - CORE_NETWORK_SEGMENT
      - NETWORK_FUNCTION_GROUP
      - CORE_NETWORK_EDGE
      - ATTACHMENT_MAPPING
      - ATTACHMENT_ROUTE_PROPAGATION
      - ATTACHMENT_ROUTE_STATIC
      - CORE_NETWORK_CONFIGURATION
      - SEGMENTS_CONFIGURATION
      - SEGMENT_ACTIONS_CONFIGURATION
      - ATTACHMENT_POLICIES_CONFIGURATION
    ClientToken:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 256
    ConnectPeerAssociationList:
      type: array
      items:
        $ref: '#/components/schemas/ConnectPeerAssociation'
    ConnectPeerAssociationState:
      type: string
      enum:
      - PENDING
      - AVAILABLE
      - DELETING
      - DELETED
    ConnectPeerBgpConfigurationList:
      type: array
      items:
        $ref: '#/components/schemas/ConnectPeerBgpConfiguration'
    ConnectPeerErrorCode:
      type: string
      enum:
      - EDGE_LOCATION_NO_FREE_IPS
      - EDGE_LOCATION_PEER_DUPLICATE
      - SUBNET_NOT_FOUND
      - IP_OUTSIDE_SUBNET_CIDR_RANGE
      - INVALID_INSIDE_CIDR_BLOCK
      - NO_ASSOCIATED_CIDR_BLOCK
    ConnectPeerErrorList:
      type: array
      items:
        $ref: '#/components/schemas/ConnectPeerError'
    ConnectPeerId:
      type: string
      pattern: ^connect-peer-([0-9a-f]{8,17})$
      minLength: 0
      maxLength: 50
    ConnectPeerIdList:
      type: array
      items:
        $ref: '#/components/schemas/ConnectPeerId'
    ConnectPeerState:
      type: string
      enum:
      - CREATING
      - FAILED
      - AVAILABLE
      - DELETING
    ConnectPeerSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/ConnectPeerSummary'
    ConnectionArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    ConnectionId:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 50
    ConnectionIdList:
      type: array
      items:
        $ref: '#/components/schemas/ConnectionId'
    ConnectionList:
      type: array
      items:
        $ref: '#/components/schemas/Connection'
    ConnectionState:
      type: string
      enum:
      - PENDING
      - AVAILABLE
      - DELETING
      - UPDATING
    ConnectionStatus:
      type: string
      enum:
      - UP
      - DOWN
    ConnectionType:
      type: string
      enum:
      - BGP
      - IPSEC
    ConstrainedString:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 256
    ConstrainedStringList:
      type: array
      items:
        $ref: '#/components/schemas/ConstrainedString'
    CoreNetworkArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    CoreNetworkChangeEventList:
      type: array
      items:
        $ref: '#/components/schemas/CoreNetworkChangeEvent'
    CoreNetworkChangeList:
      type: array
      items:
        $ref: '#/components/schemas/CoreNetworkChange'
    CoreNetworkEdgeList:
      type: array
      items:
        $ref: '#/components/schemas/CoreNetworkEdge'
    CoreNetworkId:
      type: string
      pattern: ^core-network-([0-9a-f]{8,17})$
      minLength: 0
      maxLength: 50
    CoreNetworkNetworkFunctionGroupList:
      type: array
      items:
        $ref: '#/components/schemas/CoreNetworkNetworkFunctionGroup'
    CoreNetworkPolicyAlias:
      type: string
      enum:
      - LIVE
      - LATEST
    CoreNetworkPolicyDocument:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 10000000
    CoreNetworkPolicyErrorList:
      type: array
      items:
        $ref: '#/components/schemas/CoreNetworkPolicyError'
    CoreNetworkPolicyVersionList:
      type: array
      items:
        $ref: '#/components/schemas/CoreNetworkPolicyVersion'
    CoreNetworkSegmentList:
      type: array
      items:
        $ref: '#/components/schemas/CoreNetworkSegment'
    CoreNetworkState:
      type: string
      enum:
      - CREATING
      - UPDATING
      - AVAILABLE
      - DELETING
    CoreNetworkSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/CoreNetworkSummary'
    CustomerGatewayArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    CustomerGatewayArnList:
      type: array
      items:
        $ref: '#/components/schemas/CustomerGatewayArn'
    CustomerGatewayAssociationList:
      type: array
      items:
        $ref: '#/components/schemas/CustomerGatewayAssociation'
    CustomerGatewayAssociationState:
      type: string
      enum:
      - PENDING
      - AVAILABLE
      - DELETING
      - DELETED
    DateTime:
      type: string
      format: date-time
    DeviceArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    DeviceId:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 50
    DeviceIdList:
      type: array
      items:
        $ref: '#/components/schemas/DeviceId'
    DeviceList:
      type: array
      items:
        $ref: '#/components/schemas/Device'
    DeviceState:
      type: string
      enum:
      - PENDING
      - AVAILABLE
      - DELETING
      - UPDATING
    DirectConnectGatewayArn:
      type: string
      pattern: ^arn:[^:]{1,63}:directconnect::[^:]{0,63}:dx-gateway\/[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$
      minLength: 0
      maxLength: 500
    EdgeSet:
      type: array
      items:
        $ref: '#/components/schemas/ConstrainedString'
    EdgeSetList:
      type: array
      items:
        $ref: '#/components/schemas/EdgeSet'
    ExceptionContextKey:
      type: string
    ExceptionContextMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ExceptionContextValue'
    ExceptionContextValue:
      type: string
    ExternalRegionCode:
      type: string
      pattern: ^[\s\S]*$
      minLength: 1
      maxLength: 63
    ExternalRegionCodeList:
      type: array
      items:
        $ref: '#/components/schemas/ExternalRegionCode'
    FilterMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/FilterValues'
    FilterName:
      type: string
      pattern: ^[0-9a-zA-Z\.-]*$
      minLength: 0
      maxLength: 128
    FilterValue:
      type: string
      pattern: ^[0-9a-zA-Z\*\.\\/\?-]*$
      minLength: 0
      maxLength: 255
    FilterValues:
      type: array
      items:
        $ref: '#/components/schemas/FilterValue'
    GlobalNetworkArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    GlobalNetworkId:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 50
    GlobalNetworkIdList:
      type: array
      items:
        $ref: '#/components/schemas/GlobalNetworkId'
    GlobalNetworkList:
      type: array
      items:
        $ref: '#/components/schemas/GlobalNetwork'
    GlobalNetworkState:
      type: string
      enum:
      - PENDING
      - AVAILABLE
      - DELETING
      - UPDATING
    IPAddress:
      type: string
      pattern: ^[\s\S]*$
      minLength: 1
      maxLength: 50
    Integer:
      type: integer
    LinkArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    LinkAssociationList:
      type: array
      items:
        $ref: '#/components/schemas/LinkAssociation'
    LinkAssociationState:
      type: string
      enum:
      - PENDING
      - AVAILABLE
      - DELETING
      - DELETED
    LinkId:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 50
    LinkIdList:
      type: array
      items:
        $ref: '#/components/schemas/LinkId'
    LinkList:
      type: array
      items:
        $ref: '#/components/schemas/Link'
    LinkState:
      type: string
      enum:
      - PENDING
      - AVAILABLE
      - DELETING
      - UPDATING
    Long:
      type: integer
      format: int64
    MaxResults:
      type: integer
      minimum: 1
      maximum: 500
    NetworkFunctionGroupList:
      type: array
      items:
        $ref: '#/components/schemas/NetworkFunctionGroup'
    NetworkFunctionGroupName:
      type: string
      pattern: ^[\s\S]*$
    NetworkResourceCountList:
      type: array
      items:
        $ref: '#/components/schemas/NetworkResourceCount'
    NetworkResourceList:
      type: array
      items:
        $ref: '#/components/schemas/NetworkResource'
    NetworkResourceMetadataMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ConstrainedString'
    NetworkRouteDestinationList:
      type: array
      items:
        $ref: '#/components/schemas/NetworkRouteDestination'
    NetworkRouteList:
      type: array
      items:
        $ref: '#/components/schemas/NetworkRoute'
    NetworkTelemetryList:
      type: array
      items:
        $ref: '#/components/schemas/NetworkTelemetry'
    NextToken:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 2048
    OrganizationAwsServiceAccessStatus:
      type: string
      minLength: 0
      maxLength: 50
    OrganizationId:
      type: string
      pattern: ^o-([0-9a-f]{8,17})$
      minLength: 0
      maxLength: 50
    PathComponentList:
      type: array
      items:
        $ref: '#/components/schemas/PathComponent'
    PeeringErrorCode:
      type: string
      enum:
      - TRANSIT_GATEWAY_NOT_FOUND
      - TRANSIT_GATEWAY_PEERS_LIMIT_EXCEEDED
      - MISSING_PERMISSIONS
      - INTERNAL_ERROR
      - EDGE_LOCATION_PEER_DUPLICATE
      - INVALID_TRANSIT_GATEWAY_STATE
    PeeringErrorList:
      type: array
      items:
        $ref: '#/components/schemas/PeeringError'
    PeeringId:
      type: string
      pattern: ^peering-([0-9a-f]{8,17})$
      minLength: 0
      maxLength: 50
    PeeringList:
      type: array
      items:
        $ref: '#/components/schemas/Peering'
    PeeringState:
      type: string
      enum:
      - CREATING
      - FAILED
      - AVAILABLE
      - DELETING
    PeeringType:
      type: string
      enum:
      - TRANSIT_GATEWAY
    ReasonContextKey:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 10000000
    ReasonContextMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ReasonContextValue'
    ReasonContextValue:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 10000000
    RelationshipList:
      type: array
      items:
        $ref: '#/components/schemas/Relationship'
    ResourceArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 1500
    RetryAfterSeconds:
      type: integer
    RouteAnalysisCompletionReasonCode:
      type: string
      enum:
      - TRANSIT_GATEWAY_ATTACHMENT_NOT_FOUND
      - TRANSIT_GATEWAY_ATTACHMENT_NOT_IN_TRANSIT_GATEWAY
      - CYCLIC_PATH_DETECTED
      - TRANSIT_GATEWAY_ATTACHMENT_STABLE_ROUTE_TABLE_NOT_FOUND
      - ROUTE_NOT_FOUND
      - BLACKHOLE_ROUTE_FOR_DESTINATION_FOUND
      - INACTIVE_ROUTE_FOR_DESTINATION_FOUND
      - TRANSIT_GATEWAY_ATTACHMENT_ATTACH_ARN_NO_MATCH
      - MAX_HOPS_EXCEEDED
      - POSSIBLE_MIDDLEBOX
      - NO_DESTINATION_ARN_PROVIDED
    RouteAnalysisCompletionResultCode:
      type: string
      enum:
      - CONNECTED
      - NOT_CONNECTED
    RouteAnalysisStatus:
      type: string
      enum:
      - RUNNING
      - COMPLETED
      - FAILED
    RouteState:
      type: string
      enum:
      - ACTIVE
      - BLACKHOLE
    RouteStateList:
      type: array
      items:
        $ref: '#/components/schemas/RouteState'
    RouteTableType:
      type: string
      enum:
      - TRANSIT_GATEWAY_ROUTE_TABLE
      - CORE_NETWORK_SEGMENT
      - NETWORK_FUNCTION_GROUP
    RouteType:
      type: string
      enum:
      - PROPAGATED
      - STATIC
    RouteTypeList:
      type: array
      items:
        $ref: '#/components/schemas/RouteType'
    SLRDeploymentStatus:
      type: string
      minLength: 0
      maxLength: 50
    SegmentActionServiceInsertion:
      type: string
      enum:
      - send-via
      - send-to
    SendViaMode:
      type: string
      enum:
      - dual-hop
      - single-hop
    ServerSideString:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 10000000
    ServiceInsertionActionList:
      type: array
      items:
        $ref: '#/components/schemas/ServiceInsertionAction'
    SiteArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    SiteId:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 50
    SiteIdList:
      type: array
      items:
        $ref: '#/components/schemas/SiteId'
    SiteList:
      type: array
      items:
        $ref: '#/components/schemas/Site'
    SiteState:
      type: string
      enum:
      - PENDING
      - AVAILABLE
      - DELETING
      - UPDATING
    SubnetArn:
      type: string
      pattern: ^arn:[^:]{1,63}:ec2:[^:]{0,63}:[^:]{0,63}:subnet\/subnet-[0-9a-f]{8,17}$|^$
      minLength: 0
      maxLength: 500
    SubnetArnList:
      type: array
      items:
        $ref: '#/components/schemas/SubnetArn'
    SynthesizedJsonCoreNetworkPolicyDocument:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 10000000
    SynthesizedJsonResourcePolicyDocument:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 10000000
    TagKey:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 10000000
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagList:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    TagValue:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 10000000
    TransitGatewayArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    TransitGatewayArnList:
      type: array
      items:
        $ref: '#/components/schemas/TransitGatewayArn'
    TransitGatewayAttachmentArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    TransitGatewayAttachmentId:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 50
    TransitGatewayConnectPeerArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    TransitGatewayConnectPeerArnList:
      type: array
      items:
        $ref: '#/components/schemas/TransitGatewayConnectPeerArn'
    TransitGatewayConnectPeerAssociationList:
      type: array
      items:
        $ref: '#/components/schemas/TransitGatewayConnectPeerAssociation'
    TransitGatewayConnectPeerAssociationState:
      type: string
      enum:
      - PENDING
      - AVAILABLE
      - DELETING
      - DELETED
    TransitGatewayPeeringAttachmentId:
      type: string
      pattern: ^tgw-attach-([0-9a-f]{8,17})$
      minLength: 0
      maxLength: 50
    TransitGatewayRegistrationList:
      type: array
      items:
        $ref: '#/components/schemas/TransitGatewayRegistration'
    TransitGatewayRegistrationState:
      type: string
      enum:
      - PENDING
      - AVAILABLE
      - DELETING
      - DELETED
      - FAILED
    TransitGatewayRouteTableArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    TunnelProtocol:
      type: string
      enum:
      - GRE
      - NO_ENCAP
    ValidationExceptionFieldList:
      type: array
      items:
        $ref: '#/components/schemas/ValidationExceptionField'
    ValidationExceptionReason:
      type: string
      enum:
      - UnknownOperation
      - CannotParse
      - FieldValidationFailed
      - Other
    VpcArn:
      type: string
      pattern: ^arn:[^:]{1,63}:ec2:[^:]{0,63}:[^:]{0,63}:vpc\/vpc-[0-9a-f]{8,17}$
      minLength: 0
      maxLength: 500
    VpnConnectionArn:
      type: string
      pattern: ^arn:[^:]{1,63}:ec2:[^:]{0,63}:[^:]{0,63}:vpn-connection\/vpn-[0-9a-f]{8,17}$
      minLength: 0
      maxLength: 500
    WhenSentToSegmentsList:
      type: array
      items:
        $ref: '#/components/schemas/ConstrainedString'
    WithEdgeOverridesList:
      type: array
      items:
        $ref: '#/components/schemas/EdgeOverride'
