openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: networkmanager
  x-aws-serviceName: networkmanager
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2019-07-05'
  title: AWS Network Manager
  description: |-
    Amazon Web Services enables you to centrally manage your Amazon Web Services Cloud WAN core network and your Transit Gateway network across Amazon Web Services accounts, Regions, and on-premises locations.
servers:
- description: The AWS Network Manager regional endpoint
  url: https://networkmanager.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AWSAccountId:
      type: string
      pattern: ^[\s\S]*$
      minLength: 12
      maxLength: 12
    AccountId:
      type: string
      minLength: 0
      maxLength: 50
    Action:
      type: string
      minLength: 0
      maxLength: 50
    AttachmentId:
      type: string
      pattern: ^attachment-([0-9a-f]{8,17})$
      minLength: 0
      maxLength: 50
    Boolean:
      type: boolean
      default: false
    ClientToken:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 256
    ConnectPeerId:
      type: string
      pattern: ^connect-peer-([0-9a-f]{8,17})$
      minLength: 0
      maxLength: 50
    ConnectionArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    ConnectionId:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 50
    ConstrainedString:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 256
    CoreNetworkArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    CoreNetworkId:
      type: string
      pattern: ^core-network-([0-9a-f]{8,17})$
      minLength: 0
      maxLength: 50
    CoreNetworkPolicyDocument:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 10000000
    CustomerGatewayArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    DeviceArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    DeviceId:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 50
    DirectConnectGatewayArn:
      type: string
      pattern: ^arn:[^:]{1,63}:directconnect::[^:]{0,63}:dx-gateway\/[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$
      minLength: 0
      maxLength: 500
    ExceptionContextKey:
      type: string
    ExceptionContextValue:
      type: string
    ExternalRegionCode:
      type: string
      pattern: ^[\s\S]*$
      minLength: 1
      maxLength: 63
    FilterName:
      type: string
      pattern: ^[0-9a-zA-Z\.-]*$
      minLength: 0
      maxLength: 128
    FilterValue:
      type: string
      pattern: ^[0-9a-zA-Z\*\.\\/\?-]*$
      minLength: 0
      maxLength: 255
    GlobalNetworkArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    GlobalNetworkId:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 50
    IPAddress:
      type: string
      pattern: ^[\s\S]*$
      minLength: 1
      maxLength: 50
    Integer:
      type: integer
    LinkArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    LinkId:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 50
    MaxResults:
      type: integer
      minimum: 1
      maximum: 500
    NetworkFunctionGroupName:
      type: string
      pattern: ^[\s\S]*$
    NextToken:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 2048
    OrganizationAwsServiceAccessStatus:
      type: string
      minLength: 0
      maxLength: 50
    OrganizationId:
      type: string
      pattern: ^o-([0-9a-f]{8,17})$
      minLength: 0
      maxLength: 50
    PeeringId:
      type: string
      pattern: ^peering-([0-9a-f]{8,17})$
      minLength: 0
      maxLength: 50
    ReasonContextKey:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 10000000
    ReasonContextValue:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 10000000
    ResourceArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 1500
    RetryAfterSeconds:
      type: integer
    SLRDeploymentStatus:
      type: string
      minLength: 0
      maxLength: 50
    ServerSideString:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 10000000
    SiteArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    SiteId:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 50
    SubnetArn:
      type: string
      pattern: ^arn:[^:]{1,63}:ec2:[^:]{0,63}:[^:]{0,63}:subnet\/subnet-[0-9a-f]{8,17}$|^$
      minLength: 0
      maxLength: 500
    SynthesizedJsonCoreNetworkPolicyDocument:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 10000000
    SynthesizedJsonResourcePolicyDocument:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 10000000
    TagKey:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 10000000
    TagValue:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 10000000
    TransitGatewayArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    TransitGatewayAttachmentArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    TransitGatewayAttachmentId:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 50
    TransitGatewayConnectPeerArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    TransitGatewayPeeringAttachmentId:
      type: string
      pattern: ^tgw-attach-([0-9a-f]{8,17})$
      minLength: 0
      maxLength: 50
    TransitGatewayRouteTableArn:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    VpcArn:
      type: string
      pattern: ^arn:[^:]{1,63}:ec2:[^:]{0,63}:[^:]{0,63}:vpc\/vpc-[0-9a-f]{8,17}$
      minLength: 0
      maxLength: 500
    VpnConnectionArn:
      type: string
      pattern: ^arn:[^:]{1,63}:ec2:[^:]{0,63}:[^:]{0,63}:vpn-connection\/vpn-[0-9a-f]{8,17}$
      minLength: 0
      maxLength: 500
