openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: notificationscontacts
  x-aws-serviceName: notificationscontacts
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: AWS User Notifications Contacts
  description: |-
    AWS User Notifications Contacts is a service that allows you to create and manage email contacts for AWS User Notifications. The AWS User Notifications Contacts API Reference provides descriptions, API request parameters, and the JSON response for all email contact related API actions.
servers:
- description: The AWS User Notifications Contacts regional endpoint
  url: https://notifications-contacts.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    EmailContactAddress:
      type: string
      pattern: ^(.+)@(.+)$
      minLength: 6
      maxLength: 254
    EmailContactArn:
      type: string
      pattern: ^arn:aws:notifications-contacts::[0-9]{12}:emailcontact/[a-z0-9]{27}$
    EmailContactName:
      type: string
      pattern: '[\w-.~]+'
      minLength: 1
      maxLength: 64
    EmailContactStatus:
      type: string
      enum:
      - inactive
      - active
    ErrorMessage:
      type: string
    QuotaCode:
      type: string
    ResourceId:
      type: string
    ResourceType:
      type: string
    SensitiveEmailContactAddress:
      type: string
      pattern: ^(.+)@(.+)$
      minLength: 6
      maxLength: 254
    ServiceCode:
      type: string
    TagKey:
      type: string
      pattern: ^(?!aws:).{1,128}$
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    Token:
      type: string
      pattern: ^[a-z0-9]{7}$
      minLength: 7
      maxLength: 7
