openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: oam
  x-aws-serviceName: oam
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2022-06-10'
  title: CloudWatch Observability Access Manager
  description: |-
    Use Amazon CloudWatch Observability Access Manager to create and manage links between source accounts and monitoring accounts by using _CloudWatch cross-account observability_. With CloudWatch cross-account observability, you can monitor and troubleshoot applications that span multiple accounts within a Region. Seamlessly search, visualize, and analyze your metrics, logs, traces, Application Signals services, service level objectives (SLOs), Application Insights applications, and internet monitors in any of the linked accounts without account boundaries.

    Set up one or more Amazon Web Services accounts as _monitoring accounts_ and link them with multiple _source accounts_. A monitoring account is a central Amazon Web Services account that can view and interact with observability data generated from source accounts. A source account is an individual Amazon Web Services account that generates observability data for the resources that reside in it. Source accounts share their observability data with the monitoring account. The shared observability data can include metrics in Amazon CloudWatch, logs in Amazon CloudWatch Logs, traces in X-Ray, Application Signals services, service level objectives (SLOs), applications in Amazon CloudWatch Application Insights, and internet monitors in CloudWatch Internet Monitor.

    When you set up a link, you can choose to share the metrics from all namespaces with the monitoring account, or filter to a subset of namespaces. And for CloudWatch Logs, you can choose to share all log groups with the monitoring account, or filter to a subset of log groups.
servers:
- description: The CloudWatch Observability Access Manager regional endpoint
  url: https://oam.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Arn:
      type: string
      pattern: ^arn:(\w|-)+:oam:.+:.+:.+
    LabelTemplate:
      type: string
      minLength: 1
      maxLength: 64
    ListAttachedLinksItems:
      type: array
      items:
        $ref: '#/components/schemas/ListAttachedLinksItem'
    ListAttachedLinksMaxResults:
      type: integer
      minimum: 1
      maximum: 1000
    ListLinksItems:
      type: array
      items:
        $ref: '#/components/schemas/ListLinksItem'
    ListLinksMaxResults:
      type: integer
      minimum: 1
      maximum: 5
    ListSinksItems:
      type: array
      items:
        $ref: '#/components/schemas/ListSinksItem'
    ListSinksMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    LogsFilter:
      type: string
      minLength: 1
      maxLength: 2000
    MetricsFilter:
      type: string
      minLength: 1
      maxLength: 2000
    NextToken:
      type: string
    ResourceIdentifier:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9_:\.\-\/]{0,2047}$
    ResourceType:
      type: string
      enum:
      - AWS::CloudWatch::Metric
      - AWS::Logs::LogGroup
      - AWS::XRay::Trace
      - AWS::ApplicationInsights::Application
      - AWS::InternetMonitor::Monitor
      - AWS::ApplicationSignals::Service
      - AWS::ApplicationSignals::ServiceLevelObjective
    ResourceTypesInput:
      type: array
      items:
        $ref: '#/components/schemas/ResourceType'
    ResourceTypesOutput:
      type: array
      items:
        type: string
    SinkName:
      type: string
      pattern: ^[a-zA-Z0-9_\.\-]{1,255}$
    SinkPolicy:
      type: string
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagKeys:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMapInput:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagMapOutput:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
