openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: observabilityadmin
  x-aws-serviceName: observabilityadmin
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: CloudWatch Observability Admin Service
  description: |-
    Amazon CloudWatch Obsersavability Admin to control temletry config for your AWS Organization or account. Telemetry config conﬁg to discover and understand the state of telemetry conﬁguration for your AWS resources from a central view in the CloudWatch console. Telemetry conﬁg simpliﬁes the process of auditing your telemetry collection conﬁgurations across multiple resource types across your AWS Organization or account. For more information, see [Auditing CloudWatch telemetry conﬁgurations](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/telemetry-config-cloudwatch.html) in the CloudWatch User Guide.

    For information on the permissions you need to use this API, see [Identity and access management for Amazon CloudWatch](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/auth-and-access-control-cw.html) in the CloudWatch User Guide.
servers:
- description: The CloudWatch Observability Admin Service regional endpoint
  url: https://observabilityadmin.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccountIdentifier:
      type: string
      pattern: ^[0-9]{12}$
      minLength: 12
      maxLength: 12
    AccountIdentifiers:
      type: array
      items:
        $ref: '#/components/schemas/AccountIdentifier'
    FailureReason:
      type: string
    ListResourceTelemetryForOrganizationMaxResults:
      type: integer
      minimum: 1
      maximum: 50
    ListResourceTelemetryMaxResults:
      type: integer
      minimum: 1
      maximum: 50
    NextToken:
      type: string
    ResourceIdentifier:
      type: string
    ResourceIdentifierPrefix:
      type: string
      minLength: 3
      maxLength: 768
    ResourceType:
      type: string
      enum:
      - AWS::EC2::Instance
      - AWS::EC2::VPC
      - AWS::Lambda::Function
    ResourceTypes:
      type: array
      items:
        $ref: '#/components/schemas/ResourceType'
    Status:
      type: string
      enum:
      - NOT_STARTED
      - STARTING
      - FAILED_START
      - RUNNING
      - STOPPING
      - FAILED_STOP
      - STOPPED
    TagKey:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
      minLength: 1
      maxLength: 128
    TagMapInput:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagMapOutput:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    TagValue:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
      minLength: 0
      maxLength: 256
    TelemetryConfigurationState:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TelemetryState'
    TelemetryConfigurations:
      type: array
      items:
        $ref: '#/components/schemas/TelemetryConfiguration'
    TelemetryState:
      type: string
      enum:
      - Enabled
      - Disabled
      - NotApplicable
    TelemetryType:
      type: string
      enum:
      - Logs
      - Metrics
      - Traces
