openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: opensearch
  x-aws-serviceName: opensearch
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2021-01-01'
  title: Amazon OpenSearch Service
  description: |-
    Use the Amazon OpenSearch Service configuration API to create, configure, and manage OpenSearch Service domains. The endpoint for configuration service requests is Region specific: es._region_.amazonaws.com. For example, es.us-east-1.amazonaws.com. For a current list of supported Regions and endpoints, see [Amazon Web Services service endpoints](https://docs.aws.amazon.com/general/latest/gr/rande.html#service-regions).
servers:
- description: The Amazon OpenSearch Service regional endpoint
  url: https://es.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ARN:
      type: string
      pattern: .*
      minLength: 20
      maxLength: 2048
    AWSAccount:
      type: string
      pattern: ^[0-9]+$
    AppConfigValue:
      type: string
      minLength: 1
      maxLength: 4096
    ApplicationName:
      type: string
      pattern: ^[a-z][a-z0-9\-]+$
      minLength: 3
      maxLength: 30
    AvailabilityZone:
      type: string
      minLength: 1
      maxLength: 15
    BackendRole:
      type: string
      minLength: 1
      maxLength: 256
    Boolean:
      type: boolean
    ChangeProgressStageName:
      type: string
      minLength: 1
      maxLength: 64
    ChangeProgressStageStatus:
      type: string
      minLength: 1
      maxLength: 256
    ClientToken:
      type: string
      minLength: 1
      maxLength: 64
    CloudWatchLogsLogGroupArn:
      type: string
      pattern: .*
      minLength: 20
      maxLength: 2048
    CommitMessage:
      type: string
      minLength: 0
      maxLength: 160
    ConnectionAlias:
      type: string
      pattern: ^[a-zA-Z][a-zA-Z0-9\-\_]+$
      minLength: 2
      maxLength: 100
    ConnectionId:
      type: string
      pattern: ^[a-z][a-z0-9\-]+$
      minLength: 10
      maxLength: 256
    ConnectionStatusMessage:
      type: string
    DataSourceDescription:
      type: string
      pattern: ^([a-zA-Z0-9_])*[\\a-zA-Z0-9_@#%*+=:?./!\s-]*$
      minLength: 0
      maxLength: 1000
    DataSourceName:
      type: string
      pattern: ^[a-z][a-z0-9_]+$
      minLength: 3
      maxLength: 80
    DeploymentType:
      type: string
      minLength: 2
      maxLength: 128
    DescribePackagesFilterValue:
      type: string
      pattern: ^[0-9a-zA-Z\*\.\_\\\/\?-]+$
    Description:
      type: string
    DirectQueryDataSourceDescription:
      type: string
      pattern: ^([a-zA-Z0-9_])*[\\a-zA-Z0-9_@#%*+=:?./!\s-]*$
      minLength: 0
      maxLength: 1000
    DirectQueryDataSourceName:
      type: string
      pattern: ^[a-z][a-z0-9_]+$
      minLength: 3
      maxLength: 80
    DirectQueryDataSourceRoleArn:
      type: string
      pattern: ^arn:aws[a-zA-Z-]*:iam::\d{12}:role(\/service-role)?\/[A-Za-z0-9+=,.@\-_]{1,64}$
      minLength: 32
      maxLength: 200
    DomainArn:
      type: string
      pattern: ^arn:aws[a-z\-]*:[a-z]+:[a-z0-9\-]+:[0-9]+:domain\/[a-z0-9\-]+$
      minLength: 1
      maxLength: 512
    DomainId:
      type: string
      minLength: 1
      maxLength: 64
    DomainName:
      type: string
      pattern: ^[a-z][a-z0-9\-]+$
      minLength: 3
      maxLength: 28
    DomainNameFqdn:
      type: string
      pattern: ^(((?!-)[A-Za-z0-9-]{0,62}[A-Za-z0-9])\.)+((?!-)[A-Za-z0-9-]{1,62}[A-Za-z0-9])$
      minLength: 1
      maxLength: 255
    DryRun:
      type: boolean
    Endpoint:
      type: string
      pattern: ^[A-Za-z0-9\-\.]+$
    EngineVersion:
      type: string
      pattern: ^Elasticsearch_[0-9]{1}\.[0-9]{1,2}$|^OpenSearch_[0-9]{1,2}\.[0-9]{1,2}$
    ErrorMessage:
      type: string
    ErrorType:
      type: string
    GUID:
      type: string
      pattern: ^\p{XDigit}{8}-\p{XDigit}{4}-\p{XDigit}{4}-\p{XDigit}{4}-\p{XDigit}{12}$
      minLength: 36
      maxLength: 36
    HostedZoneId:
      type: string
    Id:
      type: string
      pattern: ^[a-z0-9]{3,30}$
    IdentityCenterApplicationARN:
      type: string
      pattern: ^arn:aws[a-z\\-]*:[a-z]+:[a-z0-9\\-]*:[0-9]*:[a-z0-9\\-]+\/[a-z0-9\\-]+\/[a-z0-9\\-]+$
      minLength: 20
      maxLength: 2048
    IdentityCenterInstanceARN:
      type: string
      pattern: ^arn:aws[a-z\\-]*:[a-z]+:[a-z0-9\\-]*:[0-9]*:[a-z0-9\\-]+\/[a-z0-9\\-]+$
      minLength: 20
      maxLength: 2048
    IdentityPoolId:
      type: string
      pattern: ^[\w-]+:[0-9a-f-]+$
      minLength: 1
      maxLength: 55
    IdentityStoreId:
      type: string
      pattern: ^d-[0-9a-f]{10}$|^[0-9a-f]{8}\\b-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\\b[0-9a-f]{12}$
      minLength: 1
      maxLength: 64
    InstanceCount:
      type: integer
      minimum: 1
      description: <p>Number of instances in an OpenSearch Service cluster.</p>
    InstanceRole:
      type: string
    InstanceTypeString:
      type: string
      pattern: ^.*\..*\.search$
      minLength: 10
      maxLength: 40
    Integer:
      type: integer
      default: 0
    IntegerClass:
      type: integer
    Issue:
      type: string
    KmsKeyId:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 500
    LicenseFilepath:
      type: string
      pattern: ^(?!.*\/\.{2,})(?!.*\.\.)[a-zA-Z0-9_.-]+(?:\/[a-zA-Z0-9_.-]+)*$
      minLength: 0
      maxLength: 256
    LimitName:
      type: string
    LimitValue:
      type: string
    MaintenanceStatusMessage:
      type: string
      pattern: ^([\s\S]*)$
      minLength: 0
      maxLength: 1000
    MaxResults:
      type: integer
      default: 0
      maximum: 100
      description: "<p>An optional parameter that specifies the maximum number of\
        \ results to return for a given\n   request.</p>"
    MaximumInstanceCount:
      type: integer
      default: 0
      description: <p>Maximum number of instances that can be instantiated for a given
        instance type.</p>
    Message:
      type: string
      minLength: 0
      maxLength: 1024
    MinimumInstanceCount:
      type: integer
      default: 0
      description: <p> Minimum number of instances that can be instantiated for a
        given instance type.</p>
    NextToken:
      type: string
    NodeId:
      type: string
      minLength: 10
      maxLength: 40
    NonEmptyString:
      type: string
      pattern: ^[a-zA-Z0-9\-\_\.]+$
      minLength: 1
      maxLength: 100
    NumberOfAZs:
      type: string
      pattern: ^((\d+)|(NotAvailable))$
    NumberOfNodes:
      type: string
      pattern: ^((\d+)|(NotAvailable))$
    NumberOfShards:
      type: string
      pattern: ^((\d+)|(NotAvailable))$
    OwnerId:
      type: string
      pattern: ^[0-9]+$
      minLength: 12
      maxLength: 12
    PackageDescription:
      type: string
      minLength: 0
      maxLength: 1024
    PackageID:
      type: string
      pattern: ^([FG][0-9]+)$|^(pkg-[a-f0-9]+)$
    PackageName:
      type: string
      pattern: ^[a-z][a-z0-9\-]+$
      minLength: 3
      maxLength: 256
    PackageOwner:
      type: string
      minLength: 0
      maxLength: 1024
    PackageUser:
      type: string
      pattern: ^[0-9]{12}$|^GLOBAL$
      minLength: 6
      maxLength: 12
    PackageVersion:
      type: string
    Password:
      type: string
      pattern: .*
      minLength: 8
      maxLength: 128
    PluginClassName:
      type: string
      minLength: 0
      maxLength: 1024
    PluginDescription:
      type: string
      minLength: 0
      maxLength: 1024
    PluginName:
      type: string
      minLength: 0
      maxLength: 1024
    PluginVersion:
      type: string
      minLength: 0
      maxLength: 1024
    PolicyDocument:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 102400
    ReferencePath:
      type: string
    Region:
      type: string
      pattern: ^[a-z][a-z0-9\-]+$
      minLength: 5
      maxLength: 30
    RequestId:
      type: string
      pattern: ^([\s\S]*)$
      minLength: 1
      maxLength: 100
    ReservationToken:
      type: string
      pattern: .*
      minLength: 5
      maxLength: 64
    RoleArn:
      type: string
      pattern: ^arn:(aws|aws\-cn|aws\-us\-gov|aws\-iso|aws\-iso\-b):iam::[0-9]+:role\/
      minLength: 20
      maxLength: 2048
    RolesKey:
      type: string
      minLength: 1
      maxLength: 64
    S3BucketName:
      type: string
      minLength: 3
      maxLength: 63
    S3Key:
      type: string
      minLength: 1
      maxLength: 1024
    SAMLEntityId:
      type: string
      minLength: 8
      maxLength: 512
    SAMLMetadata:
      type: string
      minLength: 1
      maxLength: 1048576
    ScheduledAutoTuneDescription:
      type: string
    ServiceUrl:
      type: string
    StorageSubTypeName:
      type: string
    StorageTypeName:
      type: string
    String:
      type: string
    SubjectKey:
      type: string
      minLength: 1
      maxLength: 64
    TagKey:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 256
    TotalNumberOfStages:
      type: integer
      default: 0
    UIntValue:
      type: integer
      default: 0
      minimum: 0
    UpgradeName:
      type: string
    UserPoolId:
      type: string
      pattern: ^[\w-]+_[0-9a-zA-Z]+$
      minLength: 1
      maxLength: 55
    Username:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 64
    VersionString:
      type: string
      pattern: ^Elasticsearch_[0-9]{1}\.[0-9]{1,2}$|^OpenSearch_[0-9]{1,2}\.[0-9]{1,2}$
      minLength: 14
      maxLength: 18
    VolumeSize:
      type: string
    VpcEndpointId:
      type: string
      pattern: ^aos-[a-zA-Z0-9]*$
      minLength: 5
      maxLength: 256
