openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: osis
  x-aws-serviceName: osis
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2022-01-01'
  title: Amazon OpenSearch Ingestion
  description: |-
    Use the Amazon OpenSearch Ingestion API to create and manage ingestion pipelines. OpenSearch Ingestion is a fully managed data collector that delivers real-time log and trace data to OpenSearch Service domains. For more information, see [Getting data into your cluster using OpenSearch Ingestion](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/ingestion.html).
servers:
- description: The Amazon OpenSearch Ingestion regional endpoint
  url: https://osis.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    BlueprintFormat:
      type: string
      pattern: ^(YAML|JSON)$
    Boolean:
      type: boolean
    CidrBlock:
      type: string
      pattern: ^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)/(3[0-2]|[12]?[0-9])$
    ErrorMessage:
      type: string
    Integer:
      type: integer
      default: 0
    KmsKeyArn:
      type: string
      minLength: 7
      maxLength: 2048
    LogGroup:
      type: string
      pattern: ^\/aws\/vendedlogs\/[\.\-_/#A-Za-z0-9]+$
      minLength: 1
      maxLength: 512
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    NextToken:
      type: string
      pattern: ^([\s\S]*)$
      minLength: 0
      maxLength: 3000
    PipelineArn:
      type: string
      pattern: ^arn:(aws|aws\-cn|aws\-us\-gov|aws\-iso|aws\-iso\-b):osis:.+:pipeline\/.+$
      minLength: 46
      maxLength: 76
    PipelineConfigurationBody:
      type: string
      minLength: 1
      maxLength: 24000
    PipelineName:
      type: string
      pattern: ^[a-z][a-z0-9\-]+$
      minLength: 3
      maxLength: 28
    PipelineUnits:
      type: integer
      minimum: 1
    SecurityGroupId:
      type: string
      pattern: ^sg-\w{8}(\w{9})?$
      minLength: 11
      maxLength: 20
    String:
      type: string
    SubnetId:
      type: string
      pattern: ^subnet-\w{8}(\w{9})?$
      minLength: 15
      maxLength: 24
    TagKey:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 256
