openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: outposts
  x-aws-serviceName: outposts
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2019-12-03'
  title: AWS Outposts
  description: |-
    Amazon Web Services Outposts is a fully managed service that extends Amazon Web Services infrastructure, APIs, and tools to customer premises. By providing local access to Amazon Web Services managed infrastructure, Amazon Web Services Outposts enables customers to build and run applications on premises using the same programming interfaces as in Amazon Web Services Regions, while using local compute and storage resources for lower latency and local data processing needs.
servers:
- description: The AWS Outposts regional endpoint
  url: https://outposts.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AWSServiceName:
      type: string
      enum:
      - AWS
      - EC2
      - ELASTICACHE
      - ELB
      - RDS
      - ROUTE53
    AWSServiceNameList:
      type: array
      items:
        $ref: '#/components/schemas/AWSServiceName'
    AccountId:
      type: string
      pattern: ^\d{12}$
      minLength: 12
      maxLength: 12
    AccountIdList:
      type: array
      items:
        $ref: '#/components/schemas/AccountId'
    AddressLine1:
      type: string
      pattern: ^\S[\S ]*$
      minLength: 1
      maxLength: 180
    AddressLine2:
      type: string
      pattern: ^\S[\S ]*$
      minLength: 0
      maxLength: 60
    AddressLine3:
      type: string
      pattern: ^\S[\S ]*$
      minLength: 0
      maxLength: 60
    AddressType:
      type: string
      enum:
      - SHIPPING_ADDRESS
      - OPERATING_ADDRESS
    Arn:
      type: string
      pattern: ^(arn:aws([a-z-]+)?:outposts:[a-z\d-]+:\d{12}:([a-z\d-]+)/)[a-z]{2,8}-[a-f0-9]{17}$
      minLength: 0
      maxLength: 1011
    AssetId:
      type: string
      pattern: ^(\w+)$
      minLength: 1
      maxLength: 100
    AssetIdInput:
      type: string
      pattern: ^\d{10}$
      minLength: 10
      maxLength: 10
    AssetIdList:
      type: array
      items:
        $ref: '#/components/schemas/AssetId'
    AssetInstanceCapacityList:
      type: array
      items:
        $ref: '#/components/schemas/AssetInstanceTypeCapacity'
    AssetInstanceList:
      type: array
      items:
        $ref: '#/components/schemas/AssetInstance'
    AssetListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/AssetInfo'
    AssetState:
      type: string
      enum:
      - ACTIVE
      - RETIRING
      - ISOLATED
    AssetType:
      type: string
      enum:
      - COMPUTE
    AvailabilityZone:
      type: string
      pattern: ^([a-zA-Z]+-){1,3}([a-zA-Z]+)?(\d+[a-zA-Z]?)?$
      minLength: 1
      maxLength: 1000
    AvailabilityZoneId:
      type: string
      pattern: ^[a-zA-Z]+\d-[a-zA-Z]+\d$
      minLength: 1
      maxLength: 255
    AvailabilityZoneIdList:
      type: array
      items:
        $ref: '#/components/schemas/AvailabilityZoneId'
    AvailabilityZoneList:
      type: array
      items:
        $ref: '#/components/schemas/AvailabilityZone'
    BlockingInstancesList:
      type: array
      items:
        $ref: '#/components/schemas/BlockingInstance'
    CIDR:
      type: string
      pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$
      minLength: 9
      maxLength: 18
    CIDRList:
      type: array
      items:
        $ref: '#/components/schemas/CIDR'
    CapacityTaskFailureType:
      type: string
      enum:
      - UNSUPPORTED_CAPACITY_CONFIGURATION
      - UNEXPECTED_ASSET_STATE
      - BLOCKING_INSTANCES_NOT_EVACUATED
      - INTERNAL_SERVER_ERROR
      - RESOURCE_NOT_FOUND
    CapacityTaskId:
      type: string
      pattern: ^cap-[a-f0-9]{17}$
      minLength: 21
      maxLength: 21
    CapacityTaskList:
      type: array
      items:
        $ref: '#/components/schemas/CapacityTaskSummary'
    CapacityTaskStatus:
      type: string
      enum:
      - REQUESTED
      - IN_PROGRESS
      - FAILED
      - COMPLETED
      - WAITING_FOR_EVACUATION
      - CANCELLATION_IN_PROGRESS
      - CANCELLED
    CapacityTaskStatusList:
      type: array
      items:
        $ref: '#/components/schemas/CapacityTaskStatus'
    CapacityTaskStatusReason:
      type: string
      minLength: 0
      maxLength: 128
    CatalogItemClass:
      type: string
      enum:
      - RACK
      - SERVER
    CatalogItemClassList:
      type: array
      items:
        $ref: '#/components/schemas/CatalogItemClass'
    CatalogItemListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/CatalogItem'
    CatalogItemPowerKva:
      type: number
      format: float
    CatalogItemStatus:
      type: string
      enum:
      - AVAILABLE
      - DISCONTINUED
    CatalogItemWeightLbs:
      type: integer
    City:
      type: string
      pattern: ^\S[\S ]*$
      minLength: 1
      maxLength: 50
    CityList:
      type: array
      items:
        $ref: '#/components/schemas/City'
    ComputeAssetState:
      type: string
      enum:
      - ACTIVE
      - ISOLATED
      - RETIRING
    ConnectionId:
      type: string
      pattern: ^[a-zA-Z0-9+/=]{1,1024}$
      minLength: 1
      maxLength: 1024
    ContactName:
      type: string
      pattern: ^\S[\S ]*$
      minLength: 1
      maxLength: 255
    ContactPhoneNumber:
      type: string
      pattern: ^[\S ]+$
      minLength: 1
      maxLength: 20
    CountryCode:
      type: string
      pattern: ^[A-Z]{2}$
      minLength: 2
      maxLength: 2
    CountryCodeList:
      type: array
      items:
        $ref: '#/components/schemas/CountryCode'
    DeviceSerialNumber:
      type: string
      pattern: ^(\w+)$
      minLength: 1
      maxLength: 100
    DistrictOrCounty:
      type: string
      pattern: ^\S[\S ]*$
      minLength: 1
      maxLength: 60
    DryRun:
      type: boolean
      default: false
    EC2CapacityListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/EC2Capacity'
    EC2FamilyList:
      type: array
      items:
        $ref: '#/components/schemas/Family'
    ErrorMessage:
      type: string
      pattern: ^[\S \n]+$
      minLength: 1
      maxLength: 1000
    Family:
      type: string
      pattern: ^[a-z0-9]+$
      minLength: 1
      maxLength: 10
    FiberOpticCableType:
      type: string
      enum:
      - SINGLE_MODE
      - MULTI_MODE
    HostId:
      type: string
      pattern: ^[A-Za-z0-9-]*$
      minLength: 1
      maxLength: 50
    HostIdList:
      type: array
      items:
        $ref: '#/components/schemas/HostId'
    ISO8601Timestamp:
      type: string
      format: date-time
    InstanceFamilies:
      type: array
      items:
        $ref: '#/components/schemas/InstanceFamilyName'
    InstanceFamilyName:
      type: string
      pattern: ^(?:.{1,200}/)?(?:[a-z0-9-_A-Z])+$
      minLength: 1
      maxLength: 200
    InstanceId:
      type: string
      pattern: ^i-[0-9a-z]+$
      minLength: 11
      maxLength: 32
    InstanceIdList:
      type: array
      items:
        $ref: '#/components/schemas/InstanceId'
    InstanceType:
      type: string
    InstanceTypeCount:
      type: integer
      default: 0
      minimum: 0
      maximum: 9999
    InstanceTypeListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/InstanceTypeItem'
      description: <p>Information about the instance types.</p>
    InstanceTypeName:
      type: string
      pattern: ^[a-z0-9\-]+\.[a-z0-9\-]+$
      minLength: 1
      maxLength: 64
    LifeCycleStatus:
      type: string
      pattern: ^[ A-Za-z]+$
      minLength: 1
      maxLength: 20
    LifeCycleStatusList:
      type: array
      items:
        $ref: '#/components/schemas/LifeCycleStatus'
    LineItemAssetInformationList:
      type: array
      items:
        $ref: '#/components/schemas/LineItemAssetInformation'
    LineItemId:
      type: string
      pattern: ^ooi-[a-f0-9]{17}$
    LineItemListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/LineItem'
    LineItemQuantity:
      type: integer
      minimum: 1
    LineItemRequestListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/LineItemRequest'
    LineItemStatus:
      type: string
      enum:
      - PREPARING
      - BUILDING
      - SHIPPED
      - DELIVERED
      - INSTALLING
      - INSTALLED
      - ERROR
      - CANCELLED
      - REPLACED
    LineItemStatusCounts:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/LineItemQuantity'
    MacAddress:
      type: string
      pattern: ^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$
      minLength: 17
      maxLength: 17
    MacAddressList:
      type: array
      items:
        $ref: '#/components/schemas/MacAddress'
    MaxResults1000:
      type: integer
      minimum: 1
      maximum: 1000
      description: <p>The maximum page size.</p>
    MaxSize:
      type: string
    MaximumSupportedWeightLbs:
      type: string
      enum:
      - NO_LIMIT
      - MAX_1400_LBS
      - MAX_1600_LBS
      - MAX_1800_LBS
      - MAX_2000_LBS
    Municipality:
      type: string
      pattern: ^\S[\S ]*$
      minLength: 0
      maxLength: 180
    NetworkInterfaceDeviceIndex:
      type: integer
      default: 0
      minimum: 0
      maximum: 1
    OpticalStandard:
      type: string
      enum:
      - OPTIC_10GBASE_SR
      - OPTIC_10GBASE_IR
      - OPTIC_10GBASE_LR
      - OPTIC_40GBASE_SR
      - OPTIC_40GBASE_ESR
      - OPTIC_40GBASE_IR4_LR4L
      - OPTIC_40GBASE_LR4
      - OPTIC_100GBASE_SR4
      - OPTIC_100GBASE_CWDM4
      - OPTIC_100GBASE_LR4
      - OPTIC_100G_PSM4_MSA
      - OPTIC_1000BASE_LX
      - OPTIC_1000BASE_SX
    OrderId:
      type: string
      pattern: ^oo-[a-f0-9]{17}$
      minLength: 1
      maxLength: 20
    OrderStatus:
      type: string
      enum:
      - RECEIVED
      - PENDING
      - PROCESSING
      - INSTALLING
      - FULFILLED
      - CANCELLED
      - PREPARING
      - IN_PROGRESS
      - DELIVERED
      - COMPLETED
      - ERROR
    OrderSummaryListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/OrderSummary'
    OrderType:
      type: string
      enum:
      - OUTPOST
      - REPLACEMENT
    OutpostArn:
      type: string
      pattern: ^arn:aws([a-z-]+)?:outposts:[a-z\d-]+:\d{12}:outpost/op-[a-f0-9]{17}$
      minLength: 1
      maxLength: 255
    OutpostDescription:
      type: string
      pattern: ^[\S ]*$
      minLength: 0
      maxLength: 1000
    OutpostId:
      type: string
      pattern: ^(arn:aws([a-z-]+)?:outposts:[a-z\d-]+:\d{12}:outpost/)?op-[a-f0-9]{17}$
      minLength: 1
      maxLength: 180
    OutpostIdOnly:
      type: string
      pattern: ^op-[a-f0-9]{17}$
      minLength: 1
      maxLength: 20
    OutpostIdentifier:
      type: string
      pattern: ^(arn:aws([a-z-]+)?:outposts:[a-z\d-]+:\d{12}:outpost/)?op-[a-f0-9]{17}$
      minLength: 1
      maxLength: 180
    OutpostInstanceType:
      type: string
      pattern: ^[a-z0-9\-\.]+$
      minLength: 3
      maxLength: 30
    OutpostInstanceTypeList:
      type: array
      items:
        $ref: '#/components/schemas/OutpostInstanceType'
    OutpostName:
      type: string
      pattern: ^[\S ]+$
      minLength: 1
      maxLength: 255
    OwnerId:
      type: string
      pattern: ^\d{12}$
      minLength: 12
      maxLength: 12
    PaymentOption:
      type: string
      enum:
      - ALL_UPFRONT
      - NO_UPFRONT
      - PARTIAL_UPFRONT
    PaymentTerm:
      type: string
      enum:
      - THREE_YEARS
      - ONE_YEAR
      - FIVE_YEARS
    PostalCode:
      type: string
      pattern: ^[a-zA-Z0-9 -]+$
      minLength: 1
      maxLength: 20
    PowerConnector:
      type: string
      enum:
      - L6_30P
      - IEC309
      - AH530P7W
      - AH532P6W
      - CS8365C
    PowerDrawKva:
      type: string
      enum:
      - POWER_5_KVA
      - POWER_10_KVA
      - POWER_15_KVA
      - POWER_30_KVA
    PowerFeedDrop:
      type: string
      enum:
      - ABOVE_RACK
      - BELOW_RACK
    PowerPhase:
      type: string
      enum:
      - SINGLE_PHASE
      - THREE_PHASE
    Quantity:
      type: string
    RackElevation:
      type: number
      format: float
      minimum: 0
      maximum: 99
    RackId:
      type: string
      pattern: ^[\S \n]+$
      minLength: 5
      maxLength: 20
    RequestedInstancePools:
      type: array
      items:
        $ref: '#/components/schemas/InstanceTypeCapacity'
    ResourceType:
      type: string
      enum:
      - OUTPOST
      - ORDER
    ServerEndpoint:
      type: string
      pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}:[0-9]{1,5}$
      minLength: 9
      maxLength: 21
    ShipmentCarrier:
      type: string
      enum:
      - DHL
      - DBS
      - FEDEX
      - UPS
      - EXPEDITORS
    SiteArn:
      type: string
      pattern: ^arn:aws([a-z-]+)?:outposts:[a-z\d-]+:\d{12}:site/(os-[a-f0-9]{17})$
      minLength: 1
      maxLength: 255
    SiteDescription:
      type: string
      pattern: ^[\S ]+$
      minLength: 1
      maxLength: 1001
    SiteId:
      type: string
      pattern: ^(arn:aws([a-z-]+)?:outposts:[a-z\d-]+:\d{12}:site/)?(os-[a-f0-9]{17})$
      minLength: 1
      maxLength: 255
    SiteName:
      type: string
      pattern: ^[\S ]+$
      minLength: 1
      maxLength: 1000
    SiteNotes:
      type: string
      pattern: ^[\S \n]+$
      minLength: 1
      maxLength: 2000
    SkuCode:
      type: string
      pattern: ^OR-[A-Z0-9]{7}$
      minLength: 1
      maxLength: 10
    StateOrRegion:
      type: string
      pattern: ^\S[\S ]*$
      minLength: 1
      maxLength: 50
    StateOrRegionList:
      type: array
      items:
        $ref: '#/components/schemas/StateOrRegion'
    StatusList:
      type: array
      items:
        $ref: '#/components/schemas/AssetState'
    String:
      type: string
      pattern: ^[\S \n]+$
      minLength: 1
      maxLength: 1000
    SupportedHardwareType:
      type: string
      enum:
      - RACK
      - SERVER
    SupportedStorageEnum:
      type: string
      enum:
      - EBS
      - S3
    SupportedStorageList:
      type: array
      items:
        $ref: '#/components/schemas/SupportedStorageEnum'
    SupportedUplinkGbps:
      type: integer
      default: 0
    SupportedUplinkGbpsListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/SupportedUplinkGbps'
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      pattern: ^[\S \n]+$
      minLength: 0
      maxLength: 256
    TaskActionOnBlockingInstances:
      type: string
      enum:
      - WAIT_FOR_EVACUATION
      - FAIL_TASK
    Token:
      type: string
      pattern: ^(\d+)##(\S+)$
      minLength: 1
      maxLength: 2048
    TrackingId:
      type: string
      pattern: ^[a-zA-Z0-9]+$
      minLength: 6
      maxLength: 42
    UnderlayIpAddress:
      type: string
      pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}$
      minLength: 7
      maxLength: 15
    UplinkCount:
      type: string
      enum:
      - UPLINK_COUNT_1
      - UPLINK_COUNT_2
      - UPLINK_COUNT_3
      - UPLINK_COUNT_4
      - UPLINK_COUNT_5
      - UPLINK_COUNT_6
      - UPLINK_COUNT_7
      - UPLINK_COUNT_8
      - UPLINK_COUNT_12
      - UPLINK_COUNT_16
    UplinkGbps:
      type: string
      enum:
      - UPLINK_1G
      - UPLINK_10G
      - UPLINK_40G
      - UPLINK_100G
    VCPUCount:
      type: integer
    WireGuardPublicKey:
      type: string
      pattern: ^[a-zA-Z0-9/+]{43}=$
      minLength: 44
      maxLength: 44
    outpostListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/Outpost'
      description: <p>Information about the Outposts.</p>
    siteListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/Site'
      description: <p>Information about the sites.</p>
