openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: outposts
  x-aws-serviceName: outposts
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2019-12-03'
  title: AWS Outposts
  description: |-
    Amazon Web Services Outposts is a fully managed service that extends Amazon Web Services infrastructure, APIs, and tools to customer premises. By providing local access to Amazon Web Services managed infrastructure, Amazon Web Services Outposts enables customers to build and run applications on premises using the same programming interfaces as in Amazon Web Services Regions, while using local compute and storage resources for lower latency and local data processing needs.
servers:
- description: The AWS Outposts regional endpoint
  url: https://outposts.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccountId:
      type: string
      pattern: ^\d{12}$
      minLength: 12
      maxLength: 12
    AddressLine1:
      type: string
      pattern: ^\S[\S ]*$
      minLength: 1
      maxLength: 180
    AddressLine2:
      type: string
      pattern: ^\S[\S ]*$
      minLength: 0
      maxLength: 60
    AddressLine3:
      type: string
      pattern: ^\S[\S ]*$
      minLength: 0
      maxLength: 60
    Arn:
      type: string
      pattern: ^(arn:aws([a-z-]+)?:outposts:[a-z\d-]+:\d{12}:([a-z\d-]+)/)[a-z]{2,8}-[a-f0-9]{17}$
      minLength: 0
      maxLength: 1011
    AssetId:
      type: string
      pattern: ^(\w+)$
      minLength: 1
      maxLength: 100
    AssetIdInput:
      type: string
      pattern: ^\d{10}$
      minLength: 10
      maxLength: 10
    AvailabilityZone:
      type: string
      pattern: ^([a-zA-Z]+-){1,3}([a-zA-Z]+)?(\d+[a-zA-Z]?)?$
      minLength: 1
      maxLength: 1000
    AvailabilityZoneId:
      type: string
      pattern: ^[a-zA-Z]+\d-[a-zA-Z]+\d$
      minLength: 1
      maxLength: 255
    CIDR:
      type: string
      pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$
      minLength: 9
      maxLength: 18
    CapacityTaskId:
      type: string
      pattern: ^cap-[a-f0-9]{17}$
      minLength: 21
      maxLength: 21
    CapacityTaskStatusReason:
      type: string
      minLength: 0
      maxLength: 128
    CatalogItemWeightLbs:
      type: integer
    City:
      type: string
      pattern: ^\S[\S ]*$
      minLength: 1
      maxLength: 50
    ConnectionId:
      type: string
      pattern: ^[a-zA-Z0-9+/=]{1,1024}$
      minLength: 1
      maxLength: 1024
    ContactName:
      type: string
      pattern: ^\S[\S ]*$
      minLength: 1
      maxLength: 255
    ContactPhoneNumber:
      type: string
      pattern: ^[\S ]+$
      minLength: 1
      maxLength: 20
    CountryCode:
      type: string
      pattern: ^[A-Z]{2}$
      minLength: 2
      maxLength: 2
    DeviceSerialNumber:
      type: string
      pattern: ^(\w+)$
      minLength: 1
      maxLength: 100
    DistrictOrCounty:
      type: string
      pattern: ^\S[\S ]*$
      minLength: 1
      maxLength: 60
    DryRun:
      type: boolean
      default: false
    ErrorMessage:
      type: string
      pattern: ^[\S \n]+$
      minLength: 1
      maxLength: 1000
    Family:
      type: string
      pattern: ^[a-z0-9]+$
      minLength: 1
      maxLength: 10
    HostId:
      type: string
      pattern: ^[A-Za-z0-9-]*$
      minLength: 1
      maxLength: 50
    InstanceFamilyName:
      type: string
      pattern: ^(?:.{1,200}/)?(?:[a-z0-9-_A-Z])+$
      minLength: 1
      maxLength: 200
    InstanceId:
      type: string
      pattern: ^i-[0-9a-z]+$
      minLength: 11
      maxLength: 32
    InstanceType:
      type: string
    InstanceTypeCount:
      type: integer
      default: 0
      minimum: 0
      maximum: 9999
    InstanceTypeName:
      type: string
      pattern: ^[a-z0-9\-]+\.[a-z0-9\-]+$
      minLength: 1
      maxLength: 64
    LifeCycleStatus:
      type: string
      pattern: ^[ A-Za-z]+$
      minLength: 1
      maxLength: 20
    LineItemId:
      type: string
      pattern: ^ooi-[a-f0-9]{17}$
    LineItemQuantity:
      type: integer
      minimum: 1
    MacAddress:
      type: string
      pattern: ^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$
      minLength: 17
      maxLength: 17
    MaxResults1000:
      type: integer
      minimum: 1
      maximum: 1000
      description: <p>The maximum page size.</p>
    MaxSize:
      type: string
    Municipality:
      type: string
      pattern: ^\S[\S ]*$
      minLength: 0
      maxLength: 180
    NetworkInterfaceDeviceIndex:
      type: integer
      default: 0
      minimum: 0
      maximum: 1
    OrderId:
      type: string
      pattern: ^oo-[a-f0-9]{17}$
      minLength: 1
      maxLength: 20
    OutpostArn:
      type: string
      pattern: ^arn:aws([a-z-]+)?:outposts:[a-z\d-]+:\d{12}:outpost/op-[a-f0-9]{17}$
      minLength: 1
      maxLength: 255
    OutpostDescription:
      type: string
      pattern: ^[\S ]*$
      minLength: 0
      maxLength: 1000
    OutpostId:
      type: string
      pattern: ^(arn:aws([a-z-]+)?:outposts:[a-z\d-]+:\d{12}:outpost/)?op-[a-f0-9]{17}$
      minLength: 1
      maxLength: 180
    OutpostIdOnly:
      type: string
      pattern: ^op-[a-f0-9]{17}$
      minLength: 1
      maxLength: 20
    OutpostIdentifier:
      type: string
      pattern: ^(arn:aws([a-z-]+)?:outposts:[a-z\d-]+:\d{12}:outpost/)?op-[a-f0-9]{17}$
      minLength: 1
      maxLength: 180
    OutpostInstanceType:
      type: string
      pattern: ^[a-z0-9\-\.]+$
      minLength: 3
      maxLength: 30
    OutpostName:
      type: string
      pattern: ^[\S ]+$
      minLength: 1
      maxLength: 255
    OwnerId:
      type: string
      pattern: ^\d{12}$
      minLength: 12
      maxLength: 12
    PostalCode:
      type: string
      pattern: ^[a-zA-Z0-9 -]+$
      minLength: 1
      maxLength: 20
    Quantity:
      type: string
    RackId:
      type: string
      pattern: ^[\S \n]+$
      minLength: 5
      maxLength: 20
    ServerEndpoint:
      type: string
      pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}:[0-9]{1,5}$
      minLength: 9
      maxLength: 21
    SiteArn:
      type: string
      pattern: ^arn:aws([a-z-]+)?:outposts:[a-z\d-]+:\d{12}:site/(os-[a-f0-9]{17})$
      minLength: 1
      maxLength: 255
    SiteDescription:
      type: string
      pattern: ^[\S ]+$
      minLength: 1
      maxLength: 1001
    SiteId:
      type: string
      pattern: ^(arn:aws([a-z-]+)?:outposts:[a-z\d-]+:\d{12}:site/)?(os-[a-f0-9]{17})$
      minLength: 1
      maxLength: 255
    SiteName:
      type: string
      pattern: ^[\S ]+$
      minLength: 1
      maxLength: 1000
    SiteNotes:
      type: string
      pattern: ^[\S \n]+$
      minLength: 1
      maxLength: 2000
    SkuCode:
      type: string
      pattern: ^OR-[A-Z0-9]{7}$
      minLength: 1
      maxLength: 10
    StateOrRegion:
      type: string
      pattern: ^\S[\S ]*$
      minLength: 1
      maxLength: 50
    String:
      type: string
      pattern: ^[\S \n]+$
      minLength: 1
      maxLength: 1000
    SupportedUplinkGbps:
      type: integer
      default: 0
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^[\S \n]+$
      minLength: 0
      maxLength: 256
    Token:
      type: string
      pattern: ^(\d+)##(\S+)$
      minLength: 1
      maxLength: 2048
    TrackingId:
      type: string
      pattern: ^[a-zA-Z0-9]+$
      minLength: 6
      maxLength: 42
    UnderlayIpAddress:
      type: string
      pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}$
      minLength: 7
      maxLength: 15
    VCPUCount:
      type: integer
    WireGuardPublicKey:
      type: string
      pattern: ^[a-zA-Z0-9/+]{43}=$
      minLength: 44
      maxLength: 44
