openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: panorama
  x-aws-serviceName: panorama
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2019-07-24'
  title: AWS Panorama
  description: |-
    AWS Panorama

    **Overview**

    This is the _AWS Panorama API Reference_. For an introduction to the service, see [What is AWS Panorama?](https://docs.aws.amazon.com/panorama/latest/dev/panorama-welcome.html) in the _AWS Panorama Developer Guide_.
servers:
- description: The AWS Panorama regional endpoint
  url: https://panorama.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ApplicationInstanceArn:
      type: string
      minLength: 1
      maxLength: 255
    ApplicationInstanceHealthStatus:
      type: string
      enum:
      - RUNNING
      - ERROR
      - NOT_AVAILABLE
    ApplicationInstanceId:
      type: string
      pattern: ^[a-zA-Z0-9\-\_]+$
      minLength: 1
      maxLength: 255
    ApplicationInstanceName:
      type: string
      pattern: ^[a-zA-Z0-9\-\_]+$
      minLength: 1
      maxLength: 255
    ApplicationInstanceStatus:
      type: string
      enum:
      - DEPLOYMENT_PENDING
      - DEPLOYMENT_REQUESTED
      - DEPLOYMENT_IN_PROGRESS
      - DEPLOYMENT_ERROR
      - DEPLOYMENT_SUCCEEDED
      - REMOVAL_PENDING
      - REMOVAL_REQUESTED
      - REMOVAL_IN_PROGRESS
      - REMOVAL_FAILED
      - REMOVAL_SUCCEEDED
      - DEPLOYMENT_FAILED
    ApplicationInstanceStatusDescription:
      type: string
      minLength: 1
      maxLength: 255
    Boolean:
      type: boolean
      default: false
    Bucket:
      type: string
    BucketName:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 255
    ClientToken:
      type: string
      pattern: ^[a-zA-Z0-9\-\_]+$
      minLength: 1
      maxLength: 64
    ConnectionType:
      type: string
      enum:
      - STATIC_IP
      - DHCP
    CurrentSoftware:
      type: string
      minLength: 1
      maxLength: 255
    DefaultGateway:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 255
    DefaultRuntimeContextDevice:
      type: string
      pattern: ^[a-zA-Z0-9\-\_]+$
      minLength: 1
      maxLength: 255
    Description:
      type: string
      pattern: ^.*$
      minLength: 0
      maxLength: 255
    DesiredState:
      type: string
      enum:
      - RUNNING
      - STOPPED
      - REMOVED
    DeviceAggregatedStatus:
      type: string
      enum:
      - ERROR
      - AWAITING_PROVISIONING
      - PENDING
      - FAILED
      - DELETING
      - ONLINE
      - OFFLINE
      - LEASE_EXPIRED
      - UPDATE_NEEDED
      - REBOOTING
    DeviceArn:
      type: string
      minLength: 1
      maxLength: 255
    DeviceBrand:
      type: string
      enum:
      - AWS_PANORAMA
      - LENOVO
    DeviceConnectionStatus:
      type: string
      enum:
      - ONLINE
      - OFFLINE
      - AWAITING_CREDENTIALS
      - NOT_AVAILABLE
      - ERROR
    DeviceId:
      type: string
      pattern: ^[a-zA-Z0-9\-\_]+$
      minLength: 1
      maxLength: 255
    DeviceName:
      type: string
      pattern: ^[a-zA-Z0-9\-\_]+$
      minLength: 1
      maxLength: 255
    DeviceReportedStatus:
      type: string
      enum:
      - STOPPING
      - STOPPED
      - STOP_ERROR
      - REMOVAL_FAILED
      - REMOVAL_IN_PROGRESS
      - STARTING
      - RUNNING
      - INSTALL_ERROR
      - LAUNCHED
      - LAUNCH_ERROR
      - INSTALL_IN_PROGRESS
    DeviceSerialNumber:
      type: string
      pattern: ^[0-9]{1,20}$
    DeviceStatus:
      type: string
      enum:
      - AWAITING_PROVISIONING
      - PENDING
      - SUCCEEDED
      - FAILED
      - ERROR
      - DELETING
    DeviceType:
      type: string
      enum:
      - PANORAMA_APPLIANCE_DEVELOPER_KIT
      - PANORAMA_APPLIANCE
    Dns:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 255
    HwAddress:
      type: string
      minLength: 1
      maxLength: 255
    ImageVersion:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 255
    IotThingName:
      type: string
      minLength: 1
      maxLength: 255
    IpAddress:
      type: string
      pattern: ^((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d))(:(6553[0-5]|655[0-2]\d|65[0-4]\d{2}|6[0-4]\d{3}|[1-5]\d{4}|[1-9]\d{0,3}))?$
      minLength: 1
      maxLength: 255
    IpAddressOrServerName:
      type: string
      pattern: (^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$)|(^((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d))(:(6553[0-5]|655[0-2]\d|65[0-4]\d{2}|6[0-4]\d{3}|[1-5]\d{4}|[1-9]\d{0,3}))?$)
      minLength: 1
      maxLength: 255
    JobId:
      type: string
      pattern: ^[a-zA-Z0-9\-\_]+$
      minLength: 1
      maxLength: 255
    JobResourceType:
      type: string
      enum:
      - PACKAGE
    JobType:
      type: string
      enum:
      - OTA
      - REBOOT
    LatestAlternateSoftware:
      type: string
      minLength: 1
      maxLength: 255
    LatestSoftware:
      type: string
      minLength: 1
      maxLength: 255
    ListDevicesSortBy:
      type: string
      enum:
      - DEVICE_ID
      - CREATED_TIME
      - NAME
      - DEVICE_AGGREGATED_STATUS
    ManifestOverridesPayloadData:
      type: string
      pattern: ^.*$
      minLength: 0
      maxLength: 51200
    ManifestPayloadData:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 51200
    MarkLatestPatch:
      type: boolean
      default: false
    Mask:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 255
    MaxConnections:
      type: integer
      default: 0
    MaxSize25:
      type: integer
      default: 0
      minimum: 0
      maximum: 25
    NameFilter:
      type: string
    NetworkConnectionStatus:
      type: string
      enum:
      - CONNECTED
      - NOT_CONNECTED
      - CONNECTING
    NextToken:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 4096
    NodeAssetName:
      type: string
      pattern: ^[a-zA-Z0-9\-\_]+$
      minLength: 1
      maxLength: 255
    NodeCategory:
      type: string
      enum:
      - BUSINESS_LOGIC
      - ML_MODEL
      - MEDIA_SOURCE
      - MEDIA_SINK
    NodeFromTemplateJobStatus:
      type: string
      enum:
      - PENDING
      - SUCCEEDED
      - FAILED
    NodeFromTemplateJobStatusMessage:
      type: string
    NodeId:
      type: string
      pattern: ^[a-zA-Z0-9\-\_\.]+$
      minLength: 1
      maxLength: 255
    NodeInstanceId:
      type: string
      pattern: ^[a-zA-Z0-9\-\_]+$
      minLength: 1
      maxLength: 128
    NodeInstanceStatus:
      type: string
      enum:
      - RUNNING
      - ERROR
      - NOT_AVAILABLE
      - PAUSED
    NodeName:
      type: string
      pattern: ^[a-zA-Z0-9\-\_]+$
      minLength: 1
      maxLength: 128
    NodePackageArn:
      type: string
      minLength: 1
      maxLength: 255
    NodePackageId:
      type: string
      pattern: ^[a-zA-Z0-9\-\_\/]+$
      minLength: 1
      maxLength: 255
    NodePackageName:
      type: string
      pattern: ^[a-zA-Z0-9\-\_]+$
      minLength: 1
      maxLength: 128
    NodePackagePatchVersion:
      type: string
      pattern: ^[a-z0-9]+$
      minLength: 1
      maxLength: 255
    NodePackageVersion:
      type: string
      pattern: ^([0-9]+)\.([0-9]+)$
      minLength: 1
      maxLength: 255
    NodeSignalValue:
      type: string
      enum:
      - PAUSE
      - RESUME
    NtpServerName:
      type: string
      minLength: 1
      maxLength: 255
    Object:
      type: string
    ObjectKey:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 255
    PackageImportJobStatus:
      type: string
      enum:
      - PENDING
      - SUCCEEDED
      - FAILED
    PackageImportJobStatusMessage:
      type: string
    PackageImportJobType:
      type: string
      enum:
      - NODE_PACKAGE_VERSION
      - MARKETPLACE_NODE_PACKAGE_VERSION
    PackageOwnerAccount:
      type: string
      pattern: ^[0-9a-z\_]+$
      minLength: 1
      maxLength: 12
    PackageVersionStatus:
      type: string
      enum:
      - REGISTER_PENDING
      - REGISTER_COMPLETED
      - FAILED
      - DELETING
    PackageVersionStatusDescription:
      type: string
      minLength: 1
      maxLength: 255
    PortDefaultValue:
      type: string
      minLength: 1
      maxLength: 255
    PortName:
      type: string
      pattern: ^[a-zA-Z0-9\_]+$
      minLength: 1
      maxLength: 50
    PortType:
      type: string
      enum:
      - BOOLEAN
      - STRING
      - INT32
      - FLOAT32
      - MEDIA
    PrincipalArn:
      type: string
      pattern: ^arn:[a-z0-9][-.a-z0-9]{0,62}:iam::[0-9]{12}:[a-zA-Z0-9+=,.@\-_/]+$
      minLength: 1
      maxLength: 255
    Region:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 255
    ResourceArn:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 2048
    RetryAfterSeconds:
      type: integer
      default: 0
    RuntimeContextName:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 255
    RuntimeRoleArn:
      type: string
      pattern: ^arn:[a-z0-9][-.a-z0-9]{0,62}:iam::[0-9]{12}:role/.+$
      minLength: 1
      maxLength: 255
    SortOrder:
      type: string
      enum:
      - ASCENDING
      - DESCENDING
    StatusFilter:
      type: string
      enum:
      - DEPLOYMENT_SUCCEEDED
      - DEPLOYMENT_ERROR
      - REMOVAL_SUCCEEDED
      - REMOVAL_FAILED
      - PROCESSING_DEPLOYMENT
      - PROCESSING_REMOVAL
      - DEPLOYMENT_FAILED
    String:
      type: string
    TagKey:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^.*$
      minLength: 0
      maxLength: 256
    TemplateKey:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 255
    TemplateType:
      type: string
      enum:
      - RTSP_CAMERA_STREAM
    TemplateValue:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 255
    Token:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 4096
    UpdateProgress:
      type: string
      enum:
      - PENDING
      - IN_PROGRESS
      - VERIFYING
      - REBOOTING
      - DOWNLOADING
      - COMPLETED
      - FAILED
    ValidationExceptionReason:
      type: string
      enum:
      - UNKNOWN_OPERATION
      - CANNOT_PARSE
      - FIELD_VALIDATION_FAILED
      - OTHER
    Version:
      type: string
      minLength: 1
      maxLength: 255
