openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: pca_connector_ad
  x-aws-serviceName: pcaconnectorad
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: PcaConnectorAd
  description: |-
    Amazon Web Services Private CA Connector for Active Directory creates a connector between Amazon Web Services Private CA and Active Directory (AD) that enables you to provision security certificates for AD signed by a private CA that you own. For more information, see [Amazon Web Services Private CA Connector for Active Directory](https://docs.aws.amazon.com/privateca/latest/userguide/ad-connector.html).
servers:
- description: The PcaConnectorAd regional endpoint
  url: https://pca-connector-ad.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccessControlEntryList:
      type: array
      items:
        $ref: '#/components/schemas/AccessControlEntrySummary'
    AccessRight:
      type: string
      enum:
      - ALLOW
      - DENY
    ApplicationPolicy:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/ApplicationPolicyType'
        description: |-
          The type of application policy
      - allOf:
        - $ref: '#/components/schemas/CustomObjectIdentifier'
        description: |-
          The object identifier (OID) of an application policy.
      description: |-
        Application policies describe what the certificate can be used for.
    ApplicationPolicyList:
      type: array
      items:
        $ref: '#/components/schemas/ApplicationPolicy'
    ApplicationPolicyType:
      type: string
      enum:
      - ALL_APPLICATION_POLICIES
      - ANY_PURPOSE
      - ATTESTATION_IDENTITY_KEY_CERTIFICATE
      - CERTIFICATE_REQUEST_AGENT
      - CLIENT_AUTHENTICATION
      - CODE_SIGNING
      - CTL_USAGE
      - DIGITAL_RIGHTS
      - DIRECTORY_SERVICE_EMAIL_REPLICATION
      - DISALLOWED_LIST
      - DNS_SERVER_TRUST
      - DOCUMENT_ENCRYPTION
      - DOCUMENT_SIGNING
      - DYNAMIC_CODE_GENERATOR
      - EARLY_LAUNCH_ANTIMALWARE_DRIVER
      - EMBEDDED_WINDOWS_SYSTEM_COMPONENT_VERIFICATION
      - ENCLAVE
      - ENCRYPTING_FILE_SYSTEM
      - ENDORSEMENT_KEY_CERTIFICATE
      - FILE_RECOVERY
      - HAL_EXTENSION
      - IP_SECURITY_END_SYSTEM
      - IP_SECURITY_IKE_INTERMEDIATE
      - IP_SECURITY_TUNNEL_TERMINATION
      - IP_SECURITY_USER
      - ISOLATED_USER_MODE
      - KDC_AUTHENTICATION
      - KERNEL_MODE_CODE_SIGNING
      - KEY_PACK_LICENSES
      - KEY_RECOVERY
      - KEY_RECOVERY_AGENT
      - LICENSE_SERVER_VERIFICATION
      - LIFETIME_SIGNING
      - MICROSOFT_PUBLISHER
      - MICROSOFT_TIME_STAMPING
      - MICROSOFT_TRUST_LIST_SIGNING
      - OCSP_SIGNING
      - OEM_WINDOWS_SYSTEM_COMPONENT_VERIFICATION
      - PLATFORM_CERTIFICATE
      - PREVIEW_BUILD_SIGNING
      - PRIVATE_KEY_ARCHIVAL
      - PROTECTED_PROCESS_LIGHT_VERIFICATION
      - PROTECTED_PROCESS_VERIFICATION
      - QUALIFIED_SUBORDINATION
      - REVOKED_LIST_SIGNER
      - ROOT_PROGRAM_AUTO_UPDATE_CA_REVOCATION
      - ROOT_PROGRAM_AUTO_UPDATE_END_REVOCATION
      - ROOT_PROGRAM_NO_OSCP_FAILOVER_TO_CRL
      - ROOT_LIST_SIGNER
      - SECURE_EMAIL
      - SERVER_AUTHENTICATION
      - SMART_CARD_LOGIN
      - SPC_ENCRYPTED_DIGEST_RETRY_COUNT
      - SPC_RELAXED_PE_MARKER_CHECK
      - TIME_STAMPING
      - WINDOWS_HARDWARE_DRIVER_ATTESTED_VERIFICATION
      - WINDOWS_HARDWARE_DRIVER_EXTENDED_VERIFICATION
      - WINDOWS_HARDWARE_DRIVER_VERIFICATION
      - WINDOWS_HELLO_RECOVERY_KEY_ENCRYPTION
      - WINDOWS_KITS_COMPONENT
      - WINDOWS_RT_VERIFICATION
      - WINDOWS_SOFTWARE_EXTENSION_VERIFICATION
      - WINDOWS_STORE
      - WINDOWS_SYSTEM_COMPONENT_VERIFICATION
      - WINDOWS_TCB_COMPONENT
      - WINDOWS_THIRD_PARTY_APPLICATION_COMPONENT
      - WINDOWS_UPDATE
    CertificateAuthorityArn:
      type: string
      pattern: ^arn:[\w-]+:acm-pca:[\w-]+:[0-9]+:certificate-authority\/[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$
      minLength: 5
      maxLength: 200
    ClientCompatibilityV2:
      type: string
      enum:
      - WINDOWS_SERVER_2003
      - WINDOWS_SERVER_2008
      - WINDOWS_SERVER_2008_R2
      - WINDOWS_SERVER_2012
      - WINDOWS_SERVER_2012_R2
      - WINDOWS_SERVER_2016
    ClientCompatibilityV3:
      type: string
      enum:
      - WINDOWS_SERVER_2008
      - WINDOWS_SERVER_2008_R2
      - WINDOWS_SERVER_2012
      - WINDOWS_SERVER_2012_R2
      - WINDOWS_SERVER_2016
    ClientCompatibilityV4:
      type: string
      enum:
      - WINDOWS_SERVER_2012
      - WINDOWS_SERVER_2012_R2
      - WINDOWS_SERVER_2016
    ClientToken:
      type: string
      pattern: ^[!-~]+$
      minLength: 1
      maxLength: 64
    ConnectorArn:
      type: string
      pattern: ^arn:[\w-]+:pca-connector-ad:[\w-]+:[0-9]+:connector\/[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$
      minLength: 5
      maxLength: 200
    ConnectorList:
      type: array
      items:
        $ref: '#/components/schemas/ConnectorSummary'
    ConnectorStatus:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - DELETING
      - FAILED
    ConnectorStatusReason:
      type: string
      enum:
      - CA_CERTIFICATE_REGISTRATION_FAILED
      - DIRECTORY_ACCESS_DENIED
      - INTERNAL_FAILURE
      - INSUFFICIENT_FREE_ADDRESSES
      - INVALID_SUBNET_IP_PROTOCOL
      - PRIVATECA_ACCESS_DENIED
      - PRIVATECA_RESOURCE_NOT_FOUND
      - SECURITY_GROUP_NOT_IN_VPC
      - VPC_ACCESS_DENIED
      - VPC_ENDPOINT_LIMIT_EXCEEDED
      - VPC_RESOURCE_NOT_FOUND
    CryptoProvidersList:
      type: array
      items:
        type: string
    CustomObjectIdentifier:
      type: string
      pattern: ^([0-2])\.([0-9]|([0-3][0-9]))(\.([0-9]+)){0,126}$
      minLength: 1
      maxLength: 64
    DirectoryId:
      type: string
      pattern: ^d-[0-9a-f]{10}$
    DirectoryRegistrationArn:
      type: string
      pattern: ^arn:[\w-]+:pca-connector-ad:[\w-]+:[0-9]+:directory-registration\/d-[0-9a-f]{10}$
      minLength: 5
      maxLength: 200
    DirectoryRegistrationList:
      type: array
      items:
        $ref: '#/components/schemas/DirectoryRegistrationSummary'
    DirectoryRegistrationStatus:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - DELETING
      - FAILED
    DirectoryRegistrationStatusReason:
      type: string
      enum:
      - DIRECTORY_ACCESS_DENIED
      - DIRECTORY_RESOURCE_NOT_FOUND
      - DIRECTORY_NOT_ACTIVE
      - DIRECTORY_NOT_REACHABLE
      - DIRECTORY_TYPE_NOT_SUPPORTED
      - INTERNAL_FAILURE
    DisplayName:
      type: string
      pattern: ^[\x20-\x7E]+$
      minLength: 0
      maxLength: 256
    GroupSecurityIdentifier:
      type: string
      pattern: ^S-[0-9]-([0-9]+-){1,14}[0-9]+$
      minLength: 7
      maxLength: 256
    HashAlgorithm:
      type: string
      enum:
      - SHA256
      - SHA384
      - SHA512
    IpAddressType:
      type: string
      enum:
      - IPV4
      - DUALSTACK
    KeySpec:
      type: string
      enum:
      - KEY_EXCHANGE
      - SIGNATURE
    KeyUsageProperty:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/KeyUsagePropertyType'
        description: |-
          You can specify all key usages using property type ALL. You can use property type or property flags but not both.
      - allOf:
        - $ref: '#/components/schemas/KeyUsagePropertyFlags'
        description: |-
          You can specify key usage for encryption, key agreement, and signature. You can use property flags or property type but not both.
      description: |-
        The key usage property defines the purpose of the private key contained in the certificate. You can specify specific purposes using property flags or all by using property type ALL.
    KeyUsagePropertyType:
      type: string
      enum:
      - ALL
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
    NextToken:
      type: string
      pattern: ^(?:[A-Za-z0-9_-]{4})*(?:[A-Za-z0-9_-]{2}==|[A-Za-z0-9_-]{3}=)?$
      minLength: 1
      maxLength: 1000
    PrivateKeyAlgorithm:
      type: string
      enum:
      - RSA
      - ECDH_P256
      - ECDH_P384
      - ECDH_P521
    SecurityGroupId:
      type: string
      pattern: ^(?:sg-[0-9a-f]{8}|sg-[0-9a-f]{17})$
      minLength: 11
      maxLength: 20
    SecurityGroupIdList:
      type: array
      items:
        $ref: '#/components/schemas/SecurityGroupId'
    ServicePrincipalNameList:
      type: array
      items:
        $ref: '#/components/schemas/ServicePrincipalNameSummary'
    ServicePrincipalNameStatus:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - DELETING
      - FAILED
    ServicePrincipalNameStatusReason:
      type: string
      enum:
      - DIRECTORY_ACCESS_DENIED
      - DIRECTORY_NOT_REACHABLE
      - DIRECTORY_RESOURCE_NOT_FOUND
      - SPN_EXISTS_ON_DIFFERENT_AD_OBJECT
      - SPN_LIMIT_EXCEEDED
      - INTERNAL_FAILURE
    TagKeyList:
      type: array
      items:
        type: string
    Tags:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    TemplateArn:
      type: string
      pattern: ^arn:[\w-]+:pca-connector-ad:[\w-]+:[0-9]+:connector\/[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}\/template\/[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$
      minLength: 5
      maxLength: 200
    TemplateDefinition:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/TemplateV2'
        description: |-
          Template configuration to define the information included in certificates. Define certificate validity and renewal periods, certificate request handling and enrollment options, key usage extensions, application policies, and cryptography settings.
      - allOf:
        - $ref: '#/components/schemas/TemplateV3'
        description: |-
          Template configuration to define the information included in certificates. Define certificate validity and renewal periods, certificate request handling and enrollment options, key usage extensions, application policies, and cryptography settings.
      - allOf:
        - $ref: '#/components/schemas/TemplateV4'
        description: |-
          Template configuration to define the information included in certificates. Define certificate validity and renewal periods, certificate request handling and enrollment options, key usage extensions, application policies, and cryptography settings.
      description: |-
        Template configuration to define the information included in certificates. Define certificate validity and renewal periods, certificate request handling and enrollment options, key usage extensions, application policies, and cryptography settings.
    TemplateList:
      type: array
      items:
        $ref: '#/components/schemas/TemplateSummary'
    TemplateName:
      type: string
      pattern: ^(?!^\s+$)((?![\x5c'\x2b,;<=>#\x22])([\x20-\x7E]))+$
      minLength: 1
      maxLength: 64
    TemplateNameList:
      type: array
      items:
        $ref: '#/components/schemas/TemplateName'
    TemplateStatus:
      type: string
      enum:
      - ACTIVE
      - DELETING
    ValidationExceptionReason:
      type: string
      enum:
      - FIELD_VALIDATION_FAILED
      - INVALID_CA_SUBJECT
      - INVALID_PERMISSION
      - INVALID_STATE
      - MISMATCHED_CONNECTOR
      - MISMATCHED_VPC
      - NO_CLIENT_TOKEN
      - UNKNOWN_OPERATION
      - OTHER
    ValidityPeriodType:
      type: string
      enum:
      - HOURS
      - DAYS
      - WEEKS
      - MONTHS
      - YEARS
