openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: personalize_runtime
  x-aws-serviceName: personalizeruntime
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-22'
  title: Amazon Personalize Runtime
  description: ""
servers:
- description: The Amazon Personalize Runtime regional endpoint
  url: https://personalize-runtime.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ActionID:
      type: string
      minLength: 0
      maxLength: 256
    Arn:
      type: string
      pattern: ^arn:([a-z\d-]+):personalize:.*:.*:.+$
      minLength: 0
      maxLength: 256
    AttributeName:
      type: string
      pattern: ^[A-Za-z\d_]+$
      minLength: 0
      maxLength: 150
    AttributeValue:
      type: string
      minLength: 0
      maxLength: 1000
    ColumnName:
      type: string
      minLength: 0
      maxLength: 150
    ColumnValue:
      type: string
      minLength: 0
      maxLength: 20000
    DatasetType:
      type: string
      minLength: 0
      maxLength: 256
    ErrorMessage:
      type: string
    FilterAttributeName:
      type: string
      pattern: ^[A-Za-z0-9_]+$
      minLength: 0
      maxLength: 50
    FilterAttributeValue:
      type: string
      minLength: 0
      maxLength: 1000
    ItemID:
      type: string
      minLength: 0
      maxLength: 256
    Name:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9\-_]*$
      minLength: 1
      maxLength: 63
    NumResults:
      type: integer
      default: 0
      minimum: 0
    PercentPromotedItems:
      type: integer
      minimum: 1
      maximum: 100
    Reason:
      type: string
      minLength: 0
      maxLength: 256
    RecommendationID:
      type: string
    UserID:
      type: string
      minLength: 0
      maxLength: 256
