openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: pinpoint
  x-aws-serviceName: pinpoint
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2016-12-01'
  title: Amazon Pinpoint
  description: |-
    Doc Engage API - Amazon Pinpoint API
servers:
- description: The Amazon Pinpoint regional endpoint
  url: https://pinpoint.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Action:
      type: string
      enum:
      - OPEN_APP
      - DEEP_LINK
      - URL
    Alignment:
      type: string
      enum:
      - LEFT
      - CENTER
      - RIGHT
    AttributeType:
      type: string
      enum:
      - INCLUSIVE
      - EXCLUSIVE
      - CONTAINS
      - BEFORE
      - AFTER
      - 'ON'
      - BETWEEN
    ButtonAction:
      type: string
      enum:
      - LINK
      - DEEP_LINK
      - CLOSE
    CampaignStatus:
      type: string
      enum:
      - SCHEDULED
      - EXECUTING
      - PENDING_NEXT_RUN
      - COMPLETED
      - PAUSED
      - DELETED
      - INVALID
    ChannelType:
      type: string
      enum:
      - PUSH
      - GCM
      - APNS
      - APNS_SANDBOX
      - APNS_VOIP
      - APNS_VOIP_SANDBOX
      - ADM
      - SMS
      - VOICE
      - EMAIL
      - BAIDU
      - CUSTOM
      - IN_APP
    DayOfWeek:
      type: string
      enum:
      - MONDAY
      - TUESDAY
      - WEDNESDAY
      - THURSDAY
      - FRIDAY
      - SATURDAY
      - SUNDAY
    DeliveryStatus:
      type: string
      enum:
      - SUCCESSFUL
      - THROTTLED
      - TEMPORARY_FAILURE
      - PERMANENT_FAILURE
      - UNKNOWN_FAILURE
      - OPT_OUT
      - DUPLICATE
    DimensionType:
      type: string
      enum:
      - INCLUSIVE
      - EXCLUSIVE
    Duration:
      type: string
      enum:
      - HR_24
      - DAY_7
      - DAY_14
      - DAY_30
    FilterType:
      type: string
      enum:
      - SYSTEM
      - ENDPOINT
    Format:
      type: string
      enum:
      - CSV
      - JSON
    Frequency:
      type: string
      enum:
      - ONCE
      - HOURLY
      - DAILY
      - WEEKLY
      - MONTHLY
      - EVENT
      - IN_APP_EVENT
    Include:
      type: string
      enum:
      - ALL
      - ANY
      - NONE
    JobStatus:
      type: string
      enum:
      - CREATED
      - PREPARING_FOR_INITIALIZATION
      - INITIALIZING
      - PROCESSING
      - PENDING_JOB
      - COMPLETING
      - COMPLETED
      - FAILING
      - FAILED
    JourneyRunStatus:
      type: string
      enum:
      - SCHEDULED
      - RUNNING
      - COMPLETED
      - CANCELLED
    Layout:
      type: string
      enum:
      - BOTTOM_BANNER
      - TOP_BANNER
      - OVERLAYS
      - MOBILE_FEED
      - MIDDLE_BANNER
      - CAROUSEL
    ListOfActivityResponse:
      type: array
      items:
        $ref: '#/components/schemas/ActivityResponse'
    ListOfApplicationResponse:
      type: array
      items:
        $ref: '#/components/schemas/ApplicationResponse'
    ListOfCampaignResponse:
      type: array
      items:
        $ref: '#/components/schemas/CampaignResponse'
    ListOfClosedDaysRules:
      type: array
      items:
        $ref: '#/components/schemas/ClosedDaysRule'
    ListOfEndpointBatchItem:
      type: array
      items:
        $ref: '#/components/schemas/EndpointBatchItem'
    ListOfEndpointResponse:
      type: array
      items:
        $ref: '#/components/schemas/EndpointResponse'
    ListOfExportJobResponse:
      type: array
      items:
        $ref: '#/components/schemas/ExportJobResponse'
    ListOfImportJobResponse:
      type: array
      items:
        $ref: '#/components/schemas/ImportJobResponse'
    ListOfInAppMessageCampaign:
      type: array
      items:
        $ref: '#/components/schemas/InAppMessageCampaign'
    ListOfInAppMessageContent:
      type: array
      items:
        $ref: '#/components/schemas/InAppMessageContent'
    ListOfJourneyResponse:
      type: array
      items:
        $ref: '#/components/schemas/JourneyResponse'
    ListOfJourneyRunResponse:
      type: array
      items:
        $ref: '#/components/schemas/JourneyRunResponse'
    ListOfMessageHeader:
      type: array
      items:
        $ref: '#/components/schemas/MessageHeader'
    ListOfMultiConditionalBranch:
      type: array
      items:
        $ref: '#/components/schemas/MultiConditionalBranch'
    ListOfOpenHoursRules:
      type: array
      items:
        $ref: '#/components/schemas/OpenHoursRule'
    ListOfRandomSplitEntry:
      type: array
      items:
        $ref: '#/components/schemas/RandomSplitEntry'
    ListOfRecommenderConfigurationResponse:
      type: array
      items:
        $ref: '#/components/schemas/RecommenderConfigurationResponse'
    ListOfResultRow:
      type: array
      items:
        $ref: '#/components/schemas/ResultRow'
    ListOfResultRowValue:
      type: array
      items:
        $ref: '#/components/schemas/ResultRowValue'
    ListOfSegmentDimensions:
      type: array
      items:
        $ref: '#/components/schemas/SegmentDimensions'
    ListOfSegmentGroup:
      type: array
      items:
        $ref: '#/components/schemas/SegmentGroup'
    ListOfSegmentReference:
      type: array
      items:
        $ref: '#/components/schemas/SegmentReference'
    ListOfSegmentResponse:
      type: array
      items:
        $ref: '#/components/schemas/SegmentResponse'
    ListOfSimpleCondition:
      type: array
      items:
        $ref: '#/components/schemas/SimpleCondition'
    ListOfTemplateResponse:
      type: array
      items:
        $ref: '#/components/schemas/TemplateResponse'
    ListOfTemplateVersionResponse:
      type: array
      items:
        $ref: '#/components/schemas/TemplateVersionResponse'
    ListOfTreatmentResource:
      type: array
      items:
        $ref: '#/components/schemas/TreatmentResource'
    ListOfWriteTreatmentResource:
      type: array
      items:
        $ref: '#/components/schemas/WriteTreatmentResource'
    ListOf__EndpointTypesElement:
      type: array
      items:
        $ref: '#/components/schemas/__EndpointTypesElement'
    ListOf__TimezoneEstimationMethodsElement:
      type: array
      items:
        $ref: '#/components/schemas/__TimezoneEstimationMethodsElement'
    ListOf__string:
      type: array
      items:
        $ref: '#/components/schemas/__string'
    MapOfActivity:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Activity'
    MapOfAddressConfiguration:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/AddressConfiguration'
    MapOfAttributeDimension:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/AttributeDimension'
    MapOfChannelResponse:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ChannelResponse'
    MapOfEndpointMessageResult:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/EndpointMessageResult'
    MapOfEndpointSendConfiguration:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/EndpointSendConfiguration'
    MapOfEvent:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Event'
    MapOfEventItemResponse:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/EventItemResponse'
    MapOfEventsBatch:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/EventsBatch'
    MapOfItemResponse:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ItemResponse'
    MapOfListOfOpenHoursRules:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ListOfOpenHoursRules'
    MapOfListOf__string:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ListOf__string'
    MapOfMapOfEndpointMessageResult:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/MapOfEndpointMessageResult'
    MapOfMessageResult:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/MessageResult'
    MapOfMetricDimension:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/MetricDimension'
    MapOf__double:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/__double'
    MapOf__integer:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/__integer'
    MapOf__string:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/__string'
    MessageType:
      type: string
      enum:
      - TRANSACTIONAL
      - PROMOTIONAL
    Mode:
      type: string
      enum:
      - DELIVERY
      - FILTER
    Operator:
      type: string
      enum:
      - ALL
      - ANY
    RecencyType:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
    SegmentType:
      type: string
      enum:
      - DIMENSIONAL
      - IMPORT
    SourceType:
      type: string
      enum:
      - ALL
      - ANY
      - NONE
    State:
      type: string
      enum:
      - DRAFT
      - ACTIVE
      - COMPLETED
      - CANCELLED
      - CLOSED
      - PAUSED
    TemplateType:
      type: string
      enum:
      - EMAIL
      - SMS
      - VOICE
      - PUSH
      - INAPP
    Type:
      type: string
      enum:
      - ALL
      - ANY
      - NONE
    __EndpointTypesElement:
      type: string
      enum:
      - PUSH
      - GCM
      - APNS
      - APNS_SANDBOX
      - APNS_VOIP
      - APNS_VOIP_SANDBOX
      - ADM
      - SMS
      - VOICE
      - EMAIL
      - BAIDU
      - CUSTOM
      - IN_APP
    __TimezoneEstimationMethodsElement:
      type: string
      enum:
      - PHONE_NUMBER
      - POSTAL_CODE
    __blob:
      type: string
      format: byte
    __boolean:
      type: boolean
    __double:
      type: number
      format: double
    __integer:
      type: integer
    __string:
      type: string
    __timestampIso8601:
      type: string
      format: date-time
