openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: pinpoint_email
  x-aws-serviceName: pinpointemail
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-07-26'
  title: Amazon Pinpoint Email Service
  description: |-
    Amazon Pinpoint Email Service

    Welcome to the _Amazon Pinpoint Email API Reference_. This guide provides information about the Amazon Pinpoint Email API (version 1.0), including supported operations, data types, parameters, and schemas.

    [Amazon Pinpoint](https://aws.amazon.com/pinpoint) is an AWS service that you can use to engage with your customers across multiple messaging channels. You can use Amazon Pinpoint to send email, SMS text messages, voice messages, and push notifications. The Amazon Pinpoint Email API provides programmatic access to options that are unique to the email channel and supplement the options provided by the Amazon Pinpoint API.

    If you're new to Amazon Pinpoint, you might find it helpful to also review the [Amazon Pinpoint Developer Guide](https://docs.aws.amazon.com/pinpoint/latest/developerguide/welcome.html). The _Amazon Pinpoint Developer Guide_ provides tutorials, code samples, and procedures that demonstrate how to use Amazon Pinpoint features programmatically and how to integrate Amazon Pinpoint functionality into mobile apps and other types of applications. The guide also provides information about key topics such as Amazon Pinpoint integration with other AWS services and the limits that apply to using the service.

    The Amazon Pinpoint Email API is available in several AWS Regions and it provides an endpoint for each of these Regions. For a list of all the Regions and endpoints where the API is currently available, see [AWS Service Endpoints](https://docs.aws.amazon.com/general/latest/gr/rande.html#pinpoint_region) in the _Amazon Web Services General Reference_. To learn more about AWS Regions, see [Managing AWS Regions](https://docs.aws.amazon.com/general/latest/gr/rande-manage.html) in the _Amazon Web Services General Reference_.

    In each Region, AWS maintains multiple Availability Zones. These Availability Zones are physically isolated from each other, but are united by private, low-latency, high-throughput, and highly redundant network connections. These Availability Zones enable us to provide very high levels of availability and redundancy, while also minimizing latency. To learn more about the number of Availability Zones that are available in each Region, see [AWS Global Infrastructure](http://aws.amazon.com/about-aws/global-infrastructure/).
servers:
- description: The Amazon Pinpoint Email Service regional endpoint
  url: https://email.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AmazonResourceName:
      type: string
    BlacklistItemName:
      type: string
    BlacklistingDescription:
      type: string
    CampaignId:
      type: string
    Charset:
      type: string
    ConfigurationSetName:
      type: string
    CustomRedirectDomain:
      type: string
    DefaultDimensionValue:
      type: string
    DeliverabilityTestSubject:
      type: string
    DimensionName:
      type: string
    DnsToken:
      type: string
    Domain:
      type: string
    EmailAddress:
      type: string
    Enabled:
      type: boolean
      default: false
    ErrorMessage:
      type: string
    Esp:
      type: string
    EventDestinationName:
      type: string
    GeneralEnforcementStatus:
      type: string
    Identity:
      type: string
    ImageUrl:
      type: string
    Ip:
      type: string
    IspName:
      type: string
    MailFromDomainName:
      type: string
    MaxItems:
      type: integer
    MessageContent:
      type: string
    MessageData:
      type: string
    MessageTagName:
      type: string
    MessageTagValue:
      type: string
    NextToken:
      type: string
    OutboundMessageId:
      type: string
    Percentage100Wrapper:
      type: integer
    PoolName:
      type: string
    RblName:
      type: string
    ReportId:
      type: string
    ReportName:
      type: string
    SendingPoolName:
      type: string
    Subject:
      type: string
    TagKey:
      type: string
    TagValue:
      type: string
    TemplateArn:
      type: string
    TemplateData:
      type: string
      minLength: 0
      maxLength: 262144
