openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: pinpoint_sms_voice
  x-aws-serviceName: pinpointsmsvoice
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-09-05'
  title: Amazon Pinpoint SMS and Voice Service
  description: |-
    Pinpoint SMS and Voice Messaging public facing APIs
servers:
- description: The Amazon Pinpoint SMS and Voice Service regional endpoint
  url: https://sms-voice.pinpoint.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Boolean:
      type: boolean
    ConfigurationSets:
      type: array
      items:
        $ref: '#/components/schemas/WordCharactersWithDelimiters'
      description: An array that contains all of the configuration sets in your Amazon
        Pinpoint account in the current AWS Region.
    EventDestinations:
      type: array
      items:
        $ref: '#/components/schemas/EventDestination'
      description: An array of EventDestination objects. Each EventDestination object
        includes ARNs and other information that define an event destination.
    EventType:
      type: string
      enum:
      - INITIATED_CALL
      - RINGING
      - ANSWERED
      - COMPLETED_CALL
      - BUSY
      - FAILED
      - NO_ANSWER
      description: The types of events that are sent to the event destination.
    EventTypes:
      type: array
      items:
        $ref: '#/components/schemas/EventType'
      description: An array of EventDestination objects. Each EventDestination object
        includes ARNs and other information that define an event destination.
    NextTokenString:
      type: string
    NonEmptyString:
      type: string
    String:
      type: string
    WordCharactersWithDelimiters:
      type: string
    __string:
      type: string
