openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: polly
  x-aws-serviceName: polly
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2016-06-10'
  title: Amazon Polly
  description: |-
    Amazon Polly is a web service that makes it easy to synthesize speech from text.

    The Amazon Polly service provides API operations for synthesizing high-quality speech from plain text and Speech Synthesis Markup Language (SSML), along with managing pronunciations lexicons that enable you to get the best results for your application domain.
servers:
- description: The Amazon Polly regional endpoint
  url: https://polly.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Alphabet:
      type: string
    ContentType:
      type: string
    ErrorMessage:
      type: string
    IncludeAdditionalLanguageCodes:
      type: boolean
      default: false
    LanguageName:
      type: string
    LexemesCount:
      type: integer
      default: 0
    LexiconArn:
      type: string
    LexiconContent:
      type: string
    LexiconName:
      type: string
      pattern: ^[0-9A-Za-z]{1,20}$
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    NextToken:
      type: string
      minLength: 0
      maxLength: 4096
    OutputS3BucketName:
      type: string
      pattern: ^[a-z0-9][\.\-a-z0-9]{1,61}[a-z0-9]$
    OutputS3KeyPrefix:
      type: string
      pattern: ^[0-9a-zA-Z\/\!\-_\.\*\'\(\):;\$@=+\,\?&]{0,800}$
    OutputUri:
      type: string
    RequestCharacters:
      type: integer
      default: 0
    SampleRate:
      type: string
    Size:
      type: integer
      default: 0
    SnsTopicArn:
      type: string
      pattern: ^arn:aws(-(cn|iso(-b)?|us-gov))?:sns:[a-z0-9_-]{1,50}:\d{12}:[a-zA-Z0-9_-]{1,251}([a-zA-Z0-9_-]{0,5}|\.fifo)$
    TaskId:
      type: string
      pattern: ^[a-zA-Z0-9_-]{1,100}$
    TaskStatusReason:
      type: string
    Text:
      type: string
    VoiceName:
      type: string
