openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: qbusiness
  x-aws-serviceName: qbusiness
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2023-11-27'
  title: QBusiness
  description: |-
    This is the _Amazon Q Business_ API Reference. Amazon Q Business is a fully managed, generative-AI powered enterprise chat assistant that you can deploy within your organization. Amazon Q Business enhances employee productivity by supporting key tasks such as question-answering, knowledge discovery, writing email messages, summarizing text, drafting document outlines, and brainstorming ideas. Users ask questions of Amazon Q Business and get answers that are presented in a conversational manner. For an introduction to the service, see the [ _Amazon Q Business User Guide_ ](https://docs.aws.amazon.com/amazonq/latest/business-use-dg/what-is.html).

    For an overview of the Amazon Q Business APIs, see [Overview of Amazon Q Business API operations](https://docs.aws.amazon.com/amazonq/latest/business-use-dg/api-ref.html#api-overview).

    For information about the IAM access control permissions you need to use this API, see [IAM roles for Amazon Q Business](https://docs.aws.amazon.com/amazonq/latest/business-use-dg/iam-roles.html) in the _Amazon Q Business User Guide_.

    The following resources provide additional information about using the Amazon Q Business API:

      * _[Setting up for Amazon Q Business](https://docs.aws.amazon.com/amazonq/latest/business-use-dg/setting-up.html) _

      * _[Amazon Q Business CLI Reference](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/qbusiness/index.html) _

      * _[Amazon Web Services General Reference](https://docs.aws.amazon.com/general/latest/gr/amazonq.html) _
servers:
- description: The QBusiness regional endpoint
  url: https://qbusiness.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ActionPayloadFieldKey:
      type: string
      minLength: 1
    ActionPayloadFieldNameSeparator:
      type: string
      minLength: 1
      maxLength: 1
    AmazonResourceName:
      type: string
      minLength: 1
      maxLength: 1011
    ApplicationArn:
      type: string
      pattern: ^arn:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[^/].{0,1023}$
      minLength: 0
      maxLength: 1284
    ApplicationId:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]{35}$
      minLength: 36
      maxLength: 36
    ApplicationName:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9_-]*$
      minLength: 1
      maxLength: 1000
    AttachmentId:
      type: string
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
    AttachmentName:
      type: string
      pattern: ^\P{C}*$
      minLength: 1
      maxLength: 1000
    AuthResponseKey:
      type: string
      minLength: 1
      maxLength: 100
    AuthResponseValue:
      type: string
      minLength: 1
      maxLength: 2048
    BlockedPhrase:
      type: string
      pattern: ^\P{C}*$
      maxLength: 36
    BrowserExtension:
      type: string
      enum:
      - FIREFOX
      - CHROME
    ClientIdForOIDC:
      type: string
      pattern: ^[a-zA-Z0-9_.:/()*?=-]*$
      minLength: 1
      maxLength: 255
    ClientNamespace:
      type: string
      pattern: ^[a-zA-Z0-9._-]*$
      minLength: 1
      maxLength: 64
    ClientToken:
      type: string
      minLength: 1
      maxLength: 100
    ConversationId:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]{35}$
      minLength: 36
      maxLength: 36
    ConversationTitle:
      type: string
    CustomCSSUrl:
      type: string
      pattern: ^(https?://[a-zA-Z0-9-_.+%/]+\.css)?$
      minLength: 0
      maxLength: 1284
    DataAccessorArn:
      type: string
      pattern: ^arn:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[^/].{0,1023}$
      minLength: 0
      maxLength: 1284
    DataAccessorId:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]{35}$
      minLength: 36
      maxLength: 36
    DataAccessorName:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9_-]*$
      minLength: 1
      maxLength: 100
    DataSourceArn:
      type: string
      pattern: ^arn:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[^/].{0,1023}$
      minLength: 0
      maxLength: 1284
    DataSourceId:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]{35}$
      minLength: 36
      maxLength: 36
    DataSourceName:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9_-]*$
      minLength: 1
      maxLength: 1000
    DataSourceUserId:
      type: string
      pattern: ^\P{C}*$
      minLength: 1
      maxLength: 1024
    Description:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 1000
    DocumentAttributeKey:
      type: string
      pattern: ^[a-zA-Z0-9_][a-zA-Z0-9_-]*$
      minLength: 1
      maxLength: 200
    DocumentAttributeStringValue:
      type: string
      maxLength: 2048
    DocumentId:
      type: string
      pattern: ^\P{C}*$
      minLength: 1
      maxLength: 1825
    DocumentMetadataConfigurationName:
      type: string
      pattern: ^[a-zA-Z0-9_][a-zA-Z0-9_-]*$
      minLength: 1
      maxLength: 30
    ErrorMessage:
      type: string
      pattern: ^[\s\S]*$
      minLength: 1
      maxLength: 2048
    ExampleChatMessage:
      type: string
      pattern: ^\P{C}*$
      maxLength: 350
    ExecutionId:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]{35}$
      minLength: 36
      maxLength: 36
    FaviconUrl:
      type: string
      pattern: ^(https?://[a-zA-Z0-9-_.+%/]+\.(svg|ico))?$
      minLength: 0
      maxLength: 1284
    FontUrl:
      type: string
      pattern: ^(https?://[a-zA-Z0-9-_.+%/]+\.(ttf|woff|woff2|otf))?$
      minLength: 0
      maxLength: 1284
    GroupIdentifier:
      type: string
      pattern: ^([0-9a-f]{10}-|)[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}$
      minLength: 1
      maxLength: 47
    GroupName:
      type: string
      pattern: ^\P{C}*$
      minLength: 1
      maxLength: 1024
    IAMIdentityProviderArn:
      type: string
      pattern: ^arn:aws:iam::\d{12}:(oidc-provider|saml-provider)/[a-zA-Z0-9_\.\/@\-]+$
      minLength: 20
      maxLength: 2048
    IdcApplicationArn:
      type: string
      pattern: ^arn:(aws|aws-us-gov|aws-cn|aws-iso|aws-iso-b):sso::\d{12}:application/(sso)?ins-[a-zA-Z0-9-.]{16}/apl-[a-zA-Z0-9]{16}$
      minLength: 10
      maxLength: 1224
    IndexArn:
      type: string
      pattern: ^arn:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[^/].{0,1023}$
      minLength: 0
      maxLength: 1284
    IndexCapacityInteger:
      type: integer
      minimum: 1
    IndexId:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]{35}$
      minLength: 36
      maxLength: 36
    IndexName:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9_-]*$
      minLength: 1
      maxLength: 1000
    IndexedTextDocument:
      type: integer
      minimum: 0
    InstanceArn:
      type: string
      pattern: ^arn:(aws|aws-us-gov|aws-cn|aws-iso|aws-iso-b):sso:::instance/(sso)?ins-[a-zA-Z0-9-.]{16}$
      minLength: 10
      maxLength: 1224
    Integer:
      type: integer
    IntegrationId:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
      minLength: 36
      maxLength: 36
    KendraIndexId:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]{35}$
      minLength: 36
      maxLength: 36
    KmsKeyId:
      type: string
      minLength: 1
      maxLength: 2048
    LambdaArn:
      type: string
      pattern: ^arn:aws[a-zA-Z-]*:lambda:[a-z-]*-[0-9]:[0-9]{12}:function:[a-zA-Z0-9-_]+(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})?(:[a-zA-Z0-9-_]+)?$
      minLength: 1
      maxLength: 2048
    LogoUrl:
      type: string
      pattern: ^(https?://[a-zA-Z0-9-_.+%/]+\.(svg|png))?$
      minLength: 0
      maxLength: 1284
    MaxResults:
      type: integer
    MaxResultsIntegerForGetTopicConfigurations:
      type: integer
      minimum: 1
      maximum: 50
    MaxResultsIntegerForListApplications:
      type: integer
      minimum: 1
      maximum: 100
    MaxResultsIntegerForListAttachments:
      type: integer
      minimum: 1
      maximum: 100
    MaxResultsIntegerForListConversations:
      type: integer
      minimum: 1
      maximum: 100
    MaxResultsIntegerForListDataAccessors:
      type: integer
      minimum: 1
      maximum: 10
    MaxResultsIntegerForListDataSources:
      type: integer
      minimum: 1
      maximum: 10
    MaxResultsIntegerForListDataSourcesSyncJobs:
      type: integer
      minimum: 1
      maximum: 10
    MaxResultsIntegerForListDocuments:
      type: integer
      minimum: 1
      maximum: 100
    MaxResultsIntegerForListGroupsRequest:
      type: integer
      minimum: 1
      maximum: 10
    MaxResultsIntegerForListIndices:
      type: integer
      minimum: 1
      maximum: 100
    MaxResultsIntegerForListMessages:
      type: integer
      minimum: 1
      maximum: 100
    MaxResultsIntegerForListPluginActions:
      type: integer
      minimum: 1
      maximum: 50
    MaxResultsIntegerForListPluginTypeActions:
      type: integer
      minimum: 1
      maximum: 50
    MaxResultsIntegerForListPluginTypeMetadata:
      type: integer
      minimum: 1
      maximum: 50
    MaxResultsIntegerForListPlugins:
      type: integer
      minimum: 1
      maximum: 50
    MaxResultsIntegerForListRetrieversRequest:
      type: integer
      minimum: 1
      maximum: 50
    MaxResultsIntegerForListSubscriptions:
      type: integer
      minimum: 1
      maximum: 100
    MaxResultsIntegerForListWebExperiencesRequest:
      type: integer
      minimum: 1
      maximum: 100
    MediaId:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]{35}$
      minLength: 36
      maxLength: 36
    MessageBody:
      type: string
      pattern: ^\P{C}*$}$
      minLength: 0
      maxLength: 1000
    MessageId:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]{35}$
      minLength: 36
      maxLength: 36
    MessageUsefulnessComment:
      type: string
      pattern: ^\P{C}*$
      minLength: 0
      maxLength: 1000
    MetricValue:
      type: string
      pattern: ^(([1-9][0-9]*)|0)$
    NextToken:
      type: string
      minLength: 1
      maxLength: 800
    NextToken1500:
      type: string
      minLength: 1
      maxLength: 1500
    Origin:
      type: string
      pattern: ^(http://|https://)[a-zA-Z0-9-_.]+(?::[0-9]{1,5})?$
      minLength: 1
      maxLength: 256
    Payload:
      type: string
    PluginArn:
      type: string
      pattern: ^arn:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[^/].{0,1023}$
      minLength: 0
      maxLength: 1284
    PluginDescription:
      type: string
      minLength: 1
      maxLength: 200
    PluginId:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 36
      maxLength: 36
    PluginName:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9_-]*$
      minLength: 1
      maxLength: 100
    PrincipalRoleArn:
      type: string
      pattern: ^arn:aws:iam::[0-9]{12}:role/[a-zA-Z0-9_/+=,.@-]+$
      minLength: 1
      maxLength: 1284
    QIamAction:
      type: string
      pattern: ^qbusiness:[a-zA-Z]+$
    QueryText:
      type: string
    RetrieverArn:
      type: string
      pattern: ^arn:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[^/].{0,1023}$
      minLength: 0
      maxLength: 1284
    RetrieverId:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]{35}$
      minLength: 36
      maxLength: 36
    RetrieverName:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9_-]*$
      minLength: 1
      maxLength: 1000
    RoleArn:
      type: string
      pattern: ^arn:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[^/].{0,1023}$
      minLength: 0
      maxLength: 1284
    S3BucketName:
      type: string
      pattern: ^[a-z0-9][\.\-a-z0-9]{1,61}[a-z0-9]$
      minLength: 1
      maxLength: 63
    S3ObjectKey:
      type: string
      minLength: 1
      maxLength: 1024
    SamlAttribute:
      type: string
      minLength: 1
      maxLength: 256
    SamlAuthenticationUrl:
      type: string
      pattern: ^https://.*$
      minLength: 1
      maxLength: 1284
    SamlMetadataXML:
      type: string
      pattern: ^.*$
      minLength: 1000
      maxLength: 10000000
    SecretArn:
      type: string
      pattern: ^arn:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[^/].{0,1023}$
      minLength: 0
      maxLength: 1284
    SecurityGroupId:
      type: string
      pattern: ^[-0-9a-zA-Z]+$
      minLength: 1
      maxLength: 200
    SessionDurationInMinutes:
      type: integer
      minimum: 15
      maximum: 60
    SnippetExcerptText:
      type: string
    SourceAttributionMediaId:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]{35}$
      minLength: 36
      maxLength: 36
    StatementId:
      type: string
      pattern: ^[a-zA-Z0-9_-]+$
      minLength: 1
      maxLength: 100
    String:
      type: string
      minLength: 1
      maxLength: 2048
    SubnetId:
      type: string
      pattern: ^[-0-9a-zA-Z]+$
      minLength: 1
      maxLength: 200
    SubscriptionArn:
      type: string
      pattern: ^arn:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[^/].{0,1023}$
      minLength: 10
      maxLength: 1224
    SubscriptionId:
      type: string
      minLength: 0
      maxLength: 1224
    SyncSchedule:
      type: string
      pattern: ^[\s\S]*$
      maxLength: 998
    SystemMessageId:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]{35}$
      minLength: 36
      maxLength: 36
    SystemMessageOverride:
      type: string
      pattern: ^\P{C}*$
      maxLength: 350
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    Title:
      type: string
      minLength: 1
      maxLength: 1024
    TopicConfigurationName:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]{0,35}$
      minLength: 1
      maxLength: 36
    TopicDescription:
      type: string
      pattern: ^\P{C}*$
      minLength: 0
      maxLength: 350
    Url:
      type: string
      pattern: ^(https?|ftp|file)://([^\s]*)$
      minLength: 1
      maxLength: 2048
    UserId:
      type: string
      pattern: ^\P{C}*$
      minLength: 1
      maxLength: 1024
    UserIdentifier:
      type: string
      pattern: ^([0-9a-f]{10}-|)[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}$
      minLength: 1
      maxLength: 47
    UserMessage:
      type: string
    WebExperienceArn:
      type: string
      pattern: ^arn:[a-z0-9-\.]{1,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[a-z0-9-\.]{0,63}:[^/].{0,1023}$
      minLength: 0
      maxLength: 1284
    WebExperienceId:
      type: string
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9-]*$
      minLength: 36
      maxLength: 36
    WebExperienceSubtitle:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    WebExperienceTitle:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 500
    WebExperienceWelcomeMessage:
      type: string
      minLength: 0
      maxLength: 300
