openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: qconnect
  x-aws-serviceName: qconnect
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-10-19'
  title: Amazon Q Connect
  description: |-
    * [Amazon Q actions](https://docs.aws.amazon.com/connect/latest/APIReference/API_Operations_Amazon_Q_Connect.html)

      * [Amazon Q data types](https://docs.aws.amazon.com/connect/latest/APIReference/API_Types_Amazon_Q_Connect.html)

    **Powered by Amazon Bedrock** : Amazon Web Services implements [automated abuse detection](https://docs.aws.amazon.com/bedrock/latest/userguide/abuse-detection.html). Because Amazon Q in Connect is built on Amazon Bedrock, users can take full advantage of the controls implemented in Amazon Bedrock to enforce safety, security, and the responsible use of artificial intelligence (AI).

    Amazon Q in Connect is a generative AI customer service assistant. It is an LLM-enhanced evolution of Amazon Connect Wisdom that delivers real-time recommendations to help contact center agents resolve customer issues quickly and accurately.

    Amazon Q in Connect automatically detects customer intent during calls and chats using conversational analytics and natural language understanding (NLU). It then provides agents with immediate, real-time generative responses and suggested actions, and links to relevant documents and articles. Agents can also query Amazon Q in Connect directly using natural language or keywords to answer customer requests.

    Use the Amazon Q in Connect APIs to create an assistant and a knowledge base, for example, or manage content by uploading custom files.

    For more information, see [Use Amazon Q in Connect for generative AI powered agent assistance in real-time](https://docs.aws.amazon.com/connect/latest/adminguide/amazon-q-connect.html) in the _Amazon Connect Administrator Guide_.
servers:
- description: The Amazon Q Connect regional endpoint
  url: https://wisdom.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AIAgentAssociationConfigurationType:
      type: string
      enum:
      - KNOWLEDGE_BASE
    AIAgentType:
      type: string
      enum:
      - MANUAL_SEARCH
      - ANSWER_RECOMMENDATION
      - SELF_SERVICE
    AIGuardrailBlockedMessaging:
      type: string
      minLength: 1
      maxLength: 500
    AIGuardrailDescription:
      type: string
      minLength: 1
      maxLength: 200
    AIPromptAPIFormat:
      type: string
      enum:
      - ANTHROPIC_CLAUDE_MESSAGES
      - ANTHROPIC_CLAUDE_TEXT_COMPLETIONS
      - MESSAGES
      - TEXT_COMPLETIONS
    AIPromptModelIdentifier:
      type: string
      minLength: 1
      maxLength: 2048
    AIPromptTemplateType:
      type: string
      enum:
      - TEXT
    AIPromptType:
      type: string
      enum:
      - ANSWER_GENERATION
      - INTENT_LABELING_GENERATION
      - QUERY_REFORMULATION
      - SELF_SERVICE_PRE_PROCESSING
      - SELF_SERVICE_ANSWER_GENERATION
    Arn:
      type: string
      pattern: ^arn:[a-z-]*?:wisdom:[a-z0-9-]*?:[0-9]{12}:[a-z-]*?/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(?:/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}){0,2}$
    ArnWithQualifier:
      type: string
      pattern: ^arn:[a-z-]*?:wisdom:[a-z0-9-]*?:[0-9]{12}:[a-z-]*?/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(?:/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}){0,2}(:[A-Z0-9_$]+){0,1}$
    AssistantCapabilityType:
      type: string
      enum:
      - V1
      - V2
    AssistantStatus:
      type: string
      enum:
      - CREATE_IN_PROGRESS
      - CREATE_FAILED
      - ACTIVE
      - DELETE_IN_PROGRESS
      - DELETE_FAILED
      - DELETED
    AssistantType:
      type: string
      enum:
      - AGENT
    AssociationType:
      type: string
      enum:
      - KNOWLEDGE_BASE
    AttachmentFileName:
      type: string
      pattern: ^[\p{L}\p{M}\p{N}_\s&@()+,;=\-]+\.[A-Za-z0-9]+$
      minLength: 1
      maxLength: 256
    BedrockModelArnForParsing:
      type: string
      pattern: ^arn:aws(-[^:]+)?:bedrock:[a-z0-9-]{1,20}::foundation-model/anthropic.claude-3-haiku-20240307-v1:0$
      minLength: 1
      maxLength: 2048
    Channel:
      type: string
      minLength: 1
      maxLength: 10
    ChannelSubtype:
      type: string
      enum:
      - EMAIL
      - SMS
    ChunkingStrategy:
      type: string
      enum:
      - FIXED_SIZE
      - NONE
      - HIERARCHICAL
      - SEMANTIC
    CitationSpanOffset:
      type: integer
      default: 0
    ClientToken:
      type: string
      minLength: 1
      maxLength: 4096
    ContactAttributeKey:
      type: string
    ContactAttributeValue:
      type: string
    ContentAssociationType:
      type: string
      enum:
      - AMAZON_CONNECT_GUIDE
    ContentDisposition:
      type: string
      enum:
      - ATTACHMENT
    ContentStatus:
      type: string
      enum:
      - CREATE_IN_PROGRESS
      - CREATE_FAILED
      - ACTIVE
      - DELETE_IN_PROGRESS
      - DELETE_FAILED
      - DELETED
      - UPDATE_FAILED
    ContentTitle:
      type: string
      minLength: 1
      maxLength: 255
    ContentType:
      type: string
      pattern: ^(text/(plain|html|csv))|(application/(pdf|vnd\.openxmlformats-officedocument\.wordprocessingml\.document))|(application/x\.wisdom-json;source=(salesforce|servicenow|zendesk))$
    ConversationStatus:
      type: string
      enum:
      - CLOSED
      - READY
      - PROCESSING
    ConversationStatusReason:
      type: string
      enum:
      - SUCCESS
      - FAILED
      - REJECTED
    Description:
      type: string
      pattern: ^[a-zA-Z0-9\s_.,-]+
      minLength: 1
      maxLength: 255
    EmailHeaderKey:
      type: string
      pattern: ^[!-9;-@A-~]+$
      minLength: 1
      maxLength: 126
    EmailHeaderValue:
      type: string
      pattern: '[ -~]*'
      minLength: 1
      maxLength: 870
    ExternalSource:
      type: string
      enum:
      - AMAZON_CONNECT
    FilterField:
      type: string
      enum:
      - NAME
    FilterOperator:
      type: string
      enum:
      - EQUALS
    GenericArn:
      type: string
      pattern: ^arn:[a-z-]+?:[a-z-]+?:[a-z0-9-]*?:([0-9]{12})?:[a-zA-Z0-9-:/]+$
      minLength: 1
      maxLength: 2048
    GroupingCriteria:
      type: string
      minLength: 1
      maxLength: 100
    GroupingValue:
      type: string
      minLength: 1
      maxLength: 2048
    GuardrailContentFilterType:
      type: string
      enum:
      - SEXUAL
      - VIOLENCE
      - HATE
      - INSULTS
      - MISCONDUCT
      - PROMPT_ATTACK
    GuardrailContextualGroundingFilterType:
      type: string
      enum:
      - GROUNDING
      - RELEVANCE
    GuardrailFilterStrength:
      type: string
      enum:
      - NONE
      - LOW
      - MEDIUM
      - HIGH
    GuardrailManagedWordsType:
      type: string
      enum:
      - PROFANITY
    GuardrailPiiEntityType:
      type: string
      enum:
      - ADDRESS
      - AGE
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - CA_HEALTH_NUMBER
      - CA_SOCIAL_INSURANCE_NUMBER
      - CREDIT_DEBIT_CARD_CVV
      - CREDIT_DEBIT_CARD_EXPIRY
      - CREDIT_DEBIT_CARD_NUMBER
      - DRIVER_ID
      - EMAIL
      - INTERNATIONAL_BANK_ACCOUNT_NUMBER
      - IP_ADDRESS
      - LICENSE_PLATE
      - MAC_ADDRESS
      - NAME
      - PASSWORD
      - PHONE
      - PIN
      - SWIFT_CODE
      - UK_NATIONAL_HEALTH_SERVICE_NUMBER
      - UK_NATIONAL_INSURANCE_NUMBER
      - UK_UNIQUE_TAXPAYER_REFERENCE_NUMBER
      - URL
      - USERNAME
      - US_BANK_ACCOUNT_NUMBER
      - US_BANK_ROUTING_NUMBER
      - US_INDIVIDUAL_TAX_IDENTIFICATION_NUMBER
      - US_PASSPORT_NUMBER
      - US_SOCIAL_SECURITY_NUMBER
      - VEHICLE_IDENTIFICATION_NUMBER
    GuardrailRegexDescription:
      type: string
      minLength: 1
      maxLength: 1000
    GuardrailRegexName:
      type: string
      minLength: 1
      maxLength: 100
    GuardrailRegexPattern:
      type: string
      minLength: 1
    GuardrailSensitiveInformationAction:
      type: string
      enum:
      - BLOCK
      - ANONYMIZE
    GuardrailTopicDefinition:
      type: string
      minLength: 1
      maxLength: 200
    GuardrailTopicExample:
      type: string
      minLength: 1
      maxLength: 100
    GuardrailTopicName:
      type: string
      pattern: ^[0-9a-zA-Z-_ !?.]+$
      minLength: 1
      maxLength: 100
    GuardrailTopicType:
      type: string
      enum:
      - DENY
    GuardrailWordText:
      type: string
      minLength: 1
    HighlightOffset:
      type: integer
      default: 0
    ImportJobStatus:
      type: string
      enum:
      - START_IN_PROGRESS
      - FAILED
      - COMPLETE
      - DELETE_IN_PROGRESS
      - DELETE_FAILED
      - DELETED
    ImportJobType:
      type: string
      enum:
      - QUICK_RESPONSES
    KnowledgeBaseSearchType:
      type: string
      enum:
      - HYBRID
      - SEMANTIC
    KnowledgeBaseStatus:
      type: string
      enum:
      - CREATE_IN_PROGRESS
      - CREATE_FAILED
      - ACTIVE
      - DELETE_IN_PROGRESS
      - DELETE_FAILED
      - DELETED
    KnowledgeBaseType:
      type: string
      enum:
      - EXTERNAL
      - CUSTOM
      - QUICK_RESPONSES
      - MESSAGE_TEMPLATES
      - MANAGED
    LanguageCode:
      type: string
      minLength: 2
      maxLength: 5
    LlmModelId:
      type: string
      minLength: 1
      maxLength: 128
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    MessageTemplateAttributeKey:
      type: string
      minLength: 1
      maxLength: 32767
    MessageTemplateAttributeType:
      type: string
      enum:
      - SYSTEM
      - AGENT
      - CUSTOMER_PROFILE
      - CUSTOM
    MessageTemplateAttributeValue:
      type: string
      minLength: 1
      maxLength: 32767
    MessageTemplateContentSha256:
      type: string
      pattern: ^[a-zA-Z0-9]+$
      minLength: 1
      maxLength: 64
    MessageTemplateFilterOperator:
      type: string
      enum:
      - EQUALS
      - PREFIX
    MessageTemplateFilterValue:
      type: string
      minLength: 1
      maxLength: 2048
    MessageTemplateQueryOperator:
      type: string
      enum:
      - CONTAINS
      - CONTAINS_AND_PREFIX
    MessageTemplateQueryValue:
      type: string
      minLength: 1
      maxLength: 1024
    MessageType:
      type: string
      enum:
      - TEXT
    Name:
      type: string
      pattern: ^[a-zA-Z0-9\s_.,-]+
      minLength: 1
      maxLength: 255
    NextToken:
      type: string
      minLength: 1
      maxLength: 2048
    NonEmptySensitiveString:
      type: string
      minLength: 1
      maxLength: 4096
    NonEmptyString:
      type: string
      minLength: 1
      maxLength: 4096
    NonEmptyUnlimitedString:
      type: string
      minLength: 1
    NotifyRecommendationsReceivedErrorMessage:
      type: string
    Order:
      type: string
      enum:
      - ASC
      - DESC
    Origin:
      type: string
      enum:
      - SYSTEM
      - CUSTOMER
    ParsingPromptText:
      type: string
      minLength: 1
      maxLength: 10000
    ParsingStrategy:
      type: string
      enum:
      - BEDROCK_FOUNDATION_MODEL
    Participant:
      type: string
      enum:
      - CUSTOMER
      - AGENT
      - BOT
    Priority:
      type: string
      enum:
      - HIGH
      - MEDIUM
      - LOW
    QueryConditionComparisonOperator:
      type: string
      enum:
      - EQUALS
    QueryConditionFieldName:
      type: string
      enum:
      - RESULT_TYPE
    QueryResultType:
      type: string
      enum:
      - KNOWLEDGE_CONTENT
      - INTENT_ANSWER
      - GENERATIVE_ANSWER
      - GENERATIVE_ANSWER_CHUNK
      - BLOCKED_GENERATIVE_ANSWER_CHUNK
      - INTENT_ANSWER_CHUNK
      - BLOCKED_INTENT_ANSWER_CHUNK
    QueryText:
      type: string
      maxLength: 512
    QuickResponseContent:
      type: string
      minLength: 1
      maxLength: 1024
    QuickResponseDescription:
      type: string
      minLength: 1
      maxLength: 255
    QuickResponseFilterOperator:
      type: string
      enum:
      - EQUALS
      - PREFIX
    QuickResponseFilterValue:
      type: string
      minLength: 1
      maxLength: 2048
    QuickResponseName:
      type: string
      minLength: 1
      maxLength: 100
    QuickResponseQueryOperator:
      type: string
      enum:
      - CONTAINS
      - CONTAINS_AND_PREFIX
    QuickResponseQueryValue:
      type: string
      minLength: 1
      maxLength: 1024
    QuickResponseStatus:
      type: string
      enum:
      - CREATE_IN_PROGRESS
      - CREATE_FAILED
      - CREATED
      - DELETE_IN_PROGRESS
      - DELETE_FAILED
      - DELETED
      - UPDATE_IN_PROGRESS
      - UPDATE_FAILED
    QuickResponseType:
      type: string
      pattern: ^(application/x\.quickresponse;format=(plain|markdown))$
    RecommendationId:
      type: string
      minLength: 1
      maxLength: 2048
    RecommendationSourceType:
      type: string
      enum:
      - ISSUE_DETECTION
      - RULE_EVALUATION
      - OTHER
    RecommendationTriggerType:
      type: string
      enum:
      - QUERY
      - GENERATIVE
    RecommendationType:
      type: string
      enum:
      - KNOWLEDGE_CONTENT
      - GENERATIVE_RESPONSE
      - GENERATIVE_ANSWER
      - DETECTED_INTENT
      - GENERATIVE_ANSWER_CHUNK
      - BLOCKED_GENERATIVE_ANSWER_CHUNK
      - INTENT_ANSWER_CHUNK
      - BLOCKED_INTENT_ANSWER_CHUNK
    ReferenceType:
      type: string
      enum:
      - WEB_CRAWLER
      - KNOWLEDGE_BASE
    Relevance:
      type: string
      enum:
      - HELPFUL
      - NOT_HELPFUL
    RelevanceLevel:
      type: string
      enum:
      - HIGH
      - MEDIUM
      - LOW
    SensitiveString:
      type: string
    SessionDataNamespace:
      type: string
      enum:
      - Custom
    ShortCutKey:
      type: string
      minLength: 1
      maxLength: 10
    SourceContentType:
      type: string
      enum:
      - KNOWLEDGE_CONTENT
    Status:
      type: string
      enum:
      - CREATE_IN_PROGRESS
      - CREATE_FAILED
      - ACTIVE
      - DELETE_IN_PROGRESS
      - DELETE_FAILED
      - DELETED
    SyncStatus:
      type: string
      enum:
      - SYNC_FAILED
      - SYNCING_IN_PROGRESS
      - SYNC_SUCCESS
      - CREATE_IN_PROGRESS
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 1
      maxLength: 256
    TargetType:
      type: string
      enum:
      - RECOMMENDATION
      - RESULT
    TextAIPrompt:
      type: string
      minLength: 1
      maxLength: 1000000
    TimeToLive:
      type: integer
      minimum: 1
      maximum: 60
      description: Expiration time in minutes
    UploadId:
      type: string
      minLength: 1
      maxLength: 1200
    Uri:
      type: string
      minLength: 1
      maxLength: 4096
    Url:
      type: string
      minLength: 1
      maxLength: 4096
    UrlFilterPattern:
      type: string
      minLength: 1
      maxLength: 1000
    Uuid:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
    UuidOrArn:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$|^arn:[a-z-]*?:wisdom:[a-z0-9-]*?:[0-9]{12}:[a-z-]*?/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(?:/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}){0,2}$
    UuidOrArnOrEitherWithQualifier:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(:[A-Z0-9_$]+){0,1}$|^arn:[a-z-]*?:wisdom:[a-z0-9-]*?:[0-9]{12}:[a-z-]*?/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(?:/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}){0,2}(:[A-Z0-9_$]+){0,1}$
    UuidWithQualifier:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(:[A-Z0-9_$]+){0,1}$
    VisibilityStatus:
      type: string
      enum:
      - SAVED
      - PUBLISHED
    WaitTimeSeconds:
      type: integer
      default: 0
      minimum: 0
      maximum: 20
    WebScopeType:
      type: string
      enum:
      - HOST_ONLY
      - SUBDOMAINS
    WebUrl:
      type: string
      pattern: ^https?://[A-Za-z0-9][^\s]*$
