openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: qldb
  x-aws-serviceName: qldb
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2019-01-02'
  title: Amazon QLDB
  description: |-
    The resource management API for Amazon QLDB
servers:
- description: The Amazon QLDB regional endpoint
  url: https://qldb.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Arn:
      type: string
      minLength: 20
      maxLength: 1600
    Boolean:
      type: boolean
    DeletionProtection:
      type: boolean
    Digest:
      type: string
      format: byte
      minLength: 32
      maxLength: 32
    EncryptionStatus:
      type: string
      enum:
      - ENABLED
      - UPDATING
      - KMS_KEY_INACCESSIBLE
    ErrorCause:
      type: string
      enum:
      - KINESIS_STREAM_NOT_FOUND
      - IAM_PERMISSION_REVOKED
    ErrorMessage:
      type: string
    ExportStatus:
      type: string
      enum:
      - IN_PROGRESS
      - COMPLETED
      - CANCELLED
    IonText:
      type: string
      minLength: 1
      maxLength: 1048576
    JournalKinesisStreamDescriptionList:
      type: array
      items:
        $ref: '#/components/schemas/JournalKinesisStreamDescription'
    JournalS3ExportList:
      type: array
      items:
        $ref: '#/components/schemas/JournalS3ExportDescription'
    KmsKey:
      type: string
      minLength: 0
      maxLength: 1600
    LedgerList:
      type: array
      items:
        $ref: '#/components/schemas/LedgerSummary'
    LedgerName:
      type: string
      pattern: ^(?!^.*--)(?!^[0-9]+$)(?!^-)(?!.*-$)^[A-Za-z0-9-]+$
      minLength: 1
      maxLength: 32
    LedgerState:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - DELETING
      - DELETED
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    NextToken:
      type: string
      pattern: ^[A-Za-z-0-9+/=]+$
      minLength: 4
      maxLength: 1024
    OutputFormat:
      type: string
      enum:
      - ION_BINARY
      - ION_TEXT
      - JSON
    ParameterName:
      type: string
    PermissionsMode:
      type: string
      enum:
      - ALLOW_ALL
      - STANDARD
    ResourceName:
      type: string
    ResourceType:
      type: string
    S3Bucket:
      type: string
      pattern: ^[A-Za-z-0-9-_.]+$
      minLength: 3
      maxLength: 255
    S3ObjectEncryptionType:
      type: string
      enum:
      - SSE_KMS
      - SSE_S3
      - NO_ENCRYPTION
    S3Prefix:
      type: string
      minLength: 0
      maxLength: 128
    StreamName:
      type: string
      pattern: ^(?!^.*--)(?!^[0-9]+$)(?!^-)(?!.*-$)^[A-Za-z0-9-]+$
      minLength: 1
      maxLength: 32
    StreamStatus:
      type: string
      enum:
      - ACTIVE
      - COMPLETED
      - CANCELED
      - FAILED
      - IMPAIRED
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    Tags:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    Timestamp:
      type: string
      format: date-time
    UniqueId:
      type: string
      pattern: ^[A-Za-z-0-9]+$
      minLength: 22
      maxLength: 22
