openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: quicksight
  x-aws-serviceName: quicksight
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-04-01'
  title: Amazon QuickSight
  description: |-
    Amazon QuickSight API Reference

    Amazon QuickSight is a fully managed, serverless business intelligence service for the Amazon Web Services Cloud that makes it easy to extend data and insights to every user in your organization. This API reference contains documentation for a programming interface that you can use to manage Amazon QuickSight.
servers:
- description: The Amazon QuickSight regional endpoint
  url: https://quicksight.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccountName:
      type: string
      pattern: ^(?!D-|d-)([\da-zA-Z]+)([-]*[\da-zA-Z])*$
      minLength: 1
      maxLength: 62
    AggFunctionParamKey:
      type: string
      minLength: 1
      maxLength: 256
    AggFunctionParamValue:
      type: string
      minLength: 0
      maxLength: 1024
    AliasName:
      type: string
      pattern: ^[\w\-]+|(\$LATEST)|(\$PUBLISHED)$
      minLength: 1
      maxLength: 2048
    AltText:
      type: string
      pattern: ^[ -ÿ]+$
      minLength: 1
      maxLength: 512
    AnalysisName:
      type: string
      minLength: 1
      maxLength: 2048
    AnswerId:
      type: string
      pattern: ^[A-Za-z0-9-_.\\+]*$
      minLength: 0
      maxLength: 256
    Arn:
      type: string
    AssetBundleRestrictiveResourceId:
      type: string
      pattern: ^\*|[\w\-]{1,2048}$
    AwsAccountId:
      type: string
      pattern: ^[0-9]{12}$
      minLength: 12
      maxLength: 12
    AwsAndAccountId:
      type: string
      pattern: ^(aws|[0-9]{12})$
    BinCountValue:
      type: integer
      minimum: 0
    BodySectionDynamicDimensionLimit:
      type: integer
      minimum: 1
      maximum: 1000
    Boolean:
      type: boolean
      default: false
    BooleanObject:
      type: boolean
    CIDR:
      type: string
      pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(3[0-2]|[1-2][0-9]|[1-9]))$
    CalculatedFieldExpression:
      type: string
      minLength: 1
      maxLength: 32000
    Catalog:
      type: string
      minLength: 0
      maxLength: 128
    CategoryValue:
      type: string
      minLength: 0
      maxLength: 512
    ClusterId:
      type: string
      minLength: 1
      maxLength: 64
    ColumnDescriptiveText:
      type: string
      minLength: 0
      maxLength: 500
    ColumnGroupName:
      type: string
      minLength: 1
      maxLength: 64
    ColumnId:
      type: string
      minLength: 1
      maxLength: 64
    ColumnName:
      type: string
      minLength: 1
      maxLength: 128
    ConstantValueString:
      type: string
      minLength: 0
      maxLength: 1024
    CopySourceArn:
      type: string
      pattern: ^arn:[-a-z0-9]*:quicksight:[-a-z0-9]*:[0-9]{12}:datasource/.+$
    CurrencyCode:
      type: string
      pattern: ^[A-Z]{3}$
    CustomLabel:
      type: string
      minLength: 1
      maxLength: 2048
    CustomPermissionsName:
      type: string
      pattern: ^[a-zA-Z0-9+=,.@_-]+$
      minLength: 1
      maxLength: 64
    CustomSqlName:
      type: string
      minLength: 1
      maxLength: 64
    DashboardName:
      type: string
      minLength: 1
      maxLength: 2048
    DataSetCalculatedFieldExpression:
      type: string
      minLength: 1
      maxLength: 250000
    DataSetIdentifier:
      type: string
      minLength: 1
      maxLength: 2048
    DataSetName:
      type: string
      minLength: 1
      maxLength: 128
    DataSetRegion:
      type: string
      minLength: 1
      maxLength: 256
    Database:
      type: string
      minLength: 1
      maxLength: 128
    DatabaseAccessControlRole:
      type: string
      minLength: 0
      maxLength: 128
    DatabaseGroup:
      type: string
      minLength: 1
      maxLength: 64
    DatabaseUser:
      type: string
      minLength: 1
      maxLength: 64
    DatasetParameterId:
      type: string
      pattern: ^[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 128
    DatasetParameterName:
      type: string
      pattern: ^[a-zA-Z0-9]+$
      minLength: 1
      maxLength: 2048
    DateTimeFormat:
      type: string
      minLength: 1
      maxLength: 128
    DayOfMonth:
      type: string
      pattern: ^(?:LAST_DAY_OF_MONTH|1[0-9]|2[0-8]|[12]|[3-9])$
      minLength: 1
      maxLength: 17
    DbUsername:
      type: string
      minLength: 1
      maxLength: 64
    Delimiter:
      type: string
      minLength: 1
      maxLength: 1
    Description:
      type: string
      pattern: ^[ -ÿ]+$
      minLength: 1
      maxLength: 2048
    Domain:
      type: string
      minLength: 1
      maxLength: 64
    EmbeddingUrl:
      type: string
    EntryPath:
      type: string
      minLength: 1
      maxLength: 1000
    EntryPoint:
      type: string
      minLength: 1
      maxLength: 1000
    ErrorMessage:
      type: string
    Expression:
      type: string
      minLength: 1
      maxLength: 4096
    FieldFolderDescription:
      type: string
      minLength: 0
      maxLength: 500
    FieldFolderPath:
      type: string
      minLength: 1
      maxLength: 1000
    FieldId:
      type: string
      minLength: 1
      maxLength: 512
    FieldValue:
      type: string
      minLength: 0
      maxLength: 2048
    FolderName:
      type: string
      minLength: 1
      maxLength: 200
    ForecastComputationCustomSeasonalityValue:
      type: integer
      minimum: 1
      maximum: 180
    GridLayoutElementColumnIndex:
      type: integer
      minimum: 0
      maximum: 35
    GridLayoutElementColumnSpan:
      type: integer
      minimum: 1
      maximum: 36
    GridLayoutElementRowIndex:
      type: integer
      minimum: 0
      maximum: 9009
    GridLayoutElementRowSpan:
      type: integer
      minimum: 1
      maximum: 21
    GroupDescription:
      type: string
      minLength: 1
      maxLength: 512
    GroupMemberName:
      type: string
      pattern: ^[\u0020-\u00FF]+$
      minLength: 1
      maxLength: 256
    GroupName:
      type: string
      pattern: ^[\u0020-\u00FF]+$
      minLength: 1
    GrowthRatePeriodSize:
      type: integer
      minimum: 2
      maximum: 52
    HexColor:
      type: string
      pattern: ^#[A-F0-9]{6}$
    HexColorWithTransparency:
      type: string
      pattern: ^#[A-F0-9]{6}(?:[A-F0-9]{2})?$
    HierarchyId:
      type: string
      minLength: 1
      maxLength: 512
    Host:
      type: string
      minLength: 1
      maxLength: 256
    IAMPolicyAssignmentName:
      type: string
      pattern: ^(?=^.{2,256}$)(?!.*\s)[0-9a-zA-Z-_.:=+@]*$
      minLength: 1
    IPv4Address:
      type: string
      minLength: 7
      maxLength: 15
    IdentityName:
      type: string
      pattern: ^[\u0020-\u00FF]+$
      minLength: 1
    IdentityProviderResourceUri:
      type: string
      minLength: 1
      maxLength: 2048
    ImageCustomActionName:
      type: string
      minLength: 1
      maxLength: 256
    IngestionId:
      type: string
      pattern: ^[a-zA-Z0-9-_]+$
      minLength: 1
      maxLength: 128
    IngestionMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    InstanceId:
      type: string
      minLength: 1
      maxLength: 64
    Integer:
      type: integer
      default: 0
    IpRestrictionRuleDescription:
      type: string
      minLength: 0
      maxLength: 150
    LayerCustomActionName:
      type: string
      minLength: 1
      maxLength: 256
    Length:
      type: string
    LimitedString:
      type: string
      minLength: 0
      maxLength: 256
    LinkEntityArn:
      type: string
      pattern: ^arn:aws[\w\-]*:quicksight:[\w\-]+:\d+:analysis/[\w\-]{1,512}$
      minLength: 1
      maxLength: 1024
    ListIdentityPropagationMaxResults:
      type: integer
      default: 0
      minimum: 1
      maximum: 10
    LogicalTableAlias:
      type: string
      minLength: 1
      maxLength: 64
    LogicalTableId:
      type: string
      pattern: ^[0-9a-zA-Z-]*$
      minLength: 1
      maxLength: 64
    LongPlainText:
      type: string
      minLength: 1
      maxLength: 1024
    LongRichText:
      type: string
      minLength: 1
      maxLength: 2048
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    MaxTopicsToConsider:
      type: integer
      minimum: 1
      maximum: 4
    Name:
      type: string
      pattern: ^[ -ÿ]+$
      minLength: 1
      maxLength: 512
    Namespace:
      type: string
      pattern: ^[a-zA-Z0-9._-]*$
      minLength: 0
      maxLength: 64
    NarrativeString:
      type: string
      minLength: 0
      maxLength: 150000
    NetworkInterfaceId:
      type: string
      pattern: ^eni-[0-9a-z]*$
      minLength: 0
      maxLength: 255
    NonEmptyString:
      type: string
      pattern: \S
    NullString:
      type: string
      minLength: 1
      maxLength: 128
    NullableBoolean:
      type: boolean
    OAuthScope:
      type: string
      minLength: 1
      maxLength: 128
    OnClause:
      type: string
      minLength: 1
      maxLength: 512
    OptionalPort:
      type: integer
      default: 0
      minimum: 0
      maximum: 65535
    ParameterName:
      type: string
      pattern: ^[a-zA-Z0-9]+$
      minLength: 1
      maxLength: 2048
    Password:
      type: string
      minLength: 1
      maxLength: 1024
    PeriodsBackward:
      type: integer
      minimum: 0
      maximum: 1000
    PeriodsForward:
      type: integer
      minimum: 1
      maximum: 1000
    PhysicalTableId:
      type: string
      pattern: ^[0-9a-zA-Z-]*$
      minLength: 1
      maxLength: 64
    PivotTableRowsLabelText:
      type: string
      minLength: 1
      maxLength: 1024
    PixelLength:
      type: string
    Port:
      type: integer
      minimum: 1
      maximum: 65535
    PositiveInteger:
      type: integer
      minimum: 1
    PredictionInterval:
      type: integer
      minimum: 50
      maximum: 95
    Prefix:
      type: string
      minLength: 1
      maxLength: 128
    Principal:
      type: string
      minLength: 1
      maxLength: 256
    ProjectId:
      type: string
      minLength: 1
      maxLength: 256
    QAQueryText:
      type: string
      minLength: 1
      maxLength: 1024
    QAUrl:
      type: string
    Query:
      type: string
      minLength: 1
      maxLength: 256
    QuestionId:
      type: string
      pattern: ^[a-zA-Z0-9-]+$
      minLength: 0
      maxLength: 64
    RelationalTableCatalog:
      type: string
      minLength: 0
      maxLength: 256
    RelationalTableName:
      type: string
      minLength: 1
      maxLength: 256
    RelationalTableSchema:
      type: string
      minLength: 0
      maxLength: 256
    ResourceId:
      type: string
    ResourceName:
      type: string
      minLength: 1
      maxLength: 128
    RestrictiveResourceId:
      type: string
      pattern: ^[\w\-]+$
      minLength: 1
      maxLength: 2048
    RoleArn:
      type: string
      minLength: 20
      maxLength: 2048
    RoleName:
      type: string
      pattern: ^[a-zA-Z0-9+=,.@_-]+$
      minLength: 1
      maxLength: 64
    RoleSessionName:
      type: string
      pattern: ^[\w+=.@-]*$
      minLength: 2
      maxLength: 64
    RowLevelPermissionTagDelimiter:
      type: string
      minLength: 0
      maxLength: 10
    S3Bucket:
      type: string
      minLength: 1
      maxLength: 1024
    S3Key:
      type: string
      minLength: 1
      maxLength: 1024
    S3Uri:
      type: string
      pattern: ^(https|s3)://([^/]+)/?(.*)$
    Seasonality:
      type: integer
      minimum: 1
      maximum: 180
    SecretArn:
      type: string
      pattern: ^arn:[-a-z0-9]*:secretsmanager:[-a-z0-9]*:[0-9]{12}:secret:.+$
      minLength: 1
      maxLength: 2048
    SecurityGroupId:
      type: string
      pattern: ^sg-[0-9a-z]*$
      minLength: 1
      maxLength: 255
    SensitiveS3Uri:
      type: string
      pattern: ^(https|s3)://([^/]+)/?(.*)$
    SensitiveString:
      type: string
    SensitiveStringObject:
      type: string
    SessionTagKey:
      type: string
      minLength: 1
      maxLength: 128
    SessionTagValue:
      type: string
      minLength: 1
      maxLength: 256
    SheetControlInfoIconText:
      type: string
      minLength: 1
      maxLength: 100
    SheetControlTitle:
      type: string
      minLength: 1
      maxLength: 2048
    SheetDescription:
      type: string
      minLength: 1
      maxLength: 1024
    SheetName:
      type: string
      minLength: 1
      maxLength: 2048
    SheetTextBoxContent:
      type: string
      minLength: 0
      maxLength: 150000
    SheetTitle:
      type: string
      minLength: 1
      maxLength: 1024
    ShortPlainText:
      type: string
      minLength: 1
      maxLength: 512
    ShortRestrictiveResourceId:
      type: string
      pattern: ^[\w\-]+$
      minLength: 1
      maxLength: 512
    ShortRichText:
      type: string
      minLength: 1
      maxLength: 1024
    SiteBaseUrl:
      type: string
      minLength: 1
      maxLength: 1024
    SqlEndpointPath:
      type: string
      minLength: 1
      maxLength: 4096
    SqlQuery:
      type: string
      minLength: 1
      maxLength: 168000
    StatusCode:
      type: integer
      default: 0
    String:
      type: string
    StringDatasetParameterDefaultValue:
      type: string
      minLength: 0
      maxLength: 512
    SubnetId:
      type: string
      pattern: ^subnet-[0-9a-z]*$
      minLength: 1
      maxLength: 255
    Suffix:
      type: string
      minLength: 1
      maxLength: 128
    TableBorderThickness:
      type: integer
      minimum: 1
      maximum: 4
    TableFieldHeight:
      type: integer
      minimum: 8
      maximum: 500
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 1
      maxLength: 256
    TemplateName:
      type: string
      minLength: 1
      maxLength: 2048
    TextAreaControlDelimiter:
      type: string
      minLength: 1
      maxLength: 2048
    ThemeName:
      type: string
      minLength: 1
      maxLength: 2048
    TokenProviderUrl:
      type: string
      minLength: 1
      maxLength: 2048
    TopBottomMoversComputationMoverSize:
      type: integer
      minimum: 1
      maximum: 20
    TopBottomRankedComputationResultSize:
      type: integer
      minimum: 1
      maximum: 20
    TopicId:
      type: string
      pattern: ^[A-Za-z0-9-_.\\+]*$
      minLength: 0
      maxLength: 256
    TransposedColumnIndex:
      type: integer
      minimum: 0
      maximum: 9999
      description: <p>The integer value of a column index in the transposed table.</p>
    TypeCastFormat:
      type: string
      minLength: 0
      maxLength: 32
    URLOperationTemplate:
      type: string
      minLength: 1
      maxLength: 2048
    UnicodeIcon:
      type: string
      pattern: ^[^\u0000-\u00FF]$
    UnlimitedPixelLength:
      type: string
    UserName:
      type: string
      pattern: ^[\u0020-\u00FF]+$
      minLength: 1
    VPCConnectionResourceIdRestricted:
      type: string
      pattern: ^[\w\-]+$
      minLength: 1
      maxLength: 1000
    VPCConnectionResourceIdUnrestricted:
      type: string
      minLength: 1
      maxLength: 1000
    VersionDescription:
      type: string
      minLength: 1
      maxLength: 512
    VisualCustomActionName:
      type: string
      minLength: 1
      maxLength: 256
    VisualSubtitle:
      type: string
      minLength: 1
      maxLength: 1024
    VisualTitle:
      type: string
      minLength: 1
      maxLength: 1024
    VpcEndpointId:
      type: string
      pattern: ^vpce-[0-9a-z]*$
      minLength: 1
      maxLength: 255
    VpcEndpointIdRestrictionRuleDescription:
      type: string
      minLength: 0
      maxLength: 150
    VpcId:
      type: string
      pattern: ^vpc-[0-9a-z]*$
      minLength: 1
      maxLength: 255
    VpcIdRestrictionRuleDescription:
      type: string
      minLength: 0
      maxLength: 150
    Warehouse:
      type: string
      minLength: 0
      maxLength: 128
    WordCloudMaximumStringLength:
      type: integer
      minimum: 1
      maximum: 100
    WorkGroup:
      type: string
      minLength: 1
      maxLength: 128
