openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: ram
  x-aws-serviceName: ram
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-01-04'
  title: AWS Resource Access Manager
  description: |-
    This is the _Resource Access Manager API Reference_. This documentation provides descriptions and syntax for each of the actions and data types in RAM. RAM is a service that helps you securely share your Amazon Web Services resources to other Amazon Web Services accounts. If you use Organizations to manage your accounts, then you can share your resources with your entire organization or to organizational units (OUs). For supported resource types, you can also share resources with individual Identity and Access Management (IAM) roles and users.

    To learn more about RAM, see the following resources:

      * [Resource Access Manager product page](http://aws.amazon.com/ram)

      * [Resource Access Manager User Guide](https://docs.aws.amazon.com/ram/latest/userguide/)
servers:
- description: The AWS Resource Access Manager regional endpoint
  url: https://ram.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AssociatedPermissionList:
      type: array
      items:
        $ref: '#/components/schemas/AssociatedPermission'
    Boolean:
      type: boolean
    DateTime:
      type: string
      format: date-time
    Integer:
      type: integer
    MaxResults:
      type: integer
      minimum: 1
      maximum: 500
    PermissionArnList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    PermissionFeatureSet:
      type: string
      enum:
      - CREATED_FROM_POLICY
      - PROMOTING_TO_STANDARD
      - STANDARD
    PermissionName:
      type: string
      pattern: ^[\w.-]*$
      minLength: 1
      maxLength: 36
    PermissionStatus:
      type: string
      enum:
      - ATTACHABLE
      - UNATTACHABLE
      - DELETING
      - DELETED
    PermissionType:
      type: string
      enum:
      - CUSTOMER_MANAGED
      - AWS_MANAGED
    PermissionTypeFilter:
      type: string
      enum:
      - ALL
      - AWS_MANAGED
      - CUSTOMER_MANAGED
    Policy:
      type: string
    PolicyList:
      type: array
      items:
        $ref: '#/components/schemas/Policy'
    PrincipalArnOrIdList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    PrincipalList:
      type: array
      items:
        $ref: '#/components/schemas/Principal'
    ReplacePermissionAssociationsWorkIdList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    ReplacePermissionAssociationsWorkList:
      type: array
      items:
        $ref: '#/components/schemas/ReplacePermissionAssociationsWork'
    ReplacePermissionAssociationsWorkStatus:
      type: string
      enum:
      - IN_PROGRESS
      - COMPLETED
      - FAILED
    ResourceArnList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    ResourceList:
      type: array
      items:
        $ref: '#/components/schemas/Resource'
    ResourceOwner:
      type: string
      enum:
      - SELF
      - OTHER-ACCOUNTS
    ResourceRegionScope:
      type: string
      enum:
      - REGIONAL
      - GLOBAL
    ResourceRegionScopeFilter:
      type: string
      enum:
      - ALL
      - REGIONAL
      - GLOBAL
    ResourceShareArnList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    ResourceShareAssociationList:
      type: array
      items:
        $ref: '#/components/schemas/ResourceShareAssociation'
    ResourceShareAssociationStatus:
      type: string
      enum:
      - ASSOCIATING
      - ASSOCIATED
      - FAILED
      - DISASSOCIATING
      - DISASSOCIATED
    ResourceShareAssociationType:
      type: string
      enum:
      - PRINCIPAL
      - RESOURCE
    ResourceShareFeatureSet:
      type: string
      enum:
      - CREATED_FROM_POLICY
      - PROMOTING_TO_STANDARD
      - STANDARD
    ResourceShareInvitationArnList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    ResourceShareInvitationList:
      type: array
      items:
        $ref: '#/components/schemas/ResourceShareInvitation'
    ResourceShareInvitationStatus:
      type: string
      enum:
      - PENDING
      - ACCEPTED
      - REJECTED
      - EXPIRED
    ResourceShareList:
      type: array
      items:
        $ref: '#/components/schemas/ResourceShare'
    ResourceSharePermissionList:
      type: array
      items:
        $ref: '#/components/schemas/ResourceSharePermissionSummary'
    ResourceShareStatus:
      type: string
      enum:
      - PENDING
      - ACTIVE
      - FAILED
      - DELETING
      - DELETED
    ResourceStatus:
      type: string
      enum:
      - AVAILABLE
      - ZONAL_RESOURCE_INACCESSIBLE
      - LIMIT_EXCEEDED
      - UNAVAILABLE
      - PENDING
    ServiceNameAndResourceTypeList:
      type: array
      items:
        $ref: '#/components/schemas/ServiceNameAndResourceType'
    SourceArnOrAccountList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    String:
      type: string
    TagFilters:
      type: array
      items:
        $ref: '#/components/schemas/TagFilter'
    TagKey:
      type: string
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagList:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    TagValue:
      type: string
    TagValueList:
      type: array
      items:
        $ref: '#/components/schemas/TagValue'
