openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: resiliencehub
  x-aws-serviceName: resiliencehub
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-04-30'
  title: AWS Resilience Hub
  description: |-
    Resilience Hub helps you proactively prepare and protect your Amazon Web Services applications from disruptions. It offers continual resiliency assessment and validation that integrates into your software development lifecycle. This enables you to uncover resiliency weaknesses, ensure recovery time objective (RTO) and recovery point objective (RPO) targets for your applications are met, and resolve issues before they are released into production.
servers:
- description: The AWS Resilience Hub regional endpoint
  url: https://resiliencehub.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AppTemplateBody:
      type: string
      pattern: ^[\w\s:,-\.'\/{}\[\]:"\\]+$
      minLength: 0
      maxLength: 409600
    Arn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-iso|aws-iso-[a-z]{1}|aws-us-gov):[A-Za-z0-9][A-Za-z0-9_/.-]{0,62}:([a-z]{2}-((iso[a-z]{0,1}-)|(gov-)){0,1}[a-z]+-[0-9]):[0-9]{12}:[A-Za-z0-9/][A-Za-z0-9:_/+.-]{0,1023}$
    AwsRegion:
      type: string
      pattern: ^[a-z]{2}-((iso[a-z]{0,1}-)|(gov-)){0,1}[a-z]+-[0-9]$
    BooleanOptional:
      type: boolean
    ClientToken:
      type: string
      pattern: ^[A-Za-z0-9_.-]{0,63}$
      minLength: 1
      maxLength: 63
    CurrencyCode:
      type: string
      minLength: 0
      maxLength: 3
    CustomerId:
      type: string
      pattern: ^[0-9]{12}$
    DocumentName:
      type: string
      minLength: 1
      maxLength: 500
    EksNamespace:
      type: string
      pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
      minLength: 1
      maxLength: 63
    EntityDescription:
      type: string
      minLength: 0
      maxLength: 500
    EntityId:
      type: string
      pattern: ^\S{1,255}$
    EntityName:
      type: string
      pattern: ^[A-Za-z0-9][A-Za-z0-9_\-]{1,59}$
    EntityName255:
      type: string
      pattern: ^[A-Za-z0-9][A-Za-z0-9_\-]{0,254}$
    EntityVersion:
      type: string
      pattern: ^\S{1,50}$
    ErrorMessage:
      type: string
      minLength: 0
      maxLength: 500
    IamRoleArn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-iso|aws-iso-[a-z]{1}|aws-us-gov):iam::[0-9]{12}:role/(([^/][!-~]+/){1,511})?[A-Za-z0-9_+=,.@-]{1,64}$
    IamRoleName:
      type: string
      pattern: ^([^/]([!-~]+/){1,511})?[A-Za-z0-9_+=,.@-]{1,64}$
    Integer:
      type: integer
      default: 0
    IntegerOptional:
      type: integer
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    NextToken:
      type: string
      pattern: ^\S{1,2000}$
    ResourceId:
      type: string
      pattern: .*
    ResourceType:
      type: string
      pattern: .*
    RetryAfterSeconds:
      type: integer
    S3Url:
      type: string
      pattern: ^((https://([^/]+)\.s3((-|\.)[^/]+)?\.amazonaws\.com(.cn)?)|(s3://([^/]+)))/\S{1,2000}$
      maxLength: 2000
    Seconds:
      type: integer
      default: 0
      minimum: 0
    SpecReferenceId:
      type: string
      minLength: 1
      maxLength: 500
    String1024:
      type: string
      minLength: 1
      maxLength: 1024
    String128WithoutWhitespace:
      type: string
      pattern: ^\S{1,128}$
    String2048:
      type: string
      minLength: 1
      maxLength: 2048
    String255:
      type: string
      minLength: 1
      maxLength: 255
    String500:
      type: string
      minLength: 1
      maxLength: 500
    TagKey:
      type: string
      pattern: ^[^\x00-\x1f\x22]+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^[^\x00-\x1f\x22]*$
      minLength: 0
      maxLength: 256
    Uuid:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$
