openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: resiliencehub
  x-aws-serviceName: resiliencehub
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-04-30'
  title: AWS Resilience Hub
  description: |-
    Resilience Hub helps you proactively prepare and protect your Amazon Web Services applications from disruptions. It offers continual resiliency assessment and validation that integrates into your software development lifecycle. This enables you to uncover resiliency weaknesses, ensure recovery time objective (RTO) and recovery point objective (RPO) targets for your applications are met, and resolve issues before they are released into production.
servers:
- description: The AWS Resilience Hub regional endpoint
  url: https://resiliencehub.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AcceptGroupingRecommendationEntries:
      type: array
      items:
        $ref: '#/components/schemas/AcceptGroupingRecommendationEntry'
    AdditionalInfoMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/AdditionalInfoValueList'
    AdditionalInfoValueList:
      type: array
      items:
        $ref: '#/components/schemas/String1024'
    AlarmRecommendationList:
      type: array
      items:
        $ref: '#/components/schemas/AlarmRecommendation'
    AlarmReferenceIdList:
      type: array
      items:
        $ref: '#/components/schemas/String500'
    AlarmType:
      type: string
      enum:
      - Metric
      - Composite
      - Canary
      - Logs
      - Event
    AppAssessmentScheduleType:
      type: string
      enum:
      - Disabled
      - Daily
    AppAssessmentSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/AppAssessmentSummary'
    AppComplianceStatusType:
      type: string
      enum:
      - PolicyBreached
      - PolicyMet
      - NotAssessed
      - ChangesDetected
      - NotApplicable
      - MissingPolicy
    AppComponentList:
      type: array
      items:
        $ref: '#/components/schemas/AppComponent'
    AppComponentNameList:
      type: array
      items:
        $ref: '#/components/schemas/String255'
    AppDriftStatusType:
      type: string
      enum:
      - NotChecked
      - NotDetected
      - Detected
    AppInputSourceList:
      type: array
      items:
        $ref: '#/components/schemas/AppInputSource'
    AppStatusType:
      type: string
      enum:
      - Active
      - Deleting
    AppSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/AppSummary'
    AppTemplateBody:
      type: string
      pattern: ^[\w\s:,-\.'\/{}\[\]:"\\]+$
      minLength: 0
      maxLength: 409600
    AppVersionList:
      type: array
      items:
        $ref: '#/components/schemas/AppVersionSummary'
    Arn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-iso|aws-iso-[a-z]{1}|aws-us-gov):[A-Za-z0-9][A-Za-z0-9_/.-]{0,62}:([a-z]{2}-((iso[a-z]{0,1}-)|(gov-)){0,1}[a-z]+-[0-9]):[0-9]{12}:[A-Za-z0-9/][A-Za-z0-9:_/+.-]{0,1023}$
    ArnList:
      type: array
      items:
        $ref: '#/components/schemas/Arn'
    AssessmentCompliance:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/DisruptionCompliance'
    AssessmentInvoker:
      type: string
      enum:
      - User
      - System
    AssessmentRiskRecommendationList:
      type: array
      items:
        $ref: '#/components/schemas/AssessmentRiskRecommendation'
    AssessmentStatus:
      type: string
      enum:
      - Pending
      - InProgress
      - Failed
      - Success
    AssessmentStatusList:
      type: array
      items:
        $ref: '#/components/schemas/AssessmentStatus'
    AwsRegion:
      type: string
      pattern: ^[a-z]{2}-((iso[a-z]{0,1}-)|(gov-)){0,1}[a-z]+-[0-9]$
    BatchUpdateRecommendationStatusFailedEntries:
      type: array
      items:
        $ref: '#/components/schemas/BatchUpdateRecommendationStatusFailedEntry'
    BatchUpdateRecommendationStatusSuccessfulEntries:
      type: array
      items:
        $ref: '#/components/schemas/BatchUpdateRecommendationStatusSuccessfulEntry'
    BooleanOptional:
      type: boolean
    ClientToken:
      type: string
      pattern: ^[A-Za-z0-9_.-]{0,63}$
      minLength: 1
      maxLength: 63
    ComplianceDriftList:
      type: array
      items:
        $ref: '#/components/schemas/ComplianceDrift'
    ComplianceStatus:
      type: string
      enum:
      - PolicyBreached
      - PolicyMet
      - NotApplicable
      - MissingPolicy
    ComponentCompliancesList:
      type: array
      items:
        $ref: '#/components/schemas/AppComponentCompliance'
    ComponentRecommendationList:
      type: array
      items:
        $ref: '#/components/schemas/ComponentRecommendation'
    ConditionList:
      type: array
      items:
        $ref: '#/components/schemas/Condition'
    ConditionOperatorType:
      type: string
      enum:
      - Equals
      - NotEquals
      - GreaterThen
      - GreaterOrEquals
      - LessThen
      - LessOrEquals
    ConfigRecommendationList:
      type: array
      items:
        $ref: '#/components/schemas/ConfigRecommendation'
    ConfigRecommendationOptimizationType:
      type: string
      enum:
      - LeastCost
      - LeastChange
      - BestAZRecovery
      - LeastErrors
      - BestAttainable
      - BestRegionRecovery
    CostFrequency:
      type: string
      enum:
      - Hourly
      - Daily
      - Monthly
      - Yearly
    CurrencyCode:
      type: string
      minLength: 0
      maxLength: 3
    CustomerId:
      type: string
      pattern: ^[0-9]{12}$
    DataLocationConstraint:
      type: string
      enum:
      - AnyLocation
      - SameContinent
      - SameCountry
    DifferenceType:
      type: string
      enum:
      - NotEqual
      - Added
      - Removed
    DisruptionPolicy:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/FailurePolicy'
    DisruptionResiliencyScore:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Double'
    DisruptionType:
      type: string
      enum:
      - Software
      - Hardware
      - AZ
      - Region
    DocumentName:
      type: string
      minLength: 1
      maxLength: 500
    Double:
      type: number
      format: double
      default: 0
    DriftStatus:
      type: string
      enum:
      - NotChecked
      - NotDetected
      - Detected
    DriftType:
      type: string
      enum:
      - ApplicationCompliance
      - AppComponentResiliencyComplianceStatus
    EksNamespace:
      type: string
      pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
      minLength: 1
      maxLength: 63
    EksNamespaceList:
      type: array
      items:
        $ref: '#/components/schemas/EksNamespace'
    EksSourceList:
      type: array
      items:
        $ref: '#/components/schemas/EksSource'
    EntityDescription:
      type: string
      minLength: 0
      maxLength: 500
    EntityId:
      type: string
      pattern: ^\S{1,255}$
    EntityName:
      type: string
      pattern: ^[A-Za-z0-9][A-Za-z0-9_\-]{1,59}$
    EntityName255:
      type: string
      pattern: ^[A-Za-z0-9][A-Za-z0-9_\-]{0,254}$
    EntityNameList:
      type: array
      items:
        $ref: '#/components/schemas/EntityName'
    EntityVersion:
      type: string
      pattern: ^\S{1,50}$
    ErrorDetailList:
      type: array
      items:
        $ref: '#/components/schemas/ErrorDetail'
    ErrorMessage:
      type: string
      minLength: 0
      maxLength: 500
    EstimatedCostTier:
      type: string
      enum:
      - L1
      - L2
      - L3
      - L4
    EventSubscriptionList:
      type: array
      items:
        $ref: '#/components/schemas/EventSubscription'
    EventType:
      type: string
      enum:
      - ScheduledAssessmentFailure
      - DriftDetected
    ExcludeRecommendationReason:
      type: string
      enum:
      - AlreadyImplemented
      - NotRelevant
      - ComplexityOfImplementation
    FailedGroupingRecommendationEntries:
      type: array
      items:
        $ref: '#/components/schemas/FailedGroupingRecommendationEntry'
    FieldAggregationType:
      type: string
      enum:
      - Min
      - Max
      - Sum
      - Avg
      - Count
    FieldList:
      type: array
      items:
        $ref: '#/components/schemas/Field'
    GroupingRecommendationConfidenceLevel:
      type: string
      enum:
      - High
      - Medium
    GroupingRecommendationList:
      type: array
      items:
        $ref: '#/components/schemas/GroupingRecommendation'
    GroupingRecommendationRejectionReason:
      type: string
      enum:
      - DistinctBusinessPurpose
      - SeparateDataConcern
      - DistinctUserGroupHandling
      - Other
    GroupingRecommendationStatusType:
      type: string
      enum:
      - Accepted
      - Rejected
      - PendingDecision
    GroupingResourceList:
      type: array
      items:
        $ref: '#/components/schemas/GroupingResource'
    HaArchitecture:
      type: string
      enum:
      - MultiSite
      - WarmStandby
      - PilotLight
      - BackupAndRestore
      - NoRecoveryPlan
    IamRoleArn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-iso|aws-iso-[a-z]{1}|aws-us-gov):iam::[0-9]{12}:role/(([^/][!-~]+/){1,511})?[A-Za-z0-9_+=,.@-]{1,64}$
    IamRoleArnList:
      type: array
      items:
        $ref: '#/components/schemas/IamRoleArn'
    IamRoleName:
      type: string
      pattern: ^([^/]([!-~]+/){1,511})?[A-Za-z0-9_+=,.@-]{1,64}$
    Integer:
      type: integer
      default: 0
    IntegerOptional:
      type: integer
    Long:
      type: integer
      format: int64
      default: 0
    LongOptional:
      type: integer
      format: int64
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    MetricsExportStatusType:
      type: string
      enum:
      - Pending
      - InProgress
      - Failed
      - Success
    NextToken:
      type: string
      pattern: ^\S{1,2000}$
    PermissionModelType:
      type: string
      enum:
      - LegacyIAMUser
      - RoleBased
    PhysicalIdentifierType:
      type: string
      enum:
      - Arn
      - Native
    PhysicalResourceList:
      type: array
      items:
        $ref: '#/components/schemas/PhysicalResource'
    RecommendationCompliance:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/RecommendationDisruptionCompliance'
    RecommendationComplianceStatus:
      type: string
      enum:
      - BreachedUnattainable
      - BreachedCanMeet
      - MetCanImprove
      - MissingPolicy
    RecommendationIdList:
      type: array
      items:
        $ref: '#/components/schemas/Uuid'
    RecommendationItemList:
      type: array
      items:
        $ref: '#/components/schemas/RecommendationItem'
    RecommendationStatus:
      type: string
      enum:
      - Implemented
      - Inactive
      - NotImplemented
      - Excluded
    RecommendationTemplateList:
      type: array
      items:
        $ref: '#/components/schemas/RecommendationTemplate'
    RecommendationTemplateStatus:
      type: string
      enum:
      - Pending
      - InProgress
      - Failed
      - Success
    RecommendationTemplateStatusList:
      type: array
      items:
        $ref: '#/components/schemas/RecommendationTemplateStatus'
    RejectGroupingRecommendationEntries:
      type: array
      items:
        $ref: '#/components/schemas/RejectGroupingRecommendationEntry'
    RenderRecommendationType:
      type: string
      enum:
      - Alarm
      - Sop
      - Test
    RenderRecommendationTypeList:
      type: array
      items:
        $ref: '#/components/schemas/RenderRecommendationType'
    ResiliencyPolicies:
      type: array
      items:
        $ref: '#/components/schemas/ResiliencyPolicy'
    ResiliencyPolicyTier:
      type: string
      enum:
      - MissionCritical
      - Critical
      - Important
      - CoreServices
      - NonCritical
      - NotApplicable
    ResiliencyScoreType:
      type: string
      enum:
      - Compliance
      - Test
      - Alarm
      - Sop
    ResourceDriftList:
      type: array
      items:
        $ref: '#/components/schemas/ResourceDrift'
    ResourceErrorList:
      type: array
      items:
        $ref: '#/components/schemas/ResourceError'
    ResourceId:
      type: string
      pattern: .*
    ResourceImportStatusType:
      type: string
      enum:
      - Pending
      - InProgress
      - Failed
      - Success
    ResourceImportStrategyType:
      type: string
      enum:
      - AddOnly
      - ReplaceAll
    ResourceMappingList:
      type: array
      items:
        $ref: '#/components/schemas/ResourceMapping'
    ResourceMappingType:
      type: string
      enum:
      - CfnStack
      - Resource
      - AppRegistryApp
      - ResourceGroup
      - Terraform
      - EKS
    ResourceResolutionStatusType:
      type: string
      enum:
      - Pending
      - InProgress
      - Failed
      - Success
    ResourceSourceType:
      type: string
      enum:
      - AppTemplate
      - Discovered
    ResourceType:
      type: string
      pattern: .*
    ResourcesGroupingRecGenStatusType:
      type: string
      enum:
      - Pending
      - InProgress
      - Failed
      - Success
    RetryAfterSeconds:
      type: integer
    Row:
      type: array
      items:
        $ref: '#/components/schemas/String255'
    RowList:
      type: array
      items:
        $ref: '#/components/schemas/Row'
    S3Url:
      type: string
      pattern: ^((https://([^/]+)\.s3((-|\.)[^/]+)?\.amazonaws\.com(.cn)?)|(s3://([^/]+)))/\S{1,2000}$
      maxLength: 2000
    ScoringComponentResiliencyScores:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ScoringComponentResiliencyScore'
    Seconds:
      type: integer
      default: 0
      minimum: 0
    SopRecommendationList:
      type: array
      items:
        $ref: '#/components/schemas/SopRecommendation'
    SopServiceType:
      type: string
      enum:
      - SSM
    SortList:
      type: array
      items:
        $ref: '#/components/schemas/Sort'
    SpecReferenceId:
      type: string
      minLength: 1
      maxLength: 500
    String1024:
      type: string
      minLength: 1
      maxLength: 1024
    String128WithoutWhitespace:
      type: string
      pattern: ^\S{1,128}$
    String2048:
      type: string
      minLength: 1
      maxLength: 2048
    String255:
      type: string
      minLength: 1
      maxLength: 255
    String255List:
      type: array
      items:
        $ref: '#/components/schemas/String255'
    String500:
      type: string
      minLength: 1
      maxLength: 500
    SuggestedChangesList:
      type: array
      items:
        $ref: '#/components/schemas/EntityDescription'
    TagKey:
      type: string
      pattern: ^[^\x00-\x1f\x22]+$
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
      x-sensitive: true
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      pattern: ^[^\x00-\x1f\x22]*$
      minLength: 0
      maxLength: 256
    TemplateFormat:
      type: string
      enum:
      - CfnYaml
      - CfnJson
    TerraformSourceList:
      type: array
      items:
        $ref: '#/components/schemas/TerraformSource'
    TestRecommendationList:
      type: array
      items:
        $ref: '#/components/schemas/TestRecommendation'
    TestRisk:
      type: string
      enum:
      - Small
      - Medium
      - High
    TestType:
      type: string
      enum:
      - Software
      - Hardware
      - AZ
      - Region
    TimeStamp:
      type: string
      format: date-time
    UnsupportedResourceList:
      type: array
      items:
        $ref: '#/components/schemas/UnsupportedResource'
    UpdateRecommendationStatusRequestEntries:
      type: array
      items:
        $ref: '#/components/schemas/UpdateRecommendationStatusRequestEntry'
    Uuid:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$
