openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: robomaker
  x-aws-serviceName: robomaker
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-06-29'
  title: AWS RoboMaker
  description: |-
    This section provides documentation for the AWS RoboMaker API operations.
servers:
- description: The AWS RoboMaker regional endpoint
  url: https://robomaker.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Arn:
      type: string
      pattern: '^arn:'
      minLength: 1
      maxLength: 1224
    Boolean:
      type: boolean
      default: false
    BoxedBoolean:
      type: boolean
    ClientRequestToken:
      type: string
      pattern: ^[a-zA-Z0-9_\-=]*$
      minLength: 1
      maxLength: 64
    Command:
      type: string
      pattern: ^[a-zA-Z0-9_.\-]*$
      minLength: 1
      maxLength: 1024
    DeploymentVersion:
      type: string
      pattern: ^[0-9]*$
      minLength: 1
      maxLength: 255
    EnvironmentVariableKey:
      type: string
      pattern: ^[A-Z_][A-Z0-9_]*$
      minLength: 1
      maxLength: 1024
    EnvironmentVariableValue:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 1024
    FloorplanCount:
      type: integer
    GPUUnit:
      type: integer
      minimum: 0
      maximum: 1
    GenericInteger:
      type: integer
    GenericString:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 1024
    IamRole:
      type: string
      pattern: ^arn:aws:iam::\w+:role/
      minLength: 1
      maxLength: 255
    Id:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 1224
    ImageDigest:
      type: string
      pattern: ^[Ss][Hh][Aa]256:[0-9a-fA-F]{64}$
      minLength: 0
      maxLength: 72
    Integer:
      type: integer
      default: 0
    InteriorCountPerFloorplan:
      type: integer
    Json:
      type: string
      pattern: ^[\S\s]+$
      minLength: 1
      maxLength: 262144
    MaxConcurrency:
      type: integer
    MaxResults:
      type: integer
    Name:
      type: string
      pattern: ^[a-zA-Z0-9_\-]*$
      minLength: 1
      maxLength: 255
    NonEmptyString:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 255
    NonSystemPort:
      type: integer
      minimum: 1024
      maximum: 65535
    PaginationToken:
      type: string
      pattern: ^[a-zA-Z0-9_.\-\/+=]*$
      minLength: 1
      maxLength: 2048
    Path:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 1024
    Percentage:
      type: integer
      minimum: 1
      maximum: 100
    Port:
      type: integer
      minimum: 1
      maximum: 65535
    RenderingEngineVersionType:
      type: string
      pattern: ^1.x$
      minLength: 1
      maxLength: 4
    RepositoryUrl:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 1024
    RevisionId:
      type: string
      pattern: ^[a-zA-Z0-9_.\-]*$
      minLength: 1
      maxLength: 40
    S3Bucket:
      type: string
      pattern: ^[a-z0-9][a-z0-9.\-]*[a-z0-9]$
      minLength: 3
      maxLength: 63
    S3Etag:
      type: string
    S3Key:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 1024
    S3KeyOrPrefix:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 1024
    SimulationSoftwareSuiteVersionType:
      type: string
      pattern: ^7|9|11|Kinetic|Melodic|Dashing|Foxy$
      minLength: 0
      maxLength: 1024
    SimulationUnit:
      type: integer
      minimum: 1
      maximum: 15
    TagKey:
      type: string
      pattern: ^[a-zA-Z0-9 _.\-\/+=:]*$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^[a-zA-Z0-9 _.\-\/+=:]*$
      minLength: 0
      maxLength: 256
    TemplateName:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 255
    UnrestrictedCommand:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 1024
    Version:
      type: string
      pattern: ^(\$LATEST)|[0-9]*$
      minLength: 1
      maxLength: 255
    VersionQualifier:
      type: string
      pattern: ^ALL$
      minLength: 1
      maxLength: 255
    errorMessage:
      type: string
