openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: route53_recovery_control_config
  x-aws-serviceName: route53recoverycontrolconfig
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-11-02'
  title: AWS Route53 Recovery Control Config
  description: |-
    Recovery Control Configuration API Reference for Amazon Route 53 Application Recovery Controller
servers:
- description: The AWS Route53 Recovery Control Config regional endpoint
  url: https://route53-recovery-control-config.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
    __boolean:
      type: boolean
    __integer:
      type: integer
    __policy:
      type: string
      pattern: ^[\u0009\u000A\u000D\u0020-\u007E\u00A1-\u00FF]+$
      minLength: 2
      maxLength: 10240
    __string:
      type: string
    __stringMax36PatternS:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 36
    __stringMin0Max256PatternS:
      type: string
      pattern: ^\S+$
      minLength: 0
      maxLength: 256
    __stringMin12Max12PatternD12:
      type: string
      pattern: ^\d{12}$
      minLength: 12
      maxLength: 12
    __stringMin1Max128PatternAZaZ09:
      type: string
      pattern: ^[A-Za-z0-9:.\/_-]*$
      minLength: 1
      maxLength: 128
    __stringMin1Max256PatternAZaZ09:
      type: string
      pattern: ^[A-Za-z0-9:\/_-]*$
      minLength: 1
      maxLength: 256
    __stringMin1Max32PatternS:
      type: string
      pattern: ^\S+$
      minLength: 1
      maxLength: 32
    __stringMin1Max64PatternS:
      type: string
      pattern: ^\S+$
      minLength: 1
      maxLength: 64
    __stringMin1Max8096PatternS:
      type: string
      pattern: ^[\S]*$
      minLength: 1
      maxLength: 8096
