openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: route53_recovery_readiness
  x-aws-serviceName: route53recoveryreadiness
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2019-12-02'
  title: AWS Route53 Recovery Readiness
  description: |-
    Recovery readiness
servers:
- description: The AWS Route53 Recovery Readiness regional endpoint
  url: https://route53-recovery-readiness.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    CrossAccountAuthorization:
      type: string
    LastAuditTimestamp:
      type: string
      format: date-time
      description: <p>The time that a recovery group was last assessed for recommendations,
        in UTC ISO-8601 format.</p>
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
    Readiness:
      type: string
      enum:
      - READY
      - NOT_READY
      - UNKNOWN
      - NOT_AUTHORIZED
      description: <p>The readiness status.</p>
    ReadinessCheckTimestamp:
      type: string
      format: date-time
      description: <p>The time (UTC) that the cell was last checked for readiness,
        in ISO-8601 format.</p>
    Tags:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/__string'
      description: <p>A collection of tags associated with a resource.</p>
    __listOfCellOutput:
      type: array
      items:
        $ref: '#/components/schemas/CellOutput'
    __listOfCrossAccountAuthorization:
      type: array
      items:
        $ref: '#/components/schemas/CrossAccountAuthorization'
    __listOfListRulesOutput:
      type: array
      items:
        $ref: '#/components/schemas/ListRulesOutput'
    __listOfMessage:
      type: array
      items:
        $ref: '#/components/schemas/Message'
    __listOfReadinessCheckOutput:
      type: array
      items:
        $ref: '#/components/schemas/ReadinessCheckOutput'
    __listOfReadinessCheckSummary:
      type: array
      items:
        $ref: '#/components/schemas/ReadinessCheckSummary'
    __listOfRecommendation:
      type: array
      items:
        $ref: '#/components/schemas/Recommendation'
    __listOfRecoveryGroupOutput:
      type: array
      items:
        $ref: '#/components/schemas/RecoveryGroupOutput'
    __listOfResource:
      type: array
      items:
        $ref: '#/components/schemas/Resource'
    __listOfResourceResult:
      type: array
      items:
        $ref: '#/components/schemas/ResourceResult'
    __listOfResourceSetOutput:
      type: array
      items:
        $ref: '#/components/schemas/ResourceSetOutput'
    __listOfRuleResult:
      type: array
      items:
        $ref: '#/components/schemas/RuleResult'
    __listOf__string:
      type: array
      items:
        $ref: '#/components/schemas/__string'
    __string:
      type: string
    __stringMax256:
      type: string
      minLength: 0
      maxLength: 256
    __stringMax64:
      type: string
      minLength: 0
      maxLength: 64
    __stringMax64PatternAAZAZ09Z:
      type: string
      pattern: ^\A[a-zA-Z0-9_]+\z$
      minLength: 0
      maxLength: 64
    __stringPatternAWSAZaZ09AZaZ09:
      type: string
      pattern: ^AWS::[A-Za-z0-9]+::[A-Za-z0-9]+$
