openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: s3outposts
  x-aws-serviceName: s3outposts
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-07-25'
  title: Amazon S3 on Outposts
  description: |-
    Amazon S3 on Outposts provides access to S3 on Outposts operations.
servers:
- description: The Amazon S3 on Outposts regional endpoint
  url: https://s3-outposts.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AwsAccountId:
      type: string
      pattern: ^\d{12}$
    CidrBlock:
      type: string
    CustomerOwnedIpv4Pool:
      type: string
      pattern: ^ipv4pool-coip-([0-9a-f]{17})$
    EndpointArn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-us-gov|aws-iso|aws-iso-b):s3-outposts:[a-z\-0-9]*:[0-9]{12}:outpost/(op-[a-f0-9]{17}|ec2)/endpoint/[a-zA-Z0-9]{19}$
    EndpointId:
      type: string
      pattern: ^[a-zA-Z0-9]{19}$
    ErrorCode:
      type: string
    ErrorMessage:
      type: string
    MaxResults:
      type: integer
      default: 0
      minimum: 0
      maximum: 100
    Message:
      type: string
    NetworkInterfaceId:
      type: string
    NextToken:
      type: string
      pattern: ^[A-Za-z0-9\+\:\/\=\?\#-_]+$
      minLength: 1
      maxLength: 1024
    OutpostArn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-us-gov|aws-iso|aws-iso-b):outposts:[a-z\-0-9]*:[0-9]{12}:outpost/(op-[a-f0-9]{17}|ec2)$
    OutpostId:
      type: string
      pattern: ^(op-[a-f0-9]{17}|\d{12}|ec2)$
    S3OutpostArn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-us-gov|aws-iso|aws-iso-b):s3-outposts:[a-z\-0-9]*:[0-9]{12}:outpost/(op-[a-f0-9]{17}|\d{12})/s3$
    SecurityGroupId:
      type: string
      pattern: ^sg-([0-9a-f]{8}|[0-9a-f]{17})$
    SubnetId:
      type: string
      pattern: ^subnet-([0-9a-f]{8}|[0-9a-f]{17})$
    VpcId:
      type: string
