openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: s3tables
  x-aws-serviceName: s3tables
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: Amazon S3 Tables
  description: |-
    An Amazon S3 table represents a structured dataset consisting of tabular data in [Apache Parquet](https://parquet.apache.org/docs/) format and related metadata. This data is stored inside an S3 table as a subresource. All tables in a table bucket are stored in the [Apache Iceberg](https://iceberg.apache.org/docs/latest/) table format. Through integration with the [Amazon Web Services Glue Data Catalog](https://docs.aws.amazon.com/https:/docs.aws.amazon.com/glue/latest/dg/catalog-and-crawler.html) you can interact with your tables using Amazon Web Services analytics services, such as [Amazon Athena](https://docs.aws.amazon.com/https:/docs.aws.amazon.com/athena/) and [Amazon Redshift](https://docs.aws.amazon.com/https:/docs.aws.amazon.com/redshift/). Amazon S3 manages maintenance of your tables through automatic file compaction and snapshot management. For more information, see [Amazon S3 table buckets](https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-tables-buckets.html).
servers:
- description: The Amazon S3 Tables regional endpoint
  url: https://s3tables.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccountId:
      type: string
      pattern: ^[0-9].*$
      minLength: 12
      maxLength: 12
    ErrorMessage:
      type: string
    JobStatus:
      type: string
      enum:
      - Not_Yet_Run
      - Successful
      - Failed
      - Disabled
    ListNamespacesLimit:
      type: integer
      minimum: 1
      maximum: 1000
    ListTableBucketsLimit:
      type: integer
      minimum: 1
      maximum: 1000
    ListTablesLimit:
      type: integer
      minimum: 1
      maximum: 1000
    MaintenanceStatus:
      type: string
      enum:
      - enabled
      - disabled
    MetadataLocation:
      type: string
      minLength: 1
      maxLength: 2048
    NamespaceId:
      type: string
    NamespaceList:
      type: array
      items:
        $ref: '#/components/schemas/NamespaceName'
    NamespaceName:
      type: string
      pattern: ^[0-9a-z_]*$
      minLength: 1
      maxLength: 255
    NamespaceSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/NamespaceSummary'
    NextToken:
      type: string
      minLength: 1
      maxLength: 2048
    OpenTableFormat:
      type: string
      enum:
      - ICEBERG
    PositiveInteger:
      type: integer
      minimum: 1
      maximum: 2147483647
    ResourcePolicy:
      type: string
      minLength: 1
      maxLength: 20480
    SSEAlgorithm:
      type: string
      enum:
      - AES256
      - aws:kms
    SchemaFieldList:
      type: array
      items:
        $ref: '#/components/schemas/SchemaField'
    TableARN:
      type: string
      pattern: ^(arn:aws[-a-z0-9]*:[a-z0-9]+:[-a-z0-9]*:[0-9]{12}:bucket/[a-z0-9_-]{3,63}/table/[a-zA-Z0-9-_]{1,255})$
      minLength: 1
      maxLength: 2048
    TableBucketARN:
      type: string
      pattern: ^(arn:aws[-a-z0-9]*:[a-z0-9]+:[-a-z0-9]*:[0-9]{12}:bucket/[a-z0-9_-]{3,63})$
    TableBucketId:
      type: string
    TableBucketMaintenanceConfiguration:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TableBucketMaintenanceConfigurationValue'
    TableBucketMaintenanceSettings:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/IcebergUnreferencedFileRemovalSettings'
        description: |-
          The unreferenced file removal settings for the table bucket.
      description: |-
        Contains details about the maintenance settings for the table bucket.
    TableBucketMaintenanceType:
      type: string
      enum:
      - icebergUnreferencedFileRemoval
    TableBucketName:
      type: string
      pattern: ^[0-9a-z-]*$
      minLength: 3
      maxLength: 63
    TableBucketSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/TableBucketSummary'
    TableMaintenanceConfiguration:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TableMaintenanceConfigurationValue'
    TableMaintenanceJobStatus:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TableMaintenanceJobStatusValue'
    TableMaintenanceJobType:
      type: string
      enum:
      - icebergCompaction
      - icebergSnapshotManagement
      - icebergUnreferencedFileRemoval
    TableMaintenanceSettings:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/IcebergCompactionSettings'
        description: |-
          Contains details about the Iceberg compaction settings for the table.
      - allOf:
        - $ref: '#/components/schemas/IcebergSnapshotManagementSettings'
        description: |-
          Contains details about the Iceberg snapshot management settings for the table.
      description: |-
        Contains details about maintenance settings for the table.
    TableMaintenanceType:
      type: string
      enum:
      - icebergCompaction
      - icebergSnapshotManagement
    TableMetadata:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/IcebergMetadata'
        description: |-
          Contains details about the metadata of an Iceberg table.
      description: |-
        Contains details about the table metadata.
    TableName:
      type: string
      pattern: ^[0-9a-z_]*$
      minLength: 1
      maxLength: 255
    TableSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/TableSummary'
    TableType:
      type: string
      enum:
      - customer
      - aws
    VersionToken:
      type: string
      minLength: 1
      maxLength: 2048
    WarehouseLocation:
      type: string
      minLength: 1
      maxLength: 2048
