openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: sagemaker_edge
  x-aws-serviceName: sagemakeredge
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-09-23'
  title: Amazon Sagemaker Edge Manager
  description: |-
    SageMaker Edge Manager dataplane service for communicating with active agents.
servers:
- description: The Amazon Sagemaker Edge Manager regional endpoint
  url: https://edge.sagemaker.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    CacheTTLSeconds:
      type: string
      minLength: 1
      maxLength: 1000
    ChecksumString:
      type: string
      pattern: ^[a-z0-9](-*[a-z0-9])*$
      minLength: 1
      maxLength: 63
    ChecksumType:
      type: string
      enum:
      - SHA1
    Definitions:
      type: array
      items:
        $ref: '#/components/schemas/Definition'
    DeploymentModels:
      type: array
      items:
        $ref: '#/components/schemas/DeploymentModel'
    DeploymentStatus:
      type: string
      enum:
      - SUCCESS
      - FAIL
    DeploymentType:
      type: string
      enum:
      - Model
    DeviceFleetName:
      type: string
      pattern: ^[a-zA-Z0-9](-*_*[a-zA-Z0-9])*$
      minLength: 1
      maxLength: 63
    DeviceName:
      type: string
      pattern: ^[a-zA-Z0-9](-*_*[a-zA-Z0-9])*$
      minLength: 1
      maxLength: 63
    DeviceRegistration:
      type: string
      minLength: 1
      maxLength: 1000
    Dimension:
      type: string
      pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9\/])*$
      minLength: 1
      maxLength: 1000
    EdgeDeployments:
      type: array
      items:
        $ref: '#/components/schemas/EdgeDeployment'
    EdgeMetrics:
      type: array
      items:
        $ref: '#/components/schemas/EdgeMetric'
    EntityName:
      type: string
      pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*$
      minLength: 1
      maxLength: 63
    ErrorMessage:
      type: string
    FailureHandlingPolicy:
      type: string
      enum:
      - ROLLBACK_ON_FAILURE
      - DO_NOTHING
    Metric:
      type: string
      pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*$
      minLength: 4
      maxLength: 100
    ModelName:
      type: string
      pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*$
      minLength: 4
      maxLength: 255
    ModelState:
      type: string
      enum:
      - DEPLOY
      - UNDEPLOY
    Models:
      type: array
      items:
        $ref: '#/components/schemas/Model'
    S3Uri:
      type: string
      pattern: ^s3://([^/]+)/?(.*)$
      minLength: 0
      maxLength: 1024
    String:
      type: string
    Timestamp:
      type: string
      format: date-time
    Value:
      type: number
      format: double
    Version:
      type: string
      pattern: ^[a-zA-Z0-9\ \_\.]+$
      minLength: 1
      maxLength: 64
