openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: sagemaker_geospatial
  x-aws-serviceName: sagemakergeospatial
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-05-27'
  title: Amazon SageMaker geospatial capabilities
  description: |-
    Provides APIs for creating and managing SageMaker geospatial resources.
servers:
- description: The Amazon SageMaker geospatial capabilities regional endpoint
  url: https://sagemaker-geospatial.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AlgorithmNameCloudRemoval:
      type: string
      enum:
      - INTERPOLATION
    AlgorithmNameGeoMosaic:
      type: string
      enum:
      - NEAR
      - BILINEAR
      - CUBIC
      - CUBICSPLINE
      - LANCZOS
      - AVERAGE
      - RMS
      - MODE
      - MAX
      - MIN
      - MED
      - Q1
      - Q3
      - SUM
    AlgorithmNameResampling:
      type: string
      enum:
      - NEAR
      - BILINEAR
      - CUBIC
      - CUBICSPLINE
      - LANCZOS
      - AVERAGE
      - RMS
      - MODE
      - MAX
      - MIN
      - MED
      - Q1
      - Q3
      - SUM
    Arn:
      type: string
      minLength: 1
      maxLength: 2048
    ComparisonOperator:
      type: string
      enum:
      - EQUALS
      - NOT_EQUALS
      - STARTS_WITH
    DataCollectionArn:
      type: string
      pattern: ^arn:aws[a-z-]{0,12}:sagemaker-geospatial:[a-z0-9-]{1,25}:[0-9]{12}:raster-data-collection/(public|premium|user)/[a-z0-9]{12,}$
    DataCollectionType:
      type: string
      enum:
      - PUBLIC
      - PREMIUM
      - USER
    EarthObservationJobArn:
      type: string
      pattern: ^arn:aws[a-z-]{0,12}:sagemaker-geospatial:[a-z0-9-]{1,25}:[0-9]{12}:earth-observation-job/[a-z0-9]{12,}$
    EarthObservationJobErrorType:
      type: string
      enum:
      - CLIENT_ERROR
      - SERVER_ERROR
    EarthObservationJobExportStatus:
      type: string
      enum:
      - IN_PROGRESS
      - SUCCEEDED
      - FAILED
    EarthObservationJobStatus:
      type: string
      enum:
      - INITIALIZING
      - IN_PROGRESS
      - STOPPING
      - COMPLETED
      - STOPPED
      - FAILED
      - DELETING
      - DELETED
    ExecutionRoleArn:
      type: string
      pattern: ^arn:(aws[a-z-]*):iam::([0-9]{12}):role/[a-zA-Z0-9+=,.@_/-]+$
      minLength: 20
      maxLength: 2048
    ExportErrorType:
      type: string
      enum:
      - CLIENT_ERROR
      - SERVER_ERROR
    GroupBy:
      type: string
      enum:
      - ALL
      - YEARLY
    KmsKey:
      type: string
      minLength: 0
      maxLength: 2048
    LogicalOperator:
      type: string
      enum:
      - AND
    NextToken:
      type: string
      maxLength: 8192
    OutputType:
      type: string
      enum:
      - INT32
      - FLOAT32
      - INT16
      - FLOAT64
      - UINT16
    PredefinedResolution:
      type: string
      enum:
      - HIGHEST
      - LOWEST
      - AVERAGE
    S3Uri:
      type: string
      pattern: ^s3://([^/]+)/?(.*)$
    SortOrder:
      type: string
      enum:
      - ASCENDING
      - DESCENDING
    TargetOptions:
      type: string
      enum:
      - INPUT
      - OUTPUT
    TemporalStatistics:
      type: string
      enum:
      - MEAN
      - MEDIAN
      - STANDARD_DEVIATION
    Unit:
      type: string
      enum:
      - METERS
    VectorEnrichmentJobArn:
      type: string
      pattern: ^arn:aws[a-z-]{0,12}:sagemaker-geospatial:[a-z0-9-]{1,25}:[0-9]{12}:vector-enrichment-job/[a-z0-9]{12,}$
    VectorEnrichmentJobDocumentType:
      type: string
      enum:
      - CSV
    VectorEnrichmentJobErrorType:
      type: string
      enum:
      - CLIENT_ERROR
      - SERVER_ERROR
    VectorEnrichmentJobExportErrorType:
      type: string
      enum:
      - CLIENT_ERROR
      - SERVER_ERROR
    VectorEnrichmentJobExportStatus:
      type: string
      enum:
      - IN_PROGRESS
      - SUCCEEDED
      - FAILED
    VectorEnrichmentJobStatus:
      type: string
      enum:
      - INITIALIZING
      - IN_PROGRESS
      - STOPPING
      - STOPPED
      - COMPLETED
      - FAILED
      - DELETING
      - DELETED
    VectorEnrichmentJobType:
      type: string
      enum:
      - REVERSE_GEOCODING
      - MAP_MATCHING
    ZonalStatistics:
      type: string
      enum:
      - MEAN
      - MEDIAN
      - STANDARD_DEVIATION
      - MAX
      - MIN
      - SUM
