openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: sagemaker_metrics
  x-aws-serviceName: sagemakermetrics
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2022-09-30'
  title: Amazon SageMaker Metrics Service
  description: |-
    Contains all data plane API operations and data types for Amazon SageMaker Metrics. Use these APIs to put and retrieve (get) features related to your training run.

      * [BatchPutMetrics](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_metrics_BatchPutMetrics.html)
servers:
- description: The Amazon SageMaker Metrics Service regional endpoint
  url: https://metrics.sagemaker.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ExperimentEntityName:
      type: string
      pattern: ^[a-z0-9](-*[a-z0-9]){0,119}$
      minLength: 1
      maxLength: 120
    Integer:
      type: integer
    Message:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 2048
    MetricName:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 255
    SageMakerResourceArn:
      type: string
      pattern: ^arn:aws[a-z\-]*:sagemaker:[a-z0-9\-]*:[0-9]{12}:[a-z\-].*/
      minLength: 0
      maxLength: 2048
    Step:
      type: integer
      minimum: 0
