openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: sagemaker_metrics
  x-aws-serviceName: sagemakermetrics
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-07'
  version: '2022-09-30'
  title: Amazon SageMaker Metrics Service
  description: |-
    Contains all data plane API operations and data types for Amazon SageMaker Metrics. Use these APIs to put and retrieve (get) features related to your training run.

      * [BatchPutMetrics](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_metrics_BatchPutMetrics.html)
servers:
- description: The Amazon SageMaker Metrics Service regional endpoint
  url: https://metrics.sagemaker.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths:
  /BatchGetMetrics:
    post:
      operationId: BatchGetMetrics
      description: |-
        Used to retrieve training metrics from SageMaker.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                MetricQueries:
                  $ref: '#/components/schemas/MetricQueryList'
      responses:
        '200': {}
  /BatchPutMetrics:
    put:
      operationId: BatchPutMetrics
      description: |-
        Used to ingest training metrics into SageMaker. These metrics can be visualized in SageMaker Studio.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                TrialComponentName:
                  $ref: '#/components/schemas/ExperimentEntityName'
                MetricData:
                  $ref: '#/components/schemas/RawMetricDataList'
      responses:
        '200': {}
components:
  schemas:
    BatchGetMetricsRequest:
      type: object
      properties:
        MetricQueries:
          allOf:
          - $ref: '#/components/schemas/MetricQueryList'
          description: Queries made to retrieve training metrics from SageMaker.
      required:
      - MetricQueries
    BatchGetMetricsResponse:
      type: object
      properties:
        MetricQueryResults:
          allOf:
          - $ref: '#/components/schemas/MetricQueryResultList'
          description: The results of a query to retrieve training metrics from SageMaker.
    BatchPutMetricsError:
      type: object
      properties:
        Code:
          allOf:
          - $ref: '#/components/schemas/PutMetricsErrorCode'
          description: "The error code of an error that occured when attempting to\
            \ put metrics.\n\n  * `METRIC_LIMIT_EXCEEDED`: The maximum amount of metrics\
            \ per resource is exceeded.\n\n  * `INTERNAL_ERROR`: An internal error\
            \ occured.\n\n  * `VALIDATION_ERROR`: The metric data failed validation.\n\
            \n  * `CONFLICT_ERROR`: Multiple requests attempted to modify the same\
            \ data simultaneously."
        MetricIndex:
          allOf:
          - $ref: '#/components/schemas/Integer'
          description: An index that corresponds to the metric in the request.
      description: An error that occured when putting the metric data.
    BatchPutMetricsErrorList:
      type: array
      items:
        $ref: '#/components/schemas/BatchPutMetricsError'
    BatchPutMetricsRequest:
      type: object
      properties:
        TrialComponentName:
          allOf:
          - $ref: '#/components/schemas/ExperimentEntityName'
          description: The name of the Trial Component to associate with the metrics.
            The Trial Component name must be entirely lowercase.
        MetricData:
          allOf:
          - $ref: '#/components/schemas/RawMetricDataList'
          description: A list of raw metric values to put.
      required:
      - TrialComponentName
      - MetricData
    BatchPutMetricsResponse:
      type: object
      properties:
        Errors:
          allOf:
          - $ref: '#/components/schemas/BatchPutMetricsErrorList'
          description: Lists any errors that occur when inserting metric data.
    Double:
      type: number
      format: double
    ExperimentEntityName:
      type: string
      pattern: ^[a-z0-9](-*[a-z0-9]){0,119}$
      minLength: 1
      maxLength: 120
    Integer:
      type: integer
    Long:
      type: integer
      format: int64
    Message:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 2048
    MetricName:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 255
    MetricQuery:
      type: object
      properties:
        MetricName:
          allOf:
          - $ref: '#/components/schemas/MetricName'
          description: The name of the metric to retrieve.
        ResourceArn:
          allOf:
          - $ref: '#/components/schemas/SageMakerResourceArn'
          description: The ARN of the SageMaker resource to retrieve metrics for.
        MetricStat:
          allOf:
          - $ref: '#/components/schemas/MetricStatistic'
          description: The metrics stat type of metrics to retrieve.
        Period:
          allOf:
          - $ref: '#/components/schemas/Period'
          description: The time period of metrics to retrieve.
        XAxisType:
          allOf:
          - $ref: '#/components/schemas/XAxisType'
          description: The x-axis type of metrics to retrieve.
        Start:
          allOf:
          - $ref: '#/components/schemas/Long'
          description: The start time of metrics to retrieve.
        End:
          allOf:
          - $ref: '#/components/schemas/Long'
          description: The end time of metrics to retrieve.
      required:
      - MetricName
      - ResourceArn
      - MetricStat
      - Period
      - XAxisType
      description: Specifies a query to retrieve training metrics from SageMaker.
    MetricQueryList:
      type: array
      items:
        $ref: '#/components/schemas/MetricQuery'
    MetricQueryResult:
      type: object
      properties:
        Status:
          allOf:
          - $ref: '#/components/schemas/MetricQueryResultStatus'
          description: The status of the metric query.
        Message:
          allOf:
          - $ref: '#/components/schemas/Message'
          description: A message describing the status of the metric query.
        XAxisValues:
          allOf:
          - $ref: '#/components/schemas/XAxisValues'
          description: The values for the x-axis of the metrics.
        MetricValues:
          allOf:
          - $ref: '#/components/schemas/MetricValues'
          description: The metric values retrieved by the query.
      required:
      - Status
      - XAxisValues
      - MetricValues
      description: The result of a query to retrieve training metrics from SageMaker.
    MetricQueryResultList:
      type: array
      items:
        $ref: '#/components/schemas/MetricQueryResult'
    MetricQueryResultStatus:
      type: string
      enum:
      - Complete
      - Truncated
      - InternalError
      - ValidationError
    MetricStatistic:
      type: string
      enum:
      - Min
      - Max
      - Avg
      - Count
      - StdDev
      - Last
    MetricValues:
      type: array
      items:
        $ref: '#/components/schemas/Double'
    Period:
      type: string
      enum:
      - OneMinute
      - FiveMinute
      - OneHour
      - IterationNumber
    PutMetricsErrorCode:
      type: string
      enum:
      - METRIC_LIMIT_EXCEEDED
      - INTERNAL_ERROR
      - VALIDATION_ERROR
      - CONFLICT_ERROR
    RawMetricData:
      type: object
      properties:
        MetricName:
          allOf:
          - $ref: '#/components/schemas/MetricName'
          description: The name of the metric.
        Timestamp:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          description: The time that the metric was recorded.
        Step:
          allOf:
          - $ref: '#/components/schemas/Step'
          description: The metric step (epoch).
        Value:
          allOf:
          - $ref: '#/components/schemas/Double'
          description: The metric value.
      required:
      - MetricName
      - Timestamp
      - Value
      description: The raw metric data to associate with the resource.
    RawMetricDataList:
      type: array
      items:
        $ref: '#/components/schemas/RawMetricData'
    SageMakerResourceArn:
      type: string
      pattern: ^arn:aws[a-z\-]*:sagemaker:[a-z0-9\-]*:[0-9]{12}:[a-z\-].*/
      minLength: 0
      maxLength: 2048
    Step:
      type: integer
      minimum: 0
    Timestamp:
      type: string
      format: date-time
    XAxisType:
      type: string
      enum:
      - IterationNumber
      - Timestamp
    XAxisValues:
      type: array
      items:
        $ref: '#/components/schemas/Long'
