openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: sagemaker_runtime
  x-aws-serviceName: sagemakerruntime
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-05-13'
  title: Amazon SageMaker Runtime
  description: |-
    The Amazon SageMaker runtime API.
servers:
- description: The Amazon SageMaker Runtime regional endpoint
  url: https://runtime.sagemaker.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    BodyBlob:
      type: string
      format: byte
      minLength: 0
      maxLength: 6291456
      x-sensitive: true
    CustomAttributesHeader:
      type: string
      pattern: ^\p{ASCII}*$
      minLength: 0
      maxLength: 1024
    EnableExplanationsHeader:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 64
    EndpointName:
      type: string
      pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*$
      minLength: 0
      maxLength: 63
    ErrorCode:
      type: string
    Header:
      type: string
      pattern: ^\p{ASCII}*$
      minLength: 0
      maxLength: 1024
    InferenceComponentHeader:
      type: string
      pattern: ^[a-zA-Z0-9]([\-a-zA-Z0-9]*[a-zA-Z0-9])?$
      minLength: 0
      maxLength: 63
    InferenceId:
      type: string
      pattern: ^\A\S[\p{Print}]*\z$
      minLength: 1
      maxLength: 64
    InputLocationHeader:
      type: string
      pattern: ^(https|s3)://([^/]+)/?(.*)$
      minLength: 1
      maxLength: 1024
    InvocationTimeoutSecondsHeader:
      type: integer
      minimum: 1
      maximum: 3600
    LogStreamArn:
      type: string
    Message:
      type: string
      minLength: 0
      maxLength: 2048
    NewSessionResponseHeader:
      type: string
      pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*;\sExpires=[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$
      minLength: 0
      maxLength: 256
    PartBlob:
      type: string
      format: byte
      x-sensitive: true
    RequestTTLSecondsHeader:
      type: integer
      minimum: 60
      maximum: 21600
    ResponseStream:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/PayloadPart'
        description: |-
          A wrapper for pieces of the payload that's returned in response to a streaming inference request. A streaming inference response consists of one or more payload parts.
      - allOf:
        - $ref: '#/components/schemas/ModelStreamError'
        description: "An error occurred while streaming the response body. This error\
          \ can have the following error codes:\n\nModelInvocationTimeExceeded\n\n\
          \    \n\nThe model failed to finish sending the response within the timeout\
          \ period allowed by Amazon SageMaker.\n\nStreamBroken\n\n    \n\nThe Transmission\
          \ Control Protocol (TCP) connection between the client and the model was\
          \ reset or closed."
      - allOf:
        - $ref: '#/components/schemas/InternalStreamFailure'
        description: |-
          The stream processing failed because of an unknown error, exception or failure. Try your request again.
      description: |-
        A stream of payload parts. Each part contains a portion of the response for a streaming inference request.
    SessionIdHeader:
      type: string
      pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*$
      minLength: 0
      maxLength: 256
    SessionIdOrNewSessionConstantHeader:
      type: string
      pattern: ^(NEW_SESSION)$|^[a-zA-Z0-9](-*[a-zA-Z0-9])*$
      minLength: 0
      maxLength: 256
    StatusCode:
      type: integer
    TargetContainerHostnameHeader:
      type: string
      pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*$
      minLength: 0
      maxLength: 63
    TargetModelHeader:
      type: string
      pattern: ^\A\S[\p{Print}]*\z$
      minLength: 1
      maxLength: 1024
    TargetVariantHeader:
      type: string
      pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*$
      minLength: 0
      maxLength: 63
