openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: savingsplans
  x-aws-serviceName: savingsplans
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2019-06-28'
  title: AWS Savings Plans
  description: |-
    Savings Plans are a pricing model that offer significant savings on Amazon Web Services usage (for example, on Amazon EC2 instances). You commit to a consistent amount of usage per hour, in the specified currency, for a term of one or three years, and receive a lower price for that usage. For more information, see the [Amazon Web Services Savings Plans User Guide](https://docs.aws.amazon.com/savingsplans/latest/userguide/).
servers:
- description: The AWS Savings Plans regional endpoint
  url: https://savingsplans.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Amount:
      type: string
    ClientToken:
      type: string
    CurrencyCode:
      type: string
      enum:
      - CNY
      - USD
    CurrencyList:
      type: array
      items:
        $ref: '#/components/schemas/CurrencyCode'
    DateTime:
      type: string
      format: date-time
    DurationsList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlansDuration'
    EC2InstanceFamily:
      type: string
    FilterValuesList:
      type: array
      items:
        $ref: '#/components/schemas/JsonSafeFilterValueString'
    JsonSafeFilterValueString:
      type: string
      pattern: ^[a-zA-Z0-9_ \/.\:\-\(\)]+$
    ListOfStrings:
      type: array
      items:
        $ref: '#/components/schemas/String'
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
    PageSize:
      type: integer
      default: 0
      minimum: 0
      maximum: 1000
    PaginationToken:
      type: string
      pattern: ^[A-Za-z0-9/=\+]+$
      minLength: 0
      maxLength: 1024
    Region:
      type: string
    SavingsPlanArn:
      type: string
      pattern: ^arn:aws:[a-z]+:([a-z]{2}-[a-z]+-\d{1}|):(\d{12}):savingsplan\/([0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})$
    SavingsPlanArnList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanArn'
    SavingsPlanDescription:
      type: string
      pattern: ^[a-zA-Z0-9_\- ]+$
    SavingsPlanDescriptionsList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanDescription'
    SavingsPlanFilterList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanFilter'
    SavingsPlanId:
      type: string
    SavingsPlanIdList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanId'
    SavingsPlanList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlan'
    SavingsPlanOfferingFilterAttribute:
      type: string
      enum:
      - region
      - instanceFamily
    SavingsPlanOfferingFiltersList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanOfferingFilterElement'
    SavingsPlanOfferingId:
      type: string
    SavingsPlanOfferingPropertyKey:
      type: string
      enum:
      - region
      - instanceFamily
    SavingsPlanOfferingPropertyList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanOfferingProperty'
    SavingsPlanOfferingRateFiltersList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanOfferingRateFilterElement'
    SavingsPlanOfferingRatePropertyList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanOfferingRateProperty'
    SavingsPlanOfferingRatesList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanOfferingRate'
    SavingsPlanOfferingsList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanOffering'
    SavingsPlanOperation:
      type: string
      pattern: ^[a-zA-Z0-9_ \/.:-]*$
      minLength: 0
      maxLength: 255
    SavingsPlanOperationList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanOperation'
    SavingsPlanPaymentOption:
      type: string
      enum:
      - All Upfront
      - Partial Upfront
      - No Upfront
    SavingsPlanPaymentOptionList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanPaymentOption'
    SavingsPlanProductType:
      type: string
      enum:
      - EC2
      - Fargate
      - Lambda
      - SageMaker
    SavingsPlanProductTypeList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanProductType'
    SavingsPlanRateFilterAttribute:
      type: string
      enum:
      - region
      - instanceFamily
      - instanceType
      - productDescription
      - tenancy
      - productId
    SavingsPlanRateFilterList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanRateFilter'
    SavingsPlanRateFilterName:
      type: string
      enum:
      - region
      - instanceType
      - productDescription
      - tenancy
      - productType
      - serviceCode
      - usageType
      - operation
    SavingsPlanRateList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanRate'
    SavingsPlanRateOperation:
      type: string
      pattern: ^[a-zA-Z0-9_ \/.:-]*$
      minLength: 0
      maxLength: 255
    SavingsPlanRateOperationList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanRateOperation'
    SavingsPlanRatePricePerUnit:
      type: string
    SavingsPlanRatePropertyKey:
      type: string
      enum:
      - region
      - instanceType
      - instanceFamily
      - productDescription
      - tenancy
    SavingsPlanRatePropertyList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanRateProperty'
    SavingsPlanRateServiceCode:
      type: string
      enum:
      - AmazonEC2
      - AmazonECS
      - AmazonEKS
      - AWSLambda
      - AmazonSageMaker
    SavingsPlanRateServiceCodeList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanRateServiceCode'
    SavingsPlanRateUnit:
      type: string
      enum:
      - Hrs
      - Lambda-GB-Second
      - Request
    SavingsPlanRateUsageType:
      type: string
      pattern: ^[a-zA-Z0-9_ \/.:-]+$
      minLength: 0
      maxLength: 255
    SavingsPlanRateUsageTypeList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanRateUsageType'
    SavingsPlanServiceCode:
      type: string
      pattern: ^[a-zA-Z]+$
      minLength: 0
      maxLength: 255
    SavingsPlanServiceCodeList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanServiceCode'
    SavingsPlanState:
      type: string
      enum:
      - payment-pending
      - payment-failed
      - active
      - retired
      - queued
      - queued-deleted
      - pending-return
      - returned
    SavingsPlanStateList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanState'
    SavingsPlanType:
      type: string
      enum:
      - Compute
      - EC2Instance
      - SageMaker
    SavingsPlanTypeList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanType'
    SavingsPlanUsageType:
      type: string
      pattern: ^[a-zA-Z0-9_ \/.:-]+$
      minLength: 0
      maxLength: 255
    SavingsPlanUsageTypeList:
      type: array
      items:
        $ref: '#/components/schemas/SavingsPlanUsageType'
    SavingsPlansDuration:
      type: integer
      format: int64
      default: 0
      minimum: 0
    SavingsPlansFilterName:
      type: string
      enum:
      - region
      - ec2-instance-family
      - commitment
      - upfront
      - term
      - savings-plan-type
      - payment-option
      - start
      - end
    String:
      type: string
    TagKey:
      type: string
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
    TermDurationInSeconds:
      type: integer
      format: int64
      default: 0
    UUID:
      type: string
      pattern: ^[a-f0-9]+(-[a-f0-9]+)*$
    UUIDs:
      type: array
      items:
        $ref: '#/components/schemas/UUID'
