openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: scheduler
  x-aws-serviceName: scheduler
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2021-06-30'
  title: Amazon EventBridge Scheduler
  description: |-
    Amazon EventBridge Scheduler is a serverless scheduler that allows you to create, run, and manage tasks from one central, managed service. EventBridge Scheduler delivers your tasks reliably, with built-in mechanisms that adjust your schedules based on the availability of downstream targets. The following reference lists the available API actions, and data types for EventBridge Scheduler.
servers:
- description: The Amazon EventBridge Scheduler regional endpoint
  url: https://scheduler.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ActionAfterCompletion:
      type: string
      enum:
      - NONE
      - DELETE
    AssignPublicIp:
      type: string
      enum:
      - ENABLED
      - DISABLED
    CapacityProvider:
      type: string
      minLength: 1
      maxLength: 255
    CapacityProviderStrategyItemBase:
      type: integer
      default: 0
      minimum: 0
      maximum: 100000
    CapacityProviderStrategyItemWeight:
      type: integer
      default: 0
      minimum: 0
      maximum: 1000
    ClientToken:
      type: string
      pattern: ^[a-zA-Z0-9-_]+$
      minLength: 1
      maxLength: 64
    Description:
      type: string
      minLength: 0
      maxLength: 512
    DetailType:
      type: string
      minLength: 1
      maxLength: 128
    EnableECSManagedTags:
      type: boolean
    EnableExecuteCommand:
      type: boolean
    FlexibleTimeWindowMode:
      type: string
      enum:
      - 'OFF'
      - FLEXIBLE
    Group:
      type: string
      minLength: 1
      maxLength: 255
    KmsKeyArn:
      type: string
      pattern: ^arn:aws(-[a-z]+)?:kms:[a-z0-9\-]+:\d{12}:(key|alias)\/[0-9a-zA-Z-_]*$
      minLength: 1
      maxLength: 2048
    LaunchType:
      type: string
      enum:
      - EC2
      - FARGATE
      - EXTERNAL
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    MaximumEventAgeInSeconds:
      type: integer
      minimum: 60
      maximum: 86400
    MaximumRetryAttempts:
      type: integer
      minimum: 0
      maximum: 185
    MaximumWindowInMinutes:
      type: integer
      minimum: 1
      maximum: 1440
    MessageGroupId:
      type: string
      minLength: 1
      maxLength: 128
    Name:
      type: string
      pattern: ^[0-9a-zA-Z-_.]+$
      minLength: 1
      maxLength: 64
    NamePrefix:
      type: string
      pattern: ^[0-9a-zA-Z-_.]+$
      minLength: 1
      maxLength: 64
    NextToken:
      type: string
      minLength: 1
      maxLength: 2048
    PlacementConstraintExpression:
      type: string
      maxLength: 2000
    PlacementConstraintType:
      type: string
      enum:
      - distinctInstance
      - memberOf
    PlacementStrategyField:
      type: string
      maxLength: 255
    PlacementStrategyType:
      type: string
      enum:
      - random
      - spread
      - binpack
    PlatformVersion:
      type: string
      minLength: 1
      maxLength: 64
    PropagateTags:
      type: string
      enum:
      - TASK_DEFINITION
    ReferenceId:
      type: string
      maxLength: 1024
    ResourceArn:
      type: string
      minLength: 1
      maxLength: 1600
    RoleArn:
      type: string
      pattern: ^arn:aws(-[a-z]+)?:iam::\d{12}:role\/[\w+=,.@\/-]+$
      minLength: 1
      maxLength: 1600
    SageMakerPipelineParameterName:
      type: string
      pattern: ^[A-Za-z0-9\-_]*$
      minLength: 1
      maxLength: 256
    SageMakerPipelineParameterValue:
      type: string
      minLength: 1
      maxLength: 1024
    ScheduleArn:
      type: string
      pattern: ^arn:aws(-[a-z]+)?:scheduler:[a-z0-9\-]+:\d{12}:schedule\/[0-9a-zA-Z-_.]+\/[0-9a-zA-Z-_.]+$
      minLength: 1
      maxLength: 1224
    ScheduleExpression:
      type: string
      minLength: 1
      maxLength: 256
    ScheduleExpressionTimezone:
      type: string
      minLength: 1
      maxLength: 50
    ScheduleGroupArn:
      type: string
      pattern: ^arn:aws(-[a-z]+)?:scheduler:[a-z0-9\-]+:\d{12}:schedule-group\/[0-9a-zA-Z-_.]+$
      minLength: 1
      maxLength: 1224
    ScheduleGroupName:
      type: string
      pattern: ^[0-9a-zA-Z-_.]+$
      minLength: 1
      maxLength: 64
    ScheduleGroupNamePrefix:
      type: string
      pattern: ^[0-9a-zA-Z-_.]+$
      minLength: 1
      maxLength: 64
    ScheduleGroupState:
      type: string
      enum:
      - ACTIVE
      - DELETING
    ScheduleState:
      type: string
      enum:
      - ENABLED
      - DISABLED
    SecurityGroup:
      type: string
      minLength: 1
      maxLength: 1000
    Source:
      type: string
      pattern: ^(?=[/\.\-_A-Za-z0-9]+)((?!aws\.).*)|(\$(\.[\w_-]+(\[(\d+|\*)\])*)*)$
      minLength: 1
      maxLength: 256
    Subnet:
      type: string
      minLength: 1
      maxLength: 1000
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagResourceArn:
      type: string
      pattern: ^arn:aws(-[a-z]+)?:scheduler:[a-z0-9\-]+:\d{12}:schedule-group\/[0-9a-zA-Z-_.]+$
      minLength: 1
      maxLength: 1011
    TagValue:
      type: string
      minLength: 1
      maxLength: 256
    TargetArn:
      type: string
      minLength: 1
      maxLength: 1600
    TargetInput:
      type: string
      minLength: 1
    TargetPartitionKey:
      type: string
      minLength: 1
      maxLength: 256
    TaskCount:
      type: integer
      minimum: 1
      maximum: 10
    TaskDefinitionArn:
      type: string
      minLength: 1
      maxLength: 1600
