openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: schemas
  x-aws-serviceName: schemas
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2019-12-02'
  title: Schemas
  description: |-
    Amazon EventBridge Schema Registry
servers:
- description: The Schemas regional endpoint
  url: https://schemas.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Body:
      type: string
      format: byte
    CodeGenerationStatus:
      type: string
      enum:
      - CREATE_IN_PROGRESS
      - CREATE_COMPLETE
      - CREATE_FAILED
    DiscovererState:
      type: string
      enum:
      - STARTED
      - STOPPED
    GetDiscoveredSchemaVersionItemInput:
      type: string
      minLength: 1
      maxLength: 100000
    SynthesizedJson__string:
      type: string
    Tags:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/__string'
      description: <p>Key-value pairs associated with a resource.</p>
    Type:
      type: string
      enum:
      - OpenApi3
      - JSONSchemaDraft4
    __boolean:
      type: boolean
    __integer:
      type: integer
    __listOfDiscovererSummary:
      type: array
      items:
        $ref: '#/components/schemas/DiscovererSummary'
    __listOfGetDiscoveredSchemaVersionItemInput:
      type: array
      items:
        $ref: '#/components/schemas/GetDiscoveredSchemaVersionItemInput'
    __listOfRegistrySummary:
      type: array
      items:
        $ref: '#/components/schemas/RegistrySummary'
    __listOfSchemaSummary:
      type: array
      items:
        $ref: '#/components/schemas/SchemaSummary'
    __listOfSchemaVersionSummary:
      type: array
      items:
        $ref: '#/components/schemas/SchemaVersionSummary'
    __listOfSearchSchemaSummary:
      type: array
      items:
        $ref: '#/components/schemas/SearchSchemaSummary'
    __listOfSearchSchemaVersionSummary:
      type: array
      items:
        $ref: '#/components/schemas/SearchSchemaVersionSummary'
    __listOf__string:
      type: array
      items:
        $ref: '#/components/schemas/__string'
    __long:
      type: integer
      format: int64
    __string:
      type: string
    __stringMin0Max256:
      type: string
      minLength: 0
      maxLength: 256
    __stringMin0Max36:
      type: string
      minLength: 0
      maxLength: 36
    __stringMin1Max100000:
      type: string
      minLength: 1
      maxLength: 100000
    __stringMin20Max1600:
      type: string
      minLength: 20
      maxLength: 1600
    __timestampIso8601:
      type: string
      format: date-time
