openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: securitylake
  x-aws-serviceName: securitylake
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: Amazon Security Lake
  description: |-
    Amazon Security Lake is a fully managed security data lake service. You can use Security Lake to automatically centralize security data from cloud, on-premises, and custom sources into a data lake that's stored in your Amazon Web Services account. Amazon Web Services Organizations is an account management service that lets you consolidate multiple Amazon Web Services accounts into an organization that you create and centrally manage. With Organizations, you can create member accounts and invite existing accounts to join your organization. Security Lake helps you analyze security data for a more complete understanding of your security posture across the entire organization. It can also help you improve the protection of your workloads, applications, and data.

    The data lake is backed by Amazon Simple Storage Service (Amazon S3) buckets, and you retain ownership over your data.

    Amazon Security Lake integrates with CloudTrail, a service that provides a record of actions taken by a user, role, or an Amazon Web Services service. In Security Lake, CloudTrail captures API calls for Security Lake as events. The calls captured include calls from the Security Lake console and code calls to the Security Lake API operations. If you create a trail, you can enable continuous delivery of CloudTrail events to an Amazon S3 bucket, including events for Security Lake. If you don't configure a trail, you can still view the most recent events in the CloudTrail console in Event history. Using the information collected by CloudTrail you can determine the request that was made to Security Lake, the IP address from which the request was made, who made the request, when it was made, and additional details. To learn more about Security Lake information in CloudTrail, see the [Amazon Security Lake User Guide](https://docs.aws.amazon.com/security-lake/latest/userguide/securitylake-cloudtrail.html).

    Security Lake automates the collection of security-related log and event data from integrated Amazon Web Services services and third-party services. It also helps you manage the lifecycle of data with customizable retention and replication settings. Security Lake converts ingested data into Apache Parquet format and a standard open-source schema called the Open Cybersecurity Schema Framework (OCSF).

    Other Amazon Web Services services and third-party services can subscribe to the data that's stored in Security Lake for incident response and security data analytics.
servers:
- description: The Amazon Security Lake regional endpoint
  url: https://securitylake.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccessType:
      type: string
      enum:
      - LAKEFORMATION
      - S3
    AccessTypeList:
      type: array
      items:
        $ref: '#/components/schemas/AccessType'
    AccountList:
      type: array
      items:
        $ref: '#/components/schemas/AwsAccountId'
    AmazonResourceName:
      type: string
      pattern: ^arn:(aws|aws-us-gov|aws-cn):securitylake:[A-Za-z0-9_/.\-]{0,63}:[A-Za-z0-9_/.\-]{0,63}:[A-Za-z0-9][A-Za-z0-9_/.\-]{0,127}$
      minLength: 1
      maxLength: 1011
    AwsAccountId:
      type: string
      pattern: ^[0-9]{12}$
      minLength: 12
      maxLength: 12
    AwsLogSourceConfigurationList:
      type: array
      items:
        $ref: '#/components/schemas/AwsLogSourceConfiguration'
    AwsLogSourceName:
      type: string
      enum:
      - ROUTE53
      - VPC_FLOW
      - SH_FINDINGS
      - CLOUD_TRAIL_MGMT
      - LAMBDA_EXECUTION
      - S3_DATA
      - EKS_AUDIT
      - WAF
    AwsLogSourceResourceList:
      type: array
      items:
        $ref: '#/components/schemas/AwsLogSourceResource'
    AwsLogSourceVersion:
      type: string
      pattern: ^(latest|[0-9]\.[0-9])$
    AwsPrincipal:
      type: string
      pattern: ^([0-9]{12}|[a-z0-9\.\-]*\.(amazonaws|amazon)\.com)$
    CustomLogSourceName:
      type: string
      pattern: ^[\w\-\_\:\.]*$
      minLength: 1
      maxLength: 64
    CustomLogSourceVersion:
      type: string
      pattern: ^[A-Za-z0-9\-\.\_]*$
      minLength: 1
      maxLength: 32
    DataLakeAutoEnableNewAccountConfigurationList:
      type: array
      items:
        $ref: '#/components/schemas/DataLakeAutoEnableNewAccountConfiguration'
    DataLakeConfigurationList:
      type: array
      items:
        $ref: '#/components/schemas/DataLakeConfiguration'
    DataLakeExceptionList:
      type: array
      items:
        $ref: '#/components/schemas/DataLakeException'
    DataLakeLifecycleTransitionList:
      type: array
      items:
        $ref: '#/components/schemas/DataLakeLifecycleTransition'
    DataLakeResourceList:
      type: array
      items:
        $ref: '#/components/schemas/DataLakeResource'
    DataLakeSourceList:
      type: array
      items:
        $ref: '#/components/schemas/DataLakeSource'
    DataLakeSourceStatusList:
      type: array
      items:
        $ref: '#/components/schemas/DataLakeSourceStatus'
    DataLakeStatus:
      type: string
      enum:
      - INITIALIZED
      - PENDING
      - COMPLETED
      - FAILED
    DataLakeStorageClass:
      type: string
    DescriptionString:
      type: string
      pattern: ^[\\\w\s\-_:/,.@=+]*$
    ExternalId:
      type: string
      pattern: ^[\w+=,.@:\/-]*$
      minLength: 2
      maxLength: 1224
    HttpMethod:
      type: string
      enum:
      - POST
      - PUT
    LogSourceList:
      type: array
      items:
        $ref: '#/components/schemas/LogSource'
    LogSourceResource:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/AwsLogSourceResource'
        description: |-
          Amazon Security Lake supports log and event collection for natively supported Amazon Web Services services. For more information, see the [Amazon Security Lake User Guide](https://docs.aws.amazon.com/security-lake/latest/userguide/internal-sources.html).
      - allOf:
        - $ref: '#/components/schemas/CustomLogSourceResource'
        description: |-
          Amazon Security Lake supports custom source types. For more information, see the [Amazon Security Lake User Guide](https://docs.aws.amazon.com/security-lake/latest/userguide/custom-sources.html).
      description: |-
        The supported source types from which logs and events are collected in Amazon Security Lake. For a list of supported Amazon Web Services services, see the [Amazon Security Lake User Guide](https://docs.aws.amazon.com/security-lake/latest/userguide/internal-sources.html).
    LogSourceResourceList:
      type: array
      items:
        $ref: '#/components/schemas/LogSourceResource'
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    NextToken:
      type: string
      maxLength: 2048
    NotificationConfiguration:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/SqsNotificationConfiguration'
        description: |-
          The configurations for SQS subscriber notification.
      - allOf:
        - $ref: '#/components/schemas/HttpsNotificationConfiguration'
        description: |-
          The configurations used for HTTPS subscriber notification.
      description: |-
        Specify the configurations you want to use for subscriber notification to notify the subscriber when new data is written to the data lake for sources that the subscriber consumes in Security Lake.
    OcsfEventClass:
      type: string
      pattern: ^[A-Z\_0-9]*$
    OcsfEventClassList:
      type: array
      items:
        $ref: '#/components/schemas/OcsfEventClass'
    Region:
      type: string
      pattern: ^(us(-gov)?|af|ap|ca|eu|me|sa)-(central|north|(north(?:east|west))|south|south(?:east|west)|east|west)-\d+$
    RegionList:
      type: array
      items:
        $ref: '#/components/schemas/Region'
    ResourceShareArn:
      type: string
    ResourceShareName:
      type: string
      pattern: ^LakeFormation(?:-V[0-9]+)-([a-zA-Z0-9]+)-([\\\w\-_:/.@=+]*)$
    RoleArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$
    S3BucketArn:
      type: string
    S3URI:
      type: string
      pattern: ^s3[an]?://[a-z0-9][\.\-a-z0-9]{1,61}[a-z0-9](/[^/].*)+$
      minLength: 0
      maxLength: 1024
    SafeString:
      type: string
      pattern: ^[\\\w\-_:/.@=+]*$
    SourceCollectionStatus:
      type: string
      enum:
      - COLLECTING
      - MISCONFIGURED
      - NOT_COLLECTING
    SubscriberResourceList:
      type: array
      items:
        $ref: '#/components/schemas/SubscriberResource'
    SubscriberStatus:
      type: string
      enum:
      - ACTIVE
      - DEACTIVATED
      - PENDING
      - READY
    SubscriptionProtocol:
      type: string
      pattern: ^[a-z\-]*$
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagList:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    UUID:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
