openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: serverlessapplicationrepository
  x-aws-serviceName: serverlessapplicationrepository
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-09-08'
  title: AWSServerlessApplicationRepository
  description: "The AWS Serverless Application Repository makes it easy for developers\
    \ and enterprises to quickly find and deploy serverless applications in the AWS\
    \ Cloud. For more information about serverless applications, see Serverless Computing\
    \ and Applications on the AWS website.\n\nThe AWS Serverless Application Repository\
    \ is deeply integrated with the AWS Lambda console, so that developers of all\
    \ levels can get started with serverless computing without needing to learn anything\
    \ new. You can use category keywords to browse for applications such as web and\
    \ mobile backends, data processing applications, or chatbots. You can also search\
    \ for applications by name, publisher, or event source. To use an application,\
    \ you simply choose it, configure any required fields, and deploy it with a few\
    \ clicks.\n\nYou can also easily publish applications, sharing them publicly with\
    \ the community at large, or privately within your team or across your organization.\
    \ To publish a serverless application (or app), you can use the AWS Management\
    \ Console, AWS Command Line Interface (AWS CLI), or AWS SDKs to upload the code.\
    \ Along with the code, you upload a simple manifest file, also known as the AWS\
    \ Serverless Application Model (AWS SAM) template. For more information about\
    \ AWS SAM, see AWS Serverless Application Model (AWS SAM) on the AWS Labs GitHub\
    \ repository.\n\nThe AWS Serverless Application Repository Developer Guide contains\
    \ more information about the two developer experiences available:\n\n  * Consuming\
    \ Applications – Browse for applications and view information about them, including\
    \ source code and readme files. Also install, configure, and deploy applications\
    \ of your choosing. \n\nPublishing Applications – Configure and upload applications\
    \ to make them available to other developers, and publish new versions of applications."
servers:
- description: The AWSServerlessApplicationRepository regional endpoint
  url: https://serverlessrepo.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas: {}
