openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: sesv2
  x-aws-serviceName: sesv2
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2019-09-27'
  title: Amazon Simple Email Service
  description: |-
    Amazon SES API v2

    [Amazon SES](http://aws.amazon.com/ses) is an Amazon Web Services service that you can use to send email messages to your customers.

    If you're new to Amazon SES API v2, you might find it helpful to review the [Amazon Simple Email Service Developer Guide](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/). The _Amazon SES Developer Guide_ provides information and code samples that demonstrate how to use Amazon SES API v2 features programmatically.
servers:
- description: The Amazon Simple Email Service regional endpoint
  url: https://email.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AdditionalContactEmailAddress:
      type: string
      pattern: ^(.+)@(.+)$
      minLength: 6
      maxLength: 254
    AdminEmail:
      type: string
    AmazonResourceName:
      type: string
    ArchiveArn:
      type: string
      pattern: ^arn:(aws|aws-[a-z-]+):ses:[a-z]{2}-[a-z-]+-[0-9]:[0-9]{1,20}:mailmanager-archive/a-[a-z0-9]{24,62}$
      minLength: 20
      maxLength: 1011
    AttachmentContentDescription:
      type: string
      minLength: 0
      maxLength: 1000
    AttachmentContentId:
      type: string
      minLength: 1
      maxLength: 78
    AttachmentContentType:
      type: string
      minLength: 1
      maxLength: 78
    AttachmentFileName:
      type: string
      minLength: 0
      maxLength: 255
    AttributesData:
      type: string
    BlacklistItemName:
      type: string
    BlacklistingDescription:
      type: string
    BounceSubType:
      type: string
    CampaignId:
      type: string
    CaseId:
      type: string
    Charset:
      type: string
    ComplaintFeedbackType:
      type: string
    ComplaintSubType:
      type: string
    ConfigurationSetName:
      type: string
    ContactListName:
      type: string
    CustomRedirectDomain:
      type: string
    DefaultDimensionValue:
      type: string
    DeliverabilityTestSubject:
      type: string
    Description:
      type: string
    DiagnosticCode:
      type: string
    DimensionName:
      type: string
    DisplayName:
      type: string
    DnsToken:
      type: string
    Domain:
      type: string
    EmailAddress:
      type: string
    EmailSubject:
      type: string
      minLength: 1
      maxLength: 998
    EmailTemplateData:
      type: string
      minLength: 0
      maxLength: 262144
    EmailTemplateHtml:
      type: string
    EmailTemplateName:
      type: string
      minLength: 1
    EmailTemplateSubject:
      type: string
    EmailTemplateText:
      type: string
    Enabled:
      type: boolean
      default: false
    EnabledWrapper:
      type: boolean
    EndpointId:
      type: string
    EndpointName:
      type: string
      pattern: ^[\w\-_]+$
      minLength: 1
      maxLength: 64
    ErrorMessage:
      type: string
    Esp:
      type: string
    EventDestinationName:
      type: string
    ExportedRecordsCount:
      type: integer
    FailedRecordsCount:
      type: integer
    FailedRecordsS3Url:
      type: string
    FailureRedirectionURL:
      type: string
    FeedbackId:
      type: string
    GeneralEnforcementStatus:
      type: string
    Identity:
      type: string
      minLength: 1
    ImageUrl:
      type: string
    InsightsEmailAddress:
      type: string
      minLength: 1
      maxLength: 320
    Ip:
      type: string
    Isp:
      type: string
    IspName:
      type: string
    JobId:
      type: string
      minLength: 1
    ListRecommendationFilterValue:
      type: string
      minLength: 1
      maxLength: 512
    MailFromDomainName:
      type: string
    MaxItems:
      type: integer
    MessageContent:
      type: string
    MessageData:
      type: string
    MessageHeaderName:
      type: string
      pattern: ^[!-9;-@A-~]+$
      minLength: 1
      maxLength: 126
    MessageHeaderValue:
      type: string
      pattern: ^[ -~]*$
      minLength: 1
      maxLength: 870
    MessageInsightsExportMaxResults:
      type: integer
      minimum: 1
      maximum: 10000
    MessageTagName:
      type: string
    MessageTagValue:
      type: string
    MetricDimensionValue:
      type: string
    NextToken:
      type: string
    NextTokenV2:
      type: string
      pattern: ^^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
      minLength: 1
      maxLength: 5000
    OutboundMessageId:
      type: string
    PageSizeV2:
      type: integer
      minimum: 1
      maximum: 1000
    Percentage100Wrapper:
      type: integer
    Policy:
      type: string
      minLength: 1
    PolicyName:
      type: string
      minLength: 1
      maxLength: 64
    PoolName:
      type: string
    PrimaryNameServer:
      type: string
    PrivateKey:
      type: string
      pattern: ^[a-zA-Z0-9+\/]+={0,2}$
      minLength: 1
      maxLength: 20480
    ProcessedRecordsCount:
      type: integer
    QueryErrorMessage:
      type: string
    QueryIdentifier:
      type: string
      minLength: 1
      maxLength: 255
    RblName:
      type: string
    RecommendationDescription:
      type: string
    Region:
      type: string
    RenderedEmailTemplate:
      type: string
    ReportId:
      type: string
    ReportName:
      type: string
    S3Url:
      type: string
      pattern: ^s3:\/\/([^\/]+)\/(.*?([^\/]+)\/?)$
    Selector:
      type: string
      pattern: ^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9]))$
      minLength: 1
      maxLength: 63
    SendingPoolName:
      type: string
    Subject:
      type: string
    SuccessRedirectionURL:
      type: string
    TagKey:
      type: string
    TagValue:
      type: string
    TemplateContent:
      type: string
    TopicName:
      type: string
    UnsubscribeAll:
      type: boolean
      default: false
    UseCaseDescription:
      type: string
      minLength: 0
      maxLength: 5000
    UseDefaultIfPreferenceUnavailable:
      type: boolean
      default: false
    WebsiteURL:
      type: string
      pattern: ^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$
      minLength: 1
      maxLength: 1000
