openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: simspaceweaver
  x-aws-serviceName: simspaceweaver
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2022-10-28'
  title: AWS SimSpace Weaver
  description: |-
    SimSpace Weaver (SimSpace Weaver) is a service that you can use to build and run large-scale spatial simulations in the Amazon Web Services Cloud. For example, you can create crowd simulations, large real-world environments, and immersive and interactive experiences. For more information about SimSpace Weaver, see the _[SimSpace Weaver User Guide](https://docs.aws.amazon.com/simspaceweaver/latest/userguide/) _.

    This API reference describes the API operations and data types that you can use to communicate directly with SimSpace Weaver.

    SimSpace Weaver also provides the SimSpace Weaver app SDK, which you use for app development. The SimSpace Weaver app SDK API reference is included in the SimSpace Weaver app SDK documentation. This documentation is part of the SimSpace Weaver app SDK distributable package.
servers:
- description: The AWS SimSpace Weaver regional endpoint
  url: https://simspaceweaver.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AppPortMappings:
      type: array
      items:
        $ref: '#/components/schemas/SimulationAppPortMapping'
    BucketName:
      type: string
      minLength: 3
      maxLength: 63
    ClientToken:
      type: string
      pattern: ^[a-zA-Z0-9-]+$
      minLength: 32
      maxLength: 128
    ClockStatus:
      type: string
      enum:
      - UNKNOWN
      - STARTING
      - STARTED
      - STOPPING
      - STOPPED
    ClockTargetStatus:
      type: string
      enum:
      - UNKNOWN
      - STARTED
      - STOPPED
    Description:
      type: string
      minLength: 0
      maxLength: 500
    DomainList:
      type: array
      items:
        $ref: '#/components/schemas/Domain'
    LaunchCommandList:
      type: array
      items:
        $ref: '#/components/schemas/NonEmptyString'
    LifecycleManagementStrategy:
      type: string
      enum:
      - Unknown
      - PerWorker
      - BySpatialSubdivision
      - ByRequest
    LogDestinations:
      type: array
      items:
        $ref: '#/components/schemas/LogDestination'
    LogGroupArn:
      type: string
      pattern: ^arn:(?:aws|aws-cn|aws-us-gov):log-group:([a-z]{2}-[a-z]+-\d{1}):(\d{12})?:role\/(.+)$
      minLength: 0
      maxLength: 1600
    NonEmptyString:
      type: string
      minLength: 1
      maxLength: 1600
    ObjectKey:
      type: string
      minLength: 1
      maxLength: 1024
    ObjectKeyPrefix:
      type: string
      minLength: 0
      maxLength: 1024
    OptionalString:
      type: string
    PortNumber:
      type: integer
      minimum: 0
      maximum: 65535
    PositiveInteger:
      type: integer
      minimum: 1
    RoleArn:
      type: string
      pattern: ^arn:(?:aws|aws-cn|aws-us-gov):iam::(\d{12})?:role\/(.+)$
      minLength: 0
      maxLength: 1600
    SimSpaceWeaverArn:
      type: string
      pattern: ^arn:(?:aws|aws-cn|aws-us-gov):simspaceweaver:([a-z]{2}-[a-z]+-\d{1}):(\d{12})?:([a-z]+)\/(.+)$
      minLength: 0
      maxLength: 1600
    SimSpaceWeaverLongResourceName:
      type: string
      pattern: ^[a-zA-Z0-9_.-]+$
      minLength: 1
      maxLength: 256
    SimSpaceWeaverResourceName:
      type: string
      pattern: ^[a-zA-Z0-9_.-]+$
      minLength: 1
      maxLength: 64
    SimulationAppList:
      type: array
      items:
        $ref: '#/components/schemas/SimulationAppMetadata'
    SimulationAppStatus:
      type: string
      enum:
      - STARTING
      - STARTED
      - STOPPING
      - STOPPED
      - ERROR
      - UNKNOWN
    SimulationAppTargetStatus:
      type: string
      enum:
      - UNKNOWN
      - STARTED
      - STOPPED
    SimulationClockList:
      type: array
      items:
        $ref: '#/components/schemas/SimulationClock'
    SimulationList:
      type: array
      items:
        $ref: '#/components/schemas/SimulationMetadata'
    SimulationStatus:
      type: string
      enum:
      - UNKNOWN
      - STARTING
      - STARTED
      - STOPPING
      - STOPPED
      - FAILED
      - DELETING
      - DELETED
      - SNAPSHOT_IN_PROGRESS
    SimulationTargetStatus:
      type: string
      enum:
      - UNKNOWN
      - STARTED
      - STOPPED
      - DELETED
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TimeToLiveString:
      type: string
      pattern: ^\d{1,5}[mhdMHD]$
      minLength: 2
      maxLength: 6
    Timestamp:
      type: string
      format: date-time
    UUID:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 36
