openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: ssm_guiconnect
  x-aws-serviceName: ssmguiconnect
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-07'
  version: '2021-05-01'
  title: AWS SSM-GUIConnect
  description: |-
    AWS Systems Manager GUI Connect

    Systems Manager GUI Connect, a component of Fleet Manager, lets you connect to your Window Server-type Amazon Elastic Compute Cloud (Amazon EC2) instances using the Remote Desktop Protocol (RDP). GUI Connect, which is powered by [Amazon DCV](https://docs.aws.amazon.com/dcv/latest/adminguide/what-is-dcv.html), provides you with secure connectivity to your Windows Server instances directly from the Systems Manager console. You can have up to four simultaneous connections in a single browser window. In the console, GUI Connect is also referred to as Fleet Manager Remote Desktop.

    This reference is intended to be used with the [ _Amazon Web Services Systems Manager User Guide_ ](https://docs.aws.amazon.com/systems-manager/latest/userguide/). To get started, see the following user guide topics:

      * [Setting up Amazon Web Services Systems Manager](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-setting-up.html)

      * [Connect to a Windows Server managed instance using Remote Desktop](https://docs.aws.amazon.com/systems-manager/latest/userguide/fleet-rdp.html)
servers:
- description: The AWS SSM-GUIConnect regional endpoint
  url: https://ssm-guiconnect.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths:
  /DeleteConnectionRecordingPreferences:
    post:
      operationId: DeleteConnectionRecordingPreferences
      description: |-
        Deletes the preferences for recording RDP connections.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ClientToken:
                  $ref: '#/components/schemas/ClientToken'
      responses:
        '200': {}
        '403':
          description: |-
            You do not have sufficient access to perform this action.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '409':
          description: |-
            An error occurred due to a conflict.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictException'
        '500':
          description: |-
            The request processing has failed because of an unknown error, exception or failure.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
        '404':
          description: |-
            The resource could not be found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '402':
          description: |-
            Your request exceeds a service quota.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceQuotaExceededException'
        '429':
          description: |-
            The request was denied due to request throttling.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
        '400':
          description: |-
            The input fails to satisfy the constraints specified by an AWS service.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
  /GetConnectionRecordingPreferences:
    post:
      operationId: GetConnectionRecordingPreferences
      description: |-
        Returns the preferences specified for recording RDP connections in the requesting Amazon Web Services account and Amazon Web Services Region.
      responses:
        '200': {}
        '403':
          description: |-
            You do not have sufficient access to perform this action.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '409':
          description: |-
            An error occurred due to a conflict.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictException'
        '500':
          description: |-
            The request processing has failed because of an unknown error, exception or failure.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
        '404':
          description: |-
            The resource could not be found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '402':
          description: |-
            Your request exceeds a service quota.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceQuotaExceededException'
        '429':
          description: |-
            The request was denied due to request throttling.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
        '400':
          description: |-
            The input fails to satisfy the constraints specified by an AWS service.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
  /UpdateConnectionRecordingPreferences:
    post:
      operationId: UpdateConnectionRecordingPreferences
      description: |-
        Updates the preferences for recording RDP connections.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ConnectionRecordingPreferences:
                  $ref: '#/components/schemas/ConnectionRecordingPreferences'
                ClientToken:
                  $ref: '#/components/schemas/ClientToken'
      responses:
        '200': {}
        '403':
          description: |-
            You do not have sufficient access to perform this action.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '409':
          description: |-
            An error occurred due to a conflict.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictException'
        '500':
          description: |-
            The request processing has failed because of an unknown error, exception or failure.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
        '404':
          description: |-
            The resource could not be found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '402':
          description: |-
            Your request exceeds a service quota.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceQuotaExceededException'
        '429':
          description: |-
            The request was denied due to request throttling.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
        '400':
          description: |-
            The input fails to satisfy the constraints specified by an AWS service.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
components:
  schemas:
    AccessDeniedException:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/ErrorMessage'
      required:
      - message
      description: You do not have sufficient access to perform this action.
    AccountId:
      type: string
      pattern: ^[0-9]{12}$
    BucketName:
      type: string
      pattern: (?=^.{3,63}$)(?!^(\d+\.)+\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$)
    ClientToken:
      type: string
      minLength: 1
      maxLength: 64
    ConflictException:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/ErrorMessage'
      required:
      - message
      description: An error occurred due to a conflict.
    ConnectionArn:
      type: string
    ConnectionRecordingPreferences:
      type: object
      properties:
        RecordingDestinations:
          allOf:
          - $ref: '#/components/schemas/RecordingDestinations'
          description: Determines where recordings of RDP connections are stored.
        KMSKeyArn:
          allOf:
          - $ref: '#/components/schemas/String'
          description: The ARN of a KMS key that is used to encrypt data while it
            is being processed by the service. This key must exist in the same Amazon
            Web Services Region as the node you start an RDP connection to.
      required:
      - RecordingDestinations
      - KMSKeyArn
      description: The set of preferences used for recording RDP connections in the
        requesting Amazon Web Services account and Amazon Web Services Region. This
        includes details such as which S3 bucket recordings are stored in.
    ConnectionToken:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}_[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$
    DeleteConnectionRecordingPreferencesRequest:
      type: object
      properties:
        ClientToken:
          allOf:
          - $ref: '#/components/schemas/ClientToken'
          description: User-provided idempotency token.
    DeleteConnectionRecordingPreferencesResponse:
      type: object
      properties:
        ClientToken:
          allOf:
          - $ref: '#/components/schemas/ClientToken'
          description: Service-provided idempotency token.
    ErrorMessage:
      type: string
    GetConnectionRecordingPreferencesResponse:
      type: object
      properties:
        ClientToken:
          allOf:
          - $ref: '#/components/schemas/ClientToken'
          description: Service-provided idempotency token.
        ConnectionRecordingPreferences:
          allOf:
          - $ref: '#/components/schemas/ConnectionRecordingPreferences'
          description: The set of preferences used for recording RDP connections in
            the requesting Amazon Web Services account and Amazon Web Services Region.
            This includes details such as which S3 bucket recordings are stored in.
    InternalServerException:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/ErrorMessage'
      required:
      - message
      description: The request processing has failed because of an unknown error,
        exception or failure.
    RecordingDestinations:
      type: object
      properties:
        S3Buckets:
          allOf:
          - $ref: '#/components/schemas/S3Buckets'
          description: The S3 bucket where RDP connection recordings are stored.
      required:
      - S3Buckets
      description: Determines where recordings of RDP connections are stored.
    ResourceNotFoundException:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/ErrorMessage'
      required:
      - message
      description: The resource could not be found.
    S3Bucket:
      type: object
      properties:
        BucketOwner:
          allOf:
          - $ref: '#/components/schemas/AccountId'
          description: The Amazon Web Services account number that owns the S3 bucket.
        BucketName:
          allOf:
          - $ref: '#/components/schemas/BucketName'
          description: The name of the S3 bucket where RDP connection recordings are
            stored.
      required:
      - BucketOwner
      - BucketName
      description: The S3 bucket where RDP connection recordings are stored.
    S3Buckets:
      type: array
      items:
        $ref: '#/components/schemas/S3Bucket'
    ServiceQuotaExceededException:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/ErrorMessage'
      required:
      - message
      description: Your request exceeds a service quota.
    ThrottlingException:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/ErrorMessage'
      required:
      - message
      description: The request was denied due to request throttling.
    UpdateConnectionRecordingPreferencesRequest:
      type: object
      properties:
        ConnectionRecordingPreferences:
          allOf:
          - $ref: '#/components/schemas/ConnectionRecordingPreferences'
          description: The set of preferences used for recording RDP connections in
            the requesting Amazon Web Services account and Amazon Web Services Region.
            This includes details such as which S3 bucket recordings are stored in.
        ClientToken:
          allOf:
          - $ref: '#/components/schemas/ClientToken'
          description: User-provided idempotency token.
      required:
      - ConnectionRecordingPreferences
    UpdateConnectionRecordingPreferencesResponse:
      type: object
      properties:
        ClientToken:
          allOf:
          - $ref: '#/components/schemas/ClientToken'
          description: Service-provided idempotency token.
        ConnectionRecordingPreferences:
          allOf:
          - $ref: '#/components/schemas/ConnectionRecordingPreferences'
          description: The set of preferences used for recording RDP connections in
            the requesting Amazon Web Services account and Amazon Web Services Region.
            This includes details such as which S3 bucket recordings are stored in.
    ValidationException:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/ErrorMessage'
      required:
      - message
      description: The input fails to satisfy the constraints specified by an AWS
        service.
