openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: ssm_incidents
  x-aws-serviceName: ssmincidents
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: AWS Systems Manager Incident Manager
  description: |-
    Systems Manager Incident Manager is an incident management console designed to help users mitigate and recover from incidents affecting their Amazon Web Services-hosted applications. An incident is any unplanned interruption or reduction in quality of services.

    Incident Manager increases incident resolution by notifying responders of impact, highlighting relevant troubleshooting data, and providing collaboration tools to get services back up and running. To achieve the primary goal of reducing the time-to-resolution of critical incidents, Incident Manager automates response plans and enables responder team escalation.
servers:
- description: The AWS Systems Manager Incident Manager regional endpoint
  url: https://ssm-incidents.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Arn:
      type: string
      pattern: ^arn:aws(-cn|-us-gov)?:[a-z0-9-]*:[a-z0-9-]*:([0-9]{12})?:.+$
      maxLength: 1000
    ClientToken:
      type: string
      maxLength: 128
    DedupeString:
      type: string
      maxLength: 1000
    EventData:
      type: string
      maxLength: 12000
    ExceptionMessage:
      type: string
    FindingId:
      type: string
      maxLength: 128
    GeneratedId:
      type: string
      pattern: ^related-item/(ANALYSIS|INCIDENT|METRIC|PARENT|ATTACHMENT|OTHER|AUTOMATION|INVOLVED_RESOURCE|TASK)/([0-9]|[A-F]){32}$
      maxLength: 200
    Impact:
      type: integer
      minimum: 1
      maximum: 5
    IncidentRecordStatus:
      type: string
      enum:
      - OPEN
      - RESOLVED
    IncidentSource:
      type: string
      maxLength: 50
    IncidentSummary:
      type: string
      maxLength: 8000
    IncidentTitle:
      type: string
      maxLength: 200
    ItemType:
      type: string
      enum:
      - ANALYSIS
      - INCIDENT
      - METRIC
      - PARENT
      - ATTACHMENT
      - OTHER
      - AUTOMATION
      - INVOLVED_RESOURCE
      - TASK
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    MetricDefinition:
      type: string
      maxLength: 4000
    NextToken:
      type: string
      maxLength: 2000
    Policy:
      type: string
      maxLength: 4000
    PolicyId:
      type: string
      maxLength: 256
    RawData:
      type: string
      maxLength: 10000
    RegionName:
      type: string
      maxLength: 20
    RegionStatus:
      type: string
      enum:
      - ACTIVE
      - CREATING
      - DELETING
      - FAILED
    ReplicationSetStatus:
      type: string
      enum:
      - ACTIVE
      - CREATING
      - UPDATING
      - DELETING
      - FAILED
    ResourceType:
      type: string
      enum:
      - RESPONSE_PLAN
      - INCIDENT_RECORD
      - TIMELINE_EVENT
      - REPLICATION_SET
      - RESOURCE_POLICY
    ResponsePlanDisplayName:
      type: string
      maxLength: 200
    ResponsePlanName:
      type: string
      pattern: ^[a-zA-Z0-9-_]*$
      minLength: 1
      maxLength: 200
    RoleArn:
      type: string
      pattern: ^arn:aws(-cn|-us-gov)?:iam::([0-9]{12})?:role/.+$
      maxLength: 1000
    ServiceCode:
      type: string
      enum:
      - ssm-incidents
    ServicePrincipal:
      type: string
      maxLength: 1000
    SnsArn:
      type: string
      maxLength: 1000
    SortOrder:
      type: string
      enum:
      - ASCENDING
      - DESCENDING
    SseKmsKey:
      type: string
      maxLength: 2048
    SsmContactsArn:
      type: string
      pattern: ^arn:aws(-cn|-us-gov)?:ssm-contacts:[a-z0-9-]*:([0-9]{12}):contact/[a-z0-9_-]+$
      maxLength: 2048
    SsmTargetAccount:
      type: string
      enum:
      - RESPONSE_PLAN_OWNER_ACCOUNT
      - IMPACTED_ACCOUNT
    TagKey:
      type: string
      pattern: ^(?!aws:)[A-Za-z0-9 _=@:.+-/]+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^[A-Za-z0-9 _=@:.+-/]*$
      maxLength: 256
    TimelineEventSort:
      type: string
      enum:
      - EVENT_TIME
    TimelineEventType:
      type: string
      maxLength: 100
    UUID:
      type: string
      maxLength: 50
    Url:
      type: string
      maxLength: 1000
    VariableType:
      type: string
      enum:
      - INCIDENT_RECORD_ARN
      - INVOLVED_RESOURCES
