openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: ssm_sap
  x-aws-serviceName: ssmsap
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: AWS Systems Manager for SAP
  description: |-
    This API reference provides descriptions, syntax, and other details about each of the actions and data types for AWS Systems Manager for SAP. The topic for each action shows the API request parameters and responses.
servers:
- description: The AWS Systems Manager for SAP regional endpoint
  url: https://ssm-sap.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AppRegistryArn:
      type: string
      pattern: ^arn:aws:servicecatalog:[a-z0-9:\/-]+$
    ApplicationId:
      type: string
      pattern: ^[\w\d\.-]+$
      minLength: 1
      maxLength: 60
    Arn:
      type: string
      pattern: ^arn:(.+:){2,4}.+$|^arn:(.+:){1,3}.+\/.+$
    ComponentId:
      type: string
      pattern: ^[\w\d-]+$
      minLength: 1
      maxLength: 100
    DatabaseId:
      type: string
      pattern: '[\w\d]+$'
      minLength: 1
      maxLength: 300
    DatabaseName:
      type: string
      minLength: 1
      maxLength: 100
    FilterName:
      type: string
      minLength: 1
      maxLength: 32
    FilterValue:
      type: string
      minLength: 1
      maxLength: 64
    InstanceId:
      type: string
      pattern: ^i-[\w\d]{8}$|^i-[\w\d]{17}$
    MaxResults:
      type: integer
      default: 50
      minimum: 1
      maximum: 50
    NextToken:
      type: string
      pattern: ^.{16,1024}$
    OperationEventResourceType:
      type: string
      pattern: ^[\w]+::[\w]+::[\w]+$
    OperationId:
      type: string
      pattern: ^[{]?[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}[}]?$
    OperationType:
      type: string
    ResourceId:
      type: string
      minLength: 1
      maxLength: 64
    ResourceType:
      type: string
      minLength: 1
      maxLength: 64
    SAPInstanceNumber:
      type: string
      pattern: ^[0-9]{2}$
    SID:
      type: string
      pattern: ^[A-Z][A-Z0-9]{2}$
    SecretId:
      type: string
      minLength: 1
      maxLength: 100
    SsmSapArn:
      type: string
      pattern: ^arn:(.+:){2,4}.+$|^arn:(.+:){1,3}.+\/.+$
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
    TagValue:
      type: string
      minLength: 1
      maxLength: 256
