openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: ssm_sap
  x-aws-serviceName: ssmsap
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: AWS Systems Manager for SAP
  description: |-
    This API reference provides descriptions, syntax, and other details about each of the actions and data types for AWS Systems Manager for SAP. The topic for each action shows the API request parameters and responses.
servers:
- description: The AWS Systems Manager for SAP regional endpoint
  url: https://ssm-sap.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AllocationType:
      type: string
      enum:
      - VPC_SUBNET
      - ELASTIC_IP
      - OVERLAY
      - UNKNOWN
    AppRegistryArn:
      type: string
      pattern: ^arn:aws:servicecatalog:[a-z0-9:\/-]+$
    ApplicationArnList:
      type: array
      items:
        $ref: '#/components/schemas/SsmSapArn'
    ApplicationCredentialList:
      type: array
      items:
        $ref: '#/components/schemas/ApplicationCredential'
    ApplicationDiscoveryStatus:
      type: string
      enum:
      - SUCCESS
      - REGISTRATION_FAILED
      - REFRESH_FAILED
      - REGISTERING
      - DELETING
    ApplicationId:
      type: string
      pattern: ^[\w\d\.-]+$
      minLength: 1
      maxLength: 60
    ApplicationStatus:
      type: string
      enum:
      - ACTIVATED
      - STARTING
      - STOPPED
      - STOPPING
      - FAILED
      - REGISTERING
      - DELETING
      - UNKNOWN
    ApplicationSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/ApplicationSummary'
    ApplicationType:
      type: string
      enum:
      - HANA
      - SAP_ABAP
    Arn:
      type: string
      pattern: ^arn:(.+:){2,4}.+$|^arn:(.+:){1,3}.+\/.+$
    BackintMode:
      type: string
      enum:
      - AWSBackup
    ClusterStatus:
      type: string
      enum:
      - ONLINE
      - STANDBY
      - MAINTENANCE
      - OFFLINE
      - NONE
    ComponentArnList:
      type: array
      items:
        $ref: '#/components/schemas/SsmSapArn'
    ComponentId:
      type: string
      pattern: ^[\w\d-]+$
      minLength: 1
      maxLength: 100
    ComponentIdList:
      type: array
      items:
        $ref: '#/components/schemas/ComponentId'
    ComponentInfoList:
      type: array
      items:
        $ref: '#/components/schemas/ComponentInfo'
    ComponentStatus:
      type: string
      enum:
      - ACTIVATED
      - STARTING
      - STOPPED
      - STOPPING
      - RUNNING
      - RUNNING_WITH_ERROR
      - UNDEFINED
    ComponentSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/ComponentSummary'
    ComponentType:
      type: string
      enum:
      - HANA
      - HANA_NODE
      - ABAP
      - ASCS
      - DIALOG
      - WEBDISP
      - WD
      - ERS
    ConnectedEntityType:
      type: string
      enum:
      - DBMS
    CredentialType:
      type: string
      enum:
      - ADMIN
    DatabaseConnectionMethod:
      type: string
      enum:
      - DIRECT
      - OVERLAY
    DatabaseId:
      type: string
      pattern: '[\w\d]+$'
      minLength: 1
      maxLength: 300
    DatabaseIdList:
      type: array
      items:
        $ref: '#/components/schemas/DatabaseId'
    DatabaseName:
      type: string
      minLength: 1
      maxLength: 100
    DatabaseStatus:
      type: string
      enum:
      - RUNNING
      - STARTING
      - STOPPED
      - WARNING
      - UNKNOWN
      - ERROR
    DatabaseSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/DatabaseSummary'
    DatabaseType:
      type: string
      enum:
      - SYSTEM
      - TENANT
    FilterList:
      type: array
      items:
        $ref: '#/components/schemas/Filter'
    FilterName:
      type: string
      minLength: 1
      maxLength: 32
    FilterOperator:
      type: string
      enum:
      - Equals
      - GreaterThanOrEquals
      - LessThanOrEquals
    FilterValue:
      type: string
      minLength: 1
      maxLength: 64
    HostList:
      type: array
      items:
        $ref: '#/components/schemas/Host'
    HostRole:
      type: string
      enum:
      - LEADER
      - WORKER
      - STANDBY
      - UNKNOWN
    InstanceId:
      type: string
      pattern: ^i-[\w\d]{8}$|^i-[\w\d]{17}$
    InstanceList:
      type: array
      items:
        $ref: '#/components/schemas/InstanceId'
    IpAddressList:
      type: array
      items:
        $ref: '#/components/schemas/IpAddressMember'
    MaxResults:
      type: integer
      default: 50
      minimum: 1
      maximum: 50
    NextToken:
      type: string
      pattern: ^.{16,1024}$
    OperationEventList:
      type: array
      items:
        $ref: '#/components/schemas/OperationEvent'
    OperationEventResourceType:
      type: string
      pattern: ^[\w]+::[\w]+::[\w]+$
    OperationEventStatus:
      type: string
      enum:
      - IN_PROGRESS
      - COMPLETED
      - FAILED
    OperationId:
      type: string
      pattern: ^[{]?[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}[}]?$
    OperationIdList:
      type: array
      items:
        $ref: '#/components/schemas/OperationId'
    OperationList:
      type: array
      items:
        $ref: '#/components/schemas/Operation'
    OperationMode:
      type: string
      enum:
      - PRIMARY
      - LOGREPLAY
      - DELTA_DATASHIPPING
      - LOGREPLAY_READACCESS
      - NONE
    OperationProperties:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    OperationStatus:
      type: string
      enum:
      - INPROGRESS
      - SUCCESS
      - ERROR
    OperationType:
      type: string
    PermissionActionType:
      type: string
      enum:
      - RESTORE
    ReplicationMode:
      type: string
      enum:
      - PRIMARY
      - NONE
      - SYNC
      - SYNCMEM
      - ASYNC
    ResourceId:
      type: string
      minLength: 1
      maxLength: 64
    ResourceType:
      type: string
      minLength: 1
      maxLength: 64
    SAPInstanceNumber:
      type: string
      pattern: ^[0-9]{2}$
    SID:
      type: string
      pattern: ^[A-Z][A-Z0-9]{2}$
    SecretId:
      type: string
      minLength: 1
      maxLength: 100
    SsmSapArn:
      type: string
      pattern: ^arn:(.+:){2,4}.+$|^arn:(.+:){1,3}.+\/.+$
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      minLength: 1
      maxLength: 256
