openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: sso_oidc
  x-aws-serviceName: ssooidc
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2019-06-10'
  title: AWS SSO OIDC
  description: "IAM Identity Center OpenID Connect (OIDC) is a web service that enables\
    \ a client (such as CLI or a native application) to register with IAM Identity\
    \ Center. The service also enables the client to fetch the user’s access token\
    \ upon successful authentication and authorization with IAM Identity Center.\n\
    \n**API namespaces**\n\nIAM Identity Center uses the `sso` and `identitystore`\
    \ API namespaces. IAM Identity Center OpenID Connect uses the `sso-oidc` namespace.\n\
    \n**Considerations for using this guide**\n\nBefore you begin using this guide,\
    \ we recommend that you first review the following important information about\
    \ how the IAM Identity Center OIDC service works.\n\n  * The IAM Identity Center\
    \ OIDC service currently implements only the portions of the OAuth 2.0 Device\
    \ Authorization Grant standard (<https://tools.ietf.org/html/rfc8628>) that are\
    \ necessary to enable single sign-on authentication with the CLI. \n\n  * With\
    \ older versions of the CLI, the service only emits OIDC access tokens, so to\
    \ obtain a new token, users must explicitly re-authenticate. To access the OIDC\
    \ flow that supports token refresh and doesn’t require re-authentication, update\
    \ to the latest CLI version (1.27.10 for CLI V1 and 2.9.0 for CLI V2) with support\
    \ for OIDC token refresh and configurable IAM Identity Center session durations.\
    \ For more information, see [Configure Amazon Web Services access portal session\
    \ duration ](https://docs.aws.amazon.com/singlesignon/latest/userguide/configure-user-session.html).\
    \ \n\n  * The access tokens provided by this service grant access to all Amazon\
    \ Web Services account entitlements assigned to an IAM Identity Center user, not\
    \ just a particular application.\n\n  * The documentation in this guide does not\
    \ describe the mechanism to convert the access token into Amazon Web Services\
    \ Auth (“sigv4”) credentials for use with IAM-protected Amazon Web Services service\
    \ endpoints. For more information, see [GetRoleCredentials](https://docs.aws.amazon.com/singlesignon/latest/PortalAPIReference/API_GetRoleCredentials.html)\
    \ in the _IAM Identity Center Portal API Reference Guide_.\n\nFor general information\
    \ about IAM Identity Center, see [What is IAM Identity Center?](https://docs.aws.amazon.com/singlesignon/latest/userguide/what-is.html)\
    \ in the _IAM Identity Center User Guide_."
servers:
- description: The AWS SSO OIDC regional endpoint
  url: https://oidc.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccessToken:
      type: string
    ArnType:
      type: string
    Assertion:
      type: string
    AuthCode:
      type: string
    ClientId:
      type: string
    ClientName:
      type: string
    ClientSecret:
      type: string
    ClientType:
      type: string
    CodeVerifier:
      type: string
    DeviceCode:
      type: string
    Error:
      type: string
    ErrorDescription:
      type: string
    ExpirationInSeconds:
      type: integer
      default: 0
    GrantType:
      type: string
    IdToken:
      type: string
    IdentityContext:
      type: string
    IntervalInSeconds:
      type: integer
      default: 0
    Location:
      type: string
    RefreshToken:
      type: string
    Region:
      type: string
    Scope:
      type: string
    SubjectToken:
      type: string
    TokenType:
      type: string
    TokenTypeURI:
      type: string
    URI:
      type: string
    UserCode:
      type: string
