openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: support_app
  x-aws-serviceName: supportapp
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2021-08-20'
  title: AWS Support App
  description: "Amazon Web Services Support App in Slack\n\nYou can use the Amazon\
    \ Web Services Support App in Slack API to manage your support cases in Slack\
    \ for your Amazon Web Services account. After you configure your Slack workspace\
    \ and channel with the Amazon Web Services Support App, you can perform the following\
    \ tasks directly in your Slack channel:\n\n  * Create, search, update, and resolve\
    \ your support cases\n\n  * Request service quota increases for your account\n\
    \n  * Invite Amazon Web Services Support agents to your channel so that you can\
    \ chat directly about your support cases\n\nFor more information about how to\
    \ perform these actions in Slack, see the following documentation in the _Amazon\
    \ Web Services Support User Guide_ :\n\n  * [Amazon Web Services Support App in\
    \ Slack](https://docs.aws.amazon.com/awssupport/latest/user/aws-support-app-for-slack.html)\n\
    \n  * [Joining a live chat session with Amazon Web Services Support](https://docs.aws.amazon.com/awssupport/latest/user/joining-a-live-chat-session.html)\n\
    \n  * [Requesting service quota increases](https://docs.aws.amazon.com/awssupport/latest/user/service-quota-increase.html)\n\
    \n  * [Amazon Web Services Support App commands in Slack](https://docs.aws.amazon.com/awssupport/latest/user/support-app-commands.html)\n\
    \nYou can also use the Amazon Web Services Management Console instead of the Amazon\
    \ Web Services Support App API to manage your Slack configurations. For more information,\
    \ see [Authorize a Slack workspace to enable the Amazon Web Services Support App](https://docs.aws.amazon.com/awssupport/latest/user/authorize-slack-workspace.html).\n\
    \n  * You must have a Business or Enterprise Support plan to use the Amazon Web\
    \ Services Support App API. \n\n  * For more information about the Amazon Web\
    \ Services Support App endpoints, see the [Amazon Web Services Support App in\
    \ Slack endpoints](https://docs.aws.amazon.com/general/latest/gr/awssupport.html#awssupport_app_region)\
    \ in the _Amazon Web Services General Reference_."
servers:
- description: The AWS Support App regional endpoint
  url: https://supportapp.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas: {}
