openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: supplychain
  x-aws-serviceName: supplychain
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2024-01-01'
  title: AWS Supply Chain
  description: |-
    AWS Supply Chain is a cloud-based application that works with your enterprise resource planning (ERP) and supply chain management systems. Using AWS Supply Chain, you can connect and extract your inventory, supply, and demand related data from existing ERP or supply chain systems into a single data model.

    The AWS Supply Chain API supports configuration data import for Supply Planning.

    All AWS Supply chain API operations are Amazon-authenticated and certificate-signed. They not only require the use of the AWS SDK, but also allow for the exclusive use of AWS Identity and Access Management users and roles to help facilitate access, trust, and permission policies.
servers:
- description: The AWS Supply Chain regional endpoint
  url: https://scn.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AscResourceArn:
      type: string
      pattern: ^arn:aws:scn(?::([a-z0-9-]+):([0-9]+):instance)?/([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})[-_./A-Za-z0-9]*$
      minLength: 20
      maxLength: 1011
    AwsAccountId:
      type: string
      pattern: ^[0-9]{12}$
    ClientToken:
      type: string
      minLength: 33
      maxLength: 126
    ConfigurationJobStatus:
      type: string
      enum:
      - NEW
      - FAILED
      - IN_PROGRESS
      - QUEUED
      - SUCCESS
      description: <p>The status of the job.</p>
    ConfigurationS3Uri:
      type: string
      pattern: ^[sS]3://[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]/.+$
      minLength: 10
    DataIntegrationEventData:
      type: string
      minLength: 1
      maxLength: 1048576
    DataIntegrationEventGroupId:
      type: string
      minLength: 1
      maxLength: 255
    DataIntegrationEventType:
      type: string
      enum:
      - scn.data.forecast
      - scn.data.inventorylevel
      - scn.data.inboundorder
      - scn.data.inboundorderline
      - scn.data.inboundorderlineschedule
      - scn.data.outboundorderline
      - scn.data.outboundshipment
      - scn.data.processheader
      - scn.data.processoperation
      - scn.data.processproduct
      - scn.data.reservation
      - scn.data.shipment
      - scn.data.shipmentstop
      - scn.data.shipmentstoporder
      - scn.data.supplyplan
    DataIntegrationFlowFileType:
      type: string
      enum:
      - CSV
      - PARQUET
      - JSON
    DataIntegrationFlowList:
      type: array
      items:
        $ref: '#/components/schemas/DataIntegrationFlow'
    DataIntegrationFlowLoadType:
      type: string
      enum:
      - INCREMENTAL
      - REPLACE
    DataIntegrationFlowMaxResults:
      type: integer
      default: 10
      minimum: 0
      maximum: 20
    DataIntegrationFlowName:
      type: string
      pattern: ^[A-Za-z0-9-]+$
      minLength: 1
      maxLength: 256
    DataIntegrationFlowNextToken:
      type: string
      minLength: 1
      maxLength: 65535
    DataIntegrationFlowS3Prefix:
      type: string
      pattern: ^[/A-Za-z0-9._-]+$
      minLength: 0
      maxLength: 700
    DataIntegrationFlowSQLQuery:
      type: string
      minLength: 1
      maxLength: 65535
    DataIntegrationFlowSourceList:
      type: array
      items:
        $ref: '#/components/schemas/DataIntegrationFlowSource'
    DataIntegrationFlowSourceName:
      type: string
      pattern: ^[A-Za-z0-9_]+$
      minLength: 1
      maxLength: 256
    DataIntegrationFlowSourceType:
      type: string
      enum:
      - S3
      - DATASET
    DataIntegrationFlowTargetType:
      type: string
      enum:
      - S3
      - DATASET
    DataIntegrationFlowTransformationType:
      type: string
      enum:
      - SQL
      - NONE
    DataLakeDatasetDescription:
      type: string
      minLength: 1
      maxLength: 500
    DataLakeDatasetList:
      type: array
      items:
        $ref: '#/components/schemas/DataLakeDataset'
    DataLakeDatasetMaxResults:
      type: integer
      default: 10
      minimum: 0
      maximum: 20
    DataLakeDatasetName:
      type: string
      pattern: ^[a-z0-9_]+$
      minLength: 1
      maxLength: 75
    DataLakeDatasetNamespace:
      type: string
      pattern: ^[a-z]+$
      minLength: 1
      maxLength: 50
    DataLakeDatasetNextToken:
      type: string
      minLength: 1
      maxLength: 65535
    DataLakeDatasetSchemaFieldList:
      type: array
      items:
        $ref: '#/components/schemas/DataLakeDatasetSchemaField'
    DataLakeDatasetSchemaFieldName:
      type: string
      pattern: ^[a-z0-9_]+$
      minLength: 1
      maxLength: 100
    DataLakeDatasetSchemaFieldType:
      type: string
      enum:
      - INT
      - DOUBLE
      - STRING
      - TIMESTAMP
    DataLakeDatasetSchemaName:
      type: string
      pattern: ^[A-Za-z0-9]+$
      minLength: 1
      maxLength: 100
    DatasetIdentifier:
      type: string
      pattern: ^[-_/A-Za-z0-9:]+$
      minLength: 1
      maxLength: 1011
    InstanceDescription:
      type: string
      pattern: ^([a-zA-Z0-9., _ʼ'%-]){0,500}$
      minLength: 0
      maxLength: 501
    InstanceList:
      type: array
      items:
        $ref: '#/components/schemas/Instance'
    InstanceMaxResults:
      type: integer
      default: 10
      minimum: 0
      maximum: 20
    InstanceName:
      type: string
      pattern: ^(?![ _ʼ'%-])[a-zA-Z0-9 _ʼ'%-]{0,62}[a-zA-Z0-9]$
      minLength: 0
      maxLength: 63
    InstanceNameList:
      type: array
      items:
        $ref: '#/components/schemas/InstanceName'
    InstanceNextToken:
      type: string
      minLength: 1
      maxLength: 1024
    InstanceState:
      type: string
      enum:
      - Initializing
      - Active
      - CreateFailed
      - DeleteFailed
      - Deleting
      - Deleted
    InstanceStateList:
      type: array
      items:
        $ref: '#/components/schemas/InstanceState'
    InstanceWebAppDnsDomain:
      type: string
      pattern: ^(?![-])[a-zA-Z0-9-]{1,62}[a-zA-Z0-9]$
    KmsKeyArn:
      type: string
      pattern: ^arn:[a-z0-9][-.a-z0-9]{0,62}:kms:([a-z0-9][-.a-z0-9]{0,62})?:([a-z0-9][-.a-z0-9]{0,62})?:key/.{0,1019}$
      maxLength: 2048
    S3BucketName:
      type: string
      pattern: ^[a-z0-9][a-z0-9.-]*[a-z0-9]$
      minLength: 3
      maxLength: 63
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    UUID:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      minLength: 36
      maxLength: 36
