openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: synthetics
  x-aws-serviceName: synthetics
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-10-11'
  title: Synthetics
  description: |-
    Amazon CloudWatch Synthetics

    You can use Amazon CloudWatch Synthetics to continually monitor your services. You can create and manage _canaries_ , which are modular, lightweight scripts that monitor your endpoints and APIs from the outside-in. You can set up your canaries to run 24 hours a day, once per minute. The canaries help you check the availability and latency of your web services and troubleshoot anomalies by investigating load time data, screenshots of the UI, logs, and metrics. The canaries seamlessly integrate with CloudWatch ServiceLens to help you trace the causes of impacted nodes in your applications. For more information, see [Using ServiceLens to Monitor the Health of Your Applications](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ServiceLens.html) in the _Amazon CloudWatch User Guide_.

    Before you create and manage canaries, be aware of the security considerations. For more information, see [Security Considerations for Synthetics Canaries](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/servicelens_canaries_security.html).
servers:
- description: The Synthetics regional endpoint
  url: https://synthetics.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    BaseScreenshotConfigIgnoreCoordinate:
      type: string
      pattern: ^(-?\d{1,5}\.?\d{0,2},){3}(-?\d{1,5}\.?\d{0,2}){1}$
    BaseScreenshotIgnoreCoordinates:
      type: array
      items:
        $ref: '#/components/schemas/BaseScreenshotConfigIgnoreCoordinate'
    BaseScreenshots:
      type: array
      items:
        $ref: '#/components/schemas/BaseScreenshot'
    Blob:
      type: string
      format: byte
      minLength: 1
      maxLength: 10000000
    Canaries:
      type: array
      items:
        $ref: '#/components/schemas/Canary'
    CanariesLastRun:
      type: array
      items:
        $ref: '#/components/schemas/CanaryLastRun'
    CanaryArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*)?:synthetics:[a-z]{2,4}(-[a-z]{2,4})?-[a-z]+-\d{1}:\d{12}:canary:[0-9a-z_\-]{1,255}$
      minLength: 1
      maxLength: 2048
    CanaryName:
      type: string
      pattern: ^[0-9a-z_\-]+$
      minLength: 1
      maxLength: 255
    CanaryRunState:
      type: string
      enum:
      - RUNNING
      - PASSED
      - FAILED
    CanaryRunStateReasonCode:
      type: string
      enum:
      - CANARY_FAILURE
      - EXECUTION_FAILURE
    CanaryRuns:
      type: array
      items:
        $ref: '#/components/schemas/CanaryRun'
    CanaryState:
      type: string
      enum:
      - CREATING
      - READY
      - STARTING
      - RUNNING
      - UPDATING
      - STOPPING
      - STOPPED
      - ERROR
      - DELETING
    CanaryStateReasonCode:
      type: string
      enum:
      - INVALID_PERMISSIONS
      - CREATE_PENDING
      - CREATE_IN_PROGRESS
      - CREATE_FAILED
      - UPDATE_PENDING
      - UPDATE_IN_PROGRESS
      - UPDATE_COMPLETE
      - ROLLBACK_COMPLETE
      - ROLLBACK_FAILED
      - DELETE_IN_PROGRESS
      - DELETE_FAILED
      - SYNC_DELETE_IN_PROGRESS
    CodeHandler:
      type: string
      pattern: ^([0-9a-zA-Z_-]+\/)*[0-9A-Za-z_\\-]+\.[A-Za-z_][A-Za-z0-9_]*$
      minLength: 1
      maxLength: 128
    DescribeCanariesLastRunNameFilter:
      type: array
      items:
        $ref: '#/components/schemas/CanaryName'
    DescribeCanariesNameFilter:
      type: array
      items:
        $ref: '#/components/schemas/CanaryName'
    EncryptionMode:
      type: string
      enum:
      - SSE_S3
      - SSE_KMS
    EnvironmentVariableName:
      type: string
      pattern: ^[a-zA-Z]([a-zA-Z0-9_])+$
    EnvironmentVariableValue:
      type: string
    EnvironmentVariablesMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/EnvironmentVariableValue'
    ErrorMessage:
      type: string
    FunctionArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*)?:lambda:[a-z]{2,4}(-[a-z]{2,4})?-[a-z]+-\d{1}:\d{12}:function:[a-zA-Z0-9-_]+(:(\$LATEST|[a-zA-Z0-9-_]+))?$
      minLength: 1
      maxLength: 2048
    GroupArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*)?:synthetics:[a-z]{2,4}(-[a-z]{2,4})?-[a-z]+-\d{1}:\d{12}:group:[0-9a-z]+$
      minLength: 1
      maxLength: 128
    GroupIdentifier:
      type: string
      minLength: 1
      maxLength: 128
    GroupName:
      type: string
      minLength: 1
      maxLength: 64
    GroupSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/GroupSummary'
    KmsKeyArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*)?:kms:[a-z]{2,4}(-[a-z]{2,4})?-[a-z]+-\d{1}:\d{12}:key/[\w\-\/]+$
      minLength: 1
      maxLength: 2048
    MaxCanaryResults:
      type: integer
      minimum: 1
      maximum: 20
    MaxFifteenMinutesInSeconds:
      type: integer
      minimum: 3
      maximum: 840
    MaxGroupResults:
      type: integer
      minimum: 1
      maximum: 20
    MaxOneYearInSeconds:
      type: integer
      format: int64
      minimum: 0
      maximum: 31622400
    MaxSize100:
      type: integer
      minimum: 1
      maximum: 100
    MaxSize1024:
      type: integer
      minimum: 1
      maximum: 1024
    MaxSize3008:
      type: integer
      minimum: 960
      maximum: 3008
    NullableBoolean:
      type: boolean
    PaginationToken:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 512
    ProvisionedResourceCleanupSetting:
      type: string
      enum:
      - AUTOMATIC
      - 'OFF'
    ResourceArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*)?:synthetics:[a-z]{2,4}(-[a-z]{2,4})?-[a-z]+-\d{1}:\d{12}:(canary|group):[0-9a-z_\-]+$
      minLength: 1
      maxLength: 2048
    ResourceList:
      type: array
      items:
        $ref: '#/components/schemas/ResourceToTag'
    ResourceToTag:
      type: string
      enum:
      - lambda-function
    RoleArn:
      type: string
      pattern: ^arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$
      minLength: 1
      maxLength: 2048
    RuntimeVersionList:
      type: array
      items:
        $ref: '#/components/schemas/RuntimeVersion'
    SecurityGroupId:
      type: string
    SecurityGroupIds:
      type: array
      items:
        $ref: '#/components/schemas/SecurityGroupId'
    String:
      type: string
      minLength: 1
      maxLength: 1024
    StringList:
      type: array
      items:
        $ref: '#/components/schemas/String'
    SubnetId:
      type: string
    SubnetIds:
      type: array
      items:
        $ref: '#/components/schemas/SubnetId'
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    Timestamp:
      type: string
      format: date-time
    Token:
      type: string
      minLength: 4
      maxLength: 252
    UUID:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
    VpcId:
      type: string
    boolean:
      type: boolean
      default: false
