openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: taxsettings
  x-aws-serviceName: taxsettings
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: Tax Settings
  description: |-
    You can use the tax setting API to programmatically set, modify, and delete the tax registration number (TRN), associated business legal name, and address (Collectively referred to as "TRN information"). You can also programmatically view TRN information and tax addresses ("Tax profiles").

    You can use this API to automate your TRN information settings instead of manually using the console.

    Service Endpoint

      * https://tax.us-east-1.amazonaws.com
servers:
- description: The Tax Settings regional endpoint
  url: https://tax.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccountId:
      type: string
      pattern: ^\d+$
      minLength: 12
      maxLength: 12
    AccountName:
      type: string
      pattern: ^[\s\S]*$
    AddressLine1:
      type: string
      pattern: ^(?!\s*$)[\s\S]+$
      minLength: 1
      maxLength: 180
    AddressLine2:
      type: string
      pattern: ^(?!\s*$)[\s\S]+$
      minLength: 1
      maxLength: 60
    AddressLine3:
      type: string
      pattern: ^(?!\s*$)[\s\S]+$
      minLength: 1
      maxLength: 60
    Boolean:
      type: boolean
    BusinessRegistrationNumber:
      type: string
      pattern: ^[0-9]{12}$
    BusinessRepresentativeName:
      type: string
      pattern: ^[0-9\u3130-\u318F\uAC00-\uD7AF,.( )-\\s]*$
      minLength: 1
      maxLength: 200
    CanadaProvincialSalesTaxIdString:
      type: string
      pattern: ^([0-9A-Z/-]+)$
      minLength: 7
      maxLength: 16
    CanadaQuebecSalesTaxNumberString:
      type: string
      pattern: ^([0-9]{10})(TQ[0-9]{4})?$
    CanadaRetailSalesTaxNumberString:
      type: string
      pattern: ^([0-9]{6}-[0-9]{1})$
    CcmCode:
      type: string
      pattern: ^\d+$
      maxLength: 1024
    CertifiedEmailId:
      type: string
      pattern: ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,20}$
    CigNumber:
      type: string
      pattern: ^([0-9A-Z]{1,15})$
    City:
      type: string
      pattern: ^(?!\s*$)[\s\S]+$
      minLength: 1
      maxLength: 50
    ContractingAuthorityCode:
      type: string
      pattern: ^\d{4}\.[A-Z]\d{5}\.\d{4}$
    CountryCode:
      type: string
      pattern: ^[a-zA-Z]+$
      minLength: 2
      maxLength: 2
    CupNumber:
      type: string
      pattern: ^([0-9A-Z]{1,15})$
    DateOfBirth:
      type: string
      pattern: ^(\d{4}-(0[0-9]|1[0-2])-([0-2][0-9]|3[0-1]))$
      minLength: 10
      maxLength: 10
    DateString:
      type: string
      pattern: ^(\d{4}-(0[0-9]|1[0-2])-([0-2][0-9]|3[0-1]))$
    DecisionNumber:
      type: string
      pattern: ^([a-zA-Z0-9/.\-]{0,200})$
    DestinationFilePath:
      type: string
      pattern: ^[\s\S]*$
    DisplayName:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 50
    District:
      type: string
      pattern: ^(?!\s*$)[\s\S]+$
      minLength: 1
      maxLength: 50
    ElectronicTransactionCodeNumber:
      type: string
      pattern: ^\d{17}$
    EnterpriseIdentificationNumber:
      type: string
      pattern: ^(\d{10}|(\d{10}-\d{3}))$
    ErrorCode:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 50
    ErrorMessage:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 1024
    ExemptionDocumentName:
      type: string
      pattern: ^([A-Za-z0-9-_.]+).(pdf|jpg|png)$
      minLength: 0
      maxLength: 128
    FieldName:
      type: string
      pattern: ^(?!\s*$)[\s\S]+$
    GenericString:
      type: string
      pattern: ^[\s\S]*$
      minLength: 1
      maxLength: 200
    IndividualRegistrationNumber:
      type: string
      pattern: ^([0-9]{10})$
    InheritanceObtainedReason:
      type: string
      pattern: ^[\s\S]*$
    ItemOfBusiness:
      type: string
      pattern: ^[0-9\u3130-\u318F\uAC00-\uD7AF,.( )-\\s]*$
      minLength: 1
      maxLength: 100
    KepEmailId:
      type: string
      pattern: ^[\s\S]*$
    LegalName:
      type: string
      pattern: ^(?!\s*$)[\s\S]+$
      minLength: 1
      maxLength: 200
    LegalNatureCode:
      type: string
      pattern: ^\d+$
      maxLength: 1024
    LineOfBusiness:
      type: string
      pattern: ^[0-9\u3130-\u318F\uAC00-\uD7AF,.( )-\\s]*$
      minLength: 1
      maxLength: 100
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
    PaginationTokenString:
      type: string
      pattern: ^[-A-Za-z0-9_+\=\/]+$
      minLength: 1
      maxLength: 2000
    Pan:
      type: string
      pattern: ^[A-Z]{5}[0-9]{4}[A-Z]{1}$
    PaymentVoucherNumber:
      type: string
      pattern: ^(\d{17}|[A-Za-z]{3}\d{13})$
    PostalCode:
      type: string
      pattern: ^(?!\s*$)[\s\S]+$
      minLength: 1
      maxLength: 20
    PpnExceptionDesignationCode:
      type: string
      pattern: ^(01|02|03|07|08)$
    RegistrationId:
      type: string
      pattern: ^(?!\s*$)[\s\S]+$
      minLength: 1
      maxLength: 200
    RegistryCommercialCode:
      type: string
      pattern: ^\d+$
      minLength: 8
      maxLength: 8
    S3BucketName:
      type: string
      pattern: ^(?=^.{3,63}$)(?!^(\d+\.)+\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$)$
      minLength: 3
      maxLength: 63
    S3Key:
      type: string
      pattern: ^.*\S.*$
      minLength: 1
      maxLength: 1024
    S3Prefix:
      type: string
      pattern: ^.*\S.*$
      minLength: 0
      maxLength: 512
    SdiAccountId:
      type: string
      pattern: ^[0-9A-Z]{6,7}$
    SecondaryTaxId:
      type: string
      pattern: ^([0-9]{10})$
    Seller:
      type: string
      pattern: ^[\s\S]*$
    State:
      type: string
      pattern: ^(?!\s*$)[\s\S]+$
      minLength: 1
      maxLength: 50
    TaxCode:
      type: string
      pattern: ^([0-9]{11}|[A-Z]{6}[0-9]{2}[A-Z][0-9]{2}[A-Z][0-9]{3}[A-Z])$
    TaxDocumentAccessToken:
      type: string
      pattern: ^[\s\S]*$
    TaxDocumentName:
      type: string
      pattern: ^[\s\S]*$
    TaxInformationNumber:
      type: string
      pattern: ^[A-Z]{1,2}[0-9]{1,11}$
    TaxOffice:
      type: string
      pattern: ^[\s\S]*$
    UniqueIdentificationNumber:
      type: string
      pattern: ^[a-zA-Z0-9]{39}$
    Url:
      type: string
      pattern: ^https.*\S.*$
      minLength: 1
      maxLength: 200
    VatRegistrationNumber:
      type: string
      pattern: ^[0-9]{12}$
