openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: taxsettings
  x-aws-serviceName: taxsettings
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2018-05-10'
  title: Tax Settings
  description: |-
    You can use the tax setting API to programmatically set, modify, and delete the tax registration number (TRN), associated business legal name, and address (Collectively referred to as "TRN information"). You can also programmatically view TRN information and tax addresses ("Tax profiles").

    You can use this API to automate your TRN information settings instead of manually using the console.

    Service Endpoint

      * https://tax.us-east-1.amazonaws.com
servers:
- description: The Tax Settings regional endpoint
  url: https://tax.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccountDetailsList:
      type: array
      items:
        $ref: '#/components/schemas/AccountDetails'
    AccountId:
      type: string
      pattern: ^\d+$
      minLength: 12
      maxLength: 12
    AccountIds:
      type: array
      items:
        $ref: '#/components/schemas/AccountId'
    AccountName:
      type: string
      pattern: ^[\s\S]*$
    AddressLine1:
      type: string
      pattern: ^(?!\s*$)[\s\S]+$
      minLength: 1
      maxLength: 180
    AddressLine2:
      type: string
      pattern: ^(?!\s*$)[\s\S]+$
      minLength: 1
      maxLength: 60
    AddressLine3:
      type: string
      pattern: ^(?!\s*$)[\s\S]+$
      minLength: 1
      maxLength: 60
    AddressRoleMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Jurisdiction'
    AddressRoleType:
      type: string
      enum:
      - TaxAddress
      - BillingAddress
      - ContactAddress
    Authorities:
      type: array
      items:
        $ref: '#/components/schemas/Authority'
    BatchDeleteTaxRegistrationErrors:
      type: array
      items:
        $ref: '#/components/schemas/BatchDeleteTaxRegistrationError'
    BatchPutTaxRegistrationErrors:
      type: array
      items:
        $ref: '#/components/schemas/BatchPutTaxRegistrationError'
    Boolean:
      type: boolean
    BusinessRegistrationNumber:
      type: string
      pattern: ^[0-9]{12}$
    BusinessRepresentativeName:
      type: string
      pattern: ^[0-9\u3130-\u318F\uAC00-\uD7AF,.( )-\\s]*$
      minLength: 1
      maxLength: 200
    CanadaProvincialSalesTaxIdString:
      type: string
      pattern: ^([0-9A-Z/-]+)$
      minLength: 7
      maxLength: 16
    CanadaQuebecSalesTaxNumberString:
      type: string
      pattern: ^([0-9]{10})(TQ[0-9]{4})?$
    CanadaRetailSalesTaxNumberString:
      type: string
      pattern: ^([0-9]{6}-[0-9]{1})$
    CcmCode:
      type: string
      pattern: ^\d+$
      maxLength: 1024
    CertifiedEmailId:
      type: string
      pattern: ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,20}$
    CigNumber:
      type: string
      pattern: ^([0-9A-Z]{1,15})$
    City:
      type: string
      pattern: ^(?!\s*$)[\s\S]+$
      minLength: 1
      maxLength: 50
    ContractingAuthorityCode:
      type: string
      pattern: ^\d{4}\.[A-Z]\d{5}\.\d{4}$
    CountryCode:
      type: string
      pattern: ^[a-zA-Z]+$
      minLength: 2
      maxLength: 2
    CupNumber:
      type: string
      pattern: ^([0-9A-Z]{1,15})$
    DateOfBirth:
      type: string
      pattern: ^(\d{4}-(0[0-9]|1[0-2])-([0-2][0-9]|3[0-1]))$
      minLength: 10
      maxLength: 10
    DateString:
      type: string
      pattern: ^(\d{4}-(0[0-9]|1[0-2])-([0-2][0-9]|3[0-1]))$
    DecisionNumber:
      type: string
      pattern: ^([a-zA-Z0-9/.\-]{0,200})$
    DestinationFilePath:
      type: string
      pattern: ^[\s\S]*$
    DisplayName:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 50
    District:
      type: string
      pattern: ^(?!\s*$)[\s\S]+$
      minLength: 1
      maxLength: 50
    ElectronicTransactionCodeNumber:
      type: string
      pattern: ^\d{17}$
    EnterpriseIdentificationNumber:
      type: string
      pattern: ^(\d{10}|(\d{10}-\d{3}))$
    EntityExemptionAccountStatus:
      type: string
      enum:
      - None
      - Valid
      - Expired
      - Pending
    ErrorCode:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 50
    ErrorMessage:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 1024
    ExemptionDocumentName:
      type: string
      pattern: ^([A-Za-z0-9-_.]+).(pdf|jpg|png)$
      minLength: 0
      maxLength: 128
    ExemptionFileBlob:
      type: string
      format: byte
      minLength: 1
      maxLength: 4194304
    FieldName:
      type: string
      pattern: ^(?!\s*$)[\s\S]+$
    FileBlob:
      type: string
      format: byte
      minLength: 1
      maxLength: 5242880
    GenericString:
      type: string
      pattern: ^[\s\S]*$
      minLength: 1
      maxLength: 200
    HeritageStatus:
      type: string
      enum:
      - OptIn
      - OptOut
    IndividualRegistrationNumber:
      type: string
      pattern: ^([0-9]{10})$
    IndonesiaTaxRegistrationNumberType:
      type: string
      enum:
      - NIK
      - PassportNumber
      - NPWP
      - NITKU
    Industries:
      type: string
      enum:
      - CirculatingOrg
      - ProfessionalOrg
      - Banks
      - Insurance
      - PensionAndBenefitFunds
      - DevelopmentAgencies
    InheritanceObtainedReason:
      type: string
      pattern: ^[\s\S]*$
    IsraelCustomerType:
      type: string
      enum:
      - Business
      - Individual
    IsraelDealerType:
      type: string
      enum:
      - Authorized
      - Non-authorized
    ItemOfBusiness:
      type: string
      pattern: ^[0-9\u3130-\u318F\uAC00-\uD7AF,.( )-\\s]*$
      minLength: 1
      maxLength: 100
    KepEmailId:
      type: string
      pattern: ^[\s\S]*$
    LegalName:
      type: string
      pattern: ^(?!\s*$)[\s\S]+$
      minLength: 1
      maxLength: 200
    LegalNatureCode:
      type: string
      pattern: ^\d+$
      maxLength: 1024
    LineOfBusiness:
      type: string
      pattern: ^[0-9\u3130-\u318F\uAC00-\uD7AF,.( )-\\s]*$
      minLength: 1
      maxLength: 100
    MalaysiaServiceTaxCode:
      type: string
      enum:
      - Consultancy
      - Digital Service And Electronic Medium
      - IT Services
      - Training Or Coaching
    MalaysiaServiceTaxCodesList:
      type: array
      items:
        $ref: '#/components/schemas/MalaysiaServiceTaxCode'
    MaxResults:
      type: integer
      minimum: 1
      maximum: 1000
    PaginationTokenString:
      type: string
      pattern: ^[-A-Za-z0-9_+\=\/]+$
      minLength: 1
      maxLength: 2000
    Pan:
      type: string
      pattern: ^[A-Z]{5}[0-9]{4}[A-Z]{1}$
    PaymentVoucherNumber:
      type: string
      pattern: ^(\d{17}|[A-Za-z]{3}\d{13})$
    PersonType:
      type: string
      enum:
      - Legal Person
      - Physical Person
      - Business
    PostalCode:
      type: string
      pattern: ^(?!\s*$)[\s\S]+$
      minLength: 1
      maxLength: 20
    PpnExceptionDesignationCode:
      type: string
      pattern: ^(01|02|03|07|08)$
    RegistrationId:
      type: string
      pattern: ^(?!\s*$)[\s\S]+$
      minLength: 1
      maxLength: 200
    RegistrationType:
      type: string
      enum:
      - Intra-EU
      - Local
    RegistryCommercialCode:
      type: string
      pattern: ^\d+$
      minLength: 8
      maxLength: 8
    S3BucketName:
      type: string
      pattern: ^(?=^.{3,63}$)(?!^(\d+\.)+\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$)$
      minLength: 3
      maxLength: 63
    S3Key:
      type: string
      pattern: ^.*\S.*$
      minLength: 1
      maxLength: 1024
    S3Prefix:
      type: string
      pattern: ^.*\S.*$
      minLength: 0
      maxLength: 512
    SaudiArabiaTaxRegistrationNumberType:
      type: string
      enum:
      - TaxRegistrationNumber
      - TaxIdentificationNumber
      - CommercialRegistrationNumber
    SdiAccountId:
      type: string
      pattern: ^[0-9A-Z]{6,7}$
    SecondaryTaxId:
      type: string
      pattern: ^([0-9]{10})$
    Sector:
      type: string
      enum:
      - Business
      - Individual
      - Government
    Seller:
      type: string
      pattern: ^[\s\S]*$
    State:
      type: string
      pattern: ^(?!\s*$)[\s\S]+$
      minLength: 1
      maxLength: 50
    SupplementalTaxRegistrationList:
      type: array
      items:
        $ref: '#/components/schemas/SupplementalTaxRegistration'
    SupplementalTaxRegistrationType:
      type: string
      enum:
      - VAT
    TaxCode:
      type: string
      pattern: ^([0-9]{11}|[A-Z]{6}[0-9]{2}[A-Z][0-9]{2}[A-Z][0-9]{3}[A-Z])$
    TaxDocumentAccessToken:
      type: string
      pattern: ^[\s\S]*$
    TaxDocumentMetadatas:
      type: array
      items:
        $ref: '#/components/schemas/TaxDocumentMetadata'
    TaxDocumentName:
      type: string
      pattern: ^[\s\S]*$
    TaxExemptionDetailsMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TaxExemptionDetails'
    TaxExemptionTypes:
      type: array
      items:
        $ref: '#/components/schemas/TaxExemptionType'
    TaxExemptions:
      type: array
      items:
        $ref: '#/components/schemas/TaxExemption'
    TaxInformationNumber:
      type: string
      pattern: ^[A-Z]{1,2}[0-9]{1,11}$
    TaxOffice:
      type: string
      pattern: ^[\s\S]*$
    TaxRegistrationDocuments:
      type: array
      items:
        $ref: '#/components/schemas/TaxRegistrationDocument'
    TaxRegistrationNumberType:
      type: string
      enum:
      - TaxRegistrationNumber
      - LocalRegistrationNumber
    TaxRegistrationStatus:
      type: string
      enum:
      - Verified
      - Pending
      - Deleted
      - Rejected
    TaxRegistrationType:
      type: string
      enum:
      - VAT
      - GST
      - CPF
      - CNPJ
      - SST
      - TIN
      - NRIC
    UkraineTrnType:
      type: string
      enum:
      - Business
      - Individual
    UniqueIdentificationNumber:
      type: string
      pattern: ^[a-zA-Z0-9]{39}$
    Url:
      type: string
      pattern: ^https.*\S.*$
      minLength: 1
      maxLength: 200
    UzbekistanTaxRegistrationNumberType:
      type: string
      enum:
      - Business
      - Individual
    ValidationExceptionErrorCode:
      type: string
      enum:
      - MalformedToken
      - ExpiredToken
      - InvalidToken
      - FieldValidationFailed
      - MissingInput
    ValidationExceptionFieldList:
      type: array
      items:
        $ref: '#/components/schemas/ValidationExceptionField'
    VatRegistrationNumber:
      type: string
      pattern: ^[0-9]{12}$
