openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: tnb
  x-aws-serviceName: tnb
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2008-10-21'
  title: AWS Telco Network Builder
  description: |-
    Amazon Web Services Telco Network Builder (TNB) is a network automation service that helps you deploy and manage telecom networks. AWS TNB helps you with the lifecycle management of your telecommunication network functions throughout planning, deployment, and post-deployment activities.
servers:
- description: The AWS Telco Network Builder regional endpoint
  url: https://tnb.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    DescriptorContentType:
      type: string
      enum:
      - text/plain
    ErrorCause:
      type: string
      minLength: 1
      maxLength: 200
    ErrorDetails:
      type: string
      maxLength: 10240
    GetSolNetworkOperationTasksList:
      type: array
      items:
        $ref: '#/components/schemas/GetSolNetworkOperationTaskDetails'
    GetSolVnfcResourceInfoList:
      type: array
      items:
        $ref: '#/components/schemas/GetSolVnfcResourceInfo'
    LcmOperationType:
      type: string
      enum:
      - INSTANTIATE
      - UPDATE
      - TERMINATE
    ListSolFunctionInstanceResources:
      type: array
      items:
        $ref: '#/components/schemas/ListSolFunctionInstanceInfo'
    ListSolFunctionPackageResources:
      type: array
      items:
        $ref: '#/components/schemas/ListSolFunctionPackageInfo'
    ListSolNetworkInstanceResources:
      type: array
      items:
        $ref: '#/components/schemas/ListSolNetworkInstanceInfo'
    ListSolNetworkOperationsResources:
      type: array
      items:
        $ref: '#/components/schemas/ListSolNetworkOperationsInfo'
    ListSolNetworkPackageResources:
      type: array
      items:
        $ref: '#/components/schemas/ListSolNetworkPackageInfo'
    NsInstanceArn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-iso|aws-iso-b|aws-us-gov):tnb:([a-z]{2}(-(gov|isob|iso))?-(east|west|north|south|central){1,2}-[0-9]):\d{12}:(network-instance/ni-[a-f0-9]{17})$
    NsInstanceId:
      type: string
      pattern: ^ni-[a-f0-9]{17}$
    NsLcmOpOccArn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-iso|aws-iso-b|aws-us-gov):tnb:([a-z]{2}(-(gov|isob|iso))?-(east|west|north|south|central){1,2}-[0-9]):\d{12}:(network-operation/no-[a-f0-9]{17})$
    NsLcmOpOccId:
      type: string
      pattern: ^no-[a-f0-9]{17}$
    NsLcmOperationState:
      type: string
      enum:
      - PROCESSING
      - COMPLETED
      - FAILED
      - CANCELLING
      - CANCELLED
    NsState:
      type: string
      enum:
      - INSTANTIATED
      - NOT_INSTANTIATED
      - UPDATED
      - IMPAIRED
      - UPDATE_FAILED
      - STOPPED
      - DELETED
      - INSTANTIATE_IN_PROGRESS
      - INTENT_TO_UPDATE_IN_PROGRESS
      - UPDATE_IN_PROGRESS
      - TERMINATE_IN_PROGRESS
    NsdId:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
    NsdInfoArn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-iso|aws-iso-b|aws-us-gov):tnb:([a-z]{2}(-(gov|isob|iso))?-(east|west|north|south|central){1,2}-[0-9]):\d{12}:(network-package/np-[a-f0-9]{17})$
    NsdInfoId:
      type: string
      pattern: ^np-[a-f0-9]{17}$
    NsdOnboardingState:
      type: string
      enum:
      - CREATED
      - ONBOARDED
      - ERROR
    NsdOperationalState:
      type: string
      enum:
      - ENABLED
      - DISABLED
    NsdUsageState:
      type: string
      enum:
      - IN_USE
      - NOT_IN_USE
    OnboardingState:
      type: string
      enum:
      - CREATED
      - ONBOARDED
      - ERROR
    OperationalState:
      type: string
      enum:
      - ENABLED
      - DISABLED
    OverrideList:
      type: array
      items:
        $ref: '#/components/schemas/ToscaOverride'
    PackageContentType:
      type: string
      enum:
      - application/zip
    PaginationToken:
      type: string
    SensitiveBlob:
      type: string
      format: byte
      x-sensitive: true
    StringMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    TNBResourceArn:
      type: string
      pattern: ^arn:aws:tnb:[a-z0-9-]+:[^:]*:.*$
    TagKey:
      type: string
      pattern: ^(?!aws:).{1,128}$
    TagKeys:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TaskStatus:
      type: string
      enum:
      - SCHEDULED
      - STARTED
      - IN_PROGRESS
      - COMPLETED
      - ERROR
      - SKIPPED
      - CANCELLED
    UpdateSolNetworkType:
      type: string
      enum:
      - MODIFY_VNF_INFORMATION
      - UPDATE_NS
    UsageState:
      type: string
      enum:
      - IN_USE
      - NOT_IN_USE
    VnfInstanceArn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-iso|aws-iso-b|aws-us-gov):tnb:([a-z]{2}(-(gov|isob|iso))?-(east|west|north|south|central){1,2}-[0-9]):\d{12}:(function-instance/fi-[a-f0-9]{17})$
    VnfInstanceId:
      type: string
      pattern: ^fi-[a-f0-9]{17}$
    VnfInstantiationState:
      type: string
      enum:
      - INSTANTIATED
      - NOT_INSTANTIATED
    VnfOperationalState:
      type: string
      enum:
      - STARTED
      - STOPPED
    VnfPkgArn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-iso|aws-iso-b|aws-us-gov):tnb:([a-z]{2}(-(gov|isob|iso))?-(east|west|north|south|central){1,2}-[0-9]):\d{12}:(function-package/fp-[a-f0-9]{17})$
    VnfPkgId:
      type: string
      pattern: ^fp-[a-f0-9]{17}$
    VnfPkgIdList:
      type: array
      items:
        $ref: '#/components/schemas/VnfPkgId'
    VnfdId:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
