openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: transcribe_streaming
  x-aws-serviceName: transcribestreaming
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2017-10-26'
  title: Amazon Transcribe Streaming Service
  description: |-
    Amazon Transcribe streaming offers four main types of real-time transcription: **Standard** , **Medical** , **Call Analytics** , and **Health Scribe**.

      * **Standard transcriptions** are the most common option. Refer to for details.

      * **Medical transcriptions** are tailored to medical professionals and incorporate medical terms. A common use case for this service is transcribing doctor-patient dialogue in real time, so doctors can focus on their patient instead of taking notes. Refer to for details.

      * **Call Analytics transcriptions** are designed for use with call center audio on two different channels; if you're looking for insight into customer service calls, use this option. Refer to for details.

      * **HealthScribe transcriptions** are designed to automatically create clinical notes from patient-clinician conversations using generative AI. Refer to [here] for details.
servers:
- description: The Amazon Transcribe Streaming Service regional endpoint
  url: https://transcribestreaming.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Boolean:
      type: boolean
      default: false
    BucketName:
      type: string
      pattern: ^[a-z0-9][\.\-a-z0-9]{1,61}[a-z0-9]$
      minLength: 0
      maxLength: 64
    ChannelId:
      type: integer
      default: 0
      minimum: 0
      maximum: 1
    IamRoleArn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-us-gov|aws-iso-{0,1}[a-z]{0,1}):iam::[0-9]{0,63}:role/[A-Za-z0-9:_/+=,@.-]{0,1024}$
      minLength: 20
      maxLength: 2048
    Integer:
      type: integer
    KMSKeyId:
      type: string
      pattern: ^[A-Za-z0-9][A-Za-z0-9:_/+=,@.-]{0,2048}$
      minLength: 1
      maxLength: 2048
    LanguageOptions:
      type: string
      pattern: ^[a-zA-Z-,]+$
      minLength: 1
      maxLength: 200
    MediaSampleRateHertz:
      type: integer
      minimum: 8000
      maximum: 48000
    MedicalScribeChannelId:
      type: integer
      default: 0
      minimum: 0
      maximum: 1
    MedicalScribeMediaSampleRateHertz:
      type: integer
      minimum: 16000
      maximum: 48000
    ModelName:
      type: string
      pattern: ^[0-9a-zA-Z._-]+$
      minLength: 1
      maxLength: 200
    NonEmptyString:
      type: string
      pattern: \S
      minLength: 1
      maxLength: 2000
    NullableBoolean:
      type: boolean
    NumberOfChannels:
      type: integer
      minimum: 2
    PiiEntityTypes:
      type: string
      pattern: ^[A-Z_, ]+$
      minLength: 1
      maxLength: 300
    RequestId:
      type: string
    SessionId:
      type: string
      pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$
      minLength: 36
      maxLength: 36
    Stable:
      type: boolean
    String:
      type: string
    Uri:
      type: string
      pattern: ^(s3://|http(s*)://).+$
      minLength: 1
      maxLength: 2000
    VocabularyFilterName:
      type: string
      pattern: ^[0-9a-zA-Z._-]+$
      minLength: 1
      maxLength: 200
    VocabularyFilterNames:
      type: string
      pattern: ^[a-zA-Z0-9,-._]+$
      minLength: 1
      maxLength: 3000
    VocabularyName:
      type: string
      pattern: ^[0-9a-zA-Z._-]+$
      minLength: 1
      maxLength: 200
    VocabularyNames:
      type: string
      pattern: ^[a-zA-Z0-9,-._]+$
      minLength: 1
      maxLength: 3000
