openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: trustedadvisor
  x-aws-serviceName: trustedadvisor
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2022-09-15'
  title: TrustedAdvisor Public API
  description: |-
    TrustedAdvisor Public API
servers:
- description: The TrustedAdvisor Public API regional endpoint
  url: https://trustedadvisor.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccountId:
      type: string
      pattern: ^\d+$
      minLength: 12
      maxLength: 12
    AccountRecommendationArn:
      type: string
      pattern: ^arn:[\w-]+:trustedadvisor::\d{12}:recommendation\/[\w-]+$
      minLength: 20
      maxLength: 2048
    AccountRecommendationIdentifier:
      type: string
      pattern: ^arn:[\w-]+:trustedadvisor::\d{12}:recommendation\/[\w-]+$
      minLength: 20
      maxLength: 200
    AccountRecommendationLifecycleSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/AccountRecommendationLifecycleSummary'
    CheckArn:
      type: string
      pattern: ^arn:[\w-]+:trustedadvisor:::check\/[\w-]+$
      minLength: 20
      maxLength: 2048
    CheckIdentifier:
      type: string
      pattern: ^arn:[\w-]+:trustedadvisor:::check\/[\w-]+$
      minLength: 20
      maxLength: 64
    CheckSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/CheckSummary'
    ExclusionStatus:
      type: string
      enum:
      - excluded
      - included
    OrganizationRecommendationArn:
      type: string
      pattern: ^arn:[\w-]+:trustedadvisor:::organization-recommendation\/[\w-]+$
      minLength: 20
      maxLength: 2048
    OrganizationRecommendationIdentifier:
      type: string
      pattern: ^arn:[\w-]+:trustedadvisor:::organization-recommendation\/[\w-]+$
      minLength: 20
      maxLength: 200
    OrganizationRecommendationResourceSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/OrganizationRecommendationResourceSummary'
    OrganizationRecommendationSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/OrganizationRecommendationSummary'
    RecommendationAwsService:
      type: string
      minLength: 2
      maxLength: 30
    RecommendationAwsServiceList:
      type: array
      items:
        $ref: '#/components/schemas/RecommendationAwsService'
    RecommendationLanguage:
      type: string
      enum:
      - en
      - ja
      - zh
      - fr
      - de
      - ko
      - zh_TW
      - it
      - es
      - pt_BR
      - id
    RecommendationLifecycleStage:
      type: string
      enum:
      - in_progress
      - pending_response
      - dismissed
      - resolved
    RecommendationPillar:
      type: string
      enum:
      - cost_optimizing
      - performance
      - security
      - service_limits
      - fault_tolerance
      - operational_excellence
    RecommendationPillarList:
      type: array
      items:
        $ref: '#/components/schemas/RecommendationPillar'
    RecommendationRegionCode:
      type: string
      minLength: 9
      maxLength: 20
    RecommendationResourceArn:
      type: string
      pattern: ^arn:[\w-]+:trustedadvisor::\d{12}:recommendation-resource\/[\w-]+\/[\w-]+$
      minLength: 20
      maxLength: 2048
    RecommendationResourceExclusionList:
      type: array
      items:
        $ref: '#/components/schemas/RecommendationResourceExclusion'
    RecommendationResourceSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/RecommendationResourceSummary'
    RecommendationSource:
      type: string
      enum:
      - aws_config
      - compute_optimizer
      - cost_explorer
      - lse
      - manual
      - pse
      - rds
      - resilience
      - resilience_hub
      - security_hub
      - stir
      - ta_check
      - well_architected
    RecommendationStatus:
      type: string
      enum:
      - ok
      - warning
      - error
    RecommendationSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/RecommendationSummary'
    RecommendationType:
      type: string
      enum:
      - standard
      - priority
    RecommendationUpdateReason:
      type: string
      pattern: ^[\s\S]*$
      minLength: 10
      maxLength: 4096
    ResourceStatus:
      type: string
      enum:
      - ok
      - warning
      - error
    StringMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    UpdateRecommendationLifecycleStage:
      type: string
      enum:
      - pending_response
      - in_progress
      - dismissed
      - resolved
    UpdateRecommendationLifecycleStageReasonCode:
      type: string
      enum:
      - non_critical_account
      - temporary_account
      - valid_business_case
      - other_methods_available
      - low_priority
      - not_applicable
      - other
    UpdateRecommendationResourceExclusionErrorList:
      type: array
      items:
        $ref: '#/components/schemas/UpdateRecommendationResourceExclusionError'
