openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: vpc_lattice
  x-aws-serviceName: vpclattice
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2022-11-30'
  title: Amazon VPC Lattice
  description: |-
    Amazon VPC Lattice is a fully managed application networking service that you use to connect, secure, and monitor all of your services across multiple accounts and virtual private clouds (VPCs). Amazon VPC Lattice interconnects your microservices and legacy services within a logical boundary, so that you can discover and manage them more efficiently. For more information, see the [Amazon VPC Lattice User Guide](https://docs.aws.amazon.com/vpc-lattice/latest/ug/)
servers:
- description: The Amazon VPC Lattice regional endpoint
  url: https://vpc-lattice.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AccessLogDestinationArn:
      type: string
      pattern: ^arn(:[a-z0-9]+([.-][a-z0-9]+)*){2}(:([a-z0-9]+([.-][a-z0-9]+)*)?){2}:([^/].*)?$
      minLength: 20
      maxLength: 2048
    AccessLogSubscriptionArn:
      type: string
      pattern: ^arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:accesslogsubscription/als-[0-9a-z]{17}$
      minLength: 20
      maxLength: 2048
    AccessLogSubscriptionId:
      type: string
      pattern: ^als-[0-9a-z]{17}$
      minLength: 21
      maxLength: 21
    AccessLogSubscriptionIdentifier:
      type: string
      pattern: ^((als-[0-9a-z]{17})|(arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:accesslogsubscription/als-[0-9a-z]{17}))$
      minLength: 17
      maxLength: 2048
    AccountId:
      type: string
      pattern: ^[0-9]{12}$
      minLength: 1
      maxLength: 12
    Arn:
      type: string
      pattern: ^arn:[a-z0-9][-.a-z0-9]{0,62}:vpc-lattice:([a-z0-9][-.a-z0-9]{0,62})?:\d{12}?:[^/].{0,1023}$
      maxLength: 1224
    AuthPolicyState:
      type: string
      enum:
      - Active
      - Inactive
    AuthPolicyString:
      type: string
      maxLength: 10000
    AuthType:
      type: string
      enum:
      - NONE
      - AWS_IAM
    Boolean:
      type: boolean
    CertificateArn:
      type: string
      pattern: ^(arn(:[a-z0-9]+([.-][a-z0-9]+)*){2}(:([a-z0-9]+([.-][a-z0-9]+)*)?){2}:certificate/[0-9a-z-]+)?$
      maxLength: 2048
    ClientToken:
      type: string
      pattern: '[!-~]+'
      minLength: 1
      maxLength: 64
    DomainName:
      type: string
      minLength: 3
      maxLength: 255
    FailureCode:
      type: string
    FailureMessage:
      type: string
    HeaderMatchContains:
      type: string
      minLength: 1
      maxLength: 200
    HeaderMatchExact:
      type: string
      minLength: 1
      maxLength: 200
    HeaderMatchName:
      type: string
      minLength: 1
      maxLength: 100
    HeaderMatchPrefix:
      type: string
      minLength: 1
      maxLength: 200
    HealthCheckIntervalSeconds:
      type: integer
      minimum: 0
      maximum: 300
    HealthCheckPath:
      type: string
      pattern: (^/[a-zA-Z0-9@:%_+.~#?&/=-]*$|(^$))
      minLength: 0
      maxLength: 2048
    HealthCheckPort:
      type: integer
      minimum: 0
      maximum: 65535
    HealthCheckProtocolVersion:
      type: string
      enum:
      - HTTP1
      - HTTP2
    HealthCheckTimeoutSeconds:
      type: integer
      minimum: 0
      maximum: 120
    HealthyThresholdCount:
      type: integer
      minimum: 0
      maximum: 10
    HttpCodeMatcher:
      type: string
      pattern: (^[0-9-,]+$|(^$))
      minLength: 0
      maxLength: 2000
    HttpMethod:
      type: string
      maxLength: 16
    HttpStatusCode:
      type: integer
      minimum: 100
      maximum: 599
    IpAddress:
      type: string
      minLength: 4
      maxLength: 39
    IpAddressType:
      type: string
      enum:
      - IPV4
      - IPV6
    LambdaEventStructureVersion:
      type: string
      enum:
      - V1
      - V2
    ListenerArn:
      type: string
      pattern: ^arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:service/svc-[0-9a-z]{17}/listener/listener-[0-9a-z]{17}$
      minLength: 20
      maxLength: 2048
    ListenerId:
      type: string
      pattern: ^listener-[0-9a-z]{17}$
      minLength: 26
      maxLength: 26
    ListenerIdentifier:
      type: string
      pattern: ^((listener-[0-9a-z]{17})|(^arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:service/svc-[0-9a-z]{17}/listener/listener-[0-9a-z]{17}$))$
      minLength: 20
      maxLength: 2048
    ListenerName:
      type: string
      pattern: ^(?!listener-)(?![-])(?!.*[-]$)(?!.*[-]{2})[a-z0-9-]+$
      minLength: 3
      maxLength: 63
    ListenerProtocol:
      type: string
      enum:
      - HTTP
      - HTTPS
      - TLS_PASSTHROUGH
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    NextToken:
      type: string
      minLength: 1
      maxLength: 2048
    PathMatchExact:
      type: string
      pattern: ^/[a-zA-Z0-9@:%_+.~#?&/=-]*$
      minLength: 1
      maxLength: 200
    PathMatchPrefix:
      type: string
      pattern: ^/[a-zA-Z0-9@:%_+.~#?&/=-]*$
      minLength: 1
      maxLength: 200
    PolicyString:
      type: string
      pattern: ^.*\S.*$
      minLength: 1
      maxLength: 10000
    Port:
      type: integer
      minimum: 1
      maximum: 65535
    PortRange:
      type: string
      pattern: ^((\d{1,5}\-\d{1,5})|(\d+))$
      minLength: 1
      maxLength: 11
    ProtocolType:
      type: string
      enum:
      - TCP
    ResourceArn:
      type: string
      pattern: ^arn(:[a-z0-9]+([.-][a-z0-9]+)*){2}(:([a-z0-9]+([.-][a-z0-9]+)*)?){2}:((servicenetwork/sn)|(service/svc)|(resourceconfiguration/rcfg))-[0-9a-z]{17}$
      minLength: 20
      maxLength: 200
    ResourceConfigurationArn:
      type: string
      pattern: ^arn:[a-z0-9f\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:resourceconfiguration/rcfg-[0-9a-z]{17}$
      minLength: 20
      maxLength: 2048
    ResourceConfigurationId:
      type: string
      pattern: ^rcfg-[0-9a-z]{17}$
      minLength: 22
      maxLength: 22
    ResourceConfigurationIdentifier:
      type: string
      pattern: ^((rcfg-[0-9a-z]{17})|(arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:resourceconfiguration/rcfg-[0-9a-z]{17}))$
      minLength: 20
      maxLength: 2048
    ResourceConfigurationIpAddressType:
      type: string
      enum:
      - IPV4
      - IPV6
      - DUALSTACK
    ResourceConfigurationName:
      type: string
      pattern: ^(?!rcfg-)(?![-])(?!.*[-]$)(?!.*[-]{2})[a-z0-9-]+$
      minLength: 3
      maxLength: 40
    ResourceConfigurationStatus:
      type: string
      enum:
      - ACTIVE
      - CREATE_IN_PROGRESS
      - UPDATE_IN_PROGRESS
      - DELETE_IN_PROGRESS
      - CREATE_FAILED
      - UPDATE_FAILED
      - DELETE_FAILED
    ResourceConfigurationType:
      type: string
      enum:
      - GROUP
      - CHILD
      - SINGLE
      - ARN
    ResourceEndpointAssociationArn:
      type: string
      pattern: ^arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:resourceendpointassociation/rea-[0-9a-f]{17}$
      minLength: 21
      maxLength: 2048
    ResourceEndpointAssociationId:
      type: string
      pattern: ^rea-[0-9a-f]{17}$
      minLength: 21
      maxLength: 21
    ResourceEndpointAssociationIdentifier:
      type: string
      pattern: ^((rea-[0-9a-f]{17})|(arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:resourceendpointassociation/rea-[0-9a-f]{17}))$
      minLength: 21
      maxLength: 2048
    ResourceGatewayArn:
      type: string
      pattern: ^arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:resourcegateway/rgw-[0-9a-z]{17}$
      minLength: 20
      maxLength: 2048
    ResourceGatewayId:
      type: string
      pattern: ^rgw-[0-9a-z]{17}$
      minLength: 21
      maxLength: 21
    ResourceGatewayIdentifier:
      type: string
      pattern: ^((rgw-[0-9a-z]{17})|(arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:resourcegateway/rgw-[0-9a-z]{17}))$
      minLength: 17
      maxLength: 2048
    ResourceGatewayIpAddressType:
      type: string
      enum:
      - IPV4
      - IPV6
      - DUALSTACK
    ResourceGatewayName:
      type: string
      pattern: ^(?!rgw-)(?![-])(?!.*[-]$)(?!.*[-]{2})[a-z0-9-]+$
      minLength: 3
      maxLength: 40
    ResourceGatewayStatus:
      type: string
      enum:
      - ACTIVE
      - CREATE_IN_PROGRESS
      - UPDATE_IN_PROGRESS
      - DELETE_IN_PROGRESS
      - CREATE_FAILED
      - UPDATE_FAILED
      - DELETE_FAILED
    ResourceId:
      type: string
      pattern: ^((sn)|(svc))-[0-9a-z]{17}$
      minLength: 20
      maxLength: 50
    ResourceIdentifier:
      type: string
      pattern: ^((((sn)|(svc)|(rcfg))-[0-9a-z]{17})|(arn(:[a-z0-9]+([.-][a-z0-9]+)*){2}(:([a-z0-9]+([.-][a-z0-9]+)*)?){2}:((servicenetwork/sn)|(resourceconfiguration/rcfg)|(service/svc))-[0-9a-z]{17}))$
      minLength: 17
      maxLength: 200
    RuleArn:
      type: string
      pattern: ^arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:service/svc-[0-9a-z]{17}/listener/listener-[0-9a-z]{17}/rule/rule-[0-9a-z]{17}$
      minLength: 20
      maxLength: 2048
    RuleId:
      type: string
      pattern: ^rule-[0-9a-z]{17}$
      minLength: 5
      maxLength: 22
    RuleIdentifier:
      type: string
      pattern: ^((rule-[0-9a-z]{17})|(^arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:service/svc-[0-9a-z]{17}/listener/listener-[0-9a-z]{17}/rule/rule-[0-9a-z]{17}$))$
      minLength: 20
      maxLength: 2048
    RuleName:
      type: string
      pattern: ^(?!rule-)(?![-])(?!.*[-]$)(?!.*[-]{2})[a-z0-9-]+$
      minLength: 3
      maxLength: 63
    RulePriority:
      type: integer
      minimum: 1
      maximum: 100
    SecurityGroupId:
      type: string
      pattern: ^sg-(([0-9a-z]{8})|([0-9a-z]{17}))$
      minLength: 5
      maxLength: 200
    ServiceArn:
      type: string
      pattern: ^arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:service/svc-[0-9a-z]{17}$
      minLength: 20
      maxLength: 2048
    ServiceCustomDomainName:
      type: string
      minLength: 3
      maxLength: 255
    ServiceId:
      type: string
      pattern: ^svc-[0-9a-z]{17}$
      minLength: 21
      maxLength: 21
    ServiceIdentifier:
      type: string
      pattern: ^((svc-[0-9a-z]{17})|(arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:service/svc-[0-9a-z]{17}))$
      minLength: 17
      maxLength: 2048
    ServiceLoadBalancerAssociationIdentifier:
      type: string
      pattern: ^((slba-[0-9a-z]{17})|(arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:serviceloadbalancerassociation/slba-[0-9a-z]{17}))$
      minLength: 17
      maxLength: 200
    ServiceName:
      type: string
      pattern: ^(?!svc-)(?![-])(?!.*[-]$)(?!.*[-]{2})[a-z0-9-]+$
      minLength: 3
      maxLength: 40
    ServiceNetworkArn:
      type: string
      pattern: ^arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:servicenetwork/sn-[0-9a-z]{17}$
      minLength: 32
      maxLength: 2048
    ServiceNetworkArnWithoutRegex:
      type: string
      minLength: 10
      maxLength: 2048
    ServiceNetworkId:
      type: string
      pattern: ^sn-[0-9a-z]{17}$
      minLength: 20
      maxLength: 20
    ServiceNetworkIdentifier:
      type: string
      pattern: ^((sn-[0-9a-z]{17})|(arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:servicenetwork/sn-[0-9a-z]{17}))$
      minLength: 3
      maxLength: 2048
    ServiceNetworkIdentifierWithoutRegex:
      type: string
      minLength: 3
      maxLength: 2048
    ServiceNetworkLogType:
      type: string
      enum:
      - SERVICE
      - RESOURCE
    ServiceNetworkName:
      type: string
      pattern: ^(?![-])(?!.*[-]$)(?!.*[-]{2})[a-z0-9-]+$
      minLength: 3
      maxLength: 63
    ServiceNetworkNameWithoutRegex:
      type: string
      minLength: 3
      maxLength: 100
    ServiceNetworkResourceAssociationArn:
      type: string
      pattern: ^arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:servicenetworkresourceassociation/snra-[0-9a-f]{17}$
      minLength: 22
      maxLength: 2048
    ServiceNetworkResourceAssociationId:
      type: string
      pattern: ^snra-[0-9a-f]{17}$
      minLength: 22
      maxLength: 22
    ServiceNetworkResourceAssociationIdentifier:
      type: string
      pattern: ^((snra-[0-9a-z]{17})|(arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:servicenetworkresourceassociation/snra-[0-9a-f]{17}))$
      minLength: 22
      maxLength: 2048
    ServiceNetworkResourceAssociationStatus:
      type: string
      enum:
      - CREATE_IN_PROGRESS
      - ACTIVE
      - PARTIAL
      - DELETE_IN_PROGRESS
      - CREATE_FAILED
      - DELETE_FAILED
    ServiceNetworkServiceAssociationArn:
      type: string
      pattern: ^arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:servicenetworkserviceassociation/snsa-[0-9a-z]{17}$
      minLength: 20
      maxLength: 2048
    ServiceNetworkServiceAssociationIdentifier:
      type: string
      pattern: ^((snsa-[0-9a-z]{17})|(arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:servicenetworkserviceassociation/snsa-[0-9a-z]{17}))$
      minLength: 17
      maxLength: 2048
    ServiceNetworkServiceAssociationStatus:
      type: string
      enum:
      - CREATE_IN_PROGRESS
      - ACTIVE
      - DELETE_IN_PROGRESS
      - CREATE_FAILED
      - DELETE_FAILED
    ServiceNetworkVpcAssociationArn:
      type: string
      pattern: ^arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:servicenetworkvpcassociation/snva-[0-9a-z]{17}$
      minLength: 20
      maxLength: 2048
    ServiceNetworkVpcAssociationId:
      type: string
      pattern: ^snva-[0-9a-z]{17}$
      minLength: 22
      maxLength: 22
    ServiceNetworkVpcAssociationIdentifier:
      type: string
      pattern: ^((snva-[0-9a-z]{17})|(arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:servicenetworkvpcassociation/snva-[0-9a-z]{17}))$
      minLength: 17
      maxLength: 2048
    ServiceNetworkVpcAssociationStatus:
      type: string
      enum:
      - CREATE_IN_PROGRESS
      - ACTIVE
      - UPDATE_IN_PROGRESS
      - DELETE_IN_PROGRESS
      - CREATE_FAILED
      - DELETE_FAILED
      - UPDATE_FAILED
    ServiceStatus:
      type: string
      enum:
      - ACTIVE
      - CREATE_IN_PROGRESS
      - DELETE_IN_PROGRESS
      - CREATE_FAILED
      - DELETE_FAILED
    SubnetId:
      type: string
      minLength: 5
      maxLength: 200
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TargetGroupArn:
      type: string
      pattern: ^arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:targetgroup/tg-[0-9a-z]{17}$
      minLength: 20
      maxLength: 2048
    TargetGroupId:
      type: string
      pattern: ^tg-[0-9a-z]{17}$
      minLength: 20
      maxLength: 20
    TargetGroupIdentifier:
      type: string
      pattern: ^((tg-[0-9a-z]{17})|(arn:[a-z0-9\-]+:vpc-lattice:[a-zA-Z0-9\-]+:\d{12}:targetgroup/tg-[0-9a-z]{17}))$
      minLength: 17
      maxLength: 2048
    TargetGroupName:
      type: string
      pattern: ^(?!tg-)(?![-])(?!.*[-]$)(?!.*[-]{2})[a-z0-9-]+$
      minLength: 3
      maxLength: 128
    TargetGroupProtocol:
      type: string
      enum:
      - HTTP
      - HTTPS
      - TCP
    TargetGroupProtocolVersion:
      type: string
      enum:
      - HTTP1
      - HTTP2
      - GRPC
    TargetGroupStatus:
      type: string
      enum:
      - CREATE_IN_PROGRESS
      - ACTIVE
      - DELETE_IN_PROGRESS
      - CREATE_FAILED
      - DELETE_FAILED
    TargetGroupType:
      type: string
      enum:
      - IP
      - LAMBDA
      - INSTANCE
      - ALB
    TargetGroupWeight:
      type: integer
      minimum: 0
      maximum: 999
    TargetStatus:
      type: string
      enum:
      - DRAINING
      - UNAVAILABLE
      - HEALTHY
      - UNHEALTHY
      - INITIAL
      - UNUSED
    UnhealthyThresholdCount:
      type: integer
      minimum: 0
      maximum: 10
    ValidationExceptionReason:
      type: string
      enum:
      - unknownOperation
      - cannotParse
      - fieldValidationFailed
      - other
    VpcEndpointId:
      type: string
      pattern: ^vpce-[0-9a-f]{17}$
      minLength: 22
      maxLength: 22
    VpcEndpointOwner:
      type: string
      pattern: ^\d{12}$
      minLength: 12
      maxLength: 12
    VpcId:
      type: string
      pattern: ^vpc-(([0-9a-z]{8})|([0-9a-z]{17}))$
      minLength: 5
      maxLength: 50
    WildcardArn:
      type: string
      pattern: ^arn:[a-z0-9][-.a-z0-9]{0,62}:[a-z0-9][-.a-z0-9]{0,62}:([a-z0-9][-.a-z0-9]{0,62})?:\d{12}?:[^/].{0,1023}$
      minLength: 20
      maxLength: 2048
