openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: wellarchitected
  x-aws-serviceName: wellarchitected
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-03-31'
  title: AWS Well-Architected Tool
  description: |-
    Well-Architected Tool

    This is the _Well-Architected Tool API Reference_. The WA Tool API provides programmatic access to the [Well-Architected Tool](http://aws.amazon.com/well-architected-tool) in the [Amazon Web Services Management Console](https://console.aws.amazon.com/wellarchitected). For information about the Well-Architected Tool, see the [Well-Architected Tool User Guide](https://docs.aws.amazon.com/wellarchitected/latest/userguide/intro.html).
servers:
- description: The AWS Well-Architected Tool regional endpoint
  url: https://wellarchitected.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ApplicationArn:
      type: string
      pattern: ^arn:aws[-a-z]*:servicecatalog:[a-z]{2}(-gov)?-[a-z]+-\d:\d{12}:/applications/[a-z0-9]+$
      minLength: 0
      maxLength: 2084
    AwsAccountId:
      type: string
      pattern: ^[0-9]{12}$
      minLength: 12
      maxLength: 12
    AwsRegion:
      type: string
      minLength: 0
      maxLength: 100
    Base64String:
      type: string
    CheckDescription:
      type: string
    CheckId:
      type: string
    CheckName:
      type: string
    CheckStatusCount:
      type: integer
      minimum: 1
      maximum: 101
    ChoiceContentDisplayText:
      type: string
      minLength: 1
      maxLength: 1024
    ChoiceContentUrl:
      type: string
      minLength: 1
      maxLength: 1024
    ChoiceDescription:
      type: string
      minLength: 1
      maxLength: 1024
    ChoiceId:
      type: string
      minLength: 1
      maxLength: 64
    ChoiceNotes:
      type: string
      minLength: 0
      maxLength: 250
    ChoiceTitle:
      type: string
      minLength: 1
      maxLength: 512
    ClientRequestToken:
      type: string
      minLength: 1
      maxLength: 2048
    Count:
      type: integer
      minimum: 0
      description: <p>A non-negative integer that denotes how many.</p>
    DisplayText:
      type: string
      minLength: 1
      maxLength: 64
    ExceptionMessage:
      type: string
    ExceptionResourceId:
      type: string
    ExceptionResourceType:
      type: string
    FlaggedResources:
      type: integer
      minimum: 1
      maximum: 9999
    GetConsolidatedReportMaxResults:
      type: integer
      minimum: 1
      maximum: 15
    HelpfulResourceUrl:
      type: string
      minLength: 1
      maxLength: 2048
    ImprovementPlanUrl:
      type: string
      minLength: 1
      maxLength: 2048
    IncludeSharedResources:
      type: boolean
    IsApplicable:
      type: boolean
      description: <p>Defines whether this question is applicable to a lens review.</p>
    IsMajorVersion:
      type: boolean
    IsReviewOwnerUpdateAcknowledged:
      type: boolean
    JiraIssueUrl:
      type: string
      minLength: 1
      maxLength: 2048
    JiraProjectKey:
      type: string
      pattern: ^[A-Z][A-Z0-9_]*$
      minLength: 1
      maxLength: 100
    LensAlias:
      type: string
      minLength: 1
      maxLength: 128
    LensArn:
      type: string
    LensDescription:
      type: string
      minLength: 1
      maxLength: 1024
    LensJSON:
      type: string
      minLength: 2
      maxLength: 500000
    LensName:
      type: string
      minLength: 1
      maxLength: 128
    LensNamePrefix:
      type: string
      minLength: 0
      maxLength: 100
    LensOwner:
      type: string
    LensVersion:
      type: string
      minLength: 1
      maxLength: 32
    LensesAppliedCount:
      type: integer
      minimum: 0
    ListAnswersMaxResults:
      type: integer
      minimum: 1
      maximum: 50
    ListLensReviewImprovementsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListNotificationsMaxResults:
      type: integer
      minimum: 1
      maximum: 50
    ListProfileSharesMaxResults:
      type: integer
      minimum: 1
      maximum: 50
    ListReviewTemplateAnswersMaxResults:
      type: integer
      minimum: 1
      maximum: 50
    ListShareInvitationsMaxResults:
      type: integer
      minimum: 1
      maximum: 50
    ListTemplateSharesMaxResults:
      type: integer
      minimum: 1
      maximum: 50
    ListWorkloadSharesMaxResults:
      type: integer
      minimum: 1
      maximum: 50
    ListWorkloadsMaxResults:
      type: integer
      minimum: 1
      maximum: 50
    MaxResults:
      type: integer
      minimum: 1
      maximum: 50
      description: <p>The maximum number of results to return for this request.</p>
    MaxSelectedProfileChoices:
      type: integer
      minimum: 0
    MilestoneName:
      type: string
      minLength: 3
      maxLength: 100
    MilestoneNumber:
      type: integer
      minimum: 1
      maximum: 100
      description: "<p>The milestone number.</p>\n         <p>A workload can have\
        \ a maximum of 100 milestones.</p>"
    MinSelectedProfileChoices:
      type: integer
      minimum: 0
    NextToken:
      type: string
    Notes:
      type: string
      minLength: 0
      maxLength: 2084
    PillarId:
      type: string
      minLength: 1
      maxLength: 64
    PillarName:
      type: string
      minLength: 1
      maxLength: 128
    ProfileArn:
      type: string
      pattern: ^arn:aws[-a-z]*:wellarchitected:[a-z]{2}(-gov)?-[a-z]+-\d:\d{12}:profile/[a-z0-9]+$
      minLength: 0
      maxLength: 2084
    ProfileDescription:
      type: string
      minLength: 3
      maxLength: 100
    ProfileName:
      type: string
      minLength: 3
      maxLength: 100
    ProfileNamePrefix:
      type: string
      minLength: 0
      maxLength: 100
    ProfileVersion:
      type: string
      pattern: ^[A-Za-z0-9-]+$
      minLength: 1
      maxLength: 32
    QuestionDescription:
      type: string
      minLength: 1
      maxLength: 1024
    QuestionId:
      type: string
      minLength: 1
      maxLength: 128
    QuestionTitle:
      type: string
      minLength: 1
      maxLength: 512
    QuotaCode:
      type: string
    ResourceArn:
      type: string
      pattern: ^arn:aws(-us-gov|-iso(-[a-z])?|-cn)?:wellarchitected:[a-z]{2}(-gov|-iso([a-z])?)?-[a-z]+-\d:\d{12}:(review-template)/[a-f0-9]{32}$
      minLength: 50
      maxLength: 250
    SelectedQuestionId:
      type: string
    ServiceCode:
      type: string
    ShareId:
      type: string
      pattern: ^[0-9a-f]{32}$
    ShareInvitationId:
      type: string
      pattern: ^[0-9a-f]{32}$
    SharedWith:
      type: string
      minLength: 12
      maxLength: 2048
    SharedWithPrefix:
      type: string
      minLength: 0
      maxLength: 100
    StatusMessage:
      type: string
      minLength: 1
      maxLength: 512
    Subdomain:
      type: string
      minLength: 1
      maxLength: 100
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    TemplateArn:
      type: string
      pattern: ^arn:aws(-us-gov|-iso(-[a-z])?|-cn)?:wellarchitected:[a-z]{2}(-gov|-iso([a-z])?)?-[a-z]+-\d:\d{12}:(review-template)/[a-f0-9]{32}$
      minLength: 50
      maxLength: 250
    TemplateDescription:
      type: string
      pattern: ^[A-Za-z0-9-_.,:/()@!&?#+'’\s]+$
      minLength: 3
      maxLength: 250
    TemplateName:
      type: string
      pattern: ^[A-Za-z0-9-_.,:/()@!&?#+'’\s]+$
      minLength: 3
      maxLength: 100
    TemplateNamePrefix:
      type: string
      pattern: ^[A-Za-z0-9-_.,:/()@!&?#+'’\s]+$
      minLength: 0
      maxLength: 100
    ValidationExceptionFieldName:
      type: string
    WorkloadArchitecturalDesign:
      type: string
      pattern: ^(|(https?|ftp):\/\/[^\s/$.?#].[^\s]*)$
      minLength: 0
      maxLength: 2048
    WorkloadArn:
      type: string
    WorkloadDescription:
      type: string
      minLength: 3
      maxLength: 250
    WorkloadId:
      type: string
      pattern: ^[0-9a-f]{32}$
      minLength: 32
      maxLength: 32
    WorkloadIndustry:
      type: string
      minLength: 0
      maxLength: 100
    WorkloadIndustryType:
      type: string
      minLength: 0
      maxLength: 100
    WorkloadName:
      type: string
      minLength: 3
      maxLength: 100
    WorkloadNamePrefix:
      type: string
      minLength: 0
      maxLength: 100
    WorkloadNonAwsRegion:
      type: string
      minLength: 3
      maxLength: 25
    WorkloadReviewOwner:
      type: string
      minLength: 3
      maxLength: 255
