openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: wisdom
  x-aws-serviceName: wisdom
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-10-19'
  title: Amazon Connect Wisdom Service
  description: |-
    Amazon Connect Wisdom delivers agents the information they need to solve customer issues as they're actively speaking with customers. Agents can search across connected repositories from within their agent desktop to find answers quickly. Use Amazon Connect Wisdom to create an assistant and a knowledge base, for example, or manage content by uploading custom files.
servers:
- description: The Amazon Connect Wisdom Service regional endpoint
  url: https://wisdom.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Arn:
      type: string
      pattern: ^arn:[a-z-]*?:wisdom:[a-z0-9-]*?:[0-9]{12}:[a-z-]*?/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(?:/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})?$
    AssistantAssociationInputData:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/Uuid'
        description: |-
          The identifier of the knowledge base. This should not be a QUICK_RESPONSES type knowledge base if you're storing Wisdom Content resource to it.
      description: |-
        The data that is input into Wisdom as a result of the assistant association.
    AssistantAssociationOutputData:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/KnowledgeBaseAssociationData'
        description: |-
          The knowledge base where output data is sent.
      description: |-
        The data that is output as a result of the assistant association.
    AssistantAssociationSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/AssistantAssociationSummary'
    AssistantList:
      type: array
      items:
        $ref: '#/components/schemas/AssistantSummary'
    AssistantStatus:
      type: string
      enum:
      - CREATE_IN_PROGRESS
      - CREATE_FAILED
      - ACTIVE
      - DELETE_IN_PROGRESS
      - DELETE_FAILED
      - DELETED
    AssistantType:
      type: string
      enum:
      - AGENT
    AssociationType:
      type: string
      enum:
      - KNOWLEDGE_BASE
    Channel:
      type: string
      minLength: 1
      maxLength: 10
    Channels:
      type: array
      items:
        $ref: '#/components/schemas/Channel'
    ClientToken:
      type: string
      minLength: 1
      maxLength: 4096
    Configuration:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/ConnectConfiguration'
        description: |-
          The configuration information of the Amazon Connect data source.
      description: |-
        The configuration information of the external data source.
    ContactAttributeKey:
      type: string
    ContactAttributeKeys:
      type: array
      items:
        $ref: '#/components/schemas/ContactAttributeKey'
      x-sensitive: true
    ContactAttributeValue:
      type: string
    ContactAttributes:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ContactAttributeValue'
    ContentMetadata:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/NonEmptyString'
    ContentStatus:
      type: string
      enum:
      - CREATE_IN_PROGRESS
      - CREATE_FAILED
      - ACTIVE
      - DELETE_IN_PROGRESS
      - DELETE_FAILED
      - DELETED
      - UPDATE_FAILED
    ContentSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/ContentSummary'
    ContentTitle:
      type: string
      minLength: 1
      maxLength: 255
    ContentType:
      type: string
      pattern: ^(text/(plain|html|csv))|(application/(pdf|vnd\.openxmlformats-officedocument\.wordprocessingml\.document))|(application/x\.wisdom-json;source=(salesforce|servicenow|zendesk))$
    Description:
      type: string
      pattern: ^[a-zA-Z0-9\s_.,-]+
      minLength: 1
      maxLength: 255
    ExternalSource:
      type: string
      enum:
      - AMAZON_CONNECT
    FilterField:
      type: string
      enum:
      - NAME
    FilterList:
      type: array
      items:
        $ref: '#/components/schemas/Filter'
    FilterOperator:
      type: string
      enum:
      - EQUALS
    GenericArn:
      type: string
      pattern: ^arn:[a-z-]+?:[a-z-]+?:[a-z0-9-]*?:([0-9]{12})?:[a-zA-Z0-9-:/]+$
      minLength: 1
      maxLength: 2048
    GroupingCriteria:
      type: string
      minLength: 1
      maxLength: 100
    GroupingValue:
      type: string
      minLength: 1
      maxLength: 2048
    GroupingValues:
      type: array
      items:
        $ref: '#/components/schemas/GroupingValue'
    Headers:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/NonEmptyString'
    HighlightOffset:
      type: integer
      default: 0
    Highlights:
      type: array
      items:
        $ref: '#/components/schemas/Highlight'
    ImportJobList:
      type: array
      items:
        $ref: '#/components/schemas/ImportJobSummary'
    ImportJobStatus:
      type: string
      enum:
      - START_IN_PROGRESS
      - FAILED
      - COMPLETE
      - DELETE_IN_PROGRESS
      - DELETE_FAILED
      - DELETED
    ImportJobType:
      type: string
      enum:
      - QUICK_RESPONSES
    KnowledgeBaseList:
      type: array
      items:
        $ref: '#/components/schemas/KnowledgeBaseSummary'
    KnowledgeBaseStatus:
      type: string
      enum:
      - CREATE_IN_PROGRESS
      - CREATE_FAILED
      - ACTIVE
      - DELETE_IN_PROGRESS
      - DELETE_FAILED
      - DELETED
    KnowledgeBaseType:
      type: string
      enum:
      - EXTERNAL
      - CUSTOM
      - QUICK_RESPONSES
    LanguageCode:
      type: string
      minLength: 2
      maxLength: 5
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    Name:
      type: string
      pattern: ^[a-zA-Z0-9\s_.,-]+
      minLength: 1
      maxLength: 255
    NextToken:
      type: string
      minLength: 1
      maxLength: 2048
    NonEmptyString:
      type: string
      minLength: 1
      maxLength: 4096
    NotifyRecommendationsReceivedErrorList:
      type: array
      items:
        $ref: '#/components/schemas/NotifyRecommendationsReceivedError'
    NotifyRecommendationsReceivedErrorMessage:
      type: string
    ObjectFieldsList:
      type: array
      items:
        $ref: '#/components/schemas/NonEmptyString'
    Order:
      type: string
      enum:
      - ASC
      - DESC
    Priority:
      type: string
      enum:
      - HIGH
      - MEDIUM
      - LOW
    QueryResultsList:
      type: array
      items:
        $ref: '#/components/schemas/ResultData'
    QueryText:
      type: string
    QuickResponseContent:
      type: string
      minLength: 1
      maxLength: 1024
    QuickResponseContentProvider:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/QuickResponseContent'
        description: |-
          The content of the quick response.
      description: |-
        The container quick response content.
    QuickResponseDataProvider:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/QuickResponseContent'
        description: |-
          The content of the quick response.
      description: |-
        The container of quick response data.
    QuickResponseDescription:
      type: string
      minLength: 1
      maxLength: 255
    QuickResponseFilterFieldList:
      type: array
      items:
        $ref: '#/components/schemas/QuickResponseFilterField'
    QuickResponseFilterOperator:
      type: string
      enum:
      - EQUALS
      - PREFIX
    QuickResponseFilterValue:
      type: string
      minLength: 1
      maxLength: 2048
    QuickResponseFilterValueList:
      type: array
      items:
        $ref: '#/components/schemas/QuickResponseFilterValue'
    QuickResponseName:
      type: string
      minLength: 1
      maxLength: 40
    QuickResponseQueryFieldList:
      type: array
      items:
        $ref: '#/components/schemas/QuickResponseQueryField'
    QuickResponseQueryOperator:
      type: string
      enum:
      - CONTAINS
      - CONTAINS_AND_PREFIX
    QuickResponseQueryValue:
      type: string
      minLength: 1
      maxLength: 1024
    QuickResponseQueryValueList:
      type: array
      items:
        $ref: '#/components/schemas/QuickResponseQueryValue'
    QuickResponseSearchResultsList:
      type: array
      items:
        $ref: '#/components/schemas/QuickResponseSearchResultData'
    QuickResponseStatus:
      type: string
      enum:
      - CREATE_IN_PROGRESS
      - CREATE_FAILED
      - CREATED
      - DELETE_IN_PROGRESS
      - DELETE_FAILED
      - DELETED
      - UPDATE_IN_PROGRESS
      - UPDATE_FAILED
    QuickResponseSummaryList:
      type: array
      items:
        $ref: '#/components/schemas/QuickResponseSummary'
    QuickResponseType:
      type: string
      pattern: ^(application/x\.quickresponse;format=(plain|markdown))$
    RecommendationIdList:
      type: array
      items:
        type: string
    RecommendationList:
      type: array
      items:
        $ref: '#/components/schemas/RecommendationData'
    RecommendationSourceType:
      type: string
      enum:
      - ISSUE_DETECTION
      - RULE_EVALUATION
      - OTHER
    RecommendationTriggerData:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/QueryRecommendationTriggerData'
        description: |-
          Data associated with the QUERY RecommendationTriggerType.
      description: |-
        A union type containing information related to the trigger.
    RecommendationTriggerList:
      type: array
      items:
        $ref: '#/components/schemas/RecommendationTrigger'
    RecommendationTriggerType:
      type: string
      enum:
      - QUERY
    RecommendationType:
      type: string
      enum:
      - KNOWLEDGE_CONTENT
    RelevanceLevel:
      type: string
      enum:
      - HIGH
      - MEDIUM
      - LOW
    RelevanceScore:
      type: number
      format: double
      default: 0
      minimum: 0.0
    SensitiveString:
      type: string
    SessionSummaries:
      type: array
      items:
        $ref: '#/components/schemas/SessionSummary'
    ShortCutKey:
      type: string
      minLength: 1
      maxLength: 10
    SourceConfiguration:
      allOf:
      - allOf:
        - $ref: '#/components/schemas/AppIntegrationsConfiguration'
        description: |-
          Configuration information for Amazon AppIntegrations to automatically ingest content.
      description: |-
        Configuration information about the external data source.
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagKeyList:
      type: array
      items:
        $ref: '#/components/schemas/TagKey'
    TagValue:
      type: string
      minLength: 1
      maxLength: 256
    Tags:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TimeToLive:
      type: integer
      minimum: 1
      maximum: 60
      description: Expiration time in minutes
    UploadId:
      type: string
      minLength: 1
      maxLength: 1200
    Uri:
      type: string
      minLength: 1
      maxLength: 4096
    Url:
      type: string
      minLength: 1
      maxLength: 4096
    Uuid:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
    UuidOrArn:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$|^arn:[a-z-]*?:wisdom:[a-z0-9-]*?:[0-9]{12}:[a-z-]*?/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(?:/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})?$
    WaitTimeSeconds:
      type: integer
      default: 0
      minimum: 0
      maximum: 20
