openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: wisdom
  x-aws-serviceName: wisdom
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-10-19'
  title: Amazon Connect Wisdom Service
  description: |-
    Amazon Connect Wisdom delivers agents the information they need to solve customer issues as they're actively speaking with customers. Agents can search across connected repositories from within their agent desktop to find answers quickly. Use Amazon Connect Wisdom to create an assistant and a knowledge base, for example, or manage content by uploading custom files.
servers:
- description: The Amazon Connect Wisdom Service regional endpoint
  url: https://wisdom.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    Arn:
      type: string
      pattern: ^arn:[a-z-]*?:wisdom:[a-z0-9-]*?:[0-9]{12}:[a-z-]*?/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(?:/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})?$
    AssistantStatus:
      type: string
      enum:
      - CREATE_IN_PROGRESS
      - CREATE_FAILED
      - ACTIVE
      - DELETE_IN_PROGRESS
      - DELETE_FAILED
      - DELETED
    AssistantType:
      type: string
      enum:
      - AGENT
    AssociationType:
      type: string
      enum:
      - KNOWLEDGE_BASE
    Channel:
      type: string
      minLength: 1
      maxLength: 10
    ClientToken:
      type: string
      minLength: 1
      maxLength: 4096
    ContactAttributeKey:
      type: string
    ContactAttributeValue:
      type: string
    ContentStatus:
      type: string
      enum:
      - CREATE_IN_PROGRESS
      - CREATE_FAILED
      - ACTIVE
      - DELETE_IN_PROGRESS
      - DELETE_FAILED
      - DELETED
      - UPDATE_FAILED
    ContentTitle:
      type: string
      minLength: 1
      maxLength: 255
    ContentType:
      type: string
      pattern: ^(text/(plain|html|csv))|(application/(pdf|vnd\.openxmlformats-officedocument\.wordprocessingml\.document))|(application/x\.wisdom-json;source=(salesforce|servicenow|zendesk))$
    Description:
      type: string
      pattern: ^[a-zA-Z0-9\s_.,-]+
      minLength: 1
      maxLength: 255
    ExternalSource:
      type: string
      enum:
      - AMAZON_CONNECT
    FilterField:
      type: string
      enum:
      - NAME
    FilterOperator:
      type: string
      enum:
      - EQUALS
    GenericArn:
      type: string
      pattern: ^arn:[a-z-]+?:[a-z-]+?:[a-z0-9-]*?:([0-9]{12})?:[a-zA-Z0-9-:/]+$
      minLength: 1
      maxLength: 2048
    GroupingCriteria:
      type: string
      minLength: 1
      maxLength: 100
    GroupingValue:
      type: string
      minLength: 1
      maxLength: 2048
    HighlightOffset:
      type: integer
      default: 0
    ImportJobStatus:
      type: string
      enum:
      - START_IN_PROGRESS
      - FAILED
      - COMPLETE
      - DELETE_IN_PROGRESS
      - DELETE_FAILED
      - DELETED
    ImportJobType:
      type: string
      enum:
      - QUICK_RESPONSES
    KnowledgeBaseStatus:
      type: string
      enum:
      - CREATE_IN_PROGRESS
      - CREATE_FAILED
      - ACTIVE
      - DELETE_IN_PROGRESS
      - DELETE_FAILED
      - DELETED
    KnowledgeBaseType:
      type: string
      enum:
      - EXTERNAL
      - CUSTOM
      - QUICK_RESPONSES
    LanguageCode:
      type: string
      minLength: 2
      maxLength: 5
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    Name:
      type: string
      pattern: ^[a-zA-Z0-9\s_.,-]+
      minLength: 1
      maxLength: 255
    NextToken:
      type: string
      minLength: 1
      maxLength: 2048
    NonEmptyString:
      type: string
      minLength: 1
      maxLength: 4096
    NotifyRecommendationsReceivedErrorMessage:
      type: string
    Order:
      type: string
      enum:
      - ASC
      - DESC
    Priority:
      type: string
      enum:
      - HIGH
      - MEDIUM
      - LOW
    QueryText:
      type: string
    QuickResponseContent:
      type: string
      minLength: 1
      maxLength: 1024
    QuickResponseDescription:
      type: string
      minLength: 1
      maxLength: 255
    QuickResponseFilterOperator:
      type: string
      enum:
      - EQUALS
      - PREFIX
    QuickResponseFilterValue:
      type: string
      minLength: 1
      maxLength: 2048
    QuickResponseName:
      type: string
      minLength: 1
      maxLength: 40
    QuickResponseQueryOperator:
      type: string
      enum:
      - CONTAINS
      - CONTAINS_AND_PREFIX
    QuickResponseQueryValue:
      type: string
      minLength: 1
      maxLength: 1024
    QuickResponseStatus:
      type: string
      enum:
      - CREATE_IN_PROGRESS
      - CREATE_FAILED
      - CREATED
      - DELETE_IN_PROGRESS
      - DELETE_FAILED
      - DELETED
      - UPDATE_IN_PROGRESS
      - UPDATE_FAILED
    QuickResponseType:
      type: string
      pattern: ^(application/x\.quickresponse;format=(plain|markdown))$
    RecommendationSourceType:
      type: string
      enum:
      - ISSUE_DETECTION
      - RULE_EVALUATION
      - OTHER
    RecommendationTriggerType:
      type: string
      enum:
      - QUERY
    RecommendationType:
      type: string
      enum:
      - KNOWLEDGE_CONTENT
    RelevanceLevel:
      type: string
      enum:
      - HIGH
      - MEDIUM
      - LOW
    SensitiveString:
      type: string
    ShortCutKey:
      type: string
      minLength: 1
      maxLength: 10
    TagKey:
      type: string
      pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 1
      maxLength: 256
    TimeToLive:
      type: integer
      minimum: 1
      maximum: 60
      description: Expiration time in minutes
    UploadId:
      type: string
      minLength: 1
      maxLength: 1200
    Uri:
      type: string
      minLength: 1
      maxLength: 4096
    Url:
      type: string
      minLength: 1
      maxLength: 4096
    Uuid:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
    UuidOrArn:
      type: string
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$|^arn:[a-z-]*?:wisdom:[a-z0-9-]*?:[0-9]{12}:[a-z-]*?/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(?:/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})?$
    WaitTimeSeconds:
      type: integer
      default: 0
      minimum: 0
      maximum: 20
