openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: workdocs
  x-aws-serviceName: workdocs
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2016-05-01'
  title: Amazon WorkDocs
  description: |-
    The Amazon WorkDocs API is designed for the following use cases:

      * File Migration: File migration applications are supported for users who want to migrate their files from an on-premises or off-premises file system or service. Users can insert files into a user directory structure, as well as allow for basic metadata changes, such as modifications to the permissions of files.

      * Security: Support security applications are supported for users who have additional security needs, such as antivirus or data loss prevention. The API actions, along with CloudTrail, allow these applications to detect when changes occur in Amazon WorkDocs. Then, the application can take the necessary actions and replace the target file. If the target file violates the policy, the application can also choose to email the user.

      * eDiscovery/Analytics: General administrative applications are supported, such as eDiscovery and analytics. These applications can choose to mimic or record the actions in an Amazon WorkDocs site, along with CloudTrail, to replicate data for eDiscovery, backup, or analytical applications.

    All Amazon WorkDocs API actions are Amazon authenticated and certificate-signed. They not only require the use of the Amazon Web Services SDK, but also allow for the exclusive use of IAM users and roles to help facilitate access, trust, and permission policies. By creating a role and allowing an IAM user to access the Amazon WorkDocs site, the IAM user gains full administrative visibility into the entire Amazon WorkDocs site (or as set in the IAM policy). This includes, but is not limited to, the ability to modify file permissions and upload any file to any user. This allows developers to perform the three use cases above, as well as give users the ability to grant access on a selective basis using the IAM model.

    The pricing for Amazon WorkDocs APIs varies depending on the API call type for these actions:

      * `READ (Get*)`

      * `WRITE (Activate*, Add*, Create*, Deactivate*, Initiate*, Update*)`

      * `LIST (Describe*)`

      * `DELETE*, CANCEL`

    For information about Amazon WorkDocs API pricing, see [Amazon WorkDocs Pricing](https://aws.amazon.com/workdocs/pricing/).
servers:
- description: The Amazon WorkDocs regional endpoint
  url: https://workdocs.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ActivityNamesFilterType:
      type: string
      pattern: ^[\w,]+$
      minLength: 1
      maxLength: 1024
    ActivityType:
      type: string
      enum:
      - DOCUMENT_CHECKED_IN
      - DOCUMENT_CHECKED_OUT
      - DOCUMENT_RENAMED
      - DOCUMENT_VERSION_UPLOADED
      - DOCUMENT_VERSION_DELETED
      - DOCUMENT_VERSION_VIEWED
      - DOCUMENT_VERSION_DOWNLOADED
      - DOCUMENT_RECYCLED
      - DOCUMENT_RESTORED
      - DOCUMENT_REVERTED
      - DOCUMENT_SHARED
      - DOCUMENT_UNSHARED
      - DOCUMENT_SHARE_PERMISSION_CHANGED
      - DOCUMENT_SHAREABLE_LINK_CREATED
      - DOCUMENT_SHAREABLE_LINK_REMOVED
      - DOCUMENT_SHAREABLE_LINK_PERMISSION_CHANGED
      - DOCUMENT_MOVED
      - DOCUMENT_COMMENT_ADDED
      - DOCUMENT_COMMENT_DELETED
      - DOCUMENT_ANNOTATION_ADDED
      - DOCUMENT_ANNOTATION_DELETED
      - FOLDER_CREATED
      - FOLDER_DELETED
      - FOLDER_RENAMED
      - FOLDER_RECYCLED
      - FOLDER_RESTORED
      - FOLDER_SHARED
      - FOLDER_UNSHARED
      - FOLDER_SHARE_PERMISSION_CHANGED
      - FOLDER_SHAREABLE_LINK_CREATED
      - FOLDER_SHAREABLE_LINK_REMOVED
      - FOLDER_SHAREABLE_LINK_PERMISSION_CHANGED
      - FOLDER_MOVED
    AdditionalResponseFieldType:
      type: string
      enum:
      - WEBURL
    AdditionalResponseFieldsList:
      type: array
      items:
        $ref: '#/components/schemas/AdditionalResponseFieldType'
    AuthenticationHeaderType:
      type: string
      minLength: 1
      maxLength: 8199
    BooleanEnumType:
      type: string
      enum:
      - 'TRUE'
      - 'FALSE'
    BooleanType:
      type: boolean
      default: false
    CommentIdType:
      type: string
      pattern: ^[\w+-.@]+$
      minLength: 1
      maxLength: 128
    CommentList:
      type: array
      items:
        $ref: '#/components/schemas/Comment'
    CommentStatusType:
      type: string
      enum:
      - DRAFT
      - PUBLISHED
      - DELETED
    CommentTextType:
      type: string
      minLength: 1
      maxLength: 2048
    CommentVisibilityType:
      type: string
      enum:
      - PUBLIC
      - PRIVATE
    ContentCategoryType:
      type: string
      enum:
      - IMAGE
      - DOCUMENT
      - PDF
      - SPREADSHEET
      - PRESENTATION
      - AUDIO
      - VIDEO
      - SOURCE_CODE
      - OTHER
    CustomMetadataKeyList:
      type: array
      items:
        $ref: '#/components/schemas/CustomMetadataKeyType'
    CustomMetadataKeyType:
      type: string
      pattern: ^[a-zA-Z0-9._+-/=][a-zA-Z0-9 ._+-/=]*$
      minLength: 1
      maxLength: 56
    CustomMetadataMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/CustomMetadataValueType'
    CustomMetadataValueType:
      type: string
      pattern: ^[a-zA-Z0-9._+-/=][a-zA-Z0-9 ._+-/=]*$
      minLength: 1
      maxLength: 256
    DocumentContentType:
      type: string
      minLength: 1
      maxLength: 128
    DocumentMetadataList:
      type: array
      items:
        $ref: '#/components/schemas/DocumentMetadata'
    DocumentSourceType:
      type: string
      enum:
      - ORIGINAL
      - WITH_COMMENTS
    DocumentSourceUrlMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/UrlType'
    DocumentStatusType:
      type: string
      enum:
      - INITIALIZED
      - ACTIVE
    DocumentThumbnailType:
      type: string
      enum:
      - SMALL
      - SMALL_HQ
      - LARGE
    DocumentThumbnailUrlMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/UrlType'
    DocumentVersionIdType:
      type: string
      pattern: ^[\w+-.@]+$
      minLength: 1
      maxLength: 128
    DocumentVersionMetadataList:
      type: array
      items:
        $ref: '#/components/schemas/DocumentVersionMetadata'
    DocumentVersionStatus:
      type: string
      enum:
      - ACTIVE
    EmailAddressType:
      type: string
      pattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
      minLength: 1
      maxLength: 256
    EntityIdList:
      type: array
      items:
        $ref: '#/components/schemas/IdType'
    ErrorMessageType:
      type: string
    ExceptionCodeType:
      type: string
    FieldNamesType:
      type: string
      pattern: ^[\w,]+$
      minLength: 1
      maxLength: 256
    FolderContentType:
      type: string
      enum:
      - ALL
      - DOCUMENT
      - FOLDER
    FolderMetadataList:
      type: array
      items:
        $ref: '#/components/schemas/FolderMetadata'
    GroupMetadataList:
      type: array
      items:
        $ref: '#/components/schemas/GroupMetadata'
    GroupNameType:
      type: string
    HashType:
      type: string
      pattern: ^[&\w+-.@]+$
      minLength: 0
      maxLength: 128
    HeaderNameType:
      type: string
      pattern: ^[\w-]+$
      minLength: 1
      maxLength: 256
    HeaderValueType:
      type: string
      minLength: 1
      maxLength: 1024
    IdType:
      type: string
      pattern: ^[&\w+-.@]+$
      minLength: 1
      maxLength: 256
    LanguageCodeType:
      type: string
      enum:
      - AR
      - BG
      - BN
      - DA
      - DE
      - CS
      - EL
      - EN
      - ES
      - FA
      - FI
      - FR
      - HI
      - HU
      - ID
      - IT
      - JA
      - KO
      - LT
      - LV
      - NL
      - 'NO'
      - PT
      - RO
      - RU
      - SV
      - SW
      - TH
      - TR
      - ZH
      - DEFAULT
    LimitType:
      type: integer
      minimum: 1
      maximum: 999
    LocaleType:
      type: string
      enum:
      - en
      - fr
      - ko
      - de
      - es
      - ja
      - ru
      - zh_CN
      - zh_TW
      - pt_BR
      - default
    LongType:
      type: integer
      format: int64
    MarkerType:
      type: string
      pattern: ^[\u0000-\u00FF]+$
      minLength: 1
      maxLength: 2048
    MessageType:
      type: string
      minLength: 0
      maxLength: 2048
    NextMarkerType:
      type: string
      pattern: ^[\d]+$
      minLength: 1
      maxLength: 2048
    OrderByFieldType:
      type: string
      enum:
      - RELEVANCE
      - NAME
      - SIZE
      - CREATED_TIMESTAMP
      - MODIFIED_TIMESTAMP
    OrderType:
      type: string
      enum:
      - ASCENDING
      - DESCENDING
    OrganizationUserList:
      type: array
      items:
        $ref: '#/components/schemas/User'
    PageMarkerType:
      type: string
      minLength: 1
      maxLength: 2048
    PasswordType:
      type: string
      pattern: ^[\u0020-\u00FF]+$
      minLength: 4
      maxLength: 32
    PermissionInfoList:
      type: array
      items:
        $ref: '#/components/schemas/PermissionInfo'
    PositiveIntegerType:
      type: integer
      minimum: 1
    PositiveSizeType:
      type: integer
      format: int64
      minimum: 0
    PrincipalList:
      type: array
      items:
        $ref: '#/components/schemas/Principal'
    PrincipalRoleType:
      type: string
      enum:
      - VIEWER
      - CONTRIBUTOR
      - OWNER
      - COOWNER
    PrincipalType:
      type: string
      enum:
      - USER
      - GROUP
      - INVITE
      - ANONYMOUS
      - ORGANIZATION
    ResourceCollectionType:
      type: string
      enum:
      - SHARED_WITH_ME
    ResourceIdType:
      type: string
      pattern: ^[\w+-.@]+$
      minLength: 1
      maxLength: 128
    ResourceNameType:
      type: string
      pattern: ^[\u0020-\u202D\u202F-\uFFFF]+$
      minLength: 1
      maxLength: 255
    ResourcePathComponentList:
      type: array
      items:
        $ref: '#/components/schemas/ResourcePathComponent'
    ResourceSortType:
      type: string
      enum:
      - DATE
      - NAME
    ResourceStateType:
      type: string
      enum:
      - ACTIVE
      - RESTORING
      - RECYCLING
      - RECYCLED
    ResourceType:
      type: string
      enum:
      - FOLDER
      - DOCUMENT
    ResponseItemType:
      type: string
      enum:
      - DOCUMENT
      - FOLDER
      - COMMENT
      - DOCUMENT_VERSION
    ResponseItemWebUrl:
      type: string
      pattern: ^[\u0020-\uFFFF]+$
      minLength: 1
      maxLength: 512
    ResponseItemsList:
      type: array
      items:
        $ref: '#/components/schemas/ResponseItem'
    RolePermissionType:
      type: string
      enum:
      - DIRECT
      - INHERITED
    RoleType:
      type: string
      enum:
      - VIEWER
      - CONTRIBUTOR
      - OWNER
      - COOWNER
    SearchAncestorId:
      type: string
      minLength: 1
      maxLength: 128
    SearchAncestorIdList:
      type: array
      items:
        $ref: '#/components/schemas/SearchAncestorId'
    SearchCollectionType:
      type: string
      enum:
      - OWNED
      - SHARED_WITH_ME
    SearchCollectionTypeList:
      type: array
      items:
        $ref: '#/components/schemas/SearchCollectionType'
    SearchContentCategoryTypeList:
      type: array
      items:
        $ref: '#/components/schemas/ContentCategoryType'
    SearchLabel:
      type: string
      minLength: 1
      maxLength: 128
    SearchLabelList:
      type: array
      items:
        $ref: '#/components/schemas/SearchLabel'
    SearchMarkerType:
      type: string
      pattern: ^[\u0000-\u00FF]+$
      minLength: 1
      maxLength: 12288
    SearchPrincipalRoleList:
      type: array
      items:
        $ref: '#/components/schemas/PrincipalRoleType'
    SearchPrincipalTypeList:
      type: array
      items:
        $ref: '#/components/schemas/SearchPrincipalType'
    SearchQueryScopeType:
      type: string
      enum:
      - NAME
      - CONTENT
    SearchQueryScopeTypeList:
      type: array
      items:
        $ref: '#/components/schemas/SearchQueryScopeType'
    SearchQueryType:
      type: string
      pattern: ^[\u0020-\uFFFF]+$
      minLength: 1
      maxLength: 512
    SearchResourceType:
      type: string
      enum:
      - FOLDER
      - DOCUMENT
      - COMMENT
      - DOCUMENT_VERSION
    SearchResourceTypeList:
      type: array
      items:
        $ref: '#/components/schemas/SearchResourceType'
    SearchResultSortList:
      type: array
      items:
        $ref: '#/components/schemas/SearchSortResult'
    SearchResultsLimitType:
      type: integer
      minimum: 1
      maximum: 100
    SharePrincipalList:
      type: array
      items:
        $ref: '#/components/schemas/SharePrincipal'
    ShareResultsList:
      type: array
      items:
        $ref: '#/components/schemas/ShareResult'
    ShareStatusType:
      type: string
      enum:
      - SUCCESS
      - FAILURE
    SharedLabel:
      type: string
      pattern: ^[a-zA-Z0-9._+-/=][a-zA-Z0-9 ._+-/=]*$
      minLength: 1
      maxLength: 32
    SharedLabels:
      type: array
      items:
        $ref: '#/components/schemas/SharedLabel'
    SignedHeaderMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/HeaderValueType'
    SizeType:
      type: integer
      format: int64
    SortOrder:
      type: string
      enum:
      - ASC
      - DESC
    StorageType:
      type: string
      enum:
      - UNLIMITED
      - QUOTA
    SubscriptionEndPointType:
      type: string
      minLength: 1
      maxLength: 256
    SubscriptionList:
      type: array
      items:
        $ref: '#/components/schemas/Subscription'
    SubscriptionProtocolType:
      type: string
      enum:
      - HTTPS
      - SQS
    SubscriptionType:
      type: string
      enum:
      - ALL
    TextLocaleTypeList:
      type: array
      items:
        $ref: '#/components/schemas/LanguageCodeType'
    TimeZoneIdType:
      type: string
      minLength: 1
      maxLength: 256
    TimestampType:
      type: string
      format: date-time
    UrlType:
      type: string
      minLength: 1
      maxLength: 1024
    UserActivities:
      type: array
      items:
        $ref: '#/components/schemas/Activity'
    UserAttributeValueType:
      type: string
      minLength: 1
      maxLength: 64
    UserFilterType:
      type: string
      enum:
      - ALL
      - ACTIVE_PENDING
    UserIdsType:
      type: string
      pattern: ^[&\w+-.@, ]+$
      minLength: 1
      maxLength: 2000
    UserMetadataList:
      type: array
      items:
        $ref: '#/components/schemas/UserMetadata'
    UserSortType:
      type: string
      enum:
      - USER_NAME
      - FULL_NAME
      - STORAGE_LIMIT
      - USER_STATUS
      - STORAGE_USED
    UserStatusType:
      type: string
      enum:
      - ACTIVE
      - INACTIVE
      - PENDING
    UserType:
      type: string
      enum:
      - USER
      - ADMIN
      - POWERUSER
      - MINIMALUSER
      - WORKSPACESUSER
    UsernameType:
      type: string
      pattern: ^[\w\-+.]+(@[a-zA-Z0-9.\-]+\.[a-zA-Z]+)?$
      minLength: 1
      maxLength: 256
