openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: workspaces_web
  x-aws-serviceName: workspacesweb
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2020-07-08'
  title: Amazon WorkSpaces Web
  description: |-
    Amazon WorkSpaces Secure Browser is a low cost, fully managed WorkSpace built specifically to facilitate secure, web-based workloads. WorkSpaces Secure Browser makes it easy for customers to safely provide their employees with access to internal websites and SaaS web applications without the administrative burden of appliances or specialized client software. WorkSpaces Secure Browser provides simple policy tools tailored for user interactions, while offloading common tasks like capacity management, scaling, and maintaining browser images.
servers:
- description: The Amazon WorkSpaces Web regional endpoint
  url: https://workspaces-web.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ARN:
      type: string
      pattern: ^arn:[\w+=\/,.@-]+:[a-zA-Z0-9\-]+:[a-zA-Z0-9\-]*:[a-zA-Z0-9]{1,12}:[a-zA-Z]+(\/[a-fA-F0-9\-]{36})+$
      minLength: 20
      maxLength: 2048
    AuthenticationType:
      type: string
      enum:
      - Standard
      - IAM_Identity_Center
    BrowserPolicy:
      type: string
      pattern: \{[\S\s]*\}\s*
      minLength: 2
      maxLength: 131072
    BrowserType:
      type: string
      enum:
      - Chrome
    BuiltInPatternId:
      type: string
      pattern: ^[_\-\d\w]+$
      minLength: 1
      maxLength: 50
    CertificatePrincipal:
      type: string
      pattern: ^\S+$
      minLength: 1
      maxLength: 256
    CertificateThumbprint:
      type: string
      pattern: ^[A-Fa-f0-9]{64}$
      minLength: 64
      maxLength: 64
    ClientToken:
      type: string
      minLength: 1
      maxLength: 512
    ConfidenceLevel:
      type: integer
      minimum: 1
      maximum: 3
    CookieDomain:
      type: string
      pattern: ^(\.?)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)*[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$
      minLength: 0
      maxLength: 253
    CookieName:
      type: string
      minLength: 0
      maxLength: 4096
    CookiePath:
      type: string
      pattern: ^/(\S)*$
      minLength: 0
      maxLength: 2000
    Description:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 256
    DescriptionSafe:
      type: string
      pattern: ^[ _\-\d\w]+$
      minLength: 1
      maxLength: 256
    DisconnectTimeoutInMinutes:
      type: integer
      minimum: 1
      maximum: 600
    DisplayName:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 64
    DisplayNameSafe:
      type: string
      pattern: ^[ _\-\d\w]+$
      minLength: 1
      maxLength: 64
    EnabledType:
      type: string
      enum:
      - Disabled
      - Enabled
    ExceptionMessage:
      type: string
    FieldName:
      type: string
    IdentityProviderName:
      type: string
      pattern: ^[^_][\p{L}\p{M}\p{S}\p{N}\p{P}][^_]+$
      minLength: 1
      maxLength: 32
    IdentityProviderType:
      type: string
      enum:
      - SAML
      - Facebook
      - Google
      - LoginWithAmazon
      - SignInWithApple
      - OIDC
    IdleDisconnectTimeoutInMinutes:
      type: integer
      minimum: 0
      maximum: 60
    InlineRedactionUrl:
      type: string
      pattern: ^((([a-zA-Z][a-zA-Z0-9+.-]*):\/\/(\*|[\w%._\-\+~#=@]+)?(\/[^@\s]*)?(?:\?([^*\s]+(?:\*?)))?)|(\*|[\w%._\-\+~#=@]+\.[\w%._\-\+~#=@]+)(?::(\d{1,5}))?(\/[^@\s]*)?(?:\?([^*\s]+(?:\*?)))?|(([a-zA-Z][a-zA-Z0-9+.-]*):(\/\/)?\*))$
    InstanceType:
      type: string
      enum:
      - standard.regular
      - standard.large
      - standard.xlarge
    IpAddress:
      type: string
      pattern: ^((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))$|^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))$
      minLength: 1
      maxLength: 15
    IpRange:
      type: string
      pattern: ^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}(?:/([0-9]|[12][0-9]|3[0-2])|)$
    KinesisStreamArn:
      type: string
      pattern: arn:[\w+=/,.@-]+:kinesis:[a-zA-Z0-9\-]*:[a-zA-Z0-9]{1,12}:stream/.+
      minLength: 20
      maxLength: 2048
    MaxConcurrentSessions:
      type: integer
      minimum: 1
      maximum: 5000
    MaxDisplayResolution:
      type: string
      enum:
      - size4096X2160
      - size3840X2160
      - size3440X1440
      - size2560X1440
      - size1920X1080
      - size1280X720
      - size1024X768
      - size800X600
    MaxResults:
      type: integer
      minimum: 1
    PaginationToken:
      type: string
      pattern: ^\S+$
      minLength: 1
      maxLength: 2048
    PatternName:
      type: string
      pattern: ^[_\-\d\w]+$
      minLength: 1
      maxLength: 20
    PortalEndpoint:
      type: string
      pattern: ^[a-zA-Z0-9]?((?!-)([A-Za-z0-9-]*[A-Za-z0-9])\.)+[a-zA-Z0-9]+$
      minLength: 1
      maxLength: 253
    PortalId:
      type: string
      pattern: ^[a-zA-Z0-9\-]+$
      minLength: 36
      maxLength: 36
    PortalStatus:
      type: string
      enum:
      - Incomplete
      - Pending
      - Active
    QuotaCode:
      type: string
    RedactionPlaceHolderText:
      type: string
      pattern: ^[*_\-\d\w]+$
      minLength: 1
      maxLength: 20
    RedactionPlaceHolderType:
      type: string
      enum:
      - CustomText
    Regex:
      type: string
      pattern: ^\/((?:[^\n])+)\/([gimsuyvd]{0,8})$
      minLength: 0
      maxLength: 300
    RendererType:
      type: string
      enum:
      - AppStream
    ResourceId:
      type: string
    ResourceType:
      type: string
    RetryAfterSeconds:
      type: integer
      default: 0
    SamlMetadata:
      type: string
      pattern: ^.+$
      minLength: 1
      maxLength: 204800
    SecurityGroupId:
      type: string
      pattern: ^[\w+\-]+$
      minLength: 1
      maxLength: 128
    ServiceCode:
      type: string
    SessionId:
      type: string
      pattern: ^[a-zA-Z0-9\-]+$
      minLength: 36
      maxLength: 36
    StatusReason:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 1024
    StringType:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 131072
    SubnetId:
      type: string
      pattern: ^subnet-([0-9a-f]{8}|[0-9a-f]{17})$
      minLength: 1
      maxLength: 32
    SubresourceARN:
      type: string
      pattern: ^arn:[\w+=\/,.@-]+:[a-zA-Z0-9\-]+:[a-zA-Z0-9\-]*:[a-zA-Z0-9]{1,12}:[a-zA-Z]+(\/[a-fA-F0-9\-]{36}){2,}$
      minLength: 20
      maxLength: 2048
    TagExceptionMessage:
      type: string
    TagKey:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
      minLength: 0
      maxLength: 256
    ToolbarItem:
      type: string
      enum:
      - Windows
      - DualMonitor
      - FullScreen
      - Webcam
      - Microphone
    ToolbarType:
      type: string
      enum:
      - Floating
      - Docked
    Username:
      type: string
      pattern: ^[\s\S]*$
      minLength: 0
      maxLength: 256
    ValidationExceptionReason:
      type: string
      enum:
      - unknownOperation
      - cannotParse
      - fieldValidationFailed
      - other
    VisualMode:
      type: string
      enum:
      - Dark
      - Light
    VpcId:
      type: string
      pattern: ^vpc-[0-9a-z]*$
      minLength: 1
      maxLength: 255
    keyArn:
      type: string
      pattern: ^arn:[\w+=\/,.@-]+:kms:[a-zA-Z0-9\-]*:[a-zA-Z0-9]{1,12}:key\/[a-zA-Z0-9-]+$
      minLength: 20
      maxLength: 2048
