openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: workspaces_thin_client
  x-aws-serviceName: workspacesthinclient
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2023-08-22'
  title: Amazon WorkSpaces Thin Client
  description: |-
    Amazon WorkSpaces Thin Client is an affordable device built to work with Amazon Web Services End User Computing (EUC) virtual desktops to provide users with a complete cloud desktop solution. WorkSpaces Thin Client is a compact device designed to connect up to two monitors and USB devices like a keyboard, mouse, headset, and webcam. To maximize endpoint security, WorkSpaces Thin Client devices do not allow local data storage or installation of unapproved applications. The WorkSpaces Thin Client device ships preloaded with device management software.

    You can use these APIs to complete WorkSpaces Thin Client tasks, such as creating environments or viewing devices. For more information about WorkSpaces Thin Client, including the required permissions to use the service, see the [Amazon WorkSpaces Thin Client Administrator Guide](https://docs.aws.amazon.com/workspaces-thin-client/latest/ag/). For more information about using the Command Line Interface (CLI) to manage your WorkSpaces Thin Client resources, see the [WorkSpaces Thin Client section of the CLI Reference](https://docs.aws.amazon.com/cli/latest/reference/workspaces-thin-client/index.html).
servers:
- description: The Amazon WorkSpaces Thin Client regional endpoint
  url: https://thinclient.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ActivationCode:
      type: string
      pattern: ^[a-z]{2}[a-z0-9]{6}$
    ApplyTimeOf:
      type: string
      enum:
      - UTC
      - DEVICE
    Arn:
      type: string
      pattern: ^arn:[\w+=\/,.@-]+:[a-zA-Z0-9\-]+:[a-zA-Z0-9\-]*:[0-9]{0,12}:[a-zA-Z0-9\-\/\._]+$
      minLength: 20
      maxLength: 2048
    ClientToken:
      type: string
      minLength: 1
      maxLength: 512
    DayOfWeek:
      type: string
      enum:
      - MONDAY
      - TUESDAY
      - WEDNESDAY
      - THURSDAY
      - FRIDAY
      - SATURDAY
      - SUNDAY
    DayOfWeekList:
      type: array
      items:
        $ref: '#/components/schemas/DayOfWeek'
    DesktopEndpoint:
      type: string
      pattern: ^(https:\/\/)[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,32}(:[0-9]{1,5})?(\/.*)?$
      minLength: 1
      maxLength: 1024
    DesktopType:
      type: string
      enum:
      - workspaces
      - appstream
      - workspaces-web
    DeviceCreationTagKey:
      type: string
      pattern: ^(?!aws:)[A-Za-z0-9 _=@:.+-/]+$
      minLength: 1
      maxLength: 128
    DeviceCreationTagValue:
      type: string
      pattern: ^[A-Za-z0-9 _=@:.+-/]+$
      minLength: 0
      maxLength: 256
    DeviceCreationTagsMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/DeviceCreationTagValue'
    DeviceId:
      type: string
      pattern: ^[a-zA-Z0-9]{24}$
    DeviceList:
      type: array
      items:
        $ref: '#/components/schemas/DeviceSummary'
    DeviceName:
      type: string
      pattern: ^$|^[0-9\p{IsAlphabetic}+:,.@'" -]*$
      maxLength: 64
    DeviceSoftwareSetComplianceStatus:
      type: string
      enum:
      - NONE
      - COMPLIANT
      - NOT_COMPLIANT
    DeviceStatus:
      type: string
      enum:
      - REGISTERED
      - DEREGISTERING
      - DEREGISTERED
      - ARCHIVED
    EnvironmentId:
      type: string
      pattern: ^[a-z0-9]{9}$
    EnvironmentList:
      type: array
      items:
        $ref: '#/components/schemas/EnvironmentSummary'
    EnvironmentName:
      type: string
      pattern: ^$|^[0-9\p{IsAlphabetic}+:,.@'" -][0-9\p{IsAlphabetic}+=:,.@'" -]*$
      maxLength: 64
    EnvironmentSoftwareSetComplianceStatus:
      type: string
      enum:
      - NO_REGISTERED_DEVICES
      - COMPLIANT
      - NOT_COMPLIANT
    ExceptionMessage:
      type: string
    FieldName:
      type: string
    Hour:
      type: integer
      minimum: 0
      maximum: 23
    KmsKeyArn:
      type: string
      pattern: ^arn:[\w+=\/,.@-]+:kms:[a-zA-Z0-9\-]*:[0-9]{0,12}:key\/[a-zA-Z0-9-]+$
      minLength: 20
      maxLength: 2048
    MaintenanceWindowType:
      type: string
      enum:
      - SYSTEM
      - CUSTOM
    MaxResults:
      type: integer
      minimum: 1
      maximum: 50
    Minute:
      type: integer
      minimum: 0
      maximum: 59
    PaginationToken:
      type: string
      pattern: ^\S*$
      minLength: 0
      maxLength: 2048
    QuotaCode:
      type: string
    ResourceId:
      type: string
    ResourceType:
      type: string
    RetryAfterSeconds:
      type: integer
    ServiceCode:
      type: string
    SoftwareList:
      type: array
      items:
        $ref: '#/components/schemas/Software'
    SoftwareSetId:
      type: string
      pattern: ^[0-9]{1,9}$
    SoftwareSetIdOrEmptyString:
      type: string
      pattern: ^[0-9]{0,9}$
    SoftwareSetList:
      type: array
      items:
        $ref: '#/components/schemas/SoftwareSetSummary'
    SoftwareSetUpdateMode:
      type: string
      enum:
      - USE_LATEST
      - USE_DESIRED
    SoftwareSetUpdateSchedule:
      type: string
      enum:
      - USE_MAINTENANCE_WINDOW
      - APPLY_IMMEDIATELY
    SoftwareSetUpdateStatus:
      type: string
      enum:
      - AVAILABLE
      - IN_PROGRESS
      - UP_TO_DATE
    SoftwareSetValidationStatus:
      type: string
      enum:
      - VALIDATED
      - NOT_VALIDATED
    TagKeys:
      type: array
      items:
        type: string
      x-sensitive: true
    TagsMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/String'
    TargetDeviceStatus:
      type: string
      enum:
      - DEREGISTERED
      - ARCHIVED
    Timestamp:
      type: string
      format: date-time
    ValidationExceptionFieldList:
      type: array
      items:
        $ref: '#/components/schemas/ValidationExceptionField'
    ValidationExceptionReason:
      type: string
      enum:
      - unknownOperation
      - cannotParse
      - fieldValidationFailed
      - other
