openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: workdocs
  x-aws-serviceName: workdocs
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2016-05-01'
  title: Amazon WorkDocs
  description: |-
    The Amazon WorkDocs API is designed for the following use cases:

      * File Migration: File migration applications are supported for users who want to migrate their files from an on-premises or off-premises file system or service. Users can insert files into a user directory structure, as well as allow for basic metadata changes, such as modifications to the permissions of files.

      * Security: Support security applications are supported for users who have additional security needs, such as antivirus or data loss prevention. The API actions, along with CloudTrail, allow these applications to detect when changes occur in Amazon WorkDocs. Then, the application can take the necessary actions and replace the target file. If the target file violates the policy, the application can also choose to email the user.

      * eDiscovery/Analytics: General administrative applications are supported, such as eDiscovery and analytics. These applications can choose to mimic or record the actions in an Amazon WorkDocs site, along with CloudTrail, to replicate data for eDiscovery, backup, or analytical applications.

    All Amazon WorkDocs API actions are Amazon authenticated and certificate-signed. They not only require the use of the Amazon Web Services SDK, but also allow for the exclusive use of IAM users and roles to help facilitate access, trust, and permission policies. By creating a role and allowing an IAM user to access the Amazon WorkDocs site, the IAM user gains full administrative visibility into the entire Amazon WorkDocs site (or as set in the IAM policy). This includes, but is not limited to, the ability to modify file permissions and upload any file to any user. This allows developers to perform the three use cases above, as well as give users the ability to grant access on a selective basis using the IAM model.

    The pricing for Amazon WorkDocs APIs varies depending on the API call type for these actions:

      * `READ (Get*)`

      * `WRITE (Activate*, Add*, Create*, Deactivate*, Initiate*, Update*)`

      * `LIST (Describe*)`

      * `DELETE*, CANCEL`

    For information about Amazon WorkDocs API pricing, see [Amazon WorkDocs Pricing](https://aws.amazon.com/workdocs/pricing/).
servers:
- description: The Amazon WorkDocs regional endpoint
  url: https://workdocs.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    ActivityNamesFilterType:
      type: string
      pattern: ^[\w,]+$
      minLength: 1
      maxLength: 1024
    AuthenticationHeaderType:
      type: string
      minLength: 1
      maxLength: 8199
    BooleanType:
      type: boolean
      default: false
    CommentIdType:
      type: string
      pattern: ^[\w+-.@]+$
      minLength: 1
      maxLength: 128
    CommentTextType:
      type: string
      minLength: 1
      maxLength: 2048
    CustomMetadataKeyType:
      type: string
      pattern: ^[a-zA-Z0-9._+-/=][a-zA-Z0-9 ._+-/=]*$
      minLength: 1
      maxLength: 56
    CustomMetadataValueType:
      type: string
      pattern: ^[a-zA-Z0-9._+-/=][a-zA-Z0-9 ._+-/=]*$
      minLength: 1
      maxLength: 256
    DocumentContentType:
      type: string
      minLength: 1
      maxLength: 128
    DocumentVersionIdType:
      type: string
      pattern: ^[\w+-.@]+$
      minLength: 1
      maxLength: 128
    EmailAddressType:
      type: string
      pattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
      minLength: 1
      maxLength: 256
    ErrorMessageType:
      type: string
    ExceptionCodeType:
      type: string
    FieldNamesType:
      type: string
      pattern: ^[\w,]+$
      minLength: 1
      maxLength: 256
    GroupNameType:
      type: string
    HashType:
      type: string
      pattern: ^[&\w+-.@]+$
      minLength: 0
      maxLength: 128
    HeaderNameType:
      type: string
      pattern: ^[\w-]+$
      minLength: 1
      maxLength: 256
    HeaderValueType:
      type: string
      minLength: 1
      maxLength: 1024
    IdType:
      type: string
      pattern: ^[&\w+-.@]+$
      minLength: 1
      maxLength: 256
    LimitType:
      type: integer
      minimum: 1
      maximum: 999
    MarkerType:
      type: string
      pattern: ^[\u0000-\u00FF]+$
      minLength: 1
      maxLength: 2048
    MessageType:
      type: string
      minLength: 0
      maxLength: 2048
    NextMarkerType:
      type: string
      pattern: ^[\d]+$
      minLength: 1
      maxLength: 2048
    PageMarkerType:
      type: string
      minLength: 1
      maxLength: 2048
    PasswordType:
      type: string
      pattern: ^[\u0020-\u00FF]+$
      minLength: 4
      maxLength: 32
    PositiveIntegerType:
      type: integer
      minimum: 1
    ResourceIdType:
      type: string
      pattern: ^[\w+-.@]+$
      minLength: 1
      maxLength: 128
    ResourceNameType:
      type: string
      pattern: ^[\u0020-\u202D\u202F-\uFFFF]+$
      minLength: 1
      maxLength: 255
    ResponseItemWebUrl:
      type: string
      pattern: ^[\u0020-\uFFFF]+$
      minLength: 1
      maxLength: 512
    SearchAncestorId:
      type: string
      minLength: 1
      maxLength: 128
    SearchLabel:
      type: string
      minLength: 1
      maxLength: 128
    SearchMarkerType:
      type: string
      pattern: ^[\u0000-\u00FF]+$
      minLength: 1
      maxLength: 12288
    SearchQueryType:
      type: string
      pattern: ^[\u0020-\uFFFF]+$
      minLength: 1
      maxLength: 512
    SearchResultsLimitType:
      type: integer
      minimum: 1
      maximum: 100
    SharedLabel:
      type: string
      pattern: ^[a-zA-Z0-9._+-/=][a-zA-Z0-9 ._+-/=]*$
      minLength: 1
      maxLength: 32
    SubscriptionEndPointType:
      type: string
      minLength: 1
      maxLength: 256
    TimeZoneIdType:
      type: string
      minLength: 1
      maxLength: 256
    UrlType:
      type: string
      minLength: 1
      maxLength: 1024
    UserAttributeValueType:
      type: string
      minLength: 1
      maxLength: 64
    UserIdsType:
      type: string
      pattern: ^[&\w+-.@, ]+$
      minLength: 1
      maxLength: 2000
    UsernameType:
      type: string
      pattern: ^[\w\-+.]+(@[a-zA-Z0-9.\-]+\.[a-zA-Z]+)?$
      minLength: 1
      maxLength: 256
