openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  x-stackql-serviceName: xray
  x-aws-serviceName: xray
  x-aws-protocol: aws.protocols#restJson1
  x-dateGenerated: '2025-05-05'
  version: '2016-04-12'
  title: AWS X-Ray
  description: |-
    Amazon Web Services X-Ray provides APIs for managing debug traces and retrieving service maps and other data created by processing those traces.
servers:
- description: The AWS X-Ray regional endpoint
  url: https://xray.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
paths: {}
components:
  schemas:
    AmazonResourceName:
      type: string
      minLength: 1
      maxLength: 1011
    AnnotationKey:
      type: string
    AttributeKey:
      type: string
      minLength: 1
      maxLength: 32
    AttributeValue:
      type: string
      minLength: 1
      maxLength: 32
    Boolean:
      type: boolean
      default: false
    BorrowCount:
      type: integer
      default: 0
      minimum: 0
    ClientID:
      type: string
      minLength: 24
      maxLength: 24
    EC2InstanceId:
      type: string
      minLength: 0
      maxLength: 20
    EncryptionKeyId:
      type: string
      minLength: 1
      maxLength: 3000
    EntitySelectorExpression:
      type: string
      minLength: 1
      maxLength: 500
    ErrorMessage:
      type: string
    EventSummaryText:
      type: string
    FilterExpression:
      type: string
    GetGroupsNextToken:
      type: string
      minLength: 1
      maxLength: 100
    GetInsightEventsMaxResults:
      type: integer
      minimum: 1
      maximum: 50
    GetInsightSummariesMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    GroupARN:
      type: string
      minLength: 1
      maxLength: 400
    GroupName:
      type: string
      minLength: 1
      maxLength: 32
    HTTPMethod:
      type: string
      minLength: 0
      maxLength: 10
    Host:
      type: string
      minLength: 0
      maxLength: 64
    Hostname:
      type: string
      minLength: 0
      maxLength: 255
    InsightId:
      type: string
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
    InsightSummaryText:
      type: string
    Integer:
      type: integer
      default: 0
    NullableBoolean:
      type: boolean
    NullableInteger:
      type: integer
    PolicyDocument:
      type: string
    PolicyName:
      type: string
      pattern: ^[\w+=,.@-]+$
      minLength: 1
      maxLength: 128
    PolicyRevisionId:
      type: string
    Priority:
      type: integer
      minimum: 1
      maximum: 9999
    RequestCount:
      type: integer
      default: 0
      minimum: 0
    ReservoirSize:
      type: integer
      default: 0
      minimum: 0
    ResourceARN:
      type: string
      minLength: 0
      maxLength: 500
    ResourcePolicyNextToken:
      type: string
      minLength: 1
      maxLength: 100
    RetrievalToken:
      type: string
      minLength: 0
      maxLength: 1020
    RuleName:
      type: string
      minLength: 1
      maxLength: 32
    SampledCount:
      type: integer
      default: 0
      minimum: 0
    SegmentDocument:
      type: string
      minLength: 1
    SegmentId:
      type: string
    ServiceName:
      type: string
      minLength: 0
      maxLength: 64
    ServiceType:
      type: string
      minLength: 0
      maxLength: 64
    SpanDocument:
      type: string
      minLength: 0
      maxLength: 204800
    SpanId:
      type: string
      minLength: 1
      maxLength: 16
    String:
      type: string
    TagKey:
      type: string
      minLength: 1
      maxLength: 128
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    Token:
      type: string
      minLength: 1
      maxLength: 2000
    TraceId:
      type: string
      minLength: 1
      maxLength: 35
    TraceSegmentDocument:
      type: string
    URLPath:
      type: string
      minLength: 0
      maxLength: 128
    Version:
      type: integer
      minimum: 1
